<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://schemata.jklnet.org/Decompiler">
  <input>
    <address>1000:0000</address>
  </input>
  <output>
    <disassembly>foo.asm</disassembly>
    <intermediate-code>foo.cod</intermediate-code>
  </output>
  <procedure name="foo">
    <signature>
      <return>
        <reg>eax</reg>
      </return>
      <arg>
        <prim domain="SignedInt" size="4" />
        <stack />
      </arg>
      <arg>
        <prim domain="SignedInt" size="4" />
        <stack />
      </arg>
    </signature>
    <address>1000:0010</address>
  </procedure>
</project>
