// test.globals.c
// Generated by decompiling test
// using Reko decompiler version 0.9.3.0.

#include "test.h"

<anonymous> * g_ptr20A24;
ptr32 g_ptr20A4C;
word32 g_dw20A60;
<anonymous> g_tFFFFFFFF;
