// retpoline_stripped.h
// Generated by decompiling retpoline_stripped.elf
// using Reko decompiler version 0.7.2.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (400660 Eq_28 t400660) (400710 Eq_31 t400710) (400780 Eq_32 t400780) (600FF8 word64 qw600FF8))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_16: (union "Eq_16" (word32 u0) ((ptr code) u1))
	T_16 (in eax : word32)
Eq_17: (fn void ())
	T_17 (in rdx : (ptr Eq_17))
	T_33 (in rtld_fini : (ptr (fn void ())))
Eq_18: (union "Eq_18" (int32 u0) (word64 u1))
	T_18 (in qwArg00 : Eq_18)
	T_29 (in argc : int32)
Eq_19: (fn void (ptr64))
	T_19 (in __align : ptr64)
	T_20 (in signature of __align : void)
Eq_26: (fn int32 ((ptr Eq_28), Eq_18, (ptr (ptr char)), (ptr Eq_31), (ptr Eq_32), (ptr Eq_17), (ptr void)))
	T_26 (in __libc_start_main : ptr64)
	T_27 (in signature of __libc_start_main : void)
Eq_28: (fn int32 (int32, (ptr (ptr char)), (ptr (ptr char))))
	T_28 (in main : (ptr (fn int32 (int32, (ptr (ptr char)), (ptr (ptr char))))))
	T_35 (in 0x0000000000400660 : word64)
Eq_31: (fn void ())
	T_31 (in init : (ptr (fn void ())))
	T_37 (in 0x0000000000400710 : word64)
Eq_32: (fn void ())
	T_32 (in fini : (ptr (fn void ())))
	T_38 (in 0x0000000000400780 : word64)
Eq_41: (fn void ())
	T_41 (in __hlt : ptr64)
	T_42 (in signature of __hlt : void)
Eq_61: (union "Eq_61" (word32 u0) ((ptr code) u1))
	T_61 (in eax : word32)
Eq_64: (fn (ptr void) (Eq_66, Eq_66))
	T_64 (in calloc : ptr64)
	T_65 (in signature of calloc : void)
Eq_66: (union "Eq_66" (int64 u0) (size_t u1))
	T_66 (in num : size_t)
	T_67 (in size : size_t)
	T_68 (in (int64) edi : int64)
	T_69 (in (int64) esi : int64)
Eq_71: (fn void (word64))
	T_71 (in fn0000000000400700 : ptr64)
	T_72 (in signature of fn0000000000400700 : void)
Eq_76: (fn void ())
	T_76 (in __pause : ptr64)
	T_77 (in signature of __pause : void)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in rax_4 : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_3: (in 0000000000600FF8 : ptr64)
  Class: Eq_3
  DataType: (ptr word64)
  OrigDataType: (ptr (struct (0 T_6 t0000)))
T_4: (in 0x0000000000000000 : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_5: (in 0x0000000000600FF8 + 0x0000000000000000 : word64)
  Class: Eq_5
  DataType: ptr64
  OrigDataType: ptr64
T_6: (in Mem0[0x0000000000600FF8 + 0x0000000000000000:word64] : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_7: (in 0x0000000000000000 : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_8: (in rax_4 == 0x0000000000000000 : bool)
  Class: Eq_8
  DataType: bool
  OrigDataType: bool
T_9: (in rsp_17 : word64)
  Class: Eq_9
  DataType: word64
  OrigDataType: word64
T_10: (in SCZO_18 : byte)
  Class: Eq_10
  DataType: byte
  OrigDataType: byte
T_11: (in rax_19 : word64)
  Class: Eq_11
  DataType: word64
  OrigDataType: word64
T_12: (in SZO_20 : byte)
  Class: Eq_12
  DataType: byte
  OrigDataType: byte
T_13: (in C_21 : byte)
  Class: Eq_13
  DataType: byte
  OrigDataType: byte
T_14: (in Z_22 : byte)
  Class: Eq_14
  DataType: byte
  OrigDataType: byte
T_15: (in eax_23 : word32)
  Class: Eq_15
  DataType: word32
  OrigDataType: word32
T_16: (in eax : word32)
  Class: Eq_16
  DataType: Eq_16
  OrigDataType: (union (word32 u0) ((ptr code) u1))
T_17: (in rdx : (ptr Eq_17))
  Class: Eq_17
  DataType: (ptr Eq_17)
  OrigDataType: (ptr (fn void ()))
T_18: (in qwArg00 : Eq_18)
  Class: Eq_18
  DataType: Eq_18
  OrigDataType: (union (int32 u1) (word64 u0))
T_19: (in __align : ptr64)
  Class: Eq_19
  DataType: (ptr Eq_19)
  OrigDataType: (ptr (fn T_25 (T_24)))
T_20: (in signature of __align : void)
  Class: Eq_19
  DataType: (ptr Eq_19)
  OrigDataType: 
T_21: (in  : word64)
  Class: Eq_21
  DataType: ptr64
  OrigDataType: 
T_22: (in fp : ptr64)
  Class: Eq_22
  DataType: ptr64
  OrigDataType: ptr64
T_23: (in 0x0000000000000008 : word64)
  Class: Eq_23
  DataType: int64
  OrigDataType: int64
T_24: (in fp + 0x0000000000000008 : word64)
  Class: Eq_21
  DataType: ptr64
  OrigDataType: ptr64
T_25: (in __align(fp + 0x0000000000000008) : void)
  Class: Eq_25
  DataType: void
  OrigDataType: void
T_26: (in __libc_start_main : ptr64)
  Class: Eq_26
  DataType: (ptr Eq_26)
  OrigDataType: (ptr (fn T_40 (T_35, T_18, T_36, T_37, T_38, T_17, T_39)))
T_27: (in signature of __libc_start_main : void)
  Class: Eq_26
  DataType: (ptr Eq_26)
  OrigDataType: 
T_28: (in main : (ptr (fn int32 (int32, (ptr (ptr char)), (ptr (ptr char))))))
  Class: Eq_28
  DataType: (ptr Eq_28)
  OrigDataType: 
T_29: (in argc : int32)
  Class: Eq_18
  DataType: Eq_18
  OrigDataType: 
T_30: (in ubp_av : (ptr (ptr char)))
  Class: Eq_30
  DataType: (ptr (ptr char))
  OrigDataType: 
T_31: (in init : (ptr (fn void ())))
  Class: Eq_31
  DataType: (ptr Eq_31)
  OrigDataType: 
T_32: (in fini : (ptr (fn void ())))
  Class: Eq_32
  DataType: (ptr Eq_32)
  OrigDataType: 
T_33: (in rtld_fini : (ptr (fn void ())))
  Class: Eq_17
  DataType: (ptr Eq_17)
  OrigDataType: 
T_34: (in stack_end : (ptr void))
  Class: Eq_34
  DataType: (ptr void)
  OrigDataType: 
T_35: (in 0x0000000000400660 : word64)
  Class: Eq_28
  DataType: (ptr Eq_28)
  OrigDataType: (ptr (fn int32 (int32, (ptr (ptr char)), (ptr (ptr char)))))
T_36: (in fp + 0x0000000000000008 : word64)
  Class: Eq_30
  DataType: (ptr (ptr char))
  OrigDataType: (ptr (ptr char))
T_37: (in 0x0000000000400710 : word64)
  Class: Eq_31
  DataType: (ptr Eq_31)
  OrigDataType: (ptr (fn void ()))
T_38: (in 0x0000000000400780 : word64)
  Class: Eq_32
  DataType: (ptr Eq_32)
  OrigDataType: (ptr (fn void ()))
T_39: (in ptrLoc04 : (ptr void))
  Class: Eq_34
  DataType: (ptr void)
  OrigDataType: (ptr void)
T_40: (in __libc_start_main(&globals->t400660, qwArg00, fp + 0x0000000000000008, &globals->t400710, &globals->t400780, rdx, ptrLoc04) : int32)
  Class: Eq_40
  DataType: int32
  OrigDataType: int32
T_41: (in __hlt : ptr64)
  Class: Eq_41
  DataType: (ptr Eq_41)
  OrigDataType: (ptr (fn T_43 ()))
T_42: (in signature of __hlt : void)
  Class: Eq_41
  DataType: (ptr Eq_41)
  OrigDataType: 
T_43: (in __hlt() : void)
  Class: Eq_43
  DataType: void
  OrigDataType: void
T_44: (in r8 : word64)
  Class: Eq_44
  DataType: word64
  OrigDataType: word64
T_45: (in 0x0000000000601040 : word64)
  Class: Eq_44
  DataType: word64
  OrigDataType: word64
T_46: (in r8 == 0x0000000000601040 : bool)
  Class: Eq_46
  DataType: bool
  OrigDataType: bool
T_47: (in 0x0000000000000000 : uint64)
  Class: Eq_47
  DataType: uint64
  OrigDataType: uint64
T_48: (in 0x0000000000000000 : word64)
  Class: Eq_47
  DataType: uint64
  OrigDataType: word64
T_49: (in 0x0000000000000000 == 0x0000000000000000 : bool)
  Class: Eq_49
  DataType: bool
  OrigDataType: bool
T_50: (in rsp_39 : word64)
  Class: Eq_50
  DataType: word64
  OrigDataType: word64
T_51: (in rbp_40 : word64)
  Class: Eq_51
  DataType: word64
  OrigDataType: word64
T_52: (in eax_41 : word32)
  Class: Eq_52
  DataType: word32
  OrigDataType: word32
T_53: (in rax_42 : word64)
  Class: Eq_53
  DataType: word64
  OrigDataType: word64
T_54: (in r8_43 : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: word64
T_55: (in SCZO_44 : byte)
  Class: Eq_55
  DataType: byte
  OrigDataType: byte
T_56: (in Z_45 : byte)
  Class: Eq_56
  DataType: byte
  OrigDataType: byte
T_57: (in SZO_46 : byte)
  Class: Eq_57
  DataType: byte
  OrigDataType: byte
T_58: (in C_47 : byte)
  Class: Eq_58
  DataType: byte
  OrigDataType: byte
T_59: (in edi_48 : word32)
  Class: Eq_59
  DataType: word32
  OrigDataType: word32
T_60: (in rdi_49 : word64)
  Class: Eq_60
  DataType: word64
  OrigDataType: word64
T_61: (in eax : word32)
  Class: Eq_61
  DataType: Eq_61
  OrigDataType: (union (word32 u0) ((ptr code) u1))
T_62: (in esi : word32)
  Class: Eq_62
  DataType: word32
  OrigDataType: word32
T_63: (in edi : word32)
  Class: Eq_63
  DataType: word32
  OrigDataType: word32
T_64: (in calloc : ptr64)
  Class: Eq_64
  DataType: (ptr Eq_64)
  OrigDataType: (ptr (fn T_70 (T_68, T_69)))
T_65: (in signature of calloc : void)
  Class: Eq_64
  DataType: (ptr Eq_64)
  OrigDataType: 
T_66: (in num : size_t)
  Class: Eq_66
  DataType: Eq_66
  OrigDataType: 
T_67: (in size : size_t)
  Class: Eq_66
  DataType: Eq_66
  OrigDataType: 
T_68: (in (int64) edi : int64)
  Class: Eq_66
  DataType: Eq_66
  OrigDataType: (union (int64 u0) (size_t u1))
T_69: (in (int64) esi : int64)
  Class: Eq_66
  DataType: Eq_66
  OrigDataType: (union (int64 u0) (size_t u1))
T_70: (in calloc((int64) edi, (int64) esi) : (ptr void))
  Class: Eq_70
  DataType: (ptr void)
  OrigDataType: (ptr void)
T_71: (in fn0000000000400700 : ptr64)
  Class: Eq_71
  DataType: (ptr Eq_71)
  OrigDataType: (ptr (fn T_75 (T_74)))
T_72: (in signature of fn0000000000400700 : void)
  Class: Eq_71
  DataType: (ptr Eq_71)
  OrigDataType: 
T_73: (in qwArg00 : word64)
  Class: Eq_73
  DataType: word64
  OrigDataType: word64
T_74: (in qwLoc08 : word64)
  Class: Eq_73
  DataType: word64
  OrigDataType: word64
T_75: (in fn0000000000400700(qwLoc08) : void)
  Class: Eq_75
  DataType: void
  OrigDataType: void
T_76: (in __pause : ptr64)
  Class: Eq_76
  DataType: (ptr Eq_76)
  OrigDataType: (ptr (fn T_78 ()))
T_77: (in signature of __pause : void)
  Class: Eq_76
  DataType: (ptr Eq_76)
  OrigDataType: 
T_78: (in __pause() : void)
  Class: Eq_78
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
	Eq_28 t400660;	// 400660
	Eq_31 t400710;	// 400710
	Eq_32 t400780;	// 400780
	word64 qw600FF8;	// 600FF8
} Eq_1;

typedef union Eq_16 {
	word32 u0;
	<anonymous> * u1;
} Eq_16;

typedef void (Eq_17)();

typedef union Eq_18 {
	int32 u0;
	word64 u1;
} Eq_18;

typedef void (Eq_19)(ptr64);

typedef int32 (Eq_26)( *, Eq_18, char * *,  *,  *,  *, void);

typedef int32 (Eq_28)(int32 rdi, char * * rsi, char * * rdx);

typedef void (Eq_31)();

typedef void (Eq_32)();

typedef void (Eq_41)();

typedef union Eq_61 {
	word32 u0;
	<anonymous> * u1;
} Eq_61;

typedef void (Eq_64)(Eq_66, Eq_66);

typedef union Eq_66 {
	int64 u0;
	size_t u1;
} Eq_66;

typedef void (Eq_71)(word64);

typedef void (Eq_76)();

