// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem9[ds:0x0064:word16]) = fn0C00_000F(0x0064)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_000F
word16 fn0C00_000F(word16 wArg00)
fn0C00_000F_entry:		// block 0, pred:
	// succ:  1
l0C00_000F:		// block 1, pred: 0
	word16 ax_18
	word16 ax_14 = wArg00 - 0x0001
	branch ax_14 == 0x0000 l0C00_0026
	// succ:  3 2
l0C00_0026:		// block 2, pred: 1
	ax_18 = 0x0001
	// succ:  4
l0C00_0018:		// block 3, pred: 1
	ax_18 = (word16) (wArg00 *s fn0C00_000F(ax_14)) (alias)
	// succ:  4
l0C00_0029:		// block 4, pred: 3 2
	return ax_18
	// succ:  5
fn0C00_000F_exit:		// block 5, pred: 4
	// succ: 

T_2 (in fn0C00_000F : ptr32)
	trait_func(T_5 -> T_6)
T_4 (in wArg00 : word16)
	trait_primitive(word16)
	trait_primitive(word16)
T_5 (in 0x0064 : word16)
	trait_primitive(word16)
	trait_equal(T_4)
T_6 (in fn0C00_000F(0x0064) : word16)
	trait_primitive(word16)
	trait_equal(T_10)
T_7 (in ds : selector)
	trait_primitive(selector)
	trait_mem(T_9, 64)
T_8 (in 0x0064 : word16)
	trait_primitive(word16)
	trait_mem(T_7:T_9, 0)
T_9 (in Mem9[ds:0x0064:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_6)
T_10 (in ax : word16)
	trait_primitive(word16)
	trait_equal(T_11)
T_11 (in ax_18 : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_18)
	trait_primitive(word16)
	trait_equal(T_22)
	trait_primitive(word16)
T_12 (in ax_14 : word16)
	trait_primitive(word16)
	trait_equal(T_15)
	trait_primitive(word16)
	trait_equal(T_16)
	trait_primitive(word16)
	trait_equal(T_4)
T_13 (in wArg00 : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_14 (in 0x0001 : word16)
	trait_primitive(word16)
T_15 (in wArg00 - 0x0001 : word16)
	trait_primitive(word16)
T_16 (in 0x0000 : word16)
	trait_primitive(word16)
T_17 (in ax_14 == 0x0000 : bool)
	trait_primitive(bool)
T_18 (in 0x0001 : word16)
	trait_primitive(word16)
T_19 (in fn0C00_000F : ptr32)
	trait_func(T_12 -> T_20)
T_20 (in fn0C00_000F(ax_14) : word16)
	trait_primitive(word16)
	trait_equal(T_10)
	trait_primitive(int16)
T_21 (in wArg00 *s fn0C00_000F(ax_14) : int32)
	trait_primitive(int32)
	trait_primitive(int32)
T_22 (in (word16) (wArg00 *s fn0C00_000F(ax_14)) : word16)
	trait_primitive(word16)
