// MockSnarl
void MockSnarl()
MockSnarl_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	if (a0)
	{
		foo(a2);
		if (a2)
			goto b4;
	}
	else
		foo(a0);
	// succ:  4
b2:		// block 2
l2:		// block 3
b3:		// block 4, pred: 1
	foo(a3)
	if (!a3)
	{
b4:
		foo();
	}
	// succ:  6
b4:		// block 5
b5:		// block 6, pred: 4
	return
	// succ:  7
MockSnarl_exit:		// block 7, pred: 6
	// succ: 

