// fn0C00_0000
void fn0C00_0000(word16 si, segment ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	word16 ax_10 = Mem0[ds:si:word16]
	// succ:  2
l0C00_000E:		// block 2, pred: 1 3
	store(Mem15[ds:si + 0x0002:word16]) = ax_10
	store(Mem16[ds:si + 0x0004:word16]) = ax_10
	store(Mem17[ds:si + 0x0008:word16]) = 0x0003
	branch ax_10 != 0x0000
	// succ:  4 3
l0C00_0005:		// block 3, pred: 2
	store(Mem23[ds:si + 0x0006:word16]) = Mem17[ds:si + 0x0006:word16] + Mem17[ds:si + 0x0006:word16]
	ax_10 = ax_10 - 0x0001
	// succ:  2
l0C00_001E:		// block 4, pred: 2
	return
	// succ:  5
fn0C00_0000_exit:		// block 5, pred: 4
	// succ: 
-----------
hdr: 2, end: 3 [2, 3]

void fn0C00_0000(word16 si, segment ds)
{
	word16 ax_10 = Mem0[ds:si:word16]
	while (true)
	{
		Mem15[ds:si + 0x0002:word16] = ax_10;
		Mem16[ds:si + 0x0004:word16] = ax_10;
		Mem17[ds:si + 0x0008:word16] = 0x0003;
		if (ax_10 == 0x0000)
			break;
		Mem23[ds:si + 0x0006:word16] = Mem17[ds:si + 0x0006:word16] + Mem17[ds:si + 0x0006:word16];
		ax_10 = ax_10 - 0x0001;
	}
	return
}
===========
