// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	store(Mem7[ds:0x0064:word16]) = fn0C00_000B(0x0005)
	return
	// succ:  1
fn0C00_0000_exit:		// block 1, pred: 0
	// succ: 

void fn0C00_0000(selector ds)
{
	Mem7[ds:0x0064:word16] = fn0C00_000B(0x0005);
	return;
}
===========================
// fn0C00_000B
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:		// block 0, pred:
	// succ:  1
l0C00_000B:		// block 1, pred: 0
	word16 ax_13
	branch cx <= 0x0001 l0C00_001C
	// succ:  3 2
l0C00_001C:		// block 2, pred: 1
	ax_13 = 0x0001
	// succ:  4
l0C00_0011:		// block 3, pred: 1
	ax_13 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
	// succ:  4
l0C00_001F:		// block 4, pred: 2 3
	return ax_13
	// succ:  5
fn0C00_000B_exit:		// block 5, pred: 4
	// succ: 

word16 fn0C00_000B(word16 cx)
{
	word16 ax_13;
	if (cx > 0x0001)
		ax_13 = (word16) (cx *s fn0C00_000B(cx - 0x0001));
	else
		ax_13 = 0x0001;
	return ax_13;
}
===========================
