// fn0C00_0000
void fn0C00_0000(segment ds)
fn0C00_0000_entry:		// block 0
	store(Mem7[ds:0x0064:word16]) = fn0C00_000B(0x0005)
	return

void fn0C00_0000(segment ds)
{
	Mem7[ds:0x0064:word16] = fn0C00_000B(0x0005);
	return;
}
===========================
// fn0C00_000B
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:		// block 0, pred:
	// succ:  1
l0C00_000B:		// block 1, pred: 0
	word16 ax_12
	branch cx <= 0x0001
	// succ:  3 2
l0C00_001C:		// block 2, pred: 1
	ax_12 = 0x0001
	// succ:  4
l0C00_0011:		// block 3, pred: 1
	ax_12 = (word16) (cx * fn0C00_000B(cx - 0x0001)) (alias)
	// succ:  4
l0C00_001F:		// block 4, pred: 3 2
	return ax_12
	// succ:  5
fn0C00_000B_exit:		// block 5, pred: 4
	// succ: 

word16 fn0C00_000B(word16 cx)
{
	word16 ax_12;
	if (cx <= 0x0001)
		ax_12 = 0x0001;
	else
		ax_12 = (word16) (cx * fn0C00_000B(cx - 0x0001));
	return ax_12;
}
===========================
