// hello_ppc.c
// Generated by decompiling hello_ppc.exe
// using Reko decompiler version 0.8.0.2.

#include "hello_ppc.h"

Eq_2725 g_tFFFFFFA0;
Eq_973 g_tFFFFFFFD;
Eq_973 g_tFFFFFFFE;
<anonymous> * g_ptrFFFFFFFF;
Eq_973 g_t0001;
int32 g_dw0003;
Eq_3102 g_t0016;
Eq_3102 g_t0017;
ui32 g_dw0120;
word32 g_dw092C;
byte g_b0BFF;
Eq_1893 g_t1000;
Eq_1893 g_t1008;
int32 g_dw1FF8;

