
fn0C00_0000()
	call	002C
	cmp	ax,0002
	ja	0011

l0C00_0008:
	mov	bx,ax
	add	bx,bx
	call	word ptr cs:[bx+0012]

l0C00_0011:
	ret	
Call table at 0C00:0012 (6 bytes)
	0C00:0018
	0C00:0022
	0C00:002C
0C00:0012       18 00 22 00 2C 00                           ..".,.

fn0C00_0018()
	mov	ax,[si+02]
	add	ax,[si+04]
	mov	word ptr [si+06],ax
	ret	

fn0C00_0022()
	mov	ax,[si+02]
	sub	ax,[si+04]
	mov	word ptr [si+06],ax
	ret	

fn0C00_002C()
	mov	ax,[si+02]
	and	ax,[bx+04]
	mov	word ptr [si+06],ax
	ret	
