// test_plt.c
// Generated by decompiling test
// using Reko decompiler version 0.12.1.0.

#include "test.h"

<anonymous> g_t400416 = <code>; // 0000000000400416
<anonymous> g_t400426 = <code>; // 0000000000400426
<anonymous> g_t400436 = <code>; // 0000000000400436
