// Equivalence classes ////////////
Eq_1: (struct (123130 word32 dw123130))
	globals_t (in globals : (struct))
Eq_2: (struct (0 word32 dw0000))
	T_2 (in 0x00123130 : word32)
	T_3 (in r1 : word32)
// Type Variables ////////////
globals_t: (in globals : (struct))
  Class: Eq_1
  DataType: (struct (123130 word32 dw123130))
  OrigDataType: (struct)
T_2: (in 0x00123130 : word32)
  Class: Eq_2
  DataType: (ptr (struct (0 word32 dw0000)))
  OrigDataType: word32
T_3: (in r1 : word32)
  Class: Eq_2
  DataType: (ptr (struct (0 word32 dw0000)))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_4: (in 0x00000042 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[r1:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
