// Equivalence classes ////////////
// Type Variables ////////////
T_1: (in globals : ptr0)
  Class: Eq_1
  DataType: 
  OrigDataType: (ptr (struct (3000 (arr (struct 4 (0 T_7 t0000))) a3000)))
T_2: (in 0x00003000 : word32)
  Class: Eq_2
  DataType: 
  OrigDataType: word32
T_3: (in globals + 0x00003000 : ptr0)
  Class: Eq_3
  DataType: 
  OrigDataType: ptr0
T_4: (in i : word32)
  Class: Eq_4
  DataType: 
  OrigDataType: word32
T_5: (in 0x00000004 : word32)
  Class: Eq_5
  DataType: 
  OrigDataType: word32
T_6: (in i * 0x00000004 : word32)
  Class: Eq_6
  DataType: 
  OrigDataType: word32
T_7: (in (globals + 0x00003000)[i * 0x00000004] : int32)
  Class: Eq_7
  DataType: 
  OrigDataType: int32
