// GlobalVariablesMock
void GlobalVariablesMock()
GlobalVariablesMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem3[ptr:real32]) = 0.75F
	store(Mem4[0x10000000:real32]) = 0.5F
	// succ: 

// Equivalence classes ////////////
Eq_1: (ptr (struct (10000000 T_7 t10000000)))
	Globals (in globals : ptr0)
Eq_2: real32
	T_2 (in 0.75F : real32)
	T_4 (in Mem3[ptr:real32] : real32)
Eq_3: (ptr (struct (0 T_4 t0000)))
	T_3 (in ptr : word32)
Eq_5: real32
	T_5 (in 0.5F : real32)
	T_7 (in Mem4[0x10000000:real32] : real32)
Eq_6: (ptr (struct (0 T_7 t0000)))
	T_6 (in 0x10000000 : word32)
// Type Variables ////////////
Globals: (in globals : ptr0)
  Class: Eq_1
  DataType: (ptr (struct (10000000 T_7 t10000000)))
  OrigDataType: (ptr (struct (10000000 T_7 t10000000)))
T_2: (in 0.75F : real32)
  Class: Eq_2
  DataType: real32
  OrigDataType: real32
T_3: (in ptr : word32)
  Class: Eq_3
  DataType: (ptr (struct (0 T_4 t0000)))
  OrigDataType: (ptr (struct (0 T_4 t0000)))
T_4: (in Mem3[ptr:real32] : real32)
  Class: Eq_2
  DataType: real32
  OrigDataType: real32
T_5: (in 0.5F : real32)
  Class: Eq_5
  DataType: real32
  OrigDataType: real32
T_6: (in 0x10000000 : word32)
  Class: Eq_6
  DataType: (ptr (struct (0 T_7 t0000)))
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem4[0x10000000:real32] : real32)
  Class: Eq_5
  DataType: real32
  OrigDataType: real32
