// Equivalence classes ////////////
Eq_2: word16
	T_2 (in 0x0000 : word16)
	T_5 (in Mem11[ds:0x9A2E:word16] : word16)
Eq_3: (ptr (struct (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
	T_3 (in ds : segment)
Eq_4: (memptr T_3 (struct (0 T_5 t0000)))
	T_4 (in 0x9A2E : word16)
Eq_6: word16
	T_6 (in 0x0100 : word16)
	T_8 (in Mem13[ds:0x9A26:word16] : word16)
	T_14 (in v8_22 : word16)
	T_16 (in Mem19[ds:0x9A26:word16] : word16)
	T_18 (in Mem19[ds:0x9A26:word16] - 0x0001 : word16)
	T_19 (in Mem23[ds:0x9A26:word16] : word16)
	T_22 (in 0x0000 : word16)
Eq_7: (memptr T_3 (struct (0 T_8 t0000)))
	T_7 (in 0x9A26 : word16)
Eq_9: (memptr T_12 (struct 26 (0 T_13 t0000)))
	T_9 (in si_16 : word16)
	T_10 (in 0x0000 : word16)
	T_21 (in si_16 + 0x0026 : word16)
Eq_11: word16
	T_11 (in 0xFFFF : word16)
	T_13 (in Mem19[0x5CE1:si_16:word16] : word16)
Eq_12: (ptr (struct (0 (arr (struct 26 (0 T_13 t0000))) a0000)))
	T_12 (in 0x5CE1 : segment)
Eq_15: (memptr T_3 (struct (0 T_6 t0000)))
	T_15 (in 0x9A26 : word16)
Eq_17: word16
	T_17 (in 0x0001 : word16)
Eq_20: word16
	T_20 (in 0x0026 : word16)
Eq_23: bool
	T_23 (in v8_22 != 0x0000 : bool)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2:(in 0x0000)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3:(in ds)
  Class: Eq_3
  DataType: (ptr (struct (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
  OrigDataType: (ptr (struct (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
T_4:(in 0x9A2E)
  Class: Eq_4
  DataType: (memptr T_3 (struct (0 T_5 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5:(in Mem11[ds:0x9A2E:word16])
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_6:(in 0x0100)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7:(in 0x9A26)
  Class: Eq_7
  DataType: (memptr T_3 (struct (0 T_8 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_8:(in Mem13[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9:(in si_16)
  Class: Eq_9
  DataType: (memptr T_12 (struct 26 (0 T_13 t0000)))
  OrigDataType: (memptr T_12 (struct 26 (0 T_13 t0000)))
T_10:(in 0x0000)
  Class: Eq_9
  DataType: (memptr T_12 (struct 26 (0 T_13 t0000)))
  OrigDataType: word16
T_11:(in 0xFFFF)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12:(in 0x5CE1)
  Class: Eq_12
  DataType: (ptr (struct (0 (arr (struct 26 (0 T_13 t0000))) a0000)))
  OrigDataType: (ptr (struct (0 (arr (struct 26 (0 T_13 t0000))) a0000)))
T_13:(in Mem19[0x5CE1:si_16:word16])
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_14:(in v8_22)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_15:(in 0x9A26)
  Class: Eq_15
  DataType: (memptr T_3 (struct (0 T_6 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_6 t0000)))
T_16:(in Mem19[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_17:(in 0x0001)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18:(in Mem19[ds:0x9A26:word16] - 0x0001)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_19:(in Mem23[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_20:(in 0x0026)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21:(in si_16 + 0x0026)
  Class: Eq_9
  DataType: (memptr T_12 (struct 26 (0 T_13 t0000)))
  OrigDataType: word16
T_22:(in 0x0000)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_23:(in v8_22 != 0x0000)
  Class: Eq_23
  DataType: bool
  OrigDataType: bool
