// Equivalence classes ////////////
Eq_2: (ptr (fn T_10 (T_7, T_8, T_9)))
	T_2 (in fn0C00_0010 : ptr0)
	T_3 (in signature of fn0C00_0010 : )
Eq_4: (ptr (struct (400 T_42 t0400) (408 T_46 t0408)))
	T_4 (in ds : segment)
	T_7 (in ds : segment)
	T_13 (in ds : segment)
Eq_5: word16
	T_5 (in wArg02 : word16)
	T_8 (in 0x0300 : word16)
Eq_6: word16
	T_6 (in wArg04 : word16)
	T_9 (in 0x0320 : word16)
Eq_10: void
	T_10 (in fn0C00_0010(ds, 0x0300, 0x0320) : void)
Eq_11: (ptr (fn T_14 (T_7)))
	T_11 (in fn0C00_0037 : ptr0)
	T_12 (in signature of fn0C00_0037 : )
Eq_14: void
	T_14 (in fn0C00_0037(ds) : void)
Eq_15: real64
	T_15 (in rLoc1_11 : real64)
	T_17 (in Mem0[ds:wArg02:real64] : real64)
Eq_16: (memptr T_4 (struct (0 T_17 t0000) (8 T_21 t0008) (10 T_25 t0010)))
	T_16 (in wArg02 : word16)
Eq_18: real64
	T_18 (in rLoc2_13 : real64)
	T_21 (in Mem0[ds:wArg02 + 0x0008:real64] : real64)
Eq_19: word16
	T_19 (in 0x0008 : word16)
Eq_20: word16
	T_20 (in wArg02 + 0x0008 : word16)
Eq_22: real64
	T_22 (in rLoc2_16 : real64)
	T_25 (in Mem0[ds:wArg02 + 0x0010:real64] : real64)
Eq_23: word16
	T_23 (in 0x0010 : word16)
Eq_24: word16
	T_24 (in wArg02 + 0x0010 : word16)
Eq_26: real64
	T_26 (in rLoc1_11 * rLoc1_11 : real64)
Eq_27: real64
	T_27 (in rLoc2_13 * rLoc2_13 : real64)
Eq_28: real64
	T_28 (in rLoc1_11 * rLoc1_11 + rLoc2_13 * rLoc2_13 : real64)
Eq_29: real64
	T_29 (in rLoc2_16 * rLoc2_16 : real64)
Eq_30: real64
	T_30 (in rLoc1_11 * rLoc1_11 + rLoc2_13 * rLoc2_13 + rLoc2_16 * rLoc2_16 : real64)
	T_32 (in Mem20[ds:wArg04:real64] : real64)
Eq_31: (memptr T_4 (struct (0 T_32 t0000) (20 T_35 t0020) (28 T_39 t0028)))
	T_31 (in wArg04 : word16)
Eq_33: word16
	T_33 (in 0x0020 : word16)
Eq_34: word16
	T_34 (in wArg04 + 0x0020 : word16)
Eq_35: word16
	T_35 (in Mem20[ds:wArg04 + 0x0020:word16] : word16)
Eq_36: real64
	T_36 (in (real64) Mem20[ds:wArg04 + 0x0020:word16] : real64)
	T_39 (in Mem22[ds:wArg04 + 0x0028:real64] : real64)
Eq_37: word16
	T_37 (in 0x0028 : word16)
Eq_38: word16
	T_38 (in wArg04 + 0x0028 : word16)
Eq_40: real64
	T_40 (in 0 : real64)
	T_42 (in Mem5[ds:0x0400:real64] : real64)
Eq_41: (memptr T_13 (struct (0 T_42 t0000)))
	T_41 (in 0x0400 : word16)
Eq_43: real64
	T_43 (in 1 : real64)
Eq_44: word32
	T_44 (in (word32) 1 : word32)
	T_46 (in Mem7[ds:0x0408:word32] : word32)
Eq_45: (memptr T_13 (struct (0 T_46 t0000)))
	T_45 (in 0x0408 : word16)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2:(in fn0C00_0010)
  Class: Eq_2
  DataType: (ptr (fn T_10 (T_7, T_8, T_9)))
  OrigDataType: (ptr (fn T_10 (T_7, T_8, T_9)))
T_3:(in signature of fn0C00_0010)
  Class: Eq_2
  DataType: (ptr (fn T_10 (T_7, T_8, T_9)))
  OrigDataType: 
T_4:(in ds)
  Class: Eq_4
  DataType: (ptr (struct (400 T_42 t0400) (408 T_46 t0408)))
  OrigDataType: segment
T_5:(in wArg02)
  Class: Eq_5
  DataType: word16
  OrigDataType: 
T_6:(in wArg04)
  Class: Eq_6
  DataType: word16
  OrigDataType: 
T_7:(in ds)
  Class: Eq_4
  DataType: (ptr (struct (400 T_42 t0400) (408 T_46 t0408)))
  OrigDataType: segment
T_8:(in 0x0300)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_9:(in 0x0320)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_10:(in fn0C00_0010(ds, 0x0300, 0x0320))
  Class: Eq_10
  DataType: void
  OrigDataType: void
T_11:(in fn0C00_0037)
  Class: Eq_11
  DataType: (ptr (fn T_14 (T_7)))
  OrigDataType: (ptr (fn T_14 (T_7)))
T_12:(in signature of fn0C00_0037)
  Class: Eq_11
  DataType: (ptr (fn T_14 (T_7)))
  OrigDataType: 
T_13:(in ds)
  Class: Eq_4
  DataType: (ptr (struct (400 T_42 t0400) (408 T_46 t0408)))
  OrigDataType: (ptr (struct (400 T_42 t0400) (408 T_46 t0408)))
T_14:(in fn0C00_0037(ds))
  Class: Eq_14
  DataType: void
  OrigDataType: void
T_15:(in rLoc1_11)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_16:(in wArg02)
  Class: Eq_16
  DataType: (memptr T_4 (struct (0 T_17 t0000) (8 T_21 t0008) (10 T_25 t0010)))
  OrigDataType: (memptr T_4 (struct (0 T_17 t0000) (8 T_21 t0008) (10 T_25 t0010)))
T_17:(in Mem0[ds:wArg02:real64])
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_18:(in rLoc2_13)
  Class: Eq_18
  DataType: real64
  OrigDataType: real64
T_19:(in 0x0008)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20:(in wArg02 + 0x0008)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21:(in Mem0[ds:wArg02 + 0x0008:real64])
  Class: Eq_18
  DataType: real64
  OrigDataType: real64
T_22:(in rLoc2_16)
  Class: Eq_22
  DataType: real64
  OrigDataType: real64
T_23:(in 0x0010)
  Class: Eq_23
  DataType: word16
  OrigDataType: word16
T_24:(in wArg02 + 0x0010)
  Class: Eq_24
  DataType: word16
  OrigDataType: word16
T_25:(in Mem0[ds:wArg02 + 0x0010:real64])
  Class: Eq_22
  DataType: real64
  OrigDataType: real64
T_26:(in rLoc1_11 * rLoc1_11)
  Class: Eq_26
  DataType: real64
  OrigDataType: real64
T_27:(in rLoc2_13 * rLoc2_13)
  Class: Eq_27
  DataType: real64
  OrigDataType: real64
T_28:(in rLoc1_11 * rLoc1_11 + rLoc2_13 * rLoc2_13)
  Class: Eq_28
  DataType: real64
  OrigDataType: real64
T_29:(in rLoc2_16 * rLoc2_16)
  Class: Eq_29
  DataType: real64
  OrigDataType: real64
T_30:(in rLoc1_11 * rLoc1_11 + rLoc2_13 * rLoc2_13 + rLoc2_16 * rLoc2_16)
  Class: Eq_30
  DataType: real64
  OrigDataType: real64
T_31:(in wArg04)
  Class: Eq_31
  DataType: (memptr T_4 (struct (0 T_32 t0000) (20 T_35 t0020) (28 T_39 t0028)))
  OrigDataType: (memptr T_4 (struct (0 T_32 t0000) (20 T_35 t0020) (28 T_39 t0028)))
T_32:(in Mem20[ds:wArg04:real64])
  Class: Eq_30
  DataType: real64
  OrigDataType: real64
T_33:(in 0x0020)
  Class: Eq_33
  DataType: word16
  OrigDataType: word16
T_34:(in wArg04 + 0x0020)
  Class: Eq_34
  DataType: word16
  OrigDataType: word16
T_35:(in Mem20[ds:wArg04 + 0x0020:word16])
  Class: Eq_35
  DataType: word16
  OrigDataType: word16
T_36:(in (real64) Mem20[ds:wArg04 + 0x0020:word16])
  Class: Eq_36
  DataType: real64
  OrigDataType: real64
T_37:(in 0x0028)
  Class: Eq_37
  DataType: word16
  OrigDataType: word16
T_38:(in wArg04 + 0x0028)
  Class: Eq_38
  DataType: word16
  OrigDataType: word16
T_39:(in Mem22[ds:wArg04 + 0x0028:real64])
  Class: Eq_36
  DataType: real64
  OrigDataType: real64
T_40:(in 0)
  Class: Eq_40
  DataType: real64
  OrigDataType: real64
T_41:(in 0x0400)
  Class: Eq_41
  DataType: (memptr T_13 (struct (0 T_42 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_42 t0000)))
T_42:(in Mem5[ds:0x0400:real64])
  Class: Eq_40
  DataType: real64
  OrigDataType: real64
T_43:(in 1)
  Class: Eq_43
  DataType: real64
  OrigDataType: real64
T_44:(in (word32) 1)
  Class: Eq_44
  DataType: word32
  OrigDataType: word32
T_45:(in 0x0408)
  Class: Eq_45
  DataType: (memptr T_13 (struct (0 T_46 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_46 t0000)))
T_46:(in Mem7[ds:0x0408:word32])
  Class: Eq_44
  DataType: word32
  OrigDataType: word32
