// Equivalence classes ////////////
Eq_2: (memptr T_4 (struct (0 T_5 t0000)))
	T_2 (in 0x0001 : word16)
	T_3 (in si : word16)
Eq_4: word16
	T_4 (in cs : word16)
Eq_5: word16
	T_5 (in Mem0[cs:si:word16] : word16)
	T_6 (in ax : word16)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2:(in 0x0001)
  Class: Eq_2
  DataType: (memptr T_4 (struct (0 T_5 t0000)))
  OrigDataType: word16
T_3:(in si)
  Class: Eq_2
  DataType: (memptr T_4 (struct (0 T_5 t0000)))
  OrigDataType: (memptr T_4 (struct (0 T_5 t0000)))
T_4:(in cs)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5:(in Mem0[cs:si:word16])
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6:(in ax)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
