// Equivalence classes ////////////
Eq_2: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
	T_2 (in t : word32)
	T_3 (in 0x00000000 : word32)
	T_12 (in Mem0[t + 0x00000004:word32] : word32)
	T_15 (in Mem0[t + 0x00000008:word32] : word32)
Eq_4: bool
	T_4 (in t == 0x00000000 : bool)
Eq_5: int32
	T_5 (in vv_7 : word32)
	T_6 (in Mem0[t:word32] : word32)
	T_7 (in v : word32)
Eq_8: bool
	T_8 (in v == vv_7 : bool)
Eq_9: bool
	T_9 (in v < vv_7 : bool)
Eq_10: word32
	T_10 (in 0x00000004 : word32)
Eq_11: word32
	T_11 (in t + 0x00000004 : word32)
Eq_13: word32
	T_13 (in 0x00000008 : word32)
Eq_14: word32
	T_14 (in t + 0x00000008 : word32)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2:(in t)
  Class: Eq_2
  DataType: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
  OrigDataType: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
T_3:(in 0x00000000)
  Class: Eq_2
  DataType: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
  OrigDataType: word32
T_4:(in t == 0x00000000)
  Class: Eq_4
  DataType: bool
  OrigDataType: bool
T_5:(in vv_7)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
T_6:(in Mem0[t:word32])
  Class: Eq_5
  DataType: int32
  OrigDataType: word32
T_7:(in v)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
T_8:(in v == vv_7)
  Class: Eq_8
  DataType: bool
  OrigDataType: bool
T_9:(in v < vv_7)
  Class: Eq_9
  DataType: bool
  OrigDataType: bool
T_10:(in 0x00000004)
  Class: Eq_10
  DataType: word32
  OrigDataType: word32
T_11:(in t + 0x00000004)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
T_12:(in Mem0[t + 0x00000004:word32])
  Class: Eq_2
  DataType: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
  OrigDataType: word32
T_13:(in 0x00000008)
  Class: Eq_13
  DataType: word32
  OrigDataType: word32
T_14:(in t + 0x00000008)
  Class: Eq_14
  DataType: word32
  OrigDataType: word32
T_15:(in Mem0[t + 0x00000008:word32])
  Class: Eq_2
  DataType: (ptr (struct (0 T_6 t0000) (4 T_12 t0004) (8 T_15 t0008)))
  OrigDataType: word32
