// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: selector
  OrigDataType: selector
T_3: (in 0x0123 : word16)
  Class: Eq_3
  DataType: (memptr T_2 byte)
  OrigDataType: (memptr T_2 byte)
T_4: (in Mem0[ds:0x0123:byte] : byte)
  Class: Eq_4
  DataType: byte
  OrigDataType: byte
