// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem0[ds:0x00001B58:word16]) = Mem0[ds:Mem0[ds:0x00005321:word16]:word16]
	// succ: 

// Equivalence classes ////////////
Eq_2: (segment (1B58 word16 w1B58) (5321 (memptr (ptr Eq_2) Eq_4) ptr5321))
	T_2 (in ds : selector)
Eq_3: (struct (0 (memptr (ptr Eq_2) Eq_4) ptr0000))
	T_3 (in 0x00005321 : word32)
Eq_4: (struct (0 word16 w0000))
	T_4 (in Mem0[ds:0x00005321:word16] : word16)
Eq_6: (struct (0 word16 w0000))
	T_6 (in 0x00001B58 : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment (1B58 T_7 t1B58) (5321 T_4 t5321)))
T_3: (in 0x00005321 : word32)
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) Eq_3)
  OrigDataType: (memptr T_2 (struct (0 T_4 t0000)))
T_4: (in Mem0[ds:0x00005321:word16] : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_2) Eq_4)
  OrigDataType: (memptr T_2 (struct (0 T_5 t0000)))
T_5: (in Mem0[ds:Mem0[ds:0x00005321:word16]:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in 0x00001B58 : word32)
  Class: Eq_6
  DataType: (memptr (ptr Eq_2) Eq_6)
  OrigDataType: (memptr T_2 (struct (0 T_7 t0000)))
T_7: (in Mem0[ds:0x00001B58:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
