// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem0[cs:0x00000001:word16]) = 0x0800
	// succ: 

// Equivalence classes ////////////
Eq_3: (struct (1 segment pseg0001))
	T_3 (in cs : segment)
Eq_4: (struct (0 segment pseg0000))
	T_4 (in 0x00000001 : word32)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2:(in 0x0800)
  Class: Eq_2
  DataType: segment
  OrigDataType: segment
T_3:(in cs)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (struct (1 T_5 t0001)))
T_4:(in 0x00000001)
  Class: Eq_4
  DataType: (memptr (ptr Eq_3) Eq_4)
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5:(in Mem0[cs:0x00000001:word16])
  Class: Eq_2
  DataType: segment
  OrigDataType: word16
