// Fn
void Fn()
Fn_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	a = &globals->dw123456;
	*a = 0x0000002A;
	// succ: 

// Equivalence classes ////////////
Eq_1: (struct "Eq_1" (123456 word32 dw123456))
	Globals (in globals : ptr0)
// Type Variables ////////////
Globals: (in globals : ptr0)
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (123456 T_9 t123456)))
T_2: (in 0x00123456 : word32)
  Class: Eq_2
  DataType: (ptr word32)
  OrigDataType: word32
T_3: (in a : word32)
  Class: Eq_2
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_9 t0000)))
T_4: (in 0x0000002A : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in i : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in 0x00000008 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in i * 0x00000008 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in a + i * 0x00000008 : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[a + i * 0x00000008:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
