// Before ///////
// proc1
void proc1()
proc1_entry:
	// succ:  l1
l1:
	f = Mem0[p + 0x00000004:(ptr (struct "foo" 0008))] < 0x00000028
proc1_exit:

// After ///////
// proc1
void proc1()
proc1_entry:
	// succ:  l1
l1:
	f = p->ptr0004 < &globals->t0028;
proc1_exit:

// Equivalence classes ////////////
Eq_2: (struct "Eq_2" (4 (ptr Eq_5) ptr0004))
	T_2 (in p : word32)
Eq_5: (struct "foo" 0008)
	T_5 (in Mem0[p + 0x00000004:(ptr (struct "foo" 0008))] : (ptr (struct "foo" 0008)))
	T_6 (in 0x00000028 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct (28 Eq_5 t0028))))
  Class: Eq_1
  DataType: ptr32
  OrigDataType: ptr32
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (4 T_5 t0004)))
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in p + 0x00000004 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[p + 0x00000004:(ptr (struct "foo" 0008))] : (ptr (struct "foo" 0008)))
  Class: Eq_5
  DataType: (ptr Eq_5)
  OrigDataType: (ptr (struct "foo" 0008))
T_6: (in 0x00000028 : word32)
  Class: Eq_5
  DataType: (ptr Eq_5)
  OrigDataType: int32
T_7: (in p->ptr0004 < &globals->t0028 : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
T_8: (in f : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
