// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	ds2 = ds;
	ds->f5400 = ds->ptr5404->w0004 < 0x0014;
	ds2->ptr5404->w0004 = 0x0000;
	// succ: 

// Equivalence classes ////////////
Eq_2: (struct "Eq_2" (5400 bool f5400) (5404 (ptr Eq_6) ptr5404))
	T_2 (in ds : word32)
	T_3 (in ds2 : word32)
Eq_6: (struct "Eq_6" (4 int16 w0004))
	T_6 (in Mem0[ds + 0x00005404:word32] : word32)
	T_18 (in Mem0[ds2 + 0x00005404:word32] : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in ds : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (5400 T_14 t5400) (5404 T_6 t5404)))
T_3: (in ds2 : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (5404 T_18 t5404)))
T_4: (in 0x00005404 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in ds + 0x00005404 : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in Mem0[ds + 0x00005404:word32] : word32)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: (ptr (struct (4 T_9 t0004)))
T_7: (in 0x00000004 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in ds->ptr5404 + 0x00000004 : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[ds->ptr5404 + 0x00000004:word16] : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: int16
T_10: (in 0x0014 : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: int16
T_11: (in ds->ptr5404->w0004 < 0x0014 : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_12: (in 0x00005400 : word32)
  Class: Eq_12
  DataType: word32
  OrigDataType: word32
T_13: (in ds + 0x00005400 : word32)
  Class: Eq_13
  DataType: word32
  OrigDataType: word32
T_14: (in Mem0[ds + 0x00005400:bool] : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_15: (in 0x0000 : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: word16
T_16: (in 0x00005404 : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in ds2 + 0x00005404 : word32)
  Class: Eq_17
  DataType: word32
  OrigDataType: word32
T_18: (in Mem0[ds2 + 0x00005404:word32] : word32)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: (ptr (struct (4 T_21 t0004)))
T_19: (in 0x00000004 : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in ds2->ptr5404 + 0x00000004 : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_21: (in Mem0[ds2->ptr5404 + 0x00000004:word16] : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: word16
