// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	ds->f5400 = ds->w5404 < 0x0014;
	ds->w5404 = 0x0000;
	// succ: 

// Equivalence classes ////////////
Eq_2: (segment "Eq_2" (5400 bool f5400) (5404 int16 w5404))
	T_2 (in ds : selector)
// Type Variables ////////////
Globals: (in globals : ptr0)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment (5400 T_8 t5400) (5404 (union (T_4 u0) (T_11 u1)) u5404)))
T_3: (in 0x5404 : word16)
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) int16)
  OrigDataType: (memptr T_2 (struct (0 T_4 t0000)))
T_4: (in Mem0[ds:0x5404:word16] : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: int16
T_5: (in 0x0014 : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: int16
T_6: (in ds->w5404 < 0x0014 : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in 0x5400 : word16)
  Class: Eq_7
  DataType: (memptr (ptr Eq_2) bool)
  OrigDataType: (memptr T_2 (struct (0 T_8 t0000)))
T_8: (in Mem0[ds:0x5400:bool] : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_9: (in 0x0000 : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: word16
T_10: (in 0x5404 : word16)
  Class: Eq_10
  DataType: (memptr (ptr Eq_2) int16)
  OrigDataType: (memptr T_2 (struct (0 T_11 t0000)))
T_11: (in Mem0[ds:0x5404:word16] : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: word16
