// fn0C00_0000
void fn0C00_0000(segment ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	fn0C00_0010(ds, 0x0300, 0x0320)
	fn0C00_0037(ds)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_0010
void fn0C00_0010(segment ds, word16 wArg00, word16 wArg02)
fn0C00_0010_entry:		// block 0, pred:
	// succ:  1
l0C00_0010:		// block 1, pred: 0
	real64 rLoc1_12 = Mem0[ds:wArg00:real64]
	real64 rLoc2_14 = Mem0[ds:wArg00 + 0x0008:real64]
	real64 rLoc2_17 = Mem0[ds:wArg00 + 0x0010:real64]
	store(Mem21[ds:wArg02:real64]) = rLoc1_12 *s rLoc1_12 + rLoc2_14 *s rLoc2_14 + rLoc2_17 *s rLoc2_17
	store(Mem23[ds:wArg02 + 0x0028:real64]) = (real64) Mem21[ds:wArg02 + 0x0020:word16]
	return
	// succ:  2
fn0C00_0010_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_0037
void fn0C00_0037(segment ds)
fn0C00_0037_entry:		// block 0, pred:
	// succ:  1
l0C00_0037:		// block 1, pred: 0
	store(Mem5[ds:0x0400:real64]) = 0
	store(Mem7[ds:0x0408:word32]) = (word32) 1
	return
	// succ:  2
fn0C00_0037_exit:		// block 2, pred: 1
	// succ: 

T_2 (in fn0C00_0010)
	trait_func(T_7, T_8, T_9 -> T_10)
T_4 (in ds)
	trait_primitive(segment)
	trait_primitive(segment)
	trait_primitive(segment)
	trait_primitive(segment)
	trait_primitive(segment)
	trait_primitive(segment)
T_7 (in ds)
	trait_primitive(segment)
	trait_equal(T_4)
	trait_primitive(segment)
	trait_equal(T_13)
T_8 (in 0x0300)
	trait_primitive(word16)
	trait_equal(T_5)
T_9 (in 0x0320)
	trait_primitive(word16)
	trait_equal(T_6)
T_10 (in fn0C00_0010(ds, 0x0300, 0x0320))
	trait_primitive(void)
T_11 (in fn0C00_0037)
	trait_func(T_7 -> T_14)
T_13 (in ds)
	trait_primitive(segment)
	trait_mem(T_42, 400)
	trait_primitive(segment)
	trait_mem(T_46, 408)
T_14 (in fn0C00_0037(ds))
	trait_primitive(void)
T_15 (in rLoc1_12)
	trait_equal(T_17)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
T_16 (in wArg00)
	trait_primitive(word16)
	trait_mem(T_4:T_17, 0)
	trait_primitive(word16)
	trait_mem(T_4:T_21, 8)
	trait_primitive(word16)
	trait_mem(T_4:T_25, 10)
T_17 (in Mem0[ds:wArg00:real64])
	trait_primitive(real64)
T_18 (in rLoc2_14)
	trait_equal(T_21)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
T_19 (in 0x0008)
	trait_primitive(word16)
T_20 (in wArg00 + 0x0008)
	trait_primitive(word16)
T_21 (in Mem0[ds:wArg00 + 0x0008:real64])
	trait_primitive(real64)
T_22 (in rLoc2_17)
	trait_equal(T_25)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
	trait_primitive(real64)
T_23 (in 0x0010)
	trait_primitive(word16)
T_24 (in wArg00 + 0x0010)
	trait_primitive(word16)
T_25 (in Mem0[ds:wArg00 + 0x0010:real64])
	trait_primitive(real64)
T_26 (in rLoc1_12 *s rLoc1_12)
	trait_primitive(real64)
T_27 (in rLoc2_14 *s rLoc2_14)
	trait_primitive(real64)
T_28 (in rLoc1_12 *s rLoc1_12 + rLoc2_14 *s rLoc2_14)
	trait_primitive(real64)
T_29 (in rLoc2_17 *s rLoc2_17)
	trait_primitive(real64)
T_30 (in rLoc1_12 *s rLoc1_12 + rLoc2_14 *s rLoc2_14 + rLoc2_17 *s rLoc2_17)
	trait_primitive(real64)
T_31 (in wArg02)
	trait_primitive(word16)
	trait_mem(T_4:T_32, 0)
	trait_primitive(word16)
	trait_mem(T_4:T_35, 20)
	trait_primitive(word16)
	trait_mem(T_4:T_39, 28)
T_32 (in Mem21[ds:wArg02:real64])
	trait_primitive(real64)
	trait_equal(T_30)
T_33 (in 0x0020)
	trait_primitive(word16)
T_34 (in wArg02 + 0x0020)
	trait_primitive(word16)
T_35 (in Mem21[ds:wArg02 + 0x0020:word16])
	trait_primitive(word16)
T_36 (in (real64) Mem21[ds:wArg02 + 0x0020:word16])
	trait_primitive(real64)
T_37 (in 0x0028)
	trait_primitive(word16)
T_38 (in wArg02 + 0x0028)
	trait_primitive(word16)
T_39 (in Mem23[ds:wArg02 + 0x0028:real64])
	trait_primitive(real64)
	trait_equal(T_36)
T_40 (in 0)
	trait_primitive(real64)
T_41 (in 0x0400)
	trait_primitive(word16)
	trait_mem(T_13:T_42, 0)
T_42 (in Mem5[ds:0x0400:real64])
	trait_primitive(real64)
	trait_equal(T_40)
T_43 (in 1)
	trait_primitive(real64)
T_44 (in (word32) 1)
	trait_primitive(word32)
T_45 (in 0x0408)
	trait_primitive(word16)
	trait_mem(T_13:T_46, 0)
T_46 (in Mem7[ds:0x0408:word32])
	trait_primitive(word32)
	trait_equal(T_44)
