// fn0C00_0000
void fn0C00_0000(word16 bx, word16 si, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 ax_10 = Mem0[ds:bx + 0x0004:word16]
	store(Mem13[ds:bx + 0x0006:word16]) = ax_10 *s ax_10
	store(Mem15[ds:si + 0x04D4:word16]) = si + 0x0002
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

T_2 (in ax_10 : word16)
	trait_primitive(word16)
	trait_equal(T_7)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(int16)
	trait_primitive(int16)
T_3 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
T_4 (in bx : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_7, 4)
	trait_primitive(word16)
	trait_mem(T_3:T_11, 6)
T_5 (in 0x0004 : word16)
	trait_primitive(word16)
T_6 (in bx + 0x0004 : word16)
	trait_primitive(word16)
T_7 (in Mem0[ds:bx + 0x0004:word16] : word16)
	trait_primitive(word16)
T_8 (in ax_10 *s ax_10 : int16)
	trait_primitive(int16)
	trait_primitive(int16)
T_9 (in 0x0006 : word16)
	trait_primitive(word16)
T_10 (in bx + 0x0006 : word16)
	trait_primitive(word16)
T_11 (in Mem13[ds:bx + 0x0006:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_8)
T_12 (in si : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_3:T_17, 4D4)
T_13 (in 0x0002 : word16)
	trait_primitive(word16)
T_14 (in si + 0x0002 : word16)
	trait_primitive(word16)
T_15 (in 0x04D4 : word16)
	trait_primitive(word16)
T_16 (in si + 0x04D4 : word16)
	trait_primitive(word16)
T_17 (in Mem15[ds:si + 0x04D4:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_14)
