// PtrPtrIntMock
void PtrPtrIntMock()
PtrPtrIntMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	r2 = Mem0[r1:word32]
	r3 = Mem0[r2:word32]
	store(Mem0[0x00010000:word32]) = r3
	store(Mem0[0x00010004:word32]) = r1
	return r3
	// succ:  2
PtrPtrIntMock_exit:		// block 2, pred: 1
	// succ: 

Globals (in globals)
	trait_mem(T_8, 10000)
	trait_mem(T_10, 10004)
T_2 (in r1)
	trait_primitive(word32)
	trait_mem(T_3, 0)
	trait_primitive(word32)
T_3 (in Mem0[r1:word32])
	trait_primitive(word32)
T_4 (in r2)
	trait_primitive(word32)
	trait_equal(T_3)
	trait_primitive(word32)
	trait_mem(T_5, 0)
T_5 (in Mem0[r2:word32])
	trait_primitive(word32)
T_6 (in r3)
	trait_primitive(word32)
	trait_equal(T_5)
	trait_primitive(word32)
	trait_primitive(word32)
T_7 (in 0x00010000)
	trait_primitive(word32)
	trait_mem(T_8, 0)
T_8 (in Mem0[0x00010000:word32])
	trait_primitive(word32)
	trait_equal(T_6)
T_9 (in 0x00010004)
	trait_primitive(word32)
	trait_mem(T_10, 0)
T_10 (in Mem0[0x00010004:word32])
	trait_primitive(word32)
	trait_equal(T_2)
