// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem15[ds:0x0064:word16] = fn0C00_000F(0x0064)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000F
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	// succ:  l0C00_000F
l0C00_000F:
	word16 ax_26
	branch wArg02 == 0x0001 l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	ax_26 = (word16) (wArg02 *s fn0C00_000F(wArg02 - 0x0001)) (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_26 = 0x0001
	// succ:  l0C00_0029
l0C00_0029:
	return ax_26
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:

// Equivalence classes ////////////
Eq_1: (struct)
	globals_t (in globals : (struct))
Eq_2: (fn int16 (word16))
	T_2 (in fn0C00_000F : ptr32)
	T_3 (in signature of fn0C00_000F : void)
	T_16 (in fn0C00_000F : ptr32)
Eq_7: (segment (64 int16 w0064))
	T_7 (in ds : selector)
// Type Variables ////////////
globals_t: (in globals : (struct))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct))
T_2: (in fn0C00_000F : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_6 (T_5)))
T_3: (in signature of fn0C00_000F : void)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: 
T_4: (in wArg02 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in 0x0064 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_6: (in fn0C00_000F(0x0064) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_7: (in ds : selector)
  Class: Eq_7
  DataType: (ptr Eq_7)
  OrigDataType: (ptr (segment (64 T_9 t0064)))
T_8: (in 0x0064 : word16)
  Class: Eq_8
  DataType: (memptr (ptr Eq_7) int16)
  OrigDataType: (memptr T_7 (struct (0 T_9 t0000)))
T_9: (in Mem15[ds:0x0064:word16] : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_10: (in ax : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in ax_26 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in wArg02 : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: int16
T_13: (in 0x0001 : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: word16
T_14: (in wArg02 == 0x0001 : bool)
  Class: Eq_14
  DataType: bool
  OrigDataType: bool
T_15: (in 0x0001 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_16: (in fn0C00_000F : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_19 (T_18)))
T_17: (in 0x0001 : word16)
  Class: Eq_17
  DataType: int16
  OrigDataType: int16
T_18: (in wArg02 - 0x0001 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_19: (in fn0C00_000F(wArg02 - 0x0001) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_20: (in wArg02 *s fn0C00_000F(wArg02 - 0x0001) : int32)
  Class: Eq_20
  DataType: int32
  OrigDataType: int32
T_21: (in (word16) (wArg02 *s fn0C00_000F(wArg02 - 0x0001)) : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
