// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem7[ds:0x0064:word16]) = fn0C00_000B(0x0005)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_000B
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:		// block 0, pred:
	// succ:  1
l0C00_000B:		// block 1, pred: 0
	word16 ax_13
	branch cx <= 0x0001 l0C00_001C
	// succ:  3 2
l0C00_001C:		// block 2, pred: 1
	ax_13 = 0x0001
	// succ:  4
l0C00_0011:		// block 3, pred: 1
	ax_13 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
	// succ:  4
l0C00_001F:		// block 4, pred: 3 2
	return ax_13
	// succ:  5
fn0C00_000B_exit:		// block 5, pred: 4
	// succ: 

// Equivalence classes ////////////
Eq_2: (fn int16 (int16))
	T_2 (in fn0C00_000B : ptr32)
	T_3 (in signature of fn0C00_000B)
	T_15 (in fn0C00_000B : ptr32)
Eq_7: (segment (64 int16 w0064))
	T_7 (in ds : selector)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in fn0C00_000B : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_6 (T_5)))
T_3: (in signature of fn0C00_000B)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: 
T_4: (in cx : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: int16
T_5: (in 0x0005 : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: word16
T_6: (in fn0C00_000B(0x0005) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_7: (in ds : selector)
  Class: Eq_7
  DataType: (ptr Eq_7)
  OrigDataType: (ptr (segment (64 T_9 t0064)))
T_8: (in 0x0064 : word16)
  Class: Eq_8
  DataType: (memptr (ptr Eq_7) int16)
  OrigDataType: (memptr T_7 (struct (0 T_9 t0000)))
T_9: (in Mem7[ds:0x0064:word16] : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_10: (in ax : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in ax_13 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in 0x0001 : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: int16
T_13: (in cx <= 0x0001 : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in 0x0001 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_15: (in fn0C00_000B : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_18 (T_17)))
T_16: (in 0x0001 : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in cx - 0x0001 : word16)
  Class: Eq_4
  DataType: int16
  OrigDataType: word16
T_18: (in fn0C00_000B(cx - 0x0001) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_19: (in cx *s fn0C00_000B(cx - 0x0001) : int32)
  Class: Eq_19
  DataType: int32
  OrigDataType: int32
T_20: (in (word16) (cx *s fn0C00_000B(cx - 0x0001)) : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
