// StaggeredArraysFragment
void StaggeredArraysFragment()
StaggeredArraysFragment_entry:
	// succ:  l1
l1:
	x = p[i * 0x00000008]
	x = (p + 4)[i * 0x00000008]
StaggeredArraysFragment_exit:

// Equivalence classes ////////////
Eq_13: (struct 0008 (0 word32 dw0000) (4 word32 dw0004))
	T_13
Eq_14: (struct 0008 (4 word32 dw0004))
	T_14
// Type Variables ////////////
globals_t: (in globals : (ptr (struct)))
  Class: Eq_1
  DataType: ptr32
  OrigDataType: ptr32
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr (arr Eq_13))
  OrigDataType: (ptr (struct (0 (arr T_13) a0000)))
T_3: (in i : word32)
  Class: Eq_3
  DataType: ui32
  OrigDataType: ui32
T_4: (in 0x00000008 : word32)
  Class: Eq_4
  DataType: ui32
  OrigDataType: ui32
T_5: (in i * 0x00000008 : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in p[i * 0x00000008] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in x : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_8: (in 4 : int32)
  Class: Eq_8
  DataType: int32
  OrigDataType: int32
T_9: (in p + 4 : ptr32)
  Class: Eq_9
  DataType: (ptr (arr Eq_14))
  OrigDataType: (ptr (struct (0 (arr T_14) a0000)))
T_10: (in 0x00000008 : word32)
  Class: Eq_10
  DataType: ui32
  OrigDataType: ui32
T_11: (in i * 0x00000008 : word32)
  Class: Eq_11
  DataType: ui32
  OrigDataType: ui32
T_12: (in (p + 4)[i * 0x00000008] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_13:
  Class: Eq_13
  DataType: Eq_13
  OrigDataType: (struct 0008 (0 T_6 t0000))
T_14:
  Class: Eq_14
  DataType: Eq_14
  OrigDataType: (struct 0008 (0 T_12 t0000))
