// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	word16 ax_8 = 0x0000
	// succ:  l0C00_0002
l0C00_0002:		// pred: l0C00_0000 l0C00_0006
	branch bx == 0x0000 l0C00_000D
	// succ:  l0C00_0006 l0C00_000D
l0C00_0006:		// pred: l0C00_0002
	ax_8 = ax_8 + 0x0001
	bx = Mem0[ds:bx + 0x0004:word16]
	// succ:  l0C00_0002
	goto l0C00_0002
l0C00_000D:		// pred: l0C00_0002
	Mem15[ds:0x0200:word16] = ax_8
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_000D
	// succ: 

// Equivalence classes ////////////
Eq_4: (struct (4 (memptr Eq_7 Eq_4) ptr0004))
	T_4 (in bx : word16)
	T_5 (in 0x0000 : word16)
	T_14 (in Mem0[ds:bx + 0x0004:word16] : word16)
Eq_7: (segment (200 word16 w0200))
	T_7 (in ds : selector)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in ax_8 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3: (in 0x0000 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_4: (in bx : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_7) Eq_4)
  OrigDataType: (memptr T_7 (struct (4 T_14 t0004)))
T_5: (in 0x0000 : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_7) Eq_4)
  OrigDataType: word16
T_6: (in bx == 0x0000 : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in ds : selector)
  Class: Eq_7
  DataType: (ptr Eq_7)
  OrigDataType: (ptr (segment (200 T_9 t0200)))
T_8: (in 0x0200 : word16)
  Class: Eq_8
  DataType: (memptr (ptr Eq_7) word16)
  OrigDataType: (memptr T_7 (struct (0 T_9 t0000)))
T_9: (in Mem15[ds:0x0200:word16] : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_10: (in 0x0001 : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in ax_8 + 0x0001 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_12: (in 0x0004 : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in bx + 0x0004 : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in Mem0[ds:bx + 0x0004:word16] : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_7) Eq_4)
  OrigDataType: word16
