<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://schemata.jklnet.org/Reko/v4">
  <arch>testArch</arch>
  <platform>testOS</platform>
  <input>
    <disassembly>foo.asm</disassembly>
    <intermediate-code>foo.cod</intermediate-code>
    <user>
      <procedure name="foo">
        <signature>
          <return>
            <reg>eax</reg>
          </return>
          <arg>
            <prim domain="SignedInt" size="4" />
            <stack />
          </arg>
          <arg>
            <prim domain="SignedInt" size="4" />
            <stack />
          </arg>
        </signature>
        <address>1000:0010</address>
      </procedure>
      <call>
        <address>1000:0320</address>
        <noreturn>true</noreturn>
      </call>
      <global>
        <Address>2000:0000</Address>
        <str term="z">
          <prim domain="Character" size="1" />
        </str>
        <Name>g_20000</Name>
      </global>
    </user>
  </input>
</project>