<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://schemata.jklnet.org/Reko/v3">
  <input>
    <disassembly>foo.asm</disassembly>
    <intermediate-code>foo.cod</intermediate-code>
    <user>
      <address>0x1000:0x0</address>
      <procedure name="foo">
        <signature>
          <return>
            <reg>eax</reg>
          </return>
          <arg>
            <prim domain="SignedInt" size="4" />
            <stack />
          </arg>
          <arg>
            <prim domain="SignedInt" size="4" />
            <stack />
          </arg>
        </signature>
      </procedure>
    </user>
  </input>
</project>