// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// ds:Register ds
// cx:Register cx
// ax:Register ax
// cl:Register cl
// al:Register al
// SCZO:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	cx = Mem0[ds:bx:word16]
	cx = cx + 0x0002
	ax = cx
	al = (byte) ax (alias)
	cl = Mem0[ds:bx + 0x0002:byte]
	cl = cl ^ 0x11
	cl = cl | Mem0[ds:bx + 0x0003:byte]
	cx = DPB(cx, cl, 0, 8) (alias)
	SZO = cond(cl)
	C = false
	al = al | cl
	ax = DPB(ax, al, 0, 8) (alias)
	SZO = cond(al)
	C = false
	SCZO = C (alias)
	bx = ax
	// succ: 
fn0C00_0000_exit:
