Mem0:Global memory
fp:Temporary
sp:sp
bx:bx
    def:  def bx
    uses: branch bx == 0x0000 l0C00_0013
          branch bx > 0x0000 l0C00_000D
SCZO:Flags
Z:Flags
SZO:Flags
ax:ax
C:Flags
ds:ds
    def:  def ds
    uses: Mem19[ds:0x0100:word16] = ax_15
SCZO_10: orig: SCZO
Z_11: orig: Z
SZO_12: orig: SZO
C_13: orig: C
C_14: orig: C
ax_15: orig: ax
    def:  ax_15 = PHI(ax_20, ax_22, ax_21)
    uses: Mem19[ds:0x0100:word16] = ax_15
SZO_16: orig: SZO
Z_17: orig: Z
SCZO_18: orig: SCZO
Mem19: orig: Mem0
    def:  Mem19[ds:0x0100:word16] = ax_15
ax_20: orig: ax
    def:  ax_20 = 0xFFFF
    uses: ax_15 = PHI(ax_20, ax_22, ax_21)
ax_21: orig: ax
    def:  ax_21 = 0x0001
    uses: ax_15 = PHI(ax_20, ax_22, ax_21)
ax_22: orig: ax
    def:  ax_22 = 0x0000
    uses: ax_15 = PHI(ax_20, ax_22, ax_21)
SZO_23: orig: SZO
Z_24: orig: Z
C_25: orig: C
SCZO_26: orig: SCZO
// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:
	def bx
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	branch bx == 0x0000 l0C00_0013
	// succ:  l0C00_0005 l0C00_0013
l0C00_0005:
	branch bx > 0x0000 l0C00_000D
	// succ:  l0C00_0007 l0C00_000D
l0C00_0007:
	ax_20 = 0xFFFF
	goto l0C00_0015
	// succ:  l0C00_0015
l0C00_000D:
	ax_21 = 0x0001
	goto l0C00_0015
	// succ:  l0C00_0015
l0C00_0013:
	ax_22 = 0x0000
	// succ:  l0C00_0015
l0C00_0015:
	ax_15 = PHI(ax_20, ax_22, ax_21)
	Mem19[ds:0x0100:word16] = ax_15
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

