fp:fp
sp_1: orig: sp
cx_2: orig: cx
ax_3: orig: ax
Mem4: orig: Mem0
    def:  Mem4[ds:0x0064:word16] = fn0C00_000B(0x0005)
ds:ds
    def:  def ds
    uses: Mem4[ds:0x0064:word16] = fn0C00_000B(0x0005)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	Mem4[ds:0x0064:word16] = fn0C00_000B(0x0005)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
sp_1: orig: sp
sp_2: orig: sp
si:si
wLoc02_4: orig: wLoc02
cx:cx
    def:  def cx
    uses: branch cx <= 0x0001 l0C00_001C
          ax_21 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
          ax_21 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
SCZO_6: orig: SCZO
SZO_7: orig: SZO
cx_8: orig: cx
dx_ax_9: orig: dx_ax
ax_10: orig: ax
    def:  ax_10 = PHI(ax_21, ax_25)
    uses: return ax_10
dx_11: orig: dx
SCZO_12: orig: SCZO
SZO_13: orig: SZO
si_14: orig: si
sp_15: orig: sp
si_16: orig: si
cx_17: orig: cx
SZO_18: orig: SZO
ax_19: orig: ax
dx_ax_20: orig: dx_ax
ax_21: orig: ax
    def:  ax_21 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
    uses: ax_10 = PHI(ax_21, ax_25)
dx_22: orig: dx
SCZO_23: orig: SCZO
SZO_24: orig: SZO
ax_25: orig: ax
    def:  ax_25 = 0x0001
    uses: ax_10 = PHI(ax_21, ax_25)
dx:dx
dx_ax_27: orig: dx_ax
// fn0C00_000B
// Return size: 0
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:
	def cx
	// succ:  l0C00_000B
l0C00_000B:
	branch cx <= 0x0001 l0C00_001C
	// succ:  l0C00_0011 l0C00_001C
l0C00_0011:
	ax_21 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
	goto l0C00_001F
	// succ:  l0C00_001F
l0C00_001C:
	ax_25 = 0x0001
	// succ:  l0C00_001F
l0C00_001F:
	ax_10 = PHI(ax_21, ax_25)
	return ax_10
	// succ:  fn0C00_000B_exit
fn0C00_000B_exit:

