Mem0:Global memory
fp:Temporary
sp:sp
si:si
ax:ax
ds:ds
    def:  def ds
    uses: Mem9[ds:0x0202:word16] = fn0C00_0015(0x0200, ds)
          Mem9[ds:0x0202:word16] = fn0C00_0015(0x0200, ds)
          Mem13[ds:0x0302:byte] = (byte) fn0C00_0015(0x0300, ds)
          Mem13[ds:0x0302:byte] = (byte) fn0C00_0015(0x0300, ds)
al:al
si_7: orig: si
ax_8: orig: ax
    uses: Mem9[ds:0x0202:word16] = fn0C00_0015(0x0200, ds)
Mem9: orig: Mem0
    def:  Mem9[ds:0x0202:word16] = fn0C00_0015(0x0200, ds)
si_10: orig: si
ax_11: orig: ax
al_12: orig: al
    uses: Mem13[ds:0x0302:byte] = (byte) fn0C00_0015(0x0300, ds)
Mem13: orig: Mem0
    def:  Mem13[ds:0x0302:byte] = (byte) fn0C00_0015(0x0300, ds)
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	Mem9[ds:0x0202:word16] = fn0C00_0015(0x0200, ds)
	Mem13[ds:0x0302:byte] = (byte) fn0C00_0015(0x0300, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

Mem0:Global memory
    def:  def Mem0
    uses: return Mem0[ds:si:word16]
fp:Temporary
sp:sp
si:si
    def:  def si
    uses: return Mem0[ds:si:word16]
ds:ds
    def:  def ds
    uses: return Mem0[ds:si:word16]
ax:ax
ax_6: orig: ax
    uses: return Mem0[ds:si:word16]
// fn0C00_0015
word16 fn0C00_0015(word16 si, selector ds)
fn0C00_0015_entry:
	def Mem0
	def si
	def ds
	// succ:  l0C00_0015
l0C00_0015:
	return Mem0[ds:si:word16]
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:

