Register word32 fn10000000(Stack word32 dwArg00)
// MayUse: 
// LiveOut: eax
// Trashed: SCZO eax ax al ah
// Preserved: esi edi
// Stack args: Stack +0000(32)
// fn10000000
// Mem0:Global memory
// fp:Temporary
// esi:Register esi
// dwLoc08:Local -0008
// dwArg00:Stack +0000
// SCZO:Flags
// SZO:Flags
// eax:Register eax
// edi:Register edi
// dwLoc0C:Local -000C
// dwLoc10:Local -0010
// dwLoc14:Local -0014
// return address size: 4
word32 fn10000000(word32 dwArg00)
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	dwLoc08 = esi
	esi = dwArg00
	SCZO = cond(esi - 0x00000001)
	branch Test(GT,SZO) l10000011
	// succ:  3 2
l10000011:		// block 2, pred: 1
	eax = esi - 0x00000002
	dwLoc0C = edi
	dwLoc10 = eax
	eax = fn10000000(dwLoc10)
	esi = esi - 0x00000001
	dwLoc14 = esi
	edi = eax
	eax = fn10000000(dwLoc14)
	eax = eax + edi
	SCZO = cond(eax)
	edi = dwLoc0C
	esi = dwLoc08
	return eax
	// succ:  4
l1000000A:		// block 3, pred: 1
	eax = 0x00000001
	esi = dwLoc08
	return eax
	// succ:  4
fn10000000_exit:		// block 4, pred: 2 3
	// succ: 
