void fn0C00_0000(Register word16 ax, Register word16 bx, Register selector ds)
// MayUse:  ax bx ds
// LiveOut:
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// bx:Register bx
// SCZO:Flags
// Z:Flags
// ds:Register ds
// return address size: 2
void fn0C00_0000(word16 ax, word16 bx, selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	SCZO = cond(ax - bx)
	branch Test(EQ,Z) l0C00_000A
	// succ:  l0C00_0004 l0C00_000A
l0C00_0004:		// pred: l0C00_0000
	ax = 0x0000
	// succ:  l0C00_000D
l0C00_000D:		// pred: l0C00_000A l0C00_0004
	Mem0[ds:0x0064:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_000D
	// succ: 
l0C00_000A:		// pred: l0C00_0000
	ax = 0x0001
	// succ:  l0C00_000D
