void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: ax si al ah
// Preserved: sp
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:sp
// si:si
// ds:ds
// ax:ax
// al:al
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	si = 0x0200
	ax = fn0C00_0015(si, ds)
	Mem0[ds:0x0202:word16] = ax
	si = 0x0300
	ax = fn0C00_0015(si, ds)
	Mem0[ds:0x0302:byte] = al
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
Register word16 fn0C00_0015(Register word16 si, Register selector ds)
// MayUse:  si ds
// LiveOut: ax al
// Trashed: ax al ah
// Preserved: sp
// fn0C00_0015
// Mem0:Global memory
// fp:Temporary
// sp:sp
// ax:ax
// si:si
// ds:ds
// return address size: 2
word16 fn0C00_0015(word16 si, selector ds)
fn0C00_0015_entry:
	// succ:  l0C00_0015
l0C00_0015:
	ax = Mem0[ds:si:word16]
	return ax
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:
