void fn0C00_0000(Register word16 di, Register selector ds)
// MayUse:  di ds
// LiveOut:
// Trashed: SCZO ax bx si al bl ah bh
// Preserved: sp
// fn0C00_0000
// Mem0:Global memory
// fp:fp
// sp:sp
// si:si
// ss:ss
// SCZO:Flags
// wLoc02:Local -0002
// di:di
// ds:ds
// return address size: 2
void fn0C00_0000(word16 di, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	si = 0x0100
	fn0C00_0010(si, di, ds)
	sp = fp - 0x0002
	wLoc02 = 0x0100
	fn0C00_0017(di, ds, wLoc02)
	sp = fp
	SCZO = cond(fp)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
void fn0C00_0010(Register word16 si, Register word16 di, Register selector ds)
// MayUse:  si di ds
// LiveOut:
// Trashed: ax al ah
// Preserved: sp
// fn0C00_0010
// Mem0:Global memory
// fp:fp
// sp:sp
// ax:ax
// si:si
// ds:ds
// di:di
// return address size: 2
void fn0C00_0010(word16 si, word16 di, selector ds)
fn0C00_0010_entry:
	// succ:  l0C00_0010
l0C00_0010:
	ax = Mem0[ds:si + 0x0002:word16]
	fn0C00_0029(ax, di, ds)
	return
	// succ:  fn0C00_0010_exit
fn0C00_0010_exit:
void fn0C00_0017(Register word16 di, Register selector ds, Stack word16 wArg02)
// MayUse:  di ds
// LiveOut:
// Trashed: SCZO ax bx al bl ah bh
// Preserved: sp bp
// Stack args: Stack +0002(16)
// fn0C00_0017
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// bx:bx
// ax:ax
// ds:ds
// SCZO:Flags
// wLoc02:Local -0002
// wArg02:Stack +0002
// wLoc04:Local -0004
// di:di
// return address size: 2
void fn0C00_0017(word16 di, selector ds, word16 wArg02)
fn0C00_0017_entry:
	// succ:  l0C00_0017
l0C00_0017:
	sp = fp - 0x0002
	wLoc02 = bp
	bp = fp - 0x0002
	bx = wArg02
	ax = Mem0[ds:bx + 0x0002:word16]
	sp = fp - 0x0004
	wLoc04 = ax
	fn0C00_002C(di, ds, wLoc04)
	sp = fp - 0x0002
	SCZO = cond(fp - 0x0002)
	bp = wLoc02
	sp = fp
	return
	// succ:  fn0C00_0017_exit
fn0C00_0017_exit:
void fn0C00_0029(Register word16 ax, Register word16 di, Register selector ds)
// MayUse:  ax di ds
// LiveOut:
// Trashed:
// Preserved: sp
// fn0C00_0029
// Mem0:Global memory
// fp:fp
// sp:sp
// di:di
// ds:ds
// ax:ax
// return address size: 2
void fn0C00_0029(word16 ax, word16 di, selector ds)
fn0C00_0029_entry:
	// succ:  l0C00_0029
l0C00_0029:
	Mem0[ds:di:word16] = ax
	return
	// succ:  fn0C00_0029_exit
fn0C00_0029_exit:
void fn0C00_002C(Register word16 di, Register selector ds, Stack word16 wArg02)
// MayUse:  di ds
// LiveOut:
// Trashed: ax al ah
// Preserved: sp bp
// Stack args: Stack +0002(16)
// fn0C00_002C
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// ax:ax
// di:di
// ds:ds
// wLoc02:Local -0002
// wArg02:Stack +0002
// return address size: 2
void fn0C00_002C(word16 di, selector ds, word16 wArg02)
fn0C00_002C_entry:
	// succ:  l0C00_002C
l0C00_002C:
	sp = fp - 0x0002
	wLoc02 = bp
	bp = fp - 0x0002
	ax = wArg02
	Mem0[ds:di:word16] = ax
	bp = wLoc02
	sp = fp
	return
	// succ:  fn0C00_002C_exit
fn0C00_002C_exit:
