// void fn10000000(Stack word32 dwArg00)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse: 
// LiveOut:
// Trashed: eax ax al ah
// Preserved: esi edi
// Stack args: Stack +0000(32)
// fn10000000
void fn10000000(word32 dwArg00)
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	GlobalUnlock(GlobalHandle(dwArg00))
	GlobalFree(GlobalHandle(dwArg00))
	return
	// succ:  2
fn10000000_exit:		// block 2, pred: 1
	// succ: 

