// void ManyIncrements(Register word32 r0)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  r0
// LiveOut:
// Trashed: r0 r1
// Preserved: r63
// ManyIncrements
// Return size: 0
void ManyIncrements(word32 r0)
ManyIncrements_entry:
	goto loopTop
	// succ:  loopTop
done:
	return
	// succ:  ManyIncrements_exit
l1:
	Mem7[0x33333330:word32] = Mem0[r0_4:byte]
	Mem10[0x33333331:word32] = Mem7[r0_4 + 0x00000001:byte]
	r0 = r0_4 + 0x00000002
	goto loopTop
	// succ:  loopTop
l2:
	Mem13[0x33333330:word32] = Mem0[r0_4:byte]
	r0 = r0_4 + 0x00000001
	// succ:  loopTop
loopTop:
	word32 r1_3 = Mem0[r0:byte]
	word32 r0_4 = r0 + 0x00000001
	branch r1_3 != 1 not1
	goto l1
	// succ:  l1 not1
not1:
	branch r1_3 != 2 done
	goto l2
	// succ:  l2 done
ManyIncrements_exit:

