// ArrayLoopMock
void ArrayLoopMock()
ArrayLoopMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	ptr_3 = 0x04000000
	// succ:  2
looptest:		// block 2, pred: 1 5
	ptr_4 = PHI(ptr_3, ptr_7)
	branch ptr_4 >=u 0x04001000 done
	// succ:  5 3
done:		// block 3, pred: 2
	return
	// succ:  4
ArrayLoopMock_exit:		// block 4, pred: 3
	// succ: 
l2:		// block 5, pred: 2
	store(Mem6[ptr_4:word32]) = 0x00000000
	ptr_7 = ptr_4 + 0x00000004
	// succ:  2

(0x04000000 0x00000004 0x04001000)
