// ProcedureBuilder
void ProcedureBuilder()
ProcedureBuilder_entry:
	def Mem0
	def fp
	def p
	goto l1
	// succ:  l1
done:
	return
	// succ:  ProcedureBuilder_exit
l1:
	p_3 = 0x00003000
	goto loop
	// succ:  loop
l2:
	Mem5[p_4 + 0x00000000:word32] = 0x00000000
	p_6 = p_4 + 0x00000004
	// succ:  loop
loop:
	p_4 = PHI(p_3, p_6)
	branch p_4 == 0x00001000 done
	goto l2
	// succ:  l2 done
ProcedureBuilder_exit:
