Mem0:Global memory
    def:  def Mem0
    uses: r1_4 = Mem0[r2:word32]
fp:fp
    def:  def fp
    uses: call r1_4 (retsize: 4;)
r1:r1
    def:  def r1
r2:r2
    def:  def r2
    uses: r1_4 = Mem0[r2:word32]
          call r1_4 (retsize: 4;)
r1_4: orig: r1
    def:  r1_4 = Mem0[r2:word32]
    uses: call r1_4 (retsize: 4;)
          call r1_4 (retsize: 4;)
// SsaCallIndirect
void SsaCallIndirect()
SsaCallIndirect_entry:
	def Mem0
	def fp
	def r1
	def r2
	// succ:  l1
l1:
	r1_4 = Mem0[r2:word32]
	call r1_4 (retsize: 4;)
	return
	// succ:  SsaCallIndirect_exit
SsaCallIndirect_exit:
