Mem0: Mem0:Global memory, def: {def Mem0}
fp: fp:Temporary, def: {def fp}
cx: cx:Register cx, def: {def cx}
ax: ax:Register ax, def: {def ax}, uses: {call fn0C00_000B (depth: 2;)}{store(Mem6[ds:0x0064:word16]) = ax}
ds: ds:Register ds, def: {def ds}, uses: {call fn0C00_000B (depth: 2;)}{store(Mem6[ds:0x0064:word16]) = ax}
cx_5: orig: cx, def: {cx_5 = 0x0005}, uses: {call fn0C00_000B (depth: 2;)}
Mem6: orig: Mem0, def: {store(Mem6[ds:0x0064:word16]) = ax}
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	def Mem0
	def fp
	def cx
	def ax
	def ds
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	cx_5 = 0x0005
	call fn0C00_000B (depth: 2;)
	store(Mem6[ds:0x0064:word16]) = ax
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

Mem0: Mem0:Global memory, def: {def Mem0}
fp: fp:Temporary, def: {def fp}
si: si:Register si, def: {def si}, uses: {wLoc04_10 = si}
wLoc04: wLoc04:Local -0004, def: {def wLoc04}
cx: cx:Register cx, def: {def cx}, uses: {SCZO_11 = cond(cx - 0x0001)}{cx_28 = PHI(cx_16, cx)}{si_15 = cx}{cx_16 = cx - 0x0001}
SCZO: SCZO:Flags, def: {def SCZO}
SZO: SZO:Flags, def: {def SZO}
ax: ax:Register ax, def: {def ax}, uses: {call fn0C00_000B (depth: 4;)}{dx_ax_18 = si_15 *s ax}
dx: dx:Register dx, def: {def dx}, uses: {dx_ax_14 = SEQ(dx, ax_13) (alias)}{dx_24 = PHI(dx_20, dx)}{call fn0C00_000B (depth: 4;)}
dx_ax: dx_ax:Sequence dx:ax, def: {def dx_ax}
wLoc04_10: orig: wLoc04, def: {wLoc04_10 = si}, uses: {si_29 = wLoc04_10}
SCZO_11: orig: SCZO, def: {SCZO_11 = cond(cx - 0x0001)}, uses: {SZO_12 = SCZO_11 (alias)}{SCZO_27 = PHI(SCZO_21, SCZO_11)}{call fn0C00_000B (depth: 4;)}
SZO_12: orig: SZO, def: {SZO_12 = SCZO_11 (alias)}, uses: {branch Test(LE,SZO_12) l0C00_001C}{SZO_26 = PHI(SZO_22, SZO_12)}
ax_13: orig: ax, def: {ax_13 = 0x0001}, uses: {dx_ax_14 = SEQ(dx, ax_13) (alias)}{ax_25 = PHI(ax_19, ax_13)}
dx_ax_14: orig: dx_ax, def: {dx_ax_14 = SEQ(dx, ax_13) (alias)}, uses: {dx_ax_23 = PHI(dx_ax_18, dx_ax_14)}
si_15: orig: si, def: {si_15 = cx}, uses: {call fn0C00_000B (depth: 4;)}{dx_ax_18 = si_15 *s ax}
cx_16: orig: cx, def: {cx_16 = cx - 0x0001}, uses: {SZO_17 = cond(cx_16)}{call fn0C00_000B (depth: 4;)}{cx_28 = PHI(cx_16, cx)}
SZO_17: orig: SZO, def: {SZO_17 = cond(cx_16)}, uses: {call fn0C00_000B (depth: 4;)}
dx_ax_18: orig: dx_ax, def: {dx_ax_18 = si_15 *s ax}, uses: {ax_19 = (word16) dx_ax_18 (alias)}{dx_20 = SLICE(dx_ax_18, word16, 16) (alias)}{SCZO_21 = cond(dx_ax_18)}{dx_ax_23 = PHI(dx_ax_18, dx_ax_14)}
ax_19: orig: ax, def: {ax_19 = (word16) dx_ax_18 (alias)}, uses: {ax_25 = PHI(ax_19, ax_13)}
dx_20: orig: dx, def: {dx_20 = SLICE(dx_ax_18, word16, 16) (alias)}, uses: {dx_24 = PHI(dx_20, dx)}
SCZO_21: orig: SCZO, def: {SCZO_21 = cond(dx_ax_18)}, uses: {SZO_22 = SCZO_21 (alias)}{SCZO_27 = PHI(SCZO_21, SCZO_11)}
SZO_22: orig: SZO, def: {SZO_22 = SCZO_21 (alias)}, uses: {SZO_26 = PHI(SZO_22, SZO_12)}
dx_ax_23: orig: dx_ax, def: {dx_ax_23 = PHI(dx_ax_18, dx_ax_14)}
dx_24: orig: dx, def: {dx_24 = PHI(dx_20, dx)}
ax_25: orig: ax, def: {ax_25 = PHI(ax_19, ax_13)}
SZO_26: orig: SZO, def: {SZO_26 = PHI(SZO_22, SZO_12)}
SCZO_27: orig: SCZO, def: {SCZO_27 = PHI(SCZO_21, SCZO_11)}
cx_28: orig: cx, def: {cx_28 = PHI(cx_16, cx)}
si_29: orig: si, def: {si_29 = wLoc04_10}
// fn0C00_000B
void fn0C00_000B()
fn0C00_000B_entry:		// block 0, pred:
	def Mem0
	def fp
	def si
	def wLoc04
	def cx
	def SCZO
	def SZO
	def ax
	def dx
	def dx_ax
	// succ:  1
l0C00_000B:		// block 1, pred: 0
	wLoc04_10 = si
	SCZO_11 = cond(cx - 0x0001)
	SZO_12 = SCZO_11 (alias)
	branch Test(LE,SZO_12) l0C00_001C
	// succ:  3 2
l0C00_001C:		// block 2, pred: 1
	ax_13 = 0x0001
	dx_ax_14 = SEQ(dx, ax_13) (alias)
	// succ:  4
l0C00_0011:		// block 3, pred: 1
	si_15 = cx
	cx_16 = cx - 0x0001
	SZO_17 = cond(cx_16)
	call fn0C00_000B (depth: 4;)
	dx_ax_18 = si_15 *s ax
	ax_19 = (word16) dx_ax_18 (alias)
	dx_20 = SLICE(dx_ax_18, word16, 16) (alias)
	SCZO_21 = cond(dx_ax_18)
	SZO_22 = SCZO_21 (alias)
	// succ:  4
l0C00_001F:		// block 4, pred: 3 2
	dx_ax_23 = PHI(dx_ax_18, dx_ax_14)
	dx_24 = PHI(dx_20, dx)
	ax_25 = PHI(ax_19, ax_13)
	SZO_26 = PHI(SZO_22, SZO_12)
	SCZO_27 = PHI(SCZO_21, SCZO_11)
	cx_28 = PHI(cx_16, cx)
	si_29 = wLoc04_10
	return
	// succ:  5
fn0C00_000B_exit:		// block 5, pred: 4
	// succ: 

