Mem0: Mem0:Global memory, def: {def Mem0}, uses: {ecx_35 = (int32) Mem0[eax_31 + 0x00000006:word16]}{edx_36 = (int32) Mem0[eax_31 + 0x00000002:word16]}
fp: fp:Temporary, def: {def fp}
dwArg04: dwArg04:Stack +0004, def: {def dwArg04}, uses: {eax_31 = dwArg04}{dwArg04_207 = PHI(dwArg04_107, dwArg04_107, dwArg04)}
eax: eax:Register, def: {def eax}
ebx: ebx:Register, def: {def ebx}, uses: {dwLoc04_32 = ebx}
dwLoc04: dwLoc04:Local -0004, def: {def dwLoc04}
dwArg06: dwArg06:Stack +0006, def: {def dwArg06}, uses: {ebx_33 = dwArg06}
ebp: ebp:Register, def: {def ebp}, uses: {dwLoc08_34 = ebp}
dwLoc08: dwLoc08:Local -0008, def: {def dwLoc08}
ecx: ecx:Register, def: {def ecx}
edx: edx:Register, def: {def edx}
dwArg08: dwArg08:Stack +0008, def: {def dwArg08}, uses: {ebp_37 = dwArg08}
dwArg10: dwArg10:Stack +0010, def: {def dwArg10}, uses: {edx_39 = dwArg10}{ecx_175 = dwArg10}
SCZO: SCZO:Flags, def: {def SCZO}
C: C:Flags, def: {def C}
dwArg0C: dwArg0C:Stack +000C, def: {def dwArg0C}
Z: Z:Flags, def: {def Z}
rLoc1: rLoc1:FPU stack, def: {def rLoc1}, uses: {rLoc1_199 = PHI(rLoc1_108, rLoc1_108, rLoc1)}
esi: esi:Register, def: {def esi}, uses: {esi_198 = PHI(esi_182, esi_182, esi)}{dwLoc0C_56 = esi}
dwLoc0C: dwLoc0C:Local -000C, def: {def dwLoc0C}, uses: {dwLoc0C_197 = PHI(dwLoc0C_56, dwLoc0C_56, dwLoc0C)}
edi: edi:Register, def: {def edi}, uses: {edi_196 = PHI(edi_181, edi_181, edi)}{dwLoc10_57 = edi}
dwLoc10: dwLoc10:Local -0010, def: {def dwLoc10}, uses: {dwLoc10_195 = PHI(dwLoc10_57, dwLoc10_57, dwLoc10)}
rArg0C: rArg0C:Stack +000C, def: {def rArg0C}, uses: {rArg0C_53 = DPB(rArg0C, dwArg0C_52, 0, 32) (alias)}
rLoc2: rLoc2:FPU stack, def: {def rLoc2}, uses: {rLoc2_193 = PHI(rLoc2_113, rLoc2_113, rLoc2)}
SZO: SZO:Flags, def: {def SZO}
ax: ax:Register, def: {def ax}
ah: ah:Register, def: {def ah}
rArg04: rArg04:Stack +0004, def: {def rArg04}, uses: {rArg04_189 = PHI(rArg04_105, rArg04_105, rArg04)}{rArg04_66 = DPB(rArg04, dwArg04_65, 0, 32) (alias)}
rLoc3: rLoc3:FPU stack, def: {def rLoc3}, uses: {rLoc3_188 = PHI(rLoc3_133, rLoc3_133, rLoc3)}{rLoc3_69 = PHI(rLoc3, rLoc3_133)}
rLoc4: rLoc4:FPU stack, def: {def rLoc4}, uses: {rLoc4_187 = PHI(rLoc4_173, rLoc4_173, rLoc4)}{rLoc4_68 = PHI(rLoc4, rLoc4_137)}
SO: SO:Flags, def: {def SO}
eax_31: orig: eax, def: {eax_31 = dwArg04}, uses: {ecx_35 = (int32) Mem0[eax_31 + 0x00000006:word16]}{edx_36 = (int32) Mem0[eax_31 + 0x00000002:word16]}{ecx_41 = (int32) Mem40[eax_31 + 0x00000004:word16]}{eax_42 = (int32) Mem40[eax_31:word16]}
dwLoc04_32: orig: dwLoc04, def: {dwLoc04_32 = ebx}, uses: {ebx_210 = dwLoc04_32}
ebx_33: orig: ebx, def: {ebx_33 = dwArg06}, uses: {store(Mem40[ebx_33:word32]) = ecx_38}{rLoc1_55 = Mem54[ebx_33:real64]}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 4;)}{store(Mem174[ebx_33:word32]) = eax_167}{call fn10000108 (depth: 16; FPU: 3;)}{store(Mem184[ebx_33:word32]) = 0x00000000}
dwLoc08_34: orig: dwLoc08, def: {dwLoc08_34 = ebp}, uses: {ebp_209 = dwLoc08_34}
ecx_35: orig: ecx, def: {ecx_35 = (int32) Mem0[eax_31 + 0x00000006:word16]}, uses: {ecx_38 = ecx_35 - edx_36}
edx_36: orig: edx, def: {edx_36 = (int32) Mem0[eax_31 + 0x00000002:word16]}, uses: {ecx_38 = ecx_35 - edx_36}
ebp_37: orig: ebp, def: {ebp_37 = dwArg08}, uses: {SCZO_46 = cond(ebp_37 - 0x00000000)}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 2;)}{SCZO_168 = cond(esi_77 - ebp_37)}{call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}{SCZO_176 = cond(ebp_37 - edi_166)}
ecx_38: orig: ecx, def: {ecx_38 = ecx_35 - edx_36}, uses: {store(Mem40[ebx_33:word32]) = ecx_38}
edx_39: orig: edx, def: {edx_39 = dwArg10}, uses: {store(Mem54[edx_39:word32]) = ecx_45}{edx_204 = PHI(edx_39, edx_39, edx_39)}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}{edx_204 = PHI(edx_39, edx_39, edx_39)}{edx_204 = PHI(edx_39, edx_39, edx_39)}
Mem40: orig: Mem0, def: {store(Mem40[ebx_33:word32]) = ecx_38}, uses: {ecx_41 = (int32) Mem40[eax_31 + 0x00000004:word16]}{eax_42 = (int32) Mem40[eax_31:word16]}
ecx_41: orig: ecx, def: {ecx_41 = (int32) Mem40[eax_31 + 0x00000004:word16]}, uses: {ecx_45 = ecx_41 - eax_42}
eax_42: orig: eax, def: {eax_42 = (int32) Mem40[eax_31:word16]}, uses: {ax_43 = (word16) eax_42 (alias)}{ah_44 = SLICE(eax_42, byte, 8) (alias)}{ecx_45 = ecx_41 - eax_42}{eax_206 = PHI(eax_167, eax_167, eax_42)}{call fn10000108 (depth: 16; FPU: 2;)}{ecx_81 = eax_42}{eax_87 = DPB(eax_42, ax_86, 0, 16) (alias)}
ax_43: orig: ax, def: {ax_43 = (word16) eax_42 (alias)}, uses: {ax_191 = PHI(ax_165, ax_165, ax_43)}{call fn10000108 (depth: 16; FPU: 2;)}
ah_44: orig: ah, def: {ah_44 = SLICE(eax_42, byte, 8) (alias)}, uses: {ah_190 = PHI(ah_164, ah_164, ah_44)}{call fn10000108 (depth: 16; FPU: 2;)}
ecx_45: orig: ecx, def: {ecx_45 = ecx_41 - eax_42}, uses: {dwArg0C_52 = ecx_45}{store(Mem54[edx_39:word32]) = ecx_45}{ecx_205 = PHI(ecx_175, ecx_175, ecx_45)}{call fn10000108 (depth: 16; FPU: 2;)}
SCZO_46: orig: SCZO, def: {SCZO_46 = cond(ebp_37 - 0x00000000)}, uses: {Z_47 = SCZO_46 (alias)}{SZO_48 = SCZO_46 (alias)}{SO_49 = SCZO_46 (alias)}
Z_47: orig: Z, def: {Z_47 = SCZO_46 (alias)}, uses: {branch Test(EQ,Z_47)}{Z_200 = PHI(Z_178, Z_178, Z_47)}
SZO_48: orig: SZO, def: {SZO_48 = SCZO_46 (alias)}, uses: {SZO_192 = PHI(SZO_179, SZO_179, SZO_48)}
SO_49: orig: SO, def: {SO_49 = SCZO_46 (alias)}, uses: {SO_186 = PHI(SO_180, SO_180, SO_49)}
C_50: orig: C, def: {C_50 = false}, uses: {SCZO_51 = C_50 (alias)}{C_202 = PHI(C_177, C_177, C_50)}
SCZO_51: orig: SCZO, def: {SCZO_51 = C_50 (alias)}, uses: {SCZO_203 = PHI(SCZO_176, SCZO_176, SCZO_51)}
dwArg0C_52: orig: dwArg0C, def: {dwArg0C_52 = ecx_45}, uses: {rArg0C_53 = DPB(rArg0C, dwArg0C_52, 0, 32) (alias)}{dwArg0C_201 = PHI(dwArg0C_135, dwArg0C_135, dwArg0C_52)}
rArg0C_53: orig: rArg0C, def: {rArg0C_53 = DPB(rArg0C, dwArg0C_52, 0, 32) (alias)}, uses: {rArg0C_194 = PHI(rArg0C_134, rArg0C_134, rArg0C_53)}{rLoc1_67 = rArg0C_53}{rArg0C_71 = PHI(rArg0C_53, rArg0C_134)}
Mem54: orig: Mem0, def: {store(Mem54[edx_39:word32]) = ecx_45}, uses: {Mem208 = PHI(Mem185, Mem183, Mem54)}{rLoc1_55 = Mem54[ebx_33:real64]}{rLoc2_76 = rLoc2_75 * Mem54[0x0099188A:real64]}{rLoc1_108 = rLoc1_73 * Mem54[0x10033290:real64]}{C_138 = rLoc4_137 - Mem54[0x10033298:real64]}{C_148 = rLoc3_133 - Mem54[0x10033298:real64]}
rLoc1_55: orig: rLoc1, def: {rLoc1_55 = Mem54[ebx_33:real64]}, uses: {dwArg04_65 = rLoc1_55}
dwLoc0C_56: orig: dwLoc0C, def: {dwLoc0C_56 = esi}, uses: {esi_182 = dwLoc0C_56}{dwLoc0C_197 = PHI(dwLoc0C_56, dwLoc0C_56, dwLoc0C)}{dwLoc0C_197 = PHI(dwLoc0C_56, dwLoc0C_56, dwLoc0C)}
dwLoc10_57: orig: dwLoc10, def: {dwLoc10_57 = edi}, uses: {edi_181 = dwLoc10_57}{dwLoc10_195 = PHI(dwLoc10_57, dwLoc10_57, dwLoc10)}{dwLoc10_195 = PHI(dwLoc10_57, dwLoc10_57, dwLoc10)}
esi_58: orig: esi, def: {esi_58 = 0x00000000}, uses: {SCZO_59 = cond(esi_58)}{esi_72 = PHI(esi_58, esi_77)}
SCZO_59: orig: SCZO, def: {SCZO_59 = cond(esi_58)}, uses: {C_60 = SCZO_59 (alias)}{Z_61 = SCZO_59 (alias)}{SZO_62 = SCZO_59 (alias)}{SO_63 = SCZO_59 (alias)}{call fn10000108 (depth: 16; FPU: 2;)}
C_60: orig: C, def: {C_60 = SCZO_59 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
Z_61: orig: Z, def: {Z_61 = SCZO_59 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
SZO_62: orig: SZO, def: {SZO_62 = SCZO_59 (alias)}
SO_63: orig: SO, def: {SO_63 = SCZO_59 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
edi_64: orig: edi, def: {edi_64 = 0x000186A0}, uses: {call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 2;)}{edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)}{edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)}{SCZO_158 = cond(edi_64 - 0x000186A0)}{edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)}
dwArg04_65: orig: dwArg04, def: {dwArg04_65 = rLoc1_55}, uses: {rArg04_66 = DPB(rArg04, dwArg04_65, 0, 32) (alias)}{dwArg04_74 = PHI(dwArg04_65, dwArg04_107)}
rArg04_66: orig: rArg04, def: {rArg04_66 = DPB(rArg04, dwArg04_65, 0, 32) (alias)}, uses: {rArg04_70 = PHI(rArg04_66, rArg04_105)}
rLoc1_67: orig: rLoc1, def: {rLoc1_67 = rArg0C_53}, uses: {rLoc1_73 = PHI(rLoc1_67, rLoc1_108)}
rLoc4_68: orig: rLoc4, def: {rLoc4_68 = PHI(rLoc4, rLoc4_137)}
rLoc3_69: orig: rLoc3, def: {rLoc3_69 = PHI(rLoc3, rLoc3_133)}
rArg04_70: orig: rArg04, def: {rArg04_70 = PHI(rArg04_66, rArg04_105)}, uses: {rArg04_80 = DPB(rArg04_70, dwArg04_79, 0, 32) (alias)}
rArg0C_71: orig: rArg0C, def: {rArg0C_71 = PHI(rArg0C_53, rArg0C_134)}, uses: {rArg0C_83 = DPB(rArg0C_71, dwArg0C_82, 0, 32) (alias)}
esi_72: orig: esi, def: {esi_72 = PHI(esi_58, esi_77)}, uses: {esi_77 = esi_72 + 0x00000001}
rLoc1_73: orig: rLoc1, def: {rLoc1_73 = PHI(rLoc1_67, rLoc1_108)}, uses: {rLoc1_108 = rLoc1_73 * Mem54[0x10033290:real64]}
dwArg04_74: orig: dwArg04, def: {dwArg04_74 = PHI(dwArg04_65, dwArg04_107)}, uses: {rLoc2_75 = dwArg04_74}
rLoc2_75: orig: rLoc2, def: {rLoc2_75 = dwArg04_74}, uses: {rLoc2_76 = rLoc2_75 * Mem54[0x0099188A:real64]}
rLoc2_76: orig: rLoc2, def: {rLoc2_76 = rLoc2_75 * Mem54[0x0099188A:real64]}, uses: {dwArg04_79 = rLoc2_76}
esi_77: orig: esi, def: {esi_77 = esi_72 + 0x00000001}, uses: {SZO_78 = cond(esi_77)}{call fn10000108 (depth: 16; FPU: 2;)}{call fn10000108 (depth: 16; FPU: 2;)}{edi_163 = esi_77}{SCZO_168 = cond(esi_77 - ebp_37)}{esi_72 = PHI(esi_58, esi_77)}{call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
SZO_78: orig: SZO, def: {SZO_78 = cond(esi_77)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
dwArg04_79: orig: dwArg04, def: {dwArg04_79 = rLoc2_76}, uses: {rArg04_80 = DPB(rArg04_70, dwArg04_79, 0, 32) (alias)}{C_85 = rLoc2_84 - dwArg04_79}{dwArg04_107 = PHI(dwArg04_103, dwArg04_79)}
rArg04_80: orig: rArg04, def: {rArg04_80 = DPB(rArg04_70, dwArg04_79, 0, 32) (alias)}, uses: {rArg04_105 = PHI(rArg04_104, rArg04_80)}{rArg04_101 = DPB(rArg04_80, dwArg04_100, 0, 32) (alias)}
ecx_81: orig: ecx, def: {ecx_81 = eax_42}, uses: {dwArg0C_82 = ecx_81}{ecx_95 = ecx_81 + 0x00000001}{call fn10000108 (depth: 16; FPU: 2;)}
dwArg0C_82: orig: dwArg0C, def: {dwArg0C_82 = ecx_81}, uses: {rArg0C_83 = DPB(rArg0C_71, dwArg0C_82, 0, 32) (alias)}
rArg0C_83: orig: rArg0C, def: {rArg0C_83 = DPB(rArg0C_71, dwArg0C_82, 0, 32) (alias)}, uses: {rLoc2_84 = rArg0C_83}{rArg0C_112 = DPB(rArg0C_83, dwArg0C_111, 0, 32) (alias)}
rLoc2_84: orig: rLoc2, def: {rLoc2_84 = rArg0C_83}, uses: {C_85 = rLoc2_84 - dwArg04_79}{rLoc2_106 = PHI(rLoc2_102, rLoc2_84)}
C_85: orig: C, def: {C_85 = rLoc2_84 - dwArg04_79}, uses: {ax_86 = C_85}
ax_86: orig: ax, def: {ax_86 = C_85}, uses: {eax_87 = DPB(eax_42, ax_86, 0, 16) (alias)}{ah_88 = SLICE(ax_86, byte, 8) (alias)}{call fn10000108 (depth: 16; FPU: 2;)}
eax_87: orig: eax, def: {eax_87 = DPB(eax_42, ax_86, 0, 16) (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}{ecx_110 = eax_87}{eax_116 = DPB(eax_87, ax_115, 0, 16) (alias)}
ah_88: orig: ah, def: {ah_88 = SLICE(ax_86, byte, 8) (alias)}, uses: {SCZO_89 = cond(ah_88 & 0x40)}{call fn10000108 (depth: 16; FPU: 2;)}
SCZO_89: orig: SCZO, def: {SCZO_89 = cond(ah_88 & 0x40)}, uses: {Z_90 = SCZO_89 (alias)}{SZO_91 = SCZO_89 (alias)}{SO_92 = SCZO_89 (alias)}
Z_90: orig: Z, def: {Z_90 = SCZO_89 (alias)}, uses: {branch Test(NE,Z_90)}{call fn10000108 (depth: 16; FPU: 2;)}
SZO_91: orig: SZO, def: {SZO_91 = SCZO_89 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
SO_92: orig: SO, def: {SO_92 = SCZO_89 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
C_93: orig: C, def: {C_93 = false}, uses: {SCZO_94 = C_93 (alias)}{call fn10000108 (depth: 16; FPU: 2;)}{ax_115 = C_93}
SCZO_94: orig: SCZO, def: {SCZO_94 = C_93 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 2;)}
ecx_95: orig: ecx, def: {ecx_95 = ecx_81 + 0x00000001}, uses: {SZO_96 = cond(ecx_95)}{dwArg04_100 = ecx_95}
SZO_96: orig: SZO, def: {SZO_96 = cond(ecx_95)}, uses: {SCZO_97 = SZO_96 (alias)}{Z_98 = SZO_96 (alias)}{SO_99 = SZO_96 (alias)}
SCZO_97: orig: SCZO, def: {SCZO_97 = SZO_96 (alias)}
Z_98: orig: Z, def: {Z_98 = SZO_96 (alias)}
SO_99: orig: SO, def: {SO_99 = SZO_96 (alias)}
dwArg04_100: orig: dwArg04, def: {dwArg04_100 = ecx_95}, uses: {rArg04_101 = DPB(rArg04_80, dwArg04_100, 0, 32) (alias)}
rArg04_101: orig: rArg04, def: {rArg04_101 = DPB(rArg04_80, dwArg04_100, 0, 32) (alias)}, uses: {rLoc2_102 = rArg04_101}{rArg04_104 = DPB(rArg04_101, dwArg04_103, 0, 32) (alias)}
rLoc2_102: orig: rLoc2, def: {rLoc2_102 = rArg04_101}, uses: {dwArg04_103 = rLoc2_102}{rLoc2_106 = PHI(rLoc2_102, rLoc2_84)}
dwArg04_103: orig: dwArg04, def: {dwArg04_103 = rLoc2_102}, uses: {rArg04_104 = DPB(rArg04_101, dwArg04_103, 0, 32) (alias)}{dwArg04_107 = PHI(dwArg04_103, dwArg04_79)}
rArg04_104: orig: rArg04, def: {rArg04_104 = DPB(rArg04_101, dwArg04_103, 0, 32) (alias)}, uses: {rArg04_105 = PHI(rArg04_104, rArg04_80)}
rArg04_105: orig: rArg04, def: {rArg04_105 = PHI(rArg04_104, rArg04_80)}, uses: {rArg04_70 = PHI(rArg04_66, rArg04_105)}{rArg04_189 = PHI(rArg04_105, rArg04_105, rArg04)}{rArg04_189 = PHI(rArg04_105, rArg04_105, rArg04)}
rLoc2_106: orig: rLoc2, def: {rLoc2_106 = PHI(rLoc2_102, rLoc2_84)}, uses: {rLoc2_109 = rLoc2_106}
dwArg04_107: orig: dwArg04, def: {dwArg04_107 = PHI(dwArg04_103, dwArg04_79)}, uses: {rLoc4_137 = dwArg04_107}{dwArg04_74 = PHI(dwArg04_65, dwArg04_107)}{rLoc4_173 = dwArg04_107}{dwArg04_207 = PHI(dwArg04_107, dwArg04_107, dwArg04)}{dwArg04_207 = PHI(dwArg04_107, dwArg04_107, dwArg04)}
rLoc1_108: orig: rLoc1, def: {rLoc1_108 = rLoc1_73 * Mem54[0x10033290:real64]}, uses: {rLoc1_73 = PHI(rLoc1_67, rLoc1_108)}{rLoc1_199 = PHI(rLoc1_108, rLoc1_108, rLoc1)}{rLoc1_199 = PHI(rLoc1_108, rLoc1_108, rLoc1)}
rLoc2_109: orig: rLoc2, def: {rLoc2_109 = rLoc2_106}
ecx_110: orig: ecx, def: {ecx_110 = eax_87}, uses: {dwArg0C_111 = ecx_110}{ecx_136 = PHI(ecx_124, ecx_110)}{ecx_124 = ecx_110 + 0x00000001}
dwArg0C_111: orig: dwArg0C, def: {dwArg0C_111 = ecx_110}, uses: {rArg0C_112 = DPB(rArg0C_83, dwArg0C_111, 0, 32) (alias)}{dwArg0C_135 = PHI(dwArg0C_130, dwArg0C_111)}
rArg0C_112: orig: rArg0C, def: {rArg0C_112 = DPB(rArg0C_83, dwArg0C_111, 0, 32) (alias)}, uses: {rLoc2_113 = rArg0C_112}{rArg0C_134 = PHI(rArg0C_131, rArg0C_112)}{rArg0C_131 = DPB(rArg0C_112, dwArg0C_130, 0, 32) (alias)}
rLoc2_113: orig: rLoc2, def: {rLoc2_113 = rArg0C_112}, uses: {rLoc3_114 = rLoc2_113}{rLoc2_193 = PHI(rLoc2_113, rLoc2_113, rLoc2)}{rLoc2_193 = PHI(rLoc2_113, rLoc2_113, rLoc2)}
rLoc3_114: orig: rLoc3, def: {rLoc3_114 = rLoc2_113}, uses: {rLoc3_133 = PHI(rLoc3_132, rLoc3_114)}{rLoc3_129 = rLoc3_114}
ax_115: orig: ax, def: {ax_115 = C_93}, uses: {eax_116 = DPB(eax_87, ax_115, 0, 16) (alias)}{ah_117 = SLICE(ax_115, byte, 8) (alias)}
eax_116: orig: eax, def: {eax_116 = DPB(eax_87, ax_115, 0, 16) (alias)}, uses: {eax_140 = DPB(eax_116, ax_139, 0, 16) (alias)}
ah_117: orig: ah, def: {ah_117 = SLICE(ax_115, byte, 8) (alias)}, uses: {SCZO_118 = cond(ah_117 & 0x40)}
SCZO_118: orig: SCZO, def: {SCZO_118 = cond(ah_117 & 0x40)}, uses: {Z_119 = SCZO_118 (alias)}{SZO_120 = SCZO_118 (alias)}{SO_121 = SCZO_118 (alias)}
Z_119: orig: Z, def: {Z_119 = SCZO_118 (alias)}, uses: {branch Test(NE,Z_119)}
SZO_120: orig: SZO, def: {SZO_120 = SCZO_118 (alias)}
SO_121: orig: SO, def: {SO_121 = SCZO_118 (alias)}
C_122: orig: C, def: {C_122 = false}, uses: {SCZO_123 = C_122 (alias)}
SCZO_123: orig: SCZO, def: {SCZO_123 = C_122 (alias)}
ecx_124: orig: ecx, def: {ecx_124 = ecx_110 + 0x00000001}, uses: {SZO_125 = cond(ecx_124)}{dwArg0C_130 = ecx_124}{ecx_136 = PHI(ecx_124, ecx_110)}
SZO_125: orig: SZO, def: {SZO_125 = cond(ecx_124)}, uses: {SCZO_126 = SZO_125 (alias)}{Z_127 = SZO_125 (alias)}{SO_128 = SZO_125 (alias)}
SCZO_126: orig: SCZO, def: {SCZO_126 = SZO_125 (alias)}
Z_127: orig: Z, def: {Z_127 = SZO_125 (alias)}
SO_128: orig: SO, def: {SO_128 = SZO_125 (alias)}
rLoc3_129: orig: rLoc3, def: {rLoc3_129 = rLoc3_114}
dwArg0C_130: orig: dwArg0C, def: {dwArg0C_130 = ecx_124}, uses: {rArg0C_131 = DPB(rArg0C_112, dwArg0C_130, 0, 32) (alias)}{dwArg0C_135 = PHI(dwArg0C_130, dwArg0C_111)}
rArg0C_131: orig: rArg0C, def: {rArg0C_131 = DPB(rArg0C_112, dwArg0C_130, 0, 32) (alias)}, uses: {rLoc3_132 = rArg0C_131}{rArg0C_134 = PHI(rArg0C_131, rArg0C_112)}
rLoc3_132: orig: rLoc3, def: {rLoc3_132 = rArg0C_131}, uses: {rLoc3_133 = PHI(rLoc3_132, rLoc3_114)}
rLoc3_133: orig: rLoc3, def: {rLoc3_133 = PHI(rLoc3_132, rLoc3_114)}, uses: {C_148 = rLoc3_133 - Mem54[0x10033298:real64]}{rLoc3_69 = PHI(rLoc3, rLoc3_133)}{rLoc3_188 = PHI(rLoc3_133, rLoc3_133, rLoc3)}{rLoc3_188 = PHI(rLoc3_133, rLoc3_133, rLoc3)}
rArg0C_134: orig: rArg0C, def: {rArg0C_134 = PHI(rArg0C_131, rArg0C_112)}, uses: {rArg0C_71 = PHI(rArg0C_53, rArg0C_134)}{rArg0C_194 = PHI(rArg0C_134, rArg0C_134, rArg0C_53)}{rArg0C_194 = PHI(rArg0C_134, rArg0C_134, rArg0C_53)}
dwArg0C_135: orig: dwArg0C, def: {dwArg0C_135 = PHI(dwArg0C_130, dwArg0C_111)}, uses: {dwArg0C_201 = PHI(dwArg0C_135, dwArg0C_135, dwArg0C_52)}{dwArg0C_201 = PHI(dwArg0C_135, dwArg0C_135, dwArg0C_52)}
ecx_136: orig: ecx, def: {ecx_136 = PHI(ecx_124, ecx_110)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
rLoc4_137: orig: rLoc4, def: {rLoc4_137 = dwArg04_107}, uses: {C_138 = rLoc4_137 - Mem54[0x10033298:real64]}{rLoc4_68 = PHI(rLoc4, rLoc4_137)}
C_138: orig: C, def: {C_138 = rLoc4_137 - Mem54[0x10033298:real64]}, uses: {ax_139 = C_138}
ax_139: orig: ax, def: {ax_139 = C_138}, uses: {eax_140 = DPB(eax_116, ax_139, 0, 16) (alias)}{ah_141 = SLICE(ax_139, byte, 8) (alias)}{ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)}
eax_140: orig: eax, def: {eax_140 = DPB(eax_116, ax_139, 0, 16) (alias)}, uses: {eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)}{eax_150 = DPB(eax_140, ax_149, 0, 16) (alias)}
ah_141: orig: ah, def: {ah_141 = SLICE(ax_139, byte, 8) (alias)}, uses: {SCZO_142 = cond(ah_141 & 0x40)}{ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)}
SCZO_142: orig: SCZO, def: {SCZO_142 = cond(ah_141 & 0x40)}, uses: {Z_143 = SCZO_142 (alias)}{SZO_144 = SCZO_142 (alias)}{SO_145 = SCZO_142 (alias)}
Z_143: orig: Z, def: {Z_143 = SCZO_142 (alias)}, uses: {branch Test(EQ,Z_143)}
SZO_144: orig: SZO, def: {SZO_144 = SCZO_142 (alias)}
SO_145: orig: SO, def: {SO_145 = SCZO_142 (alias)}
C_146: orig: C, def: {C_146 = false}, uses: {SCZO_147 = C_146 (alias)}
SCZO_147: orig: SCZO, def: {SCZO_147 = C_146 (alias)}
C_148: orig: C, def: {C_148 = rLoc3_133 - Mem54[0x10033298:real64]}, uses: {ax_149 = C_148}
ax_149: orig: ax, def: {ax_149 = C_148}, uses: {eax_150 = DPB(eax_140, ax_149, 0, 16) (alias)}{ah_151 = SLICE(ax_149, byte, 8) (alias)}{ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)}{ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)}{ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)}
eax_150: orig: eax, def: {eax_150 = DPB(eax_140, ax_149, 0, 16) (alias)}, uses: {eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)}{eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)}{eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)}
ah_151: orig: ah, def: {ah_151 = SLICE(ax_149, byte, 8) (alias)}, uses: {SCZO_152 = cond(ah_151 & 0x40)}{ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)}{ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)}{ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)}
SCZO_152: orig: SCZO, def: {SCZO_152 = cond(ah_151 & 0x40)}, uses: {Z_153 = SCZO_152 (alias)}{SZO_154 = SCZO_152 (alias)}{SO_155 = SCZO_152 (alias)}
Z_153: orig: Z, def: {Z_153 = SCZO_152 (alias)}, uses: {branch Test(EQ,Z_153)}
SZO_154: orig: SZO, def: {SZO_154 = SCZO_152 (alias)}
SO_155: orig: SO, def: {SO_155 = SCZO_152 (alias)}
C_156: orig: C, def: {C_156 = false}, uses: {SCZO_157 = C_156 (alias)}
SCZO_157: orig: SCZO, def: {SCZO_157 = C_156 (alias)}
SCZO_158: orig: SCZO, def: {SCZO_158 = cond(edi_64 - 0x000186A0)}, uses: {C_159 = SCZO_158 (alias)}{Z_160 = SCZO_158 (alias)}{SZO_161 = SCZO_158 (alias)}{SO_162 = SCZO_158 (alias)}
C_159: orig: C, def: {C_159 = SCZO_158 (alias)}
Z_160: orig: Z, def: {Z_160 = SCZO_158 (alias)}, uses: {branch Test(NE,Z_160)}
SZO_161: orig: SZO, def: {SZO_161 = SCZO_158 (alias)}
SO_162: orig: SO, def: {SO_162 = SCZO_158 (alias)}
edi_163: orig: edi, def: {edi_163 = esi_77}, uses: {edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)}
ah_164: orig: ah, def: {ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}{ah_190 = PHI(ah_164, ah_164, ah_44)}{ah_190 = PHI(ah_164, ah_164, ah_44)}
ax_165: orig: ax, def: {ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}{ax_191 = PHI(ax_165, ax_165, ax_43)}{ax_191 = PHI(ax_165, ax_165, ax_43)}
edi_166: orig: edi, def: {edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}{SCZO_176 = cond(ebp_37 - edi_166)}
eax_167: orig: eax, def: {eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{store(Mem174[ebx_33:word32]) = eax_167}{call fn10000108 (depth: 16; FPU: 3;)}{store(Mem183[ecx_175:word32]) = eax_167}{eax_206 = PHI(eax_167, eax_167, eax_42)}{eax_206 = PHI(eax_167, eax_167, eax_42)}
SCZO_168: orig: SCZO, def: {SCZO_168 = cond(esi_77 - ebp_37)}, uses: {C_169 = SCZO_168 (alias)}{Z_170 = SCZO_168 (alias)}{SZO_171 = SCZO_168 (alias)}{SO_172 = SCZO_168 (alias)}{call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
C_169: orig: C, def: {C_169 = SCZO_168 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
Z_170: orig: Z, def: {Z_170 = SCZO_168 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
SZO_171: orig: SZO, def: {SZO_171 = SCZO_168 (alias)}, uses: {call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
SO_172: orig: SO, def: {SO_172 = SCZO_168 (alias)}, uses: {branch Test(LT,SO_172)}{call fn10000108 (depth: 16; FPU: 4;)}{call fn10000108 (depth: 16; FPU: 3;)}
rLoc4_173: orig: rLoc4, def: {rLoc4_173 = dwArg04_107}, uses: {rLoc4_187 = PHI(rLoc4_173, rLoc4_173, rLoc4)}{rLoc4_187 = PHI(rLoc4_173, rLoc4_173, rLoc4)}
Mem174: orig: Mem0, def: {store(Mem174[ebx_33:word32]) = eax_167}
ecx_175: orig: ecx, def: {ecx_175 = dwArg10}, uses: {store(Mem183[ecx_175:word32]) = eax_167}{ecx_205 = PHI(ecx_175, ecx_175, ecx_45)}{store(Mem185[ecx_175:word32]) = 0x00000000}{ecx_205 = PHI(ecx_175, ecx_175, ecx_45)}
SCZO_176: orig: SCZO, def: {SCZO_176 = cond(ebp_37 - edi_166)}, uses: {C_177 = SCZO_176 (alias)}{Z_178 = SCZO_176 (alias)}{SZO_179 = SCZO_176 (alias)}{SO_180 = SCZO_176 (alias)}{SCZO_203 = PHI(SCZO_176, SCZO_176, SCZO_51)}{SCZO_203 = PHI(SCZO_176, SCZO_176, SCZO_51)}
C_177: orig: C, def: {C_177 = SCZO_176 (alias)}, uses: {C_202 = PHI(C_177, C_177, C_50)}{C_202 = PHI(C_177, C_177, C_50)}
Z_178: orig: Z, def: {Z_178 = SCZO_176 (alias)}, uses: {Z_200 = PHI(Z_178, Z_178, Z_47)}{Z_200 = PHI(Z_178, Z_178, Z_47)}
SZO_179: orig: SZO, def: {SZO_179 = SCZO_176 (alias)}, uses: {branch Test(LE,SZO_179)}{SZO_192 = PHI(SZO_179, SZO_179, SZO_48)}{SZO_192 = PHI(SZO_179, SZO_179, SZO_48)}
SO_180: orig: SO, def: {SO_180 = SCZO_176 (alias)}, uses: {SO_186 = PHI(SO_180, SO_180, SO_49)}{SO_186 = PHI(SO_180, SO_180, SO_49)}
edi_181: orig: edi, def: {edi_181 = dwLoc10_57}, uses: {edi_196 = PHI(edi_181, edi_181, edi)}{edi_196 = PHI(edi_181, edi_181, edi)}
esi_182: orig: esi, def: {esi_182 = dwLoc0C_56}, uses: {esi_198 = PHI(esi_182, esi_182, esi)}{esi_198 = PHI(esi_182, esi_182, esi)}
Mem183: orig: Mem0, def: {store(Mem183[ecx_175:word32]) = eax_167}, uses: {Mem208 = PHI(Mem185, Mem183, Mem54)}
Mem184: orig: Mem0, def: {store(Mem184[ebx_33:word32]) = 0x00000000}
Mem185: orig: Mem0, def: {store(Mem185[ecx_175:word32]) = 0x00000000}, uses: {Mem208 = PHI(Mem185, Mem183, Mem54)}
SO_186: orig: SO, def: {SO_186 = PHI(SO_180, SO_180, SO_49)}
rLoc4_187: orig: rLoc4, def: {rLoc4_187 = PHI(rLoc4_173, rLoc4_173, rLoc4)}
rLoc3_188: orig: rLoc3, def: {rLoc3_188 = PHI(rLoc3_133, rLoc3_133, rLoc3)}
rArg04_189: orig: rArg04, def: {rArg04_189 = PHI(rArg04_105, rArg04_105, rArg04)}
ah_190: orig: ah, def: {ah_190 = PHI(ah_164, ah_164, ah_44)}
ax_191: orig: ax, def: {ax_191 = PHI(ax_165, ax_165, ax_43)}
SZO_192: orig: SZO, def: {SZO_192 = PHI(SZO_179, SZO_179, SZO_48)}
rLoc2_193: orig: rLoc2, def: {rLoc2_193 = PHI(rLoc2_113, rLoc2_113, rLoc2)}
rArg0C_194: orig: rArg0C, def: {rArg0C_194 = PHI(rArg0C_134, rArg0C_134, rArg0C_53)}
dwLoc10_195: orig: dwLoc10, def: {dwLoc10_195 = PHI(dwLoc10_57, dwLoc10_57, dwLoc10)}
edi_196: orig: edi, def: {edi_196 = PHI(edi_181, edi_181, edi)}
dwLoc0C_197: orig: dwLoc0C, def: {dwLoc0C_197 = PHI(dwLoc0C_56, dwLoc0C_56, dwLoc0C)}
esi_198: orig: esi, def: {esi_198 = PHI(esi_182, esi_182, esi)}
rLoc1_199: orig: rLoc1, def: {rLoc1_199 = PHI(rLoc1_108, rLoc1_108, rLoc1)}
Z_200: orig: Z, def: {Z_200 = PHI(Z_178, Z_178, Z_47)}
dwArg0C_201: orig: dwArg0C, def: {dwArg0C_201 = PHI(dwArg0C_135, dwArg0C_135, dwArg0C_52)}
C_202: orig: C, def: {C_202 = PHI(C_177, C_177, C_50)}
SCZO_203: orig: SCZO, def: {SCZO_203 = PHI(SCZO_176, SCZO_176, SCZO_51)}
edx_204: orig: edx, def: {edx_204 = PHI(edx_39, edx_39, edx_39)}
ecx_205: orig: ecx, def: {ecx_205 = PHI(ecx_175, ecx_175, ecx_45)}
eax_206: orig: eax, def: {eax_206 = PHI(eax_167, eax_167, eax_42)}
dwArg04_207: orig: dwArg04, def: {dwArg04_207 = PHI(dwArg04_107, dwArg04_107, dwArg04)}
Mem208: orig: Mem0, def: {Mem208 = PHI(Mem185, Mem183, Mem54)}
ebp_209: orig: ebp, def: {ebp_209 = dwLoc08_34}
ebx_210: orig: ebx, def: {ebx_210 = dwLoc04_32}
// fn10000000
void fn10000000()
fn10000000_entry:		// block 0, pred:
	def Mem0
	def fp
	def dwArg04
	def eax
	def ebx
	def dwLoc04
	def dwArg06
	def ebp
	def dwLoc08
	def ecx
	def edx
	def dwArg08
	def dwArg10
	def SCZO
	def C
	def dwArg0C
	def Z
	def rLoc1
	def esi
	def dwLoc0C
	def edi
	def dwLoc10
	def rArg0C
	def rLoc2
	def SZO
	def ax
	def ah
	def rArg04
	def rLoc3
	def rLoc4
	def SO
	// succ:  1
l10000000:		// block 1, pred: 0
	eax_31 = dwArg04
	dwLoc04_32 = ebx
	ebx_33 = dwArg06
	dwLoc08_34 = ebp
	ecx_35 = (int32) Mem0[eax_31 + 0x00000006:word16]
	edx_36 = (int32) Mem0[eax_31 + 0x00000002:word16]
	ebp_37 = dwArg08
	ecx_38 = ecx_35 - edx_36
	edx_39 = dwArg10
	store(Mem40[ebx_33:word32]) = ecx_38
	ecx_41 = (int32) Mem40[eax_31 + 0x00000004:word16]
	eax_42 = (int32) Mem40[eax_31:word16]
	ax_43 = (word16) eax_42 (alias)
	ah_44 = SLICE(eax_42, byte, 8) (alias)
	ecx_45 = ecx_41 - eax_42
	SCZO_46 = cond(ebp_37 - 0x00000000)
	Z_47 = SCZO_46 (alias)
	SZO_48 = SCZO_46 (alias)
	SO_49 = SCZO_46 (alias)
	C_50 = false
	SCZO_51 = C_50 (alias)
	dwArg0C_52 = ecx_45
	rArg0C_53 = DPB(rArg0C, dwArg0C_52, 0, 32) (alias)
	store(Mem54[edx_39:word32]) = ecx_45
	branch Test(EQ,Z_47)
	// succ:  2 14
l10000035:		// block 2, pred: 1
	rLoc1_55 = Mem54[ebx_33:real64]
	dwLoc0C_56 = esi
	dwLoc10_57 = edi
	esi_58 = 0x00000000
	SCZO_59 = cond(esi_58)
	C_60 = SCZO_59 (alias)
	Z_61 = SCZO_59 (alias)
	SZO_62 = SCZO_59 (alias)
	SO_63 = SCZO_59 (alias)
	edi_64 = 0x000186A0
	dwArg04_65 = rLoc1_55
	rArg04_66 = DPB(rArg04, dwArg04_65, 0, 32) (alias)
	rLoc1_67 = rArg0C_53
	// succ:  3
l10000048:		// block 3, pred: 2 11
	rLoc4_68 = PHI(rLoc4, rLoc4_137)
	rLoc3_69 = PHI(rLoc3, rLoc3_133)
	rArg04_70 = PHI(rArg04_66, rArg04_105)
	rArg0C_71 = PHI(rArg0C_53, rArg0C_134)
	esi_72 = PHI(esi_58, esi_77)
	rLoc1_73 = PHI(rLoc1_67, rLoc1_108)
	dwArg04_74 = PHI(dwArg04_65, dwArg04_107)
	rLoc2_75 = dwArg04_74
	rLoc2_76 = rLoc2_75 * Mem54[0x0099188A:real64]
	esi_77 = esi_72 + 0x00000001
	SZO_78 = cond(esi_77)
	dwArg04_79 = rLoc2_76
	rArg04_80 = DPB(rArg04_70, dwArg04_79, 0, 32) (alias)
	call fn10000108 (depth: 16; FPU: 2;)
	ecx_81 = eax_42
	dwArg0C_82 = ecx_81
	rArg0C_83 = DPB(rArg0C_71, dwArg0C_82, 0, 32) (alias)
	rLoc2_84 = rArg0C_83
	C_85 = rLoc2_84 - dwArg04_79
	ax_86 = C_85
	eax_87 = DPB(eax_42, ax_86, 0, 16) (alias)
	ah_88 = SLICE(ax_86, byte, 8) (alias)
	SCZO_89 = cond(ah_88 & 0x40)
	Z_90 = SCZO_89 (alias)
	SZO_91 = SCZO_89 (alias)
	SO_92 = SCZO_89 (alias)
	C_93 = false
	SCZO_94 = C_93 (alias)
	branch Test(NE,Z_90)
	// succ:  4 5
l10000072:		// block 4, pred: 3
	ecx_95 = ecx_81 + 0x00000001
	SZO_96 = cond(ecx_95)
	SCZO_97 = SZO_96 (alias)
	Z_98 = SZO_96 (alias)
	SO_99 = SZO_96 (alias)
	dwArg04_100 = ecx_95
	rArg04_101 = DPB(rArg04_80, dwArg04_100, 0, 32) (alias)
	rLoc2_102 = rArg04_101
	dwArg04_103 = rLoc2_102
	rArg04_104 = DPB(rArg04_101, dwArg04_103, 0, 32) (alias)
	// succ:  5
l1000007F:		// block 5, pred: 4 3
	rArg04_105 = PHI(rArg04_104, rArg04_80)
	rLoc2_106 = PHI(rLoc2_102, rLoc2_84)
	dwArg04_107 = PHI(dwArg04_103, dwArg04_79)
	rLoc1_108 = rLoc1_73 * Mem54[0x10033290:real64]
	rLoc2_109 = rLoc2_106
	call fn10000108 (depth: 16; FPU: 2;)
	ecx_110 = eax_87
	dwArg0C_111 = ecx_110
	rArg0C_112 = DPB(rArg0C_83, dwArg0C_111, 0, 32) (alias)
	rLoc2_113 = rArg0C_112
	rLoc3_114 = rLoc2_113
	ax_115 = C_93
	eax_116 = DPB(eax_87, ax_115, 0, 16) (alias)
	ah_117 = SLICE(ax_115, byte, 8) (alias)
	SCZO_118 = cond(ah_117 & 0x40)
	Z_119 = SCZO_118 (alias)
	SZO_120 = SCZO_118 (alias)
	SO_121 = SCZO_118 (alias)
	C_122 = false
	SCZO_123 = C_122 (alias)
	branch Test(NE,Z_119)
	// succ:  6 7
l100000A0:		// block 6, pred: 5
	ecx_124 = ecx_110 + 0x00000001
	SZO_125 = cond(ecx_124)
	SCZO_126 = SZO_125 (alias)
	Z_127 = SZO_125 (alias)
	SO_128 = SZO_125 (alias)
	rLoc3_129 = rLoc3_114
	dwArg0C_130 = ecx_124
	rArg0C_131 = DPB(rArg0C_112, dwArg0C_130, 0, 32) (alias)
	rLoc3_132 = rArg0C_131
	// succ:  7
l100000AB:		// block 7, pred: 6 5
	rLoc3_133 = PHI(rLoc3_132, rLoc3_114)
	rArg0C_134 = PHI(rArg0C_131, rArg0C_112)
	dwArg0C_135 = PHI(dwArg0C_130, dwArg0C_111)
	ecx_136 = PHI(ecx_124, ecx_110)
	rLoc4_137 = dwArg04_107
	C_138 = rLoc4_137 - Mem54[0x10033298:real64]
	ax_139 = C_138
	eax_140 = DPB(eax_116, ax_139, 0, 16) (alias)
	ah_141 = SLICE(ax_139, byte, 8) (alias)
	SCZO_142 = cond(ah_141 & 0x40)
	Z_143 = SCZO_142 (alias)
	SZO_144 = SCZO_142 (alias)
	SO_145 = SCZO_142 (alias)
	C_146 = false
	SCZO_147 = C_146 (alias)
	branch Test(EQ,Z_143)
	// succ:  8 11
l100000BD:		// block 8, pred: 7
	C_148 = rLoc3_133 - Mem54[0x10033298:real64]
	ax_149 = C_148
	eax_150 = DPB(eax_140, ax_149, 0, 16) (alias)
	ah_151 = SLICE(ax_149, byte, 8) (alias)
	SCZO_152 = cond(ah_151 & 0x40)
	Z_153 = SCZO_152 (alias)
	SZO_154 = SCZO_152 (alias)
	SO_155 = SCZO_152 (alias)
	C_156 = false
	SCZO_157 = C_156 (alias)
	branch Test(EQ,Z_153)
	// succ:  9 11
l100000CB:		// block 9, pred: 8
	SCZO_158 = cond(edi_64 - 0x000186A0)
	C_159 = SCZO_158 (alias)
	Z_160 = SCZO_158 (alias)
	SZO_161 = SCZO_158 (alias)
	SO_162 = SCZO_158 (alias)
	branch Test(NE,Z_160)
	// succ:  10 11
l100000D3:		// block 10, pred: 9
	edi_163 = esi_77
	// succ:  11
l100000D5:		// block 11, pred: 10 9 8 7
	ah_164 = PHI(ah_151, ah_151, ah_151, ah_141)
	ax_165 = PHI(ax_149, ax_149, ax_149, ax_139)
	edi_166 = PHI(edi_163, edi_64, edi_64, edi_64)
	eax_167 = PHI(eax_150, eax_150, eax_150, eax_140)
	SCZO_168 = cond(esi_77 - ebp_37)
	C_169 = SCZO_168 (alias)
	Z_170 = SCZO_168 (alias)
	SZO_171 = SCZO_168 (alias)
	SO_172 = SCZO_168 (alias)
	branch Test(LT,SO_172)
	// succ:  12 3
l100000DD:		// block 12, pred: 11
	rLoc4_173 = dwArg04_107
	call fn10000108 (depth: 16; FPU: 4;)
	store(Mem174[ebx_33:word32]) = eax_167
	call fn10000108 (depth: 16; FPU: 3;)
	ecx_175 = dwArg10
	SCZO_176 = cond(ebp_37 - edi_166)
	C_177 = SCZO_176 (alias)
	Z_178 = SCZO_176 (alias)
	SZO_179 = SCZO_176 (alias)
	SO_180 = SCZO_176 (alias)
	edi_181 = dwLoc10_57
	esi_182 = dwLoc0C_56
	store(Mem183[ecx_175:word32]) = eax_167
	branch Test(LE,SZO_179)
	// succ:  13 14
l100000F9:		// block 13, pred: 12
	store(Mem184[ebx_33:word32]) = 0x00000000
	store(Mem185[ecx_175:word32]) = 0x00000000
	// succ:  14
l10000105:		// block 14, pred: 13 12 1
	SO_186 = PHI(SO_180, SO_180, SO_49)
	rLoc4_187 = PHI(rLoc4_173, rLoc4_173, rLoc4)
	rLoc3_188 = PHI(rLoc3_133, rLoc3_133, rLoc3)
	rArg04_189 = PHI(rArg04_105, rArg04_105, rArg04)
	ah_190 = PHI(ah_164, ah_164, ah_44)
	ax_191 = PHI(ax_165, ax_165, ax_43)
	SZO_192 = PHI(SZO_179, SZO_179, SZO_48)
	rLoc2_193 = PHI(rLoc2_113, rLoc2_113, rLoc2)
	rArg0C_194 = PHI(rArg0C_134, rArg0C_134, rArg0C_53)
	dwLoc10_195 = PHI(dwLoc10_57, dwLoc10_57, dwLoc10)
	edi_196 = PHI(edi_181, edi_181, edi)
	dwLoc0C_197 = PHI(dwLoc0C_56, dwLoc0C_56, dwLoc0C)
	esi_198 = PHI(esi_182, esi_182, esi)
	rLoc1_199 = PHI(rLoc1_108, rLoc1_108, rLoc1)
	Z_200 = PHI(Z_178, Z_178, Z_47)
	dwArg0C_201 = PHI(dwArg0C_135, dwArg0C_135, dwArg0C_52)
	C_202 = PHI(C_177, C_177, C_50)
	SCZO_203 = PHI(SCZO_176, SCZO_176, SCZO_51)
	edx_204 = PHI(edx_39, edx_39, edx_39)
	ecx_205 = PHI(ecx_175, ecx_175, ecx_45)
	eax_206 = PHI(eax_167, eax_167, eax_42)
	dwArg04_207 = PHI(dwArg04_107, dwArg04_107, dwArg04)
	Mem208 = PHI(Mem185, Mem183, Mem54)
	ebp_209 = dwLoc08_34
	ebx_210 = dwLoc04_32
	return
	// succ:  15
fn10000000_exit:		// block 15, pred: 14
	// succ: 

Mem0: Mem0:Global memory, def: {def Mem0}
fp: fp:Temporary, def: {def fp}
rArg0: rArg0:FPU stack, def: {def rArg0}, uses: {rLoc04_5 = rArg0}
rLoc04: rLoc04:Local -0004, def: {def rLoc04}
eax: eax:Register, def: {def eax}
rLoc04_5: orig: rLoc04, def: {rLoc04_5 = rArg0}, uses: {eax_6 = rLoc04_5}
eax_6: orig: eax, def: {eax_6 = rLoc04_5}
// fn10000108
void fn10000108()
fn10000108_entry:		// block 0, pred:
	def Mem0
	def fp
	def rArg0
	def rLoc04
	def eax
	// succ:  1
l10000108:		// block 1, pred: 0
	rLoc04_5 = rArg0
	eax_6 = rLoc04_5
	return
	// succ:  2
fn10000108_exit:		// block 2, pred: 1
	// succ: 

