// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000000 real32 r10000000))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (struct (0 real32 r0000))
	T_2 (in 0x10000000<32> : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x10000000<32> : word32)
  Class: Eq_2
  DataType: (ptr32 (struct (0 real32 r0000)))
  OrigDataType: (ptr32 (struct (0 T_3 t0000)))
T_3: (in Mem0[0x10000000<32>:real32] : real32)
  Class: Eq_3
  DataType: real32
  OrigDataType: real32
T_4: (in r1 : word32)
  Class: Eq_3
  DataType: real32
  OrigDataType: real32
