// ArrayAccess
// Return size: 0
void ArrayAccess()
ArrayAccess_entry:
	word32 r
	word32 i
	// succ:  l1
l1:
	(r + 0x14<32>)[i * 0xA<32>] = 0<i32>
	return (r + 0x10<32>)[i * 0xA<32>]
	// succ:  ArrayAccess_exit
ArrayAccess_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr32 (struct (10 T_18 t0010) (14 T_16 t0014)))
	T_2 (in r : word32)
Eq_3: ui32
	T_3 (in i : word32)
Eq_4: int32
	T_4 (in 0<i32> : int32)
	T_9 (in (r + 0x14<32>)[i * 0xA<32>] : int32)
Eq_5: int32
	T_5 (in 0x14<32> : word32)
Eq_6: (ptr32 T_16)
	T_6 (in r + 0x14<32> : word32)
Eq_7: ui32
	T_7 (in 0xA<32> : word32)
Eq_8: ui32
	T_8 (in i * 0xA<32> : word32)
Eq_10: int32
	T_10 (in 0x10<32> : word32)
Eq_11: (ptr32 T_18)
	T_11 (in r + 0x10<32> : word32)
Eq_12: ui32
	T_12 (in 0xA<32> : word32)
Eq_13: ui32
	T_13 (in i * 0xA<32> : word32)
Eq_14: word16
	T_14 (in (r + 0x10<32>)[i * 0xA<32>] : word16)
Eq_15: (struct 000A (0 T_9 t0000))
	T_15
Eq_16: (arr T_15)
	T_16
Eq_17: (struct 000A (0 T_14 t0000))
	T_17
Eq_18: (arr T_17)
	T_18
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in r : word32)
  Class: Eq_2
  DataType: (ptr32 (struct (10 T_18 t0010) (14 T_16 t0014)))
  OrigDataType: (ptr32 (struct (10 T_18 t0010) (14 T_16 t0014)))
T_3: (in i : word32)
  Class: Eq_3
  DataType: ui32
  OrigDataType: ui32
T_4: (in 0<i32> : int32)
  Class: Eq_4
  DataType: int32
  OrigDataType: int32
T_5: (in 0x14<32> : word32)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
T_6: (in r + 0x14<32> : word32)
  Class: Eq_6
  DataType: (ptr32 T_16)
  OrigDataType: (ptr32 T_16)
T_7: (in 0xA<32> : word32)
  Class: Eq_7
  DataType: ui32
  OrigDataType: ui32
T_8: (in i * 0xA<32> : word32)
  Class: Eq_8
  DataType: ui32
  OrigDataType: ui32
T_9: (in (r + 0x14<32>)[i * 0xA<32>] : int32)
  Class: Eq_4
  DataType: int32
  OrigDataType: int32
T_10: (in 0x10<32> : word32)
  Class: Eq_10
  DataType: int32
  OrigDataType: int32
T_11: (in r + 0x10<32> : word32)
  Class: Eq_11
  DataType: (ptr32 T_18)
  OrigDataType: (ptr32 T_18)
T_12: (in 0xA<32> : word32)
  Class: Eq_12
  DataType: ui32
  OrigDataType: ui32
T_13: (in i * 0xA<32> : word32)
  Class: Eq_13
  DataType: ui32
  OrigDataType: ui32
T_14: (in (r + 0x10<32>)[i * 0xA<32>] : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15:
  Class: Eq_15
  DataType: (struct 000A (0 T_9 t0000))
  OrigDataType: (struct 000A (0 T_9 t0000))
T_16:
  Class: Eq_16
  DataType: (arr T_15)
  OrigDataType: (arr T_15)
T_17:
  Class: Eq_17
  DataType: (struct 000A (0 T_14 t0000))
  OrigDataType: (struct 000A (0 T_14 t0000))
T_18:
  Class: Eq_18
  DataType: (arr T_17)
  OrigDataType: (arr T_17)
