// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	word32 ptr_0 = 0x04000000
	goto looptest
	// succ:  looptest
l2:
	Mem2[ptr_0 + 0x00000000:word32] = 0x00000000
	ptr_0 = ptr_0 + 0x00000004
	// succ:  looptest
looptest:
	branch ptr_0 >=u 0x04001000 done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr32 (struct 0004 (0 word32 dw0000)))
	T_2 (in ptr_0 : word32)
	T_3 (in 0x04000000 : word32)
	T_4 (in 0x04001000 : word32)
	T_11 (in ptr_0 + 0x00000004 : word32)
Eq_5: bool
	T_5 (in ptr_0 >=u 0x04001000 : bool)
Eq_6: word32
	T_6 (in 0x00000000 : word32)
	T_9 (in Mem2[ptr_0 + 0x00000000:word32] : word32)
Eq_7: word32
	T_7 (in 0x00000000 : word32)
Eq_8: up32
	T_8 (in ptr_0 + 0x00000000 : word32)
Eq_10: int32
	T_10 (in 0x00000004 : word32)
Eq_12: (struct 0004 (0 T_9 t0000))
	T_12
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ptr_0 : word32)
  Class: Eq_2
  DataType: (ptr32 (struct 0004 (0 word32 dw0000)))
  OrigDataType: (ptr32 (struct 0004 (0 word32 dw0000)))
T_3: (in 0x04000000 : word32)
  Class: Eq_2
  DataType: (ptr32 (struct 0004 (0 word32 dw0000)))
  OrigDataType: word32
T_4: (in 0x04001000 : word32)
  Class: Eq_2
  DataType: (ptr32 (struct 0004 (0 word32 dw0000)))
  OrigDataType: up32
T_5: (in ptr_0 >=u 0x04001000 : bool)
  Class: Eq_5
  DataType: bool
  OrigDataType: bool
T_6: (in 0x00000000 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in 0x00000000 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in ptr_0 + 0x00000000 : word32)
  Class: Eq_8
  DataType: up32
  OrigDataType: up32
T_9: (in Mem2[ptr_0 + 0x00000000:word32] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_10: (in 0x00000004 : word32)
  Class: Eq_10
  DataType: int32
  OrigDataType: int32
T_11: (in ptr_0 + 0x00000004 : word32)
  Class: Eq_2
  DataType: (ptr32 (struct 0004 (0 word32 dw0000)))
  OrigDataType: ptr32
T_12:
  Class: Eq_12
  DataType: (struct 0004 (0 T_9 t0000))
  OrigDataType: (struct 0004 (0 T_9 t0000))
