// IndirectCallFragment
// Return size: 0
define IndirectCallFragment
IndirectCallFragment_entry:
	// succ:  l1
l1:
	call SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) (retsize: 4;)
	return
	// succ:  IndirectCallFragment_exit
IndirectCallFragment_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr16 (segment))
	T_2 (in 0x2700<16> : selector)
Eq_3: (ptr16 (segment (2040 T_12 t2040)))
	T_3 (in ds : selector)
Eq_4: (memptr T_3 T_12)
	T_4 (in 0x2040<16> : word16)
Eq_5: (ptr32 T_12)
	T_5 (in SEQ(ds, 0x2040<16>) : ptr32)
Eq_6: ui16
	T_6 (in di : word16)
Eq_7: ui16
	T_7 (in 2<16> : word16)
Eq_8: ui16
	T_8 (in di * 2<16> : word16)
Eq_9: (memptr T_2 code)
	T_9 (in SEQ(ds, 0x2040<16>)[di * 2<16>] : word16)
Eq_10: (ptr32 code)
	T_10 (in SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) : ptr32)
Eq_11: (struct 0002 (0 T_9 t0000))
	T_11
Eq_12: (arr T_11)
	T_12
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x2700<16> : selector)
  Class: Eq_2
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 (segment (2040 T_12 t2040)))
  OrigDataType: (ptr16 (segment (2040 T_12 t2040)))
T_4: (in 0x2040<16> : word16)
  Class: Eq_4
  DataType: (memptr T_3 T_12)
  OrigDataType: (memptr T_3 T_12)
T_5: (in SEQ(ds, 0x2040<16>) : ptr32)
  Class: Eq_5
  DataType: (ptr32 T_12)
  OrigDataType: (ptr32 T_12)
T_6: (in di : word16)
  Class: Eq_6
  DataType: ui16
  OrigDataType: ui16
T_7: (in 2<16> : word16)
  Class: Eq_7
  DataType: ui16
  OrigDataType: ui16
T_8: (in di * 2<16> : word16)
  Class: Eq_8
  DataType: ui16
  OrigDataType: ui16
T_9: (in SEQ(ds, 0x2040<16>)[di * 2<16>] : word16)
  Class: Eq_9
  DataType: (memptr T_2 code)
  OrigDataType: (memptr T_2 code)
T_10: (in SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) : ptr32)
  Class: Eq_10
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_11:
  Class: Eq_11
  DataType: (struct 0002 (0 T_9 t0000))
  OrigDataType: (struct 0002 (0 T_9 t0000))
T_12:
  Class: Eq_12
  DataType: (arr T_11)
  OrigDataType: (arr T_11)
