// FnPointerFragment
// Return size: 0
void FnPointerFragment()
FnPointerFragment_entry:
	// succ:  l1
l1:
	Mem4[0x10000000:word32] = 0x01213130
	call Mem4[0x10000000:word32] (retsize: 4;)
		uses: Local -0004:0x01213130,r63:fp
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

// Equivalence classes ////////////
Eq_1: (ptr (struct "Globals"))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (ptr code)
	T_2 (in 0x01213130 : word32)
	T_4 (in Mem4[0x10000000:word32] : word32)
	T_6 (in Mem4[0x10000000:word32] : word32)
Eq_3: (ptr (struct (0 T_4 t0000)))
	T_3 (in 0x10000000 : word32)
Eq_5: (ptr (struct (0 T_6 t0000)))
	T_5 (in 0x10000000 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct "Globals"))
  OrigDataType: (ptr (struct "Globals"))
T_2: (in 0x01213130 : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_3: (in 0x10000000 : word32)
  Class: Eq_3
  DataType: (ptr (struct (0 T_4 t0000)))
  OrigDataType: (ptr (struct (0 T_4 t0000)))
T_4: (in Mem4[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_5: (in 0x10000000 : word32)
  Class: Eq_5
  DataType: (ptr (struct (0 T_6 t0000)))
  OrigDataType: (ptr (struct (0 T_6 t0000)))
T_6: (in Mem4[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: (ptr code)
