// FnPointerFragment
// Return size: 0
void FnPointerFragment()
FnPointerFragment_entry:
	// succ:  l1
l1:
	pfn_0 = 0x01213130
	Mem1[0x10000000:word32] = pfn_0
	call Mem1[0x10000000:word32] (retsize: 4;)
		uses: pfn_0
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

// Equivalence classes ////////////
Eq_1: (ptr (struct "Globals"))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (ptr code)
	T_2 (in 0x01213130 : word32)
	T_3 (in pfn_0 : word32)
	T_5 (in Mem1[0x10000000:word32] : word32)
	T_7 (in Mem1[0x10000000:word32] : word32)
Eq_4: (ptr (struct (0 T_5 t0000)))
	T_4 (in 0x10000000 : word32)
Eq_6: (ptr (struct (0 T_7 t0000)))
	T_6 (in 0x10000000 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct "Globals"))
  OrigDataType: (ptr (struct "Globals"))
T_2: (in 0x01213130 : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_3: (in pfn_0 : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_4: (in 0x10000000 : word32)
  Class: Eq_4
  DataType: (ptr (struct (0 T_5 t0000)))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_5: (in Mem1[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_6: (in 0x10000000 : word32)
  Class: Eq_6
  DataType: (ptr (struct (0 T_7 t0000)))
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem1[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: (ptr code)
