// FnPointerFragment
// Return size: 0
void FnPointerFragment()
FnPointerFragment_entry:
	// succ:  l1
l1:
	Mem4[0x10000000<32>:word32] = 0x1213130<32>
	call Mem4[0x10000000<32>:word32] (retsize: 4;)
		uses: Mem:Mem4,Stack +0000:0x1213130<32>
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr32 code)
	T_2 (in 0x1213130<32> : word32)
	T_4 (in Mem4[0x10000000<32>:word32] : word32)
	T_6 (in Mem4[0x10000000<32>:word32] : word32)
Eq_3: (ptr32 (struct (0 T_4 t0000)))
	T_3 (in 0x10000000<32> : word32)
Eq_5: (ptr32 (struct (0 T_6 t0000)))
	T_5 (in 0x10000000<32> : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x1213130<32> : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_3: (in 0x10000000<32> : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (0 T_4 t0000)))
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem4[0x10000000<32>:word32] : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_5: (in 0x10000000<32> : word32)
  Class: Eq_5
  DataType: (ptr32 (struct (0 T_6 t0000)))
  OrigDataType: (ptr32 (struct (0 T_6 t0000)))
T_6: (in Mem4[0x10000000<32>:word32] : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
