// Equivalence classes ////////////
// Type Variables ////////////
T_1: (in globals : (ptr32 (struct)))
  Class: Eq_1
  DataType: 
  OrigDataType: (ptr32 (struct (3000 (arr T_8) a3000)))
T_2: (in 0x00003000<32> : word32)
  Class: Eq_2
  DataType: 
  OrigDataType: word32
T_3: (in globals + 0x00003000<32> : ptr32)
  Class: Eq_3
  DataType: 
  OrigDataType: ptr32
T_4: (in i : word32)
  Class: Eq_4
  DataType: 
  OrigDataType: ui32
T_5: (in 0x00000004<32> : word32)
  Class: Eq_5
  DataType: 
  OrigDataType: ui32
T_6: (in i * 0x00000004<32> : word32)
  Class: Eq_6
  DataType: 
  OrigDataType: ui32
T_7: (in (globals + 0x00003000<32>)[i * 0x00000004<32>] : word32)
  Class: Eq_7
  DataType: 
  OrigDataType: word32
T_8:
  Class: Eq_8
  DataType: 
  OrigDataType: (struct 0004 (0 T_7 t0000))
