// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	T_1 (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr32 (struct 0001 (0 T_3 t0000)))
	T_2 (in i : word32)
Eq_3: int32
	T_3 (in Mem0[i:int32] : int32)
Eq_4: (ptr32 (struct 0004 (0 T_5 t0000)))
	T_4 (in i2 : word32)
Eq_5: int32
	T_5 (in Mem0[i2:int32] : int32)
Eq_6: (struct 0001 (0 T_3 t0000))
	T_6
Eq_7: (struct 0004 (0 T_5 t0000))
	T_7
// Type Variables ////////////
T_1: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in i : word32)
  Class: Eq_2
  DataType: (ptr32 (struct 0001 (0 T_3 t0000)))
  OrigDataType: (ptr32 (struct 0001 (0 T_3 t0000)))
T_3: (in Mem0[i:int32] : int32)
  Class: Eq_3
  DataType: int32
  OrigDataType: int32
T_4: (in i2 : word32)
  Class: Eq_4
  DataType: (ptr32 (struct 0004 (0 T_5 t0000)))
  OrigDataType: (ptr32 (struct 0004 (0 T_5 t0000)))
T_5: (in Mem0[i2:int32] : int32)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
T_6:
  Class: Eq_6
  DataType: (struct 0001 (0 T_3 t0000))
  OrigDataType: (struct 0001 (0 T_3 t0000))
T_7:
  Class: Eq_7
  DataType: (struct 0004 (0 T_5 t0000))
  OrigDataType: (struct 0004 (0 T_5 t0000))
