// Equivalence classes ////////////
Eq_1: (ptr32 (struct (4 T_4 t0004)))
	T_1 (in pfoo : word32)
Eq_2: word32
	T_2 (in 4<32> : word32)
Eq_3: word32
	T_3 (in pfoo + 4<32> : word32)
Eq_4: word32
	T_4 (in Mem0[pfoo + 4<32>:word32] : word32)
	T_5 (in x : word32)
	T_8 (in Mem0[pfoo + 4<32>:word32] : word32)
Eq_6: word32
	T_6 (in 4<32> : word32)
Eq_7: word32
	T_7 (in pfoo + 4<32> : word32)
// Type Variables ////////////
T_1: (in pfoo : word32)
  Class: Eq_1
  DataType: (ptr32 (struct (4 T_4 t0004)))
  OrigDataType: (ptr32 (struct (4 T_4 t0004)))
T_2: (in 4<32> : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in pfoo + 4<32> : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in Mem0[pfoo + 4<32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in x : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_6: (in 4<32> : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in pfoo + 4<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem0[pfoo + 4<32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
