// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0010(ds, 0x300<16>, 0x320<16>)
	fn0C00_0037(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0010
// Return size: 0
void fn0C00_0010(selector ds, word16 wArg02, word16 wArg04)
fn0C00_0010_entry:
	// succ:  l0C00_0010
l0C00_0010:
	real64 rLoc1_36 = Mem7[ds:wArg02 + 0<16>:real64]
	real64 rLoc2_38 = Mem7[ds:wArg02 + 8<16>:real64]
	real64 rLoc2_41 = Mem7[ds:wArg02 + 0x10<16>:real64]
	Mem25[ds:wArg04 + 0<16>:real64] = rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 + rLoc2_41 * rLoc2_41
	Mem29[ds:wArg04 + 0x28<16>:real64] = CONVERT(Mem25[ds:wArg04 + 0x20<16>:int16], int16, real64)
	return
	// succ:  fn0C00_0010_exit
fn0C00_0010_exit:

// fn0C00_0037
// Return size: 0
void fn0C00_0037(selector ds)
fn0C00_0037_entry:
	// succ:  l0C00_0037
l0C00_0037:
	Mem7[ds:0x400<16>:real64] = 0.0
	Mem11[ds:0x408<16>:int32] = CONVERT(1.0, real64, int32)
	return
	// succ:  fn0C00_0037_exit
fn0C00_0037_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr16 (segment (400 T_44 t0400) (408 T_48 t0408)))
	T_2 (in ds : selector)
	T_5 (in ds : selector)
	T_13 (in ds : selector)
Eq_3: (ptr32 (fn T_10 (T_2, T_8, T_9)))
	T_3 (in fn0C00_0010 : segptr32)
	T_4 (in signature of fn0C00_0010 : void)
Eq_6: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008) (10 T_26 t0010)))
	T_6 (in wArg02 : word16)
	T_8 (in 0x300<16> : word16)
Eq_7: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020) (28 T_41 t0028)))
	T_7 (in wArg04 : word16)
	T_9 (in 0x320<16> : word16)
Eq_10: void
	T_10 (in fn0C00_0010(ds, 0x300<16>, 0x320<16>) : void)
Eq_11: (ptr32 (fn T_14 (T_2)))
	T_11 (in fn0C00_0037 : segptr32)
	T_12 (in signature of fn0C00_0037 : void)
Eq_14: void
	T_14 (in fn0C00_0037(ds) : void)
Eq_15: real64
	T_15 (in rLoc1_36 : real64)
	T_18 (in Mem7[ds:wArg02 + 0<16>:real64] : real64)
Eq_16: word16
	T_16 (in 0<16> : word16)
Eq_17: word16
	T_17 (in wArg02 + 0<16> : word16)
Eq_19: real64
	T_19 (in rLoc2_38 : real64)
	T_22 (in Mem7[ds:wArg02 + 8<16>:real64] : real64)
Eq_20: word16
	T_20 (in 8<16> : word16)
Eq_21: (memptr T_5 (struct (0 T_18 t0000)))
	T_21 (in wArg02 + 8<16> : word16)
Eq_23: real64
	T_23 (in rLoc2_41 : real64)
	T_26 (in Mem7[ds:wArg02 + 0x10<16>:real64] : real64)
Eq_24: word16
	T_24 (in 0x10<16> : word16)
Eq_25: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008)))
	T_25 (in wArg02 + 0x10<16> : word16)
Eq_27: real64
	T_27 (in rLoc1_36 * rLoc1_36 : real64)
Eq_28: real64
	T_28 (in rLoc2_38 * rLoc2_38 : real64)
Eq_29: real64
	T_29 (in rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 : real64)
Eq_30: real64
	T_30 (in rLoc2_41 * rLoc2_41 : real64)
Eq_31: real64
	T_31 (in rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 + rLoc2_41 * rLoc2_41 : real64)
	T_34 (in Mem25[ds:wArg04 + 0<16>:real64] : real64)
Eq_32: word16
	T_32 (in 0<16> : word16)
Eq_33: word16
	T_33 (in wArg04 + 0<16> : word16)
Eq_35: word16
	T_35 (in 0x20<16> : word16)
Eq_36: (memptr T_5 (struct (0 T_34 t0000)))
	T_36 (in wArg04 + 0x20<16> : word16)
Eq_37: int16
	T_37 (in Mem25[ds:wArg04 + 0x20<16>:int16] : int16)
Eq_38: real64
	T_38 (in CONVERT(Mem25[ds:wArg04 + 0x20<16>:int16], int16, real64) : real64)
	T_41 (in Mem29[ds:wArg04 + 0x28<16>:real64] : real64)
Eq_39: word16
	T_39 (in 0x28<16> : word16)
Eq_40: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020)))
	T_40 (in wArg04 + 0x28<16> : word16)
Eq_42: real64
	T_42 (in 0.0 : real64)
	T_44 (in Mem7[ds:0x400<16>:real64] : real64)
Eq_43: (memptr T_13 (struct (0 T_44 t0000)))
	T_43 (in 0x400<16> : word16)
Eq_45: real64
	T_45 (in 1.0 : real64)
Eq_46: int32
	T_46 (in CONVERT(1.0, real64, int32) : int32)
	T_48 (in Mem11[ds:0x408<16>:int32] : int32)
Eq_47: (memptr T_13 (struct (0 T_48 t0000)))
	T_47 (in 0x408<16> : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (400 T_44 t0400) (408 T_48 t0408)))
  OrigDataType: (ptr16 (segment))
T_3: (in fn0C00_0010 : segptr32)
  Class: Eq_3
  DataType: (ptr32 (fn T_10 (T_2, T_8, T_9)))
  OrigDataType: (ptr32 (fn T_10 (T_2, T_8, T_9)))
T_4: (in signature of fn0C00_0010 : void)
  Class: Eq_3
  DataType: (ptr32 (fn T_10 (T_2, T_8, T_9)))
  OrigDataType: 
T_5: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (400 T_44 t0400) (408 T_48 t0408)))
  OrigDataType: (ptr16 (segment))
T_6: (in wArg02 : word16)
  Class: Eq_6
  DataType: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008) (10 T_26 t0010)))
  OrigDataType: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008) (10 T_26 t0010)))
T_7: (in wArg04 : word16)
  Class: Eq_7
  DataType: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020) (28 T_41 t0028)))
  OrigDataType: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020) (28 T_41 t0028)))
T_8: (in 0x300<16> : word16)
  Class: Eq_6
  DataType: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008) (10 T_26 t0010)))
  OrigDataType: word16
T_9: (in 0x320<16> : word16)
  Class: Eq_7
  DataType: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020) (28 T_41 t0028)))
  OrigDataType: word16
T_10: (in fn0C00_0010(ds, 0x300<16>, 0x320<16>) : void)
  Class: Eq_10
  DataType: void
  OrigDataType: void
T_11: (in fn0C00_0037 : segptr32)
  Class: Eq_11
  DataType: (ptr32 (fn T_14 (T_2)))
  OrigDataType: (ptr32 (fn T_14 (T_2)))
T_12: (in signature of fn0C00_0037 : void)
  Class: Eq_11
  DataType: (ptr32 (fn T_14 (T_2)))
  OrigDataType: 
T_13: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (400 T_44 t0400) (408 T_48 t0408)))
  OrigDataType: (ptr16 (segment (400 T_44 t0400) (408 T_48 t0408)))
T_14: (in fn0C00_0037(ds) : void)
  Class: Eq_14
  DataType: void
  OrigDataType: void
T_15: (in rLoc1_36 : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_16: (in 0<16> : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in wArg02 + 0<16> : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in Mem7[ds:wArg02 + 0<16>:real64] : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_19: (in rLoc2_38 : real64)
  Class: Eq_19
  DataType: real64
  OrigDataType: real64
T_20: (in 8<16> : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21: (in wArg02 + 8<16> : word16)
  Class: Eq_21
  DataType: (memptr T_5 (struct (0 T_18 t0000)))
  OrigDataType: (memptr T_5 (struct (0 T_18 t0000)))
T_22: (in Mem7[ds:wArg02 + 8<16>:real64] : real64)
  Class: Eq_19
  DataType: real64
  OrigDataType: real64
T_23: (in rLoc2_41 : real64)
  Class: Eq_23
  DataType: real64
  OrigDataType: real64
T_24: (in 0x10<16> : word16)
  Class: Eq_24
  DataType: word16
  OrigDataType: word16
T_25: (in wArg02 + 0x10<16> : word16)
  Class: Eq_25
  DataType: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008)))
  OrigDataType: (memptr T_5 (struct (0 T_18 t0000) (8 T_22 t0008)))
T_26: (in Mem7[ds:wArg02 + 0x10<16>:real64] : real64)
  Class: Eq_23
  DataType: real64
  OrigDataType: real64
T_27: (in rLoc1_36 * rLoc1_36 : real64)
  Class: Eq_27
  DataType: real64
  OrigDataType: real64
T_28: (in rLoc2_38 * rLoc2_38 : real64)
  Class: Eq_28
  DataType: real64
  OrigDataType: real64
T_29: (in rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 : real64)
  Class: Eq_29
  DataType: real64
  OrigDataType: real64
T_30: (in rLoc2_41 * rLoc2_41 : real64)
  Class: Eq_30
  DataType: real64
  OrigDataType: real64
T_31: (in rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 + rLoc2_41 * rLoc2_41 : real64)
  Class: Eq_31
  DataType: real64
  OrigDataType: real64
T_32: (in 0<16> : word16)
  Class: Eq_32
  DataType: word16
  OrigDataType: word16
T_33: (in wArg04 + 0<16> : word16)
  Class: Eq_33
  DataType: word16
  OrigDataType: word16
T_34: (in Mem25[ds:wArg04 + 0<16>:real64] : real64)
  Class: Eq_31
  DataType: real64
  OrigDataType: real64
T_35: (in 0x20<16> : word16)
  Class: Eq_35
  DataType: word16
  OrigDataType: word16
T_36: (in wArg04 + 0x20<16> : word16)
  Class: Eq_36
  DataType: (memptr T_5 (struct (0 T_34 t0000)))
  OrigDataType: (memptr T_5 (struct (0 T_34 t0000)))
T_37: (in Mem25[ds:wArg04 + 0x20<16>:int16] : int16)
  Class: Eq_37
  DataType: int16
  OrigDataType: int16
T_38: (in CONVERT(Mem25[ds:wArg04 + 0x20<16>:int16], int16, real64) : real64)
  Class: Eq_38
  DataType: real64
  OrigDataType: real64
T_39: (in 0x28<16> : word16)
  Class: Eq_39
  DataType: word16
  OrigDataType: word16
T_40: (in wArg04 + 0x28<16> : word16)
  Class: Eq_40
  DataType: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020)))
  OrigDataType: (memptr T_5 (struct (0 T_34 t0000) (20 T_37 t0020)))
T_41: (in Mem29[ds:wArg04 + 0x28<16>:real64] : real64)
  Class: Eq_38
  DataType: real64
  OrigDataType: real64
T_42: (in 0.0 : real64)
  Class: Eq_42
  DataType: real64
  OrigDataType: real64
T_43: (in 0x400<16> : word16)
  Class: Eq_43
  DataType: (memptr T_13 (struct (0 T_44 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_44 t0000)))
T_44: (in Mem7[ds:0x400<16>:real64] : real64)
  Class: Eq_42
  DataType: real64
  OrigDataType: real64
T_45: (in 1.0 : real64)
  Class: Eq_45
  DataType: real64
  OrigDataType: real64
T_46: (in CONVERT(1.0, real64, int32) : int32)
  Class: Eq_46
  DataType: int32
  OrigDataType: int32
T_47: (in 0x408<16> : word16)
  Class: Eq_47
  DataType: (memptr T_13 (struct (0 T_48 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_48 t0000)))
T_48: (in Mem11[ds:0x408<16>:int32] : int32)
  Class: Eq_46
  DataType: int32
  OrigDataType: int32
