// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem2[ds:0x9A2E:word16] = 0x0000
	Mem5[ds:0x9A26:word16] = 0x0100
	word16 si_10 = 0x0000
	// succ:  l0C00_0015
l0C00_0015:
	Mem12[0x5CE1:si_10 + 0x0000:word16] = 0xFFFF
	word16 v9_15 = Mem12[ds:0x9A26:word16] - 0x0001
	Mem16[ds:0x9A26:word16] = v9_15
	si_10 = si_10 + 0x0026
	branch v9_15 != 0x0000 l0C00_0015
	// succ:  l0C00_0023 l0C00_0015
l0C00_0023:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Equivalence classes ////////////
Eq_1: (ptr (struct "Globals"))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (ptr (segment (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
	T_2 (in ds : selector)
Eq_3: word16
	T_3 (in 0x0000 : word16)
	T_5 (in Mem2[ds:0x9A2E:word16] : word16)
Eq_4: (memptr T_2 (struct (0 T_5 t0000)))
	T_4 (in 0x9A2E : word16)
Eq_6: word16
	T_6 (in 0x0100 : word16)
	T_8 (in Mem5[ds:0x9A26:word16] : word16)
	T_16 (in v9_15 : word16)
	T_18 (in Mem12[ds:0x9A26:word16] : word16)
	T_20 (in Mem12[ds:0x9A26:word16] - 0x0001 : word16)
	T_21 (in Mem16[ds:0x9A26:word16] : word16)
	T_24 (in 0x0000 : word16)
Eq_7: (memptr T_2 (struct (0 T_8 t0000)))
	T_7 (in 0x9A26 : word16)
Eq_9: (memptr T_12 (struct 0026 (0 word16 w0000)))
	T_9 (in si_10 : word16)
	T_10 (in 0x0000 : word16)
	T_23 (in si_10 + 0x0026 : word16)
Eq_11: word16
	T_11 (in 0xFFFF : word16)
	T_15 (in Mem12[0x5CE1:si_10 + 0x0000:word16] : word16)
Eq_12: (ptr (segment (0 (arr T_26) a0000)))
	T_12 (in 0x5CE1 : selector)
Eq_13: word16
	T_13 (in 0x0000 : word16)
Eq_14: (memptr T_12 T_15)
	T_14 (in si_10 + 0x0000 : word16)
Eq_17: (memptr T_2 (struct (0 T_6 t0000)))
	T_17 (in 0x9A26 : word16)
Eq_19: word16
	T_19 (in 0x0001 : word16)
Eq_22: mp16
	T_22 (in 0x0026 : word16)
Eq_25: bool
	T_25 (in v9_15 != 0x0000 : bool)
Eq_26: (struct 0026 (0 T_15 t0000))
	T_26
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct "Globals"))
  OrigDataType: (ptr (struct "Globals"))
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr (segment (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
  OrigDataType: (ptr (segment (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
T_3: (in 0x0000 : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in 0x9A2E : word16)
  Class: Eq_4
  DataType: (memptr T_2 (struct (0 T_5 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_5 t0000)))
T_5: (in Mem2[ds:0x9A2E:word16] : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_6: (in 0x0100 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0x9A26 : word16)
  Class: Eq_7
  DataType: (memptr T_2 (struct (0 T_8 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_8 t0000)))
T_8: (in Mem5[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in si_10 : word16)
  Class: Eq_9
  DataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
  OrigDataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
T_10: (in 0x0000 : word16)
  Class: Eq_9
  DataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
  OrigDataType: word16
T_11: (in 0xFFFF : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in 0x5CE1 : selector)
  Class: Eq_12
  DataType: (ptr (segment (0 (arr T_26) a0000)))
  OrigDataType: (ptr (segment (0 (arr T_26) a0000)))
T_13: (in 0x0000 : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in si_10 + 0x0000 : word16)
  Class: Eq_14
  DataType: (memptr T_12 T_15)
  OrigDataType: (memptr T_12 T_15)
T_15: (in Mem12[0x5CE1:si_10 + 0x0000:word16] : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_16: (in v9_15 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_17: (in 0x9A26 : word16)
  Class: Eq_17
  DataType: (memptr T_2 (struct (0 T_6 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_6 t0000)))
T_18: (in Mem12[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_19: (in 0x0001 : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in Mem12[ds:0x9A26:word16] - 0x0001 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_21: (in Mem16[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_22: (in 0x0026 : word16)
  Class: Eq_22
  DataType: mp16
  OrigDataType: mp16
T_23: (in si_10 + 0x0026 : word16)
  Class: Eq_9
  DataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
  OrigDataType: mp16
T_24: (in 0x0000 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_25: (in v9_15 != 0x0000 : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26:
  Class: Eq_26
  DataType: (struct 0026 (0 T_15 t0000))
  OrigDataType: (struct 0026 (0 T_15 t0000))
