// Fn1
void Fn1()
Fn1_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem0[p + 0x00000004:word32]) = 0x00000042
	Fn2(p)
	return
	// succ:  2
Fn1_exit:		// block 2, pred: 1
	// succ: 

// Fn2
void Fn2(word32 arg1)
Fn2_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem0[arg1 + 0x00000008:word32]) = 0x00000023
	return
	// succ:  2
Fn2_exit:		// block 2, pred: 1
	// succ: 

// Equivalence classes ////////////
Eq_2: word32
	T_2 (in 0x00000042 : word32)
	T_6 (in Mem0[p + 0x00000004:word32] : word32)
Eq_3: (ptr (struct (4 T_6 t0004) (8 T_14 t0008)))
	T_3 (in p : word32)
	T_9 (in arg1 : word32)
Eq_4: word32
	T_4 (in 0x00000004 : word32)
Eq_5: word32
	T_5 (in p + 0x00000004 : word32)
Eq_7: (ptr (fn T_10 (T_3)))
	T_7 (in Fn2 : ptr32)
	T_8 (in signature of Fn2)
Eq_10: word32
	T_10 (in Fn2(p) : word32)
Eq_11: word32
	T_11 (in 0x00000023 : word32)
	T_14 (in Mem0[arg1 + 0x00000008:word32] : word32)
Eq_12: word32
	T_12 (in 0x00000008 : word32)
Eq_13: word32
	T_13 (in arg1 + 0x00000008 : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in 0x00000042 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in p : word32)
  Class: Eq_3
  DataType: (ptr (struct (4 T_6 t0004) (8 T_14 t0008)))
  OrigDataType: (ptr (struct (4 T_6 t0004)))
T_4: (in 0x00000004 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in p + 0x00000004 : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in Mem0[p + 0x00000004:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_7: (in Fn2 : ptr32)
  Class: Eq_7
  DataType: (ptr (fn T_10 (T_3)))
  OrigDataType: (ptr (fn T_10 (T_3)))
T_8: (in signature of Fn2)
  Class: Eq_7
  DataType: (ptr (fn T_10 (T_3)))
  OrigDataType: 
T_9: (in arg1 : word32)
  Class: Eq_3
  DataType: (ptr (struct (4 T_6 t0004) (8 T_14 t0008)))
  OrigDataType: (ptr (struct (8 T_14 t0008)))
T_10: (in Fn2(p) : word32)
  Class: Eq_10
  DataType: word32
  OrigDataType: word32
T_11: (in 0x00000023 : word32)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
T_12: (in 0x00000008 : word32)
  Class: Eq_12
  DataType: word32
  OrigDataType: word32
T_13: (in arg1 + 0x00000008 : word32)
  Class: Eq_13
  DataType: word32
  OrigDataType: word32
T_14: (in Mem0[arg1 + 0x00000008:word32] : word32)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
