// Fn1
// Return size: 0
define Fn1
Fn1_entry:
	// succ:  l1
l1:
	Mem0[p + 4<32>:word32] = 0x42<32>
	Fn2(p)
	return
	// succ:  Fn1_exit
Fn1_exit:

// Fn2
// Return size: 0
void Fn2(word32 arg1)
Fn2_entry:
	// succ:  l1
l1:
	Mem0[arg1 + 8<32>:word32] = 0x23<32>
	return
	// succ:  Fn2_exit
Fn2_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: word32
	T_2 (in 0x42<32> : word32)
	T_6 (in Mem0[p + 4<32>:word32] : word32)
Eq_3: (ptr32 (struct (4 T_6 t0004) (8 T_14 t0008)))
	T_3 (in p : word32)
	T_9 (in arg1 : word32)
Eq_4: word32
	T_4 (in 4<32> : word32)
Eq_5: word32
	T_5 (in p + 4<32> : word32)
Eq_7: (ptr32 (fn T_10 (T_3)))
	T_7 (in Fn2 : ptr32)
	T_8 (in signature of Fn2 : void)
Eq_10: word32
	T_10 (in Fn2(p) : word32)
Eq_11: word32
	T_11 (in 0x23<32> : word32)
	T_14 (in Mem0[arg1 + 8<32>:word32] : word32)
Eq_12: word32
	T_12 (in 8<32> : word32)
Eq_13: word32
	T_13 (in arg1 + 8<32> : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x42<32> : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in p : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (4 T_6 t0004) (8 T_14 t0008)))
  OrigDataType: (ptr32 (struct (4 T_6 t0004)))
T_4: (in 4<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in p + 4<32> : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in Mem0[p + 4<32>:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_7: (in Fn2 : ptr32)
  Class: Eq_7
  DataType: (ptr32 (fn T_10 (T_3)))
  OrigDataType: (ptr32 (fn T_10 (T_3)))
T_8: (in signature of Fn2 : void)
  Class: Eq_7
  DataType: (ptr32 (fn T_10 (T_3)))
  OrigDataType: 
T_9: (in arg1 : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (4 T_6 t0004) (8 T_14 t0008)))
  OrigDataType: (ptr32 (struct (8 T_14 t0008)))
T_10: (in Fn2(p) : word32)
  Class: Eq_10
  DataType: word32
  OrigDataType: word32
T_11: (in 0x23<32> : word32)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
T_12: (in 8<32> : word32)
  Class: Eq_12
  DataType: word32
  OrigDataType: word32
T_13: (in arg1 + 8<32> : word32)
  Class: Eq_13
  DataType: word32
  OrigDataType: word32
T_14: (in Mem0[arg1 + 8<32>:word32] : word32)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
