// SegmentedPointerProc
// Return size: 0
define SegmentedPointerProc
SegmentedPointerProc_entry:
	// succ:  l1
l1:
	Mem0[ds:0x300<16>:word16] = 0x1234<16>
	Mem0[ds:0x302<16>:word16] = 0x5550<16>
	es_bx = Mem0[ds:0x300<16>:segptr32]
	Mem0[ds:0x304<16>:word16] = Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16]
SegmentedPointerProc_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: segptr32
	T_2 (in 0x1234<16> : word16)
	T_5 (in Mem0[ds:0x300<16>:word16] : word16)
	T_10 (in Mem0[ds:0x300<16>:segptr32] : segptr32)
	T_11 (in es_bx : segptr32)
Eq_3: (ptr16 (segment (300 T_2 t0300) (302 T_8 t0302) (304 T_18 t0304)))
	T_3 (in ds : selector)
Eq_4: (memptr T_3 (struct (0 T_5 t0000)))
	T_4 (in 0x300<16> : word16)
Eq_6: word16
	T_6 (in 0x5550<16> : word16)
	T_8 (in Mem0[ds:0x302<16>:word16] : word16)
Eq_7: (memptr T_3 (struct (0 T_8 t0000)))
	T_7 (in 0x302<16> : word16)
Eq_9: (memptr T_3 (struct (0 T_10 t0000)))
	T_9 (in 0x300<16> : word16)
Eq_12: (ptr16 (segment))
	T_12 (in SLICE(es_bx, selector, 16) : selector)
Eq_13: (memptr T_12 (struct (4 T_16 t0004)))
	T_13 (in SLICE(es_bx, word16, 0) : word16)
Eq_14: word16
	T_14 (in 4<16> : word16)
Eq_15: word16
	T_15 (in SLICE(es_bx, word16, 0) + 4<16> : word16)
Eq_16: word16
	T_16 (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16] : word16)
	T_18 (in Mem0[ds:0x304<16>:word16] : word16)
Eq_17: (memptr T_3 (struct (0 T_18 t0000)))
	T_17 (in 0x304<16> : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x1234<16> : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 (segment (300 T_2 t0300) (302 T_8 t0302) (304 T_18 t0304)))
  OrigDataType: (ptr16 (segment (300 T_2 t0300) (302 T_8 t0302) (304 T_18 t0304)))
T_4: (in 0x300<16> : word16)
  Class: Eq_4
  DataType: (memptr T_3 (struct (0 T_5 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5: (in Mem0[ds:0x300<16>:word16] : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_6: (in 0x5550<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0x302<16> : word16)
  Class: Eq_7
  DataType: (memptr T_3 (struct (0 T_8 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_8: (in Mem0[ds:0x302<16>:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in 0x300<16> : word16)
  Class: Eq_9
  DataType: (memptr T_3 (struct (0 T_10 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_10 t0000)))
T_10: (in Mem0[ds:0x300<16>:segptr32] : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_11: (in es_bx : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_12: (in SLICE(es_bx, selector, 16) : selector)
  Class: Eq_12
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_13: (in SLICE(es_bx, word16, 0) : word16)
  Class: Eq_13
  DataType: (memptr T_12 (struct (4 T_16 t0004)))
  OrigDataType: (memptr T_12 (struct (4 T_16 t0004)))
T_14: (in 4<16> : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in SLICE(es_bx, word16, 0) + 4<16> : word16)
  Class: Eq_15
  DataType: word16
  OrigDataType: word16
T_16: (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16] : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in 0x304<16> : word16)
  Class: Eq_17
  DataType: (memptr T_3 (struct (0 T_18 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_18 t0000)))
T_18: (in Mem0[ds:0x304<16>:word16] : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
