// SegmentedPointerProc
// Return size: 0
define SegmentedPointerProc
SegmentedPointerProc_entry:
	// succ:  l1
l1:
	Mem0[ds:0x300<16>:word16] = 0x1234<16>
	Mem0[ds:0x302<16>:word16] = 0x5550<16>
	es_bx = Mem0[ds:0x300<16>:segptr32]
	Mem0[ds:0x304<16>:word16] = Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16]
SegmentedPointerProc_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: segptr32
	T_2 (in 0x1234<16> : word16)
	T_6 (in Mem0[ds:0x300<16>:word16] : word16)
	T_13 (in Mem0[ds:0x300<16>:segptr32] : segptr32)
	T_14 (in es_bx : segptr32)
Eq_3: (ptr16 (segment (300 T_2 t0300) (302 T_10 t0302) (304 T_23 t0304)))
	T_3 (in ds : selector)
Eq_4: (memptr T_3 (struct (0 T_6 t0000)))
	T_4 (in 0x300<16> : word16)
Eq_5: segptr32
	T_5 (in ds:0x300<16> : segptr32)
Eq_7: word16
	T_7 (in 0x5550<16> : word16)
	T_10 (in Mem0[ds:0x302<16>:word16] : word16)
Eq_8: (memptr T_3 (struct (0 T_10 t0000)))
	T_8 (in 0x302<16> : word16)
Eq_9: segptr32
	T_9 (in ds:0x302<16> : segptr32)
Eq_11: (memptr T_3 (struct (0 T_13 t0000)))
	T_11 (in 0x300<16> : word16)
Eq_12: segptr32
	T_12 (in ds:0x300<16> : segptr32)
Eq_15: (ptr16 (segment))
	T_15 (in SLICE(es_bx, selector, 16) : selector)
Eq_16: (memptr T_15 (struct (4 T_20 t0004)))
	T_16 (in SLICE(es_bx, word16, 0) : word16)
Eq_17: word16
	T_17 (in 4<16> : word16)
Eq_18: word16
	T_18 (in SLICE(es_bx, word16, 0) + 4<16> : word16)
Eq_19: segptr32
	T_19 (in SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16> : segptr32)
Eq_20: word16
	T_20 (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16] : word16)
	T_23 (in Mem0[ds:0x304<16>:word16] : word16)
Eq_21: (memptr T_3 (struct (0 T_23 t0000)))
	T_21 (in 0x304<16> : word16)
Eq_22: segptr32
	T_22 (in ds:0x304<16> : segptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x1234<16> : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 (segment (300 T_2 t0300) (302 T_10 t0302) (304 T_23 t0304)))
  OrigDataType: (ptr16 (segment (300 T_2 t0300) (302 T_10 t0302) (304 T_23 t0304)))
T_4: (in 0x300<16> : word16)
  Class: Eq_4
  DataType: (memptr T_3 (struct (0 T_6 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_6 t0000)))
T_5: (in ds:0x300<16> : segptr32)
  Class: Eq_5
  DataType: segptr32
  OrigDataType: segptr32
T_6: (in Mem0[ds:0x300<16>:word16] : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_7: (in 0x5550<16> : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in 0x302<16> : word16)
  Class: Eq_8
  DataType: (memptr T_3 (struct (0 T_10 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_10 t0000)))
T_9: (in ds:0x302<16> : segptr32)
  Class: Eq_9
  DataType: segptr32
  OrigDataType: segptr32
T_10: (in Mem0[ds:0x302<16>:word16] : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_11: (in 0x300<16> : word16)
  Class: Eq_11
  DataType: (memptr T_3 (struct (0 T_13 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_13 t0000)))
T_12: (in ds:0x300<16> : segptr32)
  Class: Eq_12
  DataType: segptr32
  OrigDataType: segptr32
T_13: (in Mem0[ds:0x300<16>:segptr32] : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_14: (in es_bx : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_15: (in SLICE(es_bx, selector, 16) : selector)
  Class: Eq_15
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_16: (in SLICE(es_bx, word16, 0) : word16)
  Class: Eq_16
  DataType: (memptr T_15 (struct (4 T_20 t0004)))
  OrigDataType: (memptr T_15 (struct (4 T_20 t0004)))
T_17: (in 4<16> : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in SLICE(es_bx, word16, 0) + 4<16> : word16)
  Class: Eq_18
  DataType: word16
  OrigDataType: word16
T_19: (in SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16> : segptr32)
  Class: Eq_19
  DataType: segptr32
  OrigDataType: segptr32
T_20: (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 4<16>:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21: (in 0x304<16> : word16)
  Class: Eq_21
  DataType: (memptr T_3 (struct (0 T_23 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_23 t0000)))
T_22: (in ds:0x304<16> : segptr32)
  Class: Eq_22
  DataType: segptr32
  OrigDataType: segptr32
T_23: (in Mem0[ds:0x304<16>:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
