// ProcedureBuilder
// Return size: 0
define ProcedureBuilder
ProcedureBuilder_entry:
	// succ:  l1
l1:
	Mem0[ds:0x100<16>:ptr32] = SEQ(ds, 0x1234<16>)
ProcedureBuilder_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr16 (segment (100 T_7 t0100)))
	T_2 (in ds : selector)
Eq_3: (memptr T_2 <unknown>)
	T_3 (in 0x1234<16> : word16)
Eq_4: ptr32
	T_4 (in SEQ(ds, 0x1234<16>) : ptr32)
	T_7 (in Mem0[ds:0x100<16>:ptr32] : ptr32)
Eq_5: (memptr T_2 (struct (0 T_7 t0000)))
	T_5 (in 0x100<16> : word16)
Eq_6: segptr32
	T_6 (in ds:0x100<16> : segptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (100 T_7 t0100)))
  OrigDataType: (ptr16 (segment (100 T_7 t0100)))
T_3: (in 0x1234<16> : word16)
  Class: Eq_3
  DataType: (memptr T_2 <unknown>)
  OrigDataType: (memptr T_2 <unknown>)
T_4: (in SEQ(ds, 0x1234<16>) : ptr32)
  Class: Eq_4
  DataType: ptr32
  OrigDataType: ptr32
T_5: (in 0x100<16> : word16)
  Class: Eq_5
  DataType: (memptr T_2 (struct (0 T_7 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_7 t0000)))
T_6: (in ds:0x100<16> : segptr32)
  Class: Eq_6
  DataType: segptr32
  OrigDataType: segptr32
T_7: (in Mem0[ds:0x100<16>:ptr32] : ptr32)
  Class: Eq_4
  DataType: ptr32
  OrigDataType: ptr32
