// SegMem3Mock
// Return size: 0
define SegMem3Mock
SegMem3Mock_entry:
	// succ:  l1
l1:
	Mem0[0x1796<16>:1<16>:word16] = 0x800<16>
	Mem0[0x800<16>:0x5422<16>:word16] = ds
	Mem0[0x800<16>:0x66<16>:word16] = Mem0[0x800<16>:0x5420<16>:word16]
SegMem3Mock_exit:

// Equivalence classes ////////////
Eq_1: (ptr32 (struct "Globals"))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (ptr16 (segment (66 T_12 t0066) (5420 T_10 t5420) (5422 T_8 t5422)))
	T_2 (in 0x800<16> : selector)
	T_5 (in Mem0[0x1796<16>:1<16>:word16] : word16)
Eq_3: (ptr16 (segment (1 T_5 t0001)))
	T_3 (in 0x1796<16> : selector)
Eq_4: (memptr T_3 (struct (0 T_5 t0000)))
	T_4 (in 1<16> : word16)
Eq_6: (ptr16 (segment))
	T_6 (in ds : selector)
	T_8 (in Mem0[0x800<16>:0x5422<16>:word16] : word16)
Eq_7: (memptr T_2 (struct (0 T_8 t0000)))
	T_7 (in 0x5422<16> : word16)
Eq_9: (memptr T_2 (struct (0 T_10 t0000)))
	T_9 (in 0x5420<16> : word16)
Eq_10: word16
	T_10 (in Mem0[0x800<16>:0x5420<16>:word16] : word16)
	T_12 (in Mem0[0x800<16>:0x66<16>:word16] : word16)
Eq_11: (memptr T_2 (struct (0 T_12 t0000)))
	T_11 (in 0x66<16> : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct "Globals"))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x800<16> : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (66 T_12 t0066) (5420 T_10 t5420) (5422 T_8 t5422)))
  OrigDataType: (ptr16 (segment (66 T_12 t0066) (5420 T_10 t5420) (5422 T_8 t5422)))
T_3: (in 0x1796<16> : selector)
  Class: Eq_3
  DataType: (ptr16 (segment (1 T_5 t0001)))
  OrigDataType: (ptr16 (segment (1 T_5 t0001)))
T_4: (in 1<16> : word16)
  Class: Eq_4
  DataType: (memptr T_3 (struct (0 T_5 t0000)))
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5: (in Mem0[0x1796<16>:1<16>:word16] : word16)
  Class: Eq_2
  DataType: (ptr16 (segment (66 T_12 t0066) (5420 T_10 t5420) (5422 T_8 t5422)))
  OrigDataType: word16
T_6: (in ds : selector)
  Class: Eq_6
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_7: (in 0x5422<16> : word16)
  Class: Eq_7
  DataType: (memptr T_2 (struct (0 T_8 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_8 t0000)))
T_8: (in Mem0[0x800<16>:0x5422<16>:word16] : word16)
  Class: Eq_6
  DataType: (ptr16 (segment))
  OrigDataType: word16
T_9: (in 0x5420<16> : word16)
  Class: Eq_9
  DataType: (memptr T_2 (struct (0 T_10 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_10 t0000)))
T_10: (in Mem0[0x800<16>:0x5420<16>:word16] : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in 0x66<16> : word16)
  Class: Eq_11
  DataType: (memptr T_2 (struct (0 T_12 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x800<16>:0x66<16>:word16] : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
