// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : (ptr32 word32))
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_3: (in 4<i32> : int32)
  Class: Eq_3
  DataType: int32
  OrigDataType: int32
T_4: (in p + 4<i32> : word32)
  Class: Eq_4
  DataType: ptr32
  OrigDataType: ptr32
