// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in id : bool)
  Class: Eq_2
  DataType: bool
  OrigDataType: bool
T_3: (in id1 : int32)
  Class: Eq_3
  DataType: int32
  OrigDataType: int32
T_4: (in id2 : int32)
  Class: Eq_4
  DataType: int32
  OrigDataType: int32
T_5: (in id ? id1 : id2 : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
