// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in psz : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in 0x00000004<32> : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in psz + 0x00000004<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[psz + 0x00000004<32>:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in 0x1200 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in SEQ(Mem0[psz + 0x00000004<32>:word16], 0x1200) : cuipos32)
  Class: Eq_7
  DataType: cuipos32
  OrigDataType: cuipos32
