// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : (ptr32 real64))
  Class: Eq_2
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_3: (in 4<32> : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in p - 4<32> : (ptr32 real64))
  Class: Eq_4
  DataType: ptr32
  OrigDataType: ptr32
