// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: selector
  OrigDataType: selector
T_3: (in 0x123<16> : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in ds:0x123<16> : segptr32)
  Class: Eq_4
  DataType: segptr32
  OrigDataType: segptr32
T_5: (in Mem0[ds:0x123<16>:byte] : byte)
  Class: Eq_5
  DataType: byte
  OrigDataType: byte
