// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : ptr32)
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr (struct (4 word32 dw0004)))
  OrigDataType: (ptr (struct (4 word32 dw0004)))
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: int32
  OrigDataType: int32
T_4: (in p + 0x00000004 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[p + 0x00000004:word32] : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
