// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: real32
  OrigDataType: real32
T_3: (in -5.5F : real32)
  Class: Eq_2
  DataType: real32
  OrigDataType: real32
T_4: (in p >= -5.5F : bool)
  Class: Eq_4
  DataType: bool
  OrigDataType: bool
