// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct (300400 T_4 t300400)))
  OrigDataType: (ptr32 (struct (300400 T_4 t300400)))
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr32 (fn T_5 (real32)))
  OrigDataType: (ptr32 (fn T_5 (real32)))
T_3: (in 0x300400<32> : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (0 T_4 t0000)))
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem0[0x300400<32>:word32] : word32)
  Class: Eq_4
  DataType: real32
  OrigDataType: real32
T_5: (in p(Mem0[0x300400<32>:word32]) : void)
  Class: Eq_5
  DataType: void
  OrigDataType: void
