// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr UNKNOWN_TYPE)
  OrigDataType: (ptr UNKNOWN_TYPE)
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in p + 0x00000004 : word32)
  Class: Eq_4
  DataType: (ptr T_5)
  OrigDataType: (ptr T_5)
T_5: (in Mem0[p + 0x00000004:word32] : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
