// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: ui32
  OrigDataType: ui32
T_4: (in p - 0x00000004 : word32)
  Class: Eq_4
  DataType: (ptr32 (struct (0 T_7 t0000)))
  OrigDataType: (ptr32 (struct (0 T_7 t0000)))
T_5: (in 0x00000000 : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in p - 0x00000004 + 0x00000000 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in Mem0[p - 0x00000004 + 0x00000000:word32] : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
