// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 (segment (123 T_4 t0123)))
  OrigDataType: (ptr16 (segment (123 T_4 t0123)))
T_3: (in 0x123<16> : word16)
  Class: Eq_3
  DataType: (memptr T_2 (struct (0 T_4 t0000)))
  OrigDataType: (memptr T_2 (struct (0 T_4 t0000)))
T_4: (in Mem0[ds:0x123<16>:byte] : byte)
  Class: Eq_4
  DataType: byte
  OrigDataType: byte
