// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2:
  Class: Eq_2
  DataType: 
  OrigDataType: 
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_4: (in 4<16> : word16)
  Class: Eq_4
  DataType: (memptr T_3 T_2)
  OrigDataType: (memptr T_3 T_2)
T_5: (in SEQ(ds, 4<16>) : ptr32)
  Class: Eq_5
  DataType: (ptr32 T_2)
  OrigDataType: (ptr32 T_2)
