// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: 
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr32 (struct (C T_5 t000C)))
  OrigDataType: (ptr32 (struct (C T_5 t000C)))
T_3: (in 0xC<32> : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in p + 0xC<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[p + 0xC<32>:word32] : word32)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
T_6: (in 0xC<32> : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in p + 0xC<32> : word32)
  Class: Eq_7
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 int32)
T_8: (in Mem0[p + 0xC<32>:word32] : word32)
  Class: Eq_5
  DataType: (union (int32 u0) (real32 u1))
  OrigDataType: (union (int32 u0) (real32 u1))
