// ProcedureBuilder
// Return size: 0
void ProcedureBuilder()
ProcedureBuilder_entry:
	// succ:  l1
l1:
	Mem0[cs:0x00000001:word16] = 0x0800
ProcedureBuilder_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (8000 (ptr16 Eq_2) ptr8000))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment)
	T_2 (in 0x0800 : selector)
	T_5 (in Mem0[cs:0x00000001:word16] : word16)
Eq_3: (segment (1 (ptr16 Eq_2) ptr0001))
	T_3 (in cs : selector)
Eq_4: (struct (0 (ptr16 Eq_2) ptr0000))
	T_4 (in 0x00000001 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x0800 : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment))
T_3: (in cs : selector)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (1 T_5 t0001)))
T_4: (in 0x00000001 : word32)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_3) Eq_4)
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5: (in Mem0[cs:0x00000001:word16] : word16)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: word16
