// UnionIntRealMock
// Return size: 0
define UnionIntRealMock
UnionIntRealMock_entry:
	// succ:  l1
l1:
	x = i
	x = r
	Mem0[ptr:int32] = i
	Mem0[ptr + 4<i32>:real32] = r
	return
	// succ:  UnionIntRealMock_exit
UnionIntRealMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (union (int32 u0) (real32 u1))
	T_2 (in i : int32)
	T_3 (in x : word32)
	T_4 (in r : real32)
	T_6 (in Mem0[ptr:int32] : int32)
	T_9 (in Mem0[ptr + 4<i32>:real32] : real32)
Eq_5: (struct (0 Eq_2 t0000) (4 Eq_2 t0004))
	T_5 (in ptr : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in i : int32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: int32
T_3: (in x : word32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: (union (int32 u0) (real32 u1))
T_4: (in r : real32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: real32
T_5: (in ptr : word32)
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (struct (0 T_6 t0000) (4 T_9 t0004)))
T_6: (in Mem0[ptr:int32] : int32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: int32
T_7: (in 4<i32> : int32)
  Class: Eq_7
  DataType: int32
  OrigDataType: int32
T_8: (in ptr + 4<i32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[ptr + 4<i32>:real32] : real32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: real32
