// Before ///////
// Fn
// Return size: 0
define Fn
Fn_entry:
	// succ:  l1
l1:
	a = 0x123456<32>
	Mem0[a + i * 8<32>:int32] = 42<i32>
Fn_exit:

// After ///////
// Fn
// Return size: 0
define Fn
Fn_entry:
	// succ:  l1
l1:
	a = g_a123456
	a[i].dw0000 = 42<i32>
Fn_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (123456 (arr Eq_9) a123456))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_9: (struct "Eq_9" 0008 (0 int32 dw0000))
	T_9
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x123456<32> : word32)
  Class: Eq_2
  DataType: (ptr32 (arr Eq_9))
  OrigDataType: word32
T_3: (in a : (arr Eq_9))
  Class: Eq_2
  DataType: (ptr32 (arr Eq_9))
  OrigDataType: (ptr32 (struct (0 (arr T_9) a0000)))
T_4: (in 42<i32> : int32)
  Class: Eq_4
  DataType: int32
  OrigDataType: int32
T_5: (in i : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in 8<32> : word32)
  Class: Eq_6
  DataType: ui32
  OrigDataType: ui32
T_7: (in i * 8<32> : word32)
  Class: Eq_7
  DataType: ui32
  OrigDataType: ui32
T_8: (in a[i * 8<32>] : int32)
  Class: Eq_4
  DataType: int32
  OrigDataType: int32
T_9:
  Class: Eq_9
  DataType: Eq_9
  OrigDataType: (struct 0008 (0 T_8 t0000))
T_10:
  Class: Eq_10
  DataType: (arr Eq_9)
  OrigDataType: (arr T_9)
