// Before ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	Mem0[p:word16] = 4<16>
	Mem0[p + 4<16>:word16] = 4<16>
	p = p + i
proc1_exit:

// After ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	p->w0000 = 4<16>
	p->w0004 = 4<16>
	p = p + i /16 6<i32>
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_3: (struct "Eq_3" (0 word16 w0000) (4 word16 w0004))
	T_3 (in p : (ptr16 Eq_3))
	T_12 (in p + i : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 4<16> : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3: (in p : (ptr16 Eq_3))
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (struct (0 T_6 t0000) (4 T_10 t0004)))
T_4: (in 0<16> : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in p + 0<16> : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in Mem0[p + 0<16>:word16] : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_7: (in 4<16> : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in 4<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in p + 4<16> : word16)
  Class: Eq_9
  DataType: ptr16
  OrigDataType: ptr16
T_10: (in Mem0[p + 4<16>:word16] : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_11: (in i : int16)
  Class: Eq_11
  DataType: int16
  OrigDataType: int16
T_12: (in p + i : word16)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: ptr16
