// Before ///////
// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	ptr_3 = 0x4000000<32>
	goto looptest
	// succ:  looptest
l2:
	Mem5[ptr_3:word32] = 0<32>
	ptr_3 = ptr_3 + 4<32>
	// succ:  looptest
looptest:
	branch ptr_3 >=u 0x4001000<32> done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

// After ///////
// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	ptr_3 = g_a4000000
	goto looptest
	// succ:  looptest
l2:
	*ptr_3 = 0<32>
	ptr_3 = ptr_3 + 1<i32>
	// succ:  looptest
looptest:
	branch ptr_3 >= &g_dw4001000 done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (4000000 (arr word32 1024) a4000000) (4001000 word32 dw4001000))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x4000000<32> : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: word32
T_3: (in ptr_3 : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct 0004 (0 word32 dw0000)))
T_4: (in 0x4001000<32> : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: up32
T_5: (in ptr_3 >= &g_dw4001000 : bool)
  Class: Eq_5
  DataType: bool
  OrigDataType: bool
T_6: (in 0<32> : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in 0<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in ptr_3 + 0<32> : word32)
  Class: Eq_8
  DataType: up32
  OrigDataType: up32
T_9: (in Mem5[ptr_3 + 0<32>:word32] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_10: (in 4<32> : word32)
  Class: Eq_10
  DataType: int32
  OrigDataType: int32
T_11: (in ptr_3 + 4<32> : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_12:
  Class: Eq_12
  DataType: word32
  OrigDataType: (struct 0004 (0 T_9 t0000))
T_13:
  Class: Eq_13
  DataType: (arr word32 1024)
  OrigDataType: (arr T_12 1024)
