// Before ///////
// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	word32 ptr_0 = 0x04000000
	goto looptest
	// succ:  looptest
l2:
	Mem2[ptr_0:word32] = 0x00000000
	ptr_0 = ptr_0 + 0x00000004
	// succ:  looptest
looptest:
	branch ptr_0 >=u 0x04001000 done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

// After ///////
// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	word32 * ptr_0 = globals->a4000000
	goto looptest
	// succ:  looptest
l2:
	*ptr_0 = 0x00000000
	ptr_0 = ptr_0 + 1
	// succ:  looptest
looptest:
	branch ptr_0 >= &globals->dw4001000 done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (4000000 (arr word32 1024) a4000000) (4001000 word32 dw4001000))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ptr_0 : (ptr32 word32))
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct 0004 (0 word32 dw0000)))
T_3: (in 0x04000000 : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: word32
T_4: (in 0x04001000 : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: up32
T_5: (in ptr_0 >= &globals->dw4001000 : bool)
  Class: Eq_5
  DataType: bool
  OrigDataType: bool
T_6: (in 0x00000000 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in 0x00000000 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in ptr_0 + 0x00000000 : word32)
  Class: Eq_8
  DataType: up32
  OrigDataType: up32
T_9: (in Mem2[ptr_0 + 0x00000000:word32] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_10: (in 0x00000004 : word32)
  Class: Eq_10
  DataType: int32
  OrigDataType: int32
T_11: (in ptr_0 + 0x00000004 : word32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_12:
  Class: Eq_12
  DataType: word32
  OrigDataType: (struct 0004 (0 T_9 t0000))
