// Before ///////
// IndirectCallFragment
// Return size: 0
define IndirectCallFragment
IndirectCallFragment_entry:
	// succ:  l1
l1:
	call SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) (retsize: 4;)
	return
	// succ:  IndirectCallFragment_exit
IndirectCallFragment_exit:

// After ///////
// IndirectCallFragment
// Return size: 0
define IndirectCallFragment
IndirectCallFragment_entry:
	// succ:  l1
l1:
	(0x2700<16>->*(ds->a2040)[di])()
	return
	// succ:  IndirectCallFragment_exit
IndirectCallFragment_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (27000 (ptr16 Eq_2) ptr27000))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "Eq_2")
	T_2 (in 0x2700<16> : selector)
Eq_3: (segment "Eq_3" (2040 (arr (memptr (ptr16 Eq_2) code)) a2040))
	T_3 (in ds : (ptr16 Eq_3))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x2700<16> : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment))
T_3: (in ds : (ptr16 Eq_3))
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (2040 T_12 t2040)))
T_4: (in 0x2040<16> : word16)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_3) (memptr (ptr16 Eq_2) code))
  OrigDataType: (memptr T_3 T_12)
T_5: (in SEQ(ds, 0x2040<16>) : ptr32)
  Class: Eq_5
  DataType: (ptr32 (arr (memptr (ptr16 Eq_2) code)))
  OrigDataType: (ptr32 T_12)
T_6: (in di : ui16)
  Class: Eq_6
  DataType: ui16
  OrigDataType: ui16
T_7: (in 2<16> : word16)
  Class: Eq_7
  DataType: ui16
  OrigDataType: ui16
T_8: (in di * 2<16> : word16)
  Class: Eq_8
  DataType: ui16
  OrigDataType: ui16
T_9: (in SEQ(ds, 0x2040<16>)[di * 2<16>] : word16)
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_2) code)
  OrigDataType: (memptr T_2 code)
T_10: (in SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) : ptr32)
  Class: Eq_10
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_11:
  Class: Eq_11
  DataType: (memptr (ptr16 Eq_2) code)
  OrigDataType: (struct 0002 (0 T_9 t0000))
T_12:
  Class: Eq_12
  DataType: (arr (memptr (ptr16 Eq_2) code))
  OrigDataType: (arr T_11)
