// Before ///////
// ConstantUnionMock
void ConstantUnionMock()
ConstantUnionMock_entry:
	// succ:  l1
l1:
	x = 3
	x = 3F
ConstantUnionMock_exit:

// After ///////
// ConstantUnionMock
void ConstantUnionMock()
ConstantUnionMock_entry:
	// succ:  l1
l1:
	x.u0 = 3;
	x.u1 = 3F;
ConstantUnionMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Eq_1")
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (union "Eq_2" (int32 u0) (real32 u1))
	T_2 (in 3 : int32)
	T_3 (in x : word32)
	T_4 (in 3F : real32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct))
T_2: (in 3 : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_3: (in x : word32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: (union (int32 u0) (real32 u1))
T_4: (in 3F : real32)
  Class: Eq_2
  DataType: real32
  OrigDataType: real32
