// Before ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	word16 ax = rand()
	Mem1[0x1300:word16] = ax
	return
	// succ:  proc1_exit
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	int16 ax = rand()
	globals->w1300 = ax
	return
	// succ:  proc1_exit
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (1300 int16 w1300))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_3: (fn int16 ())
	T_3 (in rand : ptr32)
	T_4 (in signature of rand : void)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ax : int16)
  Class: Eq_2
  DataType: int16
  OrigDataType: int16
T_3: (in rand : ptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_5 ()))
T_4: (in signature of rand : void)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: 
T_5: (in rand() : int16)
  Class: Eq_2
  DataType: int16
  OrigDataType: int16
T_6: (in 0x1300 : word16)
  Class: Eq_6
  DataType: (ptr16 int16)
  OrigDataType: (ptr16 (struct (0 T_7 t0000)))
T_7: (in Mem1[0x1300:word16] : word16)
  Class: Eq_2
  DataType: int16
  OrigDataType: word16
