// Before ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	ds2 = ds
	Mem0[ds + 0x00005400:bool] = Mem0[Mem0[ds + 0x00005404:word32] + 0x00000004:word16] < 0x0014
	Mem0[Mem0[ds2 + 0x00005404:word32] + 0x00000004:word16] = 0x0000
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	ds2 = ds
	ds->f5400 = ds->ptr5404->w0004 < 0x0014
	ds2->ptr5404->w0004 = 0x0000
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (struct "Eq_2" (5400 bool f5400) (5404 (ptr Eq_6) ptr5404))
	T_2 (in ds : word32)
	T_3 (in ds2 : word32)
Eq_6: (struct "Eq_6" (4 ci16 w0004))
	T_6 (in Mem0[ds + 0x00005404:word32] : word32)
	T_18 (in Mem0[ds2 + 0x00005404:word32] : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in ds : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (5400 T_14 t5400) (5404 T_6 t5404)))
T_3: (in ds2 : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (5404 T_18 t5404)))
T_4: (in 0x00005404 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in ds + 0x00005404 : word32)
  Class: Eq_5
  DataType: (ptr (ptr Eq_6))
  OrigDataType: (ptr T_6)
T_6: (in Mem0[ds + 0x00005404:word32] : word32)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: (ptr (struct (4 T_9 t0004)))
T_7: (in 0x00000004 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem0[ds + 0x00005404:word32] + 0x00000004 : word32)
  Class: Eq_8
  DataType: (ptr ci16)
  OrigDataType: (ptr T_9)
T_9: (in Mem0[Mem0[ds + 0x00005404:word32] + 0x00000004:word16] : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: ci16
T_10: (in 0x0014 : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: ci16
T_11: (in ds->ptr5404->w0004 < 0x0014 : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_12: (in 0x00005400 : word32)
  Class: Eq_12
  DataType: word32
  OrigDataType: word32
T_13: (in ds + 0x00005400 : word32)
  Class: Eq_13
  DataType: (ptr bool)
  OrigDataType: (ptr T_14)
T_14: (in Mem0[ds + 0x00005400:bool] : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_15: (in 0x0000 : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: word16
T_16: (in 0x00005404 : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in ds2 + 0x00005404 : word32)
  Class: Eq_17
  DataType: (ptr (ptr Eq_6))
  OrigDataType: (ptr T_18)
T_18: (in Mem0[ds2 + 0x00005404:word32] : word32)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: (ptr (struct (4 T_21 t0004)))
T_19: (in 0x00000004 : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in Mem0[ds2 + 0x00005404:word32] + 0x00000004 : word32)
  Class: Eq_20
  DataType: (ptr ci16)
  OrigDataType: (ptr T_21)
T_21: (in Mem0[Mem0[ds2 + 0x00005404:word32] + 0x00000004:word16] : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: word16
