// Before ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	ds2 = ds
	Mem0[ds + 0x5400<32>:bool] = Mem0[Mem0[ds + 0x5404<32>:word32] + 4<32>:word16] < 0x14<16>
	Mem0[Mem0[ds2 + 0x5404<32>:word32] + 4<32>:word16] = 0<16>
proc1_exit:

// After ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	ds2 = ds
	ds->f5400 = ds->ptr5404->w0004 < 0x14<16>
	ds2->ptr5404->w0004 = 0<16>
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (struct "Eq_2" (5400 bool f5400) (5404 (ptr32 Eq_6) ptr5404))
	T_2 (in ds : (ptr32 Eq_2))
	T_3 (in ds2 : (ptr32 Eq_2))
Eq_6: (struct "Eq_6" (4 ci16 w0004))
	T_6 (in Mem0[ds + 0x5404<32>:word32] : word32)
	T_18 (in Mem0[ds2 + 0x5404<32>:word32] : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : (ptr32 Eq_2))
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (struct (5400 T_14 t5400) (5404 T_6 t5404)))
T_3: (in ds2 : (ptr32 Eq_2))
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (struct (5404 T_18 t5404)))
T_4: (in 0x5404<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in ds + 0x5404<32> : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in Mem0[ds + 0x5404<32>:word32] : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: (ptr32 (struct (4 T_9 t0004)))
T_7: (in 4<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem0[ds + 0x5404<32>:word32] + 4<32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[Mem0[ds + 0x5404<32>:word32] + 4<32>:word16] : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: ci16
T_10: (in 0x14<16> : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: ci16
T_11: (in ds->ptr5404->w0004 < 0x14<16> : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_12: (in 0x5400<32> : word32)
  Class: Eq_12
  DataType: word32
  OrigDataType: word32
T_13: (in ds + 0x5400<32> : word32)
  Class: Eq_13
  DataType: ptr32
  OrigDataType: ptr32
T_14: (in Mem0[ds + 0x5400<32>:bool] : bool)
  Class: Eq_11
  DataType: bool
  OrigDataType: bool
T_15: (in 0<16> : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: word16
T_16: (in 0x5404<32> : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in ds2 + 0x5404<32> : word32)
  Class: Eq_17
  DataType: word32
  OrigDataType: word32
T_18: (in Mem0[ds2 + 0x5404<32>:word32] : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: (ptr32 (struct (4 T_21 t0004)))
T_19: (in 4<32> : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in Mem0[ds2 + 0x5404<32>:word32] + 4<32> : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_21: (in Mem0[Mem0[ds2 + 0x5404<32>:word32] + 4<32>:word16] : word16)
  Class: Eq_9
  DataType: ci16
  OrigDataType: word16
