// GlobalVariablesMock
void GlobalVariablesMock()
GlobalVariablesMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	real32 * ptr = &globals->r10000004
	*ptr = 0.75F;
	globals->r10000000 = 0.5F;
	// succ: 

// Equivalence classes ////////////
Eq_1: (struct "Eq_1" (10000000 real32 r10000000) (10000004 real32 r10000004))
	Globals (in globals : ptr32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (10000000 T_10 t10000000) (10000004 T_7 t10000004)))
T_2: (in ptr : (ptr real32))
  Class: Eq_2
  DataType: (ptr real32)
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_3: (in 0x10000004 : word32)
  Class: Eq_2
  DataType: (ptr real32)
  OrigDataType: word32
T_4: (in 0.75F : real32)
  Class: Eq_4
  DataType: real32
  OrigDataType: real32
T_5: (in 0x00000000 : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in ptr + 0x00000000 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in Mem0[ptr + 0x00000000:real32] : real32)
  Class: Eq_4
  DataType: real32
  OrigDataType: real32
T_8: (in 0.5F : real32)
  Class: Eq_8
  DataType: real32
  OrigDataType: real32
T_9: (in 0x10000000 : word32)
  Class: Eq_9
  DataType: (ptr real32)
  OrigDataType: (ptr (struct (0 T_10 t0000)))
T_10: (in Mem0[0x10000000:real32] : real32)
  Class: Eq_8
  DataType: real32
  OrigDataType: real32
