// Before ///////
// GlobalVariablesMock
// Return size: 0
define GlobalVariablesMock
GlobalVariablesMock_entry:
	// succ:  l1
l1:
	r63 = fp
	ptr = 0x10000004<32>
	Mem0[ptr:real32] = 0.75F
	Mem0[0x10000000<32>:real32] = 0.5F
GlobalVariablesMock_exit:

// After ///////
// GlobalVariablesMock
// Return size: 0
define GlobalVariablesMock
GlobalVariablesMock_entry:
	// succ:  l1
l1:
	r63 = fp
	ptr = &g_r10000004
	*ptr = 0.75F
	g_r10000000 = 0.5F
GlobalVariablesMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000000 real32 r10000000) (10000004 real32 r10000004))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fp : ptr32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_3: (in r63 : ptr32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_4: (in 0x10000004<32> : word32)
  Class: Eq_4
  DataType: (ptr32 real32)
  OrigDataType: word32
T_5: (in ptr : (ptr32 real32))
  Class: Eq_4
  DataType: (ptr32 real32)
  OrigDataType: (ptr32 (struct (0 T_9 t0000)))
T_6: (in 0.75F : real32)
  Class: Eq_6
  DataType: real32
  OrigDataType: real32
T_7: (in 0<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in ptr + 0<32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[ptr + 0<32>:real32] : real32)
  Class: Eq_6
  DataType: real32
  OrigDataType: real32
T_10: (in 0.5F : real32)
  Class: Eq_10
  DataType: real32
  OrigDataType: real32
T_11: (in 0x10000000<32> : word32)
  Class: Eq_11
  DataType: (ptr32 real32)
  OrigDataType: (ptr32 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x10000000<32>:real32] : real32)
  Class: Eq_10
  DataType: real32
  OrigDataType: real32
