// Before ///////
// IntelIndexedAddressingMode
// Return size: 0
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:
	// succ:  l1
l1:
	es = Mem0[ds:0x7070:word16]
	ax = 0x004A
	si = ax *s Mem0[ds:0x1C0A:word16]
	bx = Mem0[ds:0x0CA4:word16]
	Mem0[ds:bx + 0x000A + si:byte] = 0xF8
	return
	// succ:  IntelIndexedAddressingMode_exit
IntelIndexedAddressingMode_exit:

// After ///////
// IntelIndexedAddressingMode
// Return size: 0
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:
	// succ:  l1
l1:
	es = ds->w7070
	ax = 0x004A
	si = ax *s ds->w1C0A
	bx = ds->ptr0CA4
	(&(ds->*(ds->*bx).a000A))[si] = 0xF8
	return
	// succ:  IntelIndexedAddressingMode_exit
IntelIndexedAddressingMode_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "Eq_2" (CA4 (memptr (ptr16 Eq_2) Eq_13) ptr0CA4) (1C0A int16 w1C0A) (7070 word16 w7070))
	T_2 (in ds : word16)
Eq_13: (struct "Eq_13" (A (arr byte) a000A))
	T_13 (in Mem0[ds:0x0CA4:word16] : word16)
	T_14 (in bx : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : word16)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (CA4 T_13 t0CA4) (1C0A T_9 t1C0A) (7070 T_4 t7070)))
T_3: (in 0x7070 : word16)
  Class: Eq_3
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_4 t0000)))
T_4: (in Mem0[ds:0x7070:word16] : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in es : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_6: (in 0x004A : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_7: (in ax : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_8: (in 0x1C0A : word16)
  Class: Eq_8
  DataType: (memptr (ptr16 Eq_2) int16)
  OrigDataType: (memptr T_2 (struct (0 T_9 t0000)))
T_9: (in Mem0[ds:0x1C0A:word16] : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: int16
T_10: (in ax *s ds->w1C0A : int16)
  Class: Eq_10
  DataType: int16
  OrigDataType: int16
T_11: (in si : word16)
  Class: Eq_10
  DataType: int16
  OrigDataType: int16
T_12: (in 0x0CA4 : word16)
  Class: Eq_12
  DataType: (memptr (ptr16 Eq_2) (memptr (ptr16 Eq_2) Eq_13))
  OrigDataType: (memptr T_2 (struct (0 T_13 t0000)))
T_13: (in Mem0[ds:0x0CA4:word16] : word16)
  Class: Eq_13
  DataType: (memptr (ptr16 Eq_2) Eq_13)
  OrigDataType: word16
T_14: (in bx : word16)
  Class: Eq_13
  DataType: (memptr (ptr16 Eq_2) Eq_13)
  OrigDataType: (memptr T_2 (struct (A T_21 t000A)))
T_15: (in 0xF8 : byte)
  Class: Eq_15
  DataType: byte
  OrigDataType: byte
T_16: (in 0x000A : word16)
  Class: Eq_16
  DataType: int16
  OrigDataType: int16
T_17: (in bx + 0x000A : word16)
  Class: Eq_17
  DataType: (memptr (ptr16 Eq_2) byte)
  OrigDataType: (memptr T_2 (struct (0 (arr T_20) a0000)))
T_18: (in bx + 0x000A + si : word16)
  Class: Eq_18
  DataType: (memptr (ptr16 Eq_2) byte)
  OrigDataType: (memptr T_2 (struct (0 T_19 t0000)))
T_19: (in Mem0[ds:bx + 0x000A + si:byte] : byte)
  Class: Eq_15
  DataType: byte
  OrigDataType: byte
T_20:
  Class: Eq_20
  DataType: byte
  OrigDataType: (struct 0001 (0 T_19 t0000))
T_21:
  Class: Eq_21
  DataType: (arr byte)
  OrigDataType: (arr T_20)
