// Before ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	word16 ds
	word16 cx
	// succ:  l1
l1:
	word16 di_3 = 0x5388<16>
	goto lupe
	// succ:  lupe
l2:
	return
	// succ:  proc1_exit
lupe:
	Mem6[ds:di_3 + 0<16>:word16] = 0<16>
	di_3 = di_3 + 2<16>
	cx = cx - 1<16>
	branch cx != 0<16> lupe
	goto l2
	// succ:  l2 lupe
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	struct Eq_2 * ds
	word16 cx
	// succ:  l1
l1:
	word16 Eq_2::* di_3 = Eq_2::a5388
	goto lupe
	// succ:  lupe
l2:
	return
	// succ:  proc1_exit
lupe:
	ds->*di_3 = 0<16>
	di_3 = di_3 + 1<i32>
	cx = cx - 1<16>
	branch cx != 0<16> lupe
	goto l2
	// succ:  l2 lupe
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "Eq_2" (5388 (arr word16) a5388))
	T_2 (in ds : (ptr16 Eq_2))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : (ptr16 Eq_2))
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (5388 T_17 t5388)))
T_3: (in cx : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in di_3 : (memptr (ptr16 Eq_2) word16))
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct 0002 (0 word16 w0000)))
T_5: (in 0x5388<16> : word16)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: word16
T_6: (in 0<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0<16> : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in di_3 + 0<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in Mem6[ds:di_3 + 0<16>:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_10: (in 2<16> : word16)
  Class: Eq_10
  DataType: int16
  OrigDataType: int16
T_11: (in di_3 + 2<16> : word16)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct 0002 (0 word16 w0000)))
T_12: (in 1<16> : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in cx - 1<16> : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_14: (in 0<16> : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_15: (in cx != 0<16> : bool)
  Class: Eq_15
  DataType: bool
  OrigDataType: bool
T_16:
  Class: Eq_16
  DataType: word16
  OrigDataType: (struct 0002 (0 T_9 t0000))
T_17:
  Class: Eq_17
  DataType: (arr word16)
  OrigDataType: (arr T_16)
