// Before ///////
// PtrPtrIntMock
// Return size: 0
define PtrPtrIntMock
PtrPtrIntMock_entry:
	// succ:  l1
l1:
	r2 = Mem0[r1:word32]
	r3 = Mem0[r2:word32]
	Mem0[0x10000<32>:word32] = r3
	Mem0[0x10004<32>:word32] = r1
	return r3
	// succ:  PtrPtrIntMock_exit
PtrPtrIntMock_exit:

// After ///////
// PtrPtrIntMock
// Return size: 0
define PtrPtrIntMock
PtrPtrIntMock_entry:
	// succ:  l1
l1:
	r2 = *r1
	r3 = *r2
	g_dw10000 = r3
	g_ptr10004 = r1
	return r3
	// succ:  PtrPtrIntMock_exit
PtrPtrIntMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000 word32 dw10000) (10004 (ptr32 (ptr32 word32)) ptr10004))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in r1 : (ptr32 (ptr32 word32)))
  Class: Eq_2
  DataType: (ptr32 (ptr32 word32))
  OrigDataType: (ptr32 (struct (0 T_5 t0000)))
T_3: (in 0<32> : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in r1 + 0<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[r1 + 0<32>:word32] : word32)
  Class: Eq_5
  DataType: (ptr32 word32)
  OrigDataType: word32
T_6: (in r2 : (ptr32 word32))
  Class: Eq_5
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_9 t0000)))
T_7: (in 0<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in r2 + 0<32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[r2 + 0<32>:word32] : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_10: (in r3 : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_11: (in 0x10000<32> : word32)
  Class: Eq_11
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x10000<32>:word32] : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_13: (in 0x10004<32> : word32)
  Class: Eq_13
  DataType: (ptr32 (ptr32 (ptr32 word32)))
  OrigDataType: (ptr32 (struct (0 T_14 t0000)))
T_14: (in Mem0[0x10004<32>:word32] : word32)
  Class: Eq_2
  DataType: (ptr32 (ptr32 word32))
  OrigDataType: word32
