// Before ///////
// PtrPtrIntMock
// Return size: 0
void PtrPtrIntMock()
PtrPtrIntMock_entry:
	// succ:  l1
l1:
	r2 = Mem0[r1:word32]
	r3 = Mem0[r2:word32]
	Mem0[0x00010000:word32] = r3
	Mem0[0x00010004:word32] = r1
	return r3
	// succ:  PtrPtrIntMock_exit
PtrPtrIntMock_exit:

// After ///////
// PtrPtrIntMock
// Return size: 0
void PtrPtrIntMock()
PtrPtrIntMock_entry:
	// succ:  l1
l1:
	r2 = *r1
	r3 = *r2
	globals->dw10000 = r3
	globals->ptr10004 = r1
	return r3
	// succ:  PtrPtrIntMock_exit
PtrPtrIntMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000 word32 dw10000) (10004 (ptr (ptr word32)) ptr10004))
	globals_t (in globals : (ptr (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in r1 : word32)
  Class: Eq_2
  DataType: (ptr (ptr word32))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_3: (in 0x00000000 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in r1 + 0x00000000 : word32)
  Class: Eq_4
  DataType: (ptr (ptr word32))
  OrigDataType: (ptr T_5)
T_5: (in Mem0[r1 + 0x00000000:word32] : word32)
  Class: Eq_5
  DataType: (ptr word32)
  OrigDataType: word32
T_6: (in r2 : word32)
  Class: Eq_5
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_9 t0000)))
T_7: (in 0x00000000 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in r2 + 0x00000000 : word32)
  Class: Eq_8
  DataType: (ptr word32)
  OrigDataType: (ptr T_9)
T_9: (in Mem0[r2 + 0x00000000:word32] : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_10: (in r3 : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_11: (in 0x00010000 : word32)
  Class: Eq_11
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_12 t0000)))
T_12: (in Mem0[0x00010000:word32] : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_13: (in 0x00010004 : word32)
  Class: Eq_13
  DataType: (ptr (ptr (ptr word32)))
  OrigDataType: (ptr (struct (0 T_14 t0000)))
T_14: (in Mem0[0x00010004:word32] : word32)
  Class: Eq_2
  DataType: (ptr (ptr word32))
  OrigDataType: word32
