// Before ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_36 = 0xFFF<16>
	// succ:  l0C00_000C
l0C00_000C:
	byte bl_10 = SLICE(bx_39, byte, 0)
	Mem23[0x4DE1<16>:bx_39:byte] = bl_10 & 0xF0<8> | SLICE((bl_10 & 0xF<8>) *u16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8>
	bx_36 = SEQ(SLICE(bx_39 - 1<16>, byte, 8), bl_10 - 1<8>) (alias)
	bx_39 = bx_36
	branch bx_39 >= 1<16> l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// After ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	Eq_6 bx_36 = 0xFFF<16>
	// succ:  l0C00_000C
l0C00_000C:
	byte bl_10 = (byte) bx_39
	0x4DE1<16>->*bx_39 = bl_10 & 0xF0<8> | SLICE((bl_10 & 0xF<8>) *16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8>
	bx_36 = SEQ(SLICE(bx_39 - 1<16>, byte, 8), bl_10 - 1<8>)
	bx_39 = bx_36
	branch bx_39 >= 1<16> l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (4DE10 (ptr16 Eq_25) ptr4DE10))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "seg0C00_t" 002A)
	T_2 (in seg0C00 : selector)
Eq_3: (fn void ())
	T_3 (in fn0C00_0004 : segptr32)
	T_4 (in signature of fn0C00_0004 : void)
Eq_6: (union "Eq_6" (int16 u0) ((memptr (ptr16 Eq_25) byte) u1))
	T_6 (in bx_36 : Eq_6)
	T_7 (in 0xFFF<16> : cui16)
	T_9 (in bx_39 : word16)
	T_30 (in 1<16> : word16)
	T_35 (in SEQ(SLICE(bx_39 - 1<16>, byte, 8), bl_10 - 1<8>) : word16)
Eq_25: (segment "Eq_25")
	T_25 (in 0x4DE1<16> : selector)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in seg0C00 : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment "seg0C00_t" 002A))
T_3: (in fn0C00_0004 : segptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_5 ()))
T_4: (in signature of fn0C00_0004 : void)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: 
T_5: (in fn0C00_0004() : void)
  Class: Eq_5
  DataType: void
  OrigDataType: void
T_6: (in bx_36 : Eq_6)
  Class: Eq_6
  DataType: Eq_6
  OrigDataType: cui16
T_7: (in 0xFFF<16> : cui16)
  Class: Eq_6
  DataType: int16
  OrigDataType: cui16
T_8: (in bl_10 : byte)
  Class: Eq_8
  DataType: byte
  OrigDataType: byte
T_9: (in bx_39 : word16)
  Class: Eq_6
  DataType: Eq_6
  OrigDataType: (union (int16 u1) ((memptr (ptr16 Eq_25) byte) u0))
T_10: (in SLICE(bx_39, byte, 0) : byte)
  Class: Eq_8
  DataType: byte
  OrigDataType: byte
T_11: (in 0xF0<8> : byte)
  Class: Eq_11
  DataType: byte
  OrigDataType: byte
T_12: (in bl_10 & 0xF0<8> : byte)
  Class: Eq_12
  DataType: byte
  OrigDataType: byte
T_13: (in 0xF<8> : byte)
  Class: Eq_13
  DataType: byte
  OrigDataType: byte
T_14: (in bl_10 & 0xF<8> : byte)
  Class: Eq_14
  DataType: bu8
  OrigDataType: bu8
T_15: (in SLICE(bx_39, byte, 8) : byte)
  Class: Eq_15
  DataType: bu8
  OrigDataType: bu8
T_16: (in 1<8> : byte)
  Class: Eq_16
  DataType: bu8
  OrigDataType: bu8
T_17: (in SLICE(bx_39, byte, 8) + 1<8> : byte)
  Class: Eq_17
  DataType: bu8
  OrigDataType: bu8
T_18: (in (bl_10 & 0xF<8>) *16 (SLICE(bx_39, byte, 8) + 1<8>) : uint16)
  Class: Eq_18
  DataType: uint16
  OrigDataType: uint16
T_19: (in 4<16> : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in (bl_10 & 0xF<8>) *16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16> : word16)
  Class: Eq_20
  DataType: ui16
  OrigDataType: ui16
T_21: (in SLICE((bl_10 & 0xF<8>) *u16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_22: (in 0xF<8> : byte)
  Class: Eq_22
  DataType: byte
  OrigDataType: byte
T_23: (in SLICE((bl_10 & 0xF<8>) *16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8> : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_24: (in bl_10 & 0xF0<8> | SLICE((bl_10 & 0xF<8>) *16 (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8> : byte)
  Class: Eq_24
  DataType: byte
  OrigDataType: byte
T_25: (in 0x4DE1<16> : selector)
  Class: Eq_25
  DataType: (ptr16 Eq_25)
  OrigDataType: (ptr16 (segment))
T_26: (in 0<16> : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
T_27: (in bx_39 + 0<16> : word16)
  Class: Eq_27
  DataType: word16
  OrigDataType: word16
T_28: (in 0x4DE1<16>:bx_39 + 0<16> : segptr32)
  Class: Eq_28
  DataType: segptr32
  OrigDataType: segptr32
T_29: (in Mem23[0x4DE1<16>:bx_39 + 0<16>:byte] : byte)
  Class: Eq_24
  DataType: Eq_6
  OrigDataType: byte
T_30: (in 1<16> : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_31: (in bx_39 - 1<16> : word16)
  Class: Eq_31
  DataType: (memptr (ptr16 Eq_25) byte)
  OrigDataType: (memptr T_25 (struct (0 T_29 t0000)))
T_32: (in SLICE(bx_39 - 1<16>, byte, 8) : byte)
  Class: Eq_32
  DataType: byte
  OrigDataType: byte
T_33: (in 1<8> : byte)
  Class: Eq_33
  DataType: byte
  OrigDataType: byte
T_34: (in bl_10 - 1<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_35: (in SEQ(SLICE(bx_39 - 1<16>, byte, 8), bl_10 - 1<8>) : word16)
  Class: Eq_6
  DataType: Eq_6
  OrigDataType: word16
T_36: (in bx_39 >= 1<16> : bool)
  Class: Eq_36
  DataType: bool
  OrigDataType: bool
