// Before ///////
// fn0C00_0000
void fn0C00_0000(word16 cx, word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0007(cx, ds)
	fn0C00_001D(bx, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0007
void fn0C00_0007(word16 cx, selector ds)
fn0C00_0007_entry:
	// succ:  l0C00_0007
l0C00_0007:
	word16 di_12 = 0x5388
	// succ:  l0C00_000A
l0C00_000A:
	fn0C00_003D(Mem0[ds:di_12 + 0x0000:word16], 0x2D, ds)
	di_12 = di_12 + 0x0002
	cx = cx - 0x0001
	branch cx != 0x0000 l0C00_000A
	// succ:  l0C00_001C l0C00_000A
l0C00_001C:
	return
	// succ:  fn0C00_0007_exit
fn0C00_0007_exit:

// fn0C00_001D
void fn0C00_001D(word16 bx, selector ds)
fn0C00_001D_entry:
	// succ:  l0C00_001D
l0C00_001D:
	branch bx == Mem0[ds:0x53BA:word16] l0C00_003C
	// succ:  l0C00_0023 l0C00_003C
l0C00_0023:
	branch bx >= Mem0[ds:0x53B8:word16] l0C00_003C
	// succ:  l0C00_0029 l0C00_003C
l0C00_0029:
	Mem19[ds:0x53BA:word16] = bx
	fn0C00_0046(0x4400, Mem19[ds:bx * 0x0002 + 0x5388:word16], 0x0000, ds)
	// succ:  l0C00_003C
l0C00_003C:
	return
	// succ:  fn0C00_001D_exit
fn0C00_001D_exit:

// fn0C00_003D
void fn0C00_003D(word16 dx, byte ah, selector ds)
fn0C00_003D_entry:
	// succ:  l0C00_003D
l0C00_003D:
	Mem6[ds:0x0110:byte] = ah
	Mem7[ds:0x0112:word16] = dx
	return
	// succ:  fn0C00_003D_exit
fn0C00_003D_exit:

// fn0C00_0046
void fn0C00_0046(word16 ax, word16 dx, word16 bx, selector ds)
fn0C00_0046_entry:
	// succ:  l0C00_0046
l0C00_0046:
	Mem7[ds:0x0114:word16] = ax
	Mem8[ds:0x0116:word16] = bx
	Mem9[ds:0x0118:word16] = dx
	return
	// succ:  fn0C00_0046_exit
fn0C00_0046_exit:

// After ///////
// fn0C00_0000
void fn0C00_0000(word16 cx, int16 bx, Eq_5 * ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0007(cx, ds)
	fn0C00_001D(bx, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0007
void fn0C00_0007(word16 cx, Eq_5 * ds)
fn0C00_0007_entry:
	// succ:  l0C00_0007
l0C00_0007:
	word16 Eq_5::*di_12 = Eq_5::a5388
	// succ:  l0C00_000A
l0C00_000A:
	fn0C00_003D(ds->*di_12, 0x2D, ds)
	di_12 = di_12 + 1;
	cx = cx - 0x0001;
	branch cx != 0x0000 l0C00_000A
	// succ:  l0C00_001C l0C00_000A
l0C00_001C:
	return
	// succ:  fn0C00_0007_exit
fn0C00_0007_exit:

// fn0C00_001D
void fn0C00_001D(int16 bx, Eq_5 * ds)
fn0C00_001D_entry:
	// succ:  l0C00_001D
l0C00_001D:
	branch bx == ds->w53BA l0C00_003C
	// succ:  l0C00_0023 l0C00_003C
l0C00_0023:
	branch bx >= ds->w53B8 l0C00_003C
	// succ:  l0C00_0029 l0C00_003C
l0C00_0029:
	ds->w53BA = bx;
	fn0C00_0046(0x4400, ds->a5388[bx], 0x0000, ds)
	// succ:  l0C00_003C
l0C00_003C:
	return
	// succ:  fn0C00_001D_exit
fn0C00_001D_exit:

// fn0C00_003D
void fn0C00_003D(word16 dx, byte ah, Eq_5 * ds)
fn0C00_003D_entry:
	// succ:  l0C00_003D
l0C00_003D:
	ds->b0110 = ah;
	ds->w0112 = dx;
	return
	// succ:  fn0C00_003D_exit
fn0C00_003D_exit:

// fn0C00_0046
void fn0C00_0046(word16 ax, word16 dx, word16 bx, Eq_5 * ds)
fn0C00_0046_entry:
	// succ:  l0C00_0046
l0C00_0046:
	ds->w0114 = ax;
	ds->w0116 = bx;
	ds->w0118 = dx;
	return
	// succ:  fn0C00_0046_exit
fn0C00_0046_exit:

// Equivalence classes ////////////
Eq_1: (struct "Eq_1")
	globals_t (in globals : (struct))
Eq_2: (fn void (word16, (ptr32 Eq_5)))
	T_2 (in fn0C00_0007 : ptr32)
	T_3 (in signature of fn0C00_0007 : void)
Eq_5: (segment "Eq_5" (110 byte b0110) (112 word16 w0112) (114 word16 w0114) (116 word16 w0116) (118 word16 w0118) (5388 (arr word16) a5388) (53B8 int16 w53B8) (53BA int16 w53BA))
	T_5 (in ds : (ptr32 Eq_5))
	T_7 (in ds : (ptr32 Eq_5))
	T_12 (in ds : (ptr32 Eq_5))
	T_21 (in ds : (ptr32 Eq_5))
	T_46 (in ds : (ptr32 Eq_5))
Eq_9: (fn void (int16, (ptr32 Eq_5)))
	T_9 (in fn0C00_001D : ptr32)
	T_10 (in signature of fn0C00_001D : void)
Eq_17: (fn void (word16, byte, (ptr32 Eq_5)))
	T_17 (in fn0C00_003D : ptr32)
	T_18 (in signature of fn0C00_003D : void)
Eq_41: (fn void (word16, word16, word16, (ptr32 Eq_5)))
	T_41 (in fn0C00_0046 : ptr32)
	T_42 (in signature of fn0C00_0046 : void)
// Type Variables ////////////
globals_t: (in globals : (struct))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct))
T_2: (in fn0C00_0007 : ptr32)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (fn T_8 (T_6, T_7)))
T_3: (in signature of fn0C00_0007 : void)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: 
T_4: (in cx : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in ds : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (segment (5388 (arr T_65) a5388)))
T_6: (in cx : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_7: (in ds : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (segment))
T_8: (in fn0C00_0007(cx, ds) : void)
  Class: Eq_8
  DataType: void
  OrigDataType: void
T_9: (in fn0C00_001D : ptr32)
  Class: Eq_9
  DataType: (ptr32 Eq_9)
  OrigDataType: (ptr32 (fn T_14 (T_13, T_7)))
T_10: (in signature of fn0C00_001D : void)
  Class: Eq_9
  DataType: (ptr32 Eq_9)
  OrigDataType: 
T_11: (in bx : int16)
  Class: Eq_11
  DataType: int16
  OrigDataType: int16
T_12: (in ds : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (segment (53B8 T_37 t53B8) (53BA T_11 t53BA)))
T_13: (in bx : int16)
  Class: Eq_11
  DataType: int16
  OrigDataType: word16
T_14: (in fn0C00_001D(bx, ds) : void)
  Class: Eq_14
  DataType: void
  OrigDataType: void
T_15: (in di_12 : (memptr (ptr32 Eq_5) word16))
  Class: Eq_15
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_5 (struct 0002 (0 (union (word16 u0) (T_24 u1)) u0000)))
T_16: (in 0x5388 : word16)
  Class: Eq_15
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: word16
T_17: (in fn0C00_003D : ptr32)
  Class: Eq_17
  DataType: (ptr32 Eq_17)
  OrigDataType: (ptr32 (fn T_26 (T_24, T_25, T_5)))
T_18: (in signature of fn0C00_003D : void)
  Class: Eq_17
  DataType: (ptr32 Eq_17)
  OrigDataType: 
T_19: (in dx : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in ah : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_21: (in ds : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (segment (110 T_56 t0110) (112 T_58 t0112)))
T_22: (in 0x0000 : word16)
  Class: Eq_22
  DataType: word16
  OrigDataType: word16
T_23: (in di_12 + 0x0000 : word16)
  Class: Eq_23
  DataType: word16
  OrigDataType: word16
T_24: (in Mem0[ds:di_12 + 0x0000:word16] : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_25: (in 0x2D : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_26: (in fn0C00_003D(ds->*di_12, 0x2D, ds) : void)
  Class: Eq_26
  DataType: void
  OrigDataType: void
T_27: (in 0x0002 : word16)
  Class: Eq_27
  DataType: word16
  OrigDataType: word16
T_28: (in di_12 + 0x0002 : word16)
  Class: Eq_15
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: word16
T_29: (in 0x0001 : word16)
  Class: Eq_29
  DataType: word16
  OrigDataType: word16
T_30: (in cx - 0x0001 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_31: (in 0x0000 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_32: (in cx != 0x0000 : bool)
  Class: Eq_32
  DataType: bool
  OrigDataType: bool
T_33: (in 0x53BA : word16)
  Class: Eq_33
  DataType: (memptr (ptr32 Eq_5) int16)
  OrigDataType: (memptr T_12 (struct (0 T_34 t0000)))
T_34: (in Mem0[ds:0x53BA:word16] : word16)
  Class: Eq_11
  DataType: int16
  OrigDataType: word16
T_35: (in bx == ds->w53BA : bool)
  Class: Eq_35
  DataType: bool
  OrigDataType: bool
T_36: (in 0x53B8 : word16)
  Class: Eq_36
  DataType: (memptr (ptr32 Eq_5) int16)
  OrigDataType: (memptr T_12 (struct (0 T_37 t0000)))
T_37: (in Mem0[ds:0x53B8:word16] : word16)
  Class: Eq_11
  DataType: int16
  OrigDataType: ci16
T_38: (in bx >= ds->w53B8 : bool)
  Class: Eq_38
  DataType: bool
  OrigDataType: bool
T_39: (in 0x53BA : word16)
  Class: Eq_39
  DataType: (memptr (ptr32 Eq_5) int16)
  OrigDataType: (memptr T_12 (struct (0 T_40 t0000)))
T_40: (in Mem19[ds:0x53BA:word16] : word16)
  Class: Eq_11
  DataType: int16
  OrigDataType: word16
T_41: (in fn0C00_0046 : ptr32)
  Class: Eq_41
  DataType: (ptr32 Eq_41)
  OrigDataType: (ptr32 (fn T_54 (T_47, T_52, T_53, T_12)))
T_42: (in signature of fn0C00_0046 : void)
  Class: Eq_41
  DataType: (ptr32 Eq_41)
  OrigDataType: 
T_43: (in ax : word16)
  Class: Eq_43
  DataType: word16
  OrigDataType: word16
T_44: (in dx : word16)
  Class: Eq_44
  DataType: word16
  OrigDataType: word16
T_45: (in bx : word16)
  Class: Eq_45
  DataType: word16
  OrigDataType: word16
T_46: (in ds : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (segment (114 T_60 t0114) (116 T_62 t0116) (118 T_64 t0118)))
T_47: (in 0x4400 : word16)
  Class: Eq_43
  DataType: word16
  OrigDataType: word16
T_48: (in 0x5388 : word16)
  Class: Eq_48
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_12 (struct (0 (arr T_66) a0000)))
T_49: (in SEQ(ds, 0x5388) : ptr32)
  Class: Eq_49
  DataType: (ptr32 (arr word16))
  OrigDataType: (ptr32 (struct (0 (arr T_66) a0000)))
T_50: (in 0x0002 : word16)
  Class: Eq_50
  DataType: ui16
  OrigDataType: ui16
T_51: (in bx * 0x0002 : word16)
  Class: Eq_51
  DataType: ui16
  OrigDataType: ui16
T_52: (in SEQ(ds, 0x5388)[bx * 0x0002] : word16)
  Class: Eq_44
  DataType: word16
  OrigDataType: word16
T_53: (in 0x0000 : word16)
  Class: Eq_45
  DataType: word16
  OrigDataType: word16
T_54: (in fn0C00_0046(0x4400, ds->a5388[bx], 0x0000, ds) : void)
  Class: Eq_54
  DataType: void
  OrigDataType: void
T_55: (in 0x0110 : word16)
  Class: Eq_55
  DataType: (memptr (ptr32 Eq_5) byte)
  OrigDataType: (memptr T_21 (struct (0 T_56 t0000)))
T_56: (in Mem6[ds:0x0110:byte] : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_57: (in 0x0112 : word16)
  Class: Eq_57
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_21 (struct (0 T_58 t0000)))
T_58: (in Mem7[ds:0x0112:word16] : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_59: (in 0x0114 : word16)
  Class: Eq_59
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_46 (struct (0 T_60 t0000)))
T_60: (in Mem7[ds:0x0114:word16] : word16)
  Class: Eq_43
  DataType: word16
  OrigDataType: word16
T_61: (in 0x0116 : word16)
  Class: Eq_61
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_46 (struct (0 T_62 t0000)))
T_62: (in Mem8[ds:0x0116:word16] : word16)
  Class: Eq_45
  DataType: word16
  OrigDataType: word16
T_63: (in 0x0118 : word16)
  Class: Eq_63
  DataType: (memptr (ptr32 Eq_5) word16)
  OrigDataType: (memptr T_46 (struct (0 T_64 t0000)))
T_64: (in Mem9[ds:0x0118:word16] : word16)
  Class: Eq_44
  DataType: word16
  OrigDataType: word16
T_65:
  Class: Eq_65
  DataType: word16
  OrigDataType: (struct 0002 (0 T_24 t0000))
T_66:
  Class: Eq_66
  DataType: word16
  OrigDataType: (struct 0002 (0 T_52 t0000))
