// Before ///////
// fn0000131C
void fn0000131C()
fn0000131C_entry:
	// succ:  l0000131C
l0000131C:
	branch Mem0[0x000013F8:word32] != 0x00000000 l00001346
	// succ:  l00001328 l00001346
l00001328:
	word32 a3_31 = Mem0[0x0000140C:word32]
	Mem34[0x000013F8:word32] = 1
	branch a3_31 == 0x00000000 l00001346
	// succ:  l0000133A l00001346
l0000133A:
	word32 a2_39 = Mem34[a3_31 + 4:word32]
	call Mem34[a2_39:word32] (retsize: 4; depth: 12)
	a3_31 = Mem34[a3_31:word32]
	branch a3_31 != 0x00000000 l0000133A
	// succ:  l00001346 l0000133A
l00001346:
	return
	// succ:  fn0000131C_exit
fn0000131C_exit:

// After ///////
// fn0000131C
void fn0000131C()
fn0000131C_entry:
	// succ:  l0000131C
l0000131C:
	branch globals->dw13F8 != 0x00000000 l00001346
	// succ:  l00001328 l00001346
l00001328:
	Eq_6 * a3_31 = globals->ptr140C
	globals->dw13F8 = 1;
	branch a3_31 == null l00001346
	// succ:  l0000133A l00001346
l0000133A:
	code * * a2_39 = a3_31->ptr0004
	(**a2_39)()
	a3_31 = a3_31->ptr0000;
	branch a3_31 != null l0000133A
	// succ:  l00001346 l0000133A
l00001346:
	return
	// succ:  fn0000131C_exit
fn0000131C_exit:

// Equivalence classes ////////////
Eq_1: (struct "Eq_1" (13F8 word32 dw13F8) (140C (ptr32 Eq_6) ptr140C))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_6: (struct "Eq_6" (0 (ptr32 Eq_6) ptr0000) (4 (ptr32 (ptr32 code)) ptr0004))
	T_6 (in a3_31 : (ptr32 Eq_6))
	T_8 (in Mem0[0x0000140C:word32] : word32)
	T_12 (in 0x00000000 : word32)
	T_23 (in Mem34[a3_31 + 0x00000000:word32] : word32)
	T_24 (in 0x00000000 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct))
T_2: (in 000013F8 : ptr32)
  Class: Eq_2
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_3 t0000)))
T_3: (in Mem0[0x000013F8:word32] : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in 0x00000000 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_5: (in globals->dw13F8 != 0x00000000 : bool)
  Class: Eq_5
  DataType: bool
  OrigDataType: bool
T_6: (in a3_31 : (ptr32 Eq_6))
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: (ptr32 (struct (0 T_23 t0000) (4 T_17 t0004)))
T_7: (in 0000140C : ptr32)
  Class: Eq_7
  DataType: (ptr32 (ptr32 Eq_6))
  OrigDataType: (ptr32 (struct (0 T_8 t0000)))
T_8: (in Mem0[0x0000140C:word32] : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: word32
T_9: (in 1 : int32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_10: (in 000013F8 : ptr32)
  Class: Eq_10
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_11 t0000)))
T_11: (in Mem34[0x000013F8:word32] : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: word32
T_12: (in 0x00000000 : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: word32
T_13: (in a3_31 == null : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in a2_39 : (ptr32 (ptr32 code)))
  Class: Eq_14
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_20 t0000)))
T_15: (in 4 : int32)
  Class: Eq_15
  DataType: int32
  OrigDataType: int32
T_16: (in a3_31 + 4 : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in Mem34[a3_31 + 4:word32] : word32)
  Class: Eq_14
  DataType: (ptr32 (ptr32 code))
  OrigDataType: word32
T_18: (in 0x00000000 : word32)
  Class: Eq_18
  DataType: word32
  OrigDataType: word32
T_19: (in a2_39 + 0x00000000 : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in Mem34[a2_39 + 0x00000000:word32] : word32)
  Class: Eq_20
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_21: (in 0x00000000 : word32)
  Class: Eq_21
  DataType: word32
  OrigDataType: word32
T_22: (in a3_31 + 0x00000000 : word32)
  Class: Eq_22
  DataType: word32
  OrigDataType: word32
T_23: (in Mem34[a3_31 + 0x00000000:word32] : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: word32
T_24: (in 0x00000000 : word32)
  Class: Eq_6
  DataType: (ptr32 Eq_6)
  OrigDataType: word32
T_25: (in a3_31 != null : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
