// Before ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem5[ds:0x9A2E<16>:word16] = 0<16>
	Mem7[ds:0x9A26<16>:word16] = 0x100<16>
	si_13 = 0<16>
	// succ:  l0C00_0015
l0C00_0015:
	Mem16[0x5CE1<16>:si_13:word16] = 0xFFFF<16>
	v10_20 = Mem16[ds:0x9A26<16>:word16] - 1<16>
	Mem21[ds:0x9A26<16>:word16] = v10_20
	si_13 = si_13 + 0x26<16>
	branch v10_20 != 0<16> l0C00_0015
	// succ:  l0C00_0023 l0C00_0015
l0C00_0023:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// After ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000(struct Eq_3 * ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ds->w9A2E = 0<16>
	ds->w9A26 = 0x100<16>
	si_13 = (struct Eq_12 Eq_15::*) Eq_15::a0000
	// succ:  l0C00_0015
l0C00_0015:
	(0x5CE1<16>->*si_13).w0000 = 0xFFFF<16>
	v10_20 = ds->w9A26 - 1<16>
	ds->w9A26 = v10_20
	si_13 = si_13 + 1<i32>
	branch v10_20 != 0<16> l0C00_0015
	// succ:  l0C00_0023 l0C00_0015
l0C00_0023:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (5CE10 (ptr16 Eq_15) ptr5CE10))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "seg0C00_t" 0024)
	T_2 (in seg0C00 : selector)
Eq_3: (segment "Eq_3" (9A26 word16 w9A26) (9A2E word16 w9A2E))
	T_3 (in ds : (ptr16 Eq_3))
Eq_12: (struct "Eq_12" 0026 (0 word16 w0000))
	T_12 (in 0<16> : word16)
	T_13 (in si_13 : (memptr (ptr16 Eq_15) Eq_12))
	T_29 (in si_13 + 0x26<16> : word16)
Eq_15: (segment "Eq_15" (0 (arr Eq_32) a0000))
	T_15 (in 0x5CE1<16> : selector)
Eq_32: (struct "Eq_32" 0026 (0 word16 w0000))
	T_32
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in seg0C00 : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment "seg0C00_t" 0024))
T_3: (in ds : (ptr16 Eq_3))
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (9A26 T_8 t9A26) (9A2E T_7 t9A2E)))
T_4: (in 0<16> : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in 0x9A2E<16> : word16)
  Class: Eq_5
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_7 t0000)))
T_6: (in ds:0x9A2E<16> : segptr32)
  Class: Eq_6
  DataType: segptr32
  OrigDataType: segptr32
T_7: (in Mem5[ds:0x9A2E<16>:word16] : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_8: (in 0x100<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in 0x9A26<16> : word16)
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_11 t0000)))
T_10: (in ds:0x9A26<16> : segptr32)
  Class: Eq_10
  DataType: segptr32
  OrigDataType: segptr32
T_11: (in Mem7[ds:0x9A26<16>:word16] : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_12: (in 0<16> : word16)
  Class: Eq_12
  DataType: (memptr (ptr16 Eq_15) Eq_12)
  OrigDataType: word16
T_13: (in si_13 : (memptr (ptr16 Eq_15) Eq_12))
  Class: Eq_12
  DataType: (memptr (ptr16 Eq_15) Eq_12)
  OrigDataType: (memptr T_15 (struct 0026 (0 word16 w0000)))
T_14: (in 0xFFFF<16> : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in 0x5CE1<16> : selector)
  Class: Eq_15
  DataType: (ptr16 Eq_15)
  OrigDataType: (ptr16 (segment (0 T_33 t0000)))
T_16: (in 0<16> : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in si_13 + 0<16> : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in 0x5CE1<16>:si_13 + 0<16> : segptr32)
  Class: Eq_18
  DataType: segptr32
  OrigDataType: segptr32
T_19: (in Mem16[0x5CE1<16>:si_13 + 0<16>:word16] : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_20: (in 0x9A26<16> : word16)
  Class: Eq_20
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_21: (in ds:0x9A26<16> : segptr32)
  Class: Eq_21
  DataType: segptr32
  OrigDataType: segptr32
T_22: (in Mem16[ds:0x9A26<16>:word16] : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_23: (in 1<16> : word16)
  Class: Eq_23
  DataType: word16
  OrigDataType: word16
T_24: (in ds->w9A26 - 1<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_25: (in v10_20 : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_26: (in ds:0x9A26<16> : segptr32)
  Class: Eq_26
  DataType: segptr32
  OrigDataType: segptr32
T_27: (in Mem21[ds:0x9A26<16>:word16] : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_28: (in 0x26<16> : word16)
  Class: Eq_28
  DataType: int16
  OrigDataType: int16
T_29: (in si_13 + 0x26<16> : word16)
  Class: Eq_12
  DataType: (memptr (ptr16 Eq_15) Eq_12)
  OrigDataType: (memptr T_15 (struct 0026 (0 word16 w0000)))
T_30: (in 0<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_31: (in v10_20 != 0<16> : bool)
  Class: Eq_31
  DataType: bool
  OrigDataType: bool
T_32:
  Class: Eq_32
  DataType: Eq_32
  OrigDataType: (struct 0026 (0 T_19 t0000))
T_33:
  Class: Eq_33
  DataType: (arr Eq_32)
  OrigDataType: (arr T_32)
