// Before ///////
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_16 = 0x0FFF
	byte bh_17 = 0x0F
	byte bl_18 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	Mem34[0x4DE1:bx_16:byte] = bl_18 & 0xF0 | SLICE((bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_16 = bx_16 - 0x0001
	bh_17 = SLICE(bx_16, byte, 8) (alias)
	bl_18 = (byte) bx_16 (alias)
	branch bx_16 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// After ///////
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	int16 bx_16 = 0x0FFF
	byte bh_17 = 0x0F
	byte bl_18 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	0x4DE1->a0000[bx_16] = bl_18 & 0xF0 | SLICE((bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004, byte, 8) & 0x0F;
	bx_16 = bx_16 - 0x0001;
	bh_17 = SLICE(bx_16, byte, 8);
	bl_18 = (byte) bx_16;
	branch bx_16 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// Equivalence classes ////////////
Eq_1: (struct "Eq_1" (4DE10 (ptr32 Eq_24) ptr4DE10))
	globals_t (in globals : (ptr32 (struct)))
Eq_2: (fn void ())
	T_2 (in fn0C00_0004 : ptr32)
	T_3 (in signature of fn0C00_0004 : void)
Eq_24: (segment "Eq_24" (0 (arr byte 4096) a0000))
	T_24 (in 0x4DE1 : selector)
// Type Variables ////////////
globals_t: (in globals : (struct))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct (4DE10 T_24 t4DE10)))
T_2: (in fn0C00_0004 : ptr32)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (fn T_4 ()))
T_3: (in signature of fn0C00_0004 : void)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: 
T_4: (in fn0C00_0004() : void)
  Class: Eq_4
  DataType: void
  OrigDataType: void
T_5: (in bx_16 : Eq_5)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_6: (in 0x0FFF : word16)
  Class: Eq_5
  DataType: ci16
  OrigDataType: word16
T_7: (in bh_17 : bu8)
  Class: Eq_7
  DataType: bu8
  OrigDataType: bu8
T_8: (in 0x0F : byte)
  Class: Eq_7
  DataType: bu8
  OrigDataType: byte
T_9: (in bl_18 : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_10: (in 0xFF : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_11: (in 0xF0 : byte)
  Class: Eq_11
  DataType: byte
  OrigDataType: byte
T_12: (in bl_18 & 0xF0 : byte)
  Class: Eq_12
  DataType: byte
  OrigDataType: byte
T_13: (in 0x0F : byte)
  Class: Eq_13
  DataType: byte
  OrigDataType: byte
T_14: (in bl_18 & 0x0F : byte)
  Class: Eq_14
  DataType: bu8
  OrigDataType: bu8
T_15: (in 0x01 : byte)
  Class: Eq_15
  DataType: bu8
  OrigDataType: bu8
T_16: (in bh_17 + 0x01 : byte)
  Class: Eq_16
  DataType: bu8
  OrigDataType: bu8
T_17: (in (bl_18 & 0x0F) *u (bh_17 + 0x01) : uint16)
  Class: Eq_17
  DataType: uint16
  OrigDataType: uint16
T_18: (in 0x0004 : word16)
  Class: Eq_18
  DataType: word16
  OrigDataType: word16
T_19: (in (bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004 : word16)
  Class: Eq_19
  DataType: ui16
  OrigDataType: ui16
T_20: (in SLICE((bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004, byte, 8) : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_21: (in 0x0F : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_22: (in SLICE((bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
  Class: Eq_22
  DataType: byte
  OrigDataType: byte
T_23: (in bl_18 & 0xF0 | SLICE((bl_18 & 0x0F) *u (bh_17 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_24: (in 0x4DE1 : selector)
  Class: Eq_24
  DataType: (ptr32 Eq_24)
  OrigDataType: (ptr32 (segment (0 (arr T_34 4096) a0000)))
T_25: (in 0x0000 : word16)
  Class: Eq_25
  DataType: word16
  OrigDataType: word16
T_26: (in bx_16 + 0x0000 : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
T_27: (in Mem34[0x4DE1:bx_16 + 0x0000:byte] : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_28: (in 0x0001 : word16)
  Class: Eq_28
  DataType: (memptr (ptr32 Eq_24) byte)
  OrigDataType: (memptr T_24 (struct (0 T_27 t0000)))
T_29: (in bx_16 - &Eq_24::b0001 : word16)
  Class: Eq_5
  DataType: Eq_5
  OrigDataType: word16
T_30: (in SLICE(bx_16, byte, 8) : byte)
  Class: Eq_7
  DataType: bu8
  OrigDataType: byte
T_31: (in (byte) bx_16 : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_32: (in 0x0000 : word16)
  Class: Eq_5
  DataType: ci16
  OrigDataType: ci16
T_33: (in bx_16 >= 0x0000 : bool)
  Class: Eq_33
  DataType: bool
  OrigDataType: bool
T_34:
  Class: Eq_34
  DataType: byte
  OrigDataType: (struct 0001 (0 T_27 t0000))
