// fn0C00_0000
void fn0C00_0000(segment ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	ds->w9A2E = 0x0000;
	ds->w9A26 = 0x0100;
	(memptr (ptr Eq_12) Eq_9) si_16 = &Eq_12::a0000[0]
	// succ:  2
l0C00_0015:		// block 2, pred: 1 2
	(0x5CE1->*si_16).w0000 = 0xFFFF;
	word16 v8_22 = ds->w9A26 - 0x0001
	ds->w9A26 = v8_22;
	si_16 = si_16 + 1;
	branch v8_22 != 0x0000
	// succ:  3 2
l0C00_0023:		// block 3, pred: 2
	return
	// succ:  4
fn0C00_0000_exit:		// block 4, pred: 3
	// succ: 

// Equivalence classes ////////////
Eq_3: (segment "Eq_3" (9A26 word16 w9A26) (9A2E word16 w9A2E))
	T_3 (in ds : segment)
Eq_9: (struct "Eq_9" 26 (0 word16 w0000))
	T_9 (in si_16 : (memptr (ptr Eq_12) Eq_9))
	T_10 (in 0x0000 : word16)
	T_21 (in si_16 + 0x0026 : word16)
Eq_12: (segment "Eq_12" (0 (arr Eq_25) a0000))
	T_12 (in 0x5CE1 : segment)
Eq_25: (struct "Eq_25" 26 (0 word16 w0000))
	T_25
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2:(in 0x0000)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3:(in ds)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (segment (9A26 (union (T_6 u0) (T_8 u1)) u9A26) (9A2E T_5 t9A2E)))
T_4:(in 0x9A2E)
  Class: Eq_4
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5:(in Mem11[ds:0x9A2E:word16])
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_6:(in 0x0100)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7:(in 0x9A26)
  Class: Eq_7
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_8:(in Mem13[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9:(in si_16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: (memptr T_12 (struct 26 (0 T_13 t0000)))
T_10:(in 0x0000)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: word16
T_11:(in 0xFFFF)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12:(in 0x5CE1)
  Class: Eq_12
  DataType: (ptr Eq_12)
  OrigDataType: (ptr (segment (0 (arr (struct "Eq_25" 26 (0 word16 w0000))) a0000)))
T_13:(in Mem19[0x5CE1:si_16:word16])
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_14:(in v8_22)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_15:(in 0x9A26)
  Class: Eq_15
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_6 t0000)))
T_16:(in Mem19[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_17:(in 0x0001)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18:(in ds->w9A26 - 0x0001)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_19:(in Mem23[ds:0x9A26:word16])
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_20:(in 0x0026)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21:(in si_16 + 0x0026)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: word16
T_22:(in 0x0000)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_23:(in v8_22 != 0x0000)
  Class: Eq_23
  DataType: bool
  OrigDataType: bool
T_24:
  Class: Eq_24
  DataType: word16
  OrigDataType: 
T_25:
  Class: Eq_25
  DataType: Eq_25
  OrigDataType: 
