// Before ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem5[ds:0x9A2E<16>:word16] = 0<16>
	Mem7[ds:0x9A26<16>:word16] = 0x100<16>
	word16 si_13 = 0<16>
	// succ:  l0C00_0015
l0C00_0015:
	Mem16[0x5CE1<16>:si_13:word16] = 0xFFFF<16>
	word16 v9_20 = Mem16[ds:0x9A26<16>:word16] - 1<16>
	Mem21[ds:0x9A26<16>:word16] = v9_20
	si_13 = si_13 + 0x26<16>
	branch v9_20 != 0<16> l0C00_0015
	// succ:  l0C00_0023 l0C00_0015
l0C00_0023:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// After ///////
// fn0C00_0000
// Return size: 0
void fn0C00_0000(struct Eq_2 * ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ds->w9A2E = 0<16>
	ds->w9A26 = 0x100<16>
	struct Eq_9 Eq_12::* si_13 = Eq_12::a0000
	// succ:  l0C00_0015
l0C00_0015:
	(0x5CE1<16>->*si_13).w0000 = 0xFFFF<16>
	word16 v9_20 = ds->w9A26 - 1<16>
	ds->w9A26 = v9_20
	si_13 = si_13 + 1<i32>
	branch v9_20 != 0<16> l0C00_0015
	// succ:  l0C00_0023 l0C00_0015
l0C00_0023:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (5CE10 (ptr16 Eq_12) ptr5CE10))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "Eq_2" (9A26 word16 w9A26) (9A2E word16 w9A2E))
	T_2 (in ds : (ptr16 Eq_2))
Eq_9: (struct "Eq_9" 0026 (0 word16 w0000))
	T_9 (in si_13 : (memptr (ptr16 Eq_12) Eq_9))
	T_10 (in 0<16> : word16)
	T_23 (in si_13 + 0x26<16> : word16)
Eq_12: (segment "Eq_12" (0 (arr Eq_26) a0000))
	T_12 (in 0x5CE1<16> : selector)
Eq_26: (struct "Eq_26" 0026 (0 word16 w0000))
	T_26
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : (ptr16 Eq_2))
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
T_3: (in 0<16> : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in 0x9A2E<16> : word16)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_5 t0000)))
T_5: (in Mem5[ds:0x9A2E<16>:word16] : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_6: (in 0x100<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0x9A26<16> : word16)
  Class: Eq_7
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_8 t0000)))
T_8: (in Mem7[ds:0x9A26<16>:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in si_13 : (memptr (ptr16 Eq_12) Eq_9))
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_12) Eq_9)
  OrigDataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
T_10: (in 0<16> : word16)
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_12) Eq_9)
  OrigDataType: word16
T_11: (in 0xFFFF<16> : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in 0x5CE1<16> : selector)
  Class: Eq_12
  DataType: (ptr16 Eq_12)
  OrigDataType: (ptr16 (segment (0 (arr T_26) a0000)))
T_13: (in 0<16> : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in si_13 + 0<16> : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in Mem16[0x5CE1<16>:si_13 + 0<16>:word16] : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_16: (in v9_20 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_17: (in 0x9A26<16> : word16)
  Class: Eq_17
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_6 t0000)))
T_18: (in Mem16[ds:0x9A26<16>:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_19: (in 1<16> : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in ds->w9A26 - 1<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_21: (in Mem21[ds:0x9A26<16>:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_22: (in 0x26<16> : word16)
  Class: Eq_22
  DataType: int16
  OrigDataType: int16
T_23: (in si_13 + 0x26<16> : word16)
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_12) Eq_9)
  OrigDataType: (memptr T_12 (struct 0026 (0 word16 w0000)))
T_24: (in 0<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_25: (in v9_20 != 0<16> : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26:
  Class: Eq_26
  DataType: Eq_26
  OrigDataType: (struct 0026 (0 T_15 t0000))
