// Before ///////
// proc1
// Return size: 0
void proc1(word32 dwArg04, word32 dwArg08)
proc1_entry:
	// succ:  l1
l1:
	Mem7[0x00001234:word32] = (int32) Mem0[dwArg04 + dwArg08 * 0x00000002:int16]
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1(word32 dwArg04, word32 dwArg08)
proc1_entry:
	// succ:  l1
l1:
	globals->dw1234 = (int32) dwArg04[dwArg08]
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (1234 int32 dw1234))
	globals_t (in globals : (ptr (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in dwArg04 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in dwArg08 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in dwArg04 : (arr int16))
  Class: Eq_4
  DataType: (ptr (arr int16))
  OrigDataType: (ptr (struct (0 (arr T_12) a0000)))
T_5: (in dwArg08 : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in 0x00000002 : word32)
  Class: Eq_6
  DataType: ui32
  OrigDataType: ui32
T_7: (in dwArg08 * 0x00000002 : word32)
  Class: Eq_7
  DataType: ui32
  OrigDataType: ui32
T_8: (in dwArg04[dwArg08 * 0x00000002] : int16)
  Class: Eq_8
  DataType: int16
  OrigDataType: int16
T_9: (in (int32) dwArg04[dwArg08] : int32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_10: (in 0x00001234 : word32)
  Class: Eq_10
  DataType: (ptr int32)
  OrigDataType: (ptr (struct (0 T_11 t0000)))
T_11: (in Mem7[0x00001234:word32] : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: word32
T_12:
  Class: Eq_12
  DataType: int16
  OrigDataType: (struct 0002 (0 T_8 t0000))
