// Before ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	selector ds
	word16 bx
	// succ:  l1
l1:
	Mem6[ds:0x300<16>:word16] = Mem0[ds:Mem0[ds:bx:word16]:word16]
	return
	// succ:  proc1_exit
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	struct Eq_2 * ds
	word16 Eq_2::* Eq_2::* bx
	// succ:  l1
l1:
	ds->w0300 = ds->*(ds->*bx)
	return
	// succ:  proc1_exit
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "Eq_2" (300 word16 w0300))
	T_2 (in ds : (ptr16 Eq_2))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : (ptr16 Eq_2))
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (300 T_14 t0300)))
T_3: (in bx : (memptr (ptr16 Eq_2) (memptr (ptr16 Eq_2) word16)))
  Class: Eq_3
  DataType: (memptr (ptr16 Eq_2) (memptr (ptr16 Eq_2) word16))
  OrigDataType: (memptr T_2 (struct (0 T_7 t0000)))
T_4: (in 0<16> : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in bx + 0<16> : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in ds:bx + 0<16> : segptr32)
  Class: Eq_6
  DataType: segptr32
  OrigDataType: segptr32
T_7: (in Mem0[ds:bx + 0<16>:word16] : word16)
  Class: Eq_7
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_11 t0000)))
T_8: (in 0<16> : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in Mem0[ds:bx + 0<16>:word16] + 0<16> : word16)
  Class: Eq_9
  DataType: word16
  OrigDataType: word16
T_10: (in ds:Mem0[ds:bx + 0<16>:word16] + 0<16> : segptr32)
  Class: Eq_10
  DataType: segptr32
  OrigDataType: segptr32
T_11: (in Mem0[ds:Mem0[ds:bx + 0<16>:word16] + 0<16>:word16] : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in 0x300<16> : word16)
  Class: Eq_12
  DataType: (memptr (ptr16 Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_14 t0000)))
T_13: (in ds:0x300<16> : segptr32)
  Class: Eq_13
  DataType: segptr32
  OrigDataType: segptr32
T_14: (in Mem6[ds:0x300<16>:word16] : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
