// SegmentedMemoryPointerMock
void SegmentedMemoryPointerMock()
SegmentedMemoryPointerMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	si = &Eq_4::w0001;
	ax = (cs->*si).w0000;
	si2 = &Eq_4::w0005;
	ax = cs->*si2;
	cs->w1234 = ax;
	(cs->*si).w0002 = ax;
	// succ: 

// Equivalence classes ////////////
Eq_2: (struct "Eq_2" (0 word16 w0000) (2 word16 w0002))
	T_2 (in 0x0001 : word16)
	T_3 (in si : word16)
Eq_4: (segment "Eq_4" (1 word16 w0001) (5 word16 w0005) (1234 word16 w1234))
	T_4 (in cs : selector)
// Type Variables ////////////
Globals: (in globals : ptr0)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in 0x0001 : word16)
  Class: Eq_2
  DataType: (memptr (ptr Eq_4) Eq_2)
  OrigDataType: word16
T_3: (in si : word16)
  Class: Eq_2
  DataType: (memptr (ptr Eq_4) Eq_2)
  OrigDataType: (memptr T_4 (struct (0 T_5 t0000) (2 T_14 t0002)))
T_4: (in cs : selector)
  Class: Eq_4
  DataType: (ptr Eq_4)
  OrigDataType: (ptr (segment (1 T_5 t0001) (5 T_9 t0005) (1234 T_11 t1234)))
T_5: (in Mem0[cs:si:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in ax : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_7: (in 0x0005 : word16)
  Class: Eq_7
  DataType: (memptr (ptr Eq_4) word16)
  OrigDataType: word16
T_8: (in si2 : word16)
  Class: Eq_7
  DataType: (memptr (ptr Eq_4) word16)
  OrigDataType: (memptr T_4 (struct (0 T_9 t0000)))
T_9: (in Mem0[cs:si2:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_10: (in 0x1234 : word16)
  Class: Eq_10
  DataType: (memptr (ptr Eq_4) word16)
  OrigDataType: (memptr T_4 (struct (0 T_11 t0000)))
T_11: (in Mem0[cs:0x1234:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_12: (in 0x0002 : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in si + 0x0002 : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in Mem0[cs:si + 0x0002:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
