// Before ///////
// StaggeredArraysFragment
// Return size: 0
define StaggeredArraysFragment
StaggeredArraysFragment_entry:
	// succ:  l1
l1:
	x = Mem0[p + i *s 8<32>:word32]
	x = Mem0[p + (i *s 8<32> + 4<i32>):word32]
StaggeredArraysFragment_exit:

// After ///////
// StaggeredArraysFragment
// Return size: 0
define StaggeredArraysFragment
StaggeredArraysFragment_entry:
	// succ:  l1
l1:
	x = p[i].dw0000
	x = p[i].dw0004
StaggeredArraysFragment_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_13: (struct "Eq_13" 0008 (0 word32 dw0000) (4 word32 dw0004))
	T_13
Eq_15: (struct "Eq_15" 0008 (4 word32 dw0004))
	T_15
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in p : (arr Eq_13))
  Class: Eq_2
  DataType: (ptr32 (arr Eq_13))
  OrigDataType: (ptr32 (struct (0 (arr T_13) a0000) (4 T_16 t0004)))
T_3: (in i : word32)
  Class: Eq_3
  DataType: ui32
  OrigDataType: ui32
T_4: (in 8<32> : word32)
  Class: Eq_4
  DataType: ui32
  OrigDataType: ui32
T_5: (in i * 8<32> : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in p[i * 8<32>] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in x : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_8: (in 4<i32> : int32)
  Class: Eq_8
  DataType: int32
  OrigDataType: int32
T_9: (in p + 4<i32> : ptr32)
  Class: Eq_9
  DataType: (ptr32 (arr Eq_15))
  OrigDataType: (ptr32 T_16)
T_10: (in 8<32> : word32)
  Class: Eq_10
  DataType: ui32
  OrigDataType: ui32
T_11: (in i * 8<32> : word32)
  Class: Eq_11
  DataType: ui32
  OrigDataType: ui32
T_12: (in (p + 4<i32>)[i * 8<32>] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_13:
  Class: Eq_13
  DataType: Eq_13
  OrigDataType: (struct 0008 (0 T_6 t0000))
T_14:
  Class: Eq_14
  DataType: (arr Eq_13)
  OrigDataType: (arr T_13)
T_15:
  Class: Eq_15
  DataType: Eq_15
  OrigDataType: (struct 0008 (0 T_12 t0000))
T_16:
  Class: Eq_16
  DataType: (arr Eq_15)
  OrigDataType: (arr T_15)
