// Before ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	Mem6[0x00001234:word32] = (int32) Mem0[Mem0[fp + 0x00000004:word32] + Mem0[fp + 0x00000008:word32] * 0x00000002:int16]
proc1_exit:

// After ///////
// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	globals->dw1234 = (int32) fp->ptr0004[fp->dw0008]
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (1234 int32 dw1234))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (struct "Eq_2" (4 (ptr32 (arr int16)) ptr0004) (8 ui32 dw0008))
	T_2 (in fp : ptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fp : ptr32)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (struct (4 T_5 t0004) (8 T_8 t0008)))
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in fp + 0x00000004 : word32)
  Class: Eq_4
  DataType: ptr32
  OrigDataType: ptr32
T_5: (in Mem0[fp + 0x00000004:word32] : word32)
  Class: Eq_5
  DataType: (ptr32 (arr int16))
  OrigDataType: (ptr32 (struct (0 (arr T_15) a0000)))
T_6: (in 0x00000008 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in fp + 0x00000008 : word32)
  Class: Eq_7
  DataType: ptr32
  OrigDataType: ptr32
T_8: (in Mem0[fp + 0x00000008:word32] : word32)
  Class: Eq_8
  DataType: ui32
  OrigDataType: ui32
T_9: (in 0x00000002 : word32)
  Class: Eq_9
  DataType: ui32
  OrigDataType: ui32
T_10: (in fp->dw0008 * 0x00000002 : word32)
  Class: Eq_10
  DataType: ui32
  OrigDataType: ui32
T_11: (in Mem0[fp + 0x00000004:word32][Mem0[fp + 0x00000008:word32] * 0x00000002] : int16)
  Class: Eq_11
  DataType: int16
  OrigDataType: int16
T_12: (in (int32) Mem0[fp + 0x00000004:word32][Mem0[fp + 0x00000008:word32] * 0x00000002] : int32)
  Class: Eq_12
  DataType: int32
  OrigDataType: int32
T_13: (in 0x00001234 : word32)
  Class: Eq_13
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_14 t0000)))
T_14: (in Mem6[0x00001234:word32] : word32)
  Class: Eq_12
  DataType: int32
  OrigDataType: word32
T_15:
  Class: Eq_15
  DataType: int16
  OrigDataType: (struct 0002 (0 T_11 t0000))
