// Before ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	bx = bx >>u 2<8>
	f = bx < 4<16>
	bx = 4<16>
proc1_exit:

// After ///////
// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	bx = bx >> 2<8>
	f = bx < 4<16>
	bx.u0 = 4<16>
proc1_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (union "Eq_2" (ci16 u0) (uint16 u1))
	T_2 (in bx : Eq_2)
	T_4 (in bx >> 2<8> : word16)
	T_5 (in 4<16> : word16)
	T_8 (in 4<16> : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in bx : Eq_2)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: ci16
T_3: (in 2<8> : byte)
  Class: Eq_3
  DataType: byte
  OrigDataType: byte
T_4: (in bx >> 2<8> : word16)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: uint16
T_5: (in 4<16> : word16)
  Class: Eq_2
  DataType: ci16
  OrigDataType: ci16
T_6: (in bx < 4<16> : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in f : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_8: (in 4<16> : word16)
  Class: Eq_2
  DataType: ci16
  OrigDataType: word16
