// Before ///////
// UnionIntRealMock
// Return size: 0
define UnionIntRealMock
UnionIntRealMock_entry:
	// succ:  l1
l1:
	x = i
	x = r
	Mem0[ptr:int32] = i
	Mem0[ptr + 4<i32>:real32] = r
	return
	// succ:  UnionIntRealMock_exit
UnionIntRealMock_exit:

// After ///////
// UnionIntRealMock
// Return size: 0
define UnionIntRealMock
UnionIntRealMock_entry:
	// succ:  l1
l1:
	x = i
	x = r
	ptr->t0000.u0 = (int32) i
	ptr->t0004.u1 = (real32) r
	return
	// succ:  UnionIntRealMock_exit
UnionIntRealMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (union "Eq_2" (int32 u0) (real32 u1))
	T_2 (in i : Eq_2)
	T_3 (in x : Eq_2)
	T_4 (in r : Eq_2)
	T_8 (in Mem0[ptr + 0<32>:int32] : int32)
	T_11 (in Mem0[ptr + 4<i32>:real32] : real32)
Eq_5: (struct "Eq_5" (0 Eq_2 t0000) (4 Eq_2 t0004))
	T_5 (in ptr : (ptr32 Eq_5))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in i : Eq_2)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: int32
T_3: (in x : Eq_2)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: (union (int32 u0) (real32 u1))
T_4: (in r : Eq_2)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: real32
T_5: (in ptr : (ptr32 Eq_5))
  Class: Eq_5
  DataType: (ptr32 Eq_5)
  OrigDataType: (ptr32 (struct (0 T_8 t0000) (4 T_11 t0004)))
T_6: (in 0<32> : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in ptr + 0<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem0[ptr + 0<32>:int32] : int32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: int32
T_9: (in 4<i32> : int32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_10: (in ptr + 4<i32> : word32)
  Class: Eq_10
  DataType: ptr32
  OrigDataType: ptr32
T_11: (in Mem0[ptr + 4<i32>:real32] : real32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: real32
