// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_000C(ds)
	fn0C00_0015(ds)
	Mem7[ds:0x100<16>:word16] = 0<16>
	// succ:  l0C00_0006_thunk_fn0C00_000C
l0C00_0006_thunk_fn0C00_000C:
	fn0C00_000C(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000C
// Return size: 0
void fn0C00_000C(selector ds)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	Mem7[ds:0x302<16>:word16] = Mem0[ds:0x300<16>:word16]
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

// fn0C00_0015
// Return size: 0
void fn0C00_0015(selector ds)
fn0C00_0015_entry:
	// succ:  l0C00_0015
l0C00_0015:
	Mem7[ds:0x202<16>:word16] = Mem0[ds:0x200<16>:word16]
	return
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in ds : selector)
	trait_primitive(selector)
	trait_equal(T_5)
	trait_primitive(selector)
	trait_equal(T_9)
	trait_primitive(selector)
	trait_mem(T_13, 100)
	trait_primitive(selector)
	trait_equal(T_5)
T_3 (in fn0C00_000C : segptr32)
	trait_func(T_2 -> T_6)
T_5 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_17, 300)
	trait_primitive(selector)
	trait_mem(T_19, 302)
T_6 (in fn0C00_000C(ds) : void)
	trait_primitive(void)
T_7 (in fn0C00_0015 : segptr32)
	trait_func(T_2 -> T_10)
T_9 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_21, 200)
	trait_primitive(selector)
	trait_mem(T_23, 202)
T_10 (in fn0C00_0015(ds) : void)
	trait_primitive(void)
T_11 (in 0<16> : word16)
	trait_primitive(word16)
T_12 (in 0x100<16> : word16)
	trait_primitive(word16)
	trait_mem(T_2:T_13, 0)
T_13 (in Mem7[ds:0x100<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_11)
T_14 (in fn0C00_000C : segptr32)
	trait_func(T_2 -> T_15)
T_15 (in fn0C00_000C(ds) : void)
	trait_primitive(void)
T_16 (in 0x300<16> : word16)
	trait_primitive(word16)
	trait_mem(T_5:T_17, 0)
T_17 (in Mem0[ds:0x300<16>:word16] : word16)
	trait_primitive(word16)
T_18 (in 0x302<16> : word16)
	trait_primitive(word16)
	trait_mem(T_5:T_19, 0)
T_19 (in Mem7[ds:0x302<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_17)
T_20 (in 0x200<16> : word16)
	trait_primitive(word16)
	trait_mem(T_9:T_21, 0)
T_21 (in Mem0[ds:0x200<16>:word16] : word16)
	trait_primitive(word16)
T_22 (in 0x202<16> : word16)
	trait_primitive(word16)
	trait_mem(T_9:T_23, 0)
T_23 (in Mem7[ds:0x202<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_21)
