// TreeFindMock
// Return size: 0
void TreeFindMock()
TreeFindMock_entry:
	// succ:  l0
l0:
	// succ:  l0_seek
l0_seek:
	branch t == 0<32> l5_found
	// succ:  l1 l5_found
l1:
	vv_5 = Mem0[t + 0<32>:word32]
	branch v == vv_5 l5_found
	// succ:  l2 l5_found
l2:
	branch v < vv_5 l4_lt
	// succ:  l3 l4_lt
l3:
	t = Mem0[t + 8<32>:word32]
	goto l0_seek
	// succ:  l0_seek
l4_lt:
	t = Mem0[t + 4<32>:word32]
	// succ:  l5_found
l5_found:
	return t
	// succ:  TreeFindMock_exit
TreeFindMock_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in t : word32)
	trait_primitive(word32)
	trait_equal(T_3)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_mem(T_7, 0)
	trait_primitive(word32)
	trait_mem(T_14, 4)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_14)
	trait_primitive(word32)
	trait_mem(T_17, 8)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_17)
T_3 (in 0<32> : word32)
	trait_primitive(word32)
T_4 (in t == 0<32> : bool)
	trait_primitive(bool)
T_5 (in 0<32> : word32)
	trait_primitive(word32)
T_6 (in t + 0<32> : word32)
	trait_primitive(word32)
T_7 (in Mem0[t + 0<32>:word32] : word32)
	trait_primitive(word32)
T_8 (in vv_5 : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_7)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_primitive(int32)
T_9 (in v : word32)
	trait_primitive(word32)
	trait_equal(T_8)
	trait_primitive(word32)
	trait_equal(T_8)
	trait_primitive(int32)
T_10 (in v == vv_5 : bool)
	trait_primitive(bool)
T_11 (in v < vv_5 : bool)
	trait_primitive(bool)
T_12 (in 4<32> : word32)
	trait_primitive(word32)
T_13 (in t + 4<32> : word32)
	trait_primitive(word32)
T_14 (in Mem0[t + 4<32>:word32] : word32)
	trait_primitive(word32)
T_15 (in 8<32> : word32)
	trait_primitive(word32)
T_16 (in t + 8<32> : word32)
	trait_primitive(word32)
T_17 (in Mem0[t + 8<32>:word32] : word32)
	trait_primitive(word32)
