// StaggeredArraysFragment
// Return size: 0
define StaggeredArraysFragment
StaggeredArraysFragment_entry:
	// succ:  l1
l1:
	x = p[i * 8<32>]
	x = (p + 4<i32>)[i * 8<32>]
StaggeredArraysFragment_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in p : word32)
	trait_primitive(word32)
	trait_mem_array(0, 8, 0, T_6)
	trait_primitive(word32)
	trait_mem_array(4, 8, 0, T_12)
T_3 (in i : word32)
	trait_primitive(word32)
	trait_primitive(ui32)
	trait_primitive(word32)
	trait_primitive(ui32)
T_4 (in 8<32> : word32)
	trait_primitive(word32)
	trait_primitive(ui32)
T_5 (in i * 8<32> : word32)
	trait_primitive(ui32)
T_6 (in p[i * 8<32>] : word32)
	trait_primitive(word32)
T_7 (in x : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_6)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_12)
T_8 (in 4<i32> : int32)
	trait_primitive(int32)
T_9 (in p + 4<i32> : ptr32)
	trait_primitive(ptr32)
T_10 (in 8<32> : word32)
	trait_primitive(word32)
	trait_primitive(ui32)
T_11 (in i * 8<32> : word32)
	trait_primitive(ui32)
T_12 (in (p + 4<i32>)[i * 8<32>] : word32)
	trait_primitive(word32)
