// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem4[ds:0x0064:word16] = fn0C00_000B(0x0005)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000B
// Return size: 0
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:
	// succ:  l0C00_000B
l0C00_000B:
	word16 ax_11
	branch cx <= 0x0001 l0C00_001C
	// succ:  l0C00_0011 l0C00_001C
l0C00_0011:
	ax_11 = (word16) (cx *s fn0C00_000B(cx - 0x0001)) (alias)
	goto l0C00_001F
	// succ:  l0C00_001F
l0C00_001C:
	ax_11 = 0x0001
	// succ:  l0C00_001F
l0C00_001F:
	return ax_11
	// succ:  fn0C00_000B_exit
fn0C00_000B_exit:

globals_t (in globals : (ptr (struct "Globals")))
	trait_primitive((ptr (struct "Globals")))
T_2 (in ds : selector)
	trait_primitive(selector)
	trait_mem(T_9, 64)
T_3 (in fn0C00_000B : segptr32)
	trait_func(T_6 -> T_7)
T_5 (in cx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_12)
	trait_primitive(int16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_6 (in 0x0005 : word16)
	trait_primitive(word16)
	trait_equal(T_5)
T_7 (in fn0C00_000B(0x0005) : word16)
	trait_primitive(word16)
	trait_equal(T_10)
T_8 (in 0x0064 : word16)
	trait_primitive(word16)
	trait_mem(T_2:T_9, 0)
T_9 (in Mem4[ds:0x0064:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_7)
T_10 (in ax : word16)
	trait_primitive(word16)
	trait_equal(T_11)
T_11 (in ax_11 : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_14)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_20)
	trait_primitive(word16)
T_12 (in 0x0001 : word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_13 (in cx <= 0x0001 : bool)
	trait_primitive(bool)
T_14 (in 0x0001 : word16)
	trait_primitive(word16)
T_15 (in fn0C00_000B : segptr32)
	trait_func(T_17 -> T_18)
T_16 (in 0x0001 : word16)
	trait_primitive(word16)
T_17 (in cx - 0x0001 : word16)
	trait_primitive(word16)
	trait_equal(T_5)
T_18 (in fn0C00_000B(cx - 0x0001) : word16)
	trait_primitive(word16)
	trait_equal(T_10)
	trait_primitive(int16)
T_19 (in cx *s fn0C00_000B(cx - 0x0001) : int32)
	trait_primitive(int32)
	trait_primitive(int32)
T_20 (in (word16) (cx *s fn0C00_000B(cx - 0x0001)) : word16)
	trait_primitive(word16)
