// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, word16 si, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 ax_7 = Mem0[ds:bx + 0x0004:word16]
	Mem9[ds:bx + 0x0006:word16] = ax_7 *s ax_7
	Mem12[ds:si + 0x04D4:word16] = si + 0x0002
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in bx : word16)
	trait_primitive(word16)
	trait_mem(T_4:T_8, 4)
	trait_primitive(word16)
	trait_mem(T_4:T_12, 6)
T_3 (in si : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_4:T_17, 4D4)
T_4 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
T_5 (in ax_7 : word16)
	trait_primitive(word16)
	trait_equal(T_8)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(int16)
	trait_primitive(int16)
T_6 (in 0x0004 : word16)
	trait_primitive(word16)
T_7 (in bx + 0x0004 : word16)
	trait_primitive(word16)
T_8 (in Mem0[ds:bx + 0x0004:word16] : word16)
	trait_primitive(word16)
T_9 (in ax_7 *s ax_7 : int16)
	trait_primitive(int16)
	trait_primitive(int16)
T_10 (in 0x0006 : word16)
	trait_primitive(word16)
T_11 (in bx + 0x0006 : word16)
	trait_primitive(word16)
T_12 (in Mem9[ds:bx + 0x0006:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_9)
T_13 (in 0x0002 : word16)
	trait_primitive(word16)
T_14 (in si + 0x0002 : word16)
	trait_primitive(word16)
T_15 (in 0x04D4 : word16)
	trait_primitive(word16)
T_16 (in si + 0x04D4 : word16)
	trait_primitive(word16)
T_17 (in Mem12[ds:si + 0x04D4:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_14)
