// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem11[ds:0x9A2E:word16]) = 0x0000
	store(Mem13[ds:0x9A26:word16]) = 0x0100
	word16 si_16 = 0x0000
	// succ:  2
l0C00_0015:		// block 2, pred: 1 2
	store(Mem19[0x5CE1:si_16:word16]) = 0xFFFF
	word16 v8_22 = Mem19[ds:0x9A26:word16] - 0x0001
	store(Mem23[ds:0x9A26:word16]) = v8_22
	si_16 = si_16 + 0x0026
	branch v8_22 != 0x0000
	// succ:  3 2
l0C00_0023:		// block 3, pred: 2
	return
	// succ:  4
fn0C00_0000_exit:		// block 4, pred: 3
	// succ: 

T_2 (in 0x0000 : word16)
	trait_primitive(word16)
T_3 (in ds : selector)
	trait_primitive(selector)
	trait_mem(T_5, 9A2E)
	trait_primitive(selector)
	trait_mem(T_8, 9A26)
	trait_primitive(selector)
	trait_mem(T_16, 9A26)
	trait_primitive(selector)
	trait_mem(T_19, 9A26)
T_4 (in 0x9A2E : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_5, 0)
T_5 (in Mem11[ds:0x9A2E:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_2)
T_6 (in 0x0100 : word16)
	trait_primitive(word16)
T_7 (in 0x9A26 : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_8, 0)
T_8 (in Mem13[ds:0x9A26:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_6)
T_9 (in si_16 : word16)
	trait_equal(T_10)
	trait_primitive(word16)
	trait_memsize(38)
	trait_mem(T_12:T_13, 0)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_21)
T_10 (in 0x0000 : word16)
	trait_primitive(word16)
T_11 (in 0xFFFF : word16)
	trait_primitive(word16)
T_12 (in 0x5CE1 : selector)
	trait_primitive(selector)
	trait_mem_array(0, 38, 0, T_13)
T_13 (in Mem19[0x5CE1:si_16:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_11)
T_14 (in v8_22 : word16)
	trait_equal(T_18)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_22)
T_15 (in 0x9A26 : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_16, 0)
	trait_primitive(word16)
	trait_mem(T_3:T_19, 0)
T_16 (in Mem19[ds:0x9A26:word16] : word16)
	trait_primitive(word16)
T_17 (in 0x0001 : word16)
	trait_primitive(word16)
T_18 (in Mem19[ds:0x9A26:word16] - 0x0001 : word16)
	trait_primitive(word16)
T_19 (in Mem23[ds:0x9A26:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_14)
T_20 (in 0x0026 : word16)
	trait_primitive(word16)
T_21 (in si_16 + 0x0026 : word16)
	trait_primitive(word16)
T_22 (in 0x0000 : word16)
	trait_primitive(word16)
T_23 (in v8_22 != 0x0000 : bool)
	trait_primitive(bool)
