// IntelIndexedAddressingMode
// Return size: 0
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:
	// succ:  l1
l1:
	ds:Mem0[ds:0xCA4<16>:word16] + 0xA<16>[Mem0[ds:0x1C0A<16>:word16] * 0x4A<16>] = 0xF8<8>
	return
	// succ:  IntelIndexedAddressingMode_exit
IntelIndexedAddressingMode_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in 0xF8<8> : byte)
	trait_primitive(byte)
T_3 (in ds : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_6, CA4)
	trait_primitive(word16)
	trait_mem(T_12, 1C0A)
T_4 (in 0xCA4<16> : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_6, 0)
T_5 (in ds:0xCA4<16> : segptr32)
	trait_primitive(segptr32)
T_6 (in Mem0[ds:0xCA4<16>:word16] : word16)
	trait_primitive(word16)
	trait_mem_array(A, 74, 0, T_15)
T_7 (in 0xA<16> : word16)
	trait_primitive(word16)
T_8 (in Mem0[ds:0xCA4<16>:word16] + 0xA<16> : word16)
	trait_primitive(word16)
T_9 (in ds:Mem0[ds:0xCA4<16>:word16] + 0xA<16> : ptr32)
	trait_primitive(ptr32)
T_10 (in 0x1C0A<16> : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_12, 0)
T_11 (in ds:0x1C0A<16> : segptr32)
	trait_primitive(segptr32)
T_12 (in Mem0[ds:0x1C0A<16>:word16] : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_13 (in 0x4A<16> : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_14 (in Mem0[ds:0x1C0A<16>:word16] * 0x4A<16> : word16)
	trait_primitive(ui16)
T_15 (in ds:Mem0[ds:0xCA4<16>:word16] + 0xA<16>[Mem0[ds:0x1C0A<16>:word16] * 0x4A<16>] : byte)
	trait_primitive(byte)
	trait_equal(T_2)
