// IndirectCallFragment
// Return size: 0
define IndirectCallFragment
IndirectCallFragment_entry:
	// succ:  l1
l1:
	call SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) (retsize: 4;)
	return
	// succ:  IndirectCallFragment_exit
IndirectCallFragment_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_2, 27000)
T_2 (in 0x2700<16> : selector)
	trait_primitive(selector)
T_3 (in ds : selector)
	trait_primitive(selector)
	trait_mem_array(2040, 2, 0, T_9)
T_4 (in 0x2040<16> : word16)
	trait_primitive(word16)
T_5 (in SEQ(ds, 0x2040<16>) : ptr32)
	trait_primitive(ptr32)
T_6 (in di : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_7 (in 2<16> : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_8 (in di * 2<16> : word16)
	trait_primitive(ui16)
T_9 (in SEQ(ds, 0x2040<16>)[di * 2<16>] : word16)
	trait_primitive(word16)
T_10 (in SEQ(0x2700<16>, SEQ(ds, 0x2040<16>)[di * 2<16>]) : ptr32)
	trait_primitive((ptr32 code))
	trait_primitive(ptr32)
