// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_23 = 0x0FFF
	byte bh_24 = 0x0F
	byte bl_25 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	Mem22[0x4DE1:bx_23 + 0x0000:byte] = bl_25 & 0xF0 | SLICE((bl_25 & 0x0F) *u (bh_24 + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_23 = bx_23 - 0x0001
	bh_24 = SLICE(bx_23, byte, 8) (alias)
	bl_25 = (byte) bx_23 (alias)
	branch bx_23 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_24, 4DE10)
T_2 (in fn0C00_0004 : segptr32)
	trait_func( -> T_4)
T_4 (in fn0C00_0004() : void)
	trait_primitive(void)
T_5 (in bx_23 : word16)
	trait_primitive(word16)
	trait_equal(T_6)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_29)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_32)
	trait_primitive(int16)
T_6 (in 0x0FFF : word16)
	trait_primitive(word16)
T_7 (in bh_24 : byte)
	trait_primitive(byte)
	trait_equal(T_8)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_equal(T_30)
T_8 (in 0x0F : byte)
	trait_primitive(byte)
T_9 (in bl_25 : byte)
	trait_primitive(byte)
	trait_equal(T_10)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_equal(T_31)
T_10 (in 0xFF : byte)
	trait_primitive(byte)
T_11 (in 0xF0 : byte)
	trait_primitive(byte)
T_12 (in bl_25 & 0xF0 : byte)
	trait_primitive(byte)
T_13 (in 0x0F : byte)
	trait_primitive(byte)
T_14 (in bl_25 & 0x0F : byte)
	trait_primitive(byte)
	trait_primitive(uint8)
T_15 (in 0x01 : byte)
	trait_primitive(byte)
T_16 (in bh_24 + 0x01 : byte)
	trait_primitive(byte)
	trait_primitive(uint8)
T_17 (in (bl_25 & 0x0F) *u (bh_24 + 0x01) : uint16)
	trait_primitive(uint16)
	trait_primitive(uint16)
T_18 (in 0x0004 : word16)
	trait_primitive(word16)
T_19 (in (bl_25 & 0x0F) *u (bh_24 + 0x01) << 0x0004 : word16)
	trait_primitive(ui16)
T_20 (in SLICE((bl_25 & 0x0F) *u (bh_24 + 0x01) << 0x0004, byte, 8) : byte)
	trait_primitive(byte)
T_21 (in 0x0F : byte)
	trait_primitive(byte)
T_22 (in SLICE((bl_25 & 0x0F) *u (bh_24 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
	trait_primitive(byte)
T_23 (in bl_25 & 0xF0 | SLICE((bl_25 & 0x0F) *u (bh_24 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
	trait_primitive(byte)
T_24 (in 0x4DE1 : selector)
	trait_primitive(selector)
	trait_mem_array(0, 1, 4096, T_27)
T_25 (in 0x0000 : word16)
	trait_primitive(word16)
	trait_memsize(1)
	trait_mem(T_24:T_27, 0)
T_26 (in bx_23 + 0x0000 : word16)
	trait_primitive(word16)
T_27 (in Mem22[0x4DE1:bx_23 + 0x0000:byte] : byte)
	trait_primitive(byte)
	trait_equal(T_23)
T_28 (in 0x0001 : word16)
	trait_primitive(word16)
T_29 (in bx_23 - 0x0001 : word16)
	trait_primitive(word16)
T_30 (in SLICE(bx_23, byte, 8) : byte)
	trait_primitive(byte)
T_31 (in (byte) bx_23 : byte)
	trait_primitive(byte)
T_32 (in 0x0000 : word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_33 (in bx_23 >= 0x0000 : bool)
	trait_primitive(bool)
