// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, word16 si, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 ax_7 = Mem0[ds:bx + 4<i16>:word16]
	Mem9[ds:bx + 6<i16>:word16] = ax_7 *s ax_7
	Mem12[ds:si + 0x4D4<16>:word16] = si + 2<i16>
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_3 (in bx : word16)
	trait_primitive(word16)
	trait_mem(T_5:T_9, 4)
	trait_primitive(word16)
	trait_mem(T_5:T_13, 6)
T_4 (in si : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_5:T_18, 4D4)
T_5 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
T_6 (in ax_7 : word16)
	trait_primitive(word16)
	trait_equal(T_9)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(int16)
	trait_primitive(int16)
T_7 (in 4<i16> : int16)
	trait_primitive(int16)
T_8 (in bx + 4<i16> : word16)
	trait_primitive(word16)
T_9 (in Mem0[ds:bx + 4<i16>:word16] : word16)
	trait_primitive(word16)
T_10 (in ax_7 *s ax_7 : int16)
	trait_primitive(int16)
	trait_primitive(int16)
T_11 (in 6<i16> : int16)
	trait_primitive(int16)
T_12 (in bx + 6<i16> : word16)
	trait_primitive(word16)
T_13 (in Mem9[ds:bx + 6<i16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_10)
T_14 (in 2<i16> : int16)
	trait_primitive(int16)
T_15 (in si + 2<i16> : word16)
	trait_primitive(word16)
T_16 (in 0x4D4<16> : word16)
	trait_primitive(word16)
T_17 (in si + 0x4D4<16> : word16)
	trait_primitive(word16)
T_18 (in Mem12[ds:si + 0x4D4<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_15)
