// SegmentedMemoryPointerMock
void SegmentedMemoryPointerMock()
SegmentedMemoryPointerMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	si = 0x0001
	ax = Mem0[cs:si:word16]
	si2 = 0x0005
	ax = Mem0[cs:si2:word16]
	store(Mem0[cs:0x1234:word16]) = ax
	store(Mem0[cs:si + 0x0002:word16]) = ax
	// succ: 

T_2 (in 0x0001 : word16)
	trait_primitive(word16)
T_3 (in si : word16)
	trait_primitive(word16)
	trait_equal(T_2)
	trait_primitive(word16)
	trait_mem(T_4:T_5, 0)
	trait_primitive(word16)
	trait_mem(T_4:T_14, 2)
T_4 (in cs : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_11, 1234)
	trait_primitive(selector)
T_5 (in Mem0[cs:si:word16] : word16)
	trait_primitive(word16)
T_6 (in ax : word16)
	trait_primitive(word16)
	trait_equal(T_5)
	trait_primitive(word16)
	trait_equal(T_9)
	trait_primitive(word16)
	trait_primitive(word16)
T_7 (in 0x0005 : word16)
	trait_primitive(word16)
T_8 (in si2 : word16)
	trait_primitive(word16)
	trait_equal(T_7)
	trait_primitive(word16)
	trait_mem(T_4:T_9, 0)
T_9 (in Mem0[cs:si2:word16] : word16)
	trait_primitive(word16)
T_10 (in 0x1234 : word16)
	trait_primitive(word16)
	trait_mem(T_4:T_11, 0)
T_11 (in Mem0[cs:0x1234:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_6)
T_12 (in 0x0002 : word16)
	trait_primitive(word16)
T_13 (in si + 0x0002 : word16)
	trait_primitive(word16)
T_14 (in Mem0[cs:si + 0x0002:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_6)
