// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_000C(ds)
	fn0C00_0015(ds)
	Mem7[ds:0x100<16>:word16] = 0<16>
	// succ:  l0C00_0006_thunk_fn0C00_000C
l0C00_0006_thunk_fn0C00_000C:
	fn0C00_000C(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000C
// Return size: 0
void fn0C00_000C(selector ds)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	Mem7[ds:0x302<16>:word16] = Mem0[ds:0x300<16>:word16]
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

// fn0C00_0015
// Return size: 0
void fn0C00_0015(selector ds)
fn0C00_0015_entry:
	// succ:  l0C00_0015
l0C00_0015:
	Mem7[ds:0x202<16>:word16] = Mem0[ds:0x200<16>:word16]
	return
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_3 (in ds : selector)
	trait_primitive(selector)
	trait_equal(T_6)
	trait_primitive(selector)
	trait_equal(T_10)
	trait_primitive(selector)
	trait_mem(T_15, 100)
	trait_primitive(selector)
	trait_equal(T_6)
T_4 (in fn0C00_000C : segptr32)
	trait_func(T_3 -> T_7)
T_6 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_20, 300)
	trait_primitive(selector)
	trait_mem(T_23, 302)
T_7 (in fn0C00_000C(ds) : void)
	trait_primitive(void)
T_8 (in fn0C00_0015 : segptr32)
	trait_func(T_3 -> T_11)
T_10 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_26, 200)
	trait_primitive(selector)
	trait_mem(T_29, 202)
T_11 (in fn0C00_0015(ds) : void)
	trait_primitive(void)
T_12 (in 0<16> : word16)
	trait_primitive(word16)
T_13 (in 0x100<16> : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_15, 0)
T_14 (in ds:0x100<16> : segptr32)
	trait_primitive(segptr32)
T_15 (in Mem7[ds:0x100<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_12)
T_16 (in fn0C00_000C : segptr32)
	trait_func(T_3 -> T_17)
T_17 (in fn0C00_000C(ds) : void)
	trait_primitive(void)
T_18 (in 0x300<16> : word16)
	trait_primitive(word16)
	trait_mem(T_6:T_20, 0)
T_19 (in ds:0x300<16> : segptr32)
	trait_primitive(segptr32)
T_20 (in Mem0[ds:0x300<16>:word16] : word16)
	trait_primitive(word16)
T_21 (in 0x302<16> : word16)
	trait_primitive(word16)
	trait_mem(T_6:T_23, 0)
T_22 (in ds:0x302<16> : segptr32)
	trait_primitive(segptr32)
T_23 (in Mem7[ds:0x302<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_20)
T_24 (in 0x200<16> : word16)
	trait_primitive(word16)
	trait_mem(T_10:T_26, 0)
T_25 (in ds:0x200<16> : segptr32)
	trait_primitive(segptr32)
T_26 (in Mem0[ds:0x200<16>:word16] : word16)
	trait_primitive(word16)
T_27 (in 0x202<16> : word16)
	trait_primitive(word16)
	trait_mem(T_10:T_29, 0)
T_28 (in ds:0x202<16> : segptr32)
	trait_primitive(segptr32)
T_29 (in Mem7[ds:0x202<16>:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_26)
