// CmpMock
// Return size: 0
void CmpMock()
CmpMock_entry:
	// succ:  l1
l1:
	Z = cond(r0 - 0)
	branch Test(EQ,Z) skip
	// succ:  l2 skip
l2:
	r0 = r0 + r1
	// succ:  skip
skip:
	Mem0[0x10003000:word32] = r0
	return
	// succ:  CmpMock_exit
CmpMock_exit:

globals_t (in globals : (ptr (struct "Globals")))
	trait_primitive((ptr (struct "Globals")))
	trait_mem(T_9, 10003000)
T_2 (in r0 : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_11)
T_3 (in 0 : int32)
	trait_primitive(int32)
T_4 (in r0 - 0 : word32)
	trait_primitive(word32)
T_5 (in cond(r0 - 0) : byte)
	trait_primitive(byte)
T_6 (in Z : byte)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_equal(T_5)
	trait_primitive(byte)
T_7 (in Test(EQ,Z) : bool)
	trait_primitive(bool)
T_8 (in 0x10003000 : word32)
	trait_primitive(word32)
	trait_mem(T_9, 0)
T_9 (in Mem0[0x10003000:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_2)
T_10 (in r1 : word32)
	trait_primitive(word32)
T_11 (in r0 + r1 : word32)
	trait_primitive(word32)
