// FnPointerFragment
// Return size: 0
void FnPointerFragment()
FnPointerFragment_entry:
	// succ:  l1
l1:
	pfn = 0x01213130
	Mem0[0x10000000:word32] = pfn
	call Mem0[0x10000000:word32] (retsize: 4;)
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_5, 10000000)
	trait_mem(T_7, 10000000)
T_2 (in 0x01213130 : word32)
	trait_primitive(word32)
T_3 (in pfn : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_2)
	trait_primitive(word32)
T_4 (in 0x10000000 : word32)
	trait_primitive(word32)
	trait_mem(T_5, 0)
T_5 (in Mem0[0x10000000:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_3)
T_6 (in 0x10000000 : word32)
	trait_primitive(word32)
	trait_mem(T_7, 0)
T_7 (in Mem0[0x10000000:word32] : word32)
	trait_primitive((ptr32 code))
	trait_primitive(word32)
