// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	di = 0x5388
	// succ:  2
lupe:		// block 2, pred: 1 2
	Mem7[Mem7[ds:di + 0x0000:word16]:word32] = 0x00000000<32>
        di = di + 0x0002
	cx = cx - 0x0001
	branch cx != 0x0000 lupe
	// succ:  3 2
l2:		// block 3, pred: 2
	return
	// succ:  4
ProcedureMock_exit:		// block 4, pred: 3
	// succ: 

T_2 (in 0x00000000<32> : word32)
	trait_primitive(word32)
T_3 (in ds : word16)
	trait_primitive(word16)
T_4 (in di : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_7, 5388)
	trait_primitive(word16)
	trait_equal(T_9)
T_5 (in 0x5388 : word16)
	trait_primitive(word16)
T_6 (in di + 0x5388 : word16)
	trait_primitive(word16)
T_7 (in Mem6[ds:di + 0x5388:word16] : word16)
	trait_primitive(word16)
	trait_mem(T_8, 0)
T_8 (in Mem6[Mem6[ds:di + 0x5388:word16]:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_2)
T_9 (in 0xFFFF : word16)
	trait_primitive(word16)
T_10 (in di != 0xFFFF : bool)
	trait_primitive(bool)
