// IntelIndexedAddressingMode
// Return size: 0
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:
	word16 ds
	// succ:  l1
l1:
	SEQ(ds, Mem0[ds:0xCA4<16>:word16] + 0xA<16>)[Mem0[ds:0x1C0A<16>:word16] * 0x4A<16>] = 0xF8<8>
	return
	// succ:  IntelIndexedAddressingMode_exit
IntelIndexedAddressingMode_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in ds : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_5, CA4)
	trait_primitive(word16)
	trait_mem(T_10, 1C0A)
	trait_mem_array(0, 74, 0, T_13)
T_3 (in 0xF8<8> : byte)
	trait_primitive(byte)
T_4 (in 0xCA4<16> : word16)
	trait_primitive(word16)
	trait_mem(T_2:T_5, 0)
T_5 (in Mem0[ds:0xCA4<16>:word16] : word16)
	trait_primitive(word16)
T_6 (in 0xA<16> : word16)
	trait_primitive(word16)
T_7 (in Mem0[ds:0xCA4<16>:word16] + 0xA<16> : word16)
	trait_primitive(word16)
T_8 (in SEQ(ds, Mem0[ds:0xCA4<16>:word16] + 0xA<16>) : ptr32)
	trait_primitive(ptr32)
T_9 (in 0x1C0A<16> : word16)
	trait_primitive(word16)
	trait_mem(T_2:T_10, 0)
T_10 (in Mem0[ds:0x1C0A<16>:word16] : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_11 (in 0x4A<16> : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_12 (in Mem0[ds:0x1C0A<16>:word16] * 0x4A<16> : word16)
	trait_primitive(ui16)
T_13 (in SEQ(ds, Mem0[ds:0xCA4<16>:word16] + 0xA<16>)[Mem0[ds:0x1C0A<16>:word16] * 0x4A<16>] : byte)
	trait_primitive(byte)
	trait_equal(T_3)
