// FnPointerFragment
// Return size: 0
define FnPointerFragment
FnPointerFragment_entry:
	// succ:  l1
l1:
	r63 = fp
	pfn = 0x1213130<32>
	Mem0[0x10000000<32>:word32] = pfn
	call Mem0[0x10000000<32>:word32] (retsize: 4;)
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_7, 10000000)
	trait_mem(T_9, 10000000)
T_2 (in fp : ptr32)
	trait_primitive(ptr32)
T_3 (in r63 : word32)
	trait_primitive(word32)
	trait_primitive(ptr32)
	trait_equal(T_2)
T_4 (in 0x1213130<32> : word32)
	trait_primitive(word32)
T_5 (in pfn : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_4)
	trait_primitive(word32)
T_6 (in 0x10000000<32> : word32)
	trait_primitive(word32)
	trait_mem(T_7, 0)
T_7 (in Mem0[0x10000000<32>:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_5)
T_8 (in 0x10000000<32> : word32)
	trait_primitive(word32)
	trait_mem(T_9, 0)
T_9 (in Mem0[0x10000000<32>:word32] : word32)
	trait_primitive((ptr32 code))
	trait_primitive(word32)
