// SegmentedCallFragment
// Return size: 0
define SegmentedCallFragment
SegmentedCallFragment_entry:
	// succ:  l1
l1:
	bx = Mem0[ds:0x2040<16>:word16]
	call SEQ(0x2700<16>, bx) (retsize: 4;)
	return
	// succ:  SegmentedCallFragment_exit
SegmentedCallFragment_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_7, 27000)
T_2 (in ds : selector)
	trait_primitive(selector)
	trait_mem(T_5, 2040)
T_3 (in 0x2040<16> : word16)
	trait_primitive(word16)
	trait_mem(T_2:T_5, 0)
T_4 (in ds:0x2040<16> : segptr32)
	trait_primitive(segptr32)
T_5 (in Mem0[ds:0x2040<16>:word16] : word16)
	trait_primitive(word16)
T_6 (in bx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_5)
	trait_primitive(word16)
T_7 (in 0x2700<16> : selector)
	trait_primitive(selector)
T_8 (in SEQ(0x2700<16>, bx) : ptr32)
	trait_primitive((ptr32 code))
	trait_primitive(ptr32)
