// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem8[ds:bx + 0x0000:word32] = Mem0[ds:bx + 0x0004:word32]
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in bx : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_6, 4)
	trait_primitive(word16)
	trait_mem(T_3:T_9, 0)
T_3 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
T_4 (in 0x0004 : word16)
	trait_primitive(word16)
T_5 (in bx + 0x0004 : word16)
	trait_primitive(word16)
T_6 (in Mem0[ds:bx + 0x0004:word32] : word32)
	trait_primitive(word32)
T_7 (in 0x0000 : word16)
	trait_primitive(word16)
T_8 (in bx + 0x0000 : word16)
	trait_primitive(word16)
T_9 (in Mem8[ds:bx + 0x0000:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_6)
