// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem6[ds:bx:word32]) = Mem0[ds:bx + 0x0004:word32]
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

T_2 (in ds)
	trait_primitive(selector)
	trait_primitive(selector)
T_3 (in bx)
	trait_primitive(word16)
	trait_mem(T_2:T_6, 4)
	trait_primitive(word16)
	trait_mem(T_2:T_7, 0)
T_4 (in 0x0004)
	trait_primitive(word16)
T_5 (in bx + 0x0004)
	trait_primitive(word16)
T_6 (in Mem0[ds:bx + 0x0004:word32])
	trait_primitive(word32)
T_7 (in Mem6[ds:bx:word32])
	trait_primitive(word32)
	trait_equal(T_6)
