// PtrPtrIntMock
// Return size: 0
define PtrPtrIntMock
PtrPtrIntMock_entry:
	// succ:  l1
l1:
	r2 = Mem0[r1 + 0<32>:word32]
	r3 = Mem0[r2 + 0<32>:word32]
	Mem0[0x10000<32>:word32] = r3
	Mem0[0x10004<32>:word32] = r1
	return r3
	// succ:  PtrPtrIntMock_exit
PtrPtrIntMock_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
	trait_mem(T_12, 10000)
	trait_mem(T_14, 10004)
T_2 (in r1 : word32)
	trait_primitive(word32)
	trait_mem(T_5, 0)
	trait_primitive(word32)
T_3 (in 0<32> : word32)
	trait_primitive(word32)
T_4 (in r1 + 0<32> : word32)
	trait_primitive(word32)
T_5 (in Mem0[r1 + 0<32>:word32] : word32)
	trait_primitive(word32)
T_6 (in r2 : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_5)
	trait_primitive(word32)
	trait_mem(T_9, 0)
T_7 (in 0<32> : word32)
	trait_primitive(word32)
T_8 (in r2 + 0<32> : word32)
	trait_primitive(word32)
T_9 (in Mem0[r2 + 0<32>:word32] : word32)
	trait_primitive(word32)
T_10 (in r3 : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_9)
	trait_primitive(word32)
	trait_primitive(word32)
T_11 (in 0x10000<32> : word32)
	trait_primitive(word32)
	trait_mem(T_12, 0)
T_12 (in Mem0[0x10000<32>:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_10)
T_13 (in 0x10004<32> : word32)
	trait_primitive(word32)
	trait_mem(T_14, 0)
T_14 (in Mem0[0x10004<32>:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_2)
