// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	fn0C00_0004()
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_0004
void fn0C00_0004()
fn0C00_0004_entry:		// block 0, pred:
	// succ:  1
l0C00_0004:		// block 1, pred: 0
	word16 bx_15 = 0x0FFF
	byte bh_16 = 0x0F
	byte bl_17 = 0xFF
	// succ:  2
l0C00_000C:		// block 2, pred: 1 2
	store(Mem37[0x4DE1:bx_15 + 0x0000:byte]) = bl_17 & 0xF0 | SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_15 = bx_15 - 0x0001
	bh_16 = SLICE(bx_15, byte, 8) (alias)
	bl_17 = (byte) bx_15 (alias)
	branch bx_15 >= 0x0000 l0C00_000C
	// succ:  3 2
l0C00_0029:		// block 3, pred: 2
	return
	// succ:  4
fn0C00_0004_exit:		// block 4, pred: 3
	// succ: 

T_2 (in fn0C00_0004 : ptr32)
	trait_func( -> T_4)
T_4 (in fn0C00_0004() : void)
	trait_primitive(void)
T_5 (in bx_15 : word16)
	trait_primitive(word16)
	trait_equal(T_6)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_29)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_32)
	trait_primitive(int16)
T_6 (in 0x0FFF : word16)
	trait_primitive(word16)
T_7 (in bh_16 : byte)
	trait_primitive(byte)
	trait_equal(T_8)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_equal(T_30)
T_8 (in 0x0F : byte)
	trait_primitive(byte)
T_9 (in bl_17 : byte)
	trait_primitive(byte)
	trait_equal(T_10)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_primitive(byte)
	trait_equal(T_31)
T_10 (in 0xFF : byte)
	trait_primitive(byte)
T_11 (in 0xF0 : byte)
	trait_primitive(byte)
T_12 (in bl_17 & 0xF0 : byte)
	trait_primitive(byte)
T_13 (in 0x0F : byte)
	trait_primitive(byte)
T_14 (in bl_17 & 0x0F : byte)
	trait_primitive(byte)
	trait_primitive(uint8)
T_15 (in 0x01 : byte)
	trait_primitive(byte)
T_16 (in bh_16 + 0x01 : byte)
	trait_primitive(byte)
	trait_primitive(uint8)
T_17 (in (bl_17 & 0x0F) *u (bh_16 + 0x01) : uint16)
	trait_primitive(uint16)
	trait_primitive(uint16)
T_18 (in 0x0004 : word16)
	trait_primitive(word16)
T_19 (in (bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004 : word16)
	trait_primitive(word16)
T_20 (in SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) : byte)
	trait_primitive(byte)
T_21 (in 0x0F : byte)
	trait_primitive(byte)
T_22 (in SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
	trait_primitive(byte)
T_23 (in bl_17 & 0xF0 | SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
	trait_primitive(byte)
T_24 (in 0x4DE1 : selector)
	trait_primitive(selector)
	trait_mem_array(0, 1, 4096, T_27)
T_25 (in 0x0000 : word16)
	trait_primitive(word16)
	trait_memsize(1)
	trait_mem(T_24:T_27, 0)
T_26 (in bx_15 + 0x0000 : word16)
	trait_primitive(word16)
T_27 (in Mem37[0x4DE1:bx_15 + 0x0000:byte] : byte)
	trait_primitive(byte)
	trait_equal(T_23)
T_28 (in 0x0001 : word16)
	trait_primitive(word16)
T_29 (in bx_15 - 0x0001 : word16)
	trait_primitive(word16)
T_30 (in SLICE(bx_15, byte, 8) : byte)
	trait_primitive(byte)
T_31 (in (byte) bx_15 : byte)
	trait_primitive(byte)
T_32 (in 0x0000 : word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_33 (in bx_15 >= 0x0000 : bool)
	trait_primitive(bool)
