// IntelIndexedAddressingMode
// Return size: 0
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:
	// succ:  l1
l1:
	SEQ(ds, Mem0[ds:0x0CA4:word16] + 0x000A)[Mem0[ds:0x1C0A:word16] * 0x004A] = 0xF8
	return
	// succ:  IntelIndexedAddressingMode_exit
IntelIndexedAddressingMode_exit:

globals_t (in globals : (ptr32 (struct "Globals")))
	trait_primitive((ptr32 (struct "Globals")))
T_2 (in 0xF8 : byte)
	trait_primitive(byte)
T_3 (in ds : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_mem(T_5, CA4)
	trait_primitive(word16)
	trait_mem(T_10, 1C0A)
	trait_mem_array(0, 74, 0, T_13)
T_4 (in 0x0CA4 : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_5, 0)
T_5 (in Mem0[ds:0x0CA4:word16] : word16)
	trait_primitive(word16)
T_6 (in 0x000A : word16)
	trait_primitive(word16)
T_7 (in Mem0[ds:0x0CA4:word16] + 0x000A : word16)
	trait_primitive(word16)
T_8 (in SEQ(ds, Mem0[ds:0x0CA4:word16] + 0x000A) : ptr32)
	trait_primitive(ptr32)
T_9 (in 0x1C0A : word16)
	trait_primitive(word16)
	trait_mem(T_3:T_10, 0)
T_10 (in Mem0[ds:0x1C0A:word16] : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_11 (in 0x004A : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_12 (in Mem0[ds:0x1C0A:word16] * 0x004A : word16)
	trait_primitive(ui16)
T_13 (in SEQ(ds, Mem0[ds:0x0CA4:word16] + 0x000A)[Mem0[ds:0x1C0A:word16] * 0x004A] : byte)
	trait_primitive(byte)
	trait_equal(T_2)
