// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem17[ds:0x64<16>:word16] = fn0C00_000F(0x64<16>)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000F
// Return size: 0
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	// succ:  l0C00_000F
l0C00_000F:
	branch wArg02 == 1<16> l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	ax_13 = wArg02 *s fn0C00_000F(wArg02 - 1<16>) (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_13 = 1<16>
	// succ:  l0C00_0029
l0C00_0029:
	return ax_13
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "seg0C00_t" 002B)
	T_2 (in seg0C00 : selector)
Eq_3: (segment (64 int16 w0064))
	T_3 (in ds : selector)
Eq_4: (fn int16 (int16))
	T_4 (in fn0C00_000F : segptr32)
	T_5 (in signature of fn0C00_000F : void)
	T_17 (in fn0C00_000F : segptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in seg0C00 : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment "seg0C00_t" 002B))
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (64 T_11 t0064)))
T_4: (in fn0C00_000F : segptr32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: (ptr32 (fn T_8 (T_7)))
T_5: (in signature of fn0C00_000F : void)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: 
T_6: (in wArg02 : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_7: (in 0x64<16> : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_8: (in fn0C00_000F(0x64<16>) : word16)
  Class: Eq_8
  DataType: int16
  OrigDataType: word16
T_9: (in 0x64<16> : word16)
  Class: Eq_9
  DataType: (memptr (ptr16 Eq_3) int16)
  OrigDataType: (memptr T_3 (struct (0 T_11 t0000)))
T_10: (in ds:0x64<16> : segptr32)
  Class: Eq_10
  DataType: segptr32
  OrigDataType: segptr32
T_11: (in Mem17[ds:0x64<16>:word16] : word16)
  Class: Eq_8
  DataType: int16
  OrigDataType: word16
T_12: (in ax : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: word16
T_13: (in 1<16> : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_14: (in wArg02 == 1<16> : bool)
  Class: Eq_14
  DataType: bool
  OrigDataType: bool
T_15: (in 1<16> : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: word16
T_16: (in ax_13 : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: int16
T_17: (in fn0C00_000F : segptr32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: (ptr32 (fn T_20 (T_19)))
T_18: (in 1<16> : word16)
  Class: Eq_18
  DataType: int16
  OrigDataType: int16
T_19: (in wArg02 - 1<16> : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_20: (in fn0C00_000F(wArg02 - 1<16>) : word16)
  Class: Eq_8
  DataType: int16
  OrigDataType: int16
T_21: (in wArg02 *s fn0C00_000F(wArg02 - 1<16>) : word16)
  Class: Eq_12
  DataType: int16
  OrigDataType: int16
