// RepeatedLoadsMock
void RepeatedLoadsMock()
RepeatedLoadsMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	x = Mem0[pfoo + 0x00000004:word32]
	x = Mem0[pfoo + 0x00000004:word32]
	// succ: 

// Equivalence classes ////////////
Eq_2: (struct (4 word32 dw0004))
	T_2 (in pfoo : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in pfoo : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (4 T_5 t0004)))
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in pfoo + 0x00000004 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[pfoo + 0x00000004:word32] : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in x : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_7: (in 0x00000004 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in pfoo + 0x00000004 : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[pfoo + 0x00000004:word32] : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
