// GlobalArray
void GlobalArray()
GlobalArray_entry:
	// succ:  l1
l1:
	(globals + 0x00003000<32>)[i * 0x00000004<32>]
GlobalArray_exit:

// Equivalence classes ////////////
Eq_1: (struct (3000 (arr word32) a3000))
	globals_t (in globals : (ptr32 (struct)))
Eq_3: (struct)
	T_3 (in globals + 0x00003000<32> : ptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct)))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct (3000 (arr T_8) a3000)))
T_2: (in 0x00003000<32> : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_3: (in globals + 0x00003000<32> : ptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct))
T_4: (in i : word32)
  Class: Eq_4
  DataType: ui32
  OrigDataType: ui32
T_5: (in 0x00000004<32> : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in i * 0x00000004<32> : word32)
  Class: Eq_6
  DataType: ui32
  OrigDataType: ui32
T_7: (in (globals + 0x00003000<32>)[i * 0x00000004<32>] : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8:
  Class: Eq_8
  DataType: word32
  OrigDataType: (struct 0004 (0 T_7 t0000))
