// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem9[ds:0x0064:word16]) = fn0C00_000F(0x0064)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_000F
word16 fn0C00_000F(word16 wArg00)
fn0C00_000F_entry:		// block 0, pred:
	// succ:  1
l0C00_000F:		// block 1, pred: 0
	word16 ax_18
	word16 ax_14 = wArg00 - 0x0001
	branch ax_14 == 0x0000 l0C00_0026
	// succ:  3 2
l0C00_0026:		// block 2, pred: 1
	ax_18 = 0x0001
	// succ:  4
l0C00_0018:		// block 3, pred: 1
	ax_18 = (word16) (wArg00 *s fn0C00_000F(ax_14)) (alias)
	// succ:  4
l0C00_0029:		// block 4, pred: 3 2
	return ax_18
	// succ:  5
fn0C00_000F_exit:		// block 5, pred: 4
	// succ: 

// Equivalence classes ////////////
Eq_2: (fn int16 (word16))
	T_2 (in fn0C00_000F : ptr32)
	T_3 (in signature of fn0C00_000F)
	T_19 (in fn0C00_000F : ptr32)
Eq_7: (segment (64 int16 w0064))
	T_7 (in ds : selector)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in fn0C00_000F : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_6 (T_5)))
T_3: (in signature of fn0C00_000F)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: 
T_4: (in wArg00 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in 0x0064 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_6: (in fn0C00_000F(0x0064) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_7: (in ds : selector)
  Class: Eq_7
  DataType: (ptr Eq_7)
  OrigDataType: (ptr (segment (64 T_9 t0064)))
T_8: (in 0x0064 : word16)
  Class: Eq_8
  DataType: (memptr (ptr Eq_7) int16)
  OrigDataType: (memptr T_7 (struct (0 T_9 t0000)))
T_9: (in Mem9[ds:0x0064:word16] : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: word16
T_10: (in ax : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in ax_18 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in ax_14 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_13: (in wArg00 : word16)
  Class: Eq_13
  DataType: int16
  OrigDataType: int16
T_14: (in 0x0001 : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in wArg00 - 0x0001 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_16: (in 0x0000 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_17: (in ax_14 == 0x0000 : bool)
  Class: Eq_17
  DataType: bool
  OrigDataType: bool
T_18: (in 0x0001 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_19: (in fn0C00_000F : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_20 (T_12)))
T_20: (in fn0C00_000F(ax_14) : word16)
  Class: Eq_6
  DataType: int16
  OrigDataType: int16
T_21: (in wArg00 *s fn0C00_000F(ax_14) : int32)
  Class: Eq_21
  DataType: int32
  OrigDataType: int32
T_22: (in (word16) (wArg00 *s fn0C00_000F(ax_14)) : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
