// Fn
// Return size: 0
define Fn
Fn_entry:
	// succ:  l000000000040EC30
l000000000040EC30:
	word64 rbx_18 = rdx - 1<64>
	branch rdx == 0<64> l000000000040EC69
	// succ:  l000000000040EC40 l000000000040EC69
l000000000040EC40:
	word64 rax_22 = 0x10000040<64>
	// succ:  l000000000040EC50
l000000000040EC50:
	Mem0[rdi + rbx_18:byte] = CONVERT(Mem0[rax_22 + 0<64>:word64][CONVERT(CONVERT(Mem0[rsi + rbx_18:byte], byte, word32), word32, word64) * 4<64>], word32, byte)
	rbx_18 = rbx_18 - 1<64>
	branch rbx_18 != 0xFFFFFFFFFFFFFFFF<64> l000000000040EC50
	// succ:  l000000000040EC69 l000000000040EC50
l000000000040EC69:
	return
	// succ:  Fn_exit
Fn_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000040 (ptr64 (arr word32)) ptr10000040))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in rbx_18 : word64)
  Class: Eq_2
  DataType: int64
  OrigDataType: int64
T_3: (in rdx : word64)
  Class: Eq_3
  DataType: word64
  OrigDataType: word64
T_4: (in 1<64> : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_5: (in rdx - 1<64> : word64)
  Class: Eq_2
  DataType: int64
  OrigDataType: word64
T_6: (in 0<64> : word64)
  Class: Eq_3
  DataType: word64
  OrigDataType: word64
T_7: (in rdx == 0<64> : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
T_8: (in rax_22 : word64)
  Class: Eq_8
  DataType: (ptr64 (ptr64 (arr word32)))
  OrigDataType: (ptr64 (struct (0 T_12 t0000)))
T_9: (in 0x10000040<64> : word64)
  Class: Eq_8
  DataType: (ptr64 (ptr64 (arr word32)))
  OrigDataType: word64
T_10: (in 0<64> : word64)
  Class: Eq_10
  DataType: word64
  OrigDataType: word64
T_11: (in rax_22 + 0<64> : word64)
  Class: Eq_11
  DataType: word64
  OrigDataType: word64
T_12: (in Mem0[rax_22 + 0<64>:word64] : word64)
  Class: Eq_12
  DataType: (ptr64 (arr word32))
  OrigDataType: (ptr64 (struct (0 T_30 t0000)))
T_13: (in rsi : word64)
  Class: Eq_13
  DataType: ptr64
  OrigDataType: ptr64
T_14: (in rsi + rbx_18 : word64)
  Class: Eq_14
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_15 t0000)))
T_15: (in Mem0[rsi + rbx_18:byte] : byte)
  Class: Eq_15
  DataType: byte
  OrigDataType: byte
T_16: (in CONVERT(Mem0[rsi + rbx_18:byte], byte, word32) : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in CONVERT(CONVERT(Mem0[rsi + rbx_18:byte], byte, word32), word32, word64) : word64)
  Class: Eq_17
  DataType: word64
  OrigDataType: word64
T_18: (in 4<64> : word64)
  Class: Eq_18
  DataType: ui64
  OrigDataType: ui64
T_19: (in CONVERT(CONVERT(Mem0[rsi + rbx_18:byte], byte, word32), word32, word64) * 4<64> : word64)
  Class: Eq_19
  DataType: ui64
  OrigDataType: ui64
T_20: (in Mem0[rax_22 + 0<64>:word64][CONVERT(CONVERT(Mem0[rsi + rbx_18:byte], byte, word32), word32, word64) * 4<64>] : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_21: (in CONVERT(Mem0[rax_22 + 0<64>:word64][CONVERT(CONVERT(Mem0[rsi + rbx_18:byte], byte, word32), word32, word64) * 4<64>], word32, byte) : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_22: (in rdi : word64)
  Class: Eq_22
  DataType: (ptr64 (arr byte))
  OrigDataType: (ptr64 (struct (0 T_32 t0000)))
T_23: (in rdi + rbx_18 : word64)
  Class: Eq_23
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_24 t0000)))
T_24: (in Mem0[rdi + rbx_18:byte] : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_25: (in 1<64> : word64)
  Class: Eq_25
  DataType: int64
  OrigDataType: int64
T_26: (in rbx_18 - 1<64> : word64)
  Class: Eq_2
  DataType: int64
  OrigDataType: int64
T_27: (in 0xFFFFFFFFFFFFFFFF<64> : word64)
  Class: Eq_2
  DataType: int64
  OrigDataType: word64
T_28: (in rbx_18 != 0xFFFFFFFFFFFFFFFF<64> : bool)
  Class: Eq_28
  DataType: bool
  OrigDataType: bool
T_29:
  Class: Eq_29
  DataType: word32
  OrigDataType: (struct 0004 (0 T_20 t0000))
T_30:
  Class: Eq_30
  DataType: (arr word32)
  OrigDataType: (arr T_29)
T_31:
  Class: Eq_31
  DataType: byte
  OrigDataType: (struct 0001 (0 T_24 t0000))
T_32:
  Class: Eq_32
  DataType: (arr byte)
  OrigDataType: (arr T_31)
