// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, word16 si, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	byte al_19
	Mem13[ds:bx + 4<16>:word32] = Mem0[ds:bx + 0<16>:word32] & 0xFF<32> | Mem0[ds:si + 0<16>:word32] & 0xFFFFFF00<32>
	byte al_14 = Mem13[ds:bx + 8<16>:byte]
	branch al_14 <u 0x30<8> l0C00_002A
	// succ:  l0C00_0021 l0C00_002A
l0C00_0021:
	branch al_14 >=u 0x3A<8> l0C00_002A
	// succ:  l0C00_0025 l0C00_002A
l0C00_0025:
	al_19 = 1<8>
	goto l0C00_002C
	// succ:  l0C00_002C
l0C00_002A:
	al_19 = 0<8>
	// succ:  l0C00_002C
l0C00_002C:
	Mem29[ds:bx + 9<16>:byte] = al_19
	word32 dx_ax_31 = Mem29[ds:bx + 0xC<16>:word16] *s Mem29[ds:bx + 0xA<16>:word16]
	Mem35[ds:bx + 0xE<16>:word16] = SLICE(dx_ax_31, word16, 0)
	Mem36[ds:bx + 0x10<16>:word16] = SLICE(dx_ax_31, word16, 16)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008) (9 byte b0009) (A int16 w000A) (C int16 w000C) (E word16 w000E) (10 word16 w0010))
	T_2 (in bx : word16)
Eq_4: (segment)
	T_4 (in ds : selector)
Eq_22: (struct (0 ui32 dw0000) (4 ui32 dw0004))
	T_22 (in bx + 8<16> : word16)
Eq_31: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008))
	T_31 (in bx + 9<16> : word16)
Eq_35: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008) (9 byte b0009))
	T_35 (in bx + 0xC<16> : word16)
Eq_38: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008) (9 byte b0009))
	T_38 (in bx + 0xA<16> : word16)
Eq_43: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008) (9 byte b0009) (A int16 w000A) (C int16 w000C))
	T_43 (in bx + 0xE<16> : word16)
Eq_47: (struct (0 ui32 dw0000) (4 ui32 dw0004) (8 cu8 b0008) (9 byte b0009) (A int16 w000A) (C int16 w000C) (E word16 w000E))
	T_47 (in bx + 0x10<16> : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in bx : word16)
  Class: Eq_2
  DataType: (memptr (ptr16 Eq_4) Eq_2)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008) (9 T_32 t0009) (A T_39 t000A) (C T_36 t000C) (E T_44 t000E) (10 T_48 t0010)))
T_3: (in si : word16)
  Class: Eq_3
  DataType: (memptr (ptr16 Eq_4) ui32)
  OrigDataType: (memptr T_4 (struct (0 T_13 t0000)))
T_4: (in ds : selector)
  Class: Eq_4
  DataType: (ptr16 Eq_4)
  OrigDataType: (ptr16 (segment))
T_5: (in al_19 : byte)
  Class: Eq_5
  DataType: byte
  OrigDataType: byte
T_6: (in 0<16> : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in bx + 0<16> : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in Mem0[ds:bx + 0<16>:word32] : word32)
  Class: Eq_8
  DataType: ui32
  OrigDataType: ui32
T_9: (in 0xFF<32> : word32)
  Class: Eq_9
  DataType: ui32
  OrigDataType: ui32
T_10: (in Mem0[ds:bx + 0<16>:word32] & 0xFF<32> : word32)
  Class: Eq_10
  DataType: ui32
  OrigDataType: ui32
T_11: (in 0<16> : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in si + 0<16> : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in Mem0[ds:si + 0<16>:word32] : word32)
  Class: Eq_13
  DataType: ui32
  OrigDataType: ui32
T_14: (in 0xFFFFFF00<32> : word32)
  Class: Eq_14
  DataType: ui32
  OrigDataType: ui32
T_15: (in Mem0[ds:si + 0<16>:word32] & 0xFFFFFF00<32> : word32)
  Class: Eq_15
  DataType: ui32
  OrigDataType: ui32
T_16: (in Mem0[ds:bx + 0<16>:word32] & 0xFF<32> | Mem0[ds:si + 0<16>:word32] & 0xFFFFFF00<32> : word32)
  Class: Eq_16
  DataType: ui32
  OrigDataType: ui32
T_17: (in 4<16> : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in bx + 4<16> : word16)
  Class: Eq_18
  DataType: (memptr (ptr16 Eq_4) ui32)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000)))
T_19: (in Mem13[ds:bx + 4<16>:word32] : word32)
  Class: Eq_16
  DataType: ui32
  OrigDataType: word32
T_20: (in al_14 : byte)
  Class: Eq_20
  DataType: cu8
  OrigDataType: cu8
T_21: (in 8<16> : word16)
  Class: Eq_21
  DataType: word16
  OrigDataType: word16
T_22: (in bx + 8<16> : word16)
  Class: Eq_22
  DataType: (memptr (ptr16 Eq_4) Eq_22)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004)))
T_23: (in Mem13[ds:bx + 8<16>:byte] : byte)
  Class: Eq_20
  DataType: cu8
  OrigDataType: byte
T_24: (in 0x30<8> : byte)
  Class: Eq_20
  DataType: cu8
  OrigDataType: cu8
T_25: (in al_14 <u 0x30<8> : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26: (in 0<8> : byte)
  Class: Eq_5
  DataType: byte
  OrigDataType: byte
T_27: (in 0x3A<8> : byte)
  Class: Eq_20
  DataType: cu8
  OrigDataType: cu8
T_28: (in al_14 >=u 0x3A<8> : bool)
  Class: Eq_28
  DataType: bool
  OrigDataType: bool
T_29: (in 1<8> : byte)
  Class: Eq_5
  DataType: byte
  OrigDataType: byte
T_30: (in 9<16> : word16)
  Class: Eq_30
  DataType: word16
  OrigDataType: word16
T_31: (in bx + 9<16> : word16)
  Class: Eq_31
  DataType: (memptr (ptr16 Eq_4) Eq_31)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008)))
T_32: (in Mem29[ds:bx + 9<16>:byte] : byte)
  Class: Eq_5
  DataType: byte
  OrigDataType: byte
T_33: (in dx_ax_31 : word32)
  Class: Eq_33
  DataType: int32
  OrigDataType: int32
T_34: (in 0xC<16> : word16)
  Class: Eq_34
  DataType: word16
  OrigDataType: word16
T_35: (in bx + 0xC<16> : word16)
  Class: Eq_35
  DataType: (memptr (ptr16 Eq_4) Eq_35)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008) (9 T_32 t0009)))
T_36: (in Mem29[ds:bx + 0xC<16>:word16] : word16)
  Class: Eq_36
  DataType: int16
  OrigDataType: int16
T_37: (in 0xA<16> : word16)
  Class: Eq_37
  DataType: word16
  OrigDataType: word16
T_38: (in bx + 0xA<16> : word16)
  Class: Eq_38
  DataType: (memptr (ptr16 Eq_4) Eq_38)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008) (9 T_32 t0009)))
T_39: (in Mem29[ds:bx + 0xA<16>:word16] : word16)
  Class: Eq_39
  DataType: int16
  OrigDataType: int16
T_40: (in Mem29[ds:bx + 0xC<16>:word16] *s Mem29[ds:bx + 0xA<16>:word16] : int32)
  Class: Eq_33
  DataType: int32
  OrigDataType: int32
T_41: (in SLICE(dx_ax_31, word16, 0) : word16)
  Class: Eq_41
  DataType: word16
  OrigDataType: word16
T_42: (in 0xE<16> : word16)
  Class: Eq_42
  DataType: word16
  OrigDataType: word16
T_43: (in bx + 0xE<16> : word16)
  Class: Eq_43
  DataType: (memptr (ptr16 Eq_4) Eq_43)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008) (9 T_32 t0009) (A T_39 t000A) (C T_36 t000C)))
T_44: (in Mem35[ds:bx + 0xE<16>:word16] : word16)
  Class: Eq_41
  DataType: word16
  OrigDataType: word16
T_45: (in SLICE(dx_ax_31, word16, 16) : word16)
  Class: Eq_45
  DataType: word16
  OrigDataType: word16
T_46: (in 0x10<16> : word16)
  Class: Eq_46
  DataType: word16
  OrigDataType: word16
T_47: (in bx + 0x10<16> : word16)
  Class: Eq_47
  DataType: (memptr (ptr16 Eq_4) Eq_47)
  OrigDataType: (memptr T_4 (struct (0 T_8 t0000) (4 T_19 t0004) (8 T_23 t0008) (9 T_32 t0009) (A T_39 t000A) (C T_36 t000C) (E T_44 t000E)))
T_48: (in Mem36[ds:bx + 0x10<16>:word16] : word16)
  Class: Eq_45
  DataType: word16
  OrigDataType: word16
