// SelfArray
// Return size: 0
define SelfArray
SelfArray_entry:
	// succ:  l1
l1:
	a4[d0 * 4<32>] = a4
	return
	// succ:  SelfArray_exit
SelfArray_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (struct (0 (arr Eq_7) a0000))
	T_2 (in a4 : word32)
	T_6 (in a4[d0 * 4<32>] : word32)
Eq_7: (struct 0004 (0 (ptr32 Eq_2) ptr0000))
	T_7
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in a4 : word32)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: (ptr32 (struct (0 (arr T_7) a0000)))
T_3: (in d0 : word32)
  Class: Eq_3
  DataType: ui32
  OrigDataType: ui32
T_4: (in 4<32> : ui32)
  Class: Eq_4
  DataType: ui32
  OrigDataType: ui32
T_5: (in d0 * 4<32> : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in a4[d0 * 4<32>] : word32)
  Class: Eq_2
  DataType: (ptr32 Eq_2)
  OrigDataType: word32
T_7:
  Class: Eq_7
  DataType: Eq_7
  OrigDataType: (struct 0004 (0 T_6 t0000))
T_8:
  Class: Eq_8
  DataType: (arr Eq_7)
  OrigDataType: (arr T_7)
