// TreeFindMock
// Return size: 0
define TreeFindMock
TreeFindMock_entry:
	// succ:  l0
l0:
	r63 = fp
	// succ:  l0_seek
l0_seek:
	branch t == 0<32> l5_found
	// succ:  l1 l5_found
l1:
	vv = Mem0[t + 0<32>:word32]
	branch v == vv l5_found
	// succ:  l2 l5_found
l2:
	branch v < vv l4_lt
	// succ:  l3 l4_lt
l3:
	t = Mem0[t + 8<32>:word32]
	goto l0_seek
	// succ:  l0_seek
l4_lt:
	t = Mem0[t + 4<32>:word32]
	// succ:  l5_found
l5_found:
	return t
	// succ:  TreeFindMock_exit
TreeFindMock_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_4: (struct (0 int32 dw0000) (4 (ptr32 Eq_4) ptr0004) (8 (ptr32 Eq_4) ptr0008))
	T_4 (in t : word32)
	T_5 (in 0<32> : word32)
	T_16 (in Mem0[t + 4<32>:word32] : word32)
	T_19 (in Mem0[t + 8<32>:word32] : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fp : ptr32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_3: (in r63 : word32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_4: (in t : word32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: (ptr32 (struct (0 T_9 t0000) (4 T_16 t0004) (8 T_19 t0008)))
T_5: (in 0<32> : word32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: word32
T_6: (in t == 0<32> : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in 0<32> : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in t + 0<32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in Mem0[t + 0<32>:word32] : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: word32
T_10: (in vv : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_11: (in v : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_12: (in v == vv : bool)
  Class: Eq_12
  DataType: bool
  OrigDataType: bool
T_13: (in v < vv : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in 4<32> : word32)
  Class: Eq_14
  DataType: word32
  OrigDataType: word32
T_15: (in t + 4<32> : word32)
  Class: Eq_15
  DataType: ptr32
  OrigDataType: ptr32
T_16: (in Mem0[t + 4<32>:word32] : word32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: word32
T_17: (in 8<32> : word32)
  Class: Eq_17
  DataType: word32
  OrigDataType: word32
T_18: (in t + 8<32> : word32)
  Class: Eq_18
  DataType: ptr32
  OrigDataType: ptr32
T_19: (in Mem0[t + 8<32>:word32] : word32)
  Class: Eq_4
  DataType: (ptr32 Eq_4)
  OrigDataType: word32
