// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_000C(ds)
	fn0C00_0015(ds)
	Mem7[ds:0x100<16>:word16] = 0<16>
	// succ:  l0C00_0006_thunk_fn0C00_000C
l0C00_0006_thunk_fn0C00_000C:
	fn0C00_000C(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000C
// Return size: 0
void fn0C00_000C(selector ds)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	Mem7[ds:0x302<16>:word16] = Mem0[ds:0x300<16>:word16]
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

// fn0C00_0015
// Return size: 0
void fn0C00_0015(selector ds)
fn0C00_0015_entry:
	// succ:  l0C00_0015
l0C00_0015:
	Mem7[ds:0x202<16>:word16] = Mem0[ds:0x200<16>:word16]
	return
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment "seg0C00_t" 001E)
	T_2 (in seg0C00 : selector)
Eq_3: (segment (100 word16 w0100) (200 word16 w0200) (202 word16 w0202) (300 word16 w0300) (302 word16 w0302))
	T_3 (in ds : selector)
	T_6 (in ds : selector)
	T_10 (in ds : selector)
Eq_4: (union (segptr32 u0) ((ptr32 (fn void ((ptr16 Eq_3)))) u1))
	T_4 (in fn0C00_000C : segptr32)
	T_5 (in signature of fn0C00_000C : void)
	T_16 (in fn0C00_000C : segptr32)
Eq_8: (union (segptr32 u0) ((ptr32 (fn void ((ptr16 Eq_3)))) u1))
	T_8 (in fn0C00_0015 : segptr32)
	T_9 (in signature of fn0C00_0015 : void)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in seg0C00 : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment "seg0C00_t" 001E))
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (100 T_15 t0100)))
T_4: (in fn0C00_000C : segptr32)
  Class: Eq_4
  DataType: Eq_4
  OrigDataType: (union (segptr32 u0) ((ptr32 (fn T_7 (T_3))) u1))
T_5: (in signature of fn0C00_000C : void)
  Class: Eq_4
  DataType: Eq_4
  OrigDataType: 
T_6: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (300 word16 w0300) (302 T_23 t0302)))
T_7: (in fn0C00_000C(ds) : void)
  Class: Eq_7
  DataType: void
  OrigDataType: void
T_8: (in fn0C00_0015 : segptr32)
  Class: Eq_8
  DataType: Eq_8
  OrigDataType: (union (segptr32 u0) ((ptr32 (fn void ((ptr16 Eq_3)))) u1))
T_9: (in signature of fn0C00_0015 : void)
  Class: Eq_8
  DataType: Eq_8
  OrigDataType: 
T_10: (in ds : selector)
  Class: Eq_3
  DataType: (ptr16 Eq_3)
  OrigDataType: (ptr16 (segment (200 T_26 t0200) (202 T_29 t0202)))
T_11: (in fn0C00_0015(ds) : void)
  Class: Eq_11
  DataType: void
  OrigDataType: void
T_12: (in 0<16> : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in 0x100<16> : word16)
  Class: Eq_13
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_15 t0000)))
T_14: (in ds:0x100<16> : segptr32)
  Class: Eq_14
  DataType: segptr32
  OrigDataType: segptr32
T_15: (in Mem7[ds:0x100<16>:word16] : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_16: (in fn0C00_000C : segptr32)
  Class: Eq_4
  DataType: Eq_4
  OrigDataType: (union (segptr32 u0) ((ptr32 (fn T_17 (T_3))) u1))
T_17: (in fn0C00_000C(ds) : void)
  Class: Eq_7
  DataType: void
  OrigDataType: void
T_18: (in 0x300<16> : word16)
  Class: Eq_18
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_6 (struct (0 T_20 t0000)))
T_19: (in ds:0x300<16> : segptr32)
  Class: Eq_19
  DataType: segptr32
  OrigDataType: segptr32
T_20: (in Mem0[ds:0x300<16>:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21: (in 0x302<16> : word16)
  Class: Eq_21
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_6 (struct (0 T_23 t0000)))
T_22: (in ds:0x302<16> : segptr32)
  Class: Eq_22
  DataType: segptr32
  OrigDataType: segptr32
T_23: (in Mem7[ds:0x302<16>:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_24: (in 0x200<16> : word16)
  Class: Eq_24
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_10 (struct (0 T_26 t0000)))
T_25: (in ds:0x200<16> : segptr32)
  Class: Eq_25
  DataType: segptr32
  OrigDataType: segptr32
T_26: (in Mem0[ds:0x200<16>:word16] : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
T_27: (in 0x202<16> : word16)
  Class: Eq_27
  DataType: (memptr (ptr16 Eq_3) word16)
  OrigDataType: (memptr T_10 (struct (0 T_29 t0000)))
T_28: (in ds:0x202<16> : segptr32)
  Class: Eq_28
  DataType: segptr32
  OrigDataType: segptr32
T_29: (in Mem7[ds:0x202<16>:word16] : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
