// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem12[ds:0x0064:word16] = fn0C00_000B(0x0005)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_000B
// Return size: 0
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:
	// succ:  l0C00_000B
l0C00_000B:
	word16 ax_11
	branch cx <= 0x0001 l0C00_001C
	// succ:  l0C00_0011 l0C00_001C
l0C00_0011:
	ax_11 = SLICE(cx *s fn0C00_000B(cx - 0x0001), word16, 0) (alias)
	goto l0C00_001F
	// succ:  l0C00_001F
l0C00_001C:
	ax_11 = 0x0001
	// succ:  l0C00_001F
l0C00_001F:
	return ax_11
	// succ:  fn0C00_000B_exit
fn0C00_000B_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_2: (segment (64 int16 w0064))
	T_2 (in ds : selector)
Eq_3: (fn int16 (int16))
	T_3 (in fn0C00_000B : segptr32)
	T_4 (in signature of fn0C00_000B : void)
	T_15 (in fn0C00_000B : segptr32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (64 T_9 t0064)))
T_3: (in fn0C00_000B : segptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_7 (T_6)))
T_4: (in signature of fn0C00_000B : void)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: 
T_5: (in cx : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_6: (in 0x0005 : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: word16
T_7: (in fn0C00_000B(0x0005) : word16)
  Class: Eq_7
  DataType: int16
  OrigDataType: word16
T_8: (in 0x0064 : word16)
  Class: Eq_8
  DataType: (memptr (ptr16 Eq_2) int16)
  OrigDataType: (memptr T_2 (struct (0 T_9 t0000)))
T_9: (in Mem12[ds:0x0064:word16] : word16)
  Class: Eq_7
  DataType: int16
  OrigDataType: word16
T_10: (in ax : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in ax_11 : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_12: (in 0x0001 : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: ci16
T_13: (in cx <= 0x0001 : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in 0x0001 : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_15: (in fn0C00_000B : segptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_18 (T_17)))
T_16: (in 0x0001 : word16)
  Class: Eq_16
  DataType: int16
  OrigDataType: int16
T_17: (in cx - 0x0001 : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: ci16
T_18: (in fn0C00_000B(cx - 0x0001) : word16)
  Class: Eq_7
  DataType: int16
  OrigDataType: int16
T_19: (in cx *s fn0C00_000B(cx - 0x0001) : int32)
  Class: Eq_19
  DataType: int32
  OrigDataType: int32
T_20: (in SLICE(cx *s fn0C00_000B(cx - 0x0001), word16, 0) : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
