// FnPointerMock
void FnPointerMock()
FnPointerMock_entry:
	// succ:  l1
l1:
	pfn = 0x01213130
	Mem0[0x10000000:word32] = pfn
	call Mem0[0x10000000:word32] (retsize: 0;)
FnPointerMock_exit:

// Equivalence classes ////////////
Eq_1: (struct (10000000 (ptr code) ptr10000000))
	globals_t (in globals : (ptr (struct)))
// Type Variables ////////////
globals_t: (in globals : (ptr (struct)))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (10000000 T_2 t10000000)))
T_2: (in 0x01213130 : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_3: (in pfn : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_4: (in 0x10000000 : word32)
  Class: Eq_4
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_5: (in Mem0[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: word32
T_6: (in 0x10000000 : word32)
  Class: Eq_6
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem0[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr code)
  OrigDataType: (ptr code)
