// ProcedureBuilder
// Return size: 0
void ProcedureBuilder()
ProcedureBuilder_entry:
	// succ:  l1
l1:
	Mem3[0x00003120:word32] = 0x00000000
	Mem4[0x00003120:word32] = Mem3[0x00003120:word32] + 0x00000001
	return
	// succ:  ProcedureBuilder_exit
ProcedureBuilder_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (3120 word32 dw3120))
	globals_t (in globals : (ptr (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in 0x00000000 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in 0x00003120 : word32)
  Class: Eq_3
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_4 t0000)))
T_4: (in Mem3[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_5: (in 0x00003120 : word32)
  Class: Eq_5
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_6 t0000)))
T_6: (in Mem3[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_7: (in 0x00000001 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem3[0x00003120:word32] + 0x00000001 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_9: (in 0x00003120 : word32)
  Class: Eq_9
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_10 t0000)))
T_10: (in Mem4[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
