// FnPointerFragment
// Return size: 0
define FnPointerFragment
FnPointerFragment_entry:
	// succ:  l1
l1:
	r63 = fp
	pfn = 0x1213130<32>
	Mem0[0x10000000<32>:word32] = pfn
	call Mem0[0x10000000<32>:word32] (retsize: 4;)
	return
	// succ:  FnPointerFragment_exit
FnPointerFragment_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals" (1213130 code t1213130) (10000000 (ptr32 code) ptr10000000))
	globals_t (in globals : (ptr32 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fp : ptr32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_3: (in r63 : word32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_4: (in 0x1213130<32> : word32)
  Class: Eq_4
  DataType: (ptr32 code)
  OrigDataType: word32
T_5: (in pfn : word32)
  Class: Eq_4
  DataType: (ptr32 code)
  OrigDataType: word32
T_6: (in 0x10000000<32> : word32)
  Class: Eq_6
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_7 t0000)))
T_7: (in Mem0[0x10000000<32>:word32] : word32)
  Class: Eq_4
  DataType: (ptr32 code)
  OrigDataType: word32
T_8: (in 0x10000000<32> : word32)
  Class: Eq_8
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_9 t0000)))
T_9: (in Mem0[0x10000000<32>:word32] : word32)
  Class: Eq_4
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
