// SegmentedPointerProc
// Return size: 0
void SegmentedPointerProc()
SegmentedPointerProc_entry:
	// succ:  l1
l1:
	Mem0[ds:0x0300:word16] = 0x1234
	Mem0[ds:0x0302:word16] = 0x5550
	es_bx = Mem0[ds:0x0300:segptr32]
	Mem0[ds:0x0304:word16] = Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 0x0004:word16]
SegmentedPointerProc_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr (struct "Globals")))
Eq_3: (segment (300 segptr32 ptr0300) (302 word16 w0302) (304 word16 w0304))
	T_3 (in ds : selector)
Eq_12: (segment)
	T_12 (in SLICE(es_bx, selector, 16) : selector)
Eq_13: (struct (4 word16 w0004))
	T_13 (in SLICE(es_bx, word16, 0) : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in 0x1234 : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (segment (300 T_2 t0300) (302 T_8 t0302) (304 T_18 t0304)))
T_4: (in 0x0300 : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_3) segptr32)
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5: (in Mem0[ds:0x0300:word16] : word16)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: word16
T_6: (in 0x5550 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0x0302 : word16)
  Class: Eq_7
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_8: (in Mem0[ds:0x0302:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in 0x0300 : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_3) segptr32)
  OrigDataType: (memptr T_3 (struct (0 T_10 t0000)))
T_10: (in Mem0[ds:0x0300:segptr32] : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_11: (in es_bx : segptr32)
  Class: Eq_2
  DataType: segptr32
  OrigDataType: segptr32
T_12: (in SLICE(es_bx, selector, 16) : selector)
  Class: Eq_12
  DataType: (ptr Eq_12)
  OrigDataType: (ptr (segment))
T_13: (in SLICE(es_bx, word16, 0) : word16)
  Class: Eq_13
  DataType: (memptr (ptr Eq_12) Eq_13)
  OrigDataType: (memptr T_12 (struct (4 T_16 t0004)))
T_14: (in 0x0004 : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in SLICE(es_bx, word16, 0) + 0x0004 : word16)
  Class: Eq_15
  DataType: (memptr (ptr Eq_12) word16)
  OrigDataType: (memptr T_12 T_16)
T_16: (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 0x0004:word16] : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in 0x0304 : word16)
  Class: Eq_17
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_18 t0000)))
T_18: (in Mem0[ds:0x0304:word16] : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
