// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0010(ds, 0x0300, 0x0320)
	fn0C00_0037(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0010
// Return size: 0
void fn0C00_0010(selector ds, word16 wArg02, word16 wArg04)
fn0C00_0010_entry:
	// succ:  l0C00_0010
l0C00_0010:
	real64 rLoc1_10 = Mem0[ds:wArg02 + 0x0000:real64]
	real64 rLoc2_12 = Mem0[ds:wArg02 + 0x0008:real64]
	real64 rLoc2_15 = Mem0[ds:wArg02 + 0x0010:real64]
	Mem20[ds:wArg04 + 0x0000:real64] = rLoc1_10 * rLoc1_10 + rLoc2_12 * rLoc2_12 + rLoc2_15 * rLoc2_15
	Mem22[ds:wArg04 + 0x0028:real64] = (real64) Mem20[ds:wArg04 + 0x0020:int16]
	return
	// succ:  fn0C00_0010_exit
fn0C00_0010_exit:

// fn0C00_0037
// Return size: 0
void fn0C00_0037(selector ds)
fn0C00_0037_entry:
	// succ:  l0C00_0037
l0C00_0037:
	Mem3[ds:0x0400:real64] = 0.0
	Mem6[ds:0x0408:int32] = (int32) 1.0
	return
	// succ:  fn0C00_0037_exit
fn0C00_0037_exit:

// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (segment (400 real64 r0400) (408 int32 dw0408))
	T_2 (in ds : selector)
	T_5 (in ds : selector)
	T_13 (in ds : selector)
Eq_3: (fn void ((ptr Eq_2), word16, word16))
	T_3 (in fn0C00_0010 : ptr32)
	T_4 (in signature of fn0C00_0010 : void)
Eq_11: (fn void ((ptr Eq_2)))
	T_11 (in fn0C00_0037 : ptr32)
	T_12 (in signature of fn0C00_0037 : void)
Eq_16: (struct (0 real64 r0000) (8 real64 r0008) (10 real64 r0010))
	T_16 (in wArg02 : word16)
Eq_26: (struct (0 real64 r0000) (8 real64 r0008))
	T_26 (in wArg02 + 0x0010 : word16)
Eq_33: (struct (0 real64 r0000) (20 int16 w0020) (28 real64 r0028))
	T_33 (in wArg04 : word16)
Eq_42: (struct (0 real64 r0000) (20 int16 w0020))
	T_42 (in wArg04 + 0x0028 : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment))
T_3: (in fn0C00_0010 : ptr32)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (fn T_10 (T_2, T_8, T_9)))
T_4: (in signature of fn0C00_0010 : void)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: 
T_5: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment))
T_6: (in wArg02 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in wArg04 : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in 0x0300 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in 0x0320 : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_10: (in fn0C00_0010(ds, 0x0300, 0x0320) : void)
  Class: Eq_10
  DataType: void
  OrigDataType: void
T_11: (in fn0C00_0037 : ptr32)
  Class: Eq_11
  DataType: (ptr Eq_11)
  OrigDataType: (ptr (fn T_14 (T_2)))
T_12: (in signature of fn0C00_0037 : void)
  Class: Eq_11
  DataType: (ptr Eq_11)
  OrigDataType: 
T_13: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment (400 real64 r0400) (408 T_50 t0408)))
T_14: (in fn0C00_0037(ds) : void)
  Class: Eq_14
  DataType: void
  OrigDataType: void
T_15: (in rLoc1_10 : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_16: (in wArg02 : word16)
  Class: Eq_16
  DataType: (memptr (ptr Eq_2) Eq_16)
  OrigDataType: (memptr T_5 (struct (0 T_19 t0000) (8 T_23 t0008) (10 T_27 t0010)))
T_17: (in 0x0000 : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in wArg02 + 0x0000 : word16)
  Class: Eq_18
  DataType: word16
  OrigDataType: word16
T_19: (in Mem0[ds:wArg02 + 0x0000:real64] : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_20: (in rLoc2_12 : real64)
  Class: Eq_20
  DataType: real64
  OrigDataType: real64
T_21: (in 0x0008 : word16)
  Class: Eq_21
  DataType: word16
  OrigDataType: word16
T_22: (in wArg02 + 0x0008 : word16)
  Class: Eq_22
  DataType: (memptr (ptr Eq_2) real64)
  OrigDataType: (memptr T_5 (struct (0 T_19 t0000)))
T_23: (in Mem0[ds:wArg02 + 0x0008:real64] : real64)
  Class: Eq_20
  DataType: real64
  OrigDataType: real64
T_24: (in rLoc2_15 : real64)
  Class: Eq_24
  DataType: real64
  OrigDataType: real64
T_25: (in 0x0010 : word16)
  Class: Eq_25
  DataType: word16
  OrigDataType: word16
T_26: (in wArg02 + 0x0010 : word16)
  Class: Eq_26
  DataType: (memptr (ptr Eq_2) Eq_26)
  OrigDataType: (memptr T_5 (struct (0 T_19 t0000) (8 T_23 t0008)))
T_27: (in Mem0[ds:wArg02 + 0x0010:real64] : real64)
  Class: Eq_24
  DataType: real64
  OrigDataType: real64
T_28: (in rLoc1_10 * rLoc1_10 : real64)
  Class: Eq_28
  DataType: real64
  OrigDataType: real64
T_29: (in rLoc2_12 * rLoc2_12 : real64)
  Class: Eq_29
  DataType: real64
  OrigDataType: real64
T_30: (in rLoc1_10 * rLoc1_10 + rLoc2_12 * rLoc2_12 : real64)
  Class: Eq_30
  DataType: real64
  OrigDataType: real64
T_31: (in rLoc2_15 * rLoc2_15 : real64)
  Class: Eq_31
  DataType: real64
  OrigDataType: real64
T_32: (in rLoc1_10 * rLoc1_10 + rLoc2_12 * rLoc2_12 + rLoc2_15 * rLoc2_15 : real64)
  Class: Eq_32
  DataType: real64
  OrigDataType: real64
T_33: (in wArg04 : word16)
  Class: Eq_33
  DataType: (memptr (ptr Eq_2) Eq_33)
  OrigDataType: (memptr T_5 (struct (0 T_36 t0000) (20 T_39 t0020) (28 T_43 t0028)))
T_34: (in 0x0000 : word16)
  Class: Eq_34
  DataType: word16
  OrigDataType: word16
T_35: (in wArg04 + 0x0000 : word16)
  Class: Eq_35
  DataType: word16
  OrigDataType: word16
T_36: (in Mem20[ds:wArg04 + 0x0000:real64] : real64)
  Class: Eq_32
  DataType: real64
  OrigDataType: real64
T_37: (in 0x0020 : word16)
  Class: Eq_37
  DataType: word16
  OrigDataType: word16
T_38: (in wArg04 + 0x0020 : word16)
  Class: Eq_38
  DataType: (memptr (ptr Eq_2) real64)
  OrigDataType: (memptr T_5 (struct (0 T_36 t0000)))
T_39: (in Mem20[ds:wArg04 + 0x0020:int16] : int16)
  Class: Eq_39
  DataType: int16
  OrigDataType: int16
T_40: (in (real64) Mem20[ds:wArg04 + 0x0020:int16] : real64)
  Class: Eq_40
  DataType: real64
  OrigDataType: real64
T_41: (in 0x0028 : word16)
  Class: Eq_41
  DataType: word16
  OrigDataType: word16
T_42: (in wArg04 + 0x0028 : word16)
  Class: Eq_42
  DataType: (memptr (ptr Eq_2) Eq_42)
  OrigDataType: (memptr T_5 (struct (0 T_36 t0000) (20 T_39 t0020)))
T_43: (in Mem22[ds:wArg04 + 0x0028:real64] : real64)
  Class: Eq_40
  DataType: real64
  OrigDataType: real64
T_44: (in 0.0 : real64)
  Class: Eq_44
  DataType: real64
  OrigDataType: real64
T_45: (in 0x0400 : word16)
  Class: Eq_45
  DataType: (memptr (ptr Eq_2) real64)
  OrigDataType: (memptr T_13 (struct (0 T_46 t0000)))
T_46: (in Mem3[ds:0x0400:real64] : real64)
  Class: Eq_44
  DataType: real64
  OrigDataType: real64
T_47: (in 1.0 : real64)
  Class: Eq_47
  DataType: real64
  OrigDataType: real64
T_48: (in (int32) 1.0 : int32)
  Class: Eq_48
  DataType: int32
  OrigDataType: int32
T_49: (in 0x0408 : word16)
  Class: Eq_49
  DataType: (memptr (ptr Eq_2) int32)
  OrigDataType: (memptr T_13 (struct (0 T_50 t0000)))
T_50: (in Mem6[ds:0x0408:int32] : int32)
  Class: Eq_48
  DataType: int32
  OrigDataType: int32
