// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_36 = 0xFFF<16>
	// succ:  l0C00_000C
l0C00_000C:
	byte bl_10 = SLICE(bx_39, byte, 0)
	Mem23[0x4DE1<16>:bx_39 + 0<16>:byte] = bl_10 & 0xF0<8> | SLICE((bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8>
	bx_36 = bx_39 - 1<16> (alias)
	bx_39 = bx_36
	branch bx_39 >= 1<16> l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct (4DE10 T_24 t4DE10)))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fn0C00_0004 : segptr32)
  Class: Eq_2
  DataType: (ptr32 (fn T_4 ()))
  OrigDataType: (ptr32 (fn T_4 ()))
T_3: (in signature of fn0C00_0004 : void)
  Class: Eq_2
  DataType: 
  OrigDataType: 
T_4: (in fn0C00_0004() : void)
  Class: Eq_4
  DataType: void
  OrigDataType: void
T_5: (in bx_36 : word16)
  Class: Eq_5
  DataType: (union (ci16 u0) ((memptr T_24 (struct (0 T_27 t0000))) u1))
  OrigDataType: (union (cui16 u0) ((memptr T_24 (struct (0 T_27 t0000))) u1))
T_6: (in 0xFFF<16> : cui16)
  Class: Eq_5
  DataType: cui16
  OrigDataType: cui16
T_7: (in bl_10 : byte)
  Class: Eq_7
  DataType: byte
  OrigDataType: byte
T_8: (in bx_39 : word16)
  Class: Eq_5
  DataType: (union (ci16 u0) ((memptr T_24 (struct (0 T_27 t0000))) u1))
  OrigDataType: (union (ci16 u0) ((memptr T_24 (struct (0 T_27 t0000))) u1))
T_9: (in SLICE(bx_39, byte, 0) : byte)
  Class: Eq_7
  DataType: byte
  OrigDataType: byte
T_10: (in 0xF0<8> : byte)
  Class: Eq_10
  DataType: byte
  OrigDataType: byte
T_11: (in bl_10 & 0xF0<8> : byte)
  Class: Eq_11
  DataType: byte
  OrigDataType: byte
T_12: (in 0xF<8> : byte)
  Class: Eq_12
  DataType: byte
  OrigDataType: byte
T_13: (in bl_10 & 0xF<8> : byte)
  Class: Eq_13
  DataType: bu8
  OrigDataType: bu8
T_14: (in SLICE(bx_39, byte, 8) : byte)
  Class: Eq_14
  DataType: bu8
  OrigDataType: bu8
T_15: (in 1<8> : byte)
  Class: Eq_15
  DataType: bu8
  OrigDataType: bu8
T_16: (in SLICE(bx_39, byte, 8) + 1<8> : byte)
  Class: Eq_16
  DataType: bu8
  OrigDataType: bu8
T_17: (in (bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) : uint16)
  Class: Eq_17
  DataType: uint16
  OrigDataType: uint16
T_18: (in 4<16> : word16)
  Class: Eq_18
  DataType: word16
  OrigDataType: word16
T_19: (in (bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) << 4<16> : word16)
  Class: Eq_19
  DataType: ui16
  OrigDataType: ui16
T_20: (in SLICE((bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_21: (in 0xF<8> : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_22: (in SLICE((bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8> : byte)
  Class: Eq_22
  DataType: byte
  OrigDataType: byte
T_23: (in bl_10 & 0xF0<8> | SLICE((bl_10 & 0xF<8>) *u (SLICE(bx_39, byte, 8) + 1<8>) << 4<16>, byte, 8) & 0xF<8> : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_24: (in 0x4DE1<16> : selector)
  Class: Eq_24
  DataType: (ptr16 (segment))
  OrigDataType: (ptr16 (segment))
T_25: (in 0<16> : word16)
  Class: Eq_25
  DataType: word16
  OrigDataType: word16
T_26: (in bx_39 + 0<16> : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
T_27: (in Mem23[0x4DE1<16>:bx_39 + 0<16>:byte] : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_28: (in 1<16> : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_29: (in bx_39 - 1<16> : word16)
  Class: Eq_5
  DataType: (memptr T_24 (struct (0 T_27 t0000)))
  OrigDataType: (memptr T_24 (struct (0 T_27 t0000)))
T_30: (in bx_39 >= 1<16> : bool)
  Class: Eq_30
  DataType: bool
  OrigDataType: bool
