// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	Mem0[0x00123400:word32] = Mem0[0x00123400:word32] + 0x00000001
proc1_exit:

// Equivalence classes ////////////
Eq_1: (ptr (struct "Globals"))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (ptr (struct (0 Eq_3 t0000)))
	T_2 (in 0x00123400 : word32)
Eq_3: word32
	T_3 (in Mem0[0x00123400:word32] : word32)
	T_5 (in Mem0[0x00123400:word32] + 0x00000001 : word32)
	T_7 (in Mem0[0x00123400:word32] : word32)
Eq_4: word32
	T_4 (in 0x00000001 : word32)
Eq_6: (ptr (struct (0 Eq_3 t0000)))
	T_6 (in 0x00123400 : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: (ptr (struct "Globals"))
T_2: (in 0x00123400 : word32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: (ptr (struct (0 T_3 t0000)))
T_3: (in Mem0[0x00123400:word32] : word32)
  Class: Eq_3
  DataType: Eq_3
  OrigDataType: word32
T_4: (in 0x00000001 : word32)
  Class: Eq_4
  DataType: Eq_4
  OrigDataType: word32
T_5: (in Mem0[0x00123400:word32] + 0x00000001 : word32)
  Class: Eq_3
  DataType: Eq_3
  OrigDataType: word32
T_6: (in 0x00123400 : word32)
  Class: Eq_6
  DataType: Eq_6
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem0[0x00123400:word32] : word32)
  Class: Eq_3
  DataType: Eq_3
  OrigDataType: word32
