// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 cx, word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0007(cx, ds)
	fn0C00_001D(bx, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0007
// Return size: 0
void fn0C00_0007(word16 cx, selector ds)
fn0C00_0007_entry:
	// succ:  l0C00_0007
l0C00_0007:
	word16 di_21 = 0x5388
	// succ:  l0C00_000A
l0C00_000A:
	fn0C00_003D(0x2D, Mem7[ds:di_21 + 0x0000:word16], ds)
	di_21 = di_21 + 0x0002
	cx = cx_35 - 0x0001
	cx_35 = cx
	branch cx_35 != 0x0001 l0C00_000A
	// succ:  l0C00_001C l0C00_000A
l0C00_001C:
	return
	// succ:  fn0C00_0007_exit
fn0C00_0007_exit:

// fn0C00_001D
// Return size: 0
void fn0C00_001D(word16 bx, selector ds)
fn0C00_001D_entry:
	// succ:  l0C00_001D
l0C00_001D:
	branch bx == Mem0[ds:0x53BA:word16] l0C00_003C
	// succ:  l0C00_0023 l0C00_003C
l0C00_0023:
	branch bx >= Mem0[ds:0x53B8:word16] l0C00_003C
	// succ:  l0C00_0029 l0C00_003C
l0C00_0029:
	Mem11[ds:0x53BA:word16] = bx
	fn0C00_0046(0x4400, SEQ(ds, 0x5388)[bx * 0x0002], 0x0000, ds)
	// succ:  l0C00_003C
l0C00_003C:
	return
	// succ:  fn0C00_001D_exit
fn0C00_001D_exit:

// fn0C00_003D
// Return size: 0
void fn0C00_003D(byte ah, word16 dx, selector ds)
fn0C00_003D_entry:
	// succ:  l0C00_003D
l0C00_003D:
	Mem6[ds:0x0110:byte] = ah
	Mem8[ds:0x0112:word16] = dx
	return
	// succ:  fn0C00_003D_exit
fn0C00_003D_exit:

// fn0C00_0046
// Return size: 0
void fn0C00_0046(word16 ax, word16 dx, word16 bx, selector ds)
fn0C00_0046_entry:
	// succ:  l0C00_0046
l0C00_0046:
	Mem6[ds:0x0114:word16] = ax
	Mem8[ds:0x0116:word16] = bx
	Mem10[ds:0x0118:word16] = dx
	return
	// succ:  fn0C00_0046_exit
fn0C00_0046_exit:

globals_t (in globals : (ptr (struct "Globals")))
	trait_primitive((ptr (struct "Globals")))
T_2 (in cx : word16)
	trait_primitive(word16)
	trait_equal(T_7)
T_3 (in bx : word16)
	trait_primitive(word16)
	trait_equal(T_12)
T_4 (in ds : selector)
	trait_primitive(selector)
	trait_equal(T_8)
	trait_primitive(selector)
	trait_equal(T_13)
T_5 (in fn0C00_0007 : ptr32)
	trait_func(T_2, T_4 -> T_9)
T_7 (in cx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_31)
	trait_primitive(word16)
T_8 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem_array(5388, 2, 0, T_25)
	trait_primitive(selector)
	trait_equal(T_21)
T_9 (in fn0C00_0007(cx, ds) : void)
	trait_primitive(void)
T_10 (in fn0C00_001D : ptr32)
	trait_func(T_3, T_4 -> T_14)
T_12 (in bx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_37)
	trait_primitive(word16)
	trait_equal(T_40)
	trait_primitive(int16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_13 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_37, 53BA)
	trait_primitive(selector)
	trait_mem(T_40, 53B8)
	trait_primitive(selector)
	trait_mem(T_43, 53BA)
	trait_primitive(selector)
	trait_mem_array(5388, 2, 0, T_55)
	trait_primitive(selector)
	trait_equal(T_49)
T_14 (in fn0C00_001D(bx, ds) : void)
	trait_primitive(void)
T_15 (in di_21 : word16)
	trait_primitive(word16)
	trait_equal(T_16)
	trait_primitive(word16)
	trait_memsize(2)
	trait_mem(T_8:T_25, 0)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_28)
T_16 (in 0x5388 : word16)
	trait_primitive(word16)
T_17 (in fn0C00_003D : ptr32)
	trait_func(T_22, T_25, T_8 -> T_26)
T_19 (in ah : byte)
	trait_primitive(byte)
	trait_primitive(byte)
T_20 (in dx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
T_21 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_59, 110)
	trait_primitive(selector)
	trait_mem(T_61, 112)
T_22 (in 0x2D : byte)
	trait_primitive(byte)
	trait_equal(T_19)
T_23 (in 0x0000 : word16)
	trait_primitive(word16)
T_24 (in di_21 + 0x0000 : word16)
	trait_primitive(word16)
T_25 (in Mem7[ds:di_21 + 0x0000:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_20)
T_26 (in fn0C00_003D(0x2D, Mem7[ds:di_21 + 0x0000:word16], ds) : void)
	trait_primitive(void)
T_27 (in 0x0002 : word16)
	trait_primitive(word16)
T_28 (in di_21 + 0x0002 : word16)
	trait_primitive(word16)
T_29 (in cx_35 : word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_7)
	trait_primitive(word16)
	trait_equal(T_34)
T_30 (in 0x0001 : word16)
	trait_primitive(word16)
T_31 (in cx_35 - 0x0001 : word16)
	trait_primitive(word16)
T_33 (in Mem7 : <unknown>)
	trait_primitive(<unknown>)
	trait_equal(T_32)
T_34 (in 0x0001 : word16)
	trait_primitive(word16)
T_35 (in cx_35 != 0x0001 : bool)
	trait_primitive(bool)
T_36 (in 0x53BA : word16)
	trait_primitive(word16)
	trait_mem(T_13:T_37, 0)
T_37 (in Mem0[ds:0x53BA:word16] : word16)
	trait_primitive(word16)
T_38 (in bx == Mem0[ds:0x53BA:word16] : bool)
	trait_primitive(bool)
T_39 (in 0x53B8 : word16)
	trait_primitive(word16)
	trait_mem(T_13:T_40, 0)
T_40 (in Mem0[ds:0x53B8:word16] : word16)
	trait_primitive(word16)
	trait_primitive(int16)
T_41 (in bx >= Mem0[ds:0x53B8:word16] : bool)
	trait_primitive(bool)
T_42 (in 0x53BA : word16)
	trait_primitive(word16)
	trait_mem(T_13:T_43, 0)
T_43 (in Mem11[ds:0x53BA:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_12)
T_44 (in fn0C00_0046 : ptr32)
	trait_func(T_50, T_55, T_56, T_13 -> T_57)
T_46 (in ax : word16)
	trait_primitive(word16)
	trait_primitive(word16)
T_47 (in dx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
T_48 (in bx : word16)
	trait_primitive(word16)
	trait_primitive(word16)
T_49 (in ds : selector)
	trait_primitive(selector)
	trait_primitive(selector)
	trait_mem(T_63, 114)
	trait_primitive(selector)
	trait_mem(T_65, 116)
	trait_primitive(selector)
	trait_mem(T_67, 118)
T_50 (in 0x4400 : word16)
	trait_primitive(word16)
	trait_equal(T_46)
T_51 (in 0x5388 : word16)
	trait_primitive(word16)
T_52 (in SEQ(ds, 0x5388) : ptr32)
	trait_primitive(ptr32)
T_53 (in 0x0002 : word16)
	trait_primitive(word16)
	trait_primitive(ui16)
T_54 (in bx * 0x0002 : word16)
	trait_primitive(ui16)
T_55 (in SEQ(ds, 0x5388)[bx * 0x0002] : word16)
	trait_primitive(word16)
	trait_equal(T_47)
T_56 (in 0x0000 : word16)
	trait_primitive(word16)
	trait_equal(T_48)
T_57 (in fn0C00_0046(0x4400, SEQ(ds, 0x5388)[bx * 0x0002], 0x0000, ds) : void)
	trait_primitive(void)
T_58 (in 0x0110 : word16)
	trait_primitive(word16)
	trait_mem(T_21:T_59, 0)
T_59 (in Mem6[ds:0x0110:byte] : byte)
	trait_primitive(byte)
	trait_equal(T_19)
T_60 (in 0x0112 : word16)
	trait_primitive(word16)
	trait_mem(T_21:T_61, 0)
T_61 (in Mem8[ds:0x0112:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_20)
T_62 (in 0x0114 : word16)
	trait_primitive(word16)
	trait_mem(T_49:T_63, 0)
T_63 (in Mem6[ds:0x0114:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_46)
T_64 (in 0x0116 : word16)
	trait_primitive(word16)
	trait_mem(T_49:T_65, 0)
T_65 (in Mem8[ds:0x0116:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_48)
T_66 (in 0x0118 : word16)
	trait_primitive(word16)
	trait_mem(T_49:T_67, 0)
T_67 (in Mem10[ds:0x0118:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_47)
