// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	r63 = fp
	Mem0[0x3120<32>:word32] = 0<32>
	Mem0[0x3120<32>:word32] = Mem0[0x3120<32>:word32] + 1<32>
	return
	// succ:  proc1_exit
proc1_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct (3120 T_4 t3120)))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in fp : ptr32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_3: (in r63 : word32)
  Class: Eq_2
  DataType: ptr32
  OrigDataType: ptr32
T_4: (in 0<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in 0x3120<32> : word32)
  Class: Eq_5
  DataType: (ptr32 (struct (0 T_6 t0000)))
  OrigDataType: (ptr32 (struct (0 T_6 t0000)))
T_6: (in Mem0[0x3120<32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_7: (in 0x3120<32> : word32)
  Class: Eq_7
  DataType: (ptr32 (struct (0 T_8 t0000)))
  OrigDataType: (ptr32 (struct (0 T_8 t0000)))
T_8: (in Mem0[0x3120<32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_9: (in 1<32> : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_10: (in Mem0[0x3120<32>:word32] + 1<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_11: (in 0x3120<32> : word32)
  Class: Eq_11
  DataType: (ptr32 (struct (0 T_12 t0000)))
  OrigDataType: (ptr32 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x3120<32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
