// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	eax = malloc(3<32>)
proc1_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in malloc : word32)
  Class: Eq_2
  DataType: (ptr32 (fn T_6 (T_5)))
  OrigDataType: (ptr32 (fn T_6 (T_5)))
T_3: (in signature of malloc : void)
  Class: Eq_2
  DataType: 
  OrigDataType: 
T_4: (in dwArg00 : word32)
  Class: Eq_4
  DataType: 
  OrigDataType: 
T_5: (in 3<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_6: (in malloc(3<32>) : word32)
  Class: Eq_6
  DataType: (ptr32 void)
  OrigDataType: (ptr32 void)
T_7: (in eax : word32)
  Class: Eq_6
  DataType: (ptr32 void)
  OrigDataType: (ptr32 void)
