// Fn
// Return size: 0
define Fn
Fn_entry:
	// succ:  l1
l1:
	a = 0x123456<32>
	a[i * 8<32>] = 0x2A<32>
Fn_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x123456<32> : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in a : word32)
  Class: Eq_2
  DataType: (ptr32 (struct (0 T_10 t0000)))
  OrigDataType: (ptr32 (struct (0 T_10 t0000)))
T_4: (in 0x2A<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in i : word32)
  Class: Eq_5
  DataType: ui32
  OrigDataType: ui32
T_6: (in 8<32> : word32)
  Class: Eq_6
  DataType: ui32
  OrigDataType: ui32
T_7: (in i * 8<32> : word32)
  Class: Eq_7
  DataType: ui32
  OrigDataType: ui32
T_8: (in a[i * 8<32>] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_9:
  Class: Eq_9
  DataType: (struct 0008 (0 T_8 t0000))
  OrigDataType: (struct 0008 (0 T_8 t0000))
T_10:
  Class: Eq_10
  DataType: (arr T_9)
  OrigDataType: (arr T_9)
