// ProcedureBuilder
// Return size: 0
void ProcedureBuilder()
ProcedureBuilder_entry:
	// succ:  l1
l1:
	Mem1[0x00003120:word32] = Mem0[0x00003120:word32] + 0x00000001
	return
	// succ:  ProcedureBuilder_exit
ProcedureBuilder_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct (3120 T_3 t3120)))
  OrigDataType: (ptr (struct (3120 T_3 t3120)))
T_2: (in 0x00003120 : word32)
  Class: Eq_2
  DataType: (ptr T_3)))
  OrigDataType: (ptr T_3)))
T_3: (in Mem0[0x00003120:word32] : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in 0x00000001 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[0x00003120:word32] + 0x00000001 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_6: (in 0x00003120 : word32)
  Class: Eq_6
  DataType: (ptr T_7))
  OrigDataType: (ptr T_7))
T_7: (in Mem1[0x00003120:word32] : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
