// ProcedureBuilder
// Return size: 0
void ProcedureBuilder()
ProcedureBuilder_entry:
	// succ:  l1
l1:
	word32 eax_1 = Mem0[0x00012312<32>:word32]
	Mem2[eax_1 + 0x00000000<32>:word32] = eax_1
	Mem3[eax_1 + 0x00000004<32>:word32] = eax_1
ProcedureBuilder_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct (12312 T_4 t12312)))
  OrigDataType: (ptr32 (struct (12312 T_4 t12312)))
T_2: (in eax_1 : word32)
  Class: Eq_2
  DataType: (ptr32 (struct (0 T_7 t0000) (4 T_10 t0004)))
  OrigDataType: (ptr32 (struct (0 T_7 t0000) (4 T_10 t0004)))
T_3: (in 0x00012312<32> : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (0 T_4 t0000)))
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem0[0x00012312<32>:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_5: (in 0x00000000<32> : word32)
  Class: Eq_5
  DataType: word32
  OrigDataType: word32
T_6: (in eax_1 + 0x00000000<32> : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in Mem2[eax_1 + 0x00000000<32>:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_8: (in 0x00000004<32> : word32)
  Class: Eq_8
  DataType: word32
  OrigDataType: word32
T_9: (in eax_1 + 0x00000004<32> : word32)
  Class: Eq_9
  DataType: word32
  OrigDataType: word32
T_10: (in Mem3[eax_1 + 0x00000004<32>:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
