// proc1
// Return size: 0
void proc1()
proc1_entry:
	// succ:  l1
l1:
	Mem0[0x00003120:word32] = 0x00000000
	Mem0[0x00003120:word32] = Mem0[0x00003120:word32] + 0x00000001
	return
	// succ:  proc1_exit
proc1_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 (struct (3120 T_2 t3120)))
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in 0x00000000 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in 0x00003120 : word32)
  Class: Eq_3
  DataType: (ptr32 (struct (0 T_4 t0000)))
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem0[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_5: (in 0x00003120 : word32)
  Class: Eq_5
  DataType: (ptr32 (struct (0 T_6 t0000)))
  OrigDataType: (ptr32 (struct (0 T_6 t0000)))
T_6: (in Mem0[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_7: (in 0x00000001 : word32)
  Class: Eq_7
  DataType: word32
  OrigDataType: word32
T_8: (in Mem0[0x00003120:word32] + 0x00000001 : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_9: (in 0x00003120 : word32)
  Class: Eq_9
  DataType: (ptr32 (struct (0 T_10 t0000)))
  OrigDataType: (ptr32 (struct (0 T_10 t0000)))
T_10: (in Mem0[0x00003120:word32] : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
