// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 cx, word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0007(cx, ds)
	fn0C00_001D(bx, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0007
// Return size: 0
void fn0C00_0007(word16 cx, selector ds)
fn0C00_0007_entry:
	// succ:  l0C00_0007
l0C00_0007:
	word16 di_21 = 0x5388
	// succ:  l0C00_000A
l0C00_000A:
	fn0C00_003D(0x2D, Mem7[ds:di_21 + 0x0000:word16], ds)
	di_21 = di_21 + 0x0002
	cx = cx_35 - 0x0001
	cx_35 = cx
	branch cx_35 != 0x0001 l0C00_000A
	// succ:  l0C00_001C l0C00_000A
l0C00_001C:
	return
	// succ:  fn0C00_0007_exit
fn0C00_0007_exit:

// fn0C00_001D
// Return size: 0
void fn0C00_001D(word16 bx, selector ds)
fn0C00_001D_entry:
	// succ:  l0C00_001D
l0C00_001D:
	branch bx == Mem0[ds:0x53BA:word16] l0C00_003C
	// succ:  l0C00_0023 l0C00_003C
l0C00_0023:
	branch bx >= Mem0[ds:0x53B8:word16] l0C00_003C
	// succ:  l0C00_0029 l0C00_003C
l0C00_0029:
	Mem11[ds:0x53BA:word16] = bx
	fn0C00_0046(0x4400, SEQ(ds, 0x5388)[bx * 0x0002], 0x0000, ds)
	// succ:  l0C00_003C
l0C00_003C:
	return
	// succ:  fn0C00_001D_exit
fn0C00_001D_exit:

// fn0C00_003D
// Return size: 0
void fn0C00_003D(byte ah, word16 dx, selector ds)
fn0C00_003D_entry:
	// succ:  l0C00_003D
l0C00_003D:
	Mem6[ds:0x0110:byte] = ah
	Mem8[ds:0x0112:word16] = dx
	return
	// succ:  fn0C00_003D_exit
fn0C00_003D_exit:

// fn0C00_0046
// Return size: 0
void fn0C00_0046(word16 ax, word16 dx, word16 bx, selector ds)
fn0C00_0046_entry:
	// succ:  l0C00_0046
l0C00_0046:
	Mem6[ds:0x0114:word16] = ax
	Mem8[ds:0x0116:word16] = bx
	Mem10[ds:0x0118:word16] = dx
	return
	// succ:  fn0C00_0046_exit
fn0C00_0046_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct))
  OrigDataType: (ptr (struct "Globals"))
T_2: (in cx : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3: (in bx : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in ds : selector)
  Class: Eq_4
  DataType: (ptr (segment))
  OrigDataType: (ptr (segment))
T_5: (in fn0C00_0007 : segptr32)
  Class: Eq_5
  DataType: (ptr (fn T_9 (T_2, T_4)))
  OrigDataType: (ptr (fn T_9 (T_2, T_4)))
T_6: (in signature of fn0C00_0007 : void)
  Class: Eq_5
  DataType: 
  OrigDataType: 
T_7: (in cx : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_8: (in ds : selector)
  Class: Eq_4
  DataType: (ptr (segment (5388 (arr T_68) a5388)))
  OrigDataType: (ptr (segment (5388 (arr T_68) a5388)))
T_9: (in fn0C00_0007(cx, ds) : void)
  Class: Eq_9
  DataType: void
  OrigDataType: void
T_10: (in fn0C00_001D : segptr32)
  Class: Eq_10
  DataType: (ptr (fn T_14 (T_3, T_4)))
  OrigDataType: (ptr (fn T_14 (T_3, T_4)))
T_11: (in signature of fn0C00_001D : void)
  Class: Eq_10
  DataType: 
  OrigDataType: 
T_12: (in bx : word16)
  Class: Eq_3
  DataType: int16
  OrigDataType: int16
T_13: (in ds : selector)
  Class: Eq_4
  DataType: (ptr (segment (5388 (arr T_69) a5388) (53B8 T_40 t53B8) (53BA T_3 t53BA)))
  OrigDataType: (ptr (segment (5388 (arr T_69) a5388) (53B8 T_40 t53B8) (53BA T_3 t53BA)))
T_14: (in fn0C00_001D(bx, ds) : void)
  Class: Eq_14
  DataType: void
  OrigDataType: void
T_15: (in di_21 : word16)
  Class: Eq_15
  DataType: (memptr T_8 (struct 0002 (0 word16 w0000)))
  OrigDataType: (memptr T_8 (struct 0002 (0 word16 w0000)))
T_16: (in 0x5388 : word16)
  Class: Eq_15
  DataType: word16
  OrigDataType: word16
T_17: (in fn0C00_003D : segptr32)
  Class: Eq_17
  DataType: (ptr (fn T_26 (T_22, T_25, T_8)))
  OrigDataType: (ptr (fn T_26 (T_22, T_25, T_8)))
T_18: (in signature of fn0C00_003D : void)
  Class: Eq_17
  DataType: 
  OrigDataType: 
T_19: (in ah : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_20: (in dx : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_21: (in ds : selector)
  Class: Eq_4
  DataType: (ptr (segment (110 T_59 t0110) (112 T_61 t0112)))
  OrigDataType: (ptr (segment (110 T_59 t0110) (112 T_61 t0112)))
T_22: (in 0x2D : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_23: (in 0x0000 : word16)
  Class: Eq_23
  DataType: word16
  OrigDataType: word16
T_24: (in di_21 + 0x0000 : word16)
  Class: Eq_24
  DataType: word16
  OrigDataType: word16
T_25: (in Mem7[ds:di_21 + 0x0000:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_26: (in fn0C00_003D(0x2D, Mem7[ds:di_21 + 0x0000:word16], ds) : void)
  Class: Eq_26
  DataType: void
  OrigDataType: void
T_27: (in 0x0002 : word16)
  Class: Eq_27
  DataType: int16
  OrigDataType: int16
T_28: (in di_21 + 0x0002 : word16)
  Class: Eq_15
  DataType: (memptr T_8 (struct 0002 (0 word16 w0000)))
  OrigDataType: (memptr T_8 (struct 0002 (0 word16 w0000)))
T_29: (in cx_35 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_30: (in 0x0001 : word16)
  Class: Eq_30
  DataType: word16
  OrigDataType: word16
T_31: (in cx_35 - 0x0001 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_32: (in Mem15 : <unknown>)
  Class: Eq_32
  DataType: <unknown>
  OrigDataType: <unknown>
T_33: (in Mem7 : <unknown>)
  Class: Eq_32
  DataType: <unknown>
  OrigDataType: <unknown>
T_34: (in 0x0001 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_35: (in cx_35 != 0x0001 : bool)
  Class: Eq_35
  DataType: bool
  OrigDataType: bool
T_36: (in 0x53BA : word16)
  Class: Eq_36
  DataType: (memptr T_13 (struct (0 T_37 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_37 t0000)))
T_37: (in Mem0[ds:0x53BA:word16] : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_38: (in bx == Mem0[ds:0x53BA:word16] : bool)
  Class: Eq_38
  DataType: bool
  OrigDataType: bool
T_39: (in 0x53B8 : word16)
  Class: Eq_39
  DataType: (memptr T_13 (struct (0 T_40 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_40 t0000)))
T_40: (in Mem0[ds:0x53B8:word16] : word16)
  Class: Eq_3
  DataType: ci16
  OrigDataType: ci16
T_41: (in bx >= Mem0[ds:0x53B8:word16] : bool)
  Class: Eq_41
  DataType: bool
  OrigDataType: bool
T_42: (in 0x53BA : word16)
  Class: Eq_42
  DataType: (memptr T_13 (struct (0 T_43 t0000)))
  OrigDataType: (memptr T_13 (struct (0 T_43 t0000)))
T_43: (in Mem11[ds:0x53BA:word16] : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_44: (in fn0C00_0046 : segptr32)
  Class: Eq_44
  DataType: (ptr (fn T_57 (T_50, T_55, T_56, T_13)))
  OrigDataType: (ptr (fn T_57 (T_50, T_55, T_56, T_13)))
T_45: (in signature of fn0C00_0046 : void)
  Class: Eq_44
  DataType: 
  OrigDataType: 
T_46: (in ax : word16)
  Class: Eq_46
  DataType: word16
  OrigDataType: word16
T_47: (in dx : word16)
  Class: Eq_47
  DataType: word16
  OrigDataType: word16
T_48: (in bx : word16)
  Class: Eq_48
  DataType: word16
  OrigDataType: word16
T_49: (in ds : selector)
  Class: Eq_4
  DataType: (ptr (segment (114 T_63 t0114) (116 T_65 t0116) (118 T_67 t0118)))
  OrigDataType: (ptr (segment (114 T_63 t0114) (116 T_65 t0116) (118 T_67 t0118)))
T_50: (in 0x4400 : word16)
  Class: Eq_46
  DataType: word16
  OrigDataType: word16
T_51: (in 0x5388 : word16)
  Class: Eq_51
  DataType: (memptr T_13 T_69)
  OrigDataType: (memptr T_13 T_69)
T_52: (in SEQ(ds, 0x5388) : segptr32)
  Class: Eq_52
  DataType: (ptr T_69)
  OrigDataType: (ptr T_69)
T_53: (in 0x0002 : word16)
  Class: Eq_53
  DataType: ui16
  OrigDataType: ui16
T_54: (in bx * 0x0002 : word16)
  Class: Eq_54
  DataType: ui16
  OrigDataType: ui16
T_55: (in SEQ(ds, 0x5388)[bx * 0x0002] : word16)
  Class: Eq_47
  DataType: word16
  OrigDataType: word16
T_56: (in 0x0000 : word16)
  Class: Eq_48
  DataType: word16
  OrigDataType: word16
T_57: (in fn0C00_0046(0x4400, SEQ(ds, 0x5388)[bx * 0x0002], 0x0000, ds) : void)
  Class: Eq_57
  DataType: void
  OrigDataType: void
T_58: (in 0x0110 : word16)
  Class: Eq_58
  DataType: (memptr T_21 (struct (0 T_59 t0000)))
  OrigDataType: (memptr T_21 (struct (0 T_59 t0000)))
T_59: (in Mem6[ds:0x0110:byte] : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_60: (in 0x0112 : word16)
  Class: Eq_60
  DataType: (memptr T_21 (struct (0 T_61 t0000)))
  OrigDataType: (memptr T_21 (struct (0 T_61 t0000)))
T_61: (in Mem8[ds:0x0112:word16] : word16)
  Class: Eq_20
  DataType: word16
  OrigDataType: word16
T_62: (in 0x0114 : word16)
  Class: Eq_62
  DataType: (memptr T_49 (struct (0 T_63 t0000)))
  OrigDataType: (memptr T_49 (struct (0 T_63 t0000)))
T_63: (in Mem6[ds:0x0114:word16] : word16)
  Class: Eq_46
  DataType: word16
  OrigDataType: word16
T_64: (in 0x0116 : word16)
  Class: Eq_64
  DataType: (memptr T_49 (struct (0 T_65 t0000)))
  OrigDataType: (memptr T_49 (struct (0 T_65 t0000)))
T_65: (in Mem8[ds:0x0116:word16] : word16)
  Class: Eq_48
  DataType: word16
  OrigDataType: word16
T_66: (in 0x0118 : word16)
  Class: Eq_66
  DataType: (memptr T_49 (struct (0 T_67 t0000)))
  OrigDataType: (memptr T_49 (struct (0 T_67 t0000)))
T_67: (in Mem10[ds:0x0118:word16] : word16)
  Class: Eq_47
  DataType: word16
  OrigDataType: word16
T_68:
  Class: Eq_68
  DataType: (struct 0002 (0 T_25 t0000))
  OrigDataType: (struct 0002 (0 T_25 t0000))
T_69:
  Class: Eq_69
  DataType: (struct 0002 (0 T_55 t0000))
  OrigDataType: (struct 0002 (0 T_55 t0000))
