// proc1
// Return size: 0
define proc1
proc1_entry:
	// succ:  l1
l1:
	eax = malloc(0x00000003)
proc1_exit:

// Equivalence classes ////////////
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr (struct))
  OrigDataType: (ptr (struct "Globals"))
T_2: (in malloc : word32)
  Class: Eq_2
  DataType: (ptr (fn T_6 (T_5)))
  OrigDataType: (ptr (fn T_6 (T_5)))
T_3: (in signature of malloc : void)
  Class: Eq_2
  DataType: 
  OrigDataType: 
T_4: (in dwArg00 : word32)
  Class: Eq_4
  DataType: 
  OrigDataType: 
T_5: (in 0x00000003 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_6: (in malloc(0x00000003) : (ptr void))
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in eax : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
