// sparc-rtems-unprotoize_dynamic.c
// Generated by decompiling sparc-rtems-unprotoize
// using Reko decompiler version 0.12.0.0.

#include "sparc-rtems-unprotoize.h"

Eq_n g_t27C00 = // 00027C00
	{
		0x00,
	};
