// hello_O1_rodata.c
// Generated by decompiling hello_O1
// using Reko decompiler version 0.11.6.0.

#include "hello_O1.h"

real32 g_r2074 = 0.5F; // 0000000000002074
real32 g_r2078 = 1.5F; // 0000000000002078
real32 g_r207C = 1.0F; // 000000000000207C
