// switch.c
// Generated by decompiling switch
// using Reko decompiler version 0.7.1.0.

#include "switch.h"

// 000082F0: void _init()
void _init()
{
_init_entry:
_init_exit:
}

// 00008334: void _start()
void _start()
{
_start_entry:
_start_exit:
}

// 0000836C: void call_gmon_start()
void call_gmon_start()
{
call_gmon_start_entry:
call_gmon_start_exit:
}

// 0000839C: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
__do_global_dtors_aux_entry:
__do_global_dtors_aux_exit:
}

// 000083FC: void call___do_global_dtors_aux()
void call___do_global_dtors_aux()
{
call___do_global_dtors_aux_entry:
call___do_global_dtors_aux_exit:
}

// 00008404: void frame_dummy()
void frame_dummy()
{
frame_dummy_entry:
frame_dummy_exit:
}

// 0000842C: void call_frame_dummy()
void call_frame_dummy()
{
call_frame_dummy_entry:
call_frame_dummy_exit:
}

// 00008434: void frobulate()
void frobulate()
{
frobulate_entry:
frobulate_exit:
}

// 00008470: void bazulate()
void bazulate()
{
bazulate_entry:
bazulate_exit:
}

// 000084D4: void switcheroo()
void switcheroo()
{
switcheroo_entry:
switcheroo_exit:
}

// 0000855C: void main()
void main()
{
main_entry:
main_exit:
}

// 00008588: void __divsi3()
void __divsi3()
{
__divsi3_entry:
__divsi3_exit:
}

// 00008638: void __div0()
void __div0()
{
__div0_entry:
__div0_exit:
}

// 00008654: void __libc_csu_init()
void __libc_csu_init()
{
__libc_csu_init_entry:
__libc_csu_init_exit:
}

// 000086B0: void __libc_csu_fini()
void __libc_csu_fini()
{
__libc_csu_fini_entry:
__libc_csu_fini_exit:
}

// 0000870C: void __do_global_ctors_aux()
void __do_global_ctors_aux()
{
__do_global_ctors_aux_entry:
__do_global_ctors_aux_exit:
}

// 00008744: void call___do_global_ctors_aux()
void call___do_global_ctors_aux()
{
call___do_global_ctors_aux_entry:
call___do_global_ctors_aux_exit:
}

// 0000874C: void _fini()
void _fini()
{
_fini_entry:
_fini_exit:
}

