// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 ax_9 = 0x0000
	// succ:  l0C00_0002
l0C00_0002:
	branch bx == 0x0000 l0C00_000D
	// succ:  l0C00_0006 l0C00_000D
l0C00_0006:
	ax_9 = ax_9 + 0x0001
	bx = Mem0[ds:bx + 0x0004:word16]
	goto l0C00_0002
	// succ:  l0C00_0002
l0C00_000D:
	Mem21[ds:0x0200:word16] = ax_9
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Equivalence classes ////////////
Eq_1: (struct)
	globals_t (in globals : (ptr (struct)))
Eq_4: (segment (0 Eq_9 t0000) (200 word16 w0200))
	T_4 (in ds : selector)
Eq_9: (struct (4 (memptr Eq_4 Eq_9) ptr0004))
	T_9 (in bx : word16)
	T_12 (in Mem0[ds:bx + 0x0004:word16] : word16)
	T_13 (in 0x0000 : word16)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct)))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct))
T_2: (in ax_9 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3: (in 0x0000 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_4: (in ds : selector)
  Class: Eq_4
  DataType: (ptr Eq_4)
  OrigDataType: (ptr (segment (200 T_6 t0200)))
T_5: (in 0x0200 : word16)
  Class: Eq_5
  DataType: (memptr (ptr Eq_4) word16)
  OrigDataType: (memptr T_4 (struct (0 T_6 t0000)))
T_6: (in Mem21[ds:0x0200:word16] : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_7: (in 0x0001 : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in ax_9 + 0x0001 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_9: (in bx : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_4) Eq_9)
  OrigDataType: (memptr T_4 (struct (4 T_12 t0004)))
T_10: (in 0x0004 : word16)
  Class: Eq_10
  DataType: word16
  OrigDataType: word16
T_11: (in bx + 0x0004 : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in Mem0[ds:bx + 0x0004:word16] : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_4) Eq_9)
  OrigDataType: word16
T_13: (in 0x0000 : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_4) Eq_9)
  OrigDataType: word16
T_14: (in bx == 0x0000 : bool)
  Class: Eq_14
  DataType: bool
  OrigDataType: bool
