cmake_minimum_required ( VERSION 3.10 FATAL_ERROR )
list(INSERT CMAKE_MODULE_PATH 0 "${REKO_SRC}/../cmake")

include(msbuild2cmake)

message(STATUS "Building native libraries")
invoke_cmake(
	BUILD_DIR ${CMAKE_BINARY_DIR}/build/${REKO_PLATFORM}/${CMAKE_BUILD_TYPE}
	DIRECTORY ${CMAKE_SOURCE_DIR}
	PLATFORM ${REKO_PLATFORM}
	GENERATOR ${REKO_COMPILER}
	EXTRA_ARGUMENTS
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DREKO_PLATFORM=${REKO_ACTUAL_PLATFORM}
)