#region License
/* 
 * Copyright (C) 1999-2015 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

using System;
using System.Collections.Generic;
using System.Text;

namespace Decompiler.Arch.PowerPC
{
    public enum Opcode : ushort
    {
        illegal,

        add,
        addc,
        adde,
        addco,
        addi,
        addic,
        addis,
        addze,
        and,
        andi,
        andis,
        b,
        bc,
        bcl,
        bcctr,
        bctrl,
        beq,
        beql,
        bge,
        bgel,
        bgt,
        bgtl,
        bl,
        ble,
        blel,
        blr,
        blrl,
        blt,
        bltl,
        bne,
        bnel,
        bns,
        bnsl,
        bso,
        bsol,
        cmp,
        cmpi,
        cmpl,
        cmpli,
        cmplw,
        cmpwi,
        cntlzw,
        creqv,
        crnor,
        cror,
        crxor,
        divw,
        divwu,
        extsb,
        fabs,
        fadd,
        fadds,
        fcmpo,
        fcmpu,
        fcfid,
        fctid,
        fctidz,
        fctiw,
        fctiwz,
        fdiv,
        fdivs,
        fmadd,
        fmadds,
        fmr,
        fmsub,
        fmsubs,
        fmul,
        fmuls,
        fnabs,
        fnmadd,
        fnmadds,
        fnmsub,
        fnmsubs,
        fneg,
        fres,
        frsp,
        frsqrte,
        fsel,
        fsub,
        fsubs,
        fsqrt,
        fsqrts,
        lbz,
        lbzu,
        lbzux,
        lbzx,
        lfd,
        lfdu,
        lfs,
        lfsu,
        lha,
        lhau,
        lhz,
        lhzu,
        lhzx,
        lmw,
        lwarx,
        lwbrx,
        lwzu,
        lwz,
        lwzx,
        mcrf,
        mfcr,
        mfctr,
        mflr,
        mtcrf,
        mtctr,
        mtlr,
        mulli,
        mullw,
        mulhw,
        mulhwu,
        nand,
        neg,
        nor,
        or,
        orc,
        ori,
        oris,
        rfi,
        rlwimi,
        rlwinm,
        sc,
        slw,
        sraw,
        srawi,
        srd,
        srw,
        stb,
        stbu,
        stbux,
        stbx,
        stfd,
        stfdu,
        stfs,
        stfsu,
        sth,
        sthu,
        sthx,
        stmw,
        stw,
        stwbrx,
        stwu,
        stwux,
        stwx,
        subf,
        subfc,
        subfe,
        subfic,
        subfze,
        tw,
        twi,
        xor,
        xori,
        xoris,
    }
}
