Mem0:Global memory (aliases:)
fp:Temporary (aliases:)
ds:Register ds (aliases:)
ax:Register ax (aliases:)
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	ax = Mem0[ds:0x0100:word16]
	call fn0C00_000C (depth: 2;)
	store(Mem0[ds:0x0102:word16]) = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

Mem0:Global memory (aliases:)
fp:Temporary (aliases:)
ax:Register ax (aliases: al)
wLoc04:Local -0004 (aliases:)
ds:Register ds (aliases:)
al:Register al (aliases: ax)
// fn0C00_000C
void fn0C00_000C()
fn0C00_000C_entry:		// pred:
	// succ:  l0C00_000C
l0C00_000C:		// pred: fn0C00_000C_entry
	wLoc04 = ax
	al = Mem0[ds:0x0104:byte]
	store(Mem0[ds:0x0105:byte]) = al
	ax = wLoc04
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:		// pred: l0C00_000C
	// succ: 

