Mem0:Global memory (aliases:)
fp:fp (aliases:)
sp:sp (aliases:)
ax:ax (aliases:)
ds:ds (aliases:)
// fn0C00_0000
// Return size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	ax = Mem0[ds:0x0100:word16]
	call fn0C00_000C (retsize: 2; depth: 2)
	Mem0[ds:0x0102:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

Mem0:Global memory (aliases:)
fp:fp (aliases:)
sp:sp (aliases:)
ax:ax (aliases: al)
ss:ss (aliases:)
al:al (aliases: ax)
ds:ds (aliases:)
wLoc02:Local -0002 (aliases:)
// fn0C00_000C
// Return size: 2
void fn0C00_000C()
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	sp = fp
	sp = fp - 2
	wLoc02 = ax
	al = Mem0[ds:0x0104:byte]
	Mem0[ds:0x0105:byte] = al
	ax = wLoc02
	sp = fp
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

