Mem0:Global memory (aliases:)
fp:Temporary (aliases:)
ds:Register (aliases:)
ax:Register (aliases:)
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	ax = Mem0[ds:0x0100:word16]
	call fn0C00_000C (depth: 0;)
	store(Mem0[ds:0x0102:word16]) = ax
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

Mem0:Global memory (aliases:)
fp:Temporary (aliases:)
ax:Register (aliases: al)
wLoc02:Local -0002 (aliases:)
ds:Register (aliases:)
al:Register (aliases: ax)
// fn0C00_000C
void fn0C00_000C()
fn0C00_000C_entry:		// block 0, pred:
	// succ:  1
l0C00_000C:		// block 1, pred: 0
	al = Mem0[ds:0x0104:byte]
	ax = DPB(ax, al, 0, 8) (alias)
	store(Mem0[ds:0x0105:byte]) = al
	return
	// succ:  2
fn0C00_000C_exit:		// block 2, pred: 1
	// succ: 

