Mem0:Global memory
    def:  def Mem0
    uses: r0_7 = Mem0[0x01001000:word32]
fp:Temporary
r0:Local -0004
C:Flags
r1:Register r1
    def:  def r1
    uses: r0_11 = r0_7 * 0x00000002 + (r1 <u 0x00000002)
r2:Register r2
SZC:Flags
r0_7: orig: r0
    def:  r0_7 = Mem0[0x01001000:word32]
    uses: r0_11 = r0_7 * 0x00000002 + (r1 <u 0x00000002)
SZC_8: orig: SZC
C_9: orig: C
r0_10: orig: r0
r0_11: orig: r0
    def:  r0_11 = r0_7 * 0x00000002 + (r1 <u 0x00000002)
    uses: Mem12[0x01001004:word32] = r0_11
Mem12: orig: Mem0
    def:  Mem12[0x01001004:word32] = r0_11
// AdcMock
void AdcMock(word32 r1)
AdcMock_entry:		// pred:
	def Mem0
	def r1
	// succ:  l1
l1:		// pred: AdcMock_entry
	r0_7 = Mem0[0x01001000:word32]
	r0_11 = r0_7 * 0x00000002 + (r1 <u 0x00000002)
	Mem12[0x01001004:word32] = r0_11
	return
	// succ:  AdcMock_exit
AdcMock_exit:		// pred: l1
	// succ: 

