fp:fp
sp_2: orig: sp
Top_3: orig: Top
sp_4: orig: sp
al_5: orig: al
    def:  call fn0C00_000A (retsize: 2;)	defs: al:al_5,C:C_7
    uses: Mem9[ds:0x0300:byte] = al_5
Top_6: orig: Top
C_7: orig: C
    def:  call fn0C00_000A (retsize: 2;)	defs: al:al_5,C:C_7
    uses: branch C_7 l0C00_0009
ds:ds
    def:  def ds
    uses: Mem9[ds:0x0300:byte] = al_5
Mem9: orig: Mem0
    def:  Mem9[ds:0x0300:byte] = al_5
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	call fn0C00_000A (retsize: 2;)
		defs: al:al_5,C:C_7
	branch C_7 l0C00_0009
	// succ:  l0C00_0005 l0C00_0009
l0C00_0005:
	Mem9[ds:0x0300:byte] = al_5
	// succ:  l0C00_0009
l0C00_0009:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
sp_2: orig: sp
Top_3: orig: Top
al:al
    def:  def al
    uses: branch al <u 0x30 l0C00_0032
          branch al <=u 0x39 l0C00_0022
          branch al <u 0x41 l0C00_0032
          branch al <=u 0x46 l0C00_0022
          branch al <u 0x61 l0C00_0032
          branch al >u 0x66 l0C00_0032
          branch al <u 0x3A l0C00_0030
          branch al <u 0x47 l0C00_0030
SCZO_5: orig: SCZO
C_6: orig: C
SCZO_7: orig: SCZO
CZ_8: orig: CZ
SCZO_9: orig: SCZO
C_10: orig: C
SCZO_11: orig: SCZO
CZ_12: orig: CZ
SCZO_13: orig: SCZO
C_14: orig: C
SCZO_15: orig: SCZO
CZ_16: orig: CZ
C_17: orig: C
al_19: orig: al
SCZO_20: orig: SCZO
SCZO_21: orig: SCZO
C_22: orig: C
al_23: orig: al
SCZO_24: orig: SCZO
SCZO_25: orig: SCZO
C_26: orig: C
al_27: orig: al
SCZO_28: orig: SCZO
C_29: orig: C
// fn0C00_000A
// Return size: 2
define fn0C00_000A
fn0C00_000A_entry:
	def al
	// succ:  l0C00_000A
l0C00_000A:
	branch al <u 0x30 l0C00_0032
	// succ:  l0C00_000E l0C00_0032
l0C00_000E:
	branch al <=u 0x39 l0C00_0022
	// succ:  l0C00_0012 l0C00_0022
l0C00_0012:
	branch al <u 0x41 l0C00_0032
	// succ:  l0C00_0016 l0C00_0032
l0C00_0016:
	branch al <=u 0x46 l0C00_0022
	// succ:  l0C00_001A l0C00_0022
l0C00_001A:
	branch al <u 0x61 l0C00_0032
	// succ:  l0C00_001E l0C00_0032
l0C00_001E:
	branch al >u 0x66 l0C00_0032
	// succ:  l0C00_0022 l0C00_0032
l0C00_0022:
	branch al <u 0x3A l0C00_0030
	// succ:  l0C00_0028 l0C00_0030
l0C00_0028:
	branch al <u 0x47 l0C00_0030
	// succ:  l0C00_002E l0C00_0030
l0C00_002E:
	// succ:  l0C00_0030
l0C00_0030:
	return
	// succ:  fn0C00_000A_exit
l0C00_0032:
	return
	// succ:  fn0C00_000A_exit
fn0C00_000A_exit:

