fp:fp
sp_2: orig: sp
Top_3: orig: Top
ds:ds
    def:  def ds
    uses: ax_6 = Mem0[ds:0x200<16>:word16]
          dx_7 = Mem0[ds:0x202<16>:word16]
          cx_8 = Mem0[ds:0x204<16>:word16]
          bx_9 = Mem0[ds:0x206<16>:word16]
          Mem15[ds:0x208<16>:word16] = ax_10
          Mem16[ds:0x20A<16>:word16] = dx_13
          ax_17 = Mem16[ds:0x210<16>:word16]
          dx_18 = Mem16[ds:0x212<16>:word16]
          es_cx_19 = Mem16[ds:0x214<16>:segptr32]
          Mem25[ds:0x218<16>:word16] = ax_23
          Mem29[ds:0x21A<16>:word16] = dx_27
          cl_33 = Mem29[ds:0x220<16>:byte]
          cl_38 = Mem29[ds:0x221<16>:byte]
          Mem44[ds:0x222<16>:word16] = ax_42
Mem0:Mem
    def:  def Mem0
    uses: ax_6 = Mem0[ds:0x200<16>:word16]
          dx_7 = Mem0[ds:0x202<16>:word16]
          cx_8 = Mem0[ds:0x204<16>:word16]
          bx_9 = Mem0[ds:0x206<16>:word16]
ax_6: orig: ax
    def:  ax_6 = Mem0[ds:0x200<16>:word16]
    uses: dx_ax_45 = SEQ(dx_7, ax_6)
dx_7: orig: dx
    def:  dx_7 = Mem0[ds:0x202<16>:word16]
    uses: dx_ax_45 = SEQ(dx_7, ax_6)
cx_8: orig: cx
    def:  cx_8 = Mem0[ds:0x204<16>:word16]
    uses: bx_cx_46 = SEQ(bx_9, cx_8)
bx_9: orig: bx
    def:  bx_9 = Mem0[ds:0x206<16>:word16]
    uses: bx_cx_46 = SEQ(bx_9, cx_8)
ax_10: orig: ax
    def:  ax_10 = SLICE(dx_ax_47, word16, 0) (alias)
    uses: Mem15[ds:0x208<16>:word16] = ax_10
SCZO_11: orig: SCZO
C_12: orig: C
dx_13: orig: dx
    def:  dx_13 = SLICE(dx_ax_47, word16, 16) (alias)
    uses: Mem16[ds:0x20A<16>:word16] = dx_13
SCZO_14: orig: SCZO
Mem15: orig: Mem0
    def:  Mem15[ds:0x208<16>:word16] = ax_10
Mem16: orig: Mem0
    def:  Mem16[ds:0x20A<16>:word16] = dx_13
    uses: ax_17 = Mem16[ds:0x210<16>:word16]
          dx_18 = Mem16[ds:0x212<16>:word16]
          es_cx_19 = Mem16[ds:0x214<16>:segptr32]
ax_17: orig: ax
    def:  ax_17 = Mem16[ds:0x210<16>:word16]
    uses: dx_ax_48 = SEQ(dx_18, ax_17)
dx_18: orig: dx
    def:  dx_18 = Mem16[ds:0x212<16>:word16]
    uses: dx_ax_48 = SEQ(dx_18, ax_17)
es_cx_19: orig: es_cx
    def:  es_cx_19 = Mem16[ds:0x214<16>:segptr32]
    uses: dx_ax_50 = dx_ax_48 - es_cx_19
es_20: orig: es
bx_21: orig: bx
cx_22: orig: cx
ax_23: orig: ax
    def:  ax_23 = SLICE(dx_ax_50, word16, 0) (alias)
    uses: Mem25[ds:0x218<16>:word16] = ax_23
SCZO_24: orig: SCZO
Mem25: orig: Mem0
    def:  Mem25[ds:0x218<16>:word16] = ax_23
C_26: orig: C
dx_27: orig: dx
    def:  dx_27 = SLICE(dx_ax_50, word16, 16) (alias)
    uses: Mem29[ds:0x21A<16>:word16] = dx_27
SCZO_28: orig: SCZO
Mem29: orig: Mem0
    def:  Mem29[ds:0x21A<16>:word16] = dx_27
    uses: cl_33 = Mem29[ds:0x220<16>:byte]
          cl_38 = Mem29[ds:0x221<16>:byte]
ax_30: orig: ax
SZO_31: orig: SZO
C_32: orig: C
cl_33: orig: cl
    def:  cl_33 = Mem29[ds:0x220<16>:byte]
    uses: ax_42 = (cl_33 <u 0x30<8>) * 2<16> + (cl_38 >=u 0x3A<8>)
SCZO_34: orig: SCZO
C_35: orig: C
ax_36: orig: ax
SCZO_37: orig: SCZO
cl_38: orig: cl
    def:  cl_38 = Mem29[ds:0x221<16>:byte]
    uses: ax_42 = (cl_33 <u 0x30<8>) * 2<16> + (cl_38 >=u 0x3A<8>)
SCZO_39: orig: SCZO
C_40: orig: C
C_41: orig: C
ax_42: orig: ax
    def:  ax_42 = (cl_33 <u 0x30<8>) * 2<16> + (cl_38 >=u 0x3A<8>)
    uses: Mem44[ds:0x222<16>:word16] = ax_42
SCZO_43: orig: SCZO
Mem44: orig: Mem0
    def:  Mem44[ds:0x222<16>:word16] = ax_42
dx_ax_45: orig: dx_ax
    def:  dx_ax_45 = SEQ(dx_7, ax_6)
    uses: dx_ax_47 = dx_ax_45 + bx_cx_46
bx_cx_46: orig: bx_cx
    def:  bx_cx_46 = SEQ(bx_9, cx_8)
    uses: dx_ax_47 = dx_ax_45 + bx_cx_46
dx_ax_47: orig: dx_ax
    def:  dx_ax_47 = dx_ax_45 + bx_cx_46
    uses: ax_10 = SLICE(dx_ax_47, word16, 0) (alias)
          dx_13 = SLICE(dx_ax_47, word16, 16) (alias)
dx_ax_48: orig: dx_ax
    def:  dx_ax_48 = SEQ(dx_18, ax_17)
    uses: dx_ax_50 = dx_ax_48 - es_cx_19
bx_cx_49: orig: bx_cx
dx_ax_50: orig: dx_ax
    def:  dx_ax_50 = dx_ax_48 - es_cx_19
    uses: ax_23 = SLICE(dx_ax_50, word16, 0) (alias)
          dx_27 = SLICE(dx_ax_50, word16, 16) (alias)
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def ds
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	ax_6 = Mem0[ds:0x200<16>:word16]
	dx_7 = Mem0[ds:0x202<16>:word16]
	cx_8 = Mem0[ds:0x204<16>:word16]
	bx_9 = Mem0[ds:0x206<16>:word16]
	dx_ax_45 = SEQ(dx_7, ax_6)
	bx_cx_46 = SEQ(bx_9, cx_8)
	dx_ax_47 = dx_ax_45 + bx_cx_46
	ax_10 = SLICE(dx_ax_47, word16, 0) (alias)
	dx_13 = SLICE(dx_ax_47, word16, 16) (alias)
	Mem15[ds:0x208<16>:word16] = ax_10
	Mem16[ds:0x20A<16>:word16] = dx_13
	ax_17 = Mem16[ds:0x210<16>:word16]
	dx_18 = Mem16[ds:0x212<16>:word16]
	es_cx_19 = Mem16[ds:0x214<16>:segptr32]
	dx_ax_48 = SEQ(dx_18, ax_17)
	dx_ax_50 = dx_ax_48 - es_cx_19
	ax_23 = SLICE(dx_ax_50, word16, 0) (alias)
	dx_27 = SLICE(dx_ax_50, word16, 16) (alias)
	Mem25[ds:0x218<16>:word16] = ax_23
	Mem29[ds:0x21A<16>:word16] = dx_27
	cl_33 = Mem29[ds:0x220<16>:byte]
	cl_38 = Mem29[ds:0x221<16>:byte]
	ax_42 = (cl_33 <u 0x30<8>) * 2<16> + (cl_38 >=u 0x3A<8>)
	Mem44[ds:0x222<16>:word16] = ax_42
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

