r0:r0
    def:  def r0
    uses: r0_5 = r0 + r1
          branch r0 == 0 skip
          r0_2 = PHI(r0, r0_5)
Z_1: orig: Z
r0_2: orig: r0
    def:  r0_2 = PHI(r0, r0_5)
    uses: Mem3[0x10003000:word32] = r0_2
Mem3: orig: Mem0
    def:  Mem3[0x10003000:word32] = r0_2
r1:r1
    def:  def r1
    uses: r0_5 = r0 + r1
r0_5: orig: r0
    def:  r0_5 = r0 + r1
    uses: r0_2 = PHI(r0, r0_5)
// CmpMock
// Return size: 0
void CmpMock(word32 r0, word32 r1)
CmpMock_entry:
	def r0
	def r1
	// succ:  l1
l1:
	branch r0 == 0 skip
	// succ:  l2 skip
l2:
	r0_5 = r0 + r1
	// succ:  skip
skip:
	r0_2 = PHI(r0, r0_5)
	Mem3[0x10003000:word32] = r0_2
	return
	// succ:  CmpMock_exit
CmpMock_exit:

