r0:r0
    def:  def r0
    uses: r0_4 = r0 + r1
          r0_5 = PHI(r0, r0_4)
          branch r0 == 0x00000000 skip
Z_2: orig: Z
r1:r1
    def:  def r1
    uses: r0_4 = r0 + r1
r0_4: orig: r0
    def:  r0_4 = r0 + r1
    uses: r0_5 = PHI(r0, r0_4)
r0_5: orig: r0
    def:  r0_5 = PHI(r0, r0_4)
    uses: Mem6[0x10003000:word32] = r0_5
Mem6: orig: Mem0
    def:  Mem6[0x10003000:word32] = r0_5
// CmpMock
// Return size: 0
define CmpMock
CmpMock_entry:
	def r0
	def r1
	// succ:  l1
l1:
	branch r0 == 0x00000000 skip
	// succ:  l2 skip
l2:
	r0_4 = r0 + r1
	// succ:  skip
skip:
	r0_5 = PHI(r0, r0_4)
	Mem6[0x10003000:word32] = r0_5
	return
	// succ:  CmpMock_exit
CmpMock_exit:

