r0:r0
    def:  def r0
    uses: r0_3 = r0 + r1
          r0_4 = PHI(r0, r0_3)
          branch r0 == 0x00000000 skip
Z_1: orig: Z
r1:r1
    def:  def r1
    uses: r0_3 = r0 + r1
r0_3: orig: r0
    def:  r0_3 = r0 + r1
    uses: r0_4 = PHI(r0, r0_3)
r0_4: orig: r0
    def:  r0_4 = PHI(r0, r0_3)
    uses: Mem5[0x10003000:word32] = r0_4
Mem5: orig: Mem0
    def:  Mem5[0x10003000:word32] = r0_4
// CmpMock
// Return size: 0
void CmpMock(word32 r0, word32 r1)
CmpMock_entry:
	def r0
	def r1
	// succ:  l1
l1:
	branch r0 == 0x00000000 skip
	// succ:  l2 skip
l2:
	r0_3 = r0 + r1
	// succ:  skip
skip:
	r0_4 = PHI(r0, r0_3)
	Mem5[0x10003000:word32] = r0_4
	return
	// succ:  CmpMock_exit
CmpMock_exit:

