fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
    uses: use sp_2
ds:ds
    def:  def ds
    uses: rLoc1_6 = Mem0[ds:si:real64]
          Mem11[ds:di:word16] = 0x0000
          Mem12[ds:di:word16] = 0x0001
si:si
    def:  def si
    uses: rLoc1_6 = Mem0[ds:si:real64]
Mem0:Global memory
    def:  def Mem0
    uses: rLoc1_5 = Mem0[ds:si:real64]
rLoc1_5: orig: rLoc1
    def:  rLoc1_5 = Mem0[ds:si:real64]
    uses: branch 0.0 == rLoc1_5 l0C00_0012
rLoc2_6: orig: rLoc2
FPUF_7: orig: FPUF
SCZO_8: orig: SCZO
Mem9: orig: Mem0
    def:  Mem9[ds:di:word16] = 0x0001
di:di
    def:  def di
    uses: Mem11[ds:di:word16] = 0x0000
          Mem12[ds:di:word16] = 0x0001
Mem11: orig: Mem0
    def:  Mem11[ds:di:word16] = 0x0000
Mem12: orig: Mem0
    def:  Mem12[ds:di:word16] = 0x0001
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def fp
	def ds
	def si
	def Mem0
	def di
	// succ:  l0C00_0000
l0C00_0000:
	rLoc1_5 = Mem0[ds:si:real64]
	branch 0.0 == rLoc1_5 l0C00_0012
	// succ:  l0C00_000D l0C00_0012
l0C00_000D:
	Mem12[ds:di:word16] = 0x0001
	return
	// succ:  fn0C00_0000_exit
l0C00_0012:
	Mem11[ds:di:word16] = 0x0000
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	use FPUF_8
	use rLoc1_6
	use rLoc2_7
	use SCZO_9
	use sp_2

