fp:fp
sp_2: orig: sp
Top:Top
    def:  def Top
    uses: branch ST[Top:real64] < ST[ds:bx:real32] l0C00_000C
ST:Global memory
    def:  def ST
    uses: branch ST[Top:real64] < ST[ds:bx:real32] l0C00_000C
ds:ds
    def:  def ds
    uses: branch ST[Top:real64] < ST[ds:bx:real32] l0C00_000C
bx:bx
    def:  def bx
    uses: branch ST[Top:real64] < ST[ds:bx:real32] l0C00_000C
FPUF_7: orig: FPUF
Top_8: orig: Top
SCZO_9: orig: SCZO
ecx:ecx
ecx_11: orig: ecx
SZO_12: orig: SZO
C_13: orig: C
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def Top
	def ST
	def ds
	def bx
	// succ:  l0C00_0000
l0C00_0000:
	branch ST[Top:real64] < ST[ds:bx:real32] l0C00_000C
	// succ:  l0C00_0009 l0C00_000C
l0C00_0009:
	// succ:  l0C00_000C
l0C00_000C:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

