fp:fp
sp_1: orig: sp
rLoc1_2: orig: rLoc1
ds:ds
    def:  def ds
    uses: Mem8[ds:di:word16] = 0x0001
          Mem10[ds:di:word16] = 0x0000
          branch 0.0 >= Mem0[ds:si:real64] l0C00_0010
si:si
    def:  def si
    uses: branch 0.0 >= Mem0[ds:si:real64] l0C00_0010
Mem0:Global memory
    def:  def Mem0
    uses: branch 0.0 >= Mem0[ds:si:real64] l0C00_0010
FPUF_6: orig: FPUF
SCZO_7: orig: SCZO
Mem8: orig: Mem0
    def:  Mem8[ds:di:word16] = 0x0001
di:di
    def:  def di
    uses: Mem8[ds:di:word16] = 0x0001
          Mem10[ds:di:word16] = 0x0000
Mem10: orig: Mem0
    def:  Mem10[ds:di:word16] = 0x0000
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def ds
	def si
	def Mem0
	def di
	// succ:  l0C00_0000
l0C00_0000:
	branch 0.0 >= Mem0[ds:si:real64] l0C00_0010
	// succ:  l0C00_000B l0C00_0010
l0C00_000B:
	Mem8[ds:di:word16] = 0x0001
	return
	// succ:  fn0C00_0000_exit
l0C00_0010:
	Mem10[ds:di:word16] = 0x0000
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

