fp0_3: orig: fp0
    def:  fp0_3 = (real80) Mem0[a6 - 0x00000010:int32]
    uses: branch (real96) fp0_3 == Mem0[a6 + 0x00000008:real96] l1
NZCV_4: orig: NZCV
a6:a6
    def:  def a6
    uses: fp0_3 = (real80) Mem0[a6 - 0x00000010:int32]
          branch (real96) fp0_3 == Mem0[a6 + 0x00000008:real96] l1
Mem0:Global
    def:  def Mem0
    uses: fp0_3 = (real80) Mem0[a6 - 0x00000010:int32]
          branch (real96) fp0_3 == Mem0[a6 + 0x00000008:real96] l1
// FCmpFragment
// Return size: 0
define FCmpFragment
FCmpFragment_entry:
	def a6
	def Mem0
	// succ:  l1
l1:
	fp0_3 = (real80) Mem0[a6 - 0x00000010:int32]
	branch (real96) fp0_3 == Mem0[a6 + 0x00000008:real96] l1
	// succ:  l2 l1
l2:
	return
	// succ:  FCmpFragment_exit
FCmpFragment_exit:

