r1:r1
    def:  def r1
    uses: v8_10 = SEQ(r1, r2) >>u 0x01
r1_1: orig: r1
    def:  r1_1 = SLICE(v8_10, word32, 32)
    uses: Mem7[0x00003004:word32] = r1_1
r2:r2
    def:  def r2
    uses: v8_10 = SEQ(r1, r2) >>u 0x01
r2_4: orig: r2
    def:  r2_4 = (word32) v8_10
    uses: Mem6[0x00003000:word32] = r2_4
C_5: orig: C
Mem6: orig: Mem0
    def:  Mem6[0x00003000:word32] = r2_4
Mem7: orig: Mem0
    def:  Mem7[0x00003004:word32] = r1_1
v6_8: orig: v6
v7_9: orig: v7
v8_10: orig: v8
    def:  v8_10 = SEQ(r1, r2) >>u 0x01
    uses: r1_1 = SLICE(v8_10, word32, 32)
          r2_4 = (word32) v8_10
// main
// Return size: 0
void main(word32 r1, word32 r2)
main_entry:
	def r1
	def r2
	// succ:  l1
l1:
	v8_10 = SEQ(r1, r2) >>u 0x01
	r1_1 = SLICE(v8_10, word32, 32)
	r2_4 = (word32) v8_10
	Mem6[0x00003000:word32] = r2_4
	Mem7[0x00003004:word32] = r1_1
main_exit:

