Mem0:Global memory
fp:fp
C:Flags
r1:r1
    def:  def r1
    uses: def r1
          C_7 = cond(r1 >>u 0x01)
          Mem10[0x00003000:word32] = r1 >>u 0x01
r2:r2
    def:  def r2
    uses: def r2
          r2_8 = __rcr(r2, C_7)
r63:r63
r1_6: orig: r1
C_7: orig: C
    def:  C_7 = cond(r1 >>u 0x01)
    uses: r2_8 = __rcr(r2, C_7)
r2_8: orig: r2
    def:  r2_8 = __rcr(r2, C_7)
    uses: Mem11[0x00003004:word32] = r2_8
C_9: orig: C
Mem10: orig: Mem0
    def:  Mem10[0x00003000:word32] = r1 >>u 0x01
Mem11: orig: Mem0
    def:  Mem11[0x00003004:word32] = r2_8
// main
void main(word32 r1, word32 r2)
main_entry:
	def r1
	def r2
	// succ:  l1
l1:
	C_7 = cond(r1 >>u 0x01)
	r2_8 = __rcr(r2, C_7)
	r1_r2_9 = r1_r2_9 >> 0x01
	Mem10[0x00003000:word32] = r1 >>u 0x01
	Mem11[0x00003004:word32] = r2_8
main_exit:

