fp:fp
r63_2: orig: r63
r2:r2
    def:  def r2
    uses: r3_4 = r2()
          call r3_4 + 0x00000004 (retsize: 4;)	uses: r2:r2,r3:r3_4 + 0x00000004
r3_4: orig: r3
    def:  r3_4 = r2()
    uses: call r3_4 + 0x00000004 (retsize: 4;)	uses: r2:r2,r3:r3_4 + 0x00000004
          call r3_4 + 0x00000004 (retsize: 4;)	uses: r2:r2,r3:r3_4 + 0x00000004
r3_5: orig: r3
r2_6: orig: r2
r3_7: orig: r3
r63_8: orig: r63
r63_9: orig: r63
// foo
// Return size: 0
void foo(word32 r2)
foo_entry:
	def r2
	// succ:  l1
l1:
	r3_4 = r2()
	call r3_4 + 0x00000004 (retsize: 4;)
		uses: r2:r2,r3:r3_4 + 0x00000004
	return
	// succ:  foo_exit
foo_exit:

