r2:r2
    def:  def r2
    uses: call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
          call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
r3_1: orig: r3
r3_2: orig: r3
    uses: call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
r2_3: orig: r2
    def:  call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
r3_4: orig: r3
    def:  call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
r63_5: orig: r63
    def:  call r2() + 0x00000004 (retsize: 4; depth: 4)	uses: r2,r3_2	defs: r2_3,r3_4,r63_5
// foo
// Return size: 0
void foo(word32 r2)
foo_entry:
	def r2
	// succ:  l1
l1:
	call r2() + 0x00000004 (retsize: 4; depth: 4)
		uses: r2,r3_2
		defs: r2_3,r3_4,r63_5
	return
	// succ:  foo_exit
foo_exit:

