Mem0:Global memory
    def:  def Mem0
    uses: ax_7 = Mem0[ds:si + 0x0200:word16]
fp:Temporary
sp:sp
si:si
    def:  def si
    uses: ax_7 = Mem0[ds:si + 0x0200:word16]
          Mem11[ds:0x0202:word16] = Mem9[ds:si + 0x0202:word16]
          Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
ds:ds
    def:  def ds
    uses: ax_8 = Mem0[ds:si + 0x0200:word16]
          Mem9[ds:0x0200:word16] = 0x0000
          Mem10[ds:0x0300:word16] = ax_8
          Mem12[ds:0x0202:word16] = Mem10[ds:si + 0x0202:word16]
          Mem12[ds:0x0202:word16] = Mem10[ds:si + 0x0202:word16]
          Mem15[ds:0x0204:word16] = Mem12[ds:0x0204:word16] + Mem12[ds:si + 0x0204:word16]
          Mem15[ds:0x0204:word16] = Mem12[ds:0x0204:word16] + Mem12[ds:si + 0x0204:word16]
          Mem15[ds:0x0204:word16] = Mem12[ds:0x0204:word16] + Mem12[ds:si + 0x0204:word16]
          ax_17 = Mem15[ds:0x0200:word16]
          fn0C00_002A(ds)
          Mem18[ds:0x0200:word16] = ax_17
ax:ax
v6:Temporary
SCZO:Flags
ax_8: orig: ax
    def:  ax_7 = Mem0[ds:si + 0x0200:word16]
    uses: Mem9[ds:0x0300:word16] = ax_7
Mem8: orig: Mem0
    def:  Mem8[ds:0x0200:word16] = 0x0000
Mem9: orig: Mem0
    def:  Mem9[ds:0x0300:word16] = ax_7
    uses: Mem11[ds:0x0202:word16] = Mem9[ds:si + 0x0202:word16]
ax_10: orig: ax
    uses: Mem11[ds:0x0202:word16] = Mem9[ds:si + 0x0202:word16]
Mem11: orig: Mem0
    def:  Mem11[ds:0x0202:word16] = Mem9[ds:si + 0x0202:word16]
    uses: Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
          Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
ax_12: orig: ax
v5_13: orig: v5
    uses: Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
Mem14: orig: Mem0
    def:  Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
    uses: ax_16 = Mem14[ds:0x0200:word16]
SCZO_15: orig: SCZO
ax_16: orig: ax
    def:  ax_16 = Mem14[ds:0x0200:word16]
    uses: Mem17[ds:0x0200:word16] = ax_16
Mem17: orig: Mem0
    def:  Mem17[ds:0x0200:word16] = ax_16
// fn0C00_0000
void fn0C00_0000(word16 si, selector ds)
fn0C00_0000_entry:
	def Mem0
	def si
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	ax_7 = Mem0[ds:si + 0x0200:word16]
	Mem8[ds:0x0200:word16] = 0x0000
	Mem9[ds:0x0300:word16] = ax_7
	Mem12[ds:0x0202:word16] = Mem10[ds:si + 0x0202:word16]
	Mem14[ds:0x0204:word16] = Mem11[ds:0x0204:word16] + Mem11[ds:si + 0x0204:word16]
	ax_17 = Mem15[ds:0x0200:word16]
	fn0C00_002A(ds)
	Mem18[ds:0x0200:word16] = ax_17
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	// succ: 

Mem0:Global memory
fp:Temporary
ax:ax
wLoc04:Local -0004
ds:ds
    def:  def ds
    uses: Mem6[ds:0x0200:word16] = 0xFFFF
wLoc04_5: orig: wLoc04
Mem6: orig: Mem0
    def:  Mem6[ds:0x0200:word16] = 0xFFFF
ax_7: orig: ax
// fn0C00_002A
void fn0C00_002A(selector ds)
fn0C00_002A_entry:
	def ds
	// succ: l0C00_002A
l0C00_002A:
	Mem6[ds:0x0200:word16] = 0xFFFF
	return
	// succ:  fn0C00_002A_exit
fn0C00_002A_exit:

