fp:fp
sp_2: orig: sp
Top_3: orig: Top
ds:ds
    def:  def ds
    uses: ax_7 = Mem0[ds:si + 0x200<16>:word16]
          Mem8[ds:0x200<16>:word16] = 0<16>
          Mem9[ds:0x300<16>:word16] = ax_7
          Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
          Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
          ax_16 = Mem14[ds:0x200<16>:word16]
          Mem17[ds:0x200<16>:word16] = ax_16
          fn0C00_002A(ds)
          Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
          Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
          Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
si:si
    def:  def si
    uses: ax_7 = Mem0[ds:si + 0x200<16>:word16]
          Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
          Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
Mem0:Mem
    def:  def Mem0
    uses: ax_7 = Mem0[ds:si + 0x200<16>:word16]
ax_7: orig: ax
    def:  ax_7 = Mem0[ds:si + 0x200<16>:word16]
    uses: Mem9[ds:0x300<16>:word16] = ax_7
Mem8: orig: Mem0
    def:  Mem8[ds:0x200<16>:word16] = 0<16>
Mem9: orig: Mem0
    def:  Mem9[ds:0x300<16>:word16] = ax_7
    uses: Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
ax_10: orig: ax
Mem11: orig: Mem0
    def:  Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
    uses: Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
          Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
ax_12: orig: ax
v7_13: orig: v7
Mem14: orig: Mem0
    def:  Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
    uses: ax_16 = Mem14[ds:0x200<16>:word16]
SCZO_15: orig: SCZO
ax_16: orig: ax
    def:  ax_16 = Mem14[ds:0x200<16>:word16]
    uses: Mem17[ds:0x200<16>:word16] = ax_16
Mem17: orig: Mem0
    def:  Mem17[ds:0x200<16>:word16] = ax_16
C_18: orig: C
O_19: orig: O
S_20: orig: S
Z_21: orig: Z
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, selector ds)
fn0C00_0000_entry:
	def ds
	def si
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	ax_7 = Mem0[ds:si + 0x200<16>:word16]
	Mem8[ds:0x200<16>:word16] = 0<16>
	Mem9[ds:0x300<16>:word16] = ax_7
	Mem11[ds:0x202<16>:word16] = Mem9[ds:si + 0x202<16>:word16]
	Mem14[ds:0x204<16>:word16] = Mem11[ds:0x204<16>:word16] + Mem11[ds:si + 0x204<16>:word16]
	ax_16 = Mem14[ds:0x200<16>:word16]
	fn0C00_002A(ds)
	Mem17[ds:0x200<16>:word16] = ax_16
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
sp_2: orig: sp
Top_3: orig: Top
sp_4: orig: sp
ax:ax
ss:ss
Mem7: orig: Mem0
ds:ds
    def:  def ds
    uses: Mem9[ds:0x200<16>:word16] = 0xFFFF<16>
Mem9: orig: Mem0
    def:  Mem9[ds:0x200<16>:word16] = 0xFFFF<16>
ax_10: orig: ax
sp_11: orig: sp
wLoc02_12: orig: wLoc02
// fn0C00_002A
// Return size: 0
void fn0C00_002A(selector ds)
fn0C00_002A_entry:
	def ds
	// succ:  l0C00_002A
l0C00_002A:
	Mem9[ds:0x200<16>:word16] = 0xFFFF<16>
	return
	// succ:  fn0C00_002A_exit
fn0C00_002A_exit:

