fp:fp
sp_2: orig: sp
Top_3: orig: Top
ds:ds
    def:  def ds
    uses: ax_7 = Mem0[ds:bx + 0x0004:word16]
          Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
          Mem13[ds:si + 0x04D4:word16] = si + 0x0002
bx:bx
    def:  def bx
    uses: ax_7 = Mem0[ds:bx + 0x0004:word16]
          Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
Mem0:Global memory
    def:  def Mem0
    uses: ax_7 = Mem0[ds:bx + 0x0004:word16]
ax_7: orig: ax
    def:  ax_7 = Mem0[ds:bx + 0x0004:word16]
    uses: Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
          Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
ax_8: orig: ax
SCZO_9: orig: SCZO
Mem10: orig: Mem0
    def:  Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
si:si
    def:  def si
    uses: Mem13[ds:si + 0x04D4:word16] = si + 0x0002
          Mem13[ds:si + 0x04D4:word16] = si + 0x0002
bx_12: orig: bx
Mem13: orig: Mem0
    def:  Mem13[ds:si + 0x04D4:word16] = si + 0x0002
ax_14: orig: ax
SZO_15: orig: SZO
C_16: orig: C
O_17: orig: O
S_18: orig: S
Z_19: orig: Z
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, word16 si, selector ds)
fn0C00_0000_entry:
	def ds
	def bx
	def Mem0
	def si
	// succ:  l0C00_0000
l0C00_0000:
	ax_7 = Mem0[ds:bx + 0x0004:word16]
	Mem10[ds:bx + 0x0006:word16] = ax_7 *s ax_7
	Mem13[ds:si + 0x04D4:word16] = si + 0x0002
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

