fp:fp
sp_2: orig: sp
Top_3: orig: Top
ax_4: orig: ax
bx_5: orig: bx
cx_6: orig: cx
ds:ds
    def:  def ds
    uses: Mem8[ds:0x300<16>:word16] = 4<16>
Mem8: orig: Mem0
    def:  Mem8[ds:0x300<16>:word16] = 4<16>
bx_9: orig: bx
ax_10: orig: ax
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	Mem8[ds:0x300<16>:word16] = 4<16>
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

