fp:fp
sp_2: orig: sp
edx:edx
    def:  def edx
    uses: Mem4[ds:0x7960:word32] = edx
          Mem13[ds:si + 0x00C8:word32] = -edx
Mem4: orig: Mem0
    def:  Mem4[ds:0x7960:word32] = edx
ds:ds
    def:  def ds
    uses: Mem4[ds:0x7960:word32] = edx
          Mem7[ds:0x7964:byte] = cl
          Mem13[ds:si + 0x00C8:word32] = -edx
cl:cl
    def:  def cl
    uses: Mem7[ds:0x7964:byte] = cl
Mem7: orig: Mem0
    def:  Mem7[ds:0x7964:byte] = cl
eax_8: orig: eax
eax_9: orig: eax
SCZO_10: orig: SCZO
C_11: orig: C
SCZO_12: orig: SCZO
Mem13: orig: Mem0
    def:  Mem13[ds:si + 0x00C8:word32] = -edx
si:si
    def:  def si
    uses: Mem13[ds:si + 0x00C8:word32] = -edx
// fn0C00_0000
// Return size: 0
void fn0C00_0000(byte cl, word32 edx, word16 si, selector ds)
fn0C00_0000_entry:
	def edx
	def ds
	def cl
	def si
	// succ:  l0C00_0000
l0C00_0000:
	Mem4[ds:0x7960:word32] = edx
	Mem7[ds:0x7964:byte] = cl
	Mem13[ds:si + 0x00C8:word32] = -edx
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

