Mem0: Mem0:Global memory
fp: fp:Temporary
si: si:Register
ax: ax:Register
ds: ds:Register, def: {def ds}, uses: {store(Mem8[ds:0x0202:word16]) = fn0C00_0015(0x0200, ds)}{store(Mem8[ds:0x0202:word16]) = fn0C00_0015(0x0200, ds)}{store(Mem12[ds:0x0302:byte]) = (byte) fn0C00_0015(0x0300, ds)}{store(Mem12[ds:0x0302:byte]) = (byte) fn0C00_0015(0x0300, ds)}
al: al:Register
si_6: orig: si
ax_7: orig: ax, uses: {store(Mem8[ds:0x0202:word16]) = fn0C00_0015(0x0200, ds)}
Mem8: orig: Mem0, def: {store(Mem8[ds:0x0202:word16]) = fn0C00_0015(0x0200, ds)}
si_9: orig: si
ax_10: orig: ax
al_11: orig: al, uses: {store(Mem12[ds:0x0302:byte]) = (byte) fn0C00_0015(0x0300, ds)}
Mem12: orig: Mem0, def: {store(Mem12[ds:0x0302:byte]) = (byte) fn0C00_0015(0x0300, ds)}
// fn0C00_0000
void fn0C00_0000(segment ds)
fn0C00_0000_entry:		// block 0, pred:
	def ds
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem8[ds:0x0202:word16]) = fn0C00_0015(0x0200, ds)
	store(Mem12[ds:0x0302:byte]) = (byte) fn0C00_0015(0x0300, ds)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

Mem0: Mem0:Global memory, def: {def Mem0}, uses: {return Mem0[ds:si:word16]}
fp: fp:Temporary
si: si:Register, def: {def si}, uses: {return Mem0[ds:si:word16]}
ds: ds:Register, def: {def ds}, uses: {return Mem0[ds:si:word16]}
ax: ax:Register
ax_5: orig: ax, uses: {return Mem0[ds:si:word16]}
// fn0C00_0015
word16 fn0C00_0015(word16 si, segment ds)
fn0C00_0015_entry:		// block 0, pred:
	def Mem0
	def si
	def ds
	// succ:  1
l0C00_0015:		// block 1, pred: 0
	return Mem0[ds:si:word16]
	// succ:  2
fn0C00_0015_exit:		// block 2, pred: 1
	// succ: 

