fp:fp
sp_1: orig: sp
ax_2: orig: ax
    def:  fn0C00_000E(out ax_2)
bx_3: orig: bx
Mem4: orig: Mem0
    def:  Mem4[ds:0x0300:word16] = 0x002B
ds:ds
    def:  def ds
    uses: Mem4[ds:0x0300:word16] = 0x002B
          fn0C00_0015(ax_6, bx_7, ds)
ax_6: orig: ax
    def:  bx_7 = fn0C00_000E(out ax_6)
    uses: fn0C00_0015(ax_6, bx_7, ds)
bx_7: orig: bx
    def:  bx_7 = fn0C00_000E(out ax_6)
    uses: fn0C00_0015(ax_6, bx_7, ds)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_000E(out ax_2)
	Mem4[ds:0x0300:word16] = 0x002B
	bx_7 = fn0C00_000E(out ax_6)
	fn0C00_0015(ax_6, bx_7, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
sp_1: orig: sp
ax_2: orig: ax
    def:  ax_2 = 0x002A
    uses: use ax_2 (=> axOut)
bx_3: orig: bx
axOut:Out:ax
// fn0C00_000E
// Return size: 0
word16 fn0C00_000E(ptr16 axOut)
fn0C00_000E_entry:
	// succ:  l0C00_000E
l0C00_000E:
	ax_2 = 0x002A
	return 0x002B
	// succ:  fn0C00_000E_exit
fn0C00_000E_exit:
	use ax_2 (=> axOut)

fp:fp
sp_1: orig: sp
ax:ax
    def:  def ax
    uses: Mem3[ds:0x0400:word16] = ax
Mem3: orig: Mem0
    def:  Mem3[ds:0x0400:word16] = ax
ds:ds
    def:  def ds
    uses: Mem3[ds:0x0400:word16] = ax
          Mem6[ds:0x0402:word16] = bx
bx:bx
    def:  def bx
    uses: Mem6[ds:0x0402:word16] = bx
Mem6: orig: Mem0
    def:  Mem6[ds:0x0402:word16] = bx
// fn0C00_0015
// Return size: 0
void fn0C00_0015(word16 ax, word16 bx, selector ds)
fn0C00_0015_entry:
	def ax
	def ds
	def bx
	// succ:  l0C00_0015
l0C00_0015:
	Mem3[ds:0x0400:word16] = ax
	Mem6[ds:0x0402:word16] = bx
	return
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:

