fp:fp
sp_2: orig: sp
si:si
    def:  def si
    uses: si_6 = PHI(si, si_9, si_9)
          ax_23 = si_9 - si
bx_4: orig: bx
ds_5: orig: ds
    def:  ds_5 = PHI(ds, ds_5, ds_5)
si_6: orig: si
    def:  si_6 = PHI(si, si_9, si_9)
    uses: ax_8 = Mem7[ds:si_6:word16]
          si_9 = si_6 + 0x0002
Mem7: orig: Mem0
    def:  Mem7 = PHI(Mem0, Mem12, Mem18)
    uses: ax_8 = Mem7[ds:si_6:word16]
ax_8: orig: ax
    def:  ax_8 = Mem7[ds:si_6:word16]
    uses: Mem12[ds:di:word16] = ax_8
          branch ax_8 != 0x0020 l0C00_0005
          branch ax_8 != 0x0000 l0C00_0011
          branch ax_8 != 0x000D l0C00_001A
si_9: orig: si
    def:  si_9 = si_6 + 0x0002
    uses: si_6 = PHI(si, si_9, si_9)
          si_6 = PHI(si, si_9, si_9)
          ax_23 = si_9 - si
SCZO_10: orig: SCZO
di_11: orig: di
    def:  di_11 = PHI(di, di_11, di_11)
Mem12: orig: Mem0
    def:  Mem12[ds:di:word16] = ax_8
    uses: Mem18[ds:0x0302:word16] = Mem12[ds:0x0302:word16] + 0x0001
          Mem7 = PHI(Mem0, Mem12, Mem18)
ax_13: orig: ax
SZO_14: orig: SZO
C_15: orig: C
SCZO_16: orig: SCZO
v12_17: orig: v12
Mem18: orig: Mem0
    def:  Mem18[ds:0x0302:word16] = Mem12[ds:0x0302:word16] + 0x0001
    uses: Mem7 = PHI(Mem0, Mem12, Mem18)
SZO_19: orig: SZO
ax_20: orig: ax
    def:  ax_20 = 0xFFFF
    uses: ax_25 = PHI(ax_23, ax_20)
ax_21: orig: ax
bx_22: orig: bx
    def:  bx_22 = PHI(bx_4, bx_22, bx_22)
ax_23: orig: ax
    def:  ax_23 = si_9 - si
    uses: ax_25 = PHI(ax_23, ax_20)
SCZO_24: orig: SCZO
ax_25: orig: ax
    def:  ax_25 = PHI(ax_23, ax_20)
    uses: Mem27[ds:0x0300:word16] = ax_25
ds_26: orig: ds
    def:  ds_26 = PHI(ds_5, ds_5)
Mem27: orig: Mem0
    def:  Mem27[ds:0x0300:word16] = ax_25
ds:ds
    def:  def ds
    uses: ax_8 = Mem7[ds:si_6:word16]
          Mem12[ds:di:word16] = ax_8
          Mem18[ds:0x0302:word16] = Mem12[ds:0x0302:word16] + 0x0001
          Mem18[ds:0x0302:word16] = Mem12[ds:0x0302:word16] + 0x0001
          Mem27[ds:0x0300:word16] = ax_25
Mem0:Global memory
    def:  def Mem0
    uses: Mem7 = PHI(Mem0, Mem12, Mem18)
di:di
    def:  def di
    uses: Mem12[ds:di:word16] = ax_8
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def si
	def ds
	def Mem0
	def di
	// succ:  l0C00_0000
l0C00_0000:
	goto l0C00_001A
	// succ:  l0C00_001A
l0C00_0005:
	Mem12[ds:di:word16] = ax_8
	branch ax_8 != 0x0000 l0C00_0011
	// succ:  l0C00_000B l0C00_0011
l0C00_000B:
	ax_20 = 0xFFFF
	goto l0C00_0024
	// succ:  l0C00_0024
l0C00_0011:
	branch ax_8 != 0x000D l0C00_001A
	// succ:  l0C00_0016 l0C00_001A
l0C00_0016:
	Mem18[ds:0x0302:word16] = Mem12[ds:0x0302:word16] + 0x0001
	// succ:  l0C00_001A
l0C00_001A:
	Mem7 = PHI(Mem0, Mem12, Mem18)
	si_6 = PHI(si, si_9, si_9)
	ax_8 = Mem7[ds:si_6:word16]
	si_9 = si_6 + 0x0002
	branch ax_8 != 0x0020 l0C00_0005
	// succ:  l0C00_0020 l0C00_0005
l0C00_0020:
	ax_23 = si_9 - si
	// succ:  l0C00_0024
l0C00_0024:
	ax_25 = PHI(ax_23, ax_20)
	Mem27[ds:0x0300:word16] = ax_25
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

