void fn0C00_0000(Register selector ds)
// MayUse:  ds:16
// LiveOut:
// Trashed: SCZO ax bx
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// rLoc1:FPU stack
// ds:ds
// rLoc2:FPU stack
// ss:ss
// ax:ax
// SCZO:SCZO
// bx:bx
// wLoc02:Local -0002
// wLoc04:Local -0004
// S:S
// C:C
// Z:Z
// O:O
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	rLoc1_5 = (real64) Mem0[ds:0x0300:real32]
	rLoc2_6 = (real64) Mem0[ds:0x0304:real32]
	fn0C00_0024(ds, 0x0308, rLoc2_6, rLoc1_5)
	Mem12[ds:0x030C:real32] = 0.0F
	ax_13 = Mem12[ds:0x0308:word16]
	rLoc1_17 = fn0C00_0031(ds, ax_13)
	Mem18[ds:0x030C:real32] = (real32) rLoc1_17
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
void fn0C00_0024(Register selector ds, Stack word16 wArg02, FpuStack real64 rArg0, FpuStack real64 rArg1)
// MayUse:  ds:16 FPU stack:16 FPU stack:16 Stack +0002:16
// LiveOut:
// Trashed: bx
// Preserved: bp sp
// fn0C00_0024
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// bx:bx
// rArg0:FPU stack
// ds:ds
// rArg1:FPU stack
// wLoc02:Local -0002
// wArg02:Stack +0002
// return address size: 2
void fn0C00_0024(selector ds, word16 wArg02, real64 rArg0, real64 rArg1)
fn0C00_0024_entry:
	def rArg0
	def ds
	def rArg1
	def wArg02
	// succ:  l0C00_0024
l0C00_0024:
	Mem11[ds:wArg02:real32] = (real32) rArg0
	Mem13[ds:wArg02 + 0x0004:real32] = (real32) rArg1
	return
	// succ:  fn0C00_0024_exit
fn0C00_0024_exit:
FpuStack real64 fn0C00_0031(Register selector ds, Stack word16 wArg02)
// MayUse:  ds:16 Stack +0002:16
// LiveOut: 
// Trashed: bx
// Preserved: bp sp
// fn0C00_0031
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// bx:bx
// rLoc1:FPU stack
// ds:ds
// wLoc02:Local -0002
// wArg02:Stack +0002
// return address size: 2
real64 fn0C00_0031(selector ds, word16 wArg02)
fn0C00_0031_entry:
	def ds
	def wArg02
	// succ:  l0C00_0031
l0C00_0031:
	rLoc1_10 = (real64) Mem6[ds:wArg02:real32]
	return rLoc1_10
	// succ:  fn0C00_0031_exit
fn0C00_0031_exit:
