void fn0C00_0000(Register selector ds)
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: SCZO ax bx di si Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Global
// fp:fp
// sp:sp
// di:di
// ds:ds
// si:si
// ax:ax
// bx:bx
// Top:Top
// S:S
// C:C
// Z:Z
// O:O
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	di_6 = Mem0[ds:0x0100:word16]
	si_7 = Mem0[ds:di_6:word16]
	ax_8 = fn0C00_0026(si_7, ds)
	Mem13[ds:di_6 + 0x0002:word16] = ax_8
	bx_14 = Mem13[ds:0x0102:word16]
	si_15 = Mem13[ds:bx_14 + 0x0004:word16]
	ax_16 = fn0C00_0026(si_15, ds)
	Mem21[ds:bx_14 + 0x0008:word16] = ax_16
	di_22 = Mem21[ds:0x0104:word16]
	si_23 = Mem21[ds:di_22:word16]
	ax_24 = fn0C00_0033(si_23, ds)
	Mem29[ds:di_22 + 0x0002:word16] = ax_24
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
Register word16 fn0C00_0026(Register word16 si, Register selector ds)
// MayUse:  ds:[0..15] si:[0..15]
// LiveOut: ax
// Trashed: SCZO ax Top
// Preserved: di sp
// fn0C00_0026
// Return size: 0
// Mem0:Global
// fp:fp
// sp:sp
// di:di
// ss:ss
// ds:ds
// v6:v6
// SZO:SZO
// Top:Top
// si:si
// ax:ax
// S:S
// C:C
// Z:Z
// O:O
// wLoc02:Local -0002
// return address size: 2
word16 fn0C00_0026(word16 si, selector ds)
fn0C00_0026_entry:
	def ds
	def si
	// succ:  l0C00_0026
l0C00_0026:
	di_9 = Mem7[ds:0x0104:word16]
	v6_10 = Mem7[ds:di_9 + 0x0030:word16] + 0x0001
	Mem11[ds:di_9 + 0x0030:word16] = v6_10
	ax_14 = fn0C00_0033(si, ds)
	return ax_14
	// succ:  fn0C00_0026_exit
fn0C00_0026_exit:
Register word16 fn0C00_0033(Register word16 si, Register selector ds)
// MayUse:  ds:[0..15] si:[0..15]
// LiveOut: ax
// Trashed: SCZO ax Top
// Preserved: sp
// fn0C00_0033
// Return size: 0
// Mem0:Global
// fp:fp
// sp:sp
// ax:ax
// si:si
// ds:ds
// SCZO:SCZO
// Top:Top
// S:S
// C:C
// Z:Z
// O:O
// return address size: 2
word16 fn0C00_0033(word16 si, selector ds)
fn0C00_0033_entry:
	def ds
	def si
	def Mem0
	// succ:  l0C00_0033
l0C00_0033:
	ax_7 = Mem0[ds:si:word16]
	ax_8 = ax_7 * 0x0002
	return ax_8
	// succ:  fn0C00_0033_exit
fn0C00_0033_exit:
