void fn0C00_0000(Register selector ds)
// MayUse:  ds:[0..15]
// DataTypes: 
//   ds: (ptr16 (segment 1302))
// LiveOut:
// Trashed: SCZO ax Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// sp:sp
// ss:ss
// SCZO:SCZO
// ds:ds
// ax:ax
// Top:Top
// S:S
// C:C
// Z:Z
// O:O
// wLoc02:Stack -0002
// wLoc04:Stack -0004
// wLoc06:Stack -0006
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	ax_11 = fn0C00_0011(1<16>, 2<16>, 3<16>)
	Mem19[ds:0x1300<16>:word16] = ax_11
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
Register word16 fn0C00_0011(Stack word16 wArg02, Stack word16 wArg04, Stack word16 wArg06)
// MayUse:  Stack +0002:[0..15] Stack +0004:[0..15] Stack +0006:[0..15]
// DataTypes: 
//   Stack +0002: word16
//   Stack +0004: word16
//   Stack +0006: word16
// LiveOut: ax
// Trashed: SCZO ax Top
// Preserved: bp sp
// fn0C00_0011
// Return size: 0
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// sp:sp
// bp:bp
// ss:ss
// ax:ax
// SCZO:SCZO
// Top:Top
// wLoc02:Stack -0002
// wArg02:Stack +0002
// wArg04:Stack +0004
// wArg06:Stack +0006
// S:S
// C:C
// Z:Z
// O:O
// return address size: 2
word16 fn0C00_0011(word16 wArg02, word16 wArg04, word16 wArg06)
fn0C00_0011_entry:
	def wArg02
	def wArg04
	def wArg06
	// succ:  l0C00_0011
l0C00_0011:
	ax_10 = wArg02 + wArg04
	ax_12 = ax_10 + wArg06
	return ax_12
	// succ:  fn0C00_0011_exit
fn0C00_0011_exit:
