void fn0C00_0000(Register word16 dx)
// MayUse:  dx:0
// LiveOut:
// Trashed: ax dx
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Mem
// fp:fp
// sp:sp
// dx:dx
// ax:ax
// return address size: 2
void fn0C00_0000(word16 dx)
fn0C00_0000_entry:
	def dx
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004(dx)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
void fn0C00_0004(Register word16 dx)
// MayUse:  dx:16
// LiveOut:
// Trashed: ax dx
// Preserved: sp
// fn0C00_0004
// Return size: 0
// Mem0:Mem
// fp:fp
// sp:sp
// dx:dx
// SCZO:Flags
// Z:Flags
// SZO:Flags
// ax:ax
// S:Flags
// C:Flags
// O:Flags
// return address size: 2
void fn0C00_0004(word16 dx)
fn0C00_0004_entry:
	def dx
	// succ:  l0C00_0004
l0C00_0004:
	SCZO_4 = cond(dx - 0x001E)
	branch dx != 0x001E l0C00_000F
	// succ:  l0C00_0009 l0C00_000F
l0C00_0009:
	fn0C00_0013(ax, dx)
	goto l0C00_0010
	// succ:  l0C00_0010
l0C00_000F:
	dx_5 = dx - 0x0001
	SZO_6 = cond(dx - 0x0001)
	// succ:  l0C00_0010
l0C00_0010:
	O_12 = PHI(SCZO_4, SZO_6)
	Z_11 = PHI(SCZO_4, SZO_6)
	S_9 = PHI(SCZO_4, SZO_6)
	dx_7 = PHI(dx, dx_5)
	ax_8 = dx_7
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:
	use ax_8
	use dx_7
	use O_12 | S_9 | SCZO_4 | Z_11
void fn0C00_0013(Register word16 ax, Register word16 dx)
// MayUse:  ax:16 dx:16
// LiveOut:
// Trashed: ax dx
// Preserved: sp
// fn0C00_0013
// Return size: 0
// Mem0:Mem
// fp:fp
// sp:sp
// dx:dx
// SCZO:Flags
// SO:Flags
// SZO:Flags
// ax:ax
// S:Flags
// O:Flags
// C:Flags
// Z:Flags
// return address size: 2
void fn0C00_0013(word16 ax, word16 dx)
fn0C00_0013_entry:
	def dx
	def ax
	// succ:  l0C00_0013
l0C00_0013:
	SCZO_4 = cond(dx - 0x0014)
	branch dx < 0x0014 l0C00_001F
	// succ:  l0C00_0018 l0C00_001F
l0C00_0018:
	dx_7 = dx - 0x0001
	fn0C00_0004(dx)
	goto l0C00_0025
	// succ:  l0C00_0025
l0C00_001F:
	dx_5 = dx - 0x000A
	SCZO_6 = cond(dx - 0x000A)
	fn0C00_0004(dx)
	// succ:  l0C00_0025
l0C00_0025:
	C_14 = PHI(SCZO_4, SCZO_6)
	dx_13 = PHI(dx_7, dx_5)
	ax_11 = ax + 0x0001
	SZO_12 = cond(ax + 0x0001)
	return
	// succ:  fn0C00_0013_exit
fn0C00_0013_exit:
	use C_14 | SZO_12
