void fn0C00_0000(Register word16 ax, Register word16 bx, Register selector ds)
// MayUse:  ax bx ds
// LiveOut:
// Trashed: SCZO ah al ax eax rax
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// ax:ax
// bx:bx
// SCZO:Flags
// Z:Flags
// ds:ds
// return address size: 2
void fn0C00_0000(word16 ax, word16 bx, selector ds)
fn0C00_0000_entry:
	sp = fp
	// succ:  l0C00_0000
l0C00_0000:
	SCZO = cond(ax - bx)
	branch Test(EQ,Z) l0C00_000A
	// succ:  l0C00_0004 l0C00_000A
l0C00_0004:
	ax = 0x0000
	goto l0C00_000D
	// succ:  l0C00_000D
l0C00_000A:
	ax = 0x0001
	// succ:  l0C00_000D
l0C00_000D:
	Mem0[ds:0x0064:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
