void fn0C00_0000(Register word16 ax, Register word16 bx, Register selector ds)
// MayUse:  ax:[0..15] bx:[0..15] ds:[0..15]
// DataTypes: 
//   ax: word16
//   bx: word16
//   ds: (ptr16 (segment (64 word16 w0064)))
// LiveOut:
// Trashed: SCZO ax Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Mem
// fp:fp
// sp:sp
// ax:ax
// bx:bx
// SCZO:SCZO
// Z:Z
// ds:ds
// Top:Top
// S:S
// C:C
// O:O
// return address size: 2
void fn0C00_0000(word16 ax, word16 bx, selector ds)
fn0C00_0000_entry:
	def ax
	def bx
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	branch ax == bx l0C00_000A
	// succ:  l0C00_0004 l0C00_000A
l0C00_0004:
	ax_9 = 0<16>
	goto l0C00_000D
	// succ:  l0C00_000D
l0C00_000A:
	ax_8 = 1<16>
	// succ:  l0C00_000D
l0C00_000D:
	ax_10 = PHI((ax_9, l0C00_0004), (ax_8, l0C00_000A))
	Mem13[ds:0x64<16>:word16] = ax_10
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
