void fn0C00_0000(Register word16 ax, Register word16 bx, Register selector ds)
// MayUse:  ax:16 bx:16 ds:16
// LiveOut:
// Trashed: SCZO ax
// Preserved: sp
// fn0C00_0000
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// ax:ax
// bx:bx
// SCZO:SCZO
// Z:Z
// ds:ds
// S:S
// C:C
// O:O
// return address size: 2
void fn0C00_0000(word16 ax, word16 bx, selector ds)
fn0C00_0000_entry:
	def ax
	def bx
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	branch ax == bx l0C00_000A
	// succ:  l0C00_0004 l0C00_000A
l0C00_0004:
	ax_8 = 0x0000
	goto l0C00_000D
	// succ:  l0C00_000D
l0C00_000A:
	ax_7 = 0x0001
	// succ:  l0C00_000D
l0C00_000D:
	ax_9 = PHI(ax_8, ax_7)
	Mem12[ds:0x0064:word16] = ax_9
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
