fp:fp
sp_2: orig: sp
Top_3: orig: Top
sp_4: orig: sp
si:si
ss:ss
Mem7: orig: Mem0
sp_8: orig: sp
di:di
    def:  def di
    uses: di_25 = PHI((di, l0C00_0008), (di_27, l0C00_0012))
Mem10: orig: Mem0
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
si_11: orig: si
    def:  si_11 = 0<16>
    uses: si_15 = PHI((si_11, l0C00_0008), (si_26, l0C00_0012))
S_37: orig: S
SCZO_13: orig: SCZO
Z_14: orig: Z
si_15: orig: si
    def:  si_15 = PHI((si_11, l0C00_0008), (si_26, l0C00_0012))
    uses: ax_16 = si_15
          si_26 = si_15 + Mem10[ds:di_25:word16]
ax_16: orig: ax
    def:  ax_16 = si_15
    uses: return ax_16
C_35: orig: C
O_36: orig: O
wLoc04_32: orig: wLoc04
di_20: orig: di
sp_21: orig: sp
si_22: orig: si
sp_23: orig: sp
wLoc02_31: orig: wLoc02
di_25: orig: di
    def:  di_25 = PHI((di, l0C00_0008), (di_27, l0C00_0012))
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
          di_27 = di_25 + 2<16>
si_26: orig: si
    def:  si_26 = si_15 + Mem10[ds:di_25:word16]
    uses: si_15 = PHI((si_11, l0C00_0008), (si_26, l0C00_0012))
di_27: orig: di
    def:  di_27 = di_25 + 2<16>
    uses: di_25 = PHI((di, l0C00_0008), (di_27, l0C00_0012))
SCZO_28: orig: SCZO
cx:cx
    def:  def cx
    uses: branch cx == 0<16> l0C00_001A
ds:ds
    def:  def ds
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
// fn0C00_0008
// Return size: 0
word16 fn0C00_0008(word16 cx, word16 di, selector ds)
fn0C00_0008_entry:
	def di
	def cx
	def ds
	// succ:  l0C00_0008
l0C00_0008:
	si_11 = 0<16>
	// succ:  l0C00_000D
l0C00_000D:
	di_25 = PHI((di, l0C00_0008), (di_27, l0C00_0012))
	si_15 = PHI((si_11, l0C00_0008), (si_26, l0C00_0012))
	branch cx == 0<16> l0C00_001A
	// succ:  l0C00_0012 l0C00_001A
l0C00_0012:
	si_26 = si_15 + Mem10[ds:di_25:word16]
	di_27 = di_25 + 2<16>
	goto l0C00_000D
	// succ:  l0C00_000D
l0C00_001A:
	ax_16 = si_15
	return ax_16
	// succ:  fn0C00_0008_exit
fn0C00_0008_exit:
fp:fp
sp_2: orig: sp
Top_3: orig: Top
cx_4: orig: cx
di:di
    def:  def di
    uses: ax_7 = fn0C00_0008(0x14<16>, di, ds)
          fn0C00_0008(0x14<16>, di, ds)
ds:ds
    def:  ds = SLICE(ds_si, selector, 16)
    uses: ax_7 = fn0C00_0008(0x14<16>, di, ds)
          fn0C00_0008(0x14<16>, di, ds)
ax_7: orig: ax
    def:  ax_7 = fn0C00_0008(0x14<16>, di, ds)
    uses: Mem13[ds_si:word16] = ax_7
S_8: orig: S
C_9: orig: C
Z_10: orig: Z
O_11: orig: O
si:si
Mem13: orig: Mem0
    def:  Mem13[ds_si:word16] = ax_7
ax_14: orig: ax
S_15: orig: S
C_16: orig: C
Z_17: orig: Z
O_18: orig: O
ds_si:Sequence ds:si
    def:  def ds_si
    uses: Mem13[ds_si:word16] = ax_7
          ds = SLICE(ds_si, selector, 16)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(segptr32 ds_si, word16 di)
fn0C00_0000_entry:
	def ds_si
	def di
	ds = SLICE(ds_si, selector, 16)
	// succ:  l0C00_0000
l0C00_0000:
	ax_7 = fn0C00_0008(0x14<16>, di, ds)
	Mem13[ds_si:word16] = ax_7
	// succ:  l0C00_0006_thunk_fn0C00_0008
l0C00_0006_thunk_fn0C00_0008:
	fn0C00_0008(0x14<16>, di, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
