fp:fp
sp_1: orig: sp
cx_2: orig: cx
v4_3: orig: v4
sp_4: orig: sp
wLoc02_5: orig: wLoc02
    def:  wLoc02_5 = 0x0064
    uses: ax_6 = fn0C00_000F(wLoc02_5)
ax_6: orig: ax
    def:  ax_6 = fn0C00_000F(wLoc02_5)
    uses: Mem9[ds:0x0064:word16] = ax_6
sp_7: orig: sp
SCZO_8: orig: SCZO
Mem9: orig: Mem0
    def:  Mem9[ds:0x0064:word16] = ax_6
ds:ds
    def:  def ds
    uses: Mem9[ds:0x0064:word16] = ax_6
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	wLoc02_5 = 0x0064
	ax_6 = fn0C00_000F(wLoc02_5)
	Mem9[ds:0x0064:word16] = ax_6
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
fp:fp
sp_1: orig: sp
bp:bp
v4_3: orig: v4
sp_4: orig: sp
wLoc02_5: orig: wLoc02
bp_6: orig: bp
wArg02:Stack +0002
    def:  def wArg02
    uses: ax_8 = wArg02
          dx_30 = wArg02
ax_8: orig: ax
    def:  ax_8 = wArg02
    uses: ax_9 = ax_8 - 0x0001
ax_9: orig: ax
    def:  ax_9 = ax_8 - 0x0001
    uses: v9_24 = ax_9
          branch ax_9 == 0x0000 l0C00_0026
dx:dx
dx_ax_11: orig: dx_ax
SZO_12: orig: SZO
Z_13: orig: Z
SCZO_14: orig: SCZO
wLoc04_15: orig: wLoc04
dx_ax_16: orig: dx_ax
ax_17: orig: ax
    def:  ax_17 = PHI(ax_32, ax_37)
    uses: return ax_17
dx_18: orig: dx
SCZO_19: orig: SCZO
SZO_20: orig: SZO
Z_21: orig: Z
bp_22: orig: bp
sp_23: orig: sp
v9_24: orig: v9
    def:  v9_24 = ax_9
    uses: wLoc04_26 = v9_24
sp_25: orig: sp
wLoc04_26: orig: wLoc04
    def:  wLoc04_26 = v9_24
    uses: ax_27 = fn0C00_000F(wLoc04_26)
ax_27: orig: ax
    def:  ax_27 = fn0C00_000F(wLoc04_26)
    uses: dx_ax_31 = dx_30 *s ax_27
sp_28: orig: sp
sp_29: orig: sp
dx_30: orig: dx
    def:  dx_30 = wArg02
    uses: dx_ax_31 = dx_30 *s ax_27
dx_ax_31: orig: dx_ax
    def:  dx_ax_31 = dx_30 *s ax_27
    uses: ax_32 = (word16) dx_ax_31 (alias)
ax_32: orig: ax
    def:  ax_32 = (word16) dx_ax_31 (alias)
    uses: ax_17 = PHI(ax_32, ax_37)
dx_33: orig: dx
SCZO_34: orig: SCZO
SZO_35: orig: SZO
Z_36: orig: Z
ax_37: orig: ax
    def:  ax_37 = 0x0001
    uses: ax_17 = PHI(ax_32, ax_37)
dx_ax_38: orig: dx_ax
wLoc04:Local -0004
// fn0C00_000F
// Return size: 0
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	def wArg02
	// succ:  l0C00_000F
l0C00_000F:
	ax_8 = wArg02
	ax_9 = ax_8 - 0x0001
	branch ax_9 == 0x0000 l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	v9_24 = ax_9
	wLoc04_26 = v9_24
	ax_27 = fn0C00_000F(wLoc04_26)
	dx_30 = wArg02
	dx_ax_31 = dx_30 *s ax_27
	ax_32 = (word16) dx_ax_31 (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_37 = 0x0001
	// succ:  l0C00_0029
l0C00_0029:
	ax_17 = PHI(ax_32, ax_37)
	return ax_17
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:
