fp:fp
sp_2: orig: sp
cx_3: orig: cx
sp_4: orig: sp
wLoc02_5: orig: wLoc02
    def:  wLoc02_5 = 0x0064
    uses: ax_6 = fn0C00_000F(wLoc02_5)
ax_6: orig: ax
    def:  ax_6 = fn0C00_000F(wLoc02_5)
    uses: Mem10[ds:0x0064:word16] = ax_6
sp_7: orig: sp
SCZO_8: orig: SCZO
ds:ds
    def:  def ds
    uses: Mem10[ds:0x0064:word16] = ax_6
Mem10: orig: Mem0
    def:  Mem10[ds:0x0064:word16] = ax_6
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	wLoc02_5 = 0x0064
	ax_6 = fn0C00_000F(wLoc02_5)
	Mem10[ds:0x0064:word16] = ax_6
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
fp:fp
sp_2: orig: sp
sp_3: orig: sp
bp:bp
wLoc02_5: orig: wLoc02
bp_6: orig: bp
wArg02:Stack +0002
    def:  def wArg02
    uses: ax_8 = wArg02
          dx_17 = wArg02
ax_8: orig: ax
    def:  ax_8 = wArg02
    uses: ax_9 = ax_8 - 0x0001
ax_9: orig: ax
    def:  ax_9 = ax_8 - 0x0001
    uses: wLoc04_13 = ax_9
          branch ax_9 == 0x0000 l0C00_0026
SZO_10: orig: SZO
ax_11: orig: ax
    def:  ax_11 = 0x0001
    uses: ax_26 = PHI(ax_20, ax_11)
sp_12: orig: sp
wLoc04_13: orig: wLoc04
    def:  wLoc04_13 = ax_9
    uses: ax_14 = fn0C00_000F(wLoc04_13)
ax_14: orig: ax
    def:  ax_14 = fn0C00_000F(wLoc04_13)
    uses: dx_ax_18 = dx_17 *s ax_14
sp_15: orig: sp
sp_16: orig: sp
dx_17: orig: dx
    def:  dx_17 = wArg02
    uses: dx_ax_18 = dx_17 *s ax_14
dx_ax_18: orig: dx_ax
    def:  dx_ax_18 = dx_17 *s ax_14
    uses: ax_20 = (word16) dx_ax_18 (alias)
dx_19: orig: dx
ax_20: orig: ax
    def:  ax_20 = (word16) dx_ax_18 (alias)
    uses: ax_26 = PHI(ax_20, ax_11)
SCZO_21: orig: SCZO
wLoc02_22: orig: wLoc02
    def:  wLoc02_22 = PHI(wLoc02_5, wLoc02_5)
bp_23: orig: bp
fp_24: orig: fp
    def:  fp_24 = PHI(fp, fp)
sp_25: orig: sp
ax_26: orig: ax
    def:  ax_26 = PHI(ax_20, ax_11)
    uses: return ax_26
// fn0C00_000F
// Return size: 0
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	def wArg02
	// succ:  l0C00_000F
l0C00_000F:
	ax_8 = wArg02
	ax_9 = ax_8 - 0x0001
	branch ax_9 == 0x0000 l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	wLoc04_13 = ax_9
	ax_14 = fn0C00_000F(wLoc04_13)
	dx_17 = wArg02
	dx_ax_18 = dx_17 *s ax_14
	ax_20 = (word16) dx_ax_18 (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_11 = 0x0001
	// succ:  l0C00_0029
l0C00_0029:
	ax_26 = PHI(ax_20, ax_11)
	return ax_26
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:
