Mem0:Global memory
fp:Temporary
sp:sp
cx:cx
ss:ss
SCZO:Flags
ds:ds
    def:  def ds
    uses: Mem15[ds:0x0064:word16] = ax_12
ax:ax
wLoc02:Local -0002
cx_9: orig: cx
sp_10: orig: sp
wLoc02_11: orig: wLoc02
    def:  wLoc02_11 = 0x0064
    uses: ax_12 = fn0C00_000F(wLoc02_11)
ax_12: orig: ax
    def:  ax_12 = fn0C00_000F(wLoc02_11)
    uses: Mem15[ds:0x0064:word16] = ax_12
sp_13: orig: sp
SCZO_14: orig: SCZO
Mem15: orig: Mem0
    def:  Mem15[ds:0x0064:word16] = ax_12
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	wLoc02_11 = 0x0064
	ax_12 = fn0C00_000F(wLoc02_11)
	Mem15[ds:0x0064:word16] = ax_12
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
Mem0:Global memory
fp:Temporary
sp:sp
bp:bp
ss:ss
ax:ax
SZO:Flags
Z:Flags
dx:dx
dx_ax:Sequence dx:ax
SCZO:Flags
wLoc02:Local -0002
wArg02:Stack +0002
    def:  def wArg02
    uses: ax_17 = wArg02
          dx_39 = wArg02
wLoc04:Local -0004
sp_14: orig: sp
wLoc02_15: orig: wLoc02
bp_16: orig: bp
ax_17: orig: ax
    def:  ax_17 = wArg02
    uses: ax_18 = ax_17 - 0x0001
ax_18: orig: ax
    def:  ax_18 = ax_17 - 0x0001
    uses: wLoc04_33 = ax_18
          branch ax_18 == 0x0000 l0C00_0026
dx_ax_19: orig: dx_ax
SZO_20: orig: SZO
Z_21: orig: Z
SCZO_22: orig: SCZO
wLoc04_23: orig: wLoc04
SCZO_24: orig: SCZO
dx_ax_25: orig: dx_ax
dx_26: orig: dx
Z_27: orig: Z
SZO_28: orig: SZO
ax_29: orig: ax
    def:  ax_29 = PHI(ax_41, ax_46)
    uses: return ax_29
bp_30: orig: bp
sp_31: orig: sp
sp_32: orig: sp
wLoc04_33: orig: wLoc04
    def:  wLoc04_33 = ax_18
    uses: ax_34 = fn0C00_000F(wLoc04_33)
ax_34: orig: ax
    def:  ax_34 = fn0C00_000F(wLoc04_33)
    uses: dx_ax_40 = dx_39 *s ax_34
sp_35: orig: sp
SZO_36: orig: SZO
sp_37: orig: sp
SZO_38: orig: SZO
dx_39: orig: dx
    def:  dx_39 = wArg02
    uses: dx_ax_40 = dx_39 *s ax_34
dx_ax_40: orig: dx_ax
    def:  dx_ax_40 = dx_39 *s ax_34
    uses: ax_41 = (word16) dx_ax_40 (alias)
ax_41: orig: ax
    def:  ax_41 = (word16) dx_ax_40 (alias)
    uses: ax_29 = PHI(ax_41, ax_46)
dx_42: orig: dx
SCZO_43: orig: SCZO
SZO_44: orig: SZO
Z_45: orig: Z
ax_46: orig: ax
    def:  ax_46 = 0x0001
    uses: ax_29 = PHI(ax_41, ax_46)
dx_ax_47: orig: dx_ax
// fn0C00_000F
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	def wArg02
	// succ:  l0C00_000F
l0C00_000F:
	ax_17 = wArg02
	ax_18 = ax_17 - 0x0001
	branch ax_18 == 0x0000 l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	wLoc04_33 = ax_18
	ax_34 = fn0C00_000F(wLoc04_33)
	dx_39 = wArg02
	dx_ax_40 = dx_39 *s ax_34
	ax_41 = (word16) dx_ax_40 (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_46 = 0x0001
	// succ:  l0C00_0029
l0C00_0029:
	ax_29 = PHI(ax_41, ax_46)
	return ax_29
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:
