fp:fp
sp_2: orig: sp
Top_3: orig: Top
sp_4: orig: sp
si:si
ss:ss
Mem7: orig: Mem0
sp_8: orig: sp
di:di
    def:  def di
    uses: di_25 = PHI(di, di_28)
Mem10: orig: Mem0
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
si_11: orig: si
    def:  si_11 = 0x0000
    uses: si_15 = PHI(si_11, si_26)
cx_12: orig: cx
SCZO_13: orig: SCZO
Z_14: orig: Z
si_15: orig: si
    def:  si_15 = PHI(si_11, si_26)
    uses: ax_16 = si_15
          si_26 = si_15 + Mem10[ds:di_25:word16]
ax_16: orig: ax
    def:  ax_16 = si_15
    uses: return ax_16
ss_17: orig: ss
sp_18: orig: sp
Mem19: orig: Mem0
di_20: orig: di
sp_21: orig: sp
si_22: orig: si
sp_23: orig: sp
ds_24: orig: ds
di_25: orig: di
    def:  di_25 = PHI(di, di_28)
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
          di_28 = di_25 + 0x0002
si_26: orig: si
    def:  si_26 = si_15 + Mem10[ds:di_25:word16]
    uses: si_15 = PHI(si_11, si_26)
SCZO_27: orig: SCZO
di_28: orig: di
    def:  di_28 = di_25 + 0x0002
    uses: di_25 = PHI(di, di_28)
SCZO_29: orig: SCZO
cx:cx
    def:  def cx
    uses: branch cx == 0x0000 l0C00_001A
ds:ds
    def:  def ds
    uses: si_26 = si_15 + Mem10[ds:di_25:word16]
wLoc02_32: orig: wLoc02
wLoc04_33: orig: wLoc04
C_36: orig: C
O_37: orig: O
S_38: orig: S
// fn0C00_0008
// Return size: 0
word16 fn0C00_0008(word16 cx, word16 di, selector ds)
fn0C00_0008_entry:
	def di
	def cx
	def ds
	// succ:  l0C00_0008
l0C00_0008:
	si_11 = 0x0000
	// succ:  l0C00_000D
l0C00_000D:
	di_25 = PHI(di, di_28)
	si_15 = PHI(si_11, si_26)
	branch cx == 0x0000 l0C00_001A
	// succ:  l0C00_0012 l0C00_001A
l0C00_0012:
	si_26 = si_15 + Mem10[ds:di_25:word16]
	di_28 = di_25 + 0x0002
	goto l0C00_000D
	// succ:  l0C00_000D
l0C00_001A:
	ax_16 = si_15
	return ax_16
	// succ:  fn0C00_0008_exit
fn0C00_0008_exit:
fp:fp
sp_2: orig: sp
Top_3: orig: Top
cx_4: orig: cx
di:di
    def:  def di
    uses: ax_7 = fn0C00_0008(0x0014, di, ds)
          fn0C00_0008(0x0014, di, ds)
ds:ds
    def:  def ds
    uses: ax_7 = fn0C00_0008(0x0014, di, ds)
          Mem13[ds:si:word16] = ax_7
          fn0C00_0008(0x0014, di, ds)
ax_7: orig: ax
    def:  ax_7 = fn0C00_0008(0x0014, di, ds)
    uses: Mem13[ds:si:word16] = ax_7
S_8: orig: S
    def:  ax_7 = fn0C00_0008(0x0014, di, ds)
C_9: orig: C
    def:  ax_7 = fn0C00_0008(0x0014, di, ds)
Z_10: orig: Z
    def:  ax_7 = fn0C00_0008(0x0014, di, ds)
O_11: orig: O
    def:  ax_7 = fn0C00_0008(0x0014, di, ds)
si:si
    def:  def si
    uses: Mem13[ds:si:word16] = ax_7
Mem13: orig: Mem0
    def:  Mem13[ds:si:word16] = ax_7
ax_14: orig: ax
    def:  fn0C00_0008(0x0014, di, ds)
S_15: orig: S
    def:  fn0C00_0008(0x0014, di, ds)
C_16: orig: C
    def:  fn0C00_0008(0x0014, di, ds)
Z_17: orig: Z
    def:  fn0C00_0008(0x0014, di, ds)
O_18: orig: O
    def:  fn0C00_0008(0x0014, di, ds)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def di
	def ds
	def si
	// succ:  l0C00_0000
l0C00_0000:
	ax_7 = fn0C00_0008(0x0014, di, ds)
	Mem13[ds:si:word16] = ax_7
	// succ:  l0C00_0006_thunk_fn0C00_0008
l0C00_0006_thunk_fn0C00_0008:
	fn0C00_0008(0x0014, di, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
