// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax dx al dl ah dh
// Preserved:
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	store(Mem7[ds:0x012C:word16]) = fn0C00_000B(0x001E)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

// Register word16 fn0C00_000B(Register word16 dx)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  dx
// LiveOut: ax
// Trashed: SCZO ax dx al dl ah dh
// Preserved:
// fn0C00_000B
word16 fn0C00_000B(word16 dx)
fn0C00_000B_entry:		// pred:
	// succ:  l0C00_000B
l0C00_000B:		// pred: fn0C00_000B_entry
	return fn0C00_000F(dx)
	// succ:  fn0C00_000B_exit
fn0C00_000B_exit:		// pred: l0C00_000B
	// succ: 

// Register word16 fn0C00_000F(Register word16 dx)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  dx
// LiveOut: ax
// Trashed: SCZO ax dx al dl ah dh
// Preserved: si
// fn0C00_000F
word16 fn0C00_000F(word16 dx)
fn0C00_000F_entry:		// pred:
	// succ:  l0C00_000F
l0C00_000F:		// pred: fn0C00_000F_entry
	word16 si_10 = 0x0000
	// succ:  l0C00_0018
l0C00_0018:		// pred: l0C00_000F l0C00_0015
	branch dx >= 0x0000 l0C00_0015
	// succ:  l0C00_001D l0C00_0015
l0C00_001D:		// pred: l0C00_0018
	return si_10
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:		// pred: l0C00_001D
	// succ: 
l0C00_0015:		// pred: l0C00_0018
	si_10 = si_10 + dx
	dx = dx - 0x0001
	// succ:  l0C00_0018

