// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds
// LiveOut:
// Trashed: SCZO bh bl bx ebx rbx
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0010(ds, 0x0300, 0x0320)
	fn0C00_0037(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0010(Register selector ds, Stack word16 wArg02, Stack word16 wArg04)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds
// LiveOut:
// Trashed: bh bl bx ebx rbx
// Preserved: bp sp
// Stack args: Stack +0002(16) Stack +0004(16)
// fn0C00_0010
// Return size: 0
void fn0C00_0010(selector ds, word16 wArg02, word16 wArg04)
fn0C00_0010_entry:
	// succ:  l0C00_0010
l0C00_0010:
	real64 rLoc1_10 = Mem0[ds:wArg02:real64]
	real64 rLoc2_12 = Mem0[ds:wArg02 + 0x0008:real64]
	real64 rLoc2_15 = Mem0[ds:wArg02 + 0x0010:real64]
	Mem20[ds:wArg04:real64] = rLoc1_10 * rLoc1_10 + rLoc2_12 * rLoc2_12 + rLoc2_15 * rLoc2_15
	Mem22[ds:wArg04 + 0x0028:real64] = (real64) Mem20[ds:wArg04 + 0x0020:int16]
	return
	// succ:  fn0C00_0010_exit
fn0C00_0010_exit:

// void fn0C00_0037(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds
// LiveOut:
// Trashed:
// Preserved: sp
// fn0C00_0037
// Return size: 0
void fn0C00_0037(selector ds)
fn0C00_0037_entry:
	// succ:  l0C00_0037
l0C00_0037:
	Mem3[ds:0x0400:real64] = 0.0
	Mem6[ds:0x0408:int32] = (int32) 1.0
	return
	// succ:  fn0C00_0037_exit
fn0C00_0037_exit:

