// void fn0C00_0000(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: bx FPU -1 Top
// Preserved: ds sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem11[ds:0x400<16>:real64] = fn0C00_000C(SEQ(ds, Mem0[ds:0x300<16>:word16]))
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// FpuStack real64 fn0C00_000C(Sequence segptr32 ds_bx)
// stackDelta: 2; fpuStackDelta: 1; fpuMaxParam: -1
// MayUse:  Sequence ds:bx:[0..31]
// LiveOut: FPU -1:[0..63]-fn0C00_0000
// Trashed: FPU -1 FPU -2 Top
// Preserved: sp
// fn0C00_000C
// Return size: 0
real64 fn0C00_000C(segptr32 ds_bx)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	return Mem0[ds_bx:real64] + Mem0[ds_bx + 8<i32>:real64]
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

