// void fn0C00_0000(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: SCZO bx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0010(ds, 0x300<16>, 0x320<16>)
	fn0C00_0037(ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0010(Register selector ds, Stack word16 wArg02, Stack word16 wArg04)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15] Stack +0002:[0..15] Stack +0004:[0..15]
// LiveOut:
// Trashed: bx FPU -1 FPU -2 Top
// Preserved: bp sp
// fn0C00_0010
// Return size: 0
void fn0C00_0010(selector ds, word16 wArg02, word16 wArg04)
fn0C00_0010_entry:
	// succ:  l0C00_0010
l0C00_0010:
	real64 rLoc1_36 = Mem7[ds:wArg02:real64]
	real64 rLoc2_38 = Mem7[ds:wArg02 + 8<i16>:real64]
	real64 rLoc2_41 = Mem7[ds:wArg02 + 16<i16>:real64]
	Mem25[ds:wArg04:real64] = rLoc1_36 * rLoc1_36 + rLoc2_38 * rLoc2_38 + rLoc2_41 * rLoc2_41
	Mem29[ds:wArg04 + 40<i16>:real64] = CONVERT(Mem25[ds:wArg04 + 32<i16>:int16], int16, real64)
	return
	// succ:  fn0C00_0010_exit
fn0C00_0010_exit:

// void fn0C00_0037(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: FPU -1 Top
// Preserved: sp
// fn0C00_0037
// Return size: 0
void fn0C00_0037(selector ds)
fn0C00_0037_entry:
	// succ:  l0C00_0037
l0C00_0037:
	Mem7[ds:0x400<16>:real64] = 0.0
	Mem11[ds:0x408<16>:int32] = CONVERT(1.0, real64, int32)
	return
	// succ:  fn0C00_0037_exit
fn0C00_0037_exit:

