// void fn0C00_0000(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: SCZO ax cx dx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem13[ds:0x64<16>:word16] = fn0C00_000B(5<16>)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Register word16 fn0C00_000B(Register word16 cx)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  cx:[0..15]
// LiveOut: ax
// Trashed: SCZO ax cx dx Top
// Preserved: si sp
// fn0C00_000B
// Return size: 0
word16 fn0C00_000B(word16 cx)
fn0C00_000B_entry:
	// succ:  l0C00_000B
l0C00_000B:
	branch cx <= 1<16> l0C00_001C
	// succ:  l0C00_0011 l0C00_001C
l0C00_0011:
	ax_11 = cx *s fn0C00_000B(cx - 1<16>) (alias)
	goto l0C00_001F
	// succ:  l0C00_001F
l0C00_001C:
	ax_11 = 1<16>
	// succ:  l0C00_001F
l0C00_001F:
	return ax_11
	// succ:  fn0C00_000B_exit
fn0C00_000B_exit:

