// void fn10000000(Stack word32 dwArg04)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  Stack +0004:[0..31]
// LiveOut:
// Trashed: eax
// Preserved: edi esi esp
// fn10000000
// Return size: 0
void fn10000000(word32 dwArg04)
fn10000000_entry:
	// succ:  l10000000
l10000000:
	GlobalUnlock(GlobalHandle(dwArg04))
	GlobalFree(GlobalHandle(dwArg04))
	return
	// succ:  fn10000000_exit
fn10000000_exit:

