// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: ax cx bx al cl bl ah ch bh
// Preserved:
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem9[ds:0x0300:word16]) = 0x0004
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

