// void fn0C00_0000(Register word16 dx)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  dx:[0..15]
// LiveOut:
// Trashed: SCZO ax dx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 dx)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004(dx, out dx_11)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Register word16 fn0C00_0004(Register word16 dx, Register out ptr16 dxOut)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  dx:[0..15]
// LiveOut: ax dx
// Trashed: SCZO ax dx Top
// Preserved: sp
// fn0C00_0004
// Return size: 0
word16 fn0C00_0004(word16 dx, ptr16 & dxOut)
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	branch dx != 0x1E<16> l0C00_000F
	// succ:  l0C00_0009 l0C00_000F
l0C00_0009:
	dx_11 = fn0C00_0013(dx)
	goto l0C00_0010
	// succ:  l0C00_0010
l0C00_000F:
	dx_11 = dx - 1<16>
	// succ:  l0C00_0010
l0C00_0010:
	dxOut = dx_11
	return dx_11
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

// Register word16 fn0C00_0013(Register word16 dx)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  dx:[0..15]
// LiveOut: dx
// Trashed: SCZO ax dx Top
// Preserved: sp
// fn0C00_0013
// Return size: 0
word16 fn0C00_0013(word16 dx)
fn0C00_0013_entry:
	// succ:  l0C00_0013
l0C00_0013:
	branch dx < 0x14<16> l0C00_001F
	// succ:  l0C00_0018 l0C00_001F
l0C00_0018:
	fn0C00_0004(dx - 1<16>, out dx_11)
	goto l0C00_0025
	// succ:  l0C00_0025
l0C00_001F:
	fn0C00_0004(dx - 0xA<16>, out dx_11)
	// succ:  l0C00_0025
l0C00_0025:
	return dx_11
	// succ:  fn0C00_0013_exit
fn0C00_0013_exit:

