// void ManyIncrements(Register word32 r0)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  r0:[0..31]
// LiveOut:
// Trashed: r0 r1
// Preserved: r63
// ManyIncrements
// Return size: 0
void ManyIncrements(word32 r0)
ManyIncrements_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ManyIncrements_exit
l1:
	goto loopTop
	// succ:  loopTop
l2:
	Mem12[0x33333330:word32] = Mem4[r0_6:byte]
	Mem15[0x33333331:word32] = Mem12[r0_6 + 0x00000001:byte]
	r0 = r0_6 + 0x00000002
	goto loopTop
	// succ:  loopTop
l3:
	Mem9[0x33333330:word32] = Mem4[r0_6:byte]
	r0 = r0_6 + 0x00000001
	// succ:  loopTop
loopTop:
	word32 r1_5 = Mem4[r0:byte]
	word32 r0_6 = r0 + 0x00000001
	branch r1_5 != 1 not1
	goto l2
	// succ:  l2 not1
not1:
	branch r1_5 != 2 done
	goto l3
	// succ:  l3 done
ManyIncrements_exit:

