// void fn0C00_0000(Register word32 eax, Register word16 bx, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  eax bx ds
// LiveOut:
// Trashed: SCZO eax ecx ax cx bx al cl bl ah ch bh
// Preserved:
// fn0C00_0000
void fn0C00_0000(word32 eax, word16 bx, selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem15[ds:0x0300:word32]) = 0x00000000 - (-eax == 0x00000000)
	store(Mem17[ds:0x0202:word16]) = -Mem15[ds:0x0202:word16]
	word16 v6_19 = Mem17[ds:0x0200:word16]
	store(Mem20[ds:0x0200:word16]) = -v6_19
	store(Mem23[ds:0x0308:word32]) = 0x00000000 - (v6_19 == 0x0000)
	store(Mem25[ds:0x0304:word16]) = ~bx
	store(Mem27[ds:0x0204:word16]) = ~Mem25[ds:0x0204:word16]
	store(Mem33[ds:0x0306:word16]) = 0x03E8 - Mem27[ds:0x0304:word16]
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

