// void fn0C00_0000(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: ax Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ax_6 = Mem0[ds:0x100<16>:word16]
	fn0C00_000C(ds)
	Mem7[ds:0x102<16>:word16] = ax_6
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_000C(Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: Top
// Preserved: ax sp
// fn0C00_000C
// Return size: 0
void fn0C00_000C(selector ds)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	Mem10[ds:0x105<16>:byte] = Mem7[ds:0x104<16>:byte]
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

