// void fn0C00_0000()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ah al ax bh bl bx eax ebx es rax rbx
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0004()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ah al ax bh bl bx eax ebx es rax rbx
// Preserved: sp
// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_24 = 0x0FFF
	byte bh_25 = 0x0F
	byte bl_10 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	Mem23[0x4DE1:bx_24:byte] = bl_10 & 0xF0 | SLICE((bl_10 & 0x0F) *u (bh_25 + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_24 = bx_24 - 0x0001
	bh_25 = SLICE(bx_24, byte, 8) (alias)
	bl_10 = (byte) bx_24 (alias)
	branch bx_24 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

