// void fn0C00_0000()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: ax bx C es O S Top Z
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0004()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: ax bx C es O S Top Z
// Preserved: sp
// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_36 = 0x0FFF
	byte bh_42 = 0x0F
	byte bl_11 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	word16 bx_37 = DPB(bx_36, bl_11, 0)
	Mem38[0x4DE1:bx_37:byte] = DPB(bl_11, al_31, 0)
	byte ah_26 = SLICE(DPB((bl_11 & 0x0F) *u (bh_42 + 0x01) << 0x0004, bl_11, 0), byte, 8)
	al_31 = bl_11 | DPB(ah_26, ah_26 & 0x0F, 8)
	bx_36 = bx_37 - 0x0001
	bh_42 = SLICE(bx_37 - 0x0001, byte, 8) (alias)
	bl_11 = (byte) (bx_37 - 0x0001) (alias)
	branch bx_37 >= 0x0001 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

