// void fn0C00_0000(Register word16 di, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  di ds
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 di, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0007(0x1230, di, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0007(Register word16 si, Register word16 di, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  di ds si
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_0007
// Return size: 0
void fn0C00_0007(word16 si, word16 di, selector ds)
fn0C00_0007_entry:
	// succ:  l0C00_0007
l0C00_0007:
	fn0C00_0020(ds)
	Mem11[ds:0x1444:word16] = Mem0[ds:0x1444:word16] + Mem0[ds:si + 0x0028:word16]
	branch Mem11[ds:di + 0x0030:byte] == 0x00 l0C00_001F
	// succ:  l0C00_0019 l0C00_001F
l0C00_0019:
	fn0C00_0007(si, Mem11[ds:di + 0x0030:word16], ds)
	// succ:  l0C00_001F
l0C00_001F:
	return
	// succ:  fn0C00_0007_exit
fn0C00_0007_exit:

// void fn0C00_0020(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_0020
// Return size: 0
void fn0C00_0020(selector ds)
fn0C00_0020_entry:
	// succ:  l0C00_0020
l0C00_0020:
	Mem3[ds:0x4321:word32] = 0x00001234
fn0C00_0020_exit:

