// void fn0C00_0000()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO bx cx ds dx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 ax_12 = fn0C00_0023(0x0100, 0x3000, Mem6[0x0D00:0x0300:word16], 0x0D00)
	branch ax_12 >= 0x0000 l0C00_001A
	// succ:  l0C00_0015 l0C00_001A
l0C00_0015:
	fn0C00_001F(0x01)
l0C00_001A:
	Mem19[0x0D00:0x0302:word16] = ax_12
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_001F(Register byte al)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  al:[0..7]
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_001F
// Return size: 0
void fn0C00_001F(byte al)
fn0C00_001F_entry:
	// succ:  l0C00_001F
l0C00_001F:
	msdos_terminate(al)
fn0C00_001F_exit:

// Register word16 fn0C00_0023(Register word16 cx, Register word16 dx, Register word16 bx, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  bx:[0..15] cx:[0..15] ds:[0..15] dx:[0..15]
// LiveOut: ax
// Trashed: C ax Top
// Preserved: sp
// fn0C00_0023
// Return size: 0
word16 fn0C00_0023(word16 cx, word16 dx, word16 bx, selector ds)
fn0C00_0023_entry:
	word32 ds_dx_9 = SEQ(ds, dx)
	// succ:  l0C00_0023
l0C00_0023:
	word16 ax_10
	branch msdos_read_file(bx, cx, ds_dx_9, out ax_10) l0C00_002C
	// succ:  l0C00_0029 l0C00_002C
l0C00_0029:
	ax_10 = 0xFFFF
	// succ:  l0C00_002C
l0C00_002C:
	return ax_10
	// succ:  fn0C00_0023_exit
fn0C00_0023_exit:

