// void fn0C00_0000(Register word16 ax)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ax:[0..15]
// LiveOut:
// Trashed: SCZO ax bx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 ax)
fn0C00_0000_entry:
	al_8 = SLICE(ax, byte, 0) (alias)
	// succ:  l0C00_0000
l0C00_0000:
	msdos_set_memory_allocation_strategy(al_8)
	msdos_set_UMB_link_state(ax >>u 8<16>, out ax_17)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

