// Register int32 r316(Stack int32 a)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SZO ah al ax ch cl cx eax ecx esp rax rcx rsp sp spl
// Preserved:
// Stack args: Stack +0004(32)
// r316
// Return size: 4
int32 r316(int32 a)
fn10000000_entry:
	// succ:  l10000000
l10000000:
	word32 ecx_6 = Mem0[a:word32]
	word32 esp_9
	word32 eax_10
	word32 ecx_11
	byte SZO_12
	call Mem0[ecx_6 + 0x00000004:word32] (retsize: 4; depth: 8)
		uses: dwLoc04_8,eax_4,ecx_6,esp_7
		defs: eax_10,ecx_11,esp_9,SZO_12
	return eax_10 + 0x00000001
	// succ:  fn10000000_exit
fn10000000_exit:

