// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: SCZO al Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	branch fn0C00_000C(0x20, ds) l0C00_000B
	// succ:  l0C00_0007 l0C00_000B
l0C00_0007:
	Mem10[ds:0x0300:byte] = 0x20
	// succ:  l0C00_000B
l0C00_000B:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// FlagGroup bool fn0C00_000C(Register byte al, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  al:[0..7] ds:[0..15]
// LiveOut: C
// Trashed: SCZO Top
// Preserved: sp
// fn0C00_000C
// Return size: 0
bool fn0C00_000C(byte al, selector ds)
fn0C00_000C_entry:
	// succ:  l0C00_000C
l0C00_000C:
	bool C_6 = al <u 0x20;
	branch C_6 l0C00_0014
	// succ:  l0C00_0010 l0C00_0014
l0C00_0010:
	Mem10[ds:0x0201:word16] = Mem0[ds:0x0201:word16] + 0x0001
	// succ:  l0C00_0014
l0C00_0014:
	return C_6
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:

