// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ds:[0..15]
// LiveOut:
// Trashed: SCZO ax bx cx di dx es gs Top
// Preserved: ds sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	word16 dx_9 = Mem0[ds:Mem0[ds:0x9CFD:word16] * 0x0002 + 0x99F8:word16]
	Mem10[ds:0x9CFF:word16] = dx_9
	word16 ax_22
	msdos_read_file(Mem10[ds:0x99D0:word16], 0x0180, SEQ(0x6041, dx_9), out ax_22)
	msdos_close_file(Mem17[ds:0x99D0:word16])
	Mem33[ds:0xC36A:word16] = Mem17[ds:Mem17[ds:0x9CFD:word16] * 0x0002 + 0x542E:word16]
	Mem41[ds:0x0100:word16] = ds
	Mem43[ds:0x0102:word16] = 0x6041
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

