// void fn0C00_0000()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ax bx es Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0004()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ax bx es Top
// Preserved: sp
// fn0C00_0004
// Return size: 0
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_36 = 0x0FFF
	// succ:  l0C00_000C
l0C00_000C:
	byte bl_10 = SLICE(bx_39, byte, 0)
	Mem23[0x4DE1:bx_39:byte] = bl_10 & 0xF0 | SLICE((bl_10 & 0x0F) *u (SLICE(bx_39, byte, 8) + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_36 = bx_39 - 0x0001 (alias)
	bx_39 = bx_36
	branch bx_39 >= 0x0001 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

