// void fn0C00_0000(Register word16 ax, Register word16 dx, Register word16 bx)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ax dx bx ss
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_0000
void fn0C00_0000(word16 ax, word16 dx, word16 bx)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem19[ss:0x06B6:word16] = bx
	Mem21[ss:0x06B4:word16] = ax
	Mem23[ss:0x06B2:word16] = dx
	word16 ax_30
	msdos_open_file(0800:0887, 0x01, &ax_30)
	selector ds_33 = Mem23[ss:0x06B2:selector]
	word16 dx_35 = Mem23[ss:0x06B4:word16]
	word32 ds_dx_36 = SEQ(ds_33, dx_35)
	word16 si_38 = dx_35 + 0x0001
	// succ:  l0C00_0019
l0C00_0019:
	si_38 = si_62 + 0x0001
	word16 si_62 = si_38
	branch Mem23[ds_33:si_62:byte] != 0xFFFF l0C00_0019
	// succ:  l0C00_001E l0C00_0019
l0C00_001E:
	word16 ax_50
	msdos_write_file(0x3D01, si_62 + 0x0000 - dx_35 - 0x0001, ds_dx_36, &ax_50)
	Mem55[ss:0x06B6:word16] = Mem23[ss:0x06B6:word16]
	fn0C00_0037(0x0000, 0x00FF, ds_33)
	msdos_terminate((byte) Mem55[ss:0x06B6:word16])
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0037(Register word16 ax, Register word16 dx, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  ax dx ds
// LiveOut:
// Trashed:
// Preserved: sp
// fn0C00_0037
void fn0C00_0037(word16 ax, word16 dx, selector ds)
fn0C00_0037_entry:
	// succ:  l0C00_0037
l0C00_0037:
	Mem6[ds:0x0300:word16] = ax
	Mem7[ds:0x0302:word16] = dx
	return
	// succ:  fn0C00_0037_exit
fn0C00_0037_exit:

