// Register int32 r316(Stack int32 a)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  Stack +0004:[0..31]
// LiveOut: eax
// Trashed: eax
// Preserved:
// r316
// Return size: 4
int32 r316(int32 a)
fn10000000_entry:
	// succ:  l10000000
l10000000:
	word32 ecx_6 = Mem0[a:word32]
	word32 eax_10
	call Mem8[ecx_6 + 0x00000004:word32] (retsize: 4;)
		uses: eax:a,ecx:ecx_6,esp:fp - 4,Stack +0004:0x0000000A,Stack +000C:a,Top:0
		defs: eax:eax_10
	return eax_10 + 0x00000001
	// succ:  fn10000000_exit
fn10000000_exit:

