// void fn0C00_0000()
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ax bx cx ds dx Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ax_13 = fn0C00_0023(0D00:3000, 0x100<16>, Mem6[0D00:0300:word16])
	branch ax_13 >= 0<16> l0C00_001A
	// succ:  l0C00_0015 l0C00_001A
l0C00_0015:
	fn0C00_001F(1<8>)
l0C00_001A:
	Mem22[0D00:0302:word16] = ax_13
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_001F(Register byte al)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  al:[0..7]
// LiveOut:
// Trashed:
// Preserved:
// Terminates process
// fn0C00_001F
// Return size: 0
void fn0C00_001F(byte al)
fn0C00_001F_entry:
	// succ:  l0C00_001F
l0C00_001F:
	msdos_terminate(al)
fn0C00_001F_exit:

// Register word16 fn0C00_0023(Sequence word32 ds_dx, Register word16 cx, Register word16 bx)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  bx:[0..15] cx:[0..15] Sequence ds:dx:[0..31]
// LiveOut: ax
// Trashed: C ax Top
// Preserved: ds dx sp
// fn0C00_0023
// Return size: 0
word16 fn0C00_0023(word32 ds_dx, word16 cx, word16 bx)
fn0C00_0023_entry:
	// succ:  l0C00_0023
l0C00_0023:
	branch msdos_read_file(bx, cx, ds_dx, out ax_10) l0C00_002C
	// succ:  l0C00_0029 l0C00_002C
l0C00_0029:
	ax_10 = 0xFFFF<16>
	// succ:  l0C00_002C
l0C00_002C:
	return ax_10
	// succ:  fn0C00_0023_exit
fn0C00_0023_exit:

