// void fn0C00_0000(Register word16 bx, Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  bx:[0..15] ds:[0..15] ss:[0..15]
// LiveOut:
// Trashed: ax ss Top
// Preserved: sp
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	Mem10[ds:0x306<16>:word16] = fn0C00_0008(bx, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// Register word16 fn0C00_0008(Register word16 bx, Register selector ds)
// stackDelta: 2; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse:  bx:[0..15] ds:[0..15] ss:[0..15]
// LiveOut: ax
// Trashed: ax sp ss Top
// Preserved:
// fn0C00_0008
// Return size: 0
word16 fn0C00_0008(word16 bx, selector ds)
fn0C00_0008_entry:
	// succ:  l0C00_0008
l0C00_0008:
	Mem5[ds:0x300<16>:word16] = fp
	Mem7[ds:0x302<16>:word16] = ss
	Mem9[ds:0x308<16>:word16] = bx
	return Mem9[ds:0x304<16>:word16]
	// succ:  fn0C00_0008_exit
fn0C00_0008_exit:

