// void ProcedureBuilder()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: r1 r2
// Preserved: r63
// ProcedureBuilder
// Return size: 0
void ProcedureBuilder()
ProcedureBuilder_entry:
	// succ:  l1
l1:
	Mem10[0x123404<32>:word32] = CONVERT(Mem0[0x123400<32>:word32], uint32, uint64) /u 0x2A<32>
	return
	// succ:  ProcedureBuilder_exit
ProcedureBuilder_exit:

