// void fn0C00_0000(Register word16 si, Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  si ds
// LiveOut:
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0000
void fn0C00_0000(word16 si, selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	word16 ax_10 = Mem0[ds:si:word16]
	// succ:  2
l0C00_000E:		// block 2, pred: 1 3
	store(Mem15[ds:si + 0x0002:word16]) = ax_10
	store(Mem16[ds:si + 0x0004:word16]) = ax_10
	store(Mem17[ds:si + 0x0008:word16]) = 0x0003
	branch ax_10 != 0x0000 l0C00_0005
	// succ:  4 3
l0C00_0005:		// block 3, pred: 2
	store(Mem23[ds:si + 0x0006:word16]) = Mem17[ds:si + 0x0006:word16] + Mem17[ds:si + 0x0006:word16]
	ax_10 = ax_10 - 0x0001
	// succ:  2
l0C00_001E:		// block 4, pred: 2
	return
	// succ:  5
fn0C00_0000_exit:		// block 5, pred: 4
	// succ: 

