fp:fp
    def:  def fp
    uses: r63_2 = fp
          r63_6 = fp + 4<i32>
          eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
r63_2: orig: r63
    def:  r63_2 = fp
Mem0:Mem
    def:  def Mem0
    uses: ecx_5 = Mem0[eax_4:word32]
          eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
eax_4: orig: eax
    def:  eax_4 = dwArg04_10
    uses: ecx_5 = Mem0[eax_4:word32]
ecx_5: orig: ecx
    def:  ecx_5 = Mem0[eax_4:word32]
    uses: eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
          eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
r63_6: orig: r63
    def:  r63_6 = fp + 4<i32>
eax_7: orig: eax
    def:  eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
ecx_8: orig: ecx
    def:  ecx_8 = <invalid>
a:Stack +0004
    def:  def a
    uses: dwArg04_10 = a
dwArg04_10: orig: dwArg04
    def:  dwArg04_10 = a
    uses: eax_4 = dwArg04_10
Mem11: orig: Mem0
    uses: eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
// ProcedureBuilder
// Return size: 0
void ProcedureBuilder(struct <anonymous> * a)
ProcedureBuilder_entry:
	def fp
	def Mem0
	def a
	dwArg04_10 = a
	// succ:  l1
l1:
	r63_2 = fp
	eax_4 = dwArg04_10
	ecx_5 = Mem0[eax_4:word32]
	eax_7 = Mem0[ecx_5:word32](ecx_5, Mem11[fp:int32])
	ecx_8 = <invalid>
	r63_6 = fp + 4<i32>
	return
	// succ:  ProcedureBuilder_exit
ProcedureBuilder_exit:

