fp:fp
    def:  def fp
    uses: r63_2 = fp
          r63_6 = fp - 4<32>
          call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
r63_2: orig: r63
    def:  r63_2 = fp
Mem0:Mem
    def:  def Mem0
    uses: ecx_5 = Mem0[eax_4:word32]
eax_4: orig: eax
    def:  eax_4 = dwArg04_12
    uses: ecx_5 = Mem0[eax_4:word32]
          call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
ecx_5: orig: ecx
    def:  ecx_5 = Mem0[eax_4:word32]
    uses: call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
          call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
r63_6: orig: r63
    def:  r63_6 = fp - 4<32>
Mem7: orig: Mem0
    uses: call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
          call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
r63_8: orig: r63
    def:  call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
eax_9: orig: eax
    def:  call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
ecx_10: orig: ecx
    def:  call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
a:Stack +0004
    def:  def a
    uses: dwArg04_12 = a
dwArg04_12: orig: dwArg04
    def:  dwArg04_12 = a
    uses: eax_4 = dwArg04_12
          call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
dwLoc04_13: orig: dwLoc04
    def:  dwLoc04_13 = 0xA<32>
    uses: call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)	uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12	defs: eax:eax_9,ecx:ecx_10,r63:r63_8
// ProcedureBuilder
// Return size: 0
void ProcedureBuilder(struct <anonymous> * a)
ProcedureBuilder_entry:
	def fp
	def Mem0
	def a
	dwArg04_12 = a
	// succ:  l1
l1:
	r63_2 = fp
	eax_4 = dwArg04_12
	ecx_5 = Mem0[eax_4:word32]
	r63_6 = fp - 4<32>
	dwLoc04_13 = 0xA<32>
	call Mem7[ecx_5 + 4<32>:word32] (retsize: 4;)
		uses: eax:eax_4,ecx:ecx_5,Mem:Mem7,r63:fp - 4<32>,Stack +0004:dwLoc04_13,Stack +000C:dwArg04_12
		defs: eax:eax_9,ecx:ecx_10,r63:r63_8
	return
	// succ:  ProcedureBuilder_exit
ProcedureBuilder_exit:

