a:Stack +0004
    def:  def a
    uses: a_1 = a
          ecx_6 = Mem0[a:word32]
a_1: orig: a
    def:  a_1 = a
    uses: eax_4 = a_1
fp:fp
    def:  def fp
    uses: esp_3 = fp
          esp_7 = fp - 4
          esp_9 = fp - 8
esp_3: orig: esp
    def:  esp_3 = fp
eax_4: orig: eax
    def:  eax_4 = a_1
    uses: call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
Mem0:Global memory
    def:  def Mem0
    uses: ecx_6 = Mem0[a:word32]
          call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
ecx_6: orig: ecx
    def:  ecx_6 = Mem0[a:word32]
    uses: call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
          call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
esp_7: orig: esp
    def:  esp_7 = fp - 4
dwLoc04_8: orig: dwLoc04
    def:  dwLoc04_8 = 0x0000000B
    uses: call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
esp_9: orig: esp
    def:  esp_9 = fp - 8
    uses: call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
dwLoc08_10: orig: dwLoc08
    def:  dwLoc08_10 = 0x0000000A
    uses: call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
esp_11: orig: esp
    def:  call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
eax_12: orig: eax
    def:  call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
ecx_13: orig: ecx
    def:  call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)	uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9	defs: eax_12,ecx_13,esp_11
// test
// Return size: 4
void test(str * a)
fn0C00_0000_entry:
	def a
	def fp
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	a_1 = a
	esp_3 = fp
	eax_4 = a_1
	ecx_6 = Mem0[a:word32]
	esp_7 = fp - 4
	dwLoc04_8 = 0x0000000B
	esp_9 = fp - 8
	dwLoc08_10 = 0x0000000A
	call Mem0[ecx_6 + 0x00000008:word32] (retsize: 4; depth: 12)
		uses: dwLoc04_8,dwLoc08_10,eax_4,ecx_6,esp_9
		defs: eax_12,ecx_13,esp_11
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

