a:Stack +0004
    def:  def a
    uses: a_1 = a
          ecx_6 = Mem0[a:word32]
a_1: orig: a
    def:  a_1 = a
    uses: eax_4 = a_1
fp:fp
    def:  def fp
    uses: esp_3 = fp
          esp_8 = fp - 0x00000004
esp_3: orig: esp
    def:  esp_3 = fp
eax_4: orig: eax
    def:  eax_4 = a_1
Mem0:Global memory
    def:  def Mem0
    uses: ecx_6 = Mem0[a:word32]
          Mem0[ecx_6 + 0x00000004:word32](dwLoc04_9)
ecx_6: orig: ecx
    def:  ecx_6 = Mem0[a:word32]
    uses: Mem0[ecx_6 + 0x00000004:word32](dwLoc04_9)
v5_7: orig: v5
    def:  v5_7 = 0x0000000A
esp_8: orig: esp
    def:  esp_8 = fp - 0x00000004
dwLoc04_9: orig: dwLoc04
    def:  dwLoc04_9 = 0x0000000A
    uses: Mem0[ecx_6 + 0x00000004:word32](dwLoc04_9)
esp_10: orig: esp
eax_11: orig: eax
ecx_12: orig: ecx
// test
// Return size: 4
void test(str * a)
fn0C00_0000_entry:
	def a
	def fp
	def Mem0
	// succ:  l0C00_0000
l0C00_0000:
	a_1 = a
	esp_3 = fp
	eax_4 = a_1
	ecx_6 = Mem0[a:word32]
	v5_7 = 0x0000000A
	esp_8 = fp - 0x00000004
	dwLoc04_9 = 0x0000000A
	Mem0[ecx_6 + 0x00000004:word32](dwLoc04_9)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

