// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ax = Mem0[ds:0x0200:word16]
	dx = Mem0[ds:0x0202:word16]
	cx = Mem0[ds:0x0204:word16]
	bx = Mem0[ds:0x0206:word16]
	ax = ax + cx
	SCZO = cond(ax)
	dx_ax = dx_ax + bx_cx
	SCZO = cond(dx_ax)
	Mem0[ds:0x0208:word16] = ax
	Mem0[ds:0x020A:word16] = dx
	ax = Mem0[ds:0x0210:word16]
	dx = Mem0[ds:0x0212:word16]
	es_cx = Mem0[ds:0x0214:ptr32]
	bx = es
	ax = ax - cx
	SCZO = cond(ax)
	Mem0[ds:0x0218:word16] = ax
	dx_ax = dx_ax - bx_cx
	SCZO = cond(dx_ax)
	Mem0[ds:0x021A:word16] = dx
	ax = 0x0000
	SZO = cond(ax)
	C = false
	cl = Mem0[ds:0x0220:byte]
	SCZO = cond(cl - 0x30)
	ax = 0x0000 + C
	SCZO = cond(ax)
	cl = Mem0[ds:0x0221:byte]
	SCZO = cond(cl - 0x3A)
	C = !C
	ax = ax + ax + C
	SCZO = cond(ax)
	Mem0[ds:0x0222:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

