// ArrayLoopMock
// Return size: 0
void ArrayLoopMock()
ArrayLoopMock_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ArrayLoopMock_exit
l1:
	ptr_1 = 0x04000000
	goto looptest
	// succ:  looptest
l2:
	Mem3[ptr_2:word32] = 0x00000000
	ptr_4 = ptr_2 + 0x00000004
	// succ:  looptest
looptest:
	ptr_2 = PHI(ptr_1, ptr_4)
	branch ptr_2 >=u 0x04001000 done
	goto l2
	// succ:  l2 done
ArrayLoopMock_exit:

(0x04000000 0x00000004 0x04001000)
