// ByteArrayLoopMock
void ByteArrayLoopMock()
ByteArrayLoopMock_entry:		// block 0, pred:
	def a
	// succ:  1
l1:		// block 1, pred: 0
	i_4 = 0x00000000
	// succ:  2
loop:		// block 2, pred: 1 3
	i_5 = PHI(i_4, i_8)
	branch i_5 < 0x0000000A
	// succ:  4 3
body:		// block 3, pred: 2
	store(Mem7[a + i_5:byte]) = 0x00
	i_8 = i_5 + 0x00000001
	// succ:  2
l2:		// block 4, pred: 2
	return
	// succ:  5
ByteArrayLoopMock_exit:		// block 5, pred: 4
	// succ: 
