// WhileLtIncMock
// Return size: 0
define WhileLtIncMock
WhileLtIncMock_entry:
	def a
	// succ:  l1
l1:
	i_1 = 0x00000000
	goto loopHdr
	// succ:  loopHdr
l2:
	return
	// succ:  WhileLtIncMock_exit
loop:
	Mem4[a + i_2 * 0x00000004:word32] = 0x00000000
	i_5 = i_2 + 0x00000001
	// succ:  loopHdr
loopHdr:
	i_2 = PHI((i_1, l1), (i_5, loop))
	branch i_2 < 0x00000064 loop
	goto l2
	// succ:  l2 loop
WhileLtIncMock_exit:

(0x00000000 0x00000001 0x00000064 signed)
