// WhileGtDecMock
// Return size: 0
define WhileGtDecMock
WhileGtDecMock_entry:
	def a
	// succ:  l1
l1:
	i_1 = 0x00000064
	goto loopHdr
	// succ:  loopHdr
l2:
	return
	// succ:  WhileGtDecMock_exit
loop:
	i_3 = i_2 - 1
	Mem5[a + i_3 * 0x00000004:word32] = 0x00000000
	// succ:  loopHdr
loopHdr:
	i_2 = PHI((i_1, l1), (i_3, loop))
	branch i_2 > 0 loop
	goto l2
	// succ:  l2 loop
WhileGtDecMock_exit:

(0x00000063 -1 -1 signed)
