// WhileLtIncMock
// Return size: 0
void WhileLtIncMock()
WhileLtIncMock_entry:
	def a
	// succ:  l1
l1:
	i_0 = 0x00000000
	goto loopHdr
	// succ:  loopHdr
l2:
	return
	// succ:  WhileLtIncMock_exit
loop:
	Mem2[a + i_1 * 0x00000004:word32] = 0x00000000
	i_4 = i_1 + 0x00000001
	// succ:  loopHdr
loopHdr:
	i_1 = PHI((i_0, l1), (i_4, loop))
	branch i_1 < 0x00000064 loop
	goto l2
	// succ:  l2 loop
WhileLtIncMock_exit:

(0x00000000 0x00000001 0x00000064 signed)
