// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15] si:[0..15]
	Trashed:   SCZO ax Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
	def si
	def Mem0
l0C00_0000:
	ax_7 = Mem0[ds:si + 0x200<16>:word16]
	Mem8[ds:0x200<16>:word16] = 0<16>
	Mem9[ds:0x300<16>:word16] = ax_7
	ax_10 = Mem9[ds:si + 0x202<16>:word16]
	Mem11[ds:0x202<16>:word16] = ax_10
	ax_12 = Mem11[ds:si + 0x204<16>:word16]
	v7_13 = Mem11[ds:0x204<16>:word16] + ax_12
	Mem14[ds:0x204<16>:word16] = v7_13
	ax_16 = Mem14[ds:0x200<16>:word16]
	call fn0C00_002A (retsize: 2;)
		uses: ds:ds
	Mem17[ds:0x200<16>:word16] = ax_16
	return
fn0C00_0000_exit:
// fn0C00_002A /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15]
	Trashed:   Top
	Preserved: ax sp
// fn0C00_002A
define fn0C00_002A
fn0C00_002A_entry:
	def ds
l0C00_002A:
	Mem9[ds:0x200<16>:word16] = 0xFFFF<16>
	return
fn0C00_002A_exit:
