// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ds
	BypassIn: 
	Trashed:   ah al ax eax esi rax rsi si sil
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
// SymbolicIn: sp:fp
fn0C00_0000_entry:
	sp = fp
// DataOut: ds
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0000:
	si = 0x1234
	call fn0C00_000B (retsize: 2; depth: 2)
	Mem0[ds:0x5431:word16] = ax
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp si:0x1234 ax:<invalid>
fn0C00_0000_exit:
// DataOut:
// DataOut (flags): 

// fn0C00_000B /////////////////////
	LiveOut:   ax ds
	MayUseIn:  ds si
	BypassIn: 
	Trashed:   ah al ax eax rax
	Preserved: si sp
// fn0C00_000B
void fn0C00_000B()
// SymbolicIn: sp:fp
fn0C00_000B_entry:
	sp = fp
// DataOut: ds si
// DataOut (flags): 
// LocalsOut: fp(16)

// SymbolicIn: sp:fp
l0C00_000B:
	sp = fp - 2
	wLoc02 = si
	call fn0C00_0011 (retsize: 2; depth: 4)
	si = wLoc02
	sp = fp
	return
// DataOut: ax ds
// DataOut (flags): 

// SymbolicIn: sp:fp si:si ax:<invalid> -2(fp):si
fn0C00_000B_exit:
// DataOut: ax ds
// DataOut (flags): 

// fn0C00_0011 /////////////////////
	LiveOut:   ax ds
	MayUseIn:  ds si
	BypassIn: 
	Trashed:   ah al ax eax rax
	Preserved: sp
// fn0C00_0011
void fn0C00_0011()
// SymbolicIn: sp:fp
fn0C00_0011_entry:
	sp = fp
// DataOut: ds si
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0011:
	ax = Mem0[ds:si + 0x0004:word16]
	return
// DataOut: ax ds
// DataOut (flags): 

// SymbolicIn: sp:fp ax:<invalid>
fn0C00_0011_exit:
// DataOut: ax ds
// DataOut (flags): 

