// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15]
	Trashed:   SCZO ax cx dx Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
l0C00_0000:
	call fn0C00_000B (retsize: 2;)
		uses: cx:0x0005
		defs: ax:ax_5
	Mem14[ds:0x0064:word16] = ax_5
	return
fn0C00_0000_exit:
// fn0C00_000B /////////////////////
	LiveOut:   ax:[0..15]
	BitsUsed:  cx:[0..15]
	Trashed:   SCZO ax cx dx Top
	Preserved: si sp
// fn0C00_000B
define fn0C00_000B
fn0C00_000B_entry:
	def cx
l0C00_000B:
	branch cx <= 0x0001 l0C00_001C
l0C00_0011:
	call fn0C00_000B (retsize: 2;)
		uses: cx:cx - 0x0001
		defs: ax:ax_18
	dx_ax_21 = cx *s ax_18
	ax_23 = SLICE(dx_ax_21, word16, 0) (alias)
l0C00_001C:
	ax_11 = 0x0001
l0C00_001F:
	ax_32 = PHI((ax_23, l0C00_0011), (ax_11, l0C00_001C))
	return
fn0C00_000B_exit:
	use ax_32
