// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ds
	BypassIn: 
	Trashed:   SCZO ah al ax ch cl cx dh dl dx eax ecx edx rax rcx rdx
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
// SymbolicIn: sp:fp
fn0C00_0000_entry:
// DataOut: ds
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0000:
	sp = fp
	cx = 0x0005
	call fn0C00_000B (retsize: 2; depth: 2)
	Mem0[ds:0x0064:word16] = ax
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp cx:<invalid> dx:<invalid> ax:<invalid>
fn0C00_0000_exit:
// DataOut:
// DataOut (flags): 

// fn0C00_000B /////////////////////
	LiveOut:   ax ds
	MayUseIn:  cx
	BypassIn: 
	Trashed:   SCZO ah al ax ch cl cx dh dl dx eax ecx edx rax rcx rdx
	Preserved: si sp
// fn0C00_000B
void fn0C00_000B()
// SymbolicIn: sp:fp
fn0C00_000B_entry:
// DataOut: cx ds
// DataOut (flags): 
// LocalsOut: fp(16)

// SymbolicIn: sp:fp
l0C00_000B:
	sp = fp
	sp = fp - 2
	wLoc02 = si
	SCZO = cond(cx - 0x0001)
	branch Test(LE,SZO) l0C00_001C
// DataOut: cx ds
// DataOut (flags): 

// SymbolicIn: sp:fp - 2 -2(fp):si
l0C00_0011:
	si = cx
	cx = cx - 0x0001
	SZO = cond(cx)
	call fn0C00_000B (retsize: 2; depth: 4)
	dx_ax = si *s ax
	SCZO = cond(dx_ax)
// DataOut: ax ds
// DataOut (flags): 

// SymbolicIn: sp:fp - 2 -2(fp):si
l0C00_001C:
	ax = 0x0001
// DataOut: ax ds
// DataOut (flags): 

// SymbolicIn: sp:fp - 2 si:cx cx:<invalid> Sequence dx:ax:<invalid> ax:<invalid> dx:<invalid> -2(fp):si
l0C00_001F:
	si = wLoc02
	sp = fp
	return
// DataOut: ax ds
// DataOut (flags): 

// SymbolicIn: sp:fp si:si cx:<invalid> Sequence dx:ax:<invalid> ax:<invalid> dx:<invalid> -2(fp):si
fn0C00_000B_exit:
// DataOut: ax ds
// DataOut (flags): 

