// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  bx ds
	BypassIn: 
	Trashed:   ah al ax eax rax
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
// SymbolicIn: sp:fp
fn0C00_0000_entry:
	sp = fp
// DataOut: bx ds
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0000:
	call fn0C00_0006 (retsize: 2; depth: 2)
	Mem0[ds:bx:word16] = 0x0001
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp ax:0x0001
fn0C00_0000_exit:
// DataOut:
// DataOut (flags): 

// fn0C00_0006 /////////////////////
	LiveOut:   bx ds
	MayUseIn: 
	BypassIn: 
	Trashed:   ah al ax eax rax
	Preserved: sp
// fn0C00_0006
void fn0C00_0006()
// SymbolicIn: sp:fp
fn0C00_0006_entry:
	sp = fp
// DataOut: bx ds
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0006:
	ax = 0x0001
	return
// DataOut: bx ds
// DataOut (flags): 

// SymbolicIn: sp:fp ax:0x0001
fn0C00_0006_exit:
// DataOut: bx ds
// DataOut (flags): 

