// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  bx ds
	BypassIn: 
	Trashed:   ax al ah
	Preserved:
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
// DataOut: bx ds
l0C00_0000:		// block 1, pred: 0
	call fn0C00_0006 (depth: 2;)
	store(Mem0[ds:bx:word16]) = ax
	return
	// succ:  2
// DataOut:
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 
// DataOut:
// fn0C00_0006 /////////////////////
	LiveOut:   ax bx ds
	MayUseIn: 
	BypassIn: 
	Trashed:   ax al ah
	Preserved:
// fn0C00_0006
void fn0C00_0006()
fn0C00_0006_entry:		// block 0, pred:
	// succ:  1
// DataOut: bx ds
l0C00_0006:		// block 1, pred: 0
	ax = 0x0001
	return
	// succ:  2
// DataOut: ax bx ds
fn0C00_0006_exit:		// block 2, pred: 1
	// succ: 
// DataOut: ax bx ds
