// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  Sequence ds:bx:[0..31]
	Trashed:   ax Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds_bx
l0C00_0000:
	call fn0C00_0006 (retsize: 2;)
		defs: ax:ax_4
	Mem7[ds_bx:word16] = ax_4
	return
fn0C00_0000_exit:
// fn0C00_0006 /////////////////////
	LiveOut:   ax:[0..15]-fn0C00_0000
	BitsUsed: 
	Trashed:   ax Top
	Preserved: sp
// fn0C00_0006
define fn0C00_0006
fn0C00_0006_entry:
l0C00_0006:
	ax_4 = 1<16>
	return
fn0C00_0006_exit:
	use ax_4
