// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ds
	BypassIn: 
	Trashed:   SCZO ax cx dx bx al cl dl bl ah ch dh bh
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
// DataOut: ds
// DataOut (flags):
// SymbolicIn: sp:fp

l0C00_0000:
	ax = 0x0001
	cl = 0x00
	bx = 0x0001
	ch = 0x02
	call fn0C00_001E (retsize: 2; depth: 2)
	bx = 0x0005
	ch = 0x03
	call fn0C00_0032 (retsize: 2; depth: 2)
	Mem0[ds:0x0120:word16] = ax
	Mem0[ds:0x0122:byte] = cl
	return
// DataOut:
// DataOut (flags):
// SymbolicIn: sp:fp

fn0C00_0000_exit:
// DataOut:
// DataOut (flags):
// SymbolicIn: sp:fp ax:<invalid> cl:<invalid> bx:0x0005 ch:0x03 dx:<invalid>

// fn0C00_001E /////////////////////
	LiveOut:   ax cl ds
	MayUseIn:  ax bx cl ch
	BypassIn: 
	Trashed:   SCZO ax cx bx al cl bl ah bh
	Preserved: sp
// fn0C00_001E
void fn0C00_001E()
fn0C00_001E_entry:
// DataOut: ax bx cl ch ds
// DataOut (flags):
// SymbolicIn: sp:fp
l0C00_001E:
	cl = cl - ch
	SCZO = cond(cl)
	branch Test(ULT,C) l0C00_0027
// DataOut: ax bx cl ch ds
// DataOut (flags):
// SymbolicIn: sp:fp
l0C00_0022:
	bx = bx >> cl
	SCZO = cond(bx)
// DataOut: ax bx cl ch ds
// DataOut (flags):
// SymbolicIn: sp:fp cl:cl - ch

l0C00_0027:
	cl = -cl
	SCZO = cond(cl)
	C = cl == 0x00
	ax = ax >> cl
	SCZO = cond(ax)
	cl = -cl
	SCZO = cond(cl)
	C = cl == 0x00
// DataOut: ax bx cl ch ds
// DataOut (flags):
// SymbolicIn: sp:fp cl:cl - ch

l0C00_002D:
	ax = ax + bx
	SCZO = cond(ax)
	cl = cl + ch
	SCZO = cond(cl)
	return
// DataOut: ax cl ds
// DataOut (flags):
// SymbolicIn: sp:fp cl:cl - ch ax:ax >> ch - cl bx:bx >> cl - ch
fn0C00_001E_exit:
// DataOut: ax cl ds
// DataOut (flags):
// SymbolicIn: sp:fp cl:cl - ch + ch ax:(ax >> ch - cl) + (bx >> cl - ch) bx:bx >> cl - ch

// fn0C00_0032 /////////////////////
	LiveOut:   ax cl ds
	MayUseIn:  ax bx cl ch
	BypassIn: 
	Trashed:   SCZO ax cx dx al cl dl ah dh
	Preserved: sp
// fn0C00_0032
void fn0C00_0032()
fn0C00_0032_entry:
// DataOut: ax bx cl ch ds
// DataOut (flags):
// SymbolicIn: sp:fp

l0C00_0032:
	dx_ax = bx *s ax
	SCZO = cond(dx_ax)
	cl = cl + ch
	SCZO = cond(cl)
	return
// DataOut: ax cl ds
// DataOut (flags):
// SymbolicIn: sp:fp

fn0C00_0032_exit:
// DataOut: ax cl ds
// DataOut (flags):
// SymbolicIn: sp:fp Sequence dx:ax:bx *s ax cl:cl + ch
