// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def dx
l0C00_0000:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx
	return
fn0C00_0000_exit:
// fn0C00_0004 /////////////////////
	LiveOut:   ax:[0..15] dx:[0..15]
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0004
define fn0C00_0004
fn0C00_0004_entry:
	def dx
l0C00_0004:
	branch dx != 0x1E<16> l0C00_000F
l0C00_0009:
	call fn0C00_0013 (retsize: 2;)
		uses: dx:dx
		defs: dx:dx_11
l0C00_000F:
	dx_7 = dx - 1<16>
l0C00_0010:
	dx_15 = PHI((dx_11, l0C00_0009), (dx_7, l0C00_000F))
	ax_16 = dx_15
	return
fn0C00_0004_exit:
	use ax_16
	use dx_15
// fn0C00_0013 /////////////////////
	LiveOut:   dx:[0..15]
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0013
define fn0C00_0013
fn0C00_0013_entry:
	def dx
l0C00_0013:
	branch dx < 0x14<16> l0C00_001F
l0C00_0018:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx - 1<16>
		defs: dx:dx_18
l0C00_001F:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx - 0xA<16>
		defs: dx:dx_11
l0C00_0025:
	dx_28 = PHI((dx_18, l0C00_0018), (dx_11, l0C00_001F))
	return
fn0C00_0013_exit:
	use dx_28
