// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def dx
l0C00_0000:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx
	return
fn0C00_0000_exit:
// fn0C00_0004 /////////////////////
	LiveOut:   ax:[0..15] dx:[0..15]
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0004
define fn0C00_0004
fn0C00_0004_entry:
	def dx
l0C00_0004:
	branch dx != 0x001E l0C00_000F
l0C00_0009:
	call fn0C00_0013 (retsize: 2;)
		uses: dx:dx
		defs: dx:dx_10,SCZO:SCZO_14
l0C00_000F:
	dx_7 = dx - 0x0001
l0C00_0010:
	dx_15 = PHI(dx_10, dx_7)
	ax_16 = dx_15
	return
fn0C00_0004_exit:
	use ax_16
	use dx_15
// fn0C00_0013 /////////////////////
	LiveOut:   dx:[0..15]
	BitsUsed:  dx:[0..15]
	Trashed:   SCZO ax dx Top
	Preserved: sp
// fn0C00_0013
define fn0C00_0013
fn0C00_0013_entry:
	def dx
l0C00_0013:
	branch dx < 0x0014 l0C00_001F
l0C00_0018:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx - 0x0001
		defs: ax:ax_19,dx:dx_18,SCZO:SCZO_21
l0C00_001F:
	call fn0C00_0004 (retsize: 2;)
		uses: dx:dx - 0x000A
		defs: ax:ax_12,dx:dx_10,SCZO:SCZO_14
l0C00_0025:
	dx_28 = PHI(dx_18, dx_10)
	return
fn0C00_0013_exit:
	use dx_28
