// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ax ds
	BypassIn: 
	Trashed:   SCZO ah al ax eax esi rax rsi si sil
	Preserved: bp sp
// fn0C00_0000
void fn0C00_0000()
// SymbolicIn: sp:fp
fn0C00_0000_entry:
	sp = fp
// DataOut: ax ds
// DataOut (flags): 
// LocalsOut: fp(16) Stack +0004(16)

// SymbolicIn: sp:fp
l0C00_0000:
	sp = fp - 2
	wLoc02 = bp
	bp = fp - 2
	si = ax
	ax = Mem0[ds:si + 0x0004:word16]
	ax = ax + Mem0[ds:si + 0x0006:word16]
	SCZO = cond(ax)
	si = wArg04
	ax = ax + Mem0[ds:si + 0x0004:word16]
	SCZO = cond(ax)
	ax = ax + Mem0[ds:si + 0x0006:word16]
	SCZO = cond(ax)
	sp = fp - 2
	bp = wLoc02
	sp = fp
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp bp:bp si:<invalid> ax:<invalid> -2(fp):bp
fn0C00_0000_exit:
// DataOut:
// DataOut (flags): 

