// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  di:[0..15] ds:[0..15]
	BypassIn: 
	Trashed:   SCZO ax Top
	Preserved: di sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
	def di
l0C00_0000:
	call fn0C00_000F (retsize: 2;)
		uses: di:di,ds:ds
	call fn0C00_0014 (retsize: 2;)
		uses: ax:0x0100
		defs: ax:ax_10
	Mem16[ds:0x0300:word16] = ax_10
l0C00_000E_thunk_fn0C00_000F:
	call fn0C00_000F (retsize: 0;)
		uses: di:di,ds:ds
	return
fn0C00_0000_exit:
// fn0C00_000F /////////////////////
	LiveOut:  
	BitsUsed:  di:[0..15] ds:[0..15]
	BypassIn: 
	Trashed:   Top
	Preserved: sp
// fn0C00_000F
define fn0C00_000F
fn0C00_000F_entry:
	def ds
	def di
l0C00_000F:
	Mem6[ds:di:word16] = 0x0000
	return
fn0C00_000F_exit:
// fn0C00_0014 /////////////////////
	LiveOut:   ax
	BitsUsed:  ax:[0..15]
	BypassIn: 
	Trashed:   SCZO ax di Top
	Preserved: sp
// fn0C00_0014
define fn0C00_0014
fn0C00_0014_entry:
	def ax
l0C00_0014:
	ax_7 = ax - 0x0001
	return
fn0C00_0014_exit:
	use ax_7
