// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  di:[0..15] ds:[0..15] si:[0..15]
	BypassIn: 
	Trashed:   SCZO ax cx Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def di
	def ds
	def si
l0C00_0000:
	call fn0C00_0008 (retsize: 2;)
		uses: cx:0x0014,di:di,ds:ds
		defs: ax:ax_7
	Mem13[ds:si:word16] = ax_7
l0C00_0006_thunk_fn0C00_0008:
	call fn0C00_0008 (retsize: 0;)
		uses: cx:0x0014,di:di,ds:ds
	return
fn0C00_0000_exit:
// fn0C00_0008 /////////////////////
	LiveOut:   ax
	BitsUsed:  cx:[0..15] di:[0..15] ds:[0..15]
	BypassIn: 
	Trashed:   SCZO ax Top
	Preserved: di si sp
// fn0C00_0008
define fn0C00_0008
fn0C00_0008_entry:
	def di
	def cx
	def ds
l0C00_0008:
	si_11 = 0x0000
l0C00_000D:
	di_25 = PHI(di, di_27)
	si_15 = PHI(si_11, si_26)
	branch cx == 0x0000 l0C00_001A
l0C00_0012:
	si_26 = si_15 + Mem10[ds:di_25:word16]
	di_27 = di_25 + 0x0002
l0C00_001A:
	ax_16 = si_15
	return
fn0C00_0008_exit:
	use ax_16
