// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ax:[0..15] bx:[0..15] dx:[0..15] ss:[0..15]
	Trashed:  
	Preserved:
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def bx
	def ss
	def ax
	def dx
l0C00_0000:
	Mem8[ss:0x6B6<16>:word16] = bx
	Mem11[ss:0x6B4<16>:word16] = ax
	Mem14[ss:0x6B2<16>:word16] = dx
	msdos_open_file(0800:0887, 1<8>, out ax_21)
	ds_24 = Mem14[ss:0x6B2<16>:selector]
	dx_26 = Mem14[ss:0x6B4<16>:word16]
	si_28 = dx_26
l0C00_0019:
	si_30 = PHI((si_28, l0C00_0000), (si_33, l0C00_0019))
	al_32 = Mem14[ds_24:si_30:byte]
	si_33 = si_30 + 1<i16>
	branch al_32 != 0<8> l0C00_0019
l0C00_001E:
	cx_38 = si_33 - dx_26
	ds_dx_43 = SEQ(ds_24, dx_26) (alias)
	msdos_write_file(ax_21, cx_38 - 1<16>, ds_dx_43, out ax_44)
	ax_48 = Mem14[ss:0x6B6<16>:word16]
	Mem51[ss:0x6B6<16>:word16] = ax_48
	call fn0C00_0037 (retsize: 2;)
		uses: ax:0<16>,ds:ds_24,dx:0xFF<16>
	al_57 = Mem51[ss:0x6B6<16>:byte]
	msdos_terminate(al_57)
fn0C00_0000_exit:
// fn0C00_0037 /////////////////////
	LiveOut:  
	BitsUsed:  ax:[0..15] ds:[0..15] dx:[0..15]
	Trashed:   Top
	Preserved: sp
// fn0C00_0037
define fn0C00_0037
fn0C00_0037_entry:
	def ax
	def ds
	def dx
l0C00_0037:
	Mem6[ds:0x300<16>:word16] = ax
	Mem8[ds:0x302<16>:word16] = dx
	return
fn0C00_0037_exit:
