// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15]
	Trashed:   ax si Top
	Preserved: ds sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
l0C00_0000:
	ds_si_6 = SEQ(ds, 0x200<16>) (alias)
	call fn0C00_0015 (retsize: 2;)
		uses: Sequence ds:si:ds_si_6
		defs: ax:ax_7
	Mem8[ds:0x202<16>:word16] = ax_7
	ds_si_10 = SEQ(ds, 0x300<16>) (alias)
	call fn0C00_0015 (retsize: 2;)
		uses: Sequence ds:si:ds_si_10
		defs: ax:ax_11
	al_12 = SLICE(ax_11, byte, 0) (alias)
	Mem13[ds:0x302<16>:byte] = al_12
	return
fn0C00_0000_exit:
// fn0C00_0015 /////////////////////
	LiveOut:   ax:[0..15]
	BitsUsed:  Sequence ds:si:[0..31]
	Trashed:   ax Top
	Preserved: sp
// fn0C00_0015
define fn0C00_0015
fn0C00_0015_entry:
	def ds_si
	def Mem0
l0C00_0015:
	ax_7 = Mem0[ds_si:word16]
	return
fn0C00_0015_exit:
	use ax_7
