// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15]
	Trashed:   ax si Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
l0C00_0000:
	call fn0C00_0015 (retsize: 2;)
		uses: ds:ds,si:0x0200
		defs: ax:ax_6
	Mem7[ds:0x0202:word16] = ax_6
	call fn0C00_0015 (retsize: 2;)
		uses: ds:ds,si:0x0300
		defs: ax:ax_9
	al_10 = (byte) ax_9 (alias)
	Mem11[ds:0x0302:byte] = al_10
	return
fn0C00_0000_exit:
// fn0C00_0015 /////////////////////
	LiveOut:   ax:[0..15]
	BitsUsed:  ds:[0..15] si:[0..15]
	Trashed:   ax Top
	Preserved: sp
// fn0C00_0015
define fn0C00_0015
fn0C00_0015_entry:
	def ds
	def si
	def Mem0
l0C00_0015:
	ax_7 = Mem0[ds:si:word16]
	return
fn0C00_0015_exit:
	use ax_7
