// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ds eax es si
	BypassIn: 
	Trashed:   SCZO ah al ax ch cl cx di dil eax ecx edi esi rax rcx rdi rsi si sil
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
// SymbolicIn: sp:fp
fn0C00_0000_entry:
	sp = fp
// DataOut: ds eax es si
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0000:
	eax = eax + eax * 0x00000004
	Mem0[ds:0x02FC:word32] = eax
	eax = Mem0[ds:si:word32]
	si = si + 0x0004
	Mem0[ds:0x0300:word32] = eax
	eax = Mem0[ds:si:word32]
	si = si + 0x0004
	Mem0[ds:0x0304:word32] = eax
	ax = Mem0[ds:si:word16]
	si = si + 0x0002
	Mem0[ds:0x0308:word16] = ax
	ax = Mem0[ds:si:word16]
	si = si + 0x0002
	Mem0[ds:0x030A:word16] = ax
	call fn0C00_0026 (retsize: 2; depth: 2)
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp eax:<invalid> si:si + 0x0036 ax:<invalid> cx:<invalid> al:0x00 di:<invalid>
fn0C00_0000_exit:
// DataOut:
// DataOut (flags): 

// fn0C00_0026 /////////////////////
	LiveOut:  
	MayUseIn:  ds es
	BypassIn: 
	Trashed:   SCZO al ax ch cl cx di dil eax ecx edi rax rcx rdi
	Preserved: sp
// fn0C00_0026
void fn0C00_0026()
// SymbolicIn: sp:fp
fn0C00_0026_entry:
	sp = fp
// DataOut: ds es
// DataOut (flags): 

// SymbolicIn: sp:fp
l0C00_0026:
	cx = Mem0[ds:0x0400:word16]
	al = 0x00
	di = Mem0[ds:0x0402:word16]
// DataOut: cx di ds es
// DataOut (flags): 

// SymbolicIn: sp:fp cx:<invalid> al:0x00 di:<invalid>
l0C00_0030:
	branch cx == 0x0000 l0C00_0032
// DataOut: cx di ds es
// DataOut (flags): 

// SymbolicIn: sp:fp cx:<invalid> al:0x00 di:<invalid>
l0C00_0030_1:
	SCZO = cond(0x00 - Mem0[es:di:byte])
	di = di + 0x0001
	cx = cx - 0x0001
	branch Test(NE,Z) l0C00_0030
// DataOut: cx di ds es
// DataOut (flags): 

// SymbolicIn: sp:fp cx:<invalid> al:0x00 di:<invalid>
l0C00_0032:
	Mem0[ds:0x0404:word16] = di
	return
// DataOut:
// DataOut (flags): 

// SymbolicIn: sp:fp cx:<invalid> al:0x00 di:<invalid>
fn0C00_0026_exit:
// DataOut:
// DataOut (flags): 

