// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15] eax:[0..31] es:[0..15] si:[0..15]
	BypassIn: 
	Trashed:   SCZO cx di eax si Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def eax
	def ds
	def si
	def es
l0C00_0000:
	Mem7[ds:0x02FC:word32] = eax * 0x00000005
	eax_9 = Mem7[ds:si:word32]
	Mem11[ds:0x0300:word32] = eax_9
	eax_12 = Mem11[ds:si + 0x0004:word32]
	Mem14[ds:0x0304:word32] = eax_12
	ax_15 = Mem14[ds:si + 0x0008:word16]
	Mem17[ds:0x0308:word16] = ax_15
	ax_18 = Mem17[ds:si + 0x000A:word16]
	Mem20[ds:0x030A:word16] = ax_18
	call fn0C00_0026 (retsize: 2;)
		uses: ds:ds,es:es
	return
fn0C00_0000_exit:
// fn0C00_0026 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15] es:[0..15]
	BypassIn: 
	Trashed:   SCZO al cx di Top
	Preserved: sp
// fn0C00_0026
define fn0C00_0026
fn0C00_0026_entry:
	def ds
	def Mem0
	def es
l0C00_0026:
	cx_6 = Mem0[ds:0x0400:word16]
	di_8 = Mem0[ds:0x0402:word16]
l0C00_0030:
	di_12 = PHI(di_8, di_15)
	cx_9 = PHI(cx_6, cx_16)
	branch cx_9 == 0x0000 l0C00_0032
l0C00_0030_1:
	di_15 = di_12 + 0x0001
	cx_16 = cx_9 - 0x0001
	branch 0x00 != Mem0[es:di_12:byte] l0C00_0030
l0C00_0032:
	di_18 = PHI(di_12, di_15)
	Mem21[ds:0x0404:word16] = di_18
	return
fn0C00_0026_exit:
