// fn0C00_0000 /////////////////////
	LiveOut:  
	BitsUsed:  ds:[0..15]
	Trashed:   SCZO ax bx cx Top
	Preserved: sp
// fn0C00_0000
define fn0C00_0000
fn0C00_0000_entry:
	def ds
l0C00_0000:
	call maybeterminate (retsize: 2;)
		uses: ax:0x20<16>,bx:0x3212<16>,ds:ds
		defs: ax:ax_8
	Mem14[ds:0x230<16>:word16] = ax_8
	Mem15[ds:0x234<16>:word16] = 0x7B<16>
	return
fn0C00_0000_exit:
// maybeterminate /////////////////////
	LiveOut:   ax:[0..15]
	BitsUsed:  ax:[0..15] bx:[0..15] ds:[0..15]
	Trashed:   SCZO ax bx Top
	Preserved: sp
// maybeterminate
define maybeterminate
fn0C00_0015_entry:
	def ax
	def ds
	def bx
	def Mem0
l0C00_0015:
	branch ax <u Mem0[ds:bx:word16] l0C00_0023
l0C00_0019:
	branch ax >=u Mem0[ds:bx + 2<i16>:word16] l0C00_0023
l0C00_001E:
	bx_19 = bx + ax
	ax_21 = Mem0[ds:bx_19:word16]
	return
l0C00_0023:
	Mem16[ds:0x232<16>:word16] = 0<16>
	msdos_terminate(0<8>)
fn0C00_0015_exit:
	use ax_21
