Mem0:Global memory
fp:fp
tmp:Local -0004
reg:Local -0008
    def:  def reg
    uses: branch (reg & 0x00000001) == 0x00000000 even
          reg_5 = PHI(reg, reg_6)
          reg_6 = reg + 0x00000002
          return reg_5 - reg
tmp_4: orig: tmp
reg_5: orig: reg
    def:  reg_5 = PHI(reg, reg_6)
    uses: return reg_5 - reg
reg_6: orig: reg
    def:  reg_6 = reg + 0x00000002
    uses: reg_5 = PHI(reg, reg_6)
// LiveCopyMock
void LiveCopyMock()
	// liveIn: 
LiveCopyMock_entry:
	def reg
	goto l1
	// liveOut: reg
	// liveIn: reg
even:
	reg_5 = PHI(reg, reg_6)
	return reg_5 - reg
	// liveOut: 
	// liveIn: reg
l1:
	branch (reg & 0x00000001) == 0x00000000 even
	// liveOut: reg
	// liveIn: reg
l2:
	reg_6 = reg + 0x00000002
	goto even
	// liveOut: reg reg_6
	// liveIn: 
LiveCopyMock_exit:
	// liveOut: 

