liveIn: 
LiveLoopMock_entry:		// block 0, pred:
	def Mem0
	def i
	// succ:  1
liveOut: Mem0 i

liveIn:  Mem0
loop:		// block 1, pred: 0 1
	i_4 = PHI(i, i_6)
	i_6 = i_4 + 0x00000001
	branch Mem0[i_6:byte] != 0x00 loop
	// succ:  2 1
liveOut: Mem0 i_4 i_6

liveIn:  i_4
l1:		// block 2, pred: 1
	return i_4
	// succ:  3
liveOut:

liveIn: 
LiveLoopMock_exit:		// block 3, pred: 2
	// succ: 
liveOut:

=======================
