a:Stack -0004
    def:  def a
    uses: Mem5[0x10000004<32>:word32] = a
          Mem4[0x10000000<32>:word32] = a + b
b:Stack -0008
    def:  def b
    uses: Mem4[0x10000000<32>:word32] = a + b
c_3: orig: c
Mem4: orig: Mem0
    def:  Mem4[0x10000000<32>:word32] = a + b
Mem5: orig: Mem0
    def:  Mem5[0x10000004<32>:word32] = a
// SimpleMock
define SimpleMock
	// liveIn: 
SimpleMock_entry:
	def a
	def b
	// liveOut: a b
	// liveIn: a b
l1:
	Mem4[0x10000000<32>:word32] = a + b
	Mem5[0x10000004<32>:word32] = a
	// liveOut: 
	// liveIn: 
SimpleMock_exit:
	// liveOut: 

