Mem0:Global memory
fp:Temporary
a:Local -0004
    def:  def a
    uses: Mem6[0x10000000:word32] = a + b
          Mem7[0x10000004:word32] = a
b:Local -0008
    def:  def b
    uses: Mem6[0x10000000:word32] = a + b
c:Local -000C
c_5: orig: c
    uses: Mem6[0x10000000:word32] = a + b
Mem6: orig: Mem0
    def:  Mem6[0x10000000:word32] = a + b
Mem7: orig: Mem0
    def:  Mem7[0x10000004:word32] = a
liveIn:  c_5
SimpleMock_entry:		// pred:
	def a
	def b
	// succ:  l1
liveOut: a b c_5

liveIn:  a b c_5
l1:		// pred: SimpleMock_entry
	Mem6[0x10000000:word32] = a + b
	Mem7[0x10000004:word32] = a
	// succ: 
liveOut:


