Mem0:Global memory
fp:fp
a:Local -0004
    def:  def a
    uses: Mem6[0x10000000:word32] = a + b
          Mem7[0x10000004:word32] = a
b:Local -0008
    def:  def b
    uses: Mem6[0x10000000:word32] = a + b
c:Local -000C
c_5: orig: c
Mem6: orig: Mem0
    def:  Mem6[0x10000000:word32] = a + b
Mem7: orig: Mem0
    def:  Mem7[0x10000004:word32] = a
// SimpleMock
void SimpleMock()
	// liveIn: 
SimpleMock_entry:
	def a
	def b
	// liveOut: a b
	// liveIn: a b
l1:
	Mem6[0x10000000:word32] = a + b
	Mem7[0x10000004:word32] = a
	// liveOut: 
	// liveIn: 
SimpleMock_exit:
	// liveOut: 

