fp:fp
sp_2: orig: sp
Top_3: orig: Top
si:si
    def:  def si
    uses: ax_27 = si_10 - si
          si_7 = PHI((si, l0C00_0000), (si_10, l0C00_0011), (si_10, l0C00_0016))
bx_5: orig: bx
si_7: orig: si
    def:  si_7 = PHI((si, l0C00_0000), (si_10, l0C00_0011), (si_10, l0C00_0016))
    uses: ax_9 = Mem8[ds:si_7:word16]
          si_10 = si_7 + 2<i16>
Mem8: orig: Mem0
    def:  Mem8 = PHI((Mem0, l0C00_0000), (Mem14, l0C00_0011), (Mem22, l0C00_0016))
    uses: ax_9 = Mem8[ds:si_7:word16]
ax_9: orig: ax
    def:  ax_9 = Mem8[ds:si_7:word16]
    uses: Mem14[ds:di:word16] = ax_9
          branch ax_9 != 0x20<16> l0C00_0005
          branch ax_9 != 0<16> l0C00_0011
          branch ax_9 != 0xD<16> l0C00_001A
si_10: orig: si
    def:  si_10 = si_7 + 2<i16>
    uses: ax_27 = si_10 - si
          si_7 = PHI((si, l0C00_0000), (si_10, l0C00_0011), (si_10, l0C00_0016))
          si_7 = PHI((si, l0C00_0000), (si_10, l0C00_0011), (si_10, l0C00_0016))
SCZO_11: orig: SCZO
Z_12: orig: Z
Mem14: orig: Mem0
    def:  Mem14[ds:di:word16] = ax_9
    uses: Mem8 = PHI((Mem0, l0C00_0000), (Mem14, l0C00_0011), (Mem22, l0C00_0016))
          Mem22[ds:0x302<16>:word16] = Mem14[ds:0x302<16>:word16] + 1<16>
ax_15: orig: ax
SZO_16: orig: SZO
C_17: orig: C
Z_18: orig: Z
SCZO_19: orig: SCZO
Z_20: orig: Z
v13_21: orig: v13
Mem22: orig: Mem0
    def:  Mem22[ds:0x302<16>:word16] = Mem14[ds:0x302<16>:word16] + 1<16>
    uses: Mem8 = PHI((Mem0, l0C00_0000), (Mem14, l0C00_0011), (Mem22, l0C00_0016))
SZO_23: orig: SZO
ax_24: orig: ax
    def:  ax_24 = 0xFFFF<16>
    uses: ax_29 = PHI((ax_27, l0C00_0020), (ax_24, l0C00_000B))
ax_25: orig: ax
ax_27: orig: ax
    def:  ax_27 = si_10 - si
    uses: ax_29 = PHI((ax_27, l0C00_0020), (ax_24, l0C00_000B))
SCZO_28: orig: SCZO
ax_29: orig: ax
    def:  ax_29 = PHI((ax_27, l0C00_0020), (ax_24, l0C00_000B))
    uses: Mem31[ds:0x300<16>:word16] = ax_29
Mem31: orig: Mem0
    def:  Mem31[ds:0x300<16>:word16] = ax_29
ds:ds
    def:  def ds
    uses: ax_9 = Mem8[ds:si_7:word16]
          Mem14[ds:di:word16] = ax_9
          Mem22[ds:0x302<16>:word16] = Mem14[ds:0x302<16>:word16] + 1<16>
          Mem31[ds:0x300<16>:word16] = ax_29
          Mem22[ds:0x302<16>:word16] = Mem14[ds:0x302<16>:word16] + 1<16>
Mem0:Mem
    def:  def Mem0
    uses: Mem8 = PHI((Mem0, l0C00_0000), (Mem14, l0C00_0011), (Mem22, l0C00_0016))
di:di
    def:  def di
    uses: Mem14[ds:di:word16] = ax_9
// fn0C00_0000
define fn0C00_0000
	// liveIn: 
fn0C00_0000_entry:
	def si
	def ds
	def Mem0
	def di
	// liveOut: si ds Mem0 di
	// liveIn: si ds Mem0 di
l0C00_0000:
	goto l0C00_001A
	// liveOut: si ds Mem0 di
	// liveIn: si ax_9 si_10 ds di
l0C00_0005:
	Mem14[ds:di:word16] = ax_9
	branch ax_9 != 0<16> l0C00_0011
	// liveOut: si ax_9 si_10 Mem14 ds di
	// liveIn: ds
l0C00_000B:
	ax_24 = 0xFFFF<16>
	goto l0C00_0024
	// liveOut: ax_24 ds
	// liveIn: si ax_9 si_10 Mem14 ds di
l0C00_0011:
	branch ax_9 != 0xD<16> l0C00_001A
	// liveOut: si si_10 Mem14 ds di
	// liveIn: si Mem14 ds di
l0C00_0016:
	Mem22[ds:0x302<16>:word16] = Mem14[ds:0x302<16>:word16] + 1<16>
	// liveOut: si Mem22 ds di
	// liveIn: si ds di
l0C00_001A:
	Mem8 = PHI((Mem0, l0C00_0000), (Mem14, l0C00_0011), (Mem22, l0C00_0016))
	si_7 = PHI((si, l0C00_0000), (si_10, l0C00_0011), (si_10, l0C00_0016))
	ax_9 = Mem8[ds:si_7:word16]
	si_10 = si_7 + 2<i16>
	branch ax_9 != 0x20<16> l0C00_0005
	// liveOut: si ax_9 si_10 ds di
	// liveIn: si si_10 ds
l0C00_0020:
	ax_27 = si_10 - si
	// liveOut: ax_27 ds
	// liveIn: ds
l0C00_0024:
	ax_29 = PHI((ax_27, l0C00_0020), (ax_24, l0C00_000B))
	Mem31[ds:0x300<16>:word16] = ax_29
	return
	// liveOut: 
	// liveIn: 
fn0C00_0000_exit:
	// liveOut: 

