// ProcedureBuilder
// Return size: 0
define ProcedureBuilder
ProcedureBuilder_entry:
	goto l1
	// succ:  l1
done:
	return
	// succ:  ProcedureBuilder_exit
l1:
	p_1 = 0x00003000
	goto loop
	// succ:  loop
l2:
	Mem3[p_2 + 0x00000000:int32] = 0
	p_4 = p_2 + 0x00000004
	// succ:  loop
loop:
	p_2 = PHI((p_1, l1), (p_4, l2))
	branch p_2 == 0x00001000 done
	goto l2
	// succ:  l2 done
ProcedureBuilder_exit:
