r2:r2
    def:  def r2
    uses: r1_2 = Mem0[r2:word32]
          call r1_2 (retsize: 4;)	uses: r1_2,r2
Mem0:Global memory
    def:  def Mem0
    uses: r1_2 = Mem0[r2:word32]
r1_2: orig: r1
    def:  r1_2 = Mem0[r2:word32]
    uses: call r1_2 (retsize: 4;)	uses: r1_2,r2
          call r1_2 (retsize: 4;)	uses: r1_2,r2
// SsaCallIndirect
// Return size: 0
void SsaCallIndirect()
SsaCallIndirect_entry:
	def r2
	def Mem0
	// succ:  l1
l1:
	r1_2 = Mem0[r2:word32]
	call r1_2 (retsize: 4;)
		uses: r1_2,r2
	return
	// succ:  SsaCallIndirect_exit
SsaCallIndirect_exit:
