fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
    uses: use sp_2
ax:ax
    def:  def ax
    uses: ax_4 = ax ^ ax
          ax_4 = ax ^ ax
ax_4: orig: ax
    def:  ax_4 = ax ^ ax
    uses: SZO_5 = cond(ax_4)
          ax_7 = PHI(ax_4, ax_19, ax_17)
SZO_5: orig: SZO
    def:  SZO_5 = cond(ax_4)
C_6: orig: C
    def:  C_6 = false
ax_7: orig: ax
    def:  ax_7 = PHI(ax_4, ax_19, ax_17)
    uses: SCZO_9 = cond(ax_7 - bx)
          ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
          ax_19 = ax_7 + Mem0[ds:si_13:word16]
          use ax_7
SCZO_9: orig: SCZO
    def:  SCZO_9 = cond(ax_7 - bx)
    uses: branch Test(LT,SCZO_9) l0C00_0005
          use SCZO_9
si_12: orig: si
    def:  si_12 = Mem0[ds:0x0300:word16]
    uses: si_13 = si_12 | si_12
          si_13 = si_12 | si_12
si_13: orig: si
    def:  si_13 = si_12 | si_12
    uses: SZO_14 = cond(si_13)
          ax_19 = ax_7 + Mem0[ds:si_13:word16]
          si_24 = PHI(si, si_13, si_16)
SZO_14: orig: SZO
    def:  SZO_14 = cond(si_13)
    uses: branch Test(EQ,SZO_14) l0C00_0012
C_15: orig: C
    def:  C_15 = false
si_16: orig: si
    def:  si_16 = Mem0[ds:0x0302:word16]
    uses: ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
          si_24 = PHI(si, si_13, si_16)
ax_17: orig: ax
    def:  ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
    uses: SCZO_18 = cond(ax_17)
          ax_7 = PHI(ax_4, ax_19, ax_17)
SCZO_18: orig: SCZO
    def:  SCZO_18 = cond(ax_17)
ax_19: orig: ax
    def:  ax_19 = ax_7 + Mem0[ds:si_13:word16]
    uses: SCZO_20 = cond(ax_19)
          ax_7 = PHI(ax_4, ax_19, ax_17)
SCZO_20: orig: SCZO
    def:  SCZO_20 = cond(ax_19)
bx:bx
    def:  def bx
    uses: SCZO_9 = cond(ax_7 - bx)
          use bx
ds:ds
    def:  def ds
    uses: si_12 = Mem0[ds:0x0300:word16]
          si_16 = Mem0[ds:0x0302:word16]
          ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
          ax_19 = ax_7 + Mem0[ds:si_13:word16]
          use ds
Mem0:Global memory
    def:  def Mem0
    uses: si_12 = Mem0[ds:0x0300:word16]
          si_16 = Mem0[ds:0x0302:word16]
          ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
          ax_19 = ax_7 + Mem0[ds:si_13:word16]
si_24: orig: si
    def:  si_24 = PHI(si, si_13, si_16)
    uses: use si_24
si:si
    def:  def si
    uses: si_24 = PHI(si, si_13, si_16)
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	def ax
	def bx
	def ds
	def Mem0
	def si
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	ax_4 = ax ^ ax
	SZO_5 = cond(ax_4)
	C_6 = false
	goto l0C00_0019
	// succ:  l0C00_0019
l0C00_0005:
	si_12 = Mem0[ds:0x0300:word16]
	si_13 = si_12 | si_12
	SZO_14 = cond(si_13)
	C_15 = false
	branch Test(EQ,SZO_14) l0C00_0012
	// succ:  l0C00_000D l0C00_0012
l0C00_000D:
	ax_19 = ax_7 + Mem0[ds:si_13:word16]
	SCZO_20 = cond(ax_19)
	goto l0C00_0019
	// succ:  l0C00_0019
l0C00_0012:
	si_16 = Mem0[ds:0x0302:word16]
	ax_17 = ax_7 + Mem0[ds:si_16 + 0x0004:word16]
	SCZO_18 = cond(ax_17)
	// succ:  l0C00_0019
l0C00_0019:
	si_24 = PHI(si, si_13, si_16)
	ax_7 = PHI(ax_4, ax_19, ax_17)
	SCZO_9 = cond(ax_7 - bx)
	branch Test(LT,SCZO_9) l0C00_0005
	// succ:  l0C00_001D l0C00_0005
l0C00_001D:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	use ax_7
	use bx
	use ds
	use SCZO_9
	use si_24
	use sp_2

