fp:fp
    def:  def fp
    uses: sp_1 = fp
          sp_3 = fp - 2
          sp_6 = fp
          SCZO_7 = cond(fp)
sp_1: orig: sp
    def:  sp_1 = fp
cx_2: orig: cx
    def:  cx_2 = 0x0064
sp_3: orig: sp
    def:  sp_3 = fp - 2
wLoc02_4: orig: wLoc02
    def:  wLoc02_4 = 0x0064
    uses: ax_5 = fn0C00_000F(wLoc02_4)
ax_5: orig: ax
    def:  ax_5 = fn0C00_000F(wLoc02_4)
    uses: Mem8[ds:0x0064:word16] = ax_5
sp_6: orig: sp
    def:  sp_6 = fp
SCZO_7: orig: SCZO
    def:  SCZO_7 = cond(fp)
Mem8: orig: Mem0
    def:  Mem8[ds:0x0064:word16] = ax_5
ds:ds
    def:  def ds
    uses: Mem8[ds:0x0064:word16] = ax_5
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def fp
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	sp_1 = fp
	cx_2 = 0x0064
	sp_3 = fp - 2
	wLoc02_4 = 0x0064
	ax_5 = fn0C00_000F(wLoc02_4)
	sp_6 = fp
	SCZO_7 = cond(fp)
	Mem8[ds:0x0064:word16] = ax_5
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_1 = fp
          sp_2 = fp - 2
          bp_5 = fp - 2
          sp_22 = fp
          sp_23 = fp - 4
          sp_26 = fp - 0x0003
          SZO_27 = cond(fp - 0x0003)
          sp_28 = fp - 0x0002
          SZO_29 = cond(fp - 0x0002)
sp_1: orig: sp
    def:  sp_1 = fp
sp_2: orig: sp
    def:  sp_2 = fp - 2
bp:bp
    def:  def bp
    uses: wLoc02_4 = bp
wLoc02_4: orig: wLoc02
    def:  wLoc02_4 = bp
    uses: bp_21 = wLoc02_4
bp_5: orig: bp
    def:  bp_5 = fp - 2
wArg02:Stack +0002
    def:  def wArg02
    uses: ax_7 = wArg02
          dx_30 = wArg02
ax_7: orig: ax
    def:  ax_7 = wArg02
    uses: ax_8 = ax_7 - 0x0001
ax_8: orig: ax
    def:  ax_8 = ax_7 - 0x0001
    uses: dx_ax_10 = SEQ(dx, ax_8) (alias)
          SZO_11 = cond(ax_8)
          wLoc04_24 = ax_8
dx:dx
    def:  def dx
    uses: dx_ax_10 = SEQ(dx, ax_8) (alias)
          dx_ax_38 = SEQ(dx, ax_37) (alias)
          dx_17 = PHI((dx_33, l0C00_0018), (dx, l0C00_0026))
dx_ax_10: orig: dx_ax
    def:  dx_ax_10 = SEQ(dx, ax_8) (alias)
SZO_11: orig: SZO
    def:  SZO_11 = cond(ax_8)
    uses: Z_12 = (bool) SZO_11 (alias)
          SCZO_13 = SZO_11 (alias)
          SZO_19 = PHI((SZO_35, l0C00_0018), (SZO_11, l0C00_0026))
Z_12: orig: Z
    def:  Z_12 = (bool) SZO_11 (alias)
    uses: branch Test(EQ,Z_12) l0C00_0026
          Z_20 = PHI((Z_36, l0C00_0018), (Z_12, l0C00_0026))
SCZO_13: orig: SCZO
    def:  SCZO_13 = SZO_11 (alias)
    uses: SCZO_18 = PHI((SCZO_34, l0C00_0018), (SCZO_13, l0C00_0026))
wLoc04_14: orig: wLoc04
    def:  wLoc04_14 = PHI((wLoc04_24, l0C00_0018), (wLoc04, l0C00_0026))
dx_ax_15: orig: dx_ax
    def:  dx_ax_15 = PHI((dx_ax_31, l0C00_0018), (dx_ax_38, l0C00_0026))
ax_16: orig: ax
    def:  ax_16 = PHI((ax_32, l0C00_0018), (ax_37, l0C00_0026))
    uses: return ax_16
dx_17: orig: dx
    def:  dx_17 = PHI((dx_33, l0C00_0018), (dx, l0C00_0026))
SCZO_18: orig: SCZO
    def:  SCZO_18 = PHI((SCZO_34, l0C00_0018), (SCZO_13, l0C00_0026))
SZO_19: orig: SZO
    def:  SZO_19 = PHI((SZO_35, l0C00_0018), (SZO_11, l0C00_0026))
Z_20: orig: Z
    def:  Z_20 = PHI((Z_36, l0C00_0018), (Z_12, l0C00_0026))
bp_21: orig: bp
    def:  bp_21 = wLoc02_4
sp_22: orig: sp
    def:  sp_22 = fp
sp_23: orig: sp
    def:  sp_23 = fp - 4
wLoc04_24: orig: wLoc04
    def:  wLoc04_24 = ax_8
    uses: ax_25 = fn0C00_000F(wLoc04_24)
          wLoc04_14 = PHI((wLoc04_24, l0C00_0018), (wLoc04, l0C00_0026))
ax_25: orig: ax
    def:  ax_25 = fn0C00_000F(wLoc04_24)
    uses: dx_ax_31 = dx_30 *s ax_25
sp_26: orig: sp
    def:  sp_26 = fp - 0x0003
SZO_27: orig: SZO
    def:  SZO_27 = cond(fp - 0x0003)
sp_28: orig: sp
    def:  sp_28 = fp - 0x0002
SZO_29: orig: SZO
    def:  SZO_29 = cond(fp - 0x0002)
dx_30: orig: dx
    def:  dx_30 = wArg02
    uses: dx_ax_31 = dx_30 *s ax_25
dx_ax_31: orig: dx_ax
    def:  dx_ax_31 = dx_30 *s ax_25
    uses: ax_32 = (word16) dx_ax_31 (alias)
          dx_33 = SLICE(dx_ax_31, word16, 16) (alias)
          SCZO_34 = cond(dx_ax_31)
          dx_ax_15 = PHI((dx_ax_31, l0C00_0018), (dx_ax_38, l0C00_0026))
ax_32: orig: ax
    def:  ax_32 = (word16) dx_ax_31 (alias)
    uses: ax_16 = PHI((ax_32, l0C00_0018), (ax_37, l0C00_0026))
dx_33: orig: dx
    def:  dx_33 = SLICE(dx_ax_31, word16, 16) (alias)
    uses: dx_17 = PHI((dx_33, l0C00_0018), (dx, l0C00_0026))
SCZO_34: orig: SCZO
    def:  SCZO_34 = cond(dx_ax_31)
    uses: SZO_35 = SCZO_34 (alias)
          Z_36 = (bool) SCZO_34 (alias)
          SCZO_18 = PHI((SCZO_34, l0C00_0018), (SCZO_13, l0C00_0026))
SZO_35: orig: SZO
    def:  SZO_35 = SCZO_34 (alias)
    uses: SZO_19 = PHI((SZO_35, l0C00_0018), (SZO_11, l0C00_0026))
Z_36: orig: Z
    def:  Z_36 = (bool) SCZO_34 (alias)
    uses: Z_20 = PHI((Z_36, l0C00_0018), (Z_12, l0C00_0026))
ax_37: orig: ax
    def:  ax_37 = 0x0001
    uses: dx_ax_38 = SEQ(dx, ax_37) (alias)
          ax_16 = PHI((ax_32, l0C00_0018), (ax_37, l0C00_0026))
dx_ax_38: orig: dx_ax
    def:  dx_ax_38 = SEQ(dx, ax_37) (alias)
    uses: dx_ax_15 = PHI((dx_ax_31, l0C00_0018), (dx_ax_38, l0C00_0026))
wLoc04:Local -0004
    def:  def wLoc04
    uses: wLoc04_14 = PHI((wLoc04_24, l0C00_0018), (wLoc04, l0C00_0026))
// fn0C00_000F
// Return size: 0
word16 fn0C00_000F(word16 wArg02)
fn0C00_000F_entry:
	def fp
	def bp
	def wArg02
	def dx
	def wLoc04
	// succ:  l0C00_000F
l0C00_000F:
	sp_1 = fp
	sp_2 = fp - 2
	wLoc02_4 = bp
	bp_5 = fp - 2
	ax_7 = wArg02
	ax_8 = ax_7 - 0x0001
	dx_ax_10 = SEQ(dx, ax_8) (alias)
	SZO_11 = cond(ax_8)
	Z_12 = (bool) SZO_11 (alias)
	SCZO_13 = SZO_11 (alias)
	branch Test(EQ,Z_12) l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	sp_23 = fp - 4
	wLoc04_24 = ax_8
	ax_25 = fn0C00_000F(wLoc04_24)
	sp_26 = fp - 0x0003
	SZO_27 = cond(fp - 0x0003)
	sp_28 = fp - 0x0002
	SZO_29 = cond(fp - 0x0002)
	dx_30 = wArg02
	dx_ax_31 = dx_30 *s ax_25
	ax_32 = (word16) dx_ax_31 (alias)
	dx_33 = SLICE(dx_ax_31, word16, 16) (alias)
	SCZO_34 = cond(dx_ax_31)
	SZO_35 = SCZO_34 (alias)
	Z_36 = (bool) SCZO_34 (alias)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax_37 = 0x0001
	dx_ax_38 = SEQ(dx, ax_37) (alias)
	// succ:  l0C00_0029
l0C00_0029:
	wLoc04_14 = PHI((wLoc04_24, l0C00_0018), (wLoc04, l0C00_0026))
	dx_ax_15 = PHI((dx_ax_31, l0C00_0018), (dx_ax_38, l0C00_0026))
	ax_16 = PHI((ax_32, l0C00_0018), (ax_37, l0C00_0026))
	dx_17 = PHI((dx_33, l0C00_0018), (dx, l0C00_0026))
	SCZO_18 = PHI((SCZO_34, l0C00_0018), (SCZO_13, l0C00_0026))
	SZO_19 = PHI((SZO_35, l0C00_0018), (SZO_11, l0C00_0026))
	Z_20 = PHI((Z_36, l0C00_0018), (Z_12, l0C00_0026))
	bp_21 = wLoc02_4
	sp_22 = fp
	return ax_16
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:

