Mem0:Mem
    def:  def Mem0
    uses: al_2 = Mem0[0x1234:byte]
al_2: orig: al
    def:  al_2 = Mem0[0x1234:byte]
    uses: Mem4[0x1236:byte] = al_2 *u ah_3
ah_3: orig: ah
    def:  ah_3 = 0x03
    uses: Mem4[0x1236:byte] = al_2 *u ah_3
Mem4: orig: Mem0
    def:  Mem4[0x1236:byte] = al_2 *u ah_3
// SsaHiwordLoword
// Return size: 0
define SsaHiwordLoword
SsaHiwordLoword_entry:
	def Mem0
	// succ:  l1
l1:
	al_2 = Mem0[0x1234:byte]
	ah_3 = 0x03
	Mem4[0x1236:byte] = al_2 *u ah_3
	return
	// succ:  SsaHiwordLoword_exit
SsaHiwordLoword_exit:
