Mem0:Global memory
    def:  def Mem0
    uses: bx_9 = Mem0[ds:bx + 0x0004:word16]
          cx_10 = Mem0[ds:bx_9 + 0x0002:word16]
fp:Temporary
    def:  def fp
sp:Register sp
    def:  def sp
bx:Register bx
    def:  def bx
    uses: bx_9 = Mem0[ds:bx + 0x0004:word16]
ds:Register ds
    def:  def ds
    uses: bx_9 = Mem0[ds:bx + 0x0004:word16]
          cx_10 = Mem0[ds:bx_9 + 0x0002:word16]
          store(Mem15[ds:0x012C:word16]) = cx_13
          store(Mem16[ds:bx_9 + 0x0006:word16]) = 0x0000
          cx_17 = Mem16[ds:si:word16]
          store(Mem18[ds:bx_9 + 0x0006:word16]) = 0x0001
          cx_19 = Mem18[ds:si:word16]
cx:Register cx
    def:  def cx
SCZO:Flags
    def:  def SCZO
Z:Flags
    def:  def Z
si:Register si
    def:  def si
    uses: cx_17 = Mem16[ds:si:word16]
          cx_19 = Mem18[ds:si:word16]
bx_9: orig: bx
    def:  bx_9 = Mem0[ds:bx + 0x0004:word16]
    uses: cx_10 = Mem0[ds:bx_9 + 0x0002:word16]
          store(Mem16[ds:bx_9 + 0x0006:word16]) = 0x0000
          store(Mem18[ds:bx_9 + 0x0006:word16]) = 0x0001
cx_10: orig: cx
    def:  cx_10 = Mem0[ds:bx_9 + 0x0002:word16]
    uses: SCZO_11 = cond(cx_10 - 0x0000)
SCZO_11: orig: SCZO
    def:  SCZO_11 = cond(cx_10 - 0x0000)
    uses: Z_12 = SCZO_11 (alias)
Z_12: orig: Z
    def:  Z_12 = SCZO_11 (alias)
    uses: branch Test(NE,Z_12) l0C00_0015
cx_13: orig: cx
    def:  cx_13 = PHI(cx_17, cx_19)
    uses: store(Mem15[ds:0x012C:word16]) = cx_13
Mem14: orig: Mem0
    def:  Mem14 = PHI(Mem16, Mem18)
Mem15: orig: Mem0
    def:  store(Mem15[ds:0x012C:word16]) = cx_13
Mem16: orig: Mem0
    def:  store(Mem16[ds:bx_9 + 0x0006:word16]) = 0x0000
    uses: cx_17 = Mem16[ds:si:word16]
          Mem14 = PHI(Mem16, Mem18)
cx_17: orig: cx
    def:  cx_17 = Mem16[ds:si:word16]
    uses: cx_13 = PHI(cx_17, cx_19)
Mem18: orig: Mem0
    def:  store(Mem18[ds:bx_9 + 0x0006:word16]) = 0x0001
    uses: cx_19 = Mem18[ds:si:word16]
          Mem14 = PHI(Mem16, Mem18)
cx_19: orig: cx
    def:  cx_19 = Mem18[ds:si:word16]
    uses: cx_13 = PHI(cx_17, cx_19)
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
	def Mem0
	def fp
	def sp
	def bx
	def ds
	def cx
	def SCZO
	def Z
	def si
	// succ:  l0C00_0000
l0C00_0000:
	bx_9 = Mem0[ds:bx + 0x0004:word16]
	cx_10 = Mem0[ds:bx_9 + 0x0002:word16]
	SCZO_11 = cond(cx_10 - 0x0000)
	Z_12 = SCZO_11 (alias)
	branch Test(NE,Z_12) l0C00_0015
	// succ:  l0C00_000B l0C00_0015
l0C00_000B:
	store(Mem16[ds:bx_9 + 0x0006:word16]) = 0x0000
	cx_17 = Mem16[ds:si:word16]
	goto l0C00_001C
	// succ:  l0C00_001C
l0C00_0015:
	store(Mem18[ds:bx_9 + 0x0006:word16]) = 0x0001
	cx_19 = Mem18[ds:si:word16]
	// succ:  l0C00_001C
l0C00_001C:
	cx_13 = PHI(cx_17, cx_19)
	Mem14 = PHI(Mem16, Mem18)
	store(Mem15[ds:0x012C:word16]) = cx_13
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

