fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
    uses: use sp_2
Top_3: orig: Top
    def:  Top_3 = 0
    uses: use Top_3
eax:eax
    def:  def eax
    uses: eax_5 = -eax
eax_5: orig: eax
    def:  eax_5 = -eax
    uses: SCZO_6 = cond(eax_5)
          C_7 = eax_5 == 0x00000000
          eax_8 = eax_5 - eax_5 - C_7
          eax_8 = eax_5 - eax_5 - C_7
SCZO_6: orig: SCZO
    def:  SCZO_6 = cond(eax_5)
C_7: orig: C
    def:  C_7 = eax_5 == 0x00000000
    uses: eax_8 = eax_5 - eax_5 - C_7
eax_8: orig: eax
    def:  eax_8 = eax_5 - eax_5 - C_7
    uses: SCZO_9 = cond(eax_8)
          Mem11[ds:0x0300:word32] = eax_8
          use eax_8
SCZO_9: orig: SCZO
    def:  SCZO_9 = cond(eax_8)
ds:ds
    def:  def ds
    uses: Mem11[ds:0x0300:word32] = eax_8
          v7_12 = -Mem11[ds:0x0202:word16]
          Mem13[ds:0x0202:word16] = v7_12
          v8_16 = -Mem13[ds:0x0200:word16]
          Mem17[ds:0x0200:word16] = v8_16
          Mem23[ds:0x0308:word32] = ecx_21
          Mem26[ds:0x0304:word16] = bx_25
          v11_27 = ~Mem26[ds:0x0204:word16]
          Mem28[ds:0x0204:word16] = v11_27
          cx_29 = Mem28[ds:0x0304:word16]
          Mem35[ds:0x0306:word16] = cx_32
Mem11: orig: Mem0
    def:  Mem11[ds:0x0300:word32] = eax_8
    uses: v7_12 = -Mem11[ds:0x0202:word16]
v7_12: orig: v7
    def:  v7_12 = -Mem11[ds:0x0202:word16]
    uses: Mem13[ds:0x0202:word16] = v7_12
          SCZO_14 = cond(v7_12)
          C_15 = v7_12 == 0x0000
Mem13: orig: Mem0
    def:  Mem13[ds:0x0202:word16] = v7_12
    uses: v8_16 = -Mem13[ds:0x0200:word16]
SCZO_14: orig: SCZO
    def:  SCZO_14 = cond(v7_12)
C_15: orig: C
    def:  C_15 = v7_12 == 0x0000
v8_16: orig: v8
    def:  v8_16 = -Mem13[ds:0x0200:word16]
    uses: Mem17[ds:0x0200:word16] = v8_16
          SCZO_18 = cond(v8_16)
          C_19 = v8_16 == 0x0000
Mem17: orig: Mem0
    def:  Mem17[ds:0x0200:word16] = v8_16
SCZO_18: orig: SCZO
    def:  SCZO_18 = cond(v8_16)
C_19: orig: C
    def:  C_19 = v8_16 == 0x0000
    uses: ecx_21 = ecx - ecx - C_19
ecx:ecx
    def:  def ecx
    uses: ecx_21 = ecx - ecx - C_19
          ecx_21 = ecx - ecx - C_19
          ecx_36 = DPB(ecx, cx_32, 0) (alias)
ecx_21: orig: ecx
    def:  ecx_21 = ecx - ecx - C_19
    uses: SCZO_22 = cond(ecx_21)
          Mem23[ds:0x0308:word32] = ecx_21
SCZO_22: orig: SCZO
    def:  SCZO_22 = cond(ecx_21)
Mem23: orig: Mem0
    def:  Mem23[ds:0x0308:word32] = ecx_21
bx:bx
    def:  def bx
    uses: bx_25 = ~bx
bx_25: orig: bx
    def:  bx_25 = ~bx
    uses: Mem26[ds:0x0304:word16] = bx_25
          use bx_25
Mem26: orig: Mem0
    def:  Mem26[ds:0x0304:word16] = bx_25
    uses: v11_27 = ~Mem26[ds:0x0204:word16]
v11_27: orig: v11
    def:  v11_27 = ~Mem26[ds:0x0204:word16]
    uses: Mem28[ds:0x0204:word16] = v11_27
Mem28: orig: Mem0
    def:  Mem28[ds:0x0204:word16] = v11_27
    uses: cx_29 = Mem28[ds:0x0304:word16]
cx_29: orig: cx
    def:  cx_29 = Mem28[ds:0x0304:word16]
    uses: cx_30 = cx_29 - 0x03E8
cx_30: orig: cx
    def:  cx_30 = cx_29 - 0x03E8
    uses: SCZO_31 = cond(cx_30)
          cx_32 = -cx_30
SCZO_31: orig: SCZO
    def:  SCZO_31 = cond(cx_30)
cx_32: orig: cx
    def:  cx_32 = -cx_30
    uses: SCZO_33 = cond(cx_32)
          C_34 = cx_32 == 0x0000
          Mem35[ds:0x0306:word16] = cx_32
          ecx_36 = DPB(ecx, cx_32, 0) (alias)
SCZO_33: orig: SCZO
    def:  SCZO_33 = cond(cx_32)
    uses: O_37 = SLICE(SCZO_33, bool, 4) (alias)
          S_38 = SLICE(SCZO_33, bool, 0) (alias)
          Z_39 = SLICE(SCZO_33, bool, 2) (alias)
C_34: orig: C
    def:  C_34 = cx_32 == 0x0000
    uses: use C_34
Mem35: orig: Mem0
    def:  Mem35[ds:0x0306:word16] = cx_32
ecx_36: orig: ecx
    def:  ecx_36 = DPB(ecx, cx_32, 0) (alias)
    uses: use ecx_36
O_37: orig: O
    def:  O_37 = SLICE(SCZO_33, bool, 4) (alias)
    uses: use O_37
S_38: orig: S
    def:  S_38 = SLICE(SCZO_33, bool, 0) (alias)
    uses: use S_38
Z_39: orig: Z
    def:  Z_39 = SLICE(SCZO_33, bool, 2) (alias)
    uses: use Z_39
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def bx
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	Top_3 = 0
	eax_5 = -eax
	SCZO_6 = cond(eax_5)
	C_7 = eax_5 == 0x00000000
	eax_8 = eax_5 - eax_5 - C_7
	SCZO_9 = cond(eax_8)
	Mem11[ds:0x0300:word32] = eax_8
	v7_12 = -Mem11[ds:0x0202:word16]
	Mem13[ds:0x0202:word16] = v7_12
	SCZO_14 = cond(v7_12)
	C_15 = v7_12 == 0x0000
	v8_16 = -Mem13[ds:0x0200:word16]
	Mem17[ds:0x0200:word16] = v8_16
	SCZO_18 = cond(v8_16)
	C_19 = v8_16 == 0x0000
	ecx_21 = ecx - ecx - C_19
	SCZO_22 = cond(ecx_21)
	Mem23[ds:0x0308:word32] = ecx_21
	bx_25 = ~bx
	Mem26[ds:0x0304:word16] = bx_25
	v11_27 = ~Mem26[ds:0x0204:word16]
	Mem28[ds:0x0204:word16] = v11_27
	cx_29 = Mem28[ds:0x0304:word16]
	cx_30 = cx_29 - 0x03E8
	SCZO_31 = cond(cx_30)
	cx_32 = -cx_30
	ecx_36 = DPB(ecx, cx_32, 0) (alias)
	SCZO_33 = cond(cx_32)
	O_37 = SLICE(SCZO_33, bool, 4) (alias)
	S_38 = SLICE(SCZO_33, bool, 0) (alias)
	Z_39 = SLICE(SCZO_33, bool, 2) (alias)
	C_34 = cx_32 == 0x0000
	Mem35[ds:0x0306:word16] = cx_32
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	use bx_25
	use C_34
	use eax_8
	use ecx_36
	use O_37
	use S_38
	use sp_2
	use Top_3
	use Z_39

