fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
    uses: use sp_2
Top_3: orig: Top
    def:  Top_3 = 0<i8>
    uses: use Top_3
eax:eax
    def:  def eax
    uses: eax_5 = -eax
eax_5: orig: eax
    def:  eax_5 = -eax
    uses: SCZO_6 = cond(eax_5)
          C_7 = eax_5 == 0<32>
SCZO_6: orig: SCZO
    def:  SCZO_6 = cond(eax_5)
C_7: orig: C
    def:  C_7 = eax_5 == 0<32>
    uses: eax_8 = 0<32> - C_7
eax_8: orig: eax
    def:  eax_8 = 0<32> - C_7
    uses: SCZO_9 = cond(eax_8)
          Mem11[ds:0x300<16>:word32] = eax_8
          use eax_8
SCZO_9: orig: SCZO
    def:  SCZO_9 = cond(eax_8)
ds:ds
    def:  def ds
    uses: Mem11[ds:0x300<16>:word32] = eax_8
          v7_12 = -Mem11[ds:0x202<16>:word16]
          Mem13[ds:0x202<16>:word16] = v7_12
          v8_16 = -Mem13[ds:0x200<16>:word16]
          Mem17[ds:0x200<16>:word16] = v8_16
          Mem22[ds:0x308<16>:word32] = ecx_20
          Mem25[ds:0x304<16>:word16] = bx_24
          v11_26 = ~Mem25[ds:0x204<16>:word16]
          Mem27[ds:0x204<16>:word16] = v11_26
          cx_28 = Mem27[ds:0x304<16>:word16]
          Mem34[ds:0x306<16>:word16] = cx_31
Mem11: orig: Mem0
    def:  Mem11[ds:0x300<16>:word32] = eax_8
    uses: v7_12 = -Mem11[ds:0x202<16>:word16]
v7_12: orig: v7
    def:  v7_12 = -Mem11[ds:0x202<16>:word16]
    uses: Mem13[ds:0x202<16>:word16] = v7_12
          SCZO_14 = cond(v7_12)
          C_15 = v7_12 == 0<16>
Mem13: orig: Mem0
    def:  Mem13[ds:0x202<16>:word16] = v7_12
    uses: v8_16 = -Mem13[ds:0x200<16>:word16]
SCZO_14: orig: SCZO
    def:  SCZO_14 = cond(v7_12)
C_15: orig: C
    def:  C_15 = v7_12 == 0<16>
v8_16: orig: v8
    def:  v8_16 = -Mem13[ds:0x200<16>:word16]
    uses: Mem17[ds:0x200<16>:word16] = v8_16
          SCZO_18 = cond(v8_16)
          C_19 = v8_16 == 0<16>
Mem17: orig: Mem0
    def:  Mem17[ds:0x200<16>:word16] = v8_16
SCZO_18: orig: SCZO
    def:  SCZO_18 = cond(v8_16)
C_19: orig: C
    def:  C_19 = v8_16 == 0<16>
    uses: ecx_20 = 0<32> - C_19
ecx_20: orig: ecx
    def:  ecx_20 = 0<32> - C_19
    uses: SCZO_21 = cond(ecx_20)
          Mem22[ds:0x308<16>:word32] = ecx_20
          ecx_16_16_35 = SLICE(ecx_20, word16, 16) (alias)
SCZO_21: orig: SCZO
    def:  SCZO_21 = cond(ecx_20)
Mem22: orig: Mem0
    def:  Mem22[ds:0x308<16>:word32] = ecx_20
bx:bx
    def:  def bx
    uses: bx_24 = ~bx
bx_24: orig: bx
    def:  bx_24 = ~bx
    uses: Mem25[ds:0x304<16>:word16] = bx_24
          use bx_24
Mem25: orig: Mem0
    def:  Mem25[ds:0x304<16>:word16] = bx_24
    uses: v11_26 = ~Mem25[ds:0x204<16>:word16]
v11_26: orig: v11
    def:  v11_26 = ~Mem25[ds:0x204<16>:word16]
    uses: Mem27[ds:0x204<16>:word16] = v11_26
Mem27: orig: Mem0
    def:  Mem27[ds:0x204<16>:word16] = v11_26
    uses: cx_28 = Mem27[ds:0x304<16>:word16]
cx_28: orig: cx
    def:  cx_28 = Mem27[ds:0x304<16>:word16]
    uses: cx_29 = cx_28 - 0x3E8<16>
cx_29: orig: cx
    def:  cx_29 = cx_28 - 0x3E8<16>
    uses: SCZO_30 = cond(cx_29)
          cx_31 = -cx_29
SCZO_30: orig: SCZO
    def:  SCZO_30 = cond(cx_29)
cx_31: orig: cx
    def:  cx_31 = -cx_29
    uses: SCZO_32 = cond(cx_31)
          C_33 = cx_31 == 0<16>
          Mem34[ds:0x306<16>:word16] = cx_31
          ecx_36 = SEQ(ecx_16_16_35, cx_31) (alias)
SCZO_32: orig: SCZO
    def:  SCZO_32 = cond(cx_31)
    uses: O_37 = SLICE(SCZO_32, bool, 4) (alias)
          S_38 = SLICE(SCZO_32, bool, 0) (alias)
          Z_39 = SLICE(SCZO_32, bool, 2) (alias)
C_33: orig: C
    def:  C_33 = cx_31 == 0<16>
    uses: use C_33
Mem34: orig: Mem0
    def:  Mem34[ds:0x306<16>:word16] = cx_31
ecx_16_16_35: orig: ecx_16_16
    def:  ecx_16_16_35 = SLICE(ecx_20, word16, 16) (alias)
    uses: ecx_36 = SEQ(ecx_16_16_35, cx_31) (alias)
ecx_36: orig: ecx
    def:  ecx_36 = SEQ(ecx_16_16_35, cx_31) (alias)
    uses: use ecx_36
O_37: orig: O
    def:  O_37 = SLICE(SCZO_32, bool, 4) (alias)
    uses: use O_37
S_38: orig: S
    def:  S_38 = SLICE(SCZO_32, bool, 0) (alias)
    uses: use S_38
Z_39: orig: Z
    def:  Z_39 = SLICE(SCZO_32, bool, 2) (alias)
    uses: use Z_39
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def bx
	sp_2 = fp
	Top_3 = 0<i8>
	// succ:  l0C00_0000
l0C00_0000:
	eax_5 = -eax
	SCZO_6 = cond(eax_5)
	C_7 = eax_5 == 0<32>
	eax_8 = 0<32> - C_7
	SCZO_9 = cond(eax_8)
	Mem11[ds:0x300<16>:word32] = eax_8
	v7_12 = -Mem11[ds:0x202<16>:word16]
	Mem13[ds:0x202<16>:word16] = v7_12
	SCZO_14 = cond(v7_12)
	C_15 = v7_12 == 0<16>
	v8_16 = -Mem13[ds:0x200<16>:word16]
	Mem17[ds:0x200<16>:word16] = v8_16
	SCZO_18 = cond(v8_16)
	C_19 = v8_16 == 0<16>
	ecx_20 = 0<32> - C_19
	ecx_16_16_35 = SLICE(ecx_20, word16, 16) (alias)
	SCZO_21 = cond(ecx_20)
	Mem22[ds:0x308<16>:word32] = ecx_20
	bx_24 = ~bx
	Mem25[ds:0x304<16>:word16] = bx_24
	v11_26 = ~Mem25[ds:0x204<16>:word16]
	Mem27[ds:0x204<16>:word16] = v11_26
	cx_28 = Mem27[ds:0x304<16>:word16]
	cx_29 = cx_28 - 0x3E8<16>
	SCZO_30 = cond(cx_29)
	cx_31 = -cx_29
	SCZO_32 = cond(cx_31)
	O_37 = SLICE(SCZO_32, bool, 4) (alias)
	S_38 = SLICE(SCZO_32, bool, 0) (alias)
	Z_39 = SLICE(SCZO_32, bool, 2) (alias)
	C_33 = cx_31 == 0<16>
	Mem34[ds:0x306<16>:word16] = cx_31
	ecx_36 = SEQ(ecx_16_16_35, cx_31) (alias)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	use bx_24
	use C_33
	use eax_8
	use ecx_36
	use O_37
	use S_38
	use sp_2
	use Top_3
	use Z_39

