fp:fp
    def:  def fp
    uses: esp_1 = fp
          esp_6 = fp - 0x00000004
          esp_12 = fp - 0x00000008
          esp_61 = fp - 0x00000004
          esp_63 = fp
          esp_66 = fp - 0x0000000C
          esp_69 = fp - 0x00000010
          esp_143 = fp - 0x0000000C
          esp_145 = fp - 0x00000008
esp_1: orig: esp
    def:  esp_1 = fp
dwArg04:Stack +0004
    def:  def dwArg04
    uses: eax_3 = dwArg04
          dwArg04_45 = PHI(dwArg04, dwArg04_100, dwArg04_100)
eax_3: orig: eax
    def:  eax_3 = dwArg04
    uses: ecx_15 = (int32) Mem0[eax_3 + 0x00000006:word16]
          edx_16 = (int32) Mem0[eax_3 + 0x00000002:word16]
          ecx_24 = (int32) Mem23[eax_3 + 0x00000004:word16]
          eax_25 = (int32) Mem23[eax_3:word16]
ebx:ebx
    def:  def ebx
    uses: v5_5 = ebx
v5_5: orig: v5
    def:  v5_5 = ebx
    uses: dwLoc04_7 = v5_5
esp_6: orig: esp
    def:  esp_6 = fp - 0x00000004
dwLoc04_7: orig: dwLoc04
    def:  dwLoc04_7 = v5_5
    uses: ebx_62 = dwLoc04_7
dwArg0C:Stack +000C
    def:  def dwArg0C
    uses: ebx_9 = dwArg0C
ebx_9: orig: ebx
    def:  ebx_9 = dwArg0C
    uses: Mem23[ebx_9:word32] = ecx_19
          rLoc1_64 = (real64) Mem34[ebx_9:int32]
          Mem134[ebx_9:word32] = eax_133
          Mem147[ebx_9:word32] = 0x00000000
ebp:ebp
    def:  def ebp
    uses: v7_11 = ebp
v7_11: orig: v7
    def:  v7_11 = ebp
    uses: dwLoc08_13 = v7_11
esp_12: orig: esp
    def:  esp_12 = fp - 0x00000008
dwLoc08_13: orig: dwLoc08
    def:  dwLoc08_13 = v7_11
    uses: ebp_60 = dwLoc08_13
Mem0:Global memory
    def:  def Mem0
    uses: ecx_15 = (int32) Mem0[eax_3 + 0x00000006:word16]
          edx_16 = (int32) Mem0[eax_3 + 0x00000002:word16]
ecx_15: orig: ecx
    def:  ecx_15 = (int32) Mem0[eax_3 + 0x00000006:word16]
    uses: ecx_19 = ecx_15 - edx_16
edx_16: orig: edx
    def:  edx_16 = (int32) Mem0[eax_3 + 0x00000002:word16]
    uses: ecx_19 = ecx_15 - edx_16
dwArg08:Stack +0008
    def:  def dwArg08
    uses: ebp_18 = dwArg08
ebp_18: orig: ebp
    def:  ebp_18 = dwArg08
    uses: SZO_28 = cond(ebp_18 & ebp_18)
          SZO_28 = cond(ebp_18 & ebp_18)
          SCZO_127 = cond(esi_87 - ebp_18)
          SCZO_137 = cond(ebp_18 - edi_126)
ecx_19: orig: ecx
    def:  ecx_19 = ecx_15 - edx_16
    uses: SCZO_20 = cond(ecx_19)
          Mem23[ebx_9:word32] = ecx_19
SCZO_20: orig: SCZO
    def:  SCZO_20 = cond(ecx_19)
dwArg10:Stack +0010
    def:  def dwArg10
    uses: edx_22 = dwArg10
          ecx_136 = dwArg10
edx_22: orig: edx
    def:  edx_22 = dwArg10
    uses: Mem34[edx_22:word32] = ecx_26
Mem23: orig: Mem0
    def:  Mem23[ebx_9:word32] = ecx_19
    uses: ecx_24 = (int32) Mem23[eax_3 + 0x00000004:word16]
          eax_25 = (int32) Mem23[eax_3:word16]
ecx_24: orig: ecx
    def:  ecx_24 = (int32) Mem23[eax_3 + 0x00000004:word16]
    uses: ecx_26 = ecx_24 - eax_25
eax_25: orig: eax
    def:  eax_25 = (int32) Mem23[eax_3:word16]
    uses: ecx_26 = ecx_24 - eax_25
          eax_51 = PHI(eax_25, eax_135, eax_135)
ecx_26: orig: ecx
    def:  ecx_26 = ecx_24 - eax_25
    uses: SCZO_27 = cond(ecx_26)
          dwArg0C_33 = ecx_26
          Mem34[edx_22:word32] = ecx_26
          ecx_52 = PHI(ecx_26, ecx_136, ecx_136)
SCZO_27: orig: SCZO
    def:  SCZO_27 = cond(ecx_26)
SZO_28: orig: SZO
    def:  SZO_28 = cond(ebp_18 & ebp_18)
    uses: Z_29 = SZO_28 (alias)
          SO_30 = SZO_28 (alias)
          SZO_54 = PHI(SZO_28, SZO_138, SZO_138)
Z_29: orig: Z
    def:  Z_29 = SZO_28 (alias)
    uses: branch Test(EQ,Z_29) l10000107
          Z_55 = PHI(Z_29, Z_139, Z_139)
SO_30: orig: SO
    def:  SO_30 = SZO_28 (alias)
    uses: SO_56 = PHI(SO_30, SO_140, SO_140)
C_31: orig: C
    def:  C_31 = false
    uses: SCZO_32 = C_31 (alias)
          C_57 = PHI(C_31, C_141, C_141)
SCZO_32: orig: SCZO
    def:  SCZO_32 = C_31 (alias)
    uses: SCZO_53 = PHI(SCZO_32, SCZO_137, SCZO_137)
dwArg0C_33: orig: dwArg0C
    def:  dwArg0C_33 = ecx_26
    uses: dwArg0C_47 = PHI(dwArg0C_33, dwArg0C_115, dwArg0C_115)
          rLoc1_79 = (real64) dwArg0C_33
Mem34: orig: Mem0
    def:  Mem34[edx_22:word32] = ecx_26
    uses: rLoc1_64 = (real64) Mem34[ebx_9:int32]
          rLoc2_86 = rLoc2_85 * Mem34[0x0099188A:real64]
          rLoc1_102 = rLoc1_82 * Mem34[0x10033290:real64]
          FPUF_119 = cond(rLoc2_118 - Mem34[0x10033298:real64])
          FPUF_149 = cond(rLoc1_116 - Mem34[0x10033298:real64])
dwLoc0C:Local -000C
    def:  def dwLoc0C
    uses: dwLoc0C_43 = PHI(dwLoc0C, dwLoc0C_67, dwLoc0C_67)
dwLoc10:Local -0010
    def:  def dwLoc10
    uses: dwLoc10_44 = PHI(dwLoc10, dwLoc10_70, dwLoc10_70)
rLoc3:FPU stack
    def:  def rLoc3
    uses: rLoc3_46 = PHI(rLoc3, rLoc3_108, rLoc3_108)
          rLoc3_81 = PHI(rLoc3, rLoc3_108)
rLoc1:FPU stack
    def:  def rLoc1
    uses: rLoc1_48 = PHI(rLoc1, rLoc1_116, rLoc1_116)
FPUF:Flags
    def:  def FPUF
    uses: FPUF_49 = PHI(FPUF, FPUF_125, FPUF_125)
rLoc2:FPU stack
    def:  def rLoc2
    uses: rLoc2_50 = PHI(rLoc2, rLoc2_132, rLoc2_132)
edi:edi
    def:  def edi
    uses: edi_58 = PHI(edi, edi_142, edi_142)
          v18_68 = edi
esi:esi
    def:  def esi
    uses: esi_59 = PHI(esi, esi_144, esi_144)
          v16_65 = esi
dwLoc0C_43: orig: dwLoc0C
    def:  dwLoc0C_43 = PHI(dwLoc0C, dwLoc0C_67, dwLoc0C_67)
dwLoc10_44: orig: dwLoc10
    def:  dwLoc10_44 = PHI(dwLoc10, dwLoc10_70, dwLoc10_70)
dwArg04_45: orig: dwArg04
    def:  dwArg04_45 = PHI(dwArg04, dwArg04_100, dwArg04_100)
rLoc3_46: orig: rLoc3
    def:  rLoc3_46 = PHI(rLoc3, rLoc3_108, rLoc3_108)
dwArg0C_47: orig: dwArg0C
    def:  dwArg0C_47 = PHI(dwArg0C_33, dwArg0C_115, dwArg0C_115)
rLoc1_48: orig: rLoc1
    def:  rLoc1_48 = PHI(rLoc1, rLoc1_116, rLoc1_116)
FPUF_49: orig: FPUF
    def:  FPUF_49 = PHI(FPUF, FPUF_125, FPUF_125)
rLoc2_50: orig: rLoc2
    def:  rLoc2_50 = PHI(rLoc2, rLoc2_132, rLoc2_132)
eax_51: orig: eax
    def:  eax_51 = PHI(eax_25, eax_135, eax_135)
ecx_52: orig: ecx
    def:  ecx_52 = PHI(ecx_26, ecx_136, ecx_136)
SCZO_53: orig: SCZO
    def:  SCZO_53 = PHI(SCZO_32, SCZO_137, SCZO_137)
SZO_54: orig: SZO
    def:  SZO_54 = PHI(SZO_28, SZO_138, SZO_138)
Z_55: orig: Z
    def:  Z_55 = PHI(Z_29, Z_139, Z_139)
SO_56: orig: SO
    def:  SO_56 = PHI(SO_30, SO_140, SO_140)
C_57: orig: C
    def:  C_57 = PHI(C_31, C_141, C_141)
edi_58: orig: edi
    def:  edi_58 = PHI(edi, edi_142, edi_142)
esi_59: orig: esi
    def:  esi_59 = PHI(esi, esi_144, esi_144)
ebp_60: orig: ebp
    def:  ebp_60 = dwLoc08_13
esp_61: orig: esp
    def:  esp_61 = fp - 0x00000004
ebx_62: orig: ebx
    def:  ebx_62 = dwLoc04_7
esp_63: orig: esp
    def:  esp_63 = fp
rLoc1_64: orig: rLoc1
    def:  rLoc1_64 = (real64) Mem34[ebx_9:int32]
    uses: dwArg04_78 = (real32) rLoc1_64
v16_65: orig: v16
    def:  v16_65 = esi
    uses: dwLoc0C_67 = v16_65
esp_66: orig: esp
    def:  esp_66 = fp - 0x0000000C
dwLoc0C_67: orig: dwLoc0C
    def:  dwLoc0C_67 = v16_65
    uses: esi_144 = dwLoc0C_67
          dwLoc0C_43 = PHI(dwLoc0C, dwLoc0C_67, dwLoc0C_67)
          dwLoc0C_43 = PHI(dwLoc0C, dwLoc0C_67, dwLoc0C_67)
v18_68: orig: v18
    def:  v18_68 = edi
    uses: dwLoc10_70 = v18_68
esp_69: orig: esp
    def:  esp_69 = fp - 0x00000010
dwLoc10_70: orig: dwLoc10
    def:  dwLoc10_70 = v18_68
    uses: edi_142 = dwLoc10_70
          dwLoc10_44 = PHI(dwLoc10, dwLoc10_70, dwLoc10_70)
          dwLoc10_44 = PHI(dwLoc10, dwLoc10_70, dwLoc10_70)
esi_71: orig: esi
    def:  esi_71 = 0x00000000
    uses: esi_84 = PHI(esi_71, esi_87)
SZO_72: orig: SZO
    def:  SZO_72 = cond(0x00000000)
    uses: Z_73 = SZO_72 (alias)
          SO_74 = SZO_72 (alias)
Z_73: orig: Z
    def:  Z_73 = SZO_72 (alias)
SO_74: orig: SO
    def:  SO_74 = SZO_72 (alias)
C_75: orig: C
    def:  C_75 = false
    uses: SCZO_76 = C_75 (alias)
SCZO_76: orig: SCZO
    def:  SCZO_76 = C_75 (alias)
edi_77: orig: edi
    def:  edi_77 = 0x000186A0
    uses: edi_83 = PHI(edi_77, edi_126)
dwArg04_78: orig: dwArg04
    def:  dwArg04_78 = (real32) rLoc1_64
    uses: dwArg04_80 = PHI(dwArg04_78, dwArg04_100)
rLoc1_79: orig: rLoc1
    def:  rLoc1_79 = (real64) dwArg0C_33
    uses: rLoc1_82 = PHI(rLoc1_79, rLoc1_116)
dwArg04_80: orig: dwArg04
    def:  dwArg04_80 = PHI(dwArg04_78, dwArg04_100)
    uses: rLoc2_85 = (real64) dwArg04_80
rLoc3_81: orig: rLoc3
    def:  rLoc3_81 = PHI(rLoc3, rLoc3_108)
rLoc1_82: orig: rLoc1
    def:  rLoc1_82 = PHI(rLoc1_79, rLoc1_116)
    uses: rLoc1_102 = rLoc1_82 * Mem34[0x10033290:real64]
edi_83: orig: edi
    def:  edi_83 = PHI(edi_77, edi_126)
    uses: edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
          edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
          SCZO_155 = cond(edi_83 - 0x000186A0)
          edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
esi_84: orig: esi
    def:  esi_84 = PHI(esi_71, esi_87)
    uses: esi_87 = esi_84 + 0x00000001
rLoc2_85: orig: rLoc2
    def:  rLoc2_85 = (real64) dwArg04_80
    uses: rLoc2_86 = rLoc2_85 * Mem34[0x0099188A:real64]
rLoc2_86: orig: rLoc2
    def:  rLoc2_86 = rLoc2_85 * Mem34[0x0099188A:real64]
    uses: dwArg04_89 = (real32) rLoc2_86
          eax_90 = fn1000010A(rLoc2_86)
esi_87: orig: esi
    def:  esi_87 = esi_84 + 0x00000001
    uses: SZO_88 = cond(esi_87)
          SCZO_127 = cond(esi_87 - ebp_18)
          esi_84 = PHI(esi_71, esi_87)
          edi_160 = esi_87
SZO_88: orig: SZO
    def:  SZO_88 = cond(esi_87)
dwArg04_89: orig: dwArg04
    def:  dwArg04_89 = (real32) rLoc2_86
    uses: FPUF_94 = cond(rLoc2_93 - dwArg04_89)
          dwArg04_100 = PHI(dwArg04_176, dwArg04_89)
eax_90: orig: eax
    def:  eax_90 = fn1000010A(rLoc2_86)
    uses: ecx_91 = eax_90
ecx_91: orig: ecx
    def:  ecx_91 = eax_90
    uses: dwArg0C_92 = ecx_91
          ecx_169 = ecx_91 + 0x00000001
dwArg0C_92: orig: dwArg0C
    def:  dwArg0C_92 = ecx_91
    uses: rLoc2_93 = (real64) dwArg0C_92
rLoc2_93: orig: rLoc2
    def:  rLoc2_93 = (real64) dwArg0C_92
    uses: FPUF_94 = cond(rLoc2_93 - dwArg04_89)
          rLoc2_101 = PHI(rLoc2_175, rLoc2_93)
FPUF_94: orig: FPUF
    def:  FPUF_94 = cond(rLoc2_93 - dwArg04_89)
    uses: SCZO_95 = FPUF_94
          branch Test(EQ,FPUF_94) l1000007F
SCZO_95: orig: SCZO
    def:  SCZO_95 = FPUF_94
    uses: SZO_96 = SCZO_95 (alias)
          Z_97 = SCZO_95 (alias)
          SO_98 = SCZO_95 (alias)
          C_99 = SCZO_95 (alias)
SZO_96: orig: SZO
    def:  SZO_96 = SCZO_95 (alias)
Z_97: orig: Z
    def:  Z_97 = SCZO_95 (alias)
SO_98: orig: SO
    def:  SO_98 = SCZO_95 (alias)
C_99: orig: C
    def:  C_99 = SCZO_95 (alias)
dwArg04_100: orig: dwArg04
    def:  dwArg04_100 = PHI(dwArg04_176, dwArg04_89)
    uses: rLoc2_118 = (real64) dwArg04_100
          dwArg04_80 = PHI(dwArg04_78, dwArg04_100)
          rLoc2_132 = (real64) dwArg04_100
          dwArg04_45 = PHI(dwArg04, dwArg04_100, dwArg04_100)
          dwArg04_45 = PHI(dwArg04, dwArg04_100, dwArg04_100)
rLoc2_101: orig: rLoc2
    def:  rLoc2_101 = PHI(rLoc2_175, rLoc2_93)
    uses: rLoc2_103 = rLoc2_101
rLoc1_102: orig: rLoc1
    def:  rLoc1_102 = rLoc1_82 * Mem34[0x10033290:real64]
    uses: rLoc1_116 = PHI(rLoc1_102, rLoc1_168)
          rLoc1_166 = rLoc1_102
rLoc2_103: orig: rLoc2
    def:  rLoc2_103 = rLoc2_101
    uses: eax_104 = fn1000010A(rLoc2_103)
eax_104: orig: eax
    def:  eax_104 = fn1000010A(rLoc2_103)
    uses: ecx_105 = eax_104
ecx_105: orig: ecx
    def:  ecx_105 = eax_104
    uses: dwArg0C_106 = ecx_105
          ecx_117 = PHI(ecx_105, ecx_161)
          ecx_161 = ecx_105 + 0x00000001
dwArg0C_106: orig: dwArg0C
    def:  dwArg0C_106 = ecx_105
    uses: rLoc2_107 = (real64) dwArg0C_106
          dwArg0C_115 = PHI(dwArg0C_106, dwArg0C_167)
rLoc2_107: orig: rLoc2
    def:  rLoc2_107 = (real64) dwArg0C_106
    uses: rLoc3_108 = rLoc2_107
          FPUF_109 = cond(rLoc3_108 - rLoc2_107)
rLoc3_108: orig: rLoc3
    def:  rLoc3_108 = rLoc2_107
    uses: FPUF_109 = cond(rLoc3_108 - rLoc2_107)
          rLoc3_81 = PHI(rLoc3, rLoc3_108)
          rLoc3_46 = PHI(rLoc3, rLoc3_108, rLoc3_108)
          rLoc3_46 = PHI(rLoc3, rLoc3_108, rLoc3_108)
FPUF_109: orig: FPUF
    def:  FPUF_109 = cond(rLoc3_108 - rLoc2_107)
    uses: SCZO_110 = FPUF_109
          branch Test(EQ,FPUF_109) l100000AD
SCZO_110: orig: SCZO
    def:  SCZO_110 = FPUF_109
    uses: SZO_111 = SCZO_110 (alias)
          Z_112 = SCZO_110 (alias)
          SO_113 = SCZO_110 (alias)
          C_114 = SCZO_110 (alias)
SZO_111: orig: SZO
    def:  SZO_111 = SCZO_110 (alias)
Z_112: orig: Z
    def:  Z_112 = SCZO_110 (alias)
SO_113: orig: SO
    def:  SO_113 = SCZO_110 (alias)
C_114: orig: C
    def:  C_114 = SCZO_110 (alias)
dwArg0C_115: orig: dwArg0C
    def:  dwArg0C_115 = PHI(dwArg0C_106, dwArg0C_167)
    uses: dwArg0C_47 = PHI(dwArg0C_33, dwArg0C_115, dwArg0C_115)
          dwArg0C_47 = PHI(dwArg0C_33, dwArg0C_115, dwArg0C_115)
rLoc1_116: orig: rLoc1
    def:  rLoc1_116 = PHI(rLoc1_102, rLoc1_168)
    uses: rLoc1_82 = PHI(rLoc1_79, rLoc1_116)
          eax_135 = fn1000010A(rLoc1_116)
          rLoc1_48 = PHI(rLoc1, rLoc1_116, rLoc1_116)
          rLoc1_48 = PHI(rLoc1, rLoc1_116, rLoc1_116)
          FPUF_149 = cond(rLoc1_116 - Mem34[0x10033298:real64])
ecx_117: orig: ecx
    def:  ecx_117 = PHI(ecx_105, ecx_161)
rLoc2_118: orig: rLoc2
    def:  rLoc2_118 = (real64) dwArg04_100
    uses: FPUF_119 = cond(rLoc2_118 - Mem34[0x10033298:real64])
FPUF_119: orig: FPUF
    def:  FPUF_119 = cond(rLoc2_118 - Mem34[0x10033298:real64])
    uses: SCZO_120 = FPUF_119
          branch Test(NE,FPUF_119) l100000D7
          FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
SCZO_120: orig: SCZO
    def:  SCZO_120 = FPUF_119
    uses: SZO_121 = SCZO_120 (alias)
          Z_122 = SCZO_120 (alias)
          SO_123 = SCZO_120 (alias)
          C_124 = SCZO_120 (alias)
SZO_121: orig: SZO
    def:  SZO_121 = SCZO_120 (alias)
Z_122: orig: Z
    def:  Z_122 = SCZO_120 (alias)
SO_123: orig: SO
    def:  SO_123 = SCZO_120 (alias)
C_124: orig: C
    def:  C_124 = SCZO_120 (alias)
FPUF_125: orig: FPUF
    def:  FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
    uses: FPUF_49 = PHI(FPUF, FPUF_125, FPUF_125)
          FPUF_49 = PHI(FPUF, FPUF_125, FPUF_125)
edi_126: orig: edi
    def:  edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
    uses: edi_83 = PHI(edi_77, edi_126)
          SCZO_137 = cond(ebp_18 - edi_126)
SCZO_127: orig: SCZO
    def:  SCZO_127 = cond(esi_87 - ebp_18)
    uses: SZO_128 = SCZO_127 (alias)
          Z_129 = SCZO_127 (alias)
          SO_130 = SCZO_127 (alias)
          C_131 = SCZO_127 (alias)
SZO_128: orig: SZO
    def:  SZO_128 = SCZO_127 (alias)
Z_129: orig: Z
    def:  Z_129 = SCZO_127 (alias)
SO_130: orig: SO
    def:  SO_130 = SCZO_127 (alias)
    uses: branch Test(LT,SO_130) l10000048
C_131: orig: C
    def:  C_131 = SCZO_127 (alias)
rLoc2_132: orig: rLoc2
    def:  rLoc2_132 = (real64) dwArg04_100
    uses: eax_133 = fn1000010A(rLoc2_132)
          rLoc2_50 = PHI(rLoc2, rLoc2_132, rLoc2_132)
          rLoc2_50 = PHI(rLoc2, rLoc2_132, rLoc2_132)
eax_133: orig: eax
    def:  eax_133 = fn1000010A(rLoc2_132)
    uses: Mem134[ebx_9:word32] = eax_133
Mem134: orig: Mem0
    def:  Mem134[ebx_9:word32] = eax_133
eax_135: orig: eax
    def:  eax_135 = fn1000010A(rLoc1_116)
    uses: Mem146[ecx_136:word32] = eax_135
          eax_51 = PHI(eax_25, eax_135, eax_135)
          eax_51 = PHI(eax_25, eax_135, eax_135)
ecx_136: orig: ecx
    def:  ecx_136 = dwArg10
    uses: Mem146[ecx_136:word32] = eax_135
          ecx_52 = PHI(ecx_26, ecx_136, ecx_136)
          Mem148[ecx_136:word32] = 0x00000000
          ecx_52 = PHI(ecx_26, ecx_136, ecx_136)
SCZO_137: orig: SCZO
    def:  SCZO_137 = cond(ebp_18 - edi_126)
    uses: SZO_138 = SCZO_137 (alias)
          Z_139 = SCZO_137 (alias)
          SO_140 = SCZO_137 (alias)
          C_141 = SCZO_137 (alias)
          SCZO_53 = PHI(SCZO_32, SCZO_137, SCZO_137)
          SCZO_53 = PHI(SCZO_32, SCZO_137, SCZO_137)
SZO_138: orig: SZO
    def:  SZO_138 = SCZO_137 (alias)
    uses: branch Test(LE,SZO_138) l10000107
          SZO_54 = PHI(SZO_28, SZO_138, SZO_138)
          SZO_54 = PHI(SZO_28, SZO_138, SZO_138)
Z_139: orig: Z
    def:  Z_139 = SCZO_137 (alias)
    uses: Z_55 = PHI(Z_29, Z_139, Z_139)
          Z_55 = PHI(Z_29, Z_139, Z_139)
SO_140: orig: SO
    def:  SO_140 = SCZO_137 (alias)
    uses: SO_56 = PHI(SO_30, SO_140, SO_140)
          SO_56 = PHI(SO_30, SO_140, SO_140)
C_141: orig: C
    def:  C_141 = SCZO_137 (alias)
    uses: C_57 = PHI(C_31, C_141, C_141)
          C_57 = PHI(C_31, C_141, C_141)
edi_142: orig: edi
    def:  edi_142 = dwLoc10_70
    uses: edi_58 = PHI(edi, edi_142, edi_142)
          edi_58 = PHI(edi, edi_142, edi_142)
esp_143: orig: esp
    def:  esp_143 = fp - 0x0000000C
esi_144: orig: esi
    def:  esi_144 = dwLoc0C_67
    uses: esi_59 = PHI(esi, esi_144, esi_144)
          esi_59 = PHI(esi, esi_144, esi_144)
esp_145: orig: esp
    def:  esp_145 = fp - 0x00000008
Mem146: orig: Mem0
    def:  Mem146[ecx_136:word32] = eax_135
Mem147: orig: Mem0
    def:  Mem147[ebx_9:word32] = 0x00000000
Mem148: orig: Mem0
    def:  Mem148[ecx_136:word32] = 0x00000000
FPUF_149: orig: FPUF
    def:  FPUF_149 = cond(rLoc1_116 - Mem34[0x10033298:real64])
    uses: SCZO_150 = FPUF_149
          branch Test(NE,FPUF_149) l100000D7
          FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
          FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
          FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
SCZO_150: orig: SCZO
    def:  SCZO_150 = FPUF_149
    uses: SZO_151 = SCZO_150 (alias)
          Z_152 = SCZO_150 (alias)
          SO_153 = SCZO_150 (alias)
          C_154 = SCZO_150 (alias)
SZO_151: orig: SZO
    def:  SZO_151 = SCZO_150 (alias)
Z_152: orig: Z
    def:  Z_152 = SCZO_150 (alias)
SO_153: orig: SO
    def:  SO_153 = SCZO_150 (alias)
C_154: orig: C
    def:  C_154 = SCZO_150 (alias)
SCZO_155: orig: SCZO
    def:  SCZO_155 = cond(edi_83 - 0x000186A0)
    uses: SZO_156 = SCZO_155 (alias)
          Z_157 = SCZO_155 (alias)
          SO_158 = SCZO_155 (alias)
          C_159 = SCZO_155 (alias)
SZO_156: orig: SZO
    def:  SZO_156 = SCZO_155 (alias)
Z_157: orig: Z
    def:  Z_157 = SCZO_155 (alias)
    uses: branch Test(NE,Z_157) l100000D7
SO_158: orig: SO
    def:  SO_158 = SCZO_155 (alias)
C_159: orig: C
    def:  C_159 = SCZO_155 (alias)
edi_160: orig: edi
    def:  edi_160 = esi_87
    uses: edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
ecx_161: orig: ecx
    def:  ecx_161 = ecx_105 + 0x00000001
    uses: SZO_162 = cond(ecx_161)
          dwArg0C_167 = ecx_161
          ecx_117 = PHI(ecx_105, ecx_161)
SZO_162: orig: SZO
    def:  SZO_162 = cond(ecx_161)
    uses: SCZO_163 = SZO_162 (alias)
          Z_164 = SZO_162 (alias)
          SO_165 = SZO_162 (alias)
SCZO_163: orig: SCZO
    def:  SCZO_163 = SZO_162 (alias)
Z_164: orig: Z
    def:  Z_164 = SZO_162 (alias)
SO_165: orig: SO
    def:  SO_165 = SZO_162 (alias)
rLoc1_166: orig: rLoc1
    def:  rLoc1_166 = rLoc1_102
dwArg0C_167: orig: dwArg0C
    def:  dwArg0C_167 = ecx_161
    uses: rLoc1_168 = (real64) dwArg0C_167
          dwArg0C_115 = PHI(dwArg0C_106, dwArg0C_167)
rLoc1_168: orig: rLoc1
    def:  rLoc1_168 = (real64) dwArg0C_167
    uses: rLoc1_116 = PHI(rLoc1_102, rLoc1_168)
ecx_169: orig: ecx
    def:  ecx_169 = ecx_91 + 0x00000001
    uses: SZO_170 = cond(ecx_169)
          dwArg04_174 = ecx_169
SZO_170: orig: SZO
    def:  SZO_170 = cond(ecx_169)
    uses: SCZO_171 = SZO_170 (alias)
          Z_172 = SZO_170 (alias)
          SO_173 = SZO_170 (alias)
SCZO_171: orig: SCZO
    def:  SCZO_171 = SZO_170 (alias)
Z_172: orig: Z
    def:  Z_172 = SZO_170 (alias)
SO_173: orig: SO
    def:  SO_173 = SZO_170 (alias)
dwArg04_174: orig: dwArg04
    def:  dwArg04_174 = ecx_169
    uses: rLoc2_175 = (real64) dwArg04_174
rLoc2_175: orig: rLoc2
    def:  rLoc2_175 = (real64) dwArg04_174
    uses: dwArg04_176 = (real32) rLoc2_175
          rLoc2_101 = PHI(rLoc2_175, rLoc2_93)
dwArg04_176: orig: dwArg04
    def:  dwArg04_176 = (real32) rLoc2_175
    uses: dwArg04_100 = PHI(dwArg04_176, dwArg04_89)
// fn10000000
// Return size: 0
void fn10000000(word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10)
fn10000000_entry:
	def fp
	def dwArg04
	def ebx
	def dwArg0C
	def ebp
	def Mem0
	def dwArg08
	def dwArg10
	def dwLoc0C
	def dwLoc10
	def rLoc3
	def rLoc1
	def FPUF
	def rLoc2
	def edi
	def esi
	// succ:  l10000000
l10000000:
	esp_1 = fp
	eax_3 = dwArg04
	v5_5 = ebx
	esp_6 = fp - 0x00000004
	dwLoc04_7 = v5_5
	ebx_9 = dwArg0C
	v7_11 = ebp
	esp_12 = fp - 0x00000008
	dwLoc08_13 = v7_11
	ecx_15 = (int32) Mem0[eax_3 + 0x00000006:word16]
	edx_16 = (int32) Mem0[eax_3 + 0x00000002:word16]
	ebp_18 = dwArg08
	ecx_19 = ecx_15 - edx_16
	SCZO_20 = cond(ecx_19)
	edx_22 = dwArg10
	Mem23[ebx_9:word32] = ecx_19
	ecx_24 = (int32) Mem23[eax_3 + 0x00000004:word16]
	eax_25 = (int32) Mem23[eax_3:word16]
	ecx_26 = ecx_24 - eax_25
	SCZO_27 = cond(ecx_26)
	SZO_28 = cond(ebp_18 & ebp_18)
	Z_29 = SZO_28 (alias)
	SO_30 = SZO_28 (alias)
	C_31 = false
	SCZO_32 = C_31 (alias)
	dwArg0C_33 = ecx_26
	Mem34[edx_22:word32] = ecx_26
	branch Test(EQ,Z_29) l10000107
	// succ:  l10000035 l10000107
l10000035:
	rLoc1_64 = (real64) Mem34[ebx_9:int32]
	v16_65 = esi
	esp_66 = fp - 0x0000000C
	dwLoc0C_67 = v16_65
	v18_68 = edi
	esp_69 = fp - 0x00000010
	dwLoc10_70 = v18_68
	esi_71 = 0x00000000
	SZO_72 = cond(0x00000000)
	Z_73 = SZO_72 (alias)
	SO_74 = SZO_72 (alias)
	C_75 = false
	SCZO_76 = C_75 (alias)
	edi_77 = 0x000186A0
	dwArg04_78 = (real32) rLoc1_64
	rLoc1_79 = (real64) dwArg0C_33
	// succ:  l10000048
l10000048:
	dwArg04_80 = PHI(dwArg04_78, dwArg04_100)
	rLoc3_81 = PHI(rLoc3, rLoc3_108)
	rLoc1_82 = PHI(rLoc1_79, rLoc1_116)
	edi_83 = PHI(edi_77, edi_126)
	esi_84 = PHI(esi_71, esi_87)
	rLoc2_85 = (real64) dwArg04_80
	rLoc2_86 = rLoc2_85 * Mem34[0x0099188A:real64]
	esi_87 = esi_84 + 0x00000001
	SZO_88 = cond(esi_87)
	dwArg04_89 = (real32) rLoc2_86
	eax_90 = fn1000010A(rLoc2_86)
	ecx_91 = eax_90
	dwArg0C_92 = ecx_91
	rLoc2_93 = (real64) dwArg0C_92
	FPUF_94 = cond(rLoc2_93 - dwArg04_89)
	SCZO_95 = FPUF_94
	SZO_96 = SCZO_95 (alias)
	Z_97 = SCZO_95 (alias)
	SO_98 = SCZO_95 (alias)
	C_99 = SCZO_95 (alias)
	branch Test(EQ,FPUF_94) l1000007F
	// succ:  l10000072 l1000007F
l10000072:
	ecx_169 = ecx_91 + 0x00000001
	SZO_170 = cond(ecx_169)
	SCZO_171 = SZO_170 (alias)
	Z_172 = SZO_170 (alias)
	SO_173 = SZO_170 (alias)
	dwArg04_174 = ecx_169
	rLoc2_175 = (real64) dwArg04_174
	dwArg04_176 = (real32) rLoc2_175
	// succ:  l1000007F
l1000007F:
	dwArg04_100 = PHI(dwArg04_176, dwArg04_89)
	rLoc2_101 = PHI(rLoc2_175, rLoc2_93)
	rLoc1_102 = rLoc1_82 * Mem34[0x10033290:real64]
	rLoc2_103 = rLoc2_101
	eax_104 = fn1000010A(rLoc2_103)
	ecx_105 = eax_104
	dwArg0C_106 = ecx_105
	rLoc2_107 = (real64) dwArg0C_106
	rLoc3_108 = rLoc2_107
	FPUF_109 = cond(rLoc3_108 - rLoc2_107)
	SCZO_110 = FPUF_109
	SZO_111 = SCZO_110 (alias)
	Z_112 = SCZO_110 (alias)
	SO_113 = SCZO_110 (alias)
	C_114 = SCZO_110 (alias)
	branch Test(EQ,FPUF_109) l100000AD
	// succ:  l100000A2 l100000AD
l100000A2:
	ecx_161 = ecx_105 + 0x00000001
	SZO_162 = cond(ecx_161)
	SCZO_163 = SZO_162 (alias)
	Z_164 = SZO_162 (alias)
	SO_165 = SZO_162 (alias)
	rLoc1_166 = rLoc1_102
	dwArg0C_167 = ecx_161
	rLoc1_168 = (real64) dwArg0C_167
	// succ:  l100000AD
l100000AD:
	dwArg0C_115 = PHI(dwArg0C_106, dwArg0C_167)
	rLoc1_116 = PHI(rLoc1_102, rLoc1_168)
	ecx_117 = PHI(ecx_105, ecx_161)
	rLoc2_118 = (real64) dwArg04_100
	FPUF_119 = cond(rLoc2_118 - Mem34[0x10033298:real64])
	SCZO_120 = FPUF_119
	SZO_121 = SCZO_120 (alias)
	Z_122 = SCZO_120 (alias)
	SO_123 = SCZO_120 (alias)
	C_124 = SCZO_120 (alias)
	branch Test(NE,FPUF_119) l100000D7
	// succ:  l100000BF l100000D7
l100000BF:
	FPUF_149 = cond(rLoc1_116 - Mem34[0x10033298:real64])
	SCZO_150 = FPUF_149
	SZO_151 = SCZO_150 (alias)
	Z_152 = SCZO_150 (alias)
	SO_153 = SCZO_150 (alias)
	C_154 = SCZO_150 (alias)
	branch Test(NE,FPUF_149) l100000D7
	// succ:  l100000CD l100000D7
l100000CD:
	SCZO_155 = cond(edi_83 - 0x000186A0)
	SZO_156 = SCZO_155 (alias)
	Z_157 = SCZO_155 (alias)
	SO_158 = SCZO_155 (alias)
	C_159 = SCZO_155 (alias)
	branch Test(NE,Z_157) l100000D7
	// succ:  l100000D5 l100000D7
l100000D5:
	edi_160 = esi_87
	// succ:  l100000D7
l100000D7:
	FPUF_125 = PHI(FPUF_119, FPUF_149, FPUF_149, FPUF_149)
	edi_126 = PHI(edi_83, edi_83, edi_83, edi_160)
	SCZO_127 = cond(esi_87 - ebp_18)
	SZO_128 = SCZO_127 (alias)
	Z_129 = SCZO_127 (alias)
	SO_130 = SCZO_127 (alias)
	C_131 = SCZO_127 (alias)
	branch Test(LT,SO_130) l10000048
	// succ:  l100000DF l10000048
l100000DF:
	rLoc2_132 = (real64) dwArg04_100
	eax_133 = fn1000010A(rLoc2_132)
	Mem134[ebx_9:word32] = eax_133
	eax_135 = fn1000010A(rLoc1_116)
	ecx_136 = dwArg10
	SCZO_137 = cond(ebp_18 - edi_126)
	SZO_138 = SCZO_137 (alias)
	Z_139 = SCZO_137 (alias)
	SO_140 = SCZO_137 (alias)
	C_141 = SCZO_137 (alias)
	edi_142 = dwLoc10_70
	esp_143 = fp - 0x0000000C
	esi_144 = dwLoc0C_67
	esp_145 = fp - 0x00000008
	Mem146[ecx_136:word32] = eax_135
	branch Test(LE,SZO_138) l10000107
	// succ:  l100000FB l10000107
l100000FB:
	Mem147[ebx_9:word32] = 0x00000000
	Mem148[ecx_136:word32] = 0x00000000
	// succ:  l10000107
l10000107:
	dwLoc0C_43 = PHI(dwLoc0C, dwLoc0C_67, dwLoc0C_67)
	dwLoc10_44 = PHI(dwLoc10, dwLoc10_70, dwLoc10_70)
	dwArg04_45 = PHI(dwArg04, dwArg04_100, dwArg04_100)
	rLoc3_46 = PHI(rLoc3, rLoc3_108, rLoc3_108)
	dwArg0C_47 = PHI(dwArg0C_33, dwArg0C_115, dwArg0C_115)
	rLoc1_48 = PHI(rLoc1, rLoc1_116, rLoc1_116)
	FPUF_49 = PHI(FPUF, FPUF_125, FPUF_125)
	rLoc2_50 = PHI(rLoc2, rLoc2_132, rLoc2_132)
	eax_51 = PHI(eax_25, eax_135, eax_135)
	ecx_52 = PHI(ecx_26, ecx_136, ecx_136)
	SCZO_53 = PHI(SCZO_32, SCZO_137, SCZO_137)
	SZO_54 = PHI(SZO_28, SZO_138, SZO_138)
	Z_55 = PHI(Z_29, Z_139, Z_139)
	SO_56 = PHI(SO_30, SO_140, SO_140)
	C_57 = PHI(C_31, C_141, C_141)
	edi_58 = PHI(edi, edi_142, edi_142)
	esi_59 = PHI(esi, esi_144, esi_144)
	ebp_60 = dwLoc08_13
	esp_61 = fp - 0x00000004
	ebx_62 = dwLoc04_7
	esp_63 = fp
	return
	// succ:  fn10000000_exit
fn10000000_exit:

fp:fp
    def:  def fp
    uses: esp_1 = fp
esp_1: orig: esp
    def:  esp_1 = fp
rArg0:FPU stack
    def:  def rArg0
    uses: dwLoc04_3 = (int32) rArg0
dwLoc04_3: orig: dwLoc04
    def:  dwLoc04_3 = (int32) rArg0
    uses: eax_4 = dwLoc04_3
eax_4: orig: eax
    def:  eax_4 = dwLoc04_3
    uses: return eax_4
// fn1000010A
// Return size: 0
word32 fn1000010A(real64 rArg0)
fn1000010A_entry:
	def fp
	def rArg0
	// succ:  l1000010A
l1000010A:
	esp_1 = fp
	dwLoc04_3 = (int32) rArg0
	eax_4 = dwLoc04_3
	return eax_4
	// succ:  fn1000010A_exit
fn1000010A_exit:

