fp:fp
    def:  def fp
    uses: sp_1 = fp
sp_1: orig: sp
    def:  sp_1 = fp
ds:ds
    def:  def ds
    uses: bx_3 = fn0C00_000C(ds)
          Mem4[ds:0x0300:word16] = bx_3
          Mem5[ds:0x0302:byte] = 0x00
bx_3: orig: bx
    def:  bx_3 = fn0C00_000C(ds)
    uses: Mem4[ds:0x0300:word16] = bx_3
Mem4: orig: Mem0
    def:  Mem4[ds:0x0300:word16] = bx_3
Mem5: orig: Mem0
    def:  Mem5[ds:0x0302:byte] = 0x00
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def fp
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	sp_1 = fp
	bx_3 = fn0C00_000C(ds)
	Mem4[ds:0x0300:word16] = bx_3
	Mem5[ds:0x0302:byte] = 0x00
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_1 = fp
sp_1: orig: sp
    def:  sp_1 = fp
ds:ds
    def:  def ds
    uses: cx_3 = ds
          ah_40 = Mem0[ds:di_23 + 0x0001:byte]
cx_3: orig: cx
    def:  cx_3 = ds
    uses: es_4 = cx_3
es_4: orig: es
    def:  es_4 = cx_3
    uses: SCZO_63 = cond(0x00 - Mem0[es_4:di_16:byte])
di_5: orig: di
    def:  di_5 = 0x7E0F
    uses: di_16 = PHI((di_5, l0C00_000C), (di_67, l0C00_0019_1))
cx_6: orig: cx
    def:  cx_6 = 0x000C
    uses: cl_7 = (byte) cx_6 (alias)
          cx_17 = PHI((cx_6, l0C00_000C), (cx_68, l0C00_0019_1))
cl_7: orig: cl
    def:  cl_7 = (byte) cx_6 (alias)
    uses: cl_18 = PHI((cl_7, l0C00_000C), (cl_69, l0C00_0019_1))
al_8: orig: al
    def:  al_8 = 0x00
    uses: ax_10 = DPB(ax, al_8, 0) (alias)
ax:ax
    def:  def ax
    uses: ax_10 = DPB(ax, al_8, 0) (alias)
ax_10: orig: ax
    def:  ax_10 = DPB(ax, al_8, 0) (alias)
    uses: ax_41 = DPB(ax_10, ah_40, 8) (alias)
          ax_31 = PHI((ax_41, l0C00_001D), (ax_10, l0C00_002D))
SZO_11: orig: SZO
    def:  SZO_11 = cond(0x00)
    uses: Z_12 = (bool) SZO_11 (alias)
          SZO_21 = PHI((SZO_11, l0C00_000C), (SZO_65, l0C00_0019_1))
Z_12: orig: Z
    def:  Z_12 = (bool) SZO_11 (alias)
    uses: Z_22 = PHI((Z_12, l0C00_000C), (Z_66, l0C00_0019_1))
C_13: orig: C
    def:  C_13 = false
    uses: SCZO_15 = DPB(SCZO, C_13, 0) (alias)
          C_20 = PHI((C_13, l0C00_000C), (C_64, l0C00_0019_1))
SCZO:Flags
    def:  def SCZO
    uses: SCZO_15 = DPB(SCZO, C_13, 0) (alias)
SCZO_15: orig: SCZO
    def:  SCZO_15 = DPB(SCZO, C_13, 0) (alias)
    uses: SCZO_19 = PHI((SCZO_15, l0C00_000C), (SCZO_63, l0C00_0019_1))
di_16: orig: di
    def:  di_16 = PHI((di_5, l0C00_000C), (di_67, l0C00_0019_1))
    uses: di_23 = PHI((di_16, l0C00_0019), (di_67, l0C00_0019_1))
          SCZO_63 = cond(0x00 - Mem0[es_4:di_16:byte])
          di_67 = di_16 + 0x0001
cx_17: orig: cx
    def:  cx_17 = PHI((cx_6, l0C00_000C), (cx_68, l0C00_0019_1))
    uses: branch cx_17 == 0x0000 l0C00_001B
          cx_24 = PHI((cx_17, l0C00_0019), (cx_68, l0C00_0019_1))
          cx_68 = cx_17 - 0x0001
cl_18: orig: cl
    def:  cl_18 = PHI((cl_7, l0C00_000C), (cl_69, l0C00_0019_1))
    uses: cl_25 = PHI((cl_18, l0C00_0019), (cl_69, l0C00_0019_1))
SCZO_19: orig: SCZO
    def:  SCZO_19 = PHI((SCZO_15, l0C00_000C), (SCZO_63, l0C00_0019_1))
    uses: SCZO_26 = PHI((SCZO_19, l0C00_0019), (SCZO_63, l0C00_0019_1))
C_20: orig: C
    def:  C_20 = PHI((C_13, l0C00_000C), (C_64, l0C00_0019_1))
    uses: C_27 = PHI((C_20, l0C00_0019), (C_64, l0C00_0019_1))
SZO_21: orig: SZO
    def:  SZO_21 = PHI((SZO_11, l0C00_000C), (SZO_65, l0C00_0019_1))
    uses: SZO_28 = PHI((SZO_21, l0C00_0019), (SZO_65, l0C00_0019_1))
Z_22: orig: Z
    def:  Z_22 = PHI((Z_12, l0C00_000C), (Z_66, l0C00_0019_1))
    uses: Z_29 = PHI((Z_22, l0C00_0019), (Z_66, l0C00_0019_1))
di_23: orig: di
    def:  di_23 = PHI((di_16, l0C00_0019), (di_67, l0C00_0019_1))
    uses: ah_40 = Mem0[ds:di_23 + 0x0001:byte]
          bx_47 = di_23
cx_24: orig: cx
    def:  cx_24 = PHI((cx_17, l0C00_0019), (cx_68, l0C00_0019_1))
    uses: cx_57 = DPB(cx_24, cl_56, 0) (alias)
cl_25: orig: cl
    def:  cl_25 = PHI((cl_18, l0C00_0019), (cl_69, l0C00_0019_1))
SCZO_26: orig: SCZO
    def:  SCZO_26 = PHI((SCZO_19, l0C00_0019), (SCZO_63, l0C00_0019_1))
    uses: SCZO_61 = DPB(SCZO_26, C_60, 0) (alias)
C_27: orig: C
    def:  C_27 = PHI((C_20, l0C00_0019), (C_64, l0C00_0019_1))
SZO_28: orig: SZO
    def:  SZO_28 = PHI((SZO_21, l0C00_0019), (SZO_65, l0C00_0019_1))
Z_29: orig: Z
    def:  Z_29 = PHI((Z_22, l0C00_0019), (Z_66, l0C00_0019_1))
    uses: branch Test(EQ,Z_29) l0C00_002D
ah_30: orig: ah
    def:  ah_30 = PHI((ah_40, l0C00_001D), (ah, l0C00_002D))
ax_31: orig: ax
    def:  ax_31 = PHI((ax_41, l0C00_001D), (ax_10, l0C00_002D))
cx_32: orig: cx
    def:  cx_32 = PHI((cx_44, l0C00_001D), (cx_57, l0C00_002D))
cl_33: orig: cl
    def:  cl_33 = PHI((cl_45, l0C00_001D), (cl_56, l0C00_002D))
bx_34: orig: bx
    def:  bx_34 = PHI((bx_48, l0C00_001D), (bx_53, l0C00_002D))
SCZO_35: orig: SCZO
    def:  SCZO_35 = PHI((SCZO_49, l0C00_001D), (SCZO_61, l0C00_002D))
C_36: orig: C
    def:  C_36 = PHI((C_50, l0C00_001D), (C_60, l0C00_002D))
SZO_37: orig: SZO
    def:  SZO_37 = PHI((SZO_51, l0C00_001D), (SZO_58, l0C00_002D))
Z_38: orig: Z
    def:  Z_38 = PHI((Z_52, l0C00_001D), (Z_59, l0C00_002D))
Mem0:Global memory
    def:  def Mem0
    uses: ah_40 = Mem0[ds:di_23 + 0x0001:byte]
          SCZO_63 = cond(0x00 - Mem0[es_4:di_16:byte])
ah_40: orig: ah
    def:  ah_40 = Mem0[ds:di_23 + 0x0001:byte]
    uses: ax_41 = DPB(ax_10, ah_40, 8) (alias)
          ah_30 = PHI((ah_40, l0C00_001D), (ah, l0C00_002D))
ax_41: orig: ax
    def:  ax_41 = DPB(ax_10, ah_40, 8) (alias)
    uses: Z_42 = ax_41 == 0x0000
          cx_43 = __bsr(ax_41)
          ax_31 = PHI((ax_41, l0C00_001D), (ax_10, l0C00_002D))
Z_42: orig: Z
    def:  Z_42 = ax_41 == 0x0000
cx_43: orig: cx
    def:  cx_43 = __bsr(ax_41)
    uses: cx_44 = cx_43 - 0x0008
cx_44: orig: cx
    def:  cx_44 = cx_43 - 0x0008
    uses: cl_45 = (byte) cx_44 (alias)
          SCZO_46 = cond(cx_44)
          cx_32 = PHI((cx_44, l0C00_001D), (cx_57, l0C00_002D))
cl_45: orig: cl
    def:  cl_45 = (byte) cx_44 (alias)
    uses: cl_33 = PHI((cl_45, l0C00_001D), (cl_56, l0C00_002D))
SCZO_46: orig: SCZO
    def:  SCZO_46 = cond(cx_44)
bx_47: orig: bx
    def:  bx_47 = di_23
    uses: bx_48 = bx_47 - 0x7E03
bx_48: orig: bx
    def:  bx_48 = bx_47 - 0x7E03
    uses: SCZO_49 = cond(bx_48)
          return bx_48
          bx_34 = PHI((bx_48, l0C00_001D), (bx_53, l0C00_002D))
SCZO_49: orig: SCZO
    def:  SCZO_49 = cond(bx_48)
    uses: C_50 = (bool) SCZO_49 (alias)
          SZO_51 = SCZO_49 (alias)
          Z_52 = (bool) SCZO_49 (alias)
          SCZO_35 = PHI((SCZO_49, l0C00_001D), (SCZO_61, l0C00_002D))
C_50: orig: C
    def:  C_50 = (bool) SCZO_49 (alias)
    uses: C_36 = PHI((C_50, l0C00_001D), (C_60, l0C00_002D))
SZO_51: orig: SZO
    def:  SZO_51 = SCZO_49 (alias)
    uses: SZO_37 = PHI((SZO_51, l0C00_001D), (SZO_58, l0C00_002D))
Z_52: orig: Z
    def:  Z_52 = (bool) SCZO_49 (alias)
    uses: Z_38 = PHI((Z_52, l0C00_001D), (Z_59, l0C00_002D))
bx_53: orig: bx
    def:  bx_53 = 0x0000
    uses: return bx_53
          bx_34 = PHI((bx_48, l0C00_001D), (bx_53, l0C00_002D))
SZO_54: orig: SZO
    def:  SZO_54 = cond(0x0000)
C_55: orig: C
    def:  C_55 = false
cl_56: orig: cl
    def:  cl_56 = 0x00
    uses: cx_57 = DPB(cx_24, cl_56, 0) (alias)
          cl_33 = PHI((cl_45, l0C00_001D), (cl_56, l0C00_002D))
cx_57: orig: cx
    def:  cx_57 = DPB(cx_24, cl_56, 0) (alias)
    uses: cx_32 = PHI((cx_44, l0C00_001D), (cx_57, l0C00_002D))
SZO_58: orig: SZO
    def:  SZO_58 = cond(0x00)
    uses: Z_59 = (bool) SZO_58 (alias)
          SZO_37 = PHI((SZO_51, l0C00_001D), (SZO_58, l0C00_002D))
Z_59: orig: Z
    def:  Z_59 = (bool) SZO_58 (alias)
    uses: Z_38 = PHI((Z_52, l0C00_001D), (Z_59, l0C00_002D))
C_60: orig: C
    def:  C_60 = false
    uses: SCZO_61 = DPB(SCZO_26, C_60, 0) (alias)
          C_36 = PHI((C_50, l0C00_001D), (C_60, l0C00_002D))
SCZO_61: orig: SCZO
    def:  SCZO_61 = DPB(SCZO_26, C_60, 0) (alias)
    uses: SCZO_35 = PHI((SCZO_49, l0C00_001D), (SCZO_61, l0C00_002D))
ah:ah
    def:  def ah
    uses: ah_30 = PHI((ah_40, l0C00_001D), (ah, l0C00_002D))
SCZO_63: orig: SCZO
    def:  SCZO_63 = cond(0x00 - Mem0[es_4:di_16:byte])
    uses: C_64 = (bool) SCZO_63 (alias)
          SZO_65 = SCZO_63 (alias)
          Z_66 = (bool) SCZO_63 (alias)
          SCZO_26 = PHI((SCZO_19, l0C00_0019), (SCZO_63, l0C00_0019_1))
          SCZO_19 = PHI((SCZO_15, l0C00_000C), (SCZO_63, l0C00_0019_1))
C_64: orig: C
    def:  C_64 = (bool) SCZO_63 (alias)
    uses: C_27 = PHI((C_20, l0C00_0019), (C_64, l0C00_0019_1))
          C_20 = PHI((C_13, l0C00_000C), (C_64, l0C00_0019_1))
SZO_65: orig: SZO
    def:  SZO_65 = SCZO_63 (alias)
    uses: SZO_28 = PHI((SZO_21, l0C00_0019), (SZO_65, l0C00_0019_1))
          SZO_21 = PHI((SZO_11, l0C00_000C), (SZO_65, l0C00_0019_1))
Z_66: orig: Z
    def:  Z_66 = (bool) SCZO_63 (alias)
    uses: branch Test(NE,Z_66) l0C00_0019
          Z_29 = PHI((Z_22, l0C00_0019), (Z_66, l0C00_0019_1))
          Z_22 = PHI((Z_12, l0C00_000C), (Z_66, l0C00_0019_1))
di_67: orig: di
    def:  di_67 = di_16 + 0x0001
    uses: di_23 = PHI((di_16, l0C00_0019), (di_67, l0C00_0019_1))
          di_16 = PHI((di_5, l0C00_000C), (di_67, l0C00_0019_1))
cx_68: orig: cx
    def:  cx_68 = cx_17 - 0x0001
    uses: cl_69 = (byte) cx_68 (alias)
          cx_24 = PHI((cx_17, l0C00_0019), (cx_68, l0C00_0019_1))
          cx_17 = PHI((cx_6, l0C00_000C), (cx_68, l0C00_0019_1))
cl_69: orig: cl
    def:  cl_69 = (byte) cx_68 (alias)
    uses: cl_25 = PHI((cl_18, l0C00_0019), (cl_69, l0C00_0019_1))
          cl_18 = PHI((cl_7, l0C00_000C), (cl_69, l0C00_0019_1))
// fn0C00_000C
// Return size: 0
word16 fn0C00_000C(selector ds)
fn0C00_000C_entry:
	def fp
	def ds
	def ax
	def SCZO
	def Mem0
	def ah
	// succ:  l0C00_000C
l0C00_000C:
	sp_1 = fp
	cx_3 = ds
	es_4 = cx_3
	di_5 = 0x7E0F
	cx_6 = 0x000C
	cl_7 = (byte) cx_6 (alias)
	al_8 = 0x00
	ax_10 = DPB(ax, al_8, 0) (alias)
	SZO_11 = cond(0x00)
	Z_12 = (bool) SZO_11 (alias)
	C_13 = false
	SCZO_15 = DPB(SCZO, C_13, 0) (alias)
	// succ:  l0C00_0019
l0C00_0019:
	di_16 = PHI((di_5, l0C00_000C), (di_67, l0C00_0019_1))
	cx_17 = PHI((cx_6, l0C00_000C), (cx_68, l0C00_0019_1))
	cl_18 = PHI((cl_7, l0C00_000C), (cl_69, l0C00_0019_1))
	SCZO_19 = PHI((SCZO_15, l0C00_000C), (SCZO_63, l0C00_0019_1))
	C_20 = PHI((C_13, l0C00_000C), (C_64, l0C00_0019_1))
	SZO_21 = PHI((SZO_11, l0C00_000C), (SZO_65, l0C00_0019_1))
	Z_22 = PHI((Z_12, l0C00_000C), (Z_66, l0C00_0019_1))
	branch cx_17 == 0x0000 l0C00_001B
	// succ:  l0C00_0019_1 l0C00_001B
l0C00_0019_1:
	SCZO_63 = cond(0x00 - Mem0[es_4:di_16:byte])
	C_64 = (bool) SCZO_63 (alias)
	SZO_65 = SCZO_63 (alias)
	Z_66 = (bool) SCZO_63 (alias)
	di_67 = di_16 + 0x0001
	cx_68 = cx_17 - 0x0001
	cl_69 = (byte) cx_68 (alias)
	branch Test(NE,Z_66) l0C00_0019
	// succ:  l0C00_001B l0C00_0019
l0C00_001B:
	di_23 = PHI((di_16, l0C00_0019), (di_67, l0C00_0019_1))
	cx_24 = PHI((cx_17, l0C00_0019), (cx_68, l0C00_0019_1))
	cl_25 = PHI((cl_18, l0C00_0019), (cl_69, l0C00_0019_1))
	SCZO_26 = PHI((SCZO_19, l0C00_0019), (SCZO_63, l0C00_0019_1))
	C_27 = PHI((C_20, l0C00_0019), (C_64, l0C00_0019_1))
	SZO_28 = PHI((SZO_21, l0C00_0019), (SZO_65, l0C00_0019_1))
	Z_29 = PHI((Z_22, l0C00_0019), (Z_66, l0C00_0019_1))
	branch Test(EQ,Z_29) l0C00_002D
	// succ:  l0C00_001D l0C00_002D
l0C00_001D:
	ah_40 = Mem0[ds:di_23 + 0x0001:byte]
	ax_41 = DPB(ax_10, ah_40, 8) (alias)
	Z_42 = ax_41 == 0x0000
	cx_43 = __bsr(ax_41)
	cx_44 = cx_43 - 0x0008
	cl_45 = (byte) cx_44 (alias)
	SCZO_46 = cond(cx_44)
	bx_47 = di_23
	bx_48 = bx_47 - 0x7E03
	SCZO_49 = cond(bx_48)
	C_50 = (bool) SCZO_49 (alias)
	SZO_51 = SCZO_49 (alias)
	Z_52 = (bool) SCZO_49 (alias)
	return bx_48
	// succ:  fn0C00_000C_exit
l0C00_002D:
	bx_53 = 0x0000
	SZO_54 = cond(0x0000)
	C_55 = false
	cl_56 = 0x00
	cx_57 = DPB(cx_24, cl_56, 0) (alias)
	SZO_58 = cond(0x00)
	Z_59 = (bool) SZO_58 (alias)
	C_60 = false
	SCZO_61 = DPB(SCZO_26, C_60, 0) (alias)
	return bx_53
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:
	ah_30 = PHI((ah_40, l0C00_001D), (ah, l0C00_002D))
	ax_31 = PHI((ax_41, l0C00_001D), (ax_10, l0C00_002D))
	cx_32 = PHI((cx_44, l0C00_001D), (cx_57, l0C00_002D))
	cl_33 = PHI((cl_45, l0C00_001D), (cl_56, l0C00_002D))
	bx_34 = PHI((bx_48, l0C00_001D), (bx_53, l0C00_002D))
	SCZO_35 = PHI((SCZO_49, l0C00_001D), (SCZO_61, l0C00_002D))
	C_36 = PHI((C_50, l0C00_001D), (C_60, l0C00_002D))
	SZO_37 = PHI((SZO_51, l0C00_001D), (SZO_58, l0C00_002D))
	Z_38 = PHI((Z_52, l0C00_001D), (Z_59, l0C00_002D))

