fn0C00_0000 SCZO ax cx dx Top
const ax:<invalid> cx:0x0064 dx:<invalid> Top:0x00
    fn0C00_0000_entry sp:fp
    l0C00_0000 sp:fp
    fn0C00_0000_exit ax:<invalid> cx:0x0064 dx:<invalid> sp:fp Top:0x00

fn0C00_000F SCZO ax dx Top
const ax:<invalid> dx:<invalid> Sequence dx:ax:<invalid> Top:0x00
    fn0C00_000F_entry sp:fp
    l0C00_000F sp:fp
    l0C00_0018 ax:<invalid> bp:fp - 0x0002 sp:fp - 0x0002 Top:0x00
    l0C00_0026 ax:<invalid> bp:fp - 0x0002 sp:fp - 0x0002 Top:0x00
    l0C00_0029 ax:<invalid> bp:fp - 0x0002 dx:<invalid> Sequence dx:ax:<invalid> sp:fp - 0x0002 Top:0x00
    fn0C00_000F_exit ax:<invalid> bp:bp dx:<invalid> Sequence dx:ax:<invalid> sp:fp Top:0x00

