fn0C00_0000 SCZO ah al ax eax rax
const ax:<invalid>
    fn0C00_0000_entry sp:fp
    l0C00_0000 sp:fp
    l0C00_000E_thunk_fn0C00_000F ax:<invalid> di:di sp:fp
    fn0C00_0000_exit ax:<invalid> di:di sp:fp

fn0C00_000F
    fn0C00_000F_entry sp:fp
    l0C00_000F sp:fp
    fn0C00_000F_exit sp:fp

fn0C00_0014 SCZO ah al ax di dil eax edi rax rdi
const ax:<invalid> di:0x0000
    fn0C00_0014_entry sp:fp
    l0C00_0014 sp:fp
    fn0C00_0014_exit ax:ax - 0x0001 di:0x0000 sp:fp

