fn0C00_0000 SCZO ax al ah
const ax:<invalid>
    fn0C00_0000_entry sp:fp
    l0C00_0000 sp:fp
    l0C00_0000_tmp ax:<invalid> di:di sp:fp
    fn0C00_0000_exit ax:<invalid> di:di sp:fp

fn0C00_000F
    fn0C00_000F_entry sp:fp
    l0C00_000F sp:fp
    fn0C00_000F_exit sp:fp

fn0C00_0014 SCZO ax di al ah
const ax:<invalid> di:0x0000
    fn0C00_0014_entry sp:fp
    l0C00_0014 sp:fp
    fn0C00_0014_exit ax:ax - 0x0001 di:0x0000 sp:fp

