fn0C00_0000 SCZO ax cx bx di al cl bl ah ch bh es
const ah:<invalid> al:0x00 bx:<invalid> cl:0x00 cx:<invalid> di:<invalid> es:<invalid>
    fn0C00_0000_entry sp:fp
    l0C00_0000 sp:fp
    fn0C00_0000_exit ah:<invalid> al:0x00 bx:<invalid> cx:<invalid> di:<invalid> es:<invalid> sp:fp

fn0C00_000C SCZO ax cx bx di al cl bl ah ch bh es
const ah:<invalid> al:0x00 bx:<invalid> cl:0x00 cx:<invalid> di:<invalid>
    fn0C00_000C_entry sp:fp
    l0C00_000C sp:fp
    l0C00_0019 al:0x00 cx:<invalid> di:<invalid> es:ds sp:fp
    l0C00_0019_1 al:0x00 cx:<invalid> di:<invalid> es:ds sp:fp
    l0C00_001B al:0x00 cx:<invalid> di:<invalid> es:ds sp:fp
    l0C00_001D al:0x00 cx:<invalid> di:<invalid> es:ds sp:fp
    l0C00_002D al:0x00 cx:<invalid> di:<invalid> es:ds sp:fp
    fn0C00_000C_exit ah:<invalid> al:0x00 bx:<invalid> cx:<invalid> di:<invalid> es:ds sp:fp

