// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0000
l0C00_0000:
	cx = 0x002A
	sp = fp - 2
	wLoc02 = 0x0001
	sp = fp - 4
	wLoc04 = 0x0002
	call fn0C00_0023 (retsize: 2; depth: 6)
	sp = fp
	ax = 0x0000
	SZO = cond(0x0000)
	C = false
	sp = fp - 2
	wLoc02 = 0x0000
	sp = fp - 4
	wLoc04 = 0x0000
	sp = fp - 6
	wLoc06 = 0x0000
	sp = fp - 8
	wLoc08 = 0x0000
	sp = fp - 10
	wLoc0A = 0x0000
	sp = fp - 12
	wLoc0C = 0x0000
	call fn0C00_0034 (retsize: 2; depth: 14)
	sp = fp
	SCZO = cond(fp)
	sp = fp - 2
	wLoc02 = 0x0001
	sp = fp - 4
	wLoc04 = 0x0002
	call fn0C00_005D (retsize: 2; depth: 6)
	sp = fp
	SCZO = cond(fp)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// fn0C00_0023
// Return size: 2
define fn0C00_0023
fn0C00_0023_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0023
l0C00_0023:
	sp = fp - 2
	wLoc02 = cx
	sp = fp - 4
	wLoc04 = bp
	bp = fp - 4
	cx = wArg02
	ax = wArg04
	ax = ax + cx
	SCZO = cond(ax)
	bp = wLoc04
	sp = fp - 2
	cx = wLoc02
	sp = fp
	return
	// succ:  fn0C00_0023_exit
fn0C00_0023_exit:

// fn0C00_0034
// Return size: 2
define fn0C00_0034
fn0C00_0034_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0034
l0C00_0034:
	sp = fp - 2
	wLoc02 = bx
	sp = fp - 4
	wLoc04 = cx
	sp = fp - 6
	wLoc06 = dx
	sp = fp - 8
	wLoc08 = bp
	bp = fp - 8
	bx = fp + 0x0006
	// succ:  l0C00_003D
l0C00_003D:
	ax = Mem0[ds:bx:word16]
	bx = bx + 0x0002
	SCZO = cond(bx)
	SZO = cond(ax & ax)
	C = false
	branch Test(NE,Z) l0C00_003D
	// succ:  l0C00_0046 l0C00_003D
l0C00_0046:
	dx = wArg04
	bx = bx + 0x0002
	SCZO = cond(bx)
	ax = wArg02
	cx = Mem0[ds:bx - 0x0002:word16]
	bx = fp + 0x0006
	call fn0C00_0069 (retsize: 2; depth: 10)
	bp = wLoc08
	sp = fp - 6
	dx = wLoc06
	sp = fp - 4
	cx = wLoc04
	sp = fp - 2
	bx = wLoc02
	sp = fp
	return
	// succ:  fn0C00_0034_exit
fn0C00_0034_exit:

// fn0C00_005D
// Return size: 2
define fn0C00_005D
fn0C00_005D_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_005D
l0C00_005D:
	sp = fp - 2
	wLoc02 = cx
	sp = fp - 4
	wLoc04 = bp
	bp = fp - 4
	ax = wArg04
	ax = ax + cx
	SCZO = cond(ax)
	bp = wLoc04
	sp = fp - 2
	cx = wLoc02
	sp = fp
	return
	// succ:  fn0C00_005D_exit
fn0C00_005D_exit:

// fn0C00_0069
// Return size: 2
define fn0C00_0069
fn0C00_0069_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0069
l0C00_0069:
	Mem0[ds:0x0200:word16] = bx
	Mem0[ds:0x0300:word16] = cx
	return
	// succ:  fn0C00_0069_exit
fn0C00_0069_exit:

