= FCmpFragment ========================
a6:a6
    def:  def a6
    uses: fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
          NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
Mem0:Global memory
    def:  def Mem0
    uses: fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
          NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
fp0_2: orig: fp0
    def:  fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
    uses: NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
NZCV_3: orig: NZCV
    def:  NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
// FCmpFragment
// Return size: 0
void FCmpFragment(ptr32 a6)
FCmpFragment_entry:
	def a6
	def Mem0
	// succ:  l1
l1:
	fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
	NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
	branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
	// succ:  l2 l1
l2:
	return
	// succ:  FCmpFragment_exit
FCmpFragment_exit:

a6:a6
    def:  def a6
    uses: fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
          NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
Mem0:Global memory
    def:  def Mem0
    uses: fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
          NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
fp0_2: orig: fp0
    def:  fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
    uses: NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
          branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
NZCV_3: orig: NZCV
    def:  NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
// FCmpFragment
// Return size: 0
void FCmpFragment(ptr32 a6)
FCmpFragment_entry:
	def a6
	def Mem0
	// succ:  l1
l1:
	fp0_2 = (real80) Mem0[a6 - 0x00000010:int32]
	NZCV_3 = cond((real96) fp0_2 - Mem0[a6 + 0x00000008:real96])
	branch (real96) fp0_2 == Mem0[a6 + 0x00000008:real96] l1
	// succ:  l2 l1
l2:
	return
	// succ:  FCmpFragment_exit
FCmpFragment_exit:
