= fn0C00_0000 ========================
fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
eax:eax
    def:  def eax
    uses: eax_4 = -eax
eax_4: orig: eax
    def:  eax_4 = -eax
    uses: SCZO_5 = cond(eax_4)
          C_6 = eax_4 == 0x00000000
          eax_7 = eax_4 - eax_4 - (eax_4 == 0x00000000)
          eax_7 = eax_4 - eax_4 - (eax_4 == 0x00000000)
          eax_7 = eax_4 - eax_4 - (eax_4 == 0x00000000)
SCZO_5: orig: SCZO
    def:  SCZO_5 = cond(eax_4)
C_6: orig: C
    def:  C_6 = eax_4 == 0x00000000
eax_7: orig: eax
    def:  eax_7 = eax_4 - eax_4 - (eax_4 == 0x00000000)
    uses: SCZO_8 = cond(eax_7)
          Mem10[ds:0x0300:word32] = eax_7
SCZO_8: orig: SCZO
    def:  SCZO_8 = cond(eax_7)
ds:ds
    def:  def ds
    uses: Mem10[ds:0x0300:word32] = eax_7
          v7_11 = -Mem10[ds:0x0202:word16]
          Mem12[ds:0x0202:word16] = v7_11
          v8_15 = -Mem12[ds:0x0200:word16]
          Mem16[ds:0x0200:word16] = v8_15
          Mem22[ds:0x0308:word32] = ecx_20
          Mem25[ds:0x0304:word16] = bx_24
          v11_26 = ~Mem25[ds:0x0204:word16]
          Mem27[ds:0x0204:word16] = v11_26
          cx_28 = Mem27[ds:0x0304:word16]
          Mem37[ds:0x0306:word16] = cx_34
Mem10: orig: Mem0
    def:  Mem10[ds:0x0300:word32] = eax_7
    uses: v7_11 = -Mem10[ds:0x0202:word16]
v7_11: orig: v7
    def:  v7_11 = -Mem10[ds:0x0202:word16]
    uses: Mem12[ds:0x0202:word16] = v7_11
          SCZO_13 = cond(v7_11)
          C_14 = v7_11 == 0x0000
Mem12: orig: Mem0
    def:  Mem12[ds:0x0202:word16] = v7_11
    uses: v8_15 = -Mem12[ds:0x0200:word16]
SCZO_13: orig: SCZO
    def:  SCZO_13 = cond(v7_11)
C_14: orig: C
    def:  C_14 = v7_11 == 0x0000
v8_15: orig: v8
    def:  v8_15 = -Mem12[ds:0x0200:word16]
    uses: Mem16[ds:0x0200:word16] = v8_15
          SCZO_17 = cond(v8_15)
          C_18 = v8_15 == 0x0000
          ecx_20 = ecx - ecx - (v8_15 == 0x0000)
Mem16: orig: Mem0
    def:  Mem16[ds:0x0200:word16] = v8_15
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(v8_15)
C_18: orig: C
    def:  C_18 = v8_15 == 0x0000
ecx:ecx
    def:  def ecx
    uses: ecx_20 = ecx - ecx - (v8_15 == 0x0000)
          ecx_20 = ecx - ecx - (v8_15 == 0x0000)
ecx_20: orig: ecx
    def:  ecx_20 = ecx - ecx - (v8_15 == 0x0000)
    uses: SCZO_21 = cond(ecx_20)
          Mem22[ds:0x0308:word32] = ecx_20
          ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
SCZO_21: orig: SCZO
    def:  SCZO_21 = cond(ecx_20)
Mem22: orig: Mem0
    def:  Mem22[ds:0x0308:word32] = ecx_20
bx:bx
    def:  def bx
    uses: bx_24 = ~bx
bx_24: orig: bx
    def:  bx_24 = ~bx
    uses: Mem25[ds:0x0304:word16] = bx_24
Mem25: orig: Mem0
    def:  Mem25[ds:0x0304:word16] = bx_24
    uses: v11_26 = ~Mem25[ds:0x0204:word16]
v11_26: orig: v11
    def:  v11_26 = ~Mem25[ds:0x0204:word16]
    uses: Mem27[ds:0x0204:word16] = v11_26
Mem27: orig: Mem0
    def:  Mem27[ds:0x0204:word16] = v11_26
    uses: cx_28 = Mem27[ds:0x0304:word16]
cx_28: orig: cx
    def:  cx_28 = Mem27[ds:0x0304:word16]
    uses: cx_30 = cx_28 - 0x03E8
          cx_31 = DPB(cx_28, cx_30, 0) (alias)
ecx_29: orig: ecx
    def:  ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
cx_30: orig: cx
    def:  cx_30 = cx_28 - 0x03E8
cx_31: orig: cx
    def:  cx_31 = DPB(cx_28, cx_30, 0) (alias)
    uses: SCZO_32 = cond(cx_31)
          cx_33 = -cx_31
          cx_34 = DPB(cx_31, cx_33, 0) (alias)
SCZO_32: orig: SCZO
    def:  SCZO_32 = cond(cx_31)
cx_33: orig: cx
    def:  cx_33 = -cx_31
cx_34: orig: cx
    def:  cx_34 = DPB(cx_31, cx_33, 0) (alias)
    uses: SCZO_35 = cond(cx_34)
          C_36 = cx_34 == 0x0000
          Mem37[ds:0x0306:word16] = cx_34
SCZO_35: orig: SCZO
    def:  SCZO_35 = cond(cx_34)
C_36: orig: C
    def:  C_36 = cx_34 == 0x0000
Mem37: orig: Mem0
    def:  Mem37[ds:0x0306:word16] = cx_34
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def ecx
	def bx
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	eax_4 = -eax
	SCZO_5 = cond(eax_4)
	C_6 = eax_4 == 0x00000000
	eax_7 = eax_4 - eax_4 - (eax_4 == 0x00000000)
	SCZO_8 = cond(eax_7)
	Mem10[ds:0x0300:word32] = eax_7
	v7_11 = -Mem10[ds:0x0202:word16]
	Mem12[ds:0x0202:word16] = v7_11
	SCZO_13 = cond(v7_11)
	C_14 = v7_11 == 0x0000
	v8_15 = -Mem12[ds:0x0200:word16]
	Mem16[ds:0x0200:word16] = v8_15
	SCZO_17 = cond(v8_15)
	C_18 = v8_15 == 0x0000
	ecx_20 = ecx - ecx - (v8_15 == 0x0000)
	SCZO_21 = cond(ecx_20)
	Mem22[ds:0x0308:word32] = ecx_20
	bx_24 = ~bx
	Mem25[ds:0x0304:word16] = bx_24
	v11_26 = ~Mem25[ds:0x0204:word16]
	Mem27[ds:0x0204:word16] = v11_26
	cx_28 = Mem27[ds:0x0304:word16]
	ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
	cx_30 = cx_28 - 0x03E8
	cx_31 = DPB(cx_28, cx_30, 0) (alias)
	SCZO_32 = cond(cx_31)
	cx_33 = -cx_31
	cx_34 = DPB(cx_31, cx_33, 0) (alias)
	SCZO_35 = cond(cx_34)
	C_36 = cx_34 == 0x0000
	Mem37[ds:0x0306:word16] = cx_34
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
eax:eax
    def:  def eax
    uses: eax_4 = -eax
eax_4: orig: eax
    def:  eax_4 = -eax
    uses: SCZO_5 = cond(eax_4)
          C_6 = eax_4 == 0x00000000
          eax_7 = 0x00000000 - (eax_4 == 0x00000000)
SCZO_5: orig: SCZO
    def:  SCZO_5 = cond(eax_4)
C_6: orig: C
    def:  C_6 = eax_4 == 0x00000000
eax_7: orig: eax
    def:  eax_7 = 0x00000000 - (eax_4 == 0x00000000)
    uses: SCZO_8 = cond(eax_7)
          Mem10[ds:0x0300:word32] = eax_7
SCZO_8: orig: SCZO
    def:  SCZO_8 = cond(eax_7)
ds:ds
    def:  def ds
    uses: Mem10[ds:0x0300:word32] = eax_7
          v7_11 = -Mem10[ds:0x0202:word16]
          Mem12[ds:0x0202:word16] = v7_11
          v8_15 = -Mem12[ds:0x0200:word16]
          Mem16[ds:0x0200:word16] = v8_15
          Mem22[ds:0x0308:word32] = ecx_20
          Mem25[ds:0x0304:word16] = bx_24
          v11_26 = ~Mem25[ds:0x0204:word16]
          Mem27[ds:0x0204:word16] = v11_26
          cx_28 = Mem27[ds:0x0304:word16]
          Mem37[ds:0x0306:word16] = cx_34
Mem10: orig: Mem0
    def:  Mem10[ds:0x0300:word32] = eax_7
    uses: v7_11 = -Mem10[ds:0x0202:word16]
v7_11: orig: v7
    def:  v7_11 = -Mem10[ds:0x0202:word16]
    uses: Mem12[ds:0x0202:word16] = v7_11
          SCZO_13 = cond(v7_11)
          C_14 = v7_11 == 0x0000
Mem12: orig: Mem0
    def:  Mem12[ds:0x0202:word16] = v7_11
    uses: v8_15 = -Mem12[ds:0x0200:word16]
SCZO_13: orig: SCZO
    def:  SCZO_13 = cond(v7_11)
C_14: orig: C
    def:  C_14 = v7_11 == 0x0000
v8_15: orig: v8
    def:  v8_15 = -Mem12[ds:0x0200:word16]
    uses: Mem16[ds:0x0200:word16] = v8_15
          SCZO_17 = cond(v8_15)
          C_18 = v8_15 == 0x0000
          ecx_20 = 0x00000000 - (v8_15 == 0x0000)
Mem16: orig: Mem0
    def:  Mem16[ds:0x0200:word16] = v8_15
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(v8_15)
C_18: orig: C
    def:  C_18 = v8_15 == 0x0000
ecx:ecx
    def:  def ecx
ecx_20: orig: ecx
    def:  ecx_20 = 0x00000000 - (v8_15 == 0x0000)
    uses: SCZO_21 = cond(ecx_20)
          Mem22[ds:0x0308:word32] = ecx_20
          ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
SCZO_21: orig: SCZO
    def:  SCZO_21 = cond(ecx_20)
Mem22: orig: Mem0
    def:  Mem22[ds:0x0308:word32] = ecx_20
bx:bx
    def:  def bx
    uses: bx_24 = ~bx
bx_24: orig: bx
    def:  bx_24 = ~bx
    uses: Mem25[ds:0x0304:word16] = bx_24
Mem25: orig: Mem0
    def:  Mem25[ds:0x0304:word16] = bx_24
    uses: v11_26 = ~Mem25[ds:0x0204:word16]
v11_26: orig: v11
    def:  v11_26 = ~Mem25[ds:0x0204:word16]
    uses: Mem27[ds:0x0204:word16] = v11_26
Mem27: orig: Mem0
    def:  Mem27[ds:0x0204:word16] = v11_26
    uses: cx_28 = Mem27[ds:0x0304:word16]
cx_28: orig: cx
    def:  cx_28 = Mem27[ds:0x0304:word16]
    uses: cx_30 = cx_28 - 0x03E8
          cx_31 = DPB(cx_28, cx_28 - 0x03E8, 0) (alias)
          cx_31 = DPB(cx_28, cx_28 - 0x03E8, 0) (alias)
          cx_34 = DPB(cx_28, cx_33, 0) (alias)
ecx_29: orig: ecx
    def:  ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
cx_30: orig: cx
    def:  cx_30 = cx_28 - 0x03E8
cx_31: orig: cx
    def:  cx_31 = DPB(cx_28, cx_28 - 0x03E8, 0) (alias)
    uses: SCZO_32 = cond(cx_31)
          cx_33 = -cx_31
SCZO_32: orig: SCZO
    def:  SCZO_32 = cond(cx_31)
cx_33: orig: cx
    def:  cx_33 = -cx_31
cx_34: orig: cx
    def:  cx_34 = DPB(cx_28, cx_33, 0) (alias)
    uses: SCZO_35 = cond(cx_34)
          C_36 = cx_34 == 0x0000
          Mem37[ds:0x0306:word16] = cx_34
SCZO_35: orig: SCZO
    def:  SCZO_35 = cond(cx_34)
C_36: orig: C
    def:  C_36 = cx_34 == 0x0000
Mem37: orig: Mem0
    def:  Mem37[ds:0x0306:word16] = cx_34
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def ecx
	def bx
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	eax_4 = -eax
	SCZO_5 = cond(eax_4)
	C_6 = eax_4 == 0x00000000
	eax_7 = 0x00000000 - (eax_4 == 0x00000000)
	SCZO_8 = cond(eax_7)
	Mem10[ds:0x0300:word32] = eax_7
	v7_11 = -Mem10[ds:0x0202:word16]
	Mem12[ds:0x0202:word16] = v7_11
	SCZO_13 = cond(v7_11)
	C_14 = v7_11 == 0x0000
	v8_15 = -Mem12[ds:0x0200:word16]
	Mem16[ds:0x0200:word16] = v8_15
	SCZO_17 = cond(v8_15)
	C_18 = v8_15 == 0x0000
	ecx_20 = 0x00000000 - (v8_15 == 0x0000)
	SCZO_21 = cond(ecx_20)
	Mem22[ds:0x0308:word32] = ecx_20
	bx_24 = ~bx
	Mem25[ds:0x0304:word16] = bx_24
	v11_26 = ~Mem25[ds:0x0204:word16]
	Mem27[ds:0x0204:word16] = v11_26
	cx_28 = Mem27[ds:0x0304:word16]
	ecx_29 = DPB(ecx_20, cx_28, 0) (alias)
	cx_30 = cx_28 - 0x03E8
	cx_31 = DPB(cx_28, cx_28 - 0x03E8, 0) (alias)
	SCZO_32 = cond(cx_31)
	cx_33 = -cx_31
	cx_34 = DPB(cx_28, cx_33, 0) (alias)
	SCZO_35 = cond(cx_34)
	C_36 = cx_34 == 0x0000
	Mem37[ds:0x0306:word16] = cx_34
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
