= fn0C00_0000 ========================
fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
    uses: call fn0C00_0004 (retsize: 2;)	uses: sp:sp_2	defs: sp:sp_4
Top_3: orig: Top
    def:  Top_3 = 0x00
sp_4: orig: sp
    def:  call fn0C00_0004 (retsize: 2;)	uses: sp:sp_2	defs: sp:sp_4
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	Top_3 = 0x00
	call fn0C00_0004 (retsize: 2;)
		uses: sp:sp_2
		defs: sp:sp_4
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_2 = fp
          call fn0C00_0004 (retsize: 2;)	uses: sp:fp	defs: sp:sp_4
sp_2: orig: sp
    def:  sp_2 = fp
Top_3: orig: Top
    def:  Top_3 = 0x00
sp_4: orig: sp
    def:  call fn0C00_0004 (retsize: 2;)	uses: sp:fp	defs: sp:sp_4
// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	def fp
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	Top_3 = 0x00
	call fn0C00_0004 (retsize: 2;)
		uses: sp:fp
		defs: sp:sp_4
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
= fn0C00_0004 ========================
fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
Top_3: orig: Top
    def:  Top_3 = 0x00
ax_4: orig: ax
    def:  ax_4 = 0x4DE1
    uses: es_5 = ax_4
es_5: orig: es
    def:  es_5 = ax_4
    uses: Mem38[es_5:bx_37:byte] = al_32
bx_6: orig: bx
    def:  bx_6 = 0x0FFF
    uses: bh_42 = SLICE(bx_6, byte, 8) (alias)
          bl_44 = (byte) bx_6 (alias)
          bx_36 = PHI(bx_6, bx_39)
bh_7: orig: bh
    def:  bh_7 = PHI(bh_42, bh_43)
    uses: al_8 = bh_7
al_8: orig: al
    def:  al_8 = bh_7
    uses: al_9 = al_8 + 0x01
al_9: orig: al
    def:  al_9 = al_8 + 0x01
    uses: SZO_10 = cond(al_9)
          ax_16 = ah_13 *u al_9
SZO_10: orig: SZO
    def:  SZO_10 = cond(al_9)
bl_11: orig: bl
    def:  bl_11 = PHI(bl_44, bl_45)
    uses: ah_12 = bl_11
          al_20 = bl_11
          bx_37 = DPB(bx_36, bl_11, 0) (alias)
ah_12: orig: ah
    def:  ah_12 = bl_11
    uses: ah_13 = ah_12 & 0x0F
ah_13: orig: ah
    def:  ah_13 = ah_12 & 0x0F
    uses: SZO_14 = cond(ah_13)
          ax_16 = ah_13 *u al_9
SZO_14: orig: SZO
    def:  SZO_14 = cond(ah_13)
C_15: orig: C
    def:  C_15 = false
ax_16: orig: ax
    def:  ax_16 = ah_13 *u al_9
    uses: SCZO_17 = cond(ax_16)
          ax_18 = ax_16 << 0x0004
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(ax_16)
ax_18: orig: ax
    def:  ax_18 = ax_16 << 0x0004
    uses: SCZO_19 = cond(ax_18)
          ax_21 = DPB(ax_18, al_20, 0) (alias)
SCZO_19: orig: SCZO
    def:  SCZO_19 = cond(ax_18)
al_20: orig: al
    def:  al_20 = bl_11
    uses: al_22 = al_20 & 0xF0
          al_23 = DPB(al_20, al_22, 0) (alias)
          al_31 = al_20 | ah_28
          al_32 = DPB(al_20, al_31, 0) (alias)
ax_21: orig: ax
    def:  ax_21 = DPB(ax_18, al_20, 0) (alias)
    uses: ah_26 = SLICE(ax_21, byte, 8) (alias)
al_22: orig: al
    def:  al_22 = al_20 & 0xF0
al_23: orig: al
    def:  al_23 = DPB(al_20, al_22, 0) (alias)
    uses: SZO_24 = cond(al_23)
SZO_24: orig: SZO
    def:  SZO_24 = cond(al_23)
C_25: orig: C
    def:  C_25 = false
ah_26: orig: ah
    def:  ah_26 = SLICE(ax_21, byte, 8) (alias)
    uses: ah_27 = ah_26 & 0x0F
          ah_28 = DPB(ah_26, ah_27, 8) (alias)
ah_27: orig: ah
    def:  ah_27 = ah_26 & 0x0F
ah_28: orig: ah
    def:  ah_28 = DPB(ah_26, ah_27, 8) (alias)
    uses: SZO_29 = cond(ah_28)
          al_31 = al_20 | ah_28
SZO_29: orig: SZO
    def:  SZO_29 = cond(ah_28)
C_30: orig: C
    def:  C_30 = false
al_31: orig: al
    def:  al_31 = al_20 | ah_28
al_32: orig: al
    def:  al_32 = DPB(al_20, al_31, 0) (alias)
    uses: SZO_33 = cond(al_32)
          Mem38[es_5:bx_37:byte] = al_32
SZO_33: orig: SZO
    def:  SZO_33 = cond(al_32)
C_34: orig: C
    def:  C_34 = false
es_35: orig: es
    def:  es_35 = PHI(es_5, es_35)
bx_36: orig: bx
    def:  bx_36 = PHI(bx_6, bx_39)
    uses: bx_37 = DPB(bx_36, bl_11, 0) (alias)
bx_37: orig: bx
    def:  bx_37 = DPB(bx_36, bl_11, 0) (alias)
    uses: Mem38[es_5:bx_37:byte] = al_32
          bx_39 = bx_37 - 0x0001
Mem38: orig: Mem0
    def:  Mem38[es_5:bx_37:byte] = al_32
bx_39: orig: bx
    def:  bx_39 = bx_37 - 0x0001
    uses: SZO_40 = cond(bx_39)
          bh_43 = SLICE(bx_39, byte, 8) (alias)
          bl_45 = (byte) bx_39 (alias)
          bx_36 = PHI(bx_6, bx_39)
          branch bx_39 >= 0x0000 l0C00_000C
SZO_40: orig: SZO
    def:  SZO_40 = cond(bx_39)
    uses: S_41 = SLICE(SZO_40, bool, 0) (alias)
S_41: orig: S
    def:  S_41 = SLICE(SZO_40, bool, 0) (alias)
bh_42: orig: bh
    def:  bh_42 = SLICE(bx_6, byte, 8) (alias)
    uses: bh_7 = PHI(bh_42, bh_43)
bh_43: orig: bh
    def:  bh_43 = SLICE(bx_39, byte, 8) (alias)
    uses: bh_7 = PHI(bh_42, bh_43)
bl_44: orig: bl
    def:  bl_44 = (byte) bx_6 (alias)
    uses: bl_11 = PHI(bl_44, bl_45)
bl_45: orig: bl
    def:  bl_45 = (byte) bx_39 (alias)
    uses: bl_11 = PHI(bl_44, bl_45)
// fn0C00_0004
// Return size: 2
define fn0C00_0004
fn0C00_0004_entry:
	def fp
	// succ:  l0C00_0004
l0C00_0004:
	sp_2 = fp
	Top_3 = 0x00
	ax_4 = 0x4DE1
	es_5 = ax_4
	bx_6 = 0x0FFF
	bh_42 = SLICE(bx_6, byte, 8) (alias)
	bl_44 = (byte) bx_6 (alias)
	// succ:  l0C00_000C
l0C00_000C:
	bx_36 = PHI(bx_6, bx_39)
	bl_11 = PHI(bl_44, bl_45)
	bx_37 = DPB(bx_36, bl_11, 0) (alias)
	bh_7 = PHI(bh_42, bh_43)
	al_8 = bh_7
	al_9 = al_8 + 0x01
	SZO_10 = cond(al_9)
	ah_12 = bl_11
	ah_13 = ah_12 & 0x0F
	SZO_14 = cond(ah_13)
	C_15 = false
	ax_16 = ah_13 *u al_9
	SCZO_17 = cond(ax_16)
	ax_18 = ax_16 << 0x0004
	SCZO_19 = cond(ax_18)
	al_20 = bl_11
	ax_21 = DPB(ax_18, al_20, 0) (alias)
	ah_26 = SLICE(ax_21, byte, 8) (alias)
	al_22 = al_20 & 0xF0
	al_23 = DPB(al_20, al_22, 0) (alias)
	SZO_24 = cond(al_23)
	C_25 = false
	ah_27 = ah_26 & 0x0F
	ah_28 = DPB(ah_26, ah_27, 8) (alias)
	SZO_29 = cond(ah_28)
	C_30 = false
	al_31 = al_20 | ah_28
	al_32 = DPB(al_20, al_31, 0) (alias)
	SZO_33 = cond(al_32)
	C_34 = false
	Mem38[es_5:bx_37:byte] = al_32
	bx_39 = bx_37 - 0x0001
	bh_43 = SLICE(bx_39, byte, 8) (alias)
	bl_45 = (byte) bx_39 (alias)
	SZO_40 = cond(bx_39)
	S_41 = SLICE(SZO_40, bool, 0) (alias)
	branch bx_39 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
Top_3: orig: Top
    def:  Top_3 = 0x00
ax_4: orig: ax
    def:  ax_4 = 0x4DE1
es_5: orig: es
    def:  es_5 = 0x4DE1
bx_6: orig: bx
    def:  bx_6 = 0x0FFF
    uses: bx_36 = PHI(bx_6, bx_39)
bh_7: orig: bh
    def:  bh_7 = PHI(bh_42, bh_43)
    uses: al_8 = bh_7
          al_9 = bh_7 + 0x01
al_8: orig: al
    def:  al_8 = bh_7
al_9: orig: al
    def:  al_9 = bh_7 + 0x01
    uses: SZO_10 = cond(al_9)
          ax_16 = ah_13 *u al_9
SZO_10: orig: SZO
    def:  SZO_10 = cond(al_9)
bl_11: orig: bl
    def:  bl_11 = PHI(bl_44, bl_45)
    uses: ah_12 = bl_11
          al_20 = bl_11
          bx_37 = DPB(bx_36, bl_11, 0) (alias)
          ah_13 = bl_11 & 0x0F
          ax_21 = DPB(ax_16 << 0x0004, bl_11, 0) (alias)
          al_22 = bl_11 & 0xF0
          al_23 = DPB(bl_11, al_22, 0) (alias)
          al_31 = bl_11 | ah_28
          al_32 = DPB(bl_11, al_31, 0) (alias)
ah_12: orig: ah
    def:  ah_12 = bl_11
ah_13: orig: ah
    def:  ah_13 = bl_11 & 0x0F
    uses: SZO_14 = cond(ah_13)
          ax_16 = ah_13 *u al_9
SZO_14: orig: SZO
    def:  SZO_14 = cond(ah_13)
C_15: orig: C
    def:  C_15 = false
ax_16: orig: ax
    def:  ax_16 = ah_13 *u al_9
    uses: SCZO_17 = cond(ax_16)
          ax_18 = ax_16 << 0x0004
          SCZO_19 = cond(ax_16 << 0x0004)
          ax_21 = DPB(ax_16 << 0x0004, bl_11, 0) (alias)
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(ax_16)
ax_18: orig: ax
    def:  ax_18 = ax_16 << 0x0004
SCZO_19: orig: SCZO
    def:  SCZO_19 = cond(ax_16 << 0x0004)
al_20: orig: al
    def:  al_20 = bl_11
ax_21: orig: ax
    def:  ax_21 = DPB(ax_16 << 0x0004, bl_11, 0) (alias)
    uses: ah_26 = SLICE(ax_21, byte, 8) (alias)
al_22: orig: al
    def:  al_22 = bl_11 & 0xF0
al_23: orig: al
    def:  al_23 = DPB(bl_11, al_22, 0) (alias)
    uses: SZO_24 = cond(al_23)
SZO_24: orig: SZO
    def:  SZO_24 = cond(al_23)
C_25: orig: C
    def:  C_25 = false
ah_26: orig: ah
    def:  ah_26 = SLICE(ax_21, byte, 8) (alias)
    uses: ah_27 = ah_26 & 0x0F
          ah_28 = DPB(ah_26, ah_26 & 0x0F, 8) (alias)
          ah_28 = DPB(ah_26, ah_26 & 0x0F, 8) (alias)
ah_27: orig: ah
    def:  ah_27 = ah_26 & 0x0F
ah_28: orig: ah
    def:  ah_28 = DPB(ah_26, ah_26 & 0x0F, 8) (alias)
    uses: SZO_29 = cond(ah_28)
          al_31 = bl_11 | ah_28
SZO_29: orig: SZO
    def:  SZO_29 = cond(ah_28)
C_30: orig: C
    def:  C_30 = false
al_31: orig: al
    def:  al_31 = bl_11 | ah_28
al_32: orig: al
    def:  al_32 = DPB(bl_11, al_31, 0) (alias)
    uses: SZO_33 = cond(al_32)
          Mem38[0x4DE1:bx_37:byte] = al_32
SZO_33: orig: SZO
    def:  SZO_33 = cond(al_32)
C_34: orig: C
    def:  C_34 = false
es_35: orig: es
    def:  es_35 = PHI(es_5, es_35)
bx_36: orig: bx
    def:  bx_36 = PHI(bx_6, bx_39)
    uses: bx_37 = DPB(bx_36, bl_11, 0) (alias)
bx_37: orig: bx
    def:  bx_37 = DPB(bx_36, bl_11, 0) (alias)
    uses: Mem38[0x4DE1:bx_37:byte] = al_32
          bx_39 = bx_37 - 0x0001
          bh_43 = SLICE(bx_37 - 0x0001, byte, 8) (alias)
          bl_45 = (byte) (bx_37 - 0x0001) (alias)
          SZO_40 = cond(bx_37 - 0x0001)
          branch bx_37 >= 0x0001 l0C00_000C
Mem38: orig: Mem0
    def:  Mem38[0x4DE1:bx_37:byte] = al_32
bx_39: orig: bx
    def:  bx_39 = bx_37 - 0x0001
    uses: bx_36 = PHI(bx_6, bx_39)
SZO_40: orig: SZO
    def:  SZO_40 = cond(bx_37 - 0x0001)
    uses: S_41 = SLICE(SZO_40, bool, 0) (alias)
S_41: orig: S
    def:  S_41 = SLICE(SZO_40, bool, 0) (alias)
bh_42: orig: bh
    def:  bh_42 = 0x0F (alias)
    uses: bh_7 = PHI(bh_42, bh_43)
bh_43: orig: bh
    def:  bh_43 = SLICE(bx_37 - 0x0001, byte, 8) (alias)
    uses: bh_7 = PHI(bh_42, bh_43)
bl_44: orig: bl
    def:  bl_44 = 0xFF (alias)
    uses: bl_11 = PHI(bl_44, bl_45)
bl_45: orig: bl
    def:  bl_45 = (byte) (bx_37 - 0x0001) (alias)
    uses: bl_11 = PHI(bl_44, bl_45)
// fn0C00_0004
// Return size: 2
define fn0C00_0004
fn0C00_0004_entry:
	def fp
	// succ:  l0C00_0004
l0C00_0004:
	sp_2 = fp
	Top_3 = 0x00
	ax_4 = 0x4DE1
	es_5 = 0x4DE1
	bx_6 = 0x0FFF
	bh_42 = 0x0F (alias)
	bl_44 = 0xFF (alias)
	// succ:  l0C00_000C
l0C00_000C:
	bx_36 = PHI(bx_6, bx_39)
	bl_11 = PHI(bl_44, bl_45)
	bx_37 = DPB(bx_36, bl_11, 0) (alias)
	bh_7 = PHI(bh_42, bh_43)
	al_8 = bh_7
	al_9 = bh_7 + 0x01
	SZO_10 = cond(al_9)
	ah_12 = bl_11
	ah_13 = bl_11 & 0x0F
	SZO_14 = cond(ah_13)
	C_15 = false
	ax_16 = ah_13 *u al_9
	SCZO_17 = cond(ax_16)
	ax_18 = ax_16 << 0x0004
	SCZO_19 = cond(ax_16 << 0x0004)
	al_20 = bl_11
	ax_21 = DPB(ax_16 << 0x0004, bl_11, 0) (alias)
	ah_26 = SLICE(ax_21, byte, 8) (alias)
	al_22 = bl_11 & 0xF0
	al_23 = DPB(bl_11, al_22, 0) (alias)
	SZO_24 = cond(al_23)
	C_25 = false
	ah_27 = ah_26 & 0x0F
	ah_28 = DPB(ah_26, ah_26 & 0x0F, 8) (alias)
	SZO_29 = cond(ah_28)
	C_30 = false
	al_31 = bl_11 | ah_28
	al_32 = DPB(bl_11, al_31, 0) (alias)
	SZO_33 = cond(al_32)
	C_34 = false
	Mem38[0x4DE1:bx_37:byte] = al_32
	bx_39 = bx_37 - 0x0001
	bh_43 = SLICE(bx_37 - 0x0001, byte, 8) (alias)
	bl_45 = (byte) (bx_37 - 0x0001) (alias)
	SZO_40 = cond(bx_37 - 0x0001)
	S_41 = SLICE(SZO_40, bool, 0) (alias)
	branch bx_37 >= 0x0001 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:
