= fn0C00_0000 ========================
fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
eax:eax
    def:  def eax
    uses: eax_4 = eax + eax * 0x00000004
          eax_4 = eax + eax * 0x00000004
eax_4: orig: eax
    def:  eax_4 = eax + eax * 0x00000004
    uses: Mem6[ds:0x02FC:word32] = eax_4
ds:ds
    def:  def ds
    uses: Mem6[ds:0x02FC:word32] = eax_4
          eax_8 = Mem6[ds:si:word32]
          Mem10[ds:0x0300:word32] = eax_8
          eax_11 = Mem10[ds:si_9:word32]
          Mem13[ds:0x0304:word32] = eax_11
          ax_14 = Mem13[ds:si_12:word16]
          Mem17[ds:0x0308:word16] = ax_14
          ax_18 = Mem17[ds:si_16:word16]
          Mem21[ds:0x030A:word16] = ax_19
          fn0C00_0026(es, ds)
Mem6: orig: Mem0
    def:  Mem6[ds:0x02FC:word32] = eax_4
    uses: eax_8 = Mem6[ds:si:word32]
si:si
    def:  def si
    uses: eax_8 = Mem6[ds:si:word32]
          si_9 = si + 0x0004
eax_8: orig: eax
    def:  eax_8 = Mem6[ds:si:word32]
    uses: Mem10[ds:0x0300:word32] = eax_8
si_9: orig: si
    def:  si_9 = si + 0x0004
    uses: eax_11 = Mem10[ds:si_9:word32]
          si_12 = si_9 + 0x0004
Mem10: orig: Mem0
    def:  Mem10[ds:0x0300:word32] = eax_8
    uses: eax_11 = Mem10[ds:si_9:word32]
eax_11: orig: eax
    def:  eax_11 = Mem10[ds:si_9:word32]
    uses: Mem13[ds:0x0304:word32] = eax_11
          eax_15 = DPB(eax_11, ax_14, 0) (alias)
si_12: orig: si
    def:  si_12 = si_9 + 0x0004
    uses: ax_14 = Mem13[ds:si_12:word16]
          si_16 = si_12 + 0x0002
Mem13: orig: Mem0
    def:  Mem13[ds:0x0304:word32] = eax_11
    uses: ax_14 = Mem13[ds:si_12:word16]
ax_14: orig: ax
    def:  ax_14 = Mem13[ds:si_12:word16]
    uses: Mem17[ds:0x0308:word16] = ax_14
          ax_19 = DPB(ax_14, ax_18, 0) (alias)
eax_15: orig: eax
    def:  eax_15 = DPB(eax_11, ax_14, 0) (alias)
si_16: orig: si
    def:  si_16 = si_12 + 0x0002
    uses: ax_18 = Mem17[ds:si_16:word16]
          si_20 = si_16 + 0x0002
Mem17: orig: Mem0
    def:  Mem17[ds:0x0308:word16] = ax_14
    uses: ax_18 = Mem17[ds:si_16:word16]
ax_18: orig: ax
    def:  ax_18 = Mem17[ds:si_16:word16]
ax_19: orig: ax
    def:  ax_19 = DPB(ax_14, ax_18, 0) (alias)
    uses: Mem21[ds:0x030A:word16] = ax_19
si_20: orig: si
    def:  si_20 = si_16 + 0x0002
Mem21: orig: Mem0
    def:  Mem21[ds:0x030A:word16] = ax_19
es:es
    def:  def es
    uses: fn0C00_0026(es, ds)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word32 eax, word16 si, selector es, selector ds)
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def si
	def es
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	eax_4 = eax + eax * 0x00000004
	Mem6[ds:0x02FC:word32] = eax_4
	eax_8 = Mem6[ds:si:word32]
	si_9 = si + 0x0004
	Mem10[ds:0x0300:word32] = eax_8
	eax_11 = Mem10[ds:si_9:word32]
	si_12 = si_9 + 0x0004
	Mem13[ds:0x0304:word32] = eax_11
	ax_14 = Mem13[ds:si_12:word16]
	eax_15 = DPB(eax_11, ax_14, 0) (alias)
	si_16 = si_12 + 0x0002
	Mem17[ds:0x0308:word16] = ax_14
	ax_18 = Mem17[ds:si_16:word16]
	ax_19 = DPB(ax_14, ax_18, 0) (alias)
	si_20 = si_16 + 0x0002
	Mem21[ds:0x030A:word16] = ax_19
	fn0C00_0026(es, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
eax:eax
    def:  def eax
    uses: eax_4 = eax * 0x00000005
          Mem6[ds:0x02FC:word32] = eax * 0x00000005
eax_4: orig: eax
    def:  eax_4 = eax * 0x00000005
ds:ds
    def:  def ds
    uses: Mem6[ds:0x02FC:word32] = eax * 0x00000005
          eax_8 = Mem6[ds:si:word32]
          Mem10[ds:0x0300:word32] = eax_8
          eax_11 = Mem10[ds:si + 0x0004:word32]
          Mem13[ds:0x0304:word32] = eax_11
          ax_14 = Mem13[ds:si + 0x0008:word16]
          Mem17[ds:0x0308:word16] = ax_14
          ax_18 = Mem17[ds:si + 0x000A:word16]
          Mem21[ds:0x030A:word16] = ax_19
          fn0C00_0026(es, ds)
Mem6: orig: Mem0
    def:  Mem6[ds:0x02FC:word32] = eax * 0x00000005
    uses: eax_8 = Mem6[ds:si:word32]
si:si
    def:  def si
    uses: eax_8 = Mem6[ds:si:word32]
          si_9 = si + 0x0004
          eax_11 = Mem10[ds:si + 0x0004:word32]
          si_12 = si + 0x0008
          ax_14 = Mem13[ds:si + 0x0008:word16]
          si_16 = si + 0x000A
          ax_18 = Mem17[ds:si + 0x000A:word16]
          si_20 = si + 0x000C
eax_8: orig: eax
    def:  eax_8 = Mem6[ds:si:word32]
    uses: Mem10[ds:0x0300:word32] = eax_8
si_9: orig: si
    def:  si_9 = si + 0x0004
Mem10: orig: Mem0
    def:  Mem10[ds:0x0300:word32] = eax_8
    uses: eax_11 = Mem10[ds:si + 0x0004:word32]
eax_11: orig: eax
    def:  eax_11 = Mem10[ds:si + 0x0004:word32]
    uses: Mem13[ds:0x0304:word32] = eax_11
          eax_15 = DPB(eax_11, ax_14, 0) (alias)
si_12: orig: si
    def:  si_12 = si + 0x0008
Mem13: orig: Mem0
    def:  Mem13[ds:0x0304:word32] = eax_11
    uses: ax_14 = Mem13[ds:si + 0x0008:word16]
ax_14: orig: ax
    def:  ax_14 = Mem13[ds:si + 0x0008:word16]
    uses: Mem17[ds:0x0308:word16] = ax_14
          ax_19 = DPB(ax_14, ax_18, 0) (alias)
eax_15: orig: eax
    def:  eax_15 = DPB(eax_11, ax_14, 0) (alias)
si_16: orig: si
    def:  si_16 = si + 0x000A
Mem17: orig: Mem0
    def:  Mem17[ds:0x0308:word16] = ax_14
    uses: ax_18 = Mem17[ds:si + 0x000A:word16]
ax_18: orig: ax
    def:  ax_18 = Mem17[ds:si + 0x000A:word16]
ax_19: orig: ax
    def:  ax_19 = DPB(ax_14, ax_18, 0) (alias)
    uses: Mem21[ds:0x030A:word16] = ax_19
si_20: orig: si
    def:  si_20 = si + 0x000C
Mem21: orig: Mem0
    def:  Mem21[ds:0x030A:word16] = ax_19
es:es
    def:  def es
    uses: fn0C00_0026(es, ds)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word32 eax, word16 si, selector es, selector ds)
fn0C00_0000_entry:
	def fp
	def eax
	def ds
	def si
	def es
	// succ:  l0C00_0000
l0C00_0000:
	sp_2 = fp
	eax_4 = eax * 0x00000005
	Mem6[ds:0x02FC:word32] = eax * 0x00000005
	eax_8 = Mem6[ds:si:word32]
	si_9 = si + 0x0004
	Mem10[ds:0x0300:word32] = eax_8
	eax_11 = Mem10[ds:si + 0x0004:word32]
	si_12 = si + 0x0008
	Mem13[ds:0x0304:word32] = eax_11
	ax_14 = Mem13[ds:si + 0x0008:word16]
	eax_15 = DPB(eax_11, ax_14, 0) (alias)
	si_16 = si + 0x000A
	Mem17[ds:0x0308:word16] = ax_14
	ax_18 = Mem17[ds:si + 0x000A:word16]
	ax_19 = DPB(ax_14, ax_18, 0) (alias)
	si_20 = si + 0x000C
	Mem21[ds:0x030A:word16] = ax_19
	fn0C00_0026(es, ds)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
= fn0C00_0026 ========================
fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
ds:ds
    def:  def ds
    uses: cx_5 = Mem0[ds:0x0400:word16]
          di_7 = Mem0[ds:0x0402:word16]
          ds_16 = PHI(ds, ds_17)
Mem0:Global memory
    def:  def Mem0
    uses: cx_5 = Mem0[ds:0x0400:word16]
          di_7 = Mem0[ds:0x0402:word16]
          branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
cx_5: orig: cx
    def:  cx_5 = Mem0[ds:0x0400:word16]
    uses: cx_8 = PHI(cx_5, cx_14)
al_6: orig: al
    def:  al_6 = 0x00
di_7: orig: di
    def:  di_7 = Mem0[ds:0x0402:word16]
    uses: di_10 = PHI(di_7, di_13)
cx_8: orig: cx
    def:  cx_8 = PHI(cx_5, cx_14)
    uses: branch cx_8 == 0x0000 l0C00_0032
          cx_14 = cx_8 - 0x0001
es_9: orig: es
    def:  es_9 = PHI(es, es_9)
di_10: orig: di
    def:  di_10 = PHI(di_7, di_13)
    uses: SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
          di_13 = di_10 + 0x0001
          di_15 = PHI(di_10, di_13)
          branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
Mem11: orig: Mem0
    def:  Mem11 = PHI(Mem0, Mem11)
SCZO_12: orig: SCZO
    def:  SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
di_13: orig: di
    def:  di_13 = di_10 + 0x0001
    uses: di_15 = PHI(di_10, di_13)
          di_10 = PHI(di_7, di_13)
cx_14: orig: cx
    def:  cx_14 = cx_8 - 0x0001
    uses: cx_8 = PHI(cx_5, cx_14)
di_15: orig: di
    def:  di_15 = PHI(di_10, di_13)
    uses: Mem18[ds_16:0x0404:word16] = di_15
ds_16: orig: ds
    def:  ds_16 = PHI(ds, ds_17)
    uses: Mem18[ds_16:0x0404:word16] = di_15
ds_17: orig: ds
    def:  ds_17 = PHI(ds, ds_17)
    uses: ds_16 = PHI(ds, ds_17)
Mem18: orig: Mem0
    def:  Mem18[ds_16:0x0404:word16] = di_15
es:es
    def:  def es
    uses: branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
// fn0C00_0026
// Return size: 0
void fn0C00_0026(selector es, selector ds)
fn0C00_0026_entry:
	def fp
	def ds
	def Mem0
	def es
	// succ:  l0C00_0026
l0C00_0026:
	sp_2 = fp
	cx_5 = Mem0[ds:0x0400:word16]
	al_6 = 0x00
	di_7 = Mem0[ds:0x0402:word16]
	// succ:  l0C00_0030
l0C00_0030:
	di_10 = PHI(di_7, di_13)
	cx_8 = PHI(cx_5, cx_14)
	branch cx_8 == 0x0000 l0C00_0032
	// succ:  l0C00_0030_1 l0C00_0032
l0C00_0030_1:
	SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
	di_13 = di_10 + 0x0001
	cx_14 = cx_8 - 0x0001
	branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
	// succ:  l0C00_0032 l0C00_0030
l0C00_0032:
	ds_16 = PHI(ds, ds_17)
	di_15 = PHI(di_10, di_13)
	Mem18[ds_16:0x0404:word16] = di_15
	return
	// succ:  fn0C00_0026_exit
fn0C00_0026_exit:

fp:fp
    def:  def fp
    uses: sp_2 = fp
sp_2: orig: sp
    def:  sp_2 = fp
ds:ds
    def:  def ds
    uses: cx_5 = Mem0[ds:0x0400:word16]
          di_7 = Mem0[ds:0x0402:word16]
          ds_16 = PHI(ds, ds_17)
Mem0:Global memory
    def:  def Mem0
    uses: cx_5 = Mem0[ds:0x0400:word16]
          di_7 = Mem0[ds:0x0402:word16]
          branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
cx_5: orig: cx
    def:  cx_5 = Mem0[ds:0x0400:word16]
    uses: cx_8 = PHI(cx_5, cx_14)
al_6: orig: al
    def:  al_6 = 0x00
di_7: orig: di
    def:  di_7 = Mem0[ds:0x0402:word16]
    uses: di_10 = PHI(di_7, di_13)
cx_8: orig: cx
    def:  cx_8 = PHI(cx_5, cx_14)
    uses: branch cx_8 == 0x0000 l0C00_0032
          cx_14 = cx_8 - 0x0001
es_9: orig: es
    def:  es_9 = PHI(es, es_9)
di_10: orig: di
    def:  di_10 = PHI(di_7, di_13)
    uses: SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
          di_13 = di_10 + 0x0001
          di_15 = PHI(di_10, di_13)
          branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
Mem11: orig: Mem0
    def:  Mem11 = PHI(Mem0, Mem11)
SCZO_12: orig: SCZO
    def:  SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
di_13: orig: di
    def:  di_13 = di_10 + 0x0001
    uses: di_15 = PHI(di_10, di_13)
          di_10 = PHI(di_7, di_13)
cx_14: orig: cx
    def:  cx_14 = cx_8 - 0x0001
    uses: cx_8 = PHI(cx_5, cx_14)
di_15: orig: di
    def:  di_15 = PHI(di_10, di_13)
    uses: Mem18[ds_16:0x0404:word16] = di_15
ds_16: orig: ds
    def:  ds_16 = PHI(ds, ds_17)
    uses: Mem18[ds_16:0x0404:word16] = di_15
ds_17: orig: ds
    def:  ds_17 = PHI(ds, ds_17)
    uses: ds_16 = PHI(ds, ds_17)
Mem18: orig: Mem0
    def:  Mem18[ds_16:0x0404:word16] = di_15
es:es
    def:  def es
    uses: branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
// fn0C00_0026
// Return size: 0
void fn0C00_0026(selector es, selector ds)
fn0C00_0026_entry:
	def fp
	def ds
	def Mem0
	def es
	// succ:  l0C00_0026
l0C00_0026:
	sp_2 = fp
	cx_5 = Mem0[ds:0x0400:word16]
	al_6 = 0x00
	di_7 = Mem0[ds:0x0402:word16]
	// succ:  l0C00_0030
l0C00_0030:
	di_10 = PHI(di_7, di_13)
	cx_8 = PHI(cx_5, cx_14)
	branch cx_8 == 0x0000 l0C00_0032
	// succ:  l0C00_0030_1 l0C00_0032
l0C00_0030_1:
	SCZO_12 = cond(0x00 - Mem0[es:di_10:byte])
	di_13 = di_10 + 0x0001
	cx_14 = cx_8 - 0x0001
	branch 0x00 != Mem0[es:di_10:byte] l0C00_0030
	// succ:  l0C00_0032 l0C00_0030
l0C00_0032:
	ds_16 = PHI(ds, ds_17)
	di_15 = PHI(di_10, di_13)
	Mem18[ds_16:0x0404:word16] = di_15
	return
	// succ:  fn0C00_0026_exit
fn0C00_0026_exit:
