= fn0C00_0000 ========================
fp:fp
    def:  def fp
    uses: sp_1 = fp
sp_1: orig: sp
    def:  sp_1 = fp
si:si
    def:  def si
    uses: bx_3 = si
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
bx_3: orig: bx
    def:  bx_3 = si
    uses: ax_20 = ax_19 - bx_3
si_4: orig: si
    def:  si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
    uses: ax_7 = Mem0[ds:si_4:word16]
          si_8 = si_4 + 0x0002
ds:ds
    def:  def ds
    uses: ax_7 = Mem0[ds:si_4:word16]
          Mem18[ds:0x0300:word16] = ax_13
          Mem25[ds:di:word16] = ax_7
          v12_37 = Mem25[ds:0x0302:word16] + 0x0001
          Mem38[ds:0x0302:word16] = v12_37
Mem0:Global memory
    def:  def Mem0
    uses: ax_7 = Mem0[ds:si_4:word16]
ax_7: orig: ax
    def:  ax_7 = Mem0[ds:si_4:word16]
    uses: SCZO_9 = cond(ax_7 - 0x0020)
          Mem25[ds:di:word16] = ax_7
          ax_27 = ax_7 | ax_7
          ax_27 = ax_7 | ax_7
          branch ax_7 != 0x0020 l0C00_0005
si_8: orig: si
    def:  si_8 = si_4 + 0x0002
    uses: ax_19 = si_8
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
SCZO_9: orig: SCZO
    def:  SCZO_9 = cond(ax_7 - 0x0020)
    uses: Z_10 = (bool) SCZO_9 (alias)
          SZO_11 = SCZO_9 (alias)
          C_12 = (bool) SCZO_9 (alias)
          SCZO_31 = DPB(SCZO_9, C_30, 0) (alias)
Z_10: orig: Z
    def:  Z_10 = (bool) SCZO_9 (alias)
SZO_11: orig: SZO
    def:  SZO_11 = SCZO_9 (alias)
C_12: orig: C
    def:  C_12 = (bool) SCZO_9 (alias)
ax_13: orig: ax
    def:  ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
    uses: Mem18[ds:0x0300:word16] = ax_13
SCZO_14: orig: SCZO
    def:  SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
Z_15: orig: Z
    def:  Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
SZO_16: orig: SZO
    def:  SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
C_17: orig: C
    def:  C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
Mem18: orig: Mem0
    def:  Mem18[ds:0x0300:word16] = ax_13
ax_19: orig: ax
    def:  ax_19 = si_8
    uses: ax_20 = ax_19 - bx_3
ax_20: orig: ax
    def:  ax_20 = ax_19 - bx_3
    uses: SCZO_21 = cond(ax_20)
          ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
SCZO_21: orig: SCZO
    def:  SCZO_21 = cond(ax_20)
    uses: Z_22 = (bool) SCZO_21 (alias)
          SZO_23 = SCZO_21 (alias)
          C_24 = (bool) SCZO_21 (alias)
          SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
Z_22: orig: Z
    def:  Z_22 = (bool) SCZO_21 (alias)
    uses: Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
SZO_23: orig: SZO
    def:  SZO_23 = SCZO_21 (alias)
    uses: SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
C_24: orig: C
    def:  C_24 = (bool) SCZO_21 (alias)
    uses: C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
Mem25: orig: Mem0
    def:  Mem25[ds:di:word16] = ax_7
    uses: v12_37 = Mem25[ds:0x0302:word16] + 0x0001
di:di
    def:  def di
    uses: Mem25[ds:di:word16] = ax_7
ax_27: orig: ax
    def:  ax_27 = ax_7 | ax_7
    uses: SZO_28 = cond(ax_27)
          SCZO_33 = cond(ax_27 - 0x000D)
          branch ax_27 != 0x0000 l0C00_0011
          branch ax_27 != 0x000D l0C00_001A
SZO_28: orig: SZO
    def:  SZO_28 = cond(ax_27)
    uses: Z_29 = (bool) SZO_28 (alias)
          SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
Z_29: orig: Z
    def:  Z_29 = (bool) SZO_28 (alias)
    uses: Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
C_30: orig: C
    def:  C_30 = false
    uses: SCZO_31 = DPB(SCZO_9, C_30, 0) (alias)
          C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
SCZO_31: orig: SCZO
    def:  SCZO_31 = DPB(SCZO_9, C_30, 0) (alias)
    uses: SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
ax_32: orig: ax
    def:  ax_32 = 0xFFFF
    uses: ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
SCZO_33: orig: SCZO
    def:  SCZO_33 = cond(ax_27 - 0x000D)
    uses: Z_34 = (bool) SCZO_33 (alias)
          SZO_35 = SCZO_33 (alias)
          C_36 = (bool) SCZO_33 (alias)
Z_34: orig: Z
    def:  Z_34 = (bool) SCZO_33 (alias)
SZO_35: orig: SZO
    def:  SZO_35 = SCZO_33 (alias)
C_36: orig: C
    def:  C_36 = (bool) SCZO_33 (alias)
v12_37: orig: v12
    def:  v12_37 = Mem25[ds:0x0302:word16] + 0x0001
    uses: Mem38[ds:0x0302:word16] = v12_37
          SZO_39 = cond(v12_37)
Mem38: orig: Mem0
    def:  Mem38[ds:0x0302:word16] = v12_37
SZO_39: orig: SZO
    def:  SZO_39 = cond(v12_37)
    uses: SCZO_40 = SZO_39 (alias)
          Z_41 = (bool) SZO_39 (alias)
SCZO_40: orig: SCZO
    def:  SCZO_40 = SZO_39 (alias)
Z_41: orig: Z
    def:  Z_41 = (bool) SZO_39 (alias)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def fp
	def si
	def ds
	def Mem0
	def di
	sp_1 = fp
	// succ:  l0C00_0000
l0C00_0000:
	bx_3 = si
	goto l0C00_001A
	// succ:  l0C00_001A
l0C00_0005:
	Mem25[ds:di:word16] = ax_7
	ax_27 = ax_7 | ax_7
	SZO_28 = cond(ax_27)
	Z_29 = (bool) SZO_28 (alias)
	C_30 = false
	SCZO_31 = DPB(SCZO_9, C_30, 0) (alias)
	branch ax_27 != 0x0000 l0C00_0011
	// succ:  l0C00_000B l0C00_0011
l0C00_000B:
	ax_32 = 0xFFFF
	goto l0C00_0024
	// succ:  l0C00_0024
l0C00_0011:
	SCZO_33 = cond(ax_27 - 0x000D)
	Z_34 = (bool) SCZO_33 (alias)
	SZO_35 = SCZO_33 (alias)
	C_36 = (bool) SCZO_33 (alias)
	branch ax_27 != 0x000D l0C00_001A
	// succ:  l0C00_0016 l0C00_001A
l0C00_0016:
	v12_37 = Mem25[ds:0x0302:word16] + 0x0001
	Mem38[ds:0x0302:word16] = v12_37
	SZO_39 = cond(v12_37)
	SCZO_40 = SZO_39 (alias)
	Z_41 = (bool) SZO_39 (alias)
	// succ:  l0C00_001A
l0C00_001A:
	si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
	ax_7 = Mem0[ds:si_4:word16]
	si_8 = si_4 + 0x0002
	SCZO_9 = cond(ax_7 - 0x0020)
	Z_10 = (bool) SCZO_9 (alias)
	SZO_11 = SCZO_9 (alias)
	C_12 = (bool) SCZO_9 (alias)
	branch ax_7 != 0x0020 l0C00_0005
	// succ:  l0C00_0020 l0C00_0005
l0C00_0020:
	ax_19 = si_8
	ax_20 = ax_19 - bx_3
	SCZO_21 = cond(ax_20)
	Z_22 = (bool) SCZO_21 (alias)
	SZO_23 = SCZO_21 (alias)
	C_24 = (bool) SCZO_21 (alias)
	// succ:  l0C00_0024
l0C00_0024:
	ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
	SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
	Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
	SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
	C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
	Mem18[ds:0x0300:word16] = ax_13
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

fp:fp
    def:  def fp
    uses: sp_1 = fp
sp_1: orig: sp
    def:  sp_1 = fp
si:si
    def:  def si
    uses: bx_3 = si
          ax_20 = si_8 - si
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
bx_3: orig: bx
    def:  bx_3 = si
si_4: orig: si
    def:  si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
    uses: ax_7 = Mem0[ds:si_4:word16]
          si_8 = si_4 + 0x0002
ds:ds
    def:  def ds
    uses: ax_7 = Mem0[ds:si_4:word16]
          Mem18[ds:0x0300:word16] = ax_13
          Mem25[ds:di:word16] = ax_7
          v12_37 = Mem25[ds:0x0302:word16] + 0x0001
          Mem38[ds:0x0302:word16] = v12_37
Mem0:Global memory
    def:  def Mem0
    uses: ax_7 = Mem0[ds:si_4:word16]
ax_7: orig: ax
    def:  ax_7 = Mem0[ds:si_4:word16]
    uses: SCZO_9 = cond(ax_7 - 0x0020)
          Mem25[ds:di:word16] = ax_7
          ax_27 = ax_7
          branch ax_7 != 0x0020 l0C00_0005
          SZO_28 = cond(ax_7)
          branch ax_7 != 0x0000 l0C00_0011
          SCZO_33 = cond(ax_7 - 0x000D)
          branch ax_7 != 0x000D l0C00_001A
si_8: orig: si
    def:  si_8 = si_4 + 0x0002
    uses: ax_19 = si_8
          ax_20 = si_8 - si
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
          si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
SCZO_9: orig: SCZO
    def:  SCZO_9 = cond(ax_7 - 0x0020)
    uses: Z_10 = (bool) SCZO_9 (alias)
          SZO_11 = SCZO_9 (alias)
          C_12 = (bool) SCZO_9 (alias)
          SCZO_31 = DPB(SCZO_9, false, 0) (alias)
Z_10: orig: Z
    def:  Z_10 = (bool) SCZO_9 (alias)
SZO_11: orig: SZO
    def:  SZO_11 = SCZO_9 (alias)
C_12: orig: C
    def:  C_12 = (bool) SCZO_9 (alias)
ax_13: orig: ax
    def:  ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
    uses: Mem18[ds:0x0300:word16] = ax_13
SCZO_14: orig: SCZO
    def:  SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
Z_15: orig: Z
    def:  Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
SZO_16: orig: SZO
    def:  SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
C_17: orig: C
    def:  C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
Mem18: orig: Mem0
    def:  Mem18[ds:0x0300:word16] = ax_13
ax_19: orig: ax
    def:  ax_19 = si_8
ax_20: orig: ax
    def:  ax_20 = si_8 - si
    uses: SCZO_21 = cond(ax_20)
          ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
SCZO_21: orig: SCZO
    def:  SCZO_21 = cond(ax_20)
    uses: Z_22 = (bool) SCZO_21 (alias)
          SZO_23 = SCZO_21 (alias)
          C_24 = (bool) SCZO_21 (alias)
          SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
Z_22: orig: Z
    def:  Z_22 = (bool) SCZO_21 (alias)
    uses: Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
SZO_23: orig: SZO
    def:  SZO_23 = SCZO_21 (alias)
    uses: SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
C_24: orig: C
    def:  C_24 = (bool) SCZO_21 (alias)
    uses: C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
Mem25: orig: Mem0
    def:  Mem25[ds:di:word16] = ax_7
    uses: v12_37 = Mem25[ds:0x0302:word16] + 0x0001
di:di
    def:  def di
    uses: Mem25[ds:di:word16] = ax_7
ax_27: orig: ax
    def:  ax_27 = ax_7
SZO_28: orig: SZO
    def:  SZO_28 = cond(ax_7)
    uses: Z_29 = (bool) SZO_28 (alias)
          SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
Z_29: orig: Z
    def:  Z_29 = (bool) SZO_28 (alias)
    uses: Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
C_30: orig: C
    def:  C_30 = false
    uses: C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
SCZO_31: orig: SCZO
    def:  SCZO_31 = DPB(SCZO_9, false, 0) (alias)
    uses: SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
ax_32: orig: ax
    def:  ax_32 = 0xFFFF
    uses: ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
SCZO_33: orig: SCZO
    def:  SCZO_33 = cond(ax_7 - 0x000D)
    uses: Z_34 = (bool) SCZO_33 (alias)
          SZO_35 = SCZO_33 (alias)
          C_36 = (bool) SCZO_33 (alias)
Z_34: orig: Z
    def:  Z_34 = (bool) SCZO_33 (alias)
SZO_35: orig: SZO
    def:  SZO_35 = SCZO_33 (alias)
C_36: orig: C
    def:  C_36 = (bool) SCZO_33 (alias)
v12_37: orig: v12
    def:  v12_37 = Mem25[ds:0x0302:word16] + 0x0001
    uses: Mem38[ds:0x0302:word16] = v12_37
          SZO_39 = cond(v12_37)
Mem38: orig: Mem0
    def:  Mem38[ds:0x0302:word16] = v12_37
SZO_39: orig: SZO
    def:  SZO_39 = cond(v12_37)
    uses: SCZO_40 = SZO_39 (alias)
          Z_41 = (bool) SZO_39 (alias)
SCZO_40: orig: SCZO
    def:  SCZO_40 = SZO_39 (alias)
Z_41: orig: Z
    def:  Z_41 = (bool) SZO_39 (alias)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def fp
	def si
	def ds
	def Mem0
	def di
	sp_1 = fp
	// succ:  l0C00_0000
l0C00_0000:
	bx_3 = si
	goto l0C00_001A
	// succ:  l0C00_001A
l0C00_0005:
	Mem25[ds:di:word16] = ax_7
	ax_27 = ax_7
	SZO_28 = cond(ax_7)
	Z_29 = (bool) SZO_28 (alias)
	C_30 = false
	SCZO_31 = DPB(SCZO_9, false, 0) (alias)
	branch ax_7 != 0x0000 l0C00_0011
	// succ:  l0C00_000B l0C00_0011
l0C00_000B:
	ax_32 = 0xFFFF
	goto l0C00_0024
	// succ:  l0C00_0024
l0C00_0011:
	SCZO_33 = cond(ax_7 - 0x000D)
	Z_34 = (bool) SCZO_33 (alias)
	SZO_35 = SCZO_33 (alias)
	C_36 = (bool) SCZO_33 (alias)
	branch ax_7 != 0x000D l0C00_001A
	// succ:  l0C00_0016 l0C00_001A
l0C00_0016:
	v12_37 = Mem25[ds:0x0302:word16] + 0x0001
	Mem38[ds:0x0302:word16] = v12_37
	SZO_39 = cond(v12_37)
	SCZO_40 = SZO_39 (alias)
	Z_41 = (bool) SZO_39 (alias)
	// succ:  l0C00_001A
l0C00_001A:
	si_4 = PHI((si, l0C00_0000), (si_8, l0C00_0011), (si_8, l0C00_0016))
	ax_7 = Mem0[ds:si_4:word16]
	si_8 = si_4 + 0x0002
	SCZO_9 = cond(ax_7 - 0x0020)
	Z_10 = (bool) SCZO_9 (alias)
	SZO_11 = SCZO_9 (alias)
	C_12 = (bool) SCZO_9 (alias)
	branch ax_7 != 0x0020 l0C00_0005
	// succ:  l0C00_0020 l0C00_0005
l0C00_0020:
	ax_19 = si_8
	ax_20 = si_8 - si
	SCZO_21 = cond(ax_20)
	Z_22 = (bool) SCZO_21 (alias)
	SZO_23 = SCZO_21 (alias)
	C_24 = (bool) SCZO_21 (alias)
	// succ:  l0C00_0024
l0C00_0024:
	ax_13 = PHI((ax_20, l0C00_0020), (ax_32, l0C00_000B))
	SCZO_14 = PHI((SCZO_21, l0C00_0020), (SCZO_31, l0C00_000B))
	Z_15 = PHI((Z_22, l0C00_0020), (Z_29, l0C00_000B))
	SZO_16 = PHI((SZO_23, l0C00_0020), (SZO_28, l0C00_000B))
	C_17 = PHI((C_24, l0C00_0020), (C_30, l0C00_000B))
	Mem18[ds:0x0300:word16] = ax_13
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
