// example.c
// Generated by decompiling example
// using Reko decompiler version 0.8.0.2.

#include "example.h"

byte g_b2028 = 0x00;
Eq_99 g_t2030 = 
	{
		0x0000000000000000
	};
Eq_3 g_t2038 = 
	{
		0x0000000000000000
	};
Eq_59 g_t2040 = 
	{
		0x0000000000001000
	};
Eq_229 g_t2048 = 
	{
		0x0000000000000000
	};
Eq_143 g_t2050 = 
	{
		0x0000000000000000
	};

