// hello_m68k.globals.c
// Generated by decompiling hello_m68k.exe
// using Reko decompiler version 0.9.1.0.

#include "hello_m68k.h"

Eq_n g_t0000;
word16 g_w0AF0;
word16 g_a1758[] = 
	{
	};
word16 g_a2C58[] = 
	{
	};

