// hello_m68k.globals.c
// Generated by decompiling hello_m68k.exe
// using Reko decompiler version 0.11.2.0.

#include "hello_m68k.h"

struct Eq_n * g_ptr0000; // 00000000
word16 g_w0AF0; // 00000AF0
