Mem0: Mem0:Global memory, def: {def Mem0}, uses: {ax_16 = Mem0[ds:0x0200:word16]}{dx_17 = Mem0[ds:0x0202:word16]}{cx_19 = Mem0[ds:0x0204:word16]}{bx_20 = Mem0[ds:0x0206:word16]}
fp: fp:Temporary
ds: ds:Register ds, def: {def ds}, uses: {ax_16 = Mem0[ds:0x0200:word16]}{dx_17 = Mem0[ds:0x0202:word16]}{cx_19 = Mem0[ds:0x0204:word16]}{bx_20 = Mem0[ds:0x0206:word16]}{store(Mem26[ds:0x0208:word16]) = ax_23}{store(Mem27[ds:0x020A:word16]) = dx_24}{ax_28 = Mem27[ds:0x0210:word16]}{dx_29 = Mem27[ds:0x0212:word16]}{es_cx_31 = Mem27[ds:0x0214:ptr32]}{store(Mem39[ds:0x0218:word16]) = ax_36}{store(Mem40[ds:0x021A:word16]) = dx_37}{cl_42 = Mem40[ds:0x0220:byte]}{cl_47 = Mem40[ds:0x0221:byte]}{store(Mem54[ds:0x0222:word16]) = ax_52}
ax: ax:Register ax
dx: dx:Register dx
cx: cx:Register cx
bx: bx:Register bx
bx_cx: bx_cx:Sequence bx:cx
dx_ax: dx_ax:Sequence dx:ax
SCZO: SCZO:Flags
es: es:Register es
es_cx: es_cx:Sequence es:cx
cl: cl:Register cl
v13: v13:Temporary
C: C:Flags
v15: v15:Temporary
ax_16: orig: ax, def: {ax_16 = Mem0[ds:0x0200:word16]}, uses: {dx_ax_18 = SEQ(dx_17, ax_16) (alias)}
dx_17: orig: dx, def: {dx_17 = Mem0[ds:0x0202:word16]}, uses: {dx_ax_18 = SEQ(dx_17, ax_16) (alias)}
dx_ax_18: orig: dx_ax, def: {dx_ax_18 = SEQ(dx_17, ax_16) (alias)}, uses: {dx_ax_22 = dx_ax_18 + bx_cx_21}
cx_19: orig: cx, def: {cx_19 = Mem0[ds:0x0204:word16]}, uses: {bx_cx_21 = SEQ(bx_20, cx_19) (alias)}{bx_cx_34 = SEQ(bx_33, cx_19) (alias)}
bx_20: orig: bx, def: {bx_20 = Mem0[ds:0x0206:word16]}, uses: {bx_cx_21 = SEQ(bx_20, cx_19) (alias)}
bx_cx_21: orig: bx_cx, def: {bx_cx_21 = SEQ(bx_20, cx_19) (alias)}, uses: {dx_ax_22 = dx_ax_18 + bx_cx_21}
dx_ax_22: orig: dx_ax, def: {dx_ax_22 = dx_ax_18 + bx_cx_21}, uses: {ax_23 = (word16) dx_ax_22 (alias)}{dx_24 = SLICE(dx_ax_22, word16, 16) (alias)}
ax_23: orig: ax, def: {ax_23 = (word16) dx_ax_22 (alias)}, uses: {store(Mem26[ds:0x0208:word16]) = ax_23}
dx_24: orig: dx, def: {dx_24 = SLICE(dx_ax_22, word16, 16) (alias)}, uses: {store(Mem27[ds:0x020A:word16]) = dx_24}
SCZO_25: orig: SCZO
Mem26: orig: Mem0, def: {store(Mem26[ds:0x0208:word16]) = ax_23}
Mem27: orig: Mem0, def: {store(Mem27[ds:0x020A:word16]) = dx_24}, uses: {ax_28 = Mem27[ds:0x0210:word16]}{dx_29 = Mem27[ds:0x0212:word16]}{es_cx_31 = Mem27[ds:0x0214:ptr32]}
ax_28: orig: ax, def: {ax_28 = Mem27[ds:0x0210:word16]}, uses: {dx_ax_30 = SEQ(dx_29, ax_28) (alias)}
dx_29: orig: dx, def: {dx_29 = Mem27[ds:0x0212:word16]}, uses: {dx_ax_30 = SEQ(dx_29, ax_28) (alias)}
dx_ax_30: orig: dx_ax, def: {dx_ax_30 = SEQ(dx_29, ax_28) (alias)}, uses: {dx_ax_35 = dx_ax_30 - bx_cx_34}
es_cx_31: orig: es_cx, def: {es_cx_31 = Mem27[ds:0x0214:ptr32]}, uses: {es_32 = SLICE(es_cx_31, selector, 16) (alias)}
es_32: orig: es, def: {es_32 = SLICE(es_cx_31, selector, 16) (alias)}, uses: {bx_33 = es_32}
bx_33: orig: bx, def: {bx_33 = es_32}, uses: {bx_cx_34 = SEQ(bx_33, cx_19) (alias)}
bx_cx_34: orig: bx_cx, def: {bx_cx_34 = SEQ(bx_33, cx_19) (alias)}, uses: {dx_ax_35 = dx_ax_30 - bx_cx_34}
dx_ax_35: orig: dx_ax, def: {dx_ax_35 = dx_ax_30 - bx_cx_34}, uses: {ax_36 = (word16) dx_ax_35 (alias)}{dx_37 = SLICE(dx_ax_35, word16, 16) (alias)}
ax_36: orig: ax, def: {ax_36 = (word16) dx_ax_35 (alias)}, uses: {store(Mem39[ds:0x0218:word16]) = ax_36}
dx_37: orig: dx, def: {dx_37 = SLICE(dx_ax_35, word16, 16) (alias)}, uses: {store(Mem40[ds:0x021A:word16]) = dx_37}
SCZO_38: orig: SCZO
Mem39: orig: Mem0, def: {store(Mem39[ds:0x0218:word16]) = ax_36}
Mem40: orig: Mem0, def: {store(Mem40[ds:0x021A:word16]) = dx_37}, uses: {cl_42 = Mem40[ds:0x0220:byte]}{cl_47 = Mem40[ds:0x0221:byte]}
ax_41: orig: ax, def: {ax_41 = 0x0000}, uses: {v13_45 = ax_41 + ax_41}{v13_45 = ax_41 + ax_41}
cl_42: orig: cl, def: {cl_42 = Mem40[ds:0x0220:byte]}, uses: {ax_46 = v13_45 + (word16) (cl_42 <u 0x30)}
SCZO_43: orig: SCZO
C_44: orig: C
v13_45: orig: v13, def: {v13_45 = ax_41 + ax_41}, uses: {ax_46 = v13_45 + (word16) (cl_42 <u 0x30)}
ax_46: orig: ax, def: {ax_46 = v13_45 + (word16) (cl_42 <u 0x30)}, uses: {v15_51 = ax_46 + ax_46}{v15_51 = ax_46 + ax_46}
cl_47: orig: cl, def: {cl_47 = Mem40[ds:0x0221:byte]}, uses: {ax_52 = v15_51 + (word16) (cl_47 >=u 0x3A)}
SCZO_48: orig: SCZO
C_49: orig: C
C_50: orig: C
v15_51: orig: v15, def: {v15_51 = ax_46 + ax_46}, uses: {ax_52 = v15_51 + (word16) (cl_47 >=u 0x3A)}
ax_52: orig: ax, def: {ax_52 = v15_51 + (word16) (cl_47 >=u 0x3A)}, uses: {store(Mem54[ds:0x0222:word16]) = ax_52}
SCZO_53: orig: SCZO
Mem54: orig: Mem0, def: {store(Mem54[ds:0x0222:word16]) = ax_52}
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	def Mem0
	def ds
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	ax_16 = Mem0[ds:0x0200:word16]
	dx_17 = Mem0[ds:0x0202:word16]
	dx_ax_18 = SEQ(dx_17, ax_16) (alias)
	cx_19 = Mem0[ds:0x0204:word16]
	bx_20 = Mem0[ds:0x0206:word16]
	bx_cx_21 = SEQ(bx_20, cx_19) (alias)
	dx_ax_22 = dx_ax_18 + bx_cx_21
	ax_23 = (word16) dx_ax_22 (alias)
	dx_24 = SLICE(dx_ax_22, word16, 16) (alias)
	store(Mem26[ds:0x0208:word16]) = ax_23
	store(Mem27[ds:0x020A:word16]) = dx_24
	ax_28 = Mem27[ds:0x0210:word16]
	dx_29 = Mem27[ds:0x0212:word16]
	dx_ax_30 = SEQ(dx_29, ax_28) (alias)
	es_cx_31 = Mem27[ds:0x0214:ptr32]
	es_32 = SLICE(es_cx_31, selector, 16) (alias)
	bx_33 = es_32
	bx_cx_34 = SEQ(bx_33, cx_19) (alias)
	dx_ax_35 = dx_ax_30 - bx_cx_34
	ax_36 = (word16) dx_ax_35 (alias)
	dx_37 = SLICE(dx_ax_35, word16, 16) (alias)
	store(Mem39[ds:0x0218:word16]) = ax_36
	store(Mem40[ds:0x021A:word16]) = dx_37
	ax_41 = 0x0000
	cl_42 = Mem40[ds:0x0220:byte]
	v13_45 = ax_41 + ax_41
	ax_46 = v13_45 + (word16) (cl_42 <u 0x30)
	cl_47 = Mem40[ds:0x0221:byte]
	v15_51 = ax_46 + ax_46
	ax_52 = v15_51 + (word16) (cl_47 >=u 0x3A)
	store(Mem54[ds:0x0222:word16]) = ax_52
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

