void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: ax si al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// si:Register si
// ax:Register ax
// ds:Register ds
// al:Register al
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	si = 0x0200
	ax = fn0C00_0015(si, ds)
	store(Mem0[ds:0x0202:word16]) = ax
	si = 0x0300
	ax = fn0C00_0015(si, ds)
	store(Mem0[ds:0x0302:byte]) = al
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 
Register word16 fn0C00_0015(Register word16 si, Register selector ds)
// MayUse:  si ds
// LiveOut: ax al
// Trashed: ax al ah
// Preserved:
// fn0C00_0015
// Mem0:Global memory
// fp:Temporary
// si:Register si
// ds:Register ds
// ax:Register ax
// return address size: 2
word16 fn0C00_0015(word16 si, selector ds)
fn0C00_0015_entry:		// block 0, pred:
	// succ:  1
l0C00_0015:		// block 1, pred: 0
	ax = Mem0[ds:si:word16]
	return ax
	// succ:  2
fn0C00_0015_exit:		// block 2, pred: 1
	// succ: 
