// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  ds
	BypassIn: 
	Trashed:   SCZO ax cx dx al cl dl ah ch dh
	Preserved:
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
// DataOut: ds
l0C00_0000:		// pred: fn0C00_0000_entry
	cx = 0x0005
	call fn0C00_000B (depth: 2;)
	store(Mem0[ds:0x0064:word16]) = ax
	return
	// succ:  fn0C00_0000_exit
// DataOut:
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
// DataOut:
// fn0C00_000B /////////////////////
	LiveOut:   ax ds
	MayUseIn:  cx
	BypassIn: 
	Trashed:   SCZO ax cx dx al cl dl ah ch dh
	Preserved: si
// fn0C00_000B
void fn0C00_000B()
fn0C00_000B_entry:		// pred:
	// succ:  l0C00_000B
// DataOut: cx ds
l0C00_000B:		// pred: fn0C00_000B_entry
	wLoc04 = si
	SCZO = cond(cx - 0x0001)
	branch Test(LE,SZO) l0C00_001C
	// succ:  l0C00_0011 l0C00_001C
// DataOut: cx ds
l0C00_001C:		// pred: l0C00_000B
	ax = 0x0001
	// succ:  l0C00_001F
// DataOut: ax ds
l0C00_0011:		// pred: l0C00_000B
	si = cx
	cx = cx - 0x0001
	call fn0C00_000B (depth: 4;)
	dx_ax = si *s ax
	SCZO = cond(dx_ax)
	// succ:  l0C00_001F
// DataOut: ax ds
l0C00_001F:		// pred: l0C00_001C l0C00_0011
	si = wLoc04
	return
	// succ:  fn0C00_000B_exit
// DataOut: ax ds
fn0C00_000B_exit:		// pred: l0C00_001F
	// succ: 
// DataOut: ax ds
