// fn0C00_0000
void fn0C00_0000(I2 ax, I2 si)
fn0C00_0000_entry:		// block 0, pred:
	branch ax != 0000
	// succ:  2 1
l0C00_000B:		// block 1, pred: 0
	bx_9 = 1211
	// succ:  3
l0C00_0005:		// block 2, pred: 0
	bx_9 = 1234
	// succ:  3
l0C00_000E:		// block 3, pred: 2 1
	si->w00000000 = bx_9
	return
	// succ: 
-----------
fn0C00_0000()
{
    if (ax != 0000)
        bx_9 = 1211;
    else
        bx_9 = 1234;
    si->w00000000 = bx_9;
    return;
}
===========
