// MockWhileBreak
void MockWhileBreak()
MockWhileBreak_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	r2 = 0x00000000
	// succ:  2
looptest:		// block 2, pred: 1 6
	branch r1 == 0x00000000
	// succ:  3 4
l2:		// block 3, pred: 2
	r3 = Mem0[r1:word32]
	r2 = r2 + r3
	r3 = Mem0[r1 + 0x00000004:word32]
	branch r3 == 0x00000000
	// succ:  6 4
done:		// block 4, pred: 2 3
	return r2
	// succ:  5
MockWhileBreak_exit:		// block 5, pred: 4
	// succ: 
l3:		// block 6, pred: 3
	r1 = Mem0[r1 + 0x0000000C:word32]
	// succ:  2
