// WhileExitMock
void WhileExitMock()
WhileExitMock_entry:		// block 0, pred:
	// succ:  1
loop:		// block 1, pred: 0 3
	branch p == 0x00000000
	// succ:  2 5
l1:		// block 2, pred: 1
	foo()
	branch p != 0x00000002
	// succ:  4 3
not2:		// block 3, pred: 2
	foo()
	p = p - 0x00000001
	// succ:  1
exitBlock:		// block 4, pred: 2
	bar()
	// succ:  5
done:		// block 5, pred: 1 4
	return p
	// succ:  6
WhileExitMock_exit:		// block 6, pred: 5
	// succ: 
-----------
hdr: 1, end: 3 [1, 2, 3, 4]

void WhileExitMock()
{
	while (p != 0x00000000)
	{
		foo();
		if (p == 0x00000002)
		{
			bar();
			break;
		}
		foo();
		p = p - 0x00000001;
	}
	return p
}
===========
