// nbody.h
// Generated by decompiling nbody.wasm
// using Reko decompiler version 0.11.4.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (100000 (ptr32 Eq_3) ptr100000) (100008 ptr32 ptr100008) (10000C word32 dw10000C))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_3: (struct "Eq_3"
		(0 (arr Eq_516) a0000)
		(18 real64 r0018)
		(20 real64 r0020)
		(28 real64 r0028)
		(30 real64 r0030)
		(50 real64 r0050)
		(58 real64 r0058)
		(60 real64 r0060)
		(68 real64 r0068)
		(88 real64 r0088)
		(90 real64 r0090)
		(98 real64 r0098)
		(A0 real64 r00A0)
		(C0 real64 r00C0)
		(C8 real64 r00C8)
		(D0 real64 r00D0)
		(D8 real64 r00D8)
		(F8 real64 r00F8)
		(100 real64 r0100)
		(108 real64 r0108)
		(110 real64 r0110))
	T_3 (in arg1 : (ptr32 Eq_3))
	T_331 (in Mem1[0x00100000<p32>:word32] @ 000E0409 : word32)
	T_336 (in Mem1[0x00100000<p32>:word32] @ 000E0420 : word32)
	T_341 (in Mem1[0x00100000<p32>:word32] @ 000E042E : word32)
	T_346 (in Mem1[0x00100000<p32>:word32] @ 000E043E : word32)
	T_351 (in Mem1[0x00100000<p32>:word32] @ 000E044E : word32)
	T_356 (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
	T_363 (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
	T_369 (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
	T_375 (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
	T_381 (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
	T_388 (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
	T_395 (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
	T_401 (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
	T_407 (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
	T_413 (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
	T_419 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_426 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_432 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_438 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_444 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_453 (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
	T_460 (in Mem97[0x00100000<p32>:word32] @ 000E04F5 : word32)
	T_467 (in Mem104[0x00100000<p32>:word32] @ 000E0509 : word32)
	T_485 (in Mem0[0x00100000<p32>:word32] @ 000E064A : word32)
	T_503 (in Mem0[0x00100000<p32>:word32] @ 000E0778 : word32)
Eq_26: (struct "Eq_26" (8 real64 r0008))
	T_26 (in arg1 + loc3_19 * 0x38<32> @ 000E00A3 : word32)
Eq_32: (struct "Eq_32" (8 real64 r0008))
	T_32 (in arg1 + v24_12 * 0x38<32> @ 000E00A3 : word32)
Eq_40: (struct "Eq_40" (10 real64 r0010))
	T_40 (in arg1 + loc3_19 * 0x38<32> @ 000E00B7 : word32)
Eq_46: (struct "Eq_46" (10 real64 r0010))
	T_46 (in arg1 + v24_12 * 0x38<32> @ 000E00B7 : word32)
Eq_54: (struct "Eq_54" (30 real64 r0030))
	T_54 (in arg1 + loc3_19 * 0x38<32> @ 000E0076 : word32)
Eq_59: (fn real64 (real64))
	T_59 (in sqrt @ 000E00BE : ptr32)
	T_60 (in signature of sqrt : void)
Eq_68: (struct "Eq_68" (18 real64 r0018))
	T_68 (in v49_45 @ 000E004E : (ptr32 Eq_68))
	T_71 (in arg1 + loc3_19 * 0x38<32> @ 000E004E : word32)
Eq_75: (struct "Eq_75" (30 real64 r0030))
	T_75 (in arg1 + v24_12 * 0x38<32> @ 000E00DB : word32)
Eq_91: (struct "Eq_91" (20 real64 r0020))
	T_91 (in v56_53 @ 000E005B : (ptr32 Eq_91))
	T_94 (in arg1 + loc3_19 * 0x38<32> @ 000E005B : word32)
Eq_103: (struct "Eq_103" (28 real64 r0028))
	T_103 (in v63_61 @ 000E0068 : (ptr32 Eq_103))
	T_106 (in arg1 + loc3_19 * 0x38<32> @ 000E0068 : word32)
Eq_115: (struct "Eq_115" (18 real64 r0018))
	T_115 (in v148_160 @ 000E0115 : (ptr32 Eq_115))
	T_118 (in arg1 + v24_12 * 0x38<32> @ 000E0115 : word32)
Eq_127: (struct "Eq_127" (20 real64 r0020))
	T_127 (in v163_177 @ 000E0133 : (ptr32 Eq_127))
	T_130 (in arg1 + v24_12 * 0x38<32> @ 000E0133 : word32)
Eq_139: (struct "Eq_139" (28 real64 r0028))
	T_139 (in v178_194 @ 000E0151 : (ptr32 Eq_139))
	T_142 (in arg1 + v24_12 * 0x38<32> @ 000E0151 : word32)
Eq_170: (struct "Eq_170" (18 real64 r0018))
	T_170 (in arg1 + loc4_220 * 0x38<32> @ 000E01B0 : word32)
Eq_179: (struct "Eq_179" (8 real64 r0008))
	T_179 (in v220_247 @ 000E01BA : (ptr32 Eq_179))
	T_182 (in arg1 + loc4_220 * 0x38<32> @ 000E01BA : word32)
Eq_188: (struct "Eq_188" (20 real64 r0020))
	T_188 (in arg1 + loc4_220 * 0x38<32> @ 000E01D4 : word32)
Eq_196: (struct "Eq_196" (10 real64 r0010))
	T_196 (in v238_267 @ 000E01DE : (ptr32 Eq_196))
	T_199 (in arg1 + loc4_220 * 0x38<32> @ 000E01DE : word32)
Eq_205: (struct "Eq_205" (28 real64 r0028))
	T_205 (in arg1 + loc4_220 * 0x38<32> @ 000E01F8 : word32)
Eq_231: (struct "Eq_231" (18 real64 r0018))
	T_231 (in arg1 + loc2_15 * 0x38<32> @ 000E0251 : word32)
Eq_238: (struct "Eq_238" (20 real64 r0020))
	T_238 (in arg1 + loc2_15 * 0x38<32> @ 000E0261 : word32)
Eq_245: (struct "Eq_245" (28 real64 r0028))
	T_245 (in arg1 + loc2_15 * 0x38<32> @ 000E0272 : word32)
Eq_252: (struct "Eq_252" (30 real64 r0030))
	T_252 (in arg1 + loc2_15 * 0x38<32> @ 000E027C : word32)
Eq_276: (struct "Eq_276" (18 real64 r0018) (20 real64 r0020) (28 real64 r0028) (30 real64 r0030))
	T_276 (in arg1 @ 000E0328 : (ptr32 Eq_276))
Eq_482: (fn word32 (int32, (ptr32 Eq_3), real64))
	T_482 (in _advance @ 000E064A : ptr32)
	T_483 (in signature of _advance @ 000E0000 : void)
Eq_513: (fn word32 ())
	T_513 (in runPostSets @ 000E0784 : ptr32)
	T_514 (in signature of runPostSets @ 000E076E : void)
Eq_516: (struct "Eq_516" 0038 (0 real64 r0000))
	T_516
	T_518
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in arg0 : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_3: (in arg1 : (ptr32 Eq_3))
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (0 (arr T_516) a0000)))
T_4: (in arg2 : real64)
  Class: Eq_4
  DataType: real64
  OrigDataType: real64
T_5: (in 0<32> @ 000E0009 : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_6: (in arg0 > 0<32> @ 000E0009 : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in !(arg0 > 0<32>) @ 000E0009 : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
T_8: (in loc3_19 @ 000E000D : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_9: (in 0<32> @ 000E000D : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: word32
T_10: (in v24_12 @ 000E0018 : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_11: (in 1<32> @ 000E0018 : word32)
  Class: Eq_11
  DataType: word32
  OrigDataType: word32
T_12: (in loc3_19 + 1<32> @ 000E0018 : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: word32
T_13: (in v24_12 < arg0 @ 000E001E : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in !(v24_12 < arg0) @ 000E001E : bool)
  Class: Eq_14
  DataType: bool
  OrigDataType: bool
T_15: (in v81_84 @ 000E0090 : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_16: (in 0x38<32> @ 000E0090 : word32)
  Class: Eq_16
  DataType: ui32
  OrigDataType: ui32
T_17: (in loc3_19 * 0x38<32> @ 000E0090 : word32)
  Class: Eq_17
  DataType: ui32
  OrigDataType: ui32
T_18: (in arg1[loc3_19 * 0x38<32>] @ 000E0090 : real64)
  Class: Eq_18
  DataType: real64
  OrigDataType: real64
T_19: (in 0x38<32> @ 000E0090 : word32)
  Class: Eq_19
  DataType: ui32
  OrigDataType: ui32
T_20: (in v24_12 * 0x38<32> @ 000E0090 : word32)
  Class: Eq_20
  DataType: ui32
  OrigDataType: ui32
T_21: (in arg1[v24_12 * 0x38<32>] @ 000E0090 : real64)
  Class: Eq_18
  DataType: real64
  OrigDataType: real64
T_22: (in arg1[loc3_19 * 0x38<32> / 280<i32>] - arg1[(v24_12 * 0x38<32>) / 280<i32>] @ 000E0090 : real64)
  Class: Eq_15
  DataType: real64
  OrigDataType: real64
T_23: (in v91_95 @ 000E00A3 : real64)
  Class: Eq_23
  DataType: real64
  OrigDataType: real64
T_24: (in 0x38<32> @ 000E00A3 : word32)
  Class: Eq_24
  DataType: ui32
  OrigDataType: ui32
T_25: (in loc3_19 * 0x38<32> @ 000E00A3 : word32)
  Class: Eq_25
  DataType: int32
  OrigDataType: int32
T_26: (in arg1 + loc3_19 * 0x38<32> @ 000E00A3 : word32)
  Class: Eq_26
  DataType: (ptr32 Eq_26)
  OrigDataType: (ptr32 (struct (8 T_29 t0008)))
T_27: (in 8<u32> @ 000E00A3 : uint32)
  Class: Eq_27
  DataType: uint32
  OrigDataType: uint32
T_28: (in arg1 + loc3_19 * 0x38<32> + 8<u32> @ 000E00A3 : word32)
  Class: Eq_28
  DataType: ptr32
  OrigDataType: ptr32
T_29: (in Mem24[arg1 + loc3_19 * 0x38<32> + 8<u32>:real64] @ 000E00A3 : real64)
  Class: Eq_29
  DataType: real64
  OrigDataType: real64
T_30: (in 0x38<32> @ 000E00A3 : word32)
  Class: Eq_30
  DataType: ui32
  OrigDataType: ui32
T_31: (in v24_12 * 0x38<32> @ 000E00A3 : word32)
  Class: Eq_31
  DataType: int32
  OrigDataType: int32
T_32: (in arg1 + v24_12 * 0x38<32> @ 000E00A3 : word32)
  Class: Eq_32
  DataType: (ptr32 Eq_32)
  OrigDataType: (ptr32 (struct (8 T_35 t0008)))
T_33: (in 8<u32> @ 000E00A3 : uint32)
  Class: Eq_33
  DataType: uint32
  OrigDataType: uint32
T_34: (in arg1 + v24_12 * 0x38<32> + 8<u32> @ 000E00A3 : word32)
  Class: Eq_34
  DataType: ptr32
  OrigDataType: ptr32
T_35: (in Mem24[arg1 + v24_12 * 0x38<32> + 8<u32>:real64] @ 000E00A3 : real64)
  Class: Eq_35
  DataType: real64
  OrigDataType: real64
T_36: (in (&(arg1 + (loc3_19 * 0x38<32>) / 280<i32>)->a0000[0<i32>].r0000)[1<i32>] - (&(((arg1 + (v24_12 * 0x38<32>) / 280<i32>)->a0000))[0<i32>].r0000)[1<i32>] @ 000E00A3 : real64)
  Class: Eq_23
  DataType: real64
  OrigDataType: real64
T_37: (in v102_107 @ 000E00B7 : real64)
  Class: Eq_37
  DataType: real64
  OrigDataType: real64
T_38: (in 0x38<32> @ 000E00B7 : word32)
  Class: Eq_38
  DataType: ui32
  OrigDataType: ui32
T_39: (in loc3_19 * 0x38<32> @ 000E00B7 : word32)
  Class: Eq_39
  DataType: int32
  OrigDataType: int32
T_40: (in arg1 + loc3_19 * 0x38<32> @ 000E00B7 : word32)
  Class: Eq_40
  DataType: (ptr32 Eq_40)
  OrigDataType: (ptr32 (struct (10 T_43 t0010)))
T_41: (in 0x10<u32> @ 000E00B7 : uint32)
  Class: Eq_41
  DataType: uint32
  OrigDataType: uint32
T_42: (in arg1 + loc3_19 * 0x38<32> + 0x10<u32> @ 000E00B7 : word32)
  Class: Eq_42
  DataType: ptr32
  OrigDataType: ptr32
T_43: (in Mem24[arg1 + loc3_19 * 0x38<32> + 0x10<u32>:real64] @ 000E00B7 : real64)
  Class: Eq_43
  DataType: real64
  OrigDataType: real64
T_44: (in 0x38<32> @ 000E00B7 : word32)
  Class: Eq_44
  DataType: ui32
  OrigDataType: ui32
T_45: (in v24_12 * 0x38<32> @ 000E00B7 : word32)
  Class: Eq_45
  DataType: int32
  OrigDataType: int32
T_46: (in arg1 + v24_12 * 0x38<32> @ 000E00B7 : word32)
  Class: Eq_46
  DataType: (ptr32 Eq_46)
  OrigDataType: (ptr32 (struct (10 T_49 t0010)))
T_47: (in 0x10<u32> @ 000E00B7 : uint32)
  Class: Eq_47
  DataType: uint32
  OrigDataType: uint32
T_48: (in arg1 + v24_12 * 0x38<32> + 0x10<u32> @ 000E00B7 : word32)
  Class: Eq_48
  DataType: ptr32
  OrigDataType: ptr32
T_49: (in Mem24[arg1 + v24_12 * 0x38<32> + 0x10<u32>:real64] @ 000E00B7 : real64)
  Class: Eq_49
  DataType: real64
  OrigDataType: real64
T_50: (in (&(arg1 + (loc3_19 * 0x38<32>) / 280<i32>)->a0000[0<i32>].r0000)[2<i32>] - (&(((arg1 + (v24_12 * 0x38<32>) / 280<i32>)->a0000))[0<i32>].r0000)[2<i32>] @ 000E00B7 : real64)
  Class: Eq_37
  DataType: real64
  OrigDataType: real64
T_51: (in v71_70 @ 000E0076 : real64)
  Class: Eq_51
  DataType: real64
  OrigDataType: real64
T_52: (in 0x38<32> @ 000E0076 : word32)
  Class: Eq_52
  DataType: ui32
  OrigDataType: ui32
T_53: (in loc3_19 * 0x38<32> @ 000E0076 : word32)
  Class: Eq_53
  DataType: int32
  OrigDataType: int32
T_54: (in arg1 + loc3_19 * 0x38<32> @ 000E0076 : word32)
  Class: Eq_54
  DataType: (ptr32 Eq_54)
  OrigDataType: (ptr32 (struct (30 T_57 t0030)))
T_55: (in 0x30<u32> @ 000E0076 : uint32)
  Class: Eq_55
  DataType: uint32
  OrigDataType: uint32
T_56: (in arg1 + loc3_19 * 0x38<32> + 0x30<u32> @ 000E0076 : word32)
  Class: Eq_56
  DataType: ptr32
  OrigDataType: ptr32
T_57: (in Mem24[arg1 + loc3_19 * 0x38<32> + 0x30<u32>:real64] @ 000E0076 : real64)
  Class: Eq_51
  DataType: real64
  OrigDataType: real64
T_58: (in v106_112 @ 000E00BE : real64)
  Class: Eq_58
  DataType: real64
  OrigDataType: real64
T_59: (in sqrt @ 000E00BE : ptr32)
  Class: Eq_59
  DataType: (ptr32 Eq_59)
  OrigDataType: (ptr32 (fn T_67 (T_66)))
T_60: (in signature of sqrt : void)
  Class: Eq_59
  DataType: (ptr32 Eq_59)
  OrigDataType: 
T_61: (in p1 @ 000E00BE : real64)
  Class: Eq_61
  DataType: real64
  OrigDataType: 
T_62: (in v81_84 * v81_84 @ 000E00BE : real64)
  Class: Eq_62
  DataType: real64
  OrigDataType: real64
T_63: (in v91_95 * v91_95 @ 000E00BE : real64)
  Class: Eq_63
  DataType: real64
  OrigDataType: real64
T_64: (in v81_84 * v81_84 + v91_95 * v91_95 @ 000E00BE : real64)
  Class: Eq_64
  DataType: real64
  OrigDataType: real64
T_65: (in v102_107 * v102_107 @ 000E00BE : real64)
  Class: Eq_65
  DataType: real64
  OrigDataType: real64
T_66: (in v81_84 * v81_84 + v91_95 * v91_95 + v102_107 * v102_107 @ 000E00BE : real64)
  Class: Eq_61
  DataType: real64
  OrigDataType: real64
T_67: (in sqrt(v81_84 * v81_84 + v91_95 * v91_95 + v102_107 * v102_107) @ 000E00BE : real64)
  Class: Eq_58
  DataType: real64
  OrigDataType: real64
T_68: (in v49_45 @ 000E004E : (ptr32 Eq_68))
  Class: Eq_68
  DataType: (ptr32 Eq_68)
  OrigDataType: (ptr32 (struct (18 T_85 t0018)))
T_69: (in 0x38<32> @ 000E004E : word32)
  Class: Eq_69
  DataType: ui32
  OrigDataType: ui32
T_70: (in loc3_19 * 0x38<32> @ 000E004E : word32)
  Class: Eq_70
  DataType: int32
  OrigDataType: int32
T_71: (in arg1 + loc3_19 * 0x38<32> @ 000E004E : word32)
  Class: Eq_68
  DataType: (ptr32 Eq_68)
  OrigDataType: ptr32
T_72: (in v121_129 @ 000E00DB : real64)
  Class: Eq_72
  DataType: real64
  OrigDataType: real64
T_73: (in 0x38<32> @ 000E00DB : word32)
  Class: Eq_73
  DataType: ui32
  OrigDataType: ui32
T_74: (in v24_12 * 0x38<32> @ 000E00DB : word32)
  Class: Eq_74
  DataType: int32
  OrigDataType: int32
T_75: (in arg1 + v24_12 * 0x38<32> @ 000E00DB : word32)
  Class: Eq_75
  DataType: (ptr32 Eq_75)
  OrigDataType: (ptr32 (struct (30 T_78 t0030)))
T_76: (in 0x30<u32> @ 000E00DB : uint32)
  Class: Eq_76
  DataType: uint32
  OrigDataType: uint32
T_77: (in arg1 + v24_12 * 0x38<32> + 0x30<u32> @ 000E00DB : word32)
  Class: Eq_77
  DataType: ptr32
  OrigDataType: ptr32
T_78: (in Mem24[arg1 + v24_12 * 0x38<32> + 0x30<u32>:real64] @ 000E00DB : real64)
  Class: Eq_72
  DataType: real64
  OrigDataType: real64
T_79: (in v111_118 @ 000E00C7 : real64)
  Class: Eq_79
  DataType: real64
  OrigDataType: real64
T_80: (in v106_112 * v106_112 @ 000E00C7 : real64)
  Class: Eq_80
  DataType: real64
  OrigDataType: real64
T_81: (in v106_112 * (v106_112 * v106_112) @ 000E00C7 : real64)
  Class: Eq_81
  DataType: real64
  OrigDataType: real64
T_82: (in arg2 / (v106_112 * (v106_112 * v106_112)) @ 000E00C7 : real64)
  Class: Eq_79
  DataType: real64
  OrigDataType: real64
T_83: (in 0x18<32> @ 000E00E5 : word32)
  Class: Eq_83
  DataType: word32
  OrigDataType: word32
T_84: (in v49_45 + 0x18<32> @ 000E00E5 : word32)
  Class: Eq_84
  DataType: ptr32
  OrigDataType: ptr32
T_85: (in Mem24[v49_45 + 0x18<32>:real64] @ 000E00E5 : real64)
  Class: Eq_85
  DataType: real64
  OrigDataType: real64
T_86: (in v81_84 * v121_129 @ 000E00E5 : real64)
  Class: Eq_86
  DataType: real64
  OrigDataType: real64
T_87: (in v81_84 * v121_129 * v111_118 @ 000E00E5 : real64)
  Class: Eq_87
  DataType: real64
  OrigDataType: real64
T_88: (in v49_45->r0018 - (v81_84 * v121_129) * v111_118 @ 000E00E5 : real64)
  Class: Eq_85
  DataType: real64
  OrigDataType: real64
T_89: (in v49_45 + 0x18<32> @ 000E00E5 : word32)
  Class: Eq_89
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_90: (in Mem135[v49_45 + 0x18<32>:real64] @ 000E00E5 : real64)
  Class: Eq_85
  DataType: real64
  OrigDataType: real64
T_91: (in v56_53 @ 000E005B : (ptr32 Eq_91))
  Class: Eq_91
  DataType: (ptr32 Eq_91)
  OrigDataType: (ptr32 (struct (20 T_97 t0020)))
T_92: (in 0x38<32> @ 000E005B : word32)
  Class: Eq_92
  DataType: ui32
  OrigDataType: ui32
T_93: (in loc3_19 * 0x38<32> @ 000E005B : word32)
  Class: Eq_93
  DataType: int32
  OrigDataType: int32
T_94: (in arg1 + loc3_19 * 0x38<32> @ 000E005B : word32)
  Class: Eq_91
  DataType: (ptr32 Eq_91)
  OrigDataType: ptr32
T_95: (in 0x20<32> @ 000E00F8 : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_96: (in v56_53 + 0x20<32> @ 000E00F8 : word32)
  Class: Eq_96
  DataType: ptr32
  OrigDataType: ptr32
T_97: (in Mem135[v56_53 + 0x20<32>:real64] @ 000E00F8 : real64)
  Class: Eq_97
  DataType: real64
  OrigDataType: real64
T_98: (in v91_95 * v121_129 @ 000E00F8 : real64)
  Class: Eq_98
  DataType: real64
  OrigDataType: real64
T_99: (in v111_118 * (v91_95 * v121_129) @ 000E00F8 : real64)
  Class: Eq_99
  DataType: real64
  OrigDataType: real64
T_100: (in v56_53->r0020 - v111_118 * (v91_95 * v121_129) @ 000E00F8 : real64)
  Class: Eq_97
  DataType: real64
  OrigDataType: real64
T_101: (in v56_53 + 0x20<32> @ 000E00F8 : word32)
  Class: Eq_101
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_102: (in Mem145[v56_53 + 0x20<32>:real64] @ 000E00F8 : real64)
  Class: Eq_97
  DataType: real64
  OrigDataType: real64
T_103: (in v63_61 @ 000E0068 : (ptr32 Eq_103))
  Class: Eq_103
  DataType: (ptr32 Eq_103)
  OrigDataType: (ptr32 (struct (28 T_109 t0028)))
T_104: (in 0x38<32> @ 000E0068 : word32)
  Class: Eq_104
  DataType: ui32
  OrigDataType: ui32
T_105: (in loc3_19 * 0x38<32> @ 000E0068 : word32)
  Class: Eq_105
  DataType: int32
  OrigDataType: int32
T_106: (in arg1 + loc3_19 * 0x38<32> @ 000E0068 : word32)
  Class: Eq_103
  DataType: (ptr32 Eq_103)
  OrigDataType: ptr32
T_107: (in 0x28<32> @ 000E010B : word32)
  Class: Eq_107
  DataType: word32
  OrigDataType: word32
T_108: (in v63_61 + 0x28<32> @ 000E010B : word32)
  Class: Eq_108
  DataType: ptr32
  OrigDataType: ptr32
T_109: (in Mem145[v63_61 + 0x28<32>:real64] @ 000E010B : real64)
  Class: Eq_109
  DataType: real64
  OrigDataType: real64
T_110: (in v102_107 * v121_129 @ 000E010B : real64)
  Class: Eq_110
  DataType: real64
  OrigDataType: real64
T_111: (in v111_118 * (v102_107 * v121_129) @ 000E010B : real64)
  Class: Eq_111
  DataType: real64
  OrigDataType: real64
T_112: (in v63_61->r0028 - v111_118 * (v102_107 * v121_129) @ 000E010B : real64)
  Class: Eq_109
  DataType: real64
  OrigDataType: real64
T_113: (in v63_61 + 0x28<32> @ 000E010B : word32)
  Class: Eq_113
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_114: (in Mem155[v63_61 + 0x28<32>:real64] @ 000E010B : real64)
  Class: Eq_109
  DataType: real64
  OrigDataType: real64
T_115: (in v148_160 @ 000E0115 : (ptr32 Eq_115))
  Class: Eq_115
  DataType: (ptr32 Eq_115)
  OrigDataType: (ptr32 (struct (18 T_121 t0018)))
T_116: (in 0x38<32> @ 000E0115 : word32)
  Class: Eq_116
  DataType: ui32
  OrigDataType: ui32
T_117: (in v24_12 * 0x38<32> @ 000E0115 : word32)
  Class: Eq_117
  DataType: int32
  OrigDataType: int32
T_118: (in arg1 + v24_12 * 0x38<32> @ 000E0115 : word32)
  Class: Eq_115
  DataType: (ptr32 Eq_115)
  OrigDataType: ptr32
T_119: (in 0x18<32> @ 000E0129 : word32)
  Class: Eq_119
  DataType: word32
  OrigDataType: word32
T_120: (in v148_160 + 0x18<32> @ 000E0129 : word32)
  Class: Eq_120
  DataType: ptr32
  OrigDataType: ptr32
T_121: (in Mem155[v148_160 + 0x18<32>:real64] @ 000E0129 : real64)
  Class: Eq_121
  DataType: real64
  OrigDataType: real64
T_122: (in v81_84 * v71_70 @ 000E0129 : real64)
  Class: Eq_122
  DataType: real64
  OrigDataType: real64
T_123: (in v111_118 * (v81_84 * v71_70) @ 000E0129 : real64)
  Class: Eq_123
  DataType: real64
  OrigDataType: real64
T_124: (in v148_160->r0018 + v111_118 * (v81_84 * v71_70) @ 000E0129 : real64)
  Class: Eq_121
  DataType: real64
  OrigDataType: real64
T_125: (in v148_160 + 0x18<32> @ 000E0129 : word32)
  Class: Eq_125
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_126: (in Mem172[v148_160 + 0x18<32>:real64] @ 000E0129 : real64)
  Class: Eq_121
  DataType: real64
  OrigDataType: real64
T_127: (in v163_177 @ 000E0133 : (ptr32 Eq_127))
  Class: Eq_127
  DataType: (ptr32 Eq_127)
  OrigDataType: (ptr32 (struct (20 T_133 t0020)))
T_128: (in 0x38<32> @ 000E0133 : word32)
  Class: Eq_128
  DataType: ui32
  OrigDataType: ui32
T_129: (in v24_12 * 0x38<32> @ 000E0133 : word32)
  Class: Eq_129
  DataType: int32
  OrigDataType: int32
T_130: (in arg1 + v24_12 * 0x38<32> @ 000E0133 : word32)
  Class: Eq_127
  DataType: (ptr32 Eq_127)
  OrigDataType: ptr32
T_131: (in 0x20<32> @ 000E0147 : word32)
  Class: Eq_131
  DataType: word32
  OrigDataType: word32
T_132: (in v163_177 + 0x20<32> @ 000E0147 : word32)
  Class: Eq_132
  DataType: ptr32
  OrigDataType: ptr32
T_133: (in Mem172[v163_177 + 0x20<32>:real64] @ 000E0147 : real64)
  Class: Eq_133
  DataType: real64
  OrigDataType: real64
T_134: (in v91_95 * v71_70 @ 000E0147 : real64)
  Class: Eq_134
  DataType: real64
  OrigDataType: real64
T_135: (in v111_118 * (v91_95 * v71_70) @ 000E0147 : real64)
  Class: Eq_135
  DataType: real64
  OrigDataType: real64
T_136: (in v163_177->r0020 + v111_118 * (v91_95 * v71_70) @ 000E0147 : real64)
  Class: Eq_133
  DataType: real64
  OrigDataType: real64
T_137: (in v163_177 + 0x20<32> @ 000E0147 : word32)
  Class: Eq_137
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_138: (in Mem189[v163_177 + 0x20<32>:real64] @ 000E0147 : real64)
  Class: Eq_133
  DataType: real64
  OrigDataType: real64
T_139: (in v178_194 @ 000E0151 : (ptr32 Eq_139))
  Class: Eq_139
  DataType: (ptr32 Eq_139)
  OrigDataType: (ptr32 (struct (28 T_145 t0028)))
T_140: (in 0x38<32> @ 000E0151 : word32)
  Class: Eq_140
  DataType: ui32
  OrigDataType: ui32
T_141: (in v24_12 * 0x38<32> @ 000E0151 : word32)
  Class: Eq_141
  DataType: int32
  OrigDataType: int32
T_142: (in arg1 + v24_12 * 0x38<32> @ 000E0151 : word32)
  Class: Eq_139
  DataType: (ptr32 Eq_139)
  OrigDataType: ptr32
T_143: (in 0x28<32> @ 000E0165 : word32)
  Class: Eq_143
  DataType: word32
  OrigDataType: word32
T_144: (in v178_194 + 0x28<32> @ 000E0165 : word32)
  Class: Eq_144
  DataType: ptr32
  OrigDataType: ptr32
T_145: (in Mem189[v178_194 + 0x28<32>:real64] @ 000E0165 : real64)
  Class: Eq_145
  DataType: real64
  OrigDataType: real64
T_146: (in v102_107 * v71_70 @ 000E0165 : real64)
  Class: Eq_146
  DataType: real64
  OrigDataType: real64
T_147: (in v111_118 * (v102_107 * v71_70) @ 000E0165 : real64)
  Class: Eq_147
  DataType: real64
  OrigDataType: real64
T_148: (in v178_194->r0028 + v111_118 * (v102_107 * v71_70) @ 000E0165 : real64)
  Class: Eq_145
  DataType: real64
  OrigDataType: real64
T_149: (in v178_194 + 0x28<32> @ 000E0165 : word32)
  Class: Eq_149
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_150: (in Mem206[v178_194 + 0x28<32>:real64] @ 000E0165 : real64)
  Class: Eq_145
  DataType: real64
  OrigDataType: real64
T_151: (in 1<32> @ 000E016D : word32)
  Class: Eq_151
  DataType: word32
  OrigDataType: word32
T_152: (in v24_12 + 1<32> @ 000E016D : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_153: (in v24_12 + 1<32> @ 000E0172 : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: int32
T_154: (in v24_12 + 1<32> != arg0 @ 000E0172 : bool)
  Class: Eq_154
  DataType: bool
  OrigDataType: bool
T_155: (in v24_12 != arg0 @ 000E017B : bool)
  Class: Eq_155
  DataType: bool
  OrigDataType: bool
T_156: (in !(v24_12 != arg0) @ 000E017B : bool)
  Class: Eq_156
  DataType: bool
  OrigDataType: bool
T_157: (in arg0 > 0<32> @ 000E0187 : bool)
  Class: Eq_157
  DataType: bool
  OrigDataType: bool
T_158: (in !(arg0 > 0<32>) @ 000E0187 : bool)
  Class: Eq_158
  DataType: bool
  OrigDataType: bool
T_159: (in loc4_220 @ 000E018B : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: ui32
T_160: (in 0<32> @ 000E018B : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: word32
T_161: (in v204_227 @ 000E0199 : (ptr32 real64))
  Class: Eq_161
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 (struct (0 T_167 t0000)))
T_162: (in 0x38<32> @ 000E0199 : word32)
  Class: Eq_162
  DataType: ui32
  OrigDataType: ui32
T_163: (in loc4_220 * 0x38<32> @ 000E0199 : word32)
  Class: Eq_163
  DataType: int32
  OrigDataType: int32
T_164: (in arg1 + loc4_220 * 0x38<32> @ 000E0199 : word32)
  Class: Eq_161
  DataType: (ptr32 real64)
  OrigDataType: ptr32
T_165: (in 0<32> @ 000E01B0 : word32)
  Class: Eq_165
  DataType: word32
  OrigDataType: word32
T_166: (in v204_227 + 0<32> @ 000E01B0 : word32)
  Class: Eq_166
  DataType: ptr32
  OrigDataType: ptr32
T_167: (in Mem230[v204_227 + 0<32>:real64] @ 000E01B0 : real64)
  Class: Eq_167
  DataType: real64
  OrigDataType: real64
T_168: (in 0x38<32> @ 000E01B0 : word32)
  Class: Eq_168
  DataType: ui32
  OrigDataType: ui32
T_169: (in loc4_220 * 0x38<32> @ 000E01B0 : word32)
  Class: Eq_169
  DataType: int32
  OrigDataType: int32
T_170: (in arg1 + loc4_220 * 0x38<32> @ 000E01B0 : word32)
  Class: Eq_170
  DataType: (ptr32 Eq_170)
  OrigDataType: (ptr32 (struct (18 T_173 t0018)))
T_171: (in 0x18<u32> @ 000E01B0 : uint32)
  Class: Eq_171
  DataType: uint32
  OrigDataType: uint32
T_172: (in arg1 + loc4_220 * 0x38<32> + 0x18<u32> @ 000E01B0 : word32)
  Class: Eq_172
  DataType: ptr32
  OrigDataType: ptr32
T_173: (in Mem230[arg1 + loc4_220 * 0x38<32> + 0x18<u32>:real64] @ 000E01B0 : real64)
  Class: Eq_173
  DataType: real64
  OrigDataType: real64
T_174: (in (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0018 * arg2 @ 000E01B0 : real64)
  Class: Eq_174
  DataType: real64
  OrigDataType: real64
T_175: (in *v204_227 + (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0018 * arg2 @ 000E01B0 : real64)
  Class: Eq_167
  DataType: real64
  OrigDataType: real64
T_176: (in 0<32> @ 000E01B0 : word32)
  Class: Eq_176
  DataType: word32
  OrigDataType: word32
T_177: (in v204_227 + 0<32> @ 000E01B0 : word32)
  Class: Eq_177
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_178: (in Mem242[v204_227 + 0<32>:real64] @ 000E01B0 : real64)
  Class: Eq_167
  DataType: real64
  OrigDataType: real64
T_179: (in v220_247 @ 000E01BA : (ptr32 Eq_179))
  Class: Eq_179
  DataType: (ptr32 Eq_179)
  OrigDataType: (ptr32 (struct (8 T_185 t0008)))
T_180: (in 0x38<32> @ 000E01BA : word32)
  Class: Eq_180
  DataType: ui32
  OrigDataType: ui32
T_181: (in loc4_220 * 0x38<32> @ 000E01BA : word32)
  Class: Eq_181
  DataType: int32
  OrigDataType: int32
T_182: (in arg1 + loc4_220 * 0x38<32> @ 000E01BA : word32)
  Class: Eq_179
  DataType: (ptr32 Eq_179)
  OrigDataType: ptr32
T_183: (in 8<32> @ 000E01D4 : word32)
  Class: Eq_183
  DataType: word32
  OrigDataType: word32
T_184: (in v220_247 + 8<32> @ 000E01D4 : word32)
  Class: Eq_184
  DataType: ptr32
  OrigDataType: ptr32
T_185: (in Mem242[v220_247 + 8<32>:real64] @ 000E01D4 : real64)
  Class: Eq_185
  DataType: real64
  OrigDataType: real64
T_186: (in 0x38<32> @ 000E01D4 : word32)
  Class: Eq_186
  DataType: ui32
  OrigDataType: ui32
T_187: (in loc4_220 * 0x38<32> @ 000E01D4 : word32)
  Class: Eq_187
  DataType: int32
  OrigDataType: int32
T_188: (in arg1 + loc4_220 * 0x38<32> @ 000E01D4 : word32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (struct (20 T_191 t0020)))
T_189: (in 0x20<u32> @ 000E01D4 : uint32)
  Class: Eq_189
  DataType: uint32
  OrigDataType: uint32
T_190: (in arg1 + loc4_220 * 0x38<32> + 0x20<u32> @ 000E01D4 : word32)
  Class: Eq_190
  DataType: ptr32
  OrigDataType: ptr32
T_191: (in Mem242[arg1 + loc4_220 * 0x38<32> + 0x20<u32>:real64] @ 000E01D4 : real64)
  Class: Eq_191
  DataType: real64
  OrigDataType: real64
T_192: (in (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0020 * arg2 @ 000E01D4 : real64)
  Class: Eq_192
  DataType: real64
  OrigDataType: real64
T_193: (in v220_247->r0008 + (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0020 * arg2 @ 000E01D4 : real64)
  Class: Eq_185
  DataType: real64
  OrigDataType: real64
T_194: (in v220_247 + 8<32> @ 000E01D4 : word32)
  Class: Eq_194
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_195: (in Mem262[v220_247 + 8<32>:real64] @ 000E01D4 : real64)
  Class: Eq_185
  DataType: real64
  OrigDataType: real64
T_196: (in v238_267 @ 000E01DE : (ptr32 Eq_196))
  Class: Eq_196
  DataType: (ptr32 Eq_196)
  OrigDataType: (ptr32 (struct (10 T_202 t0010)))
T_197: (in 0x38<32> @ 000E01DE : word32)
  Class: Eq_197
  DataType: ui32
  OrigDataType: ui32
T_198: (in loc4_220 * 0x38<32> @ 000E01DE : word32)
  Class: Eq_198
  DataType: int32
  OrigDataType: int32
T_199: (in arg1 + loc4_220 * 0x38<32> @ 000E01DE : word32)
  Class: Eq_196
  DataType: (ptr32 Eq_196)
  OrigDataType: ptr32
T_200: (in 0x10<32> @ 000E01F8 : word32)
  Class: Eq_200
  DataType: word32
  OrigDataType: word32
T_201: (in v238_267 + 0x10<32> @ 000E01F8 : word32)
  Class: Eq_201
  DataType: ptr32
  OrigDataType: ptr32
T_202: (in Mem262[v238_267 + 0x10<32>:real64] @ 000E01F8 : real64)
  Class: Eq_202
  DataType: real64
  OrigDataType: real64
T_203: (in 0x38<32> @ 000E01F8 : word32)
  Class: Eq_203
  DataType: ui32
  OrigDataType: ui32
T_204: (in loc4_220 * 0x38<32> @ 000E01F8 : word32)
  Class: Eq_204
  DataType: int32
  OrigDataType: int32
T_205: (in arg1 + loc4_220 * 0x38<32> @ 000E01F8 : word32)
  Class: Eq_205
  DataType: (ptr32 Eq_205)
  OrigDataType: (ptr32 (struct (28 T_208 t0028)))
T_206: (in 0x28<u32> @ 000E01F8 : uint32)
  Class: Eq_206
  DataType: uint32
  OrigDataType: uint32
T_207: (in arg1 + loc4_220 * 0x38<32> + 0x28<u32> @ 000E01F8 : word32)
  Class: Eq_207
  DataType: ptr32
  OrigDataType: ptr32
T_208: (in Mem262[arg1 + loc4_220 * 0x38<32> + 0x28<u32>:real64] @ 000E01F8 : real64)
  Class: Eq_208
  DataType: real64
  OrigDataType: real64
T_209: (in (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0028 * arg2 @ 000E01F8 : real64)
  Class: Eq_209
  DataType: real64
  OrigDataType: real64
T_210: (in v238_267->r0010 + (arg1 + (loc4_220 * 0x38<32>) / 280<i32>)->r0028 * arg2 @ 000E01F8 : real64)
  Class: Eq_202
  DataType: real64
  OrigDataType: real64
T_211: (in v238_267 + 0x10<32> @ 000E01F8 : word32)
  Class: Eq_211
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_212: (in Mem282[v238_267 + 0x10<32>:real64] @ 000E01F8 : real64)
  Class: Eq_202
  DataType: real64
  OrigDataType: real64
T_213: (in v254_285 @ 000E01FF : int32)
  Class: Eq_2
  DataType: int32
  OrigDataType: ui32
T_214: (in 1<32> @ 000E01FF : word32)
  Class: Eq_214
  DataType: word32
  OrigDataType: word32
T_215: (in loc4_220 + 1<32> @ 000E01FF : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: ui32
T_216: (in v254_285 != arg0 @ 000E0205 : bool)
  Class: Eq_216
  DataType: bool
  OrigDataType: bool
T_217: (in  @ 000E0209 : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_218: (in arg0 @ 000E0209 : int32)
  Class: Eq_218
  DataType: int32
  OrigDataType: int32
T_219: (in arg1 @ 000E0209 : ptr32)
  Class: Eq_219
  DataType: ptr32
  OrigDataType: ptr32
T_220: (in 0<32> @ 000E0211 : word32)
  Class: Eq_218
  DataType: int32
  OrigDataType: int32
T_221: (in arg0 > 0<32> @ 000E0211 : bool)
  Class: Eq_221
  DataType: bool
  OrigDataType: bool
T_222: (in !(arg0 > 0<32>) @ 000E0211 : bool)
  Class: Eq_222
  DataType: bool
  OrigDataType: bool
T_223: (in loc2_15 @ 000E0215 : int32)
  Class: Eq_218
  DataType: int32
  OrigDataType: int32
T_224: (in 0<32> @ 000E0215 : word32)
  Class: Eq_218
  DataType: int32
  OrigDataType: word32
T_225: (in loc4_10 @ 000E0220 : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_226: (in 0.0 @ 000E0220 : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_227: (in 0.0 @ 000E022C : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_228: (in v29_30 @ 000E0251 : real64)
  Class: Eq_228
  DataType: real64
  OrigDataType: real64
T_229: (in 0x38<32> @ 000E0251 : word32)
  Class: Eq_229
  DataType: ui32
  OrigDataType: ui32
T_230: (in loc2_15 * 0x38<32> @ 000E0251 : word32)
  Class: Eq_230
  DataType: int32
  OrigDataType: int32
T_231: (in arg1 + loc2_15 * 0x38<32> @ 000E0251 : word32)
  Class: Eq_231
  DataType: (ptr32 Eq_231)
  OrigDataType: (ptr32 (struct (18 T_234 t0018)))
T_232: (in 0x18<u32> @ 000E0251 : uint32)
  Class: Eq_232
  DataType: uint32
  OrigDataType: uint32
T_233: (in arg1 + loc2_15 * 0x38<32> + 0x18<u32> @ 000E0251 : word32)
  Class: Eq_233
  DataType: word32
  OrigDataType: word32
T_234: (in Mem0[arg1 + loc2_15 * 0x38<32> + 0x18<u32>:real64] @ 000E0251 : real64)
  Class: Eq_228
  DataType: real64
  OrigDataType: real64
T_235: (in v37_39 @ 000E0261 : real64)
  Class: Eq_235
  DataType: real64
  OrigDataType: real64
T_236: (in 0x38<32> @ 000E0261 : word32)
  Class: Eq_236
  DataType: ui32
  OrigDataType: ui32
T_237: (in loc2_15 * 0x38<32> @ 000E0261 : word32)
  Class: Eq_237
  DataType: int32
  OrigDataType: int32
T_238: (in arg1 + loc2_15 * 0x38<32> @ 000E0261 : word32)
  Class: Eq_238
  DataType: (ptr32 Eq_238)
  OrigDataType: (ptr32 (struct (20 T_241 t0020)))
T_239: (in 0x20<u32> @ 000E0261 : uint32)
  Class: Eq_239
  DataType: uint32
  OrigDataType: uint32
T_240: (in arg1 + loc2_15 * 0x38<32> + 0x20<u32> @ 000E0261 : word32)
  Class: Eq_240
  DataType: ptr32
  OrigDataType: ptr32
T_241: (in Mem0[arg1 + loc2_15 * 0x38<32> + 0x20<u32>:real64] @ 000E0261 : real64)
  Class: Eq_235
  DataType: real64
  OrigDataType: real64
T_242: (in v46_49 @ 000E0272 : real64)
  Class: Eq_242
  DataType: real64
  OrigDataType: real64
T_243: (in 0x38<32> @ 000E0272 : word32)
  Class: Eq_243
  DataType: ui32
  OrigDataType: ui32
T_244: (in loc2_15 * 0x38<32> @ 000E0272 : word32)
  Class: Eq_244
  DataType: int32
  OrigDataType: int32
T_245: (in arg1 + loc2_15 * 0x38<32> @ 000E0272 : word32)
  Class: Eq_245
  DataType: (ptr32 Eq_245)
  OrigDataType: (ptr32 (struct (28 T_248 t0028)))
T_246: (in 0x28<u32> @ 000E0272 : uint32)
  Class: Eq_246
  DataType: uint32
  OrigDataType: uint32
T_247: (in arg1 + loc2_15 * 0x38<32> + 0x28<u32> @ 000E0272 : word32)
  Class: Eq_247
  DataType: ptr32
  OrigDataType: ptr32
T_248: (in Mem0[arg1 + loc2_15 * 0x38<32> + 0x28<u32>:real64] @ 000E0272 : real64)
  Class: Eq_242
  DataType: real64
  OrigDataType: real64
T_249: (in v51_55 @ 000E027C : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_250: (in 0x38<32> @ 000E027C : word32)
  Class: Eq_250
  DataType: ui32
  OrigDataType: ui32
T_251: (in loc2_15 * 0x38<32> @ 000E027C : word32)
  Class: Eq_251
  DataType: int32
  OrigDataType: int32
T_252: (in arg1 + loc2_15 * 0x38<32> @ 000E027C : word32)
  Class: Eq_252
  DataType: (ptr32 Eq_252)
  OrigDataType: (ptr32 (struct (30 T_255 t0030)))
T_253: (in 0x30<u32> @ 000E027C : uint32)
  Class: Eq_253
  DataType: uint32
  OrigDataType: uint32
T_254: (in arg1 + loc2_15 * 0x38<32> + 0x30<u32> @ 000E027C : word32)
  Class: Eq_254
  DataType: ptr32
  OrigDataType: ptr32
T_255: (in Mem0[arg1 + loc2_15 * 0x38<32> + 0x30<u32>:real64] @ 000E027C : real64)
  Class: Eq_255
  DataType: real64
  OrigDataType: real64
T_256: (in 0.5 @ 000E027C : real64)
  Class: Eq_256
  DataType: real64
  OrigDataType: real64
T_257: (in (arg1 + loc2_15 * 0x38<32>)->r0030 * 0.5 @ 000E027C : real64)
  Class: Eq_257
  DataType: real64
  OrigDataType: real64
T_258: (in v29_30 * v29_30 @ 000E027C : real64)
  Class: Eq_258
  DataType: real64
  OrigDataType: real64
T_259: (in v37_39 * v37_39 @ 000E027C : real64)
  Class: Eq_259
  DataType: real64
  OrigDataType: real64
T_260: (in v29_30 * v29_30 + v37_39 * v37_39 @ 000E027C : real64)
  Class: Eq_260
  DataType: real64
  OrigDataType: real64
T_261: (in v46_49 * v46_49 @ 000E027C : real64)
  Class: Eq_261
  DataType: real64
  OrigDataType: real64
T_262: (in v29_30 * v29_30 + v37_39 * v37_39 + v46_49 * v46_49 @ 000E027C : real64)
  Class: Eq_262
  DataType: real64
  OrigDataType: real64
T_263: (in (arg1 + loc2_15 * 0x38<32>)->r0030 * 0.5 * ((v29_30 * v29_30 + v37_39 * v37_39) + v46_49 * v46_49) @ 000E027C : real64)
  Class: Eq_263
  DataType: real64
  OrigDataType: real64
T_264: (in loc4_10 + ((arg1 + loc2_15 * 0x38<32>)->r0030 * 0.5) * ((v29_30 * v29_30 + v37_39 * v37_39) + v46_49 * v46_49) @ 000E027C : real64)
  Class: Eq_217
  DataType: real64
  OrigDataType: real64
T_265: (in v54_59 @ 000E0283 : int32)
  Class: Eq_218
  DataType: int32
  OrigDataType: int32
T_266: (in 1<32> @ 000E0283 : word32)
  Class: Eq_266
  DataType: word32
  OrigDataType: word32
T_267: (in loc2_15 + 1<32> @ 000E0283 : word32)
  Class: Eq_218
  DataType: int32
  OrigDataType: ui32
T_268: (in v54_59 < arg0 @ 000E0289 : bool)
  Class: Eq_268
  DataType: bool
  OrigDataType: bool
T_269: (in !(v54_59 < arg0) @ 000E0289 : bool)
  Class: Eq_269
  DataType: bool
  OrigDataType: bool
T_270: (in 1<32> @ 000E0312 : word32)
  Class: Eq_270
  DataType: word32
  OrigDataType: word32
T_271: (in v54_59 + 1<32> @ 000E0312 : word32)
  Class: Eq_218
  DataType: int32
  OrigDataType: int32
T_272: (in v54_59 + 1<32> != arg0 @ 000E0312 : bool)
  Class: Eq_272
  DataType: bool
  OrigDataType: bool
T_273: (in v54_59 != arg0 @ 000E031B : bool)
  Class: Eq_273
  DataType: bool
  OrigDataType: bool
T_274: (in !(v54_59 != arg0) @ 000E031B : bool)
  Class: Eq_274
  DataType: bool
  OrigDataType: bool
T_275: (in arg0 @ 000E0328 : int32)
  Class: Eq_275
  DataType: int32
  OrigDataType: int32
T_276: (in arg1 @ 000E0328 : (ptr32 Eq_276))
  Class: Eq_276
  DataType: (ptr32 Eq_276)
  OrigDataType: (ptr32 (struct (18 T_289 t0018) (20 T_295 t0020) (28 T_301 t0028) (30 T_286 t0030)))
T_277: (in loc3_60 @ 000E0329 : real64)
  Class: Eq_277
  DataType: real64
  OrigDataType: real64
T_278: (in loc4_49 @ 000E0329 : real64)
  Class: Eq_278
  DataType: real64
  OrigDataType: real64
T_279: (in loc5_11 @ 000E0329 : real64)
  Class: Eq_279
  DataType: real64
  OrigDataType: real64
T_280: (in 0<32> @ 000E0330 : word32)
  Class: Eq_275
  DataType: int32
  OrigDataType: int32
T_281: (in arg0 > 0<32> @ 000E0330 : bool)
  Class: Eq_281
  DataType: bool
  OrigDataType: bool
T_282: (in !(arg0 > 0<32>) @ 000E0330 : bool)
  Class: Eq_282
  DataType: bool
  OrigDataType: bool
T_283: (in v26_34 @ 000E036E : real64)
  Class: Eq_283
  DataType: real64
  OrigDataType: real64
T_284: (in 0x30<u32> @ 000E036E : uint32)
  Class: Eq_284
  DataType: uint32
  OrigDataType: uint32
T_285: (in arg1 + 0x30<u32> @ 000E036E : word32)
  Class: Eq_285
  DataType: word32
  OrigDataType: word32
T_286: (in Mem0[arg1 + 0x30<u32>:real64] @ 000E036E : real64)
  Class: Eq_283
  DataType: real64
  OrigDataType: real64
T_287: (in 0x18<u32> @ 000E0375 : uint32)
  Class: Eq_287
  DataType: uint32
  OrigDataType: uint32
T_288: (in arg1 + 0x18<u32> @ 000E0375 : word32)
  Class: Eq_288
  DataType: ptr32
  OrigDataType: ptr32
T_289: (in Mem0[arg1 + 0x18<u32>:real64] @ 000E0375 : real64)
  Class: Eq_289
  DataType: real64
  OrigDataType: real64
T_290: (in arg1->r0018 * v26_34 @ 000E0375 : real64)
  Class: Eq_290
  DataType: real64
  OrigDataType: real64
T_291: (in 0.0 @ 000E0375 : real64)
  Class: Eq_291
  DataType: real64
  OrigDataType: real64
T_292: (in arg1->r0018 * v26_34 + 0.0 @ 000E0375 : real64)
  Class: Eq_279
  DataType: real64
  OrigDataType: real64
T_293: (in 0x20<u32> @ 000E0388 : uint32)
  Class: Eq_293
  DataType: uint32
  OrigDataType: uint32
T_294: (in arg1 + 0x20<u32> @ 000E0388 : word32)
  Class: Eq_294
  DataType: ptr32
  OrigDataType: ptr32
T_295: (in Mem0[arg1 + 0x20<u32>:real64] @ 000E0388 : real64)
  Class: Eq_295
  DataType: real64
  OrigDataType: real64
T_296: (in v26_34 * arg1->r0020 @ 000E0388 : real64)
  Class: Eq_296
  DataType: real64
  OrigDataType: real64
T_297: (in 0.0 @ 000E0388 : real64)
  Class: Eq_297
  DataType: real64
  OrigDataType: real64
T_298: (in v26_34 * arg1->r0020 + 0.0 @ 000E0388 : real64)
  Class: Eq_278
  DataType: real64
  OrigDataType: real64
T_299: (in 0x28<u32> @ 000E039B : uint32)
  Class: Eq_299
  DataType: uint32
  OrigDataType: uint32
T_300: (in arg1 + 0x28<u32> @ 000E039B : word32)
  Class: Eq_300
  DataType: ptr32
  OrigDataType: ptr32
T_301: (in Mem0[arg1 + 0x28<u32>:real64] @ 000E039B : real64)
  Class: Eq_301
  DataType: real64
  OrigDataType: real64
T_302: (in v26_34 * arg1->r0028 @ 000E039B : real64)
  Class: Eq_302
  DataType: real64
  OrigDataType: real64
T_303: (in 0.0 @ 000E039B : real64)
  Class: Eq_303
  DataType: real64
  OrigDataType: real64
T_304: (in v26_34 * arg1->r0028 + 0.0 @ 000E039B : real64)
  Class: Eq_277
  DataType: real64
  OrigDataType: real64
T_305: (in 1<32> @ 000E03A7 : word32)
  Class: Eq_275
  DataType: int32
  OrigDataType: word32
T_306: (in arg0 != 1<32> @ 000E03A7 : bool)
  Class: Eq_306
  DataType: bool
  OrigDataType: bool
T_307: (in 0.0 @ 000E03B4 : real64)
  Class: Eq_277
  DataType: real64
  OrigDataType: real64
T_308: (in 0.0 @ 000E03BF : real64)
  Class: Eq_278
  DataType: real64
  OrigDataType: real64
T_309: (in 0.0 @ 000E03CA : real64)
  Class: Eq_279
  DataType: real64
  OrigDataType: real64
T_310: (in -loc5_11 @ 000E03DC : real64)
  Class: Eq_310
  DataType: real64
  OrigDataType: real64
T_311: (in 39.47841760435743 @ 000E03DC : real64)
  Class: Eq_311
  DataType: real64
  OrigDataType: real64
T_312: (in -loc5_11 / 39.47841760435743 @ 000E03DC : real64)
  Class: Eq_289
  DataType: real64
  OrigDataType: real64
T_313: (in 0x18<u32> @ 000E03DC : uint32)
  Class: Eq_313
  DataType: uint32
  OrigDataType: uint32
T_314: (in arg1 + 0x18<u32> @ 000E03DC : word32)
  Class: Eq_314
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_315: (in Mem77[arg1 + 0x18<u32>:real64] @ 000E03DC : real64)
  Class: Eq_289
  DataType: real64
  OrigDataType: real64
T_316: (in -loc4_49 @ 000E03EE : real64)
  Class: Eq_316
  DataType: real64
  OrigDataType: real64
T_317: (in 39.47841760435743 @ 000E03EE : real64)
  Class: Eq_317
  DataType: real64
  OrigDataType: real64
T_318: (in -loc4_49 / 39.47841760435743 @ 000E03EE : real64)
  Class: Eq_295
  DataType: real64
  OrigDataType: real64
T_319: (in 0x20<u32> @ 000E03EE : uint32)
  Class: Eq_319
  DataType: uint32
  OrigDataType: uint32
T_320: (in arg1 + 0x20<u32> @ 000E03EE : word32)
  Class: Eq_320
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_321: (in Mem84[arg1 + 0x20<u32>:real64] @ 000E03EE : real64)
  Class: Eq_295
  DataType: real64
  OrigDataType: real64
T_322: (in -loc3_60 @ 000E0400 : real64)
  Class: Eq_322
  DataType: real64
  OrigDataType: real64
T_323: (in 39.47841760435743 @ 000E0400 : real64)
  Class: Eq_323
  DataType: real64
  OrigDataType: real64
T_324: (in -loc3_60 / 39.47841760435743 @ 000E0400 : real64)
  Class: Eq_301
  DataType: real64
  OrigDataType: real64
T_325: (in 0x28<u32> @ 000E0400 : uint32)
  Class: Eq_325
  DataType: uint32
  OrigDataType: uint32
T_326: (in arg1 + 0x28<u32> @ 000E0400 : word32)
  Class: Eq_326
  DataType: (ptr32 real64)
  OrigDataType: (ptr32 real64)
T_327: (in Mem91[arg1 + 0x28<u32>:real64] @ 000E0400 : real64)
  Class: Eq_301
  DataType: real64
  OrigDataType: real64
T_328: (in  @ 000E0404 : real64)
  Class: Eq_328
  DataType: real64
  OrigDataType: real64
T_329: (in v12_3 @ 000E0409 : real64)
  Class: Eq_329
  DataType: real64
  OrigDataType: real64
T_330: (in 00100000 @ 000E0409 : ptr32)
  Class: Eq_330
  DataType: (ptr32 (ptr32 Eq_3))
  OrigDataType: (ptr32 (struct (0 T_3 t0000)))
T_331: (in Mem1[0x00100000<p32>:word32] @ 000E0409 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030)))
T_332: (in 0x30<u32> @ 000E0409 : uint32)
  Class: Eq_332
  DataType: uint32
  OrigDataType: uint32
T_333: (in Mem1[0x00100000<p32>:word32] + 0x30<u32> @ 000E0409 : word32)
  Class: Eq_333
  DataType: word32
  OrigDataType: word32
T_334: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x30<u32>:real64] @ 000E0409 : real64)
  Class: Eq_329
  DataType: real64
  OrigDataType: real64
T_335: (in v19_11 @ 000E0420 : real64)
  Class: Eq_335
  DataType: real64
  OrigDataType: real64
T_336: (in Mem1[0x00100000<p32>:word32] @ 000E0420 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (68 T_339 t0068)))
T_337: (in 0x68<u32> @ 000E0420 : uint32)
  Class: Eq_337
  DataType: uint32
  OrigDataType: uint32
T_338: (in Mem1[0x00100000<p32>:word32] + 0x68<u32> @ 000E0420 : word32)
  Class: Eq_338
  DataType: ptr32
  OrigDataType: ptr32
T_339: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x68<u32>:real64] @ 000E0420 : real64)
  Class: Eq_335
  DataType: real64
  OrigDataType: real64
T_340: (in v25_18 @ 000E042E : real64)
  Class: Eq_340
  DataType: real64
  OrigDataType: real64
T_341: (in Mem1[0x00100000<p32>:word32] @ 000E042E : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (A0 T_344 t00A0)))
T_342: (in 0xA0<u32> @ 000E042E : uint32)
  Class: Eq_342
  DataType: uint32
  OrigDataType: uint32
T_343: (in Mem1[0x00100000<p32>:word32] + 0xA0<u32> @ 000E042E : word32)
  Class: Eq_343
  DataType: ptr32
  OrigDataType: ptr32
T_344: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xA0<u32>:real64] @ 000E042E : real64)
  Class: Eq_340
  DataType: real64
  OrigDataType: real64
T_345: (in v31_25 @ 000E043E : real64)
  Class: Eq_345
  DataType: real64
  OrigDataType: real64
T_346: (in Mem1[0x00100000<p32>:word32] @ 000E043E : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (D8 T_349 t00D8)))
T_347: (in 0xD8<u32> @ 000E043E : uint32)
  Class: Eq_347
  DataType: uint32
  OrigDataType: uint32
T_348: (in Mem1[0x00100000<p32>:word32] + 0xD8<u32> @ 000E043E : word32)
  Class: Eq_348
  DataType: ptr32
  OrigDataType: ptr32
T_349: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xD8<u32>:real64] @ 000E043E : real64)
  Class: Eq_345
  DataType: real64
  OrigDataType: real64
T_350: (in v37_32 @ 000E044E : real64)
  Class: Eq_350
  DataType: real64
  OrigDataType: real64
T_351: (in Mem1[0x00100000<p32>:word32] @ 000E044E : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (110 T_354 t0110)))
T_352: (in 0x110<u32> @ 000E044E : uint32)
  Class: Eq_352
  DataType: uint32
  OrigDataType: uint32
T_353: (in Mem1[0x00100000<p32>:word32] + 0x110<u32> @ 000E044E : word32)
  Class: Eq_353
  DataType: ptr32
  OrigDataType: ptr32
T_354: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x110<u32>:real64] @ 000E044E : real64)
  Class: Eq_350
  DataType: real64
  OrigDataType: real64
T_355: (in v41_37 @ 000E045B : real64)
  Class: Eq_355
  DataType: real64
  OrigDataType: real64
T_356: (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (20 T_359 t0020) (30 T_334 t0030)))
T_357: (in 0x20<u32> @ 000E045B : uint32)
  Class: Eq_357
  DataType: uint32
  OrigDataType: uint32
T_358: (in Mem1[0x00100000<p32>:word32] + 0x20<u32> @ 000E045B : word32)
  Class: Eq_358
  DataType: ptr32
  OrigDataType: ptr32
T_359: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x20<u32>:real64] @ 000E045B : real64)
  Class: Eq_359
  DataType: real64
  OrigDataType: real64
T_360: (in v12_3 * g_ptr100000->r0020 @ 000E045B : real64)
  Class: Eq_360
  DataType: real64
  OrigDataType: real64
T_361: (in 0.0 @ 000E045B : real64)
  Class: Eq_361
  DataType: real64
  OrigDataType: real64
T_362: (in v12_3 * g_ptr100000->r0020 + 0.0 @ 000E045B : real64)
  Class: Eq_362
  DataType: real64
  OrigDataType: real64
T_363: (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (58 T_366 t0058)))
T_364: (in 0x58<u32> @ 000E045B : uint32)
  Class: Eq_364
  DataType: uint32
  OrigDataType: uint32
T_365: (in Mem1[0x00100000<p32>:word32] + 0x58<u32> @ 000E045B : word32)
  Class: Eq_365
  DataType: ptr32
  OrigDataType: ptr32
T_366: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x58<u32>:real64] @ 000E045B : real64)
  Class: Eq_366
  DataType: real64
  OrigDataType: real64
T_367: (in v19_11 * g_ptr100000->r0058 @ 000E045B : real64)
  Class: Eq_367
  DataType: real64
  OrigDataType: real64
T_368: (in v12_3 * g_ptr100000->r0020 + 0.0 + v19_11 * g_ptr100000->r0058 @ 000E045B : real64)
  Class: Eq_368
  DataType: real64
  OrigDataType: real64
T_369: (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (90 T_372 t0090)))
T_370: (in 0x90<u32> @ 000E045B : uint32)
  Class: Eq_370
  DataType: uint32
  OrigDataType: uint32
T_371: (in Mem1[0x00100000<p32>:word32] + 0x90<u32> @ 000E045B : word32)
  Class: Eq_371
  DataType: ptr32
  OrigDataType: ptr32
T_372: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x90<u32>:real64] @ 000E045B : real64)
  Class: Eq_372
  DataType: real64
  OrigDataType: real64
T_373: (in v25_18 * g_ptr100000->r0090 @ 000E045B : real64)
  Class: Eq_373
  DataType: real64
  OrigDataType: real64
T_374: (in v12_3 * g_ptr100000->r0020 + 0.0 + v19_11 * g_ptr100000->r0058 + v25_18 * g_ptr100000->r0090 @ 000E045B : real64)
  Class: Eq_374
  DataType: real64
  OrigDataType: real64
T_375: (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (C8 T_378 t00C8)))
T_376: (in 0xC8<u32> @ 000E045B : uint32)
  Class: Eq_376
  DataType: uint32
  OrigDataType: uint32
T_377: (in Mem1[0x00100000<p32>:word32] + 0xC8<u32> @ 000E045B : word32)
  Class: Eq_377
  DataType: ptr32
  OrigDataType: ptr32
T_378: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xC8<u32>:real64] @ 000E045B : real64)
  Class: Eq_378
  DataType: real64
  OrigDataType: real64
T_379: (in v31_25 * g_ptr100000->r00C8 @ 000E045B : real64)
  Class: Eq_379
  DataType: real64
  OrigDataType: real64
T_380: (in v12_3 * g_ptr100000->r0020 + 0.0 + v19_11 * g_ptr100000->r0058 + v25_18 * g_ptr100000->r0090 + v31_25 * g_ptr100000->r00C8 @ 000E045B : real64)
  Class: Eq_380
  DataType: real64
  OrigDataType: real64
T_381: (in Mem1[0x00100000<p32>:word32] @ 000E045B : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (100 T_384 t0100)))
T_382: (in 0x100<u32> @ 000E045B : uint32)
  Class: Eq_382
  DataType: uint32
  OrigDataType: uint32
T_383: (in Mem1[0x00100000<p32>:word32] + 0x100<u32> @ 000E045B : word32)
  Class: Eq_383
  DataType: ptr32
  OrigDataType: ptr32
T_384: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x100<u32>:real64] @ 000E045B : real64)
  Class: Eq_384
  DataType: real64
  OrigDataType: real64
T_385: (in v37_32 * g_ptr100000->r0100 @ 000E045B : real64)
  Class: Eq_385
  DataType: real64
  OrigDataType: real64
T_386: (in v12_3 * g_ptr100000->r0020 + 0.0 + v19_11 * g_ptr100000->r0058 + v25_18 * g_ptr100000->r0090 + v31_25 * g_ptr100000->r00C8 + v37_32 * g_ptr100000->r0100 @ 000E045B : real64)
  Class: Eq_355
  DataType: real64
  OrigDataType: real64
T_387: (in v67_64 @ 000E0496 : real64)
  Class: Eq_387
  DataType: real64
  OrigDataType: real64
T_388: (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (28 T_391 t0028) (30 T_334 t0030)))
T_389: (in 0x28<u32> @ 000E0496 : uint32)
  Class: Eq_389
  DataType: uint32
  OrigDataType: uint32
T_390: (in Mem1[0x00100000<p32>:word32] + 0x28<u32> @ 000E0496 : word32)
  Class: Eq_390
  DataType: ptr32
  OrigDataType: ptr32
T_391: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x28<u32>:real64] @ 000E0496 : real64)
  Class: Eq_391
  DataType: real64
  OrigDataType: real64
T_392: (in v12_3 * g_ptr100000->r0028 @ 000E0496 : real64)
  Class: Eq_392
  DataType: real64
  OrigDataType: real64
T_393: (in 0.0 @ 000E0496 : real64)
  Class: Eq_393
  DataType: real64
  OrigDataType: real64
T_394: (in v12_3 * g_ptr100000->r0028 + 0.0 @ 000E0496 : real64)
  Class: Eq_394
  DataType: real64
  OrigDataType: real64
T_395: (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (60 T_398 t0060)))
T_396: (in 0x60<u32> @ 000E0496 : uint32)
  Class: Eq_396
  DataType: uint32
  OrigDataType: uint32
T_397: (in Mem1[0x00100000<p32>:word32] + 0x60<u32> @ 000E0496 : word32)
  Class: Eq_397
  DataType: ptr32
  OrigDataType: ptr32
T_398: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x60<u32>:real64] @ 000E0496 : real64)
  Class: Eq_398
  DataType: real64
  OrigDataType: real64
T_399: (in v19_11 * g_ptr100000->r0060 @ 000E0496 : real64)
  Class: Eq_399
  DataType: real64
  OrigDataType: real64
T_400: (in v12_3 * g_ptr100000->r0028 + 0.0 + v19_11 * g_ptr100000->r0060 @ 000E0496 : real64)
  Class: Eq_400
  DataType: real64
  OrigDataType: real64
T_401: (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (98 T_404 t0098)))
T_402: (in 0x98<u32> @ 000E0496 : uint32)
  Class: Eq_402
  DataType: uint32
  OrigDataType: uint32
T_403: (in Mem1[0x00100000<p32>:word32] + 0x98<u32> @ 000E0496 : word32)
  Class: Eq_403
  DataType: ptr32
  OrigDataType: ptr32
T_404: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x98<u32>:real64] @ 000E0496 : real64)
  Class: Eq_404
  DataType: real64
  OrigDataType: real64
T_405: (in v25_18 * g_ptr100000->r0098 @ 000E0496 : real64)
  Class: Eq_405
  DataType: real64
  OrigDataType: real64
T_406: (in v12_3 * g_ptr100000->r0028 + 0.0 + v19_11 * g_ptr100000->r0060 + v25_18 * g_ptr100000->r0098 @ 000E0496 : real64)
  Class: Eq_406
  DataType: real64
  OrigDataType: real64
T_407: (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (D0 T_410 t00D0)))
T_408: (in 0xD0<u32> @ 000E0496 : uint32)
  Class: Eq_408
  DataType: uint32
  OrigDataType: uint32
T_409: (in Mem1[0x00100000<p32>:word32] + 0xD0<u32> @ 000E0496 : word32)
  Class: Eq_409
  DataType: ptr32
  OrigDataType: ptr32
T_410: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xD0<u32>:real64] @ 000E0496 : real64)
  Class: Eq_410
  DataType: real64
  OrigDataType: real64
T_411: (in v31_25 * g_ptr100000->r00D0 @ 000E0496 : real64)
  Class: Eq_411
  DataType: real64
  OrigDataType: real64
T_412: (in v12_3 * g_ptr100000->r0028 + 0.0 + v19_11 * g_ptr100000->r0060 + v25_18 * g_ptr100000->r0098 + v31_25 * g_ptr100000->r00D0 @ 000E0496 : real64)
  Class: Eq_412
  DataType: real64
  OrigDataType: real64
T_413: (in Mem1[0x00100000<p32>:word32] @ 000E0496 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (108 T_416 t0108)))
T_414: (in 0x108<u32> @ 000E0496 : uint32)
  Class: Eq_414
  DataType: uint32
  OrigDataType: uint32
T_415: (in Mem1[0x00100000<p32>:word32] + 0x108<u32> @ 000E0496 : word32)
  Class: Eq_415
  DataType: ptr32
  OrigDataType: ptr32
T_416: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x108<u32>:real64] @ 000E0496 : real64)
  Class: Eq_416
  DataType: real64
  OrigDataType: real64
T_417: (in v37_32 * g_ptr100000->r0108 @ 000E0496 : real64)
  Class: Eq_417
  DataType: real64
  OrigDataType: real64
T_418: (in v12_3 * g_ptr100000->r0028 + 0.0 + v19_11 * g_ptr100000->r0060 + v25_18 * g_ptr100000->r0098 + v31_25 * g_ptr100000->r00D0 + v37_32 * g_ptr100000->r0108 @ 000E0496 : real64)
  Class: Eq_387
  DataType: real64
  OrigDataType: real64
T_419: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (18 T_422 t0018) (30 T_334 t0030)))
T_420: (in 0x18<u32> @ 000E04E1 : uint32)
  Class: Eq_420
  DataType: uint32
  OrigDataType: uint32
T_421: (in Mem1[0x00100000<p32>:word32] + 0x18<u32> @ 000E04E1 : word32)
  Class: Eq_421
  DataType: ptr32
  OrigDataType: ptr32
T_422: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x18<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_422
  DataType: real64
  OrigDataType: real64
T_423: (in g_ptr100000->r0018 * v12_3 @ 000E04E1 : real64)
  Class: Eq_423
  DataType: real64
  OrigDataType: real64
T_424: (in 0.0 @ 000E04E1 : real64)
  Class: Eq_424
  DataType: real64
  OrigDataType: real64
T_425: (in g_ptr100000->r0018 * v12_3 + 0.0 @ 000E04E1 : real64)
  Class: Eq_425
  DataType: real64
  OrigDataType: real64
T_426: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (50 T_429 t0050)))
T_427: (in 0x50<u32> @ 000E04E1 : uint32)
  Class: Eq_427
  DataType: uint32
  OrigDataType: uint32
T_428: (in Mem1[0x00100000<p32>:word32] + 0x50<u32> @ 000E04E1 : word32)
  Class: Eq_428
  DataType: ptr32
  OrigDataType: ptr32
T_429: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x50<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_429
  DataType: real64
  OrigDataType: real64
T_430: (in g_ptr100000->r0050 * v19_11 @ 000E04E1 : real64)
  Class: Eq_430
  DataType: real64
  OrigDataType: real64
T_431: (in g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 @ 000E04E1 : real64)
  Class: Eq_431
  DataType: real64
  OrigDataType: real64
T_432: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (88 T_435 t0088)))
T_433: (in 0x88<u32> @ 000E04E1 : uint32)
  Class: Eq_433
  DataType: uint32
  OrigDataType: uint32
T_434: (in Mem1[0x00100000<p32>:word32] + 0x88<u32> @ 000E04E1 : word32)
  Class: Eq_434
  DataType: ptr32
  OrigDataType: ptr32
T_435: (in Mem1[Mem1[0x00100000<p32>:word32] + 0x88<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_435
  DataType: real64
  OrigDataType: real64
T_436: (in g_ptr100000->r0088 * v25_18 @ 000E04E1 : real64)
  Class: Eq_436
  DataType: real64
  OrigDataType: real64
T_437: (in g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 + g_ptr100000->r0088 * v25_18 @ 000E04E1 : real64)
  Class: Eq_437
  DataType: real64
  OrigDataType: real64
T_438: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (C0 T_441 t00C0)))
T_439: (in 0xC0<u32> @ 000E04E1 : uint32)
  Class: Eq_439
  DataType: uint32
  OrigDataType: uint32
T_440: (in Mem1[0x00100000<p32>:word32] + 0xC0<u32> @ 000E04E1 : word32)
  Class: Eq_440
  DataType: ptr32
  OrigDataType: ptr32
T_441: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xC0<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_441
  DataType: real64
  OrigDataType: real64
T_442: (in g_ptr100000->r00C0 * v31_25 @ 000E04E1 : real64)
  Class: Eq_442
  DataType: real64
  OrigDataType: real64
T_443: (in g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 + g_ptr100000->r0088 * v25_18 + g_ptr100000->r00C0 * v31_25 @ 000E04E1 : real64)
  Class: Eq_443
  DataType: real64
  OrigDataType: real64
T_444: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030) (F8 T_447 t00F8)))
T_445: (in 0xF8<u32> @ 000E04E1 : uint32)
  Class: Eq_445
  DataType: uint32
  OrigDataType: uint32
T_446: (in Mem1[0x00100000<p32>:word32] + 0xF8<u32> @ 000E04E1 : word32)
  Class: Eq_446
  DataType: ptr32
  OrigDataType: ptr32
T_447: (in Mem1[Mem1[0x00100000<p32>:word32] + 0xF8<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_447
  DataType: real64
  OrigDataType: real64
T_448: (in g_ptr100000->r00F8 * v37_32 @ 000E04E1 : real64)
  Class: Eq_448
  DataType: real64
  OrigDataType: real64
T_449: (in g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 + g_ptr100000->r0088 * v25_18 + g_ptr100000->r00C0 * v31_25 + g_ptr100000->r00F8 * v37_32 @ 000E04E1 : real64)
  Class: Eq_449
  DataType: real64
  OrigDataType: real64
T_450: (in -(g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 + g_ptr100000->r0088 * v25_18 + g_ptr100000->r00C0 * v31_25 + g_ptr100000->r00F8 * v37_32) @ 000E04E1 : real64)
  Class: Eq_450
  DataType: real64
  OrigDataType: real64
T_451: (in 39.47841760435743 @ 000E04E1 : real64)
  Class: Eq_451
  DataType: real64
  OrigDataType: real64
T_452: (in -(g_ptr100000->r0018 * v12_3 + 0.0 + g_ptr100000->r0050 * v19_11 + g_ptr100000->r0088 * v25_18 + g_ptr100000->r00C0 * v31_25 + g_ptr100000->r00F8 * v37_32) / 39.47841760435743 @ 000E04E1 : real64)
  Class: Eq_422
  DataType: real64
  OrigDataType: real64
T_453: (in Mem1[0x00100000<p32>:word32] @ 000E04E1 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (18 T_456 t0018) (30 T_334 t0030)))
T_454: (in 0x18<u32> @ 000E04E1 : uint32)
  Class: Eq_454
  DataType: uint32
  OrigDataType: uint32
T_455: (in Mem1[0x00100000<p32>:word32] + 0x18<u32> @ 000E04E1 : word32)
  Class: Eq_455
  DataType: ptr32
  OrigDataType: ptr32
T_456: (in Mem97[Mem1[0x00100000<p32>:word32] + 0x18<u32>:real64] @ 000E04E1 : real64)
  Class: Eq_422
  DataType: real64
  OrigDataType: real64
T_457: (in -v41_37 @ 000E04F5 : real64)
  Class: Eq_457
  DataType: real64
  OrigDataType: real64
T_458: (in 39.47841760435743 @ 000E04F5 : real64)
  Class: Eq_458
  DataType: real64
  OrigDataType: real64
T_459: (in -v41_37 / 39.47841760435743 @ 000E04F5 : real64)
  Class: Eq_359
  DataType: real64
  OrigDataType: real64
T_460: (in Mem97[0x00100000<p32>:word32] @ 000E04F5 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (20 T_463 t0020) (30 T_334 t0030)))
T_461: (in 0x20<u32> @ 000E04F5 : uint32)
  Class: Eq_461
  DataType: uint32
  OrigDataType: uint32
T_462: (in Mem97[0x00100000<p32>:word32] + 0x20<u32> @ 000E04F5 : word32)
  Class: Eq_462
  DataType: ptr32
  OrigDataType: ptr32
T_463: (in Mem104[Mem97[0x00100000<p32>:word32] + 0x20<u32>:real64] @ 000E04F5 : real64)
  Class: Eq_359
  DataType: real64
  OrigDataType: real64
T_464: (in -v67_64 @ 000E0509 : real64)
  Class: Eq_464
  DataType: real64
  OrigDataType: real64
T_465: (in 39.47841760435743 @ 000E0509 : real64)
  Class: Eq_465
  DataType: real64
  OrigDataType: real64
T_466: (in -v67_64 / 39.47841760435743 @ 000E0509 : real64)
  Class: Eq_391
  DataType: real64
  OrigDataType: real64
T_467: (in Mem104[0x00100000<p32>:word32] @ 000E0509 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (28 T_470 t0028) (30 T_334 t0030)))
T_468: (in 0x28<u32> @ 000E0509 : uint32)
  Class: Eq_468
  DataType: uint32
  OrigDataType: uint32
T_469: (in Mem104[0x00100000<p32>:word32] + 0x28<u32> @ 000E0509 : word32)
  Class: Eq_469
  DataType: ptr32
  OrigDataType: ptr32
T_470: (in Mem111[Mem104[0x00100000<p32>:word32] + 0x28<u32>:real64] @ 000E0509 : real64)
  Class: Eq_391
  DataType: real64
  OrigDataType: real64
T_471: (in false @ 000E054A : bool)
  Class: Eq_471
  DataType: bool
  OrigDataType: bool
T_472: (in true @ 000E05D3 : bool)
  Class: Eq_472
  DataType: bool
  OrigDataType: bool
T_473: (in false @ 000E05DC : bool)
  Class: Eq_473
  DataType: bool
  OrigDataType: bool
T_474: (in <invalid> @ 000E061D : real64)
  Class: Eq_328
  DataType: real64
  OrigDataType: real64
T_475: (in  @ 000E061D : real64)
  Class: Eq_328
  DataType: real64
  OrigDataType: real64
T_476: (in arg0 @ 000E061D : int32)
  Class: Eq_476
  DataType: int32
  OrigDataType: int32
T_477: (in arg0_168 @ 000E061E : int32)
  Class: Eq_477
  DataType: int32
  OrigDataType: int32
T_478: (in 1<32> @ 000E0625 : word32)
  Class: Eq_476
  DataType: int32
  OrigDataType: int32
T_479: (in arg0 < 1<32> @ 000E0625 : bool)
  Class: Eq_479
  DataType: bool
  OrigDataType: bool
T_480: (in !(arg0 < 1<32>) @ 000E0625 : bool)
  Class: Eq_480
  DataType: bool
  OrigDataType: bool
T_481: (in 0<32> @ 000E0629 : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: word32
T_482: (in _advance @ 000E064A : ptr32)
  Class: Eq_482
  DataType: (ptr32 Eq_482)
  OrigDataType: (ptr32 (fn T_487 (T_484, T_485, T_486)))
T_483: (in signature of _advance @ 000E0000 : void)
  Class: Eq_482
  DataType: (ptr32 Eq_482)
  OrigDataType: 
T_484: (in 5<32> @ 000E064A : word32)
  Class: Eq_2
  DataType: int32
  OrigDataType: word32
T_485: (in Mem0[0x00100000<p32>:word32] @ 000E064A : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (30 T_334 t0030)))
T_486: (in 0.01 @ 000E064A : real64)
  Class: Eq_4
  DataType: real64
  OrigDataType: real64
T_487: (in _advance(5<32>, g_ptr100000, 0.01) @ 000E064A : word32)
  Class: Eq_487
  DataType: word32
  OrigDataType: word32
T_488: (in 1<32> @ 000E0658 : word32)
  Class: Eq_476
  DataType: int32
  OrigDataType: word32
T_489: (in arg0 == 1<32> @ 000E0658 : bool)
  Class: Eq_489
  DataType: bool
  OrigDataType: bool
T_490: (in !(arg0 == 1<32>) @ 000E0658 : bool)
  Class: Eq_490
  DataType: bool
  OrigDataType: bool
T_491: (in 0<32> @ 000E065C : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: word32
T_492: (in v66_77 @ 000E06C8 : int32)
  Class: Eq_477
  DataType: int32
  OrigDataType: int32
T_493: (in 1<32> @ 000E06C8 : word32)
  Class: Eq_493
  DataType: word32
  OrigDataType: word32
T_494: (in arg0_168 + 1<32> @ 000E06C8 : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: word32
T_495: (in 5<32> @ 000E06CE : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: int32
T_496: (in v66_77 < 5<32> @ 000E06CE : bool)
  Class: Eq_496
  DataType: bool
  OrigDataType: bool
T_497: (in !(v66_77 < 5<32>) @ 000E06CE : bool)
  Class: Eq_497
  DataType: bool
  OrigDataType: bool
T_498: (in 0xFFFFFFFC<32> @ 000E0757 : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: word32
T_499: (in v66_77 != 0xFFFFFFFC<32> @ 000E0757 : bool)
  Class: Eq_499
  DataType: bool
  OrigDataType: bool
T_500: (in 5<32> @ 000E0760 : word32)
  Class: Eq_477
  DataType: int32
  OrigDataType: word32
T_501: (in v66_77 != 5<32> @ 000E0760 : bool)
  Class: Eq_501
  DataType: bool
  OrigDataType: bool
T_502: (in !(v66_77 != 5<32>) @ 000E0760 : bool)
  Class: Eq_502
  DataType: bool
  OrigDataType: bool
T_503: (in Mem0[0x00100000<p32>:word32] @ 000E0778 : word32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (struct (0 (arr T_516) a0000)))
T_504: (in 0x120<32> @ 000E0778 : word32)
  Class: Eq_504
  DataType: int32
  OrigDataType: int32
T_505: (in Mem0[0x00100000<p32>:word32] + 0x120<32> @ 000E0778 : word32)
  Class: Eq_505
  DataType: ptr32
  OrigDataType: ptr32
T_506: (in 00100008 @ 000E0778 : ptr32)
  Class: Eq_506
  DataType: (ptr32 ptr32)
  OrigDataType: (ptr32 (struct (0 T_505 t0000)))
T_507: (in Mem5[0x00100008<p32>:word32] @ 000E0778 : word32)
  Class: Eq_505
  DataType: ptr32
  OrigDataType: word32
T_508: (in Mem5[0x00100008<p32>:word32] @ 000E0782 : word32)
  Class: Eq_505
  DataType: ptr32
  OrigDataType: word32
T_509: (in 0x500000<32> @ 000E0782 : word32)
  Class: Eq_509
  DataType: word32
  OrigDataType: word32
T_510: (in g_ptr100008 + 0x500000<32> @ 000E0782 : word32)
  Class: Eq_510
  DataType: word32
  OrigDataType: word32
T_511: (in 0010000C @ 000E0782 : ptr32)
  Class: Eq_511
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_512 t0000)))
T_512: (in Mem9[0x0010000C<p32>:word32] @ 000E0782 : word32)
  Class: Eq_510
  DataType: word32
  OrigDataType: word32
T_513: (in runPostSets @ 000E0784 : ptr32)
  Class: Eq_513
  DataType: (ptr32 Eq_513)
  OrigDataType: (ptr32 (fn T_515 ()))
T_514: (in signature of runPostSets @ 000E076E : void)
  Class: Eq_513
  DataType: (ptr32 Eq_513)
  OrigDataType: 
T_515: (in runPostSets() @ 000E0784 : word32)
  Class: Eq_515
  DataType: word32
  OrigDataType: word32
T_516:
  Class: Eq_516
  DataType: Eq_516
  OrigDataType: (struct 0038 (0 T_18 t0000))
T_517:
  Class: Eq_517
  DataType: (arr Eq_516)
  OrigDataType: (arr T_516)
T_518:
  Class: Eq_516
  DataType: Eq_516
  OrigDataType: (struct 0038 (0 T_21 t0000))
T_519:
  Class: Eq_519
  DataType: (arr Eq_516)
  OrigDataType: (arr T_518)
*/
typedef struct Globals {
	struct Eq_3 * ptr100000;	// 100000
	ptr32 ptr100008;	// 100008
	word32 dw10000C;	// 10000C
} Eq_1;

typedef struct Eq_3 {
	Eq_516 a0000[];	// 0
	real64 r0018;	// 18
	real64 r0020;	// 20
	real64 r0028;	// 28
	real64 r0030;	// 30
	real64 r0050;	// 50
	real64 r0058;	// 58
	real64 r0060;	// 60
	real64 r0068;	// 68
	real64 r0088;	// 88
	real64 r0090;	// 90
	real64 r0098;	// 98
	real64 r00A0;	// A0
	real64 r00C0;	// C0
	real64 r00C8;	// C8
	real64 r00D0;	// D0
	real64 r00D8;	// D8
	real64 r00F8;	// F8
	real64 r0100;	// 100
	real64 r0108;	// 108
	real64 r0110;	// 110
} Eq_3;

typedef struct Eq_26 {
	real64 r0008;	// 8
} Eq_26;

typedef struct Eq_32 {
	real64 r0008;	// 8
} Eq_32;

typedef struct Eq_40 {
	real64 r0010;	// 10
} Eq_40;

typedef struct Eq_46 {
	real64 r0010;	// 10
} Eq_46;

typedef struct Eq_54 {
	real64 r0030;	// 30
} Eq_54;

typedef real64 (Eq_59)(real64);

typedef struct Eq_68 {
	real64 r0018;	// 18
} Eq_68;

typedef struct Eq_75 {
	real64 r0030;	// 30
} Eq_75;

typedef struct Eq_91 {
	real64 r0020;	// 20
} Eq_91;

typedef struct Eq_103 {
	real64 r0028;	// 28
} Eq_103;

typedef struct Eq_115 {
	real64 r0018;	// 18
} Eq_115;

typedef struct Eq_127 {
	real64 r0020;	// 20
} Eq_127;

typedef struct Eq_139 {
	real64 r0028;	// 28
} Eq_139;

typedef struct Eq_170 {
	real64 r0018;	// 18
} Eq_170;

typedef struct Eq_179 {
	real64 r0008;	// 8
} Eq_179;

typedef struct Eq_188 {
	real64 r0020;	// 20
} Eq_188;

typedef struct Eq_196 {
	real64 r0010;	// 10
} Eq_196;

typedef struct Eq_205 {
	real64 r0028;	// 28
} Eq_205;

typedef struct Eq_231 {
	real64 r0018;	// 18
} Eq_231;

typedef struct Eq_238 {
	real64 r0020;	// 20
} Eq_238;

typedef struct Eq_245 {
	real64 r0028;	// 28
} Eq_245;

typedef struct Eq_252 {
	real64 r0030;	// 30
} Eq_252;

typedef struct Eq_276 {
	real64 r0018;	// 18
	real64 r0020;	// 20
	real64 r0028;	// 28
	real64 r0030;	// 30
} Eq_276;

typedef word32 (Eq_482)(int32, Eq_3 *, real64);

typedef word32 (Eq_513)();

typedef struct Eq_516 {	// size: 56 38
	real64 r0000;	// 0
} Eq_516;

