;;; Segment .exports (000B0000)
; (export "_run" (func 4))
; (export "__post_instantiate" (func 6))
; (export "runPostSets" (func 5))
; (export "_energy" (func 1))
; (export "_start" (func 3))
; (export "_offset_momentum" (func 2))
; (export "_advance" (func 0))
; (export "_bodies" (global 4))
