push	320h
push	300h
call	0010h
call	0037h
add	sp,4h
ret
push	bp
mov	bp,sp
mov	bx,[bp+4h]
fld	double ptr [bx]
fmul	st(0),st(0)
fld	double ptr [bx+8h]
fmul	st(0),st(0)
faddp	st(1),st(0)
fld	double ptr [bx+10h]
fmul	st(0),st(0)
faddp	st(1),st(0)
mov	bx,[bp+6h]
fstp	double ptr [bx]
fild	word ptr [bx+20h]
fstp	double ptr [bx+28h]
mov	sp,bp
pop	bp
ret
fldz
fstp	double ptr [0400h]
fld1
fistp	dword ptr [0408h]
ret
