push	0320
push	0300
call	0010
call	0037
add	sp,04
ret
push	bp
mov	bp,sp
mov	bx,[bp+04]
fld	double ptr [bx]
fmul	st(0),st(0)
fld	double ptr [bx+08]
fmul	st(0),st(0)
faddp	st(1),st(0)
fld	double ptr [bx+10]
fmul	st(0),st(0)
faddp	st(1),st(0)
mov	bx,[bp+06]
fstp	double ptr [bx]
fild	word ptr [bx+20]
fstp	double ptr [bx+28]
mov	sp,bp
pop	bp
ret
fldz
fstp	double ptr [0400]
fld1
fistp	dword ptr [0408]
ret
