// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// bp:Register
// wLoc02:Local -0002
// ax:Register
// wArg02:Stack +0002
// dx:Register
// C:Flags
// ds:Register
// ds_dx:Sequence ds:dx
// al:Register
// wLoc04:Local -0004
// wArg04:Stack +0004
// wLoc06:Local -0006
// bx:Register
// cx:Register
// SCZO:Flags
// Z:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	wLoc02 = bp
	ax = 0x3D00
	dx = wArg02
	C = msdos_open_file(ds_dx, al, &ax)
	wLoc04 = ax
	ax = 0x3D01
	dx = wArg04
	C = msdos_open_file(ds_dx, al, &ax)
	wLoc06 = ax
	// succ:  2
l0C00_002A:		// block 2, pred: 1 4
	bx = wLoc04
	dx = 0x0800
	cx = 0x0800
	ax = 0x3F00
	C = msdos_read_file(bx, cx, ds_dx, &ax)
	branch Test(ULT,C)
	// succ:  3 5
l0C00_003A:		// block 3, pred: 2
	SCZO = cond(ax - 0x0000)
	branch Test(NE,Z)
	// succ:  5 4
l0C00_001F:		// block 4, pred: 3
	bx = wLoc06
	dx = 0x0800
	ax = 0x4000
	C = msdos_write_file(bx, cx, ds_dx, &ax)
	// succ:  2
l0C00_003E:		// block 5, pred: 3 2
	bp = wLoc02
	return
	// succ:  6
fn0C00_0000_exit:		// block 6, pred: 5
	// succ: 
