// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// SCZO:Flags
// ax:ax
// dx:dx
// ds:ds
// ds_dx:Sequence ds:dx
// al:al
// C:Flags
// bx:bx
// cx:cx
// SZO:Flags
// Z:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = bp
	bp = sp
	sp = sp - 0x0004
	SCZO = cond(sp)
	ax = 0x3D00
	dx = Mem0[ss:bp + 0x0004:word16]
	C = msdos_open_file(ds_dx, al, out ax)
	Mem0[ss:bp - 0x0002:word16] = ax
	ax = 0x3D01
	dx = Mem0[ss:bp + 0x0006:word16]
	C = msdos_open_file(ds_dx, al, out ax)
	Mem0[ss:bp - 0x0004:word16] = ax
	goto l0C00_002A
	// succ:  l0C00_002A
l0C00_001F:
	bx = Mem0[ss:bp - 0x0004:word16]
	dx = 0x0800
	ax = 0x4000
	C = msdos_write_file(bx, cx, ds_dx, out ax)
	// succ:  l0C00_002A
l0C00_002A:
	bx = Mem0[ss:bp - 0x0002:word16]
	dx = 0x0800
	cx = 0x0800
	ax = 0x3F00
	C = msdos_read_file(bx, cx, ds_dx, out ax)
	branch Test(ULT,C) l0C00_003E
	// succ:  l0C00_003A l0C00_003E
l0C00_003A:
	ax = ax | ax
	SZO = cond(ax)
	C = false
	branch Test(NE,Z) l0C00_001F
	// succ:  l0C00_003E l0C00_001F
l0C00_003E:
	sp = bp
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
