// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// ax:ax
// SZO:Flags
// C:Flags
// cx:cx
// bx:bx
// ds:ds
// SCZO:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	sp = fp
	// succ:  l0C00_0000
l0C00_0000:
	ax = ax ^ ax
	SZO = cond(ax)
	C = false
	cx = Mem0[ds:bx:word16]
	// succ:  l0C00_0004
l0C00_0004:
	ax = ax + cx
	SCZO = cond(ax)
	ax = ax + cx
	SCZO = cond(ax)
	cx = cx - 0x0001
	branch cx != 0x0000 l0C00_0004
	// succ:  l0C00_000A l0C00_0004
l0C00_000A:
	Mem0[ds:0x0300:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
