// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// bp:Register
// wLoc02:Local -0002
// wArg02:Stack +0002
// bx:Register
// ds:Register
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	wLoc02 = bp
	bx = wArg02
	store(Mem0[ds:bx:byte]) = 0x00
	bp = wLoc02
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

