// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// ss:ss
// bx:bx
// ds:ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	sp = sp - 2
	Mem0[ss:sp:word16] = bp
	bp = sp
	bx = Mem0[ss:bp + 0x0004:word16]
	Mem0[ds:bx:byte] = 0x00
	sp = bp
	bp = Mem0[ss:sp:word16]
	sp = sp + 2
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

