// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// cx:cx
// v4:v4
// ss:ss
// SCZO:Flags
// ds:ds
// ax:ax
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	cx = 0x0064
	v4 = cx
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	call fn0C00_000F (retsize: 2;)
	sp = sp + 0x0002
	SCZO = cond(sp)
	Mem0[ds:0x0064:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_000F
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// v4:v4
// ss:ss
// ax:ax
// SZO:Flags
// Z:Flags
// v9:v9
// dx:dx
// dx_ax:Sequence dx:ax
// SCZO:Flags
// return address size: 2
void fn0C00_000F()
fn0C00_000F_entry:
	// succ:  l0C00_000F
l0C00_000F:
	sp = fp
	v4 = bp
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	bp = sp
	ax = Mem0[ss:bp + 0x0004:word16]
	ax = ax - 0x0001
	SZO = cond(ax)
	branch Test(EQ,Z) l0C00_0026
	// succ:  l0C00_0018 l0C00_0026
l0C00_0018:
	v9 = ax
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v9
	call fn0C00_000F (retsize: 2;)
	sp = sp + 0x0001
	SZO = cond(sp)
	sp = sp + 0x0001
	SZO = cond(sp)
	dx = Mem0[ss:bp + 0x0004:word16]
	dx_ax = dx *s ax
	SCZO = cond(dx_ax)
	goto l0C00_0029
	// succ:  l0C00_0029
l0C00_0026:
	ax = 0x0001
	// succ:  l0C00_0029
l0C00_0029:
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
	// succ:  fn0C00_000F_exit
fn0C00_000F_exit:
