// fn10000000
// Return size: 4
// Mem0:Mem
// fp:fp
// esp:esp
// edi:edi
// Top:Top
// eax:eax
// return address size: 4
define fn10000000
fn10000000_entry:
	esp = fp
	Top = 0
	// succ:  l10000000
l10000000:
	edi = 0x10001212
	Top = Top - 1
	ST[Top:real64] = Mem0[edi + 0x00000004:real64]
	Top = Top - 1
	ST[Top:real64] = Mem0[edi + 0x0000000C:real64]
	eax = _ftol(ST[Top:real64])
	Top = Top + 1
	Mem0[edi + 0x00000014:word32] = eax
	eax = _ftol(ST[Top:real64])
	Top = Top + 1
	Mem0[edi + 0x0000001C:word32] = eax
	return
	// succ:  fn10000000_exit
fn10000000_exit:

