// fn10000000
// Return size: 4
// Mem0:Global memory
// fp:fp
// esp:esp
// edi:edi
// rLoc1:FPU stack
// rLoc2:FPU stack
// eax:eax
// return address size: 4
void fn10000000()
fn10000000_entry:
	esp = fp
	// succ:  l10000000
l10000000:
	edi = 0x10001212
	rLoc1 = Mem0[edi + 0x00000004:real64]
	rLoc2 = Mem0[edi + 0x0000000C:real64]
	eax = _ftol(rLoc2)
	Mem0[edi + 0x00000014:word32] = eax
	eax = _ftol(rLoc1)
	Mem0[edi + 0x0000001C:word32] = eax
	return
	// succ:  fn10000000_exit
fn10000000_exit:

