// fn10000000
// Mem0:Global memory
// fp:Temporary
// edi:Register edi
// rLoc1:FPU stack
// rLoc2:FPU stack
// eax:Register eax
// return address size: 4
void fn10000000()
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	edi = 0x10001212
	rLoc1 = Mem0[edi + 0x00000004:real64]
	rLoc2 = Mem0[edi + 0x0000000C:real64]
	eax = _ftol(rLoc2)
	store(Mem0[edi + 0x00000014:word32]) = eax
	eax = _ftol(rLoc1)
	store(Mem0[edi + 0x0000001C:word32]) = eax
	return
	// succ:  2
fn10000000_exit:		// block 2, pred: 1
	// succ: 

