// fn10000000
// Mem0:Global memory
// fp:Temporary
// esi:Register
// dwLoc04:Local -0004
// dwArg04:Stack +0004
// edi:Register
// dwLoc08:Local -0008
// dwLoc0C:Local -000C
// eax:Register
// return address size: 4
void fn10000000()
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	dwLoc04 = esi
	esi = dwArg04
	dwLoc08 = edi
	edi = GlobalHandle
	dwLoc0C = esi
	eax = GlobalHandle(dwLoc0C)
	dwLoc0C = eax
	eax = GlobalUnlock(dwLoc0C)
	dwLoc0C = esi
	eax = GlobalHandle(dwLoc0C)
	dwLoc0C = eax
	eax = GlobalFree(dwLoc0C)
	edi = dwLoc08
	esi = dwLoc04
	return
	// succ:  2
fn10000000_exit:		// block 2, pred: 1
	// succ: 

