// fn10000000
// Mem0:Global memory
// fp:Temporary
// esp:Register esp
// esi:Register esi
// edi:Register edi
// eax:Register eax
// return address size: 4
void fn10000000()
fn10000000_entry:
	// succ:  l10000000
l10000000:
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = esi
	esi = Mem0[esp + 0x00000008:word32]
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = edi
	edi = GlobalHandle
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = esi
	eax = GlobalHandle(Mem0[esp:word32])
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = eax
	eax = GlobalUnlock(Mem0[esp:word32])
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = esi
	eax = GlobalHandle(Mem0[esp:word32])
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = eax
	eax = GlobalFree(Mem0[esp:word32])
	edi = Mem0[esp:word32]
	esp = esp + 0x00000004
	esi = Mem0[esp:word32]
	esp = esp + 0x00000004
	return
	// succ:  fn10000000_exit
fn10000000_exit:

