// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	bx = 0x1234
	call fn0C00_000C (depth: 2;)
	bx = 0x5678
	call fn0C00_0018 (depth: 2;)
	call fn0C00_000C (depth: 2;)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
// fn0C00_000C
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// ds:Register ds
// SCZO:Flags
// SZO:Flags
// ax:Register ax
// return address size: 2
void fn0C00_000C()
fn0C00_000C_entry:		// pred:
	// succ:  l0C00_000C
l0C00_000C:		// pred: fn0C00_000C_entry
	SCZO = cond(Mem0[ds:bx:word16] - 0x007B)
	branch Test(LE,SZO) l0C00_000F_branch
	// succ:  l0C00_0011 l0C00_000F_branch
l0C00_0011:		// pred: l0C00_000C
	ax = 0x0000
	SCZO = cond(ax)
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:		// pred: l0C00_000F_branch l0C00_0011
	// succ: 
l0C00_000F_branch:		// pred: l0C00_000C
	call fn0C00_0014 (depth: 2;)
	return
	// succ:  fn0C00_000C_exit
// fn0C00_0014
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// ds:Register ds
// ax:Register ax
// SZO:Flags
// return address size: 2
void fn0C00_0014()
fn0C00_0014_entry:		// pred:
	// succ:  l0C00_0014
l0C00_0014:		// pred: fn0C00_0014_entry
	ax = Mem0[ds:bx:word16]
	ax = ax + 0x0001
	SZO = cond(ax)
	return
fn0C00_0014_exit:
// fn0C00_0018
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// SCZO:Flags
// return address size: 2
void fn0C00_0018()
fn0C00_0018_entry:	
l0C00_0018:
	bx = bx + 0x0004
	SCZO = cond(bx)
	call fn0C00_0014 (depth: 2;)
	return
fn0C00_0018_exit:
