// fn0C00_0000
// Return size: 2
// Mem0:Mem
// fp:fp
// sp:sp
// ax:ax
// SZO:SZO
// C:C
// ebx:ebx
// Z:Z
// ds:ds
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	ax = ax & 0x000F
	SZO = cond(ax)
	C = false
	ebx = ebx & ebx
	SZO = cond(ebx)
	C = false
	branch Test(EQ,Z) l0C00_000C
	// succ:  l0C00_0008 l0C00_000C
l0C00_0008:
	Mem0[ds:0x0300:word16] = ax
	// succ:  l0C00_000C
l0C00_000C:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

