// fn10000000
// Mem0:Global memory
// fp:Temporary
// edi:Register edi
// esi:Register esi
// ebx:Register ebx
// SZO:Flags
// C:Flags
// Z:Flags
// esp:Register esp
// eax:Register eax
// SCZO:Flags
// return address size: 4
void fn10000000()
fn10000000_entry:
l10000000:
	edi = 0x10000034
	esi = 0x00000003
	ebx = malloc
	goto l1000002F
l10000015:
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = 0x00000008
	eax = malloc(Mem0[esp:word32])
	esp = esp + 0x00000004
	SCZO = cond(esp)
	store(Mem0[eax:word32]) = 0x00000000
	store(Mem0[eax + 0x00000004:word32]) = 0x00000000
	store(Mem0[edi:word32]) = eax
	esi = esi - 0x00000001
	SZO = cond(esi)
	edi = edi + 0x00000004
	SCZO = cond(edi)
l1000002F:
	esi = esi | esi
	SZO = cond(esi)
	C = false
	branch Test(NE,Z) l10000015
l10000033:
	return
fn10000000_exit:

