// fn10000008
// Return size: 4
// Mem0:Global memory
// fp:fp
// esp:esp
// v3:v3
// eax:eax
// SCZO:Flags
// v6:v6
// return address size: 4
void fn10000008()
fn10000008_entry:
	// succ:  l10000008
l10000008:
	esp = fp
	v3 = 0x00000008
	esp = esp - 0x00000004
	Mem0[esp:word32] = v3
	eax = malloc(Mem0[esp:size_t])
	esp = esp + 0x00000004
	SCZO = cond(esp)
	Mem0[eax:word32] = 0x00000000
	Mem0[eax + 0x00000004:word32] = 0x00001024
	v6 = eax
	esp = esp - 0x00000004
	Mem0[esp:word32] = v6
	free(Mem0[esp:(ptr void)])
	esp = esp + 0x00000004
	SCZO = cond(esp)
	return
	// succ:  fn10000008_exit
fn10000008_exit:

