// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	bx = Mem0[ds:bx + 0x0002:word16]
	SCZO = cond(bx - ax)
	branch Test(GT,SZO) l0C00_000F
l0C00_0007:
	store(Mem0[ds:bx + 0x0004:word16]) = 0x0001
	goto l0C00_002B
l0C00_000F:
	store(Mem0[ds:bx + 0x0004:word16]) = 0x0000
	ax = Mem0[ds:bx + 0x0004:word16]
	store(Mem0[ds:bx + 0x0006:word16]) = ax
	eax = (word32) Mem0[ds:bx + 0x0008:word16]
	ecx = (int32) Mem0[ds:bx + 0x000A:word16]
	eax = eax + ecx
	SCZO = cond(eax)
	store(Mem0[ds:bx + 0x000C:word32]) = eax
l0C00_002B:
	return
fn0C00_0000_exit:
