// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// ss:ss
// ds:ds
// dx:dx
// bx:bx
// cx:cx
// ax:ax
// SZO:Flags
// C:Flags
// SO:Flags
// al:al
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	sp = fp
	// succ:  l0C00_0000
l0C00_0000:
	sp = sp - 2
	Mem0[ss:sp:word16] = 0x0D00
	ds = Mem0[ss:sp:selector]
	sp = sp + 2
	dx = 0x3000
	bx = Mem0[ds:0x0300:word16]
	cx = 0x0100
	call fn0C00_0023 (retsize: 2;)
	ax = ax | ax
	SZO = cond(ax)
	C = false
	branch Test(GE,SO) l0C00_001A
	// succ:  l0C00_0015 l0C00_001A
l0C00_0015:
	al = 0x01
	call fn0C00_001F (retsize: 2;)
	// succ:  l0C00_001A
l0C00_001A:
	Mem0[ds:0x0302:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_001F
// Return size: 0
// Mem0:Global memory
// fp:fp
// sp:sp
// ah:ah
// al:al
// return address size: 0
void fn0C00_001F()
fn0C00_001F_entry:
	sp = fp
	// succ:  l0C00_001F
l0C00_001F:
	ah = 0x4C
	msdos_terminate(al)
fn0C00_001F_exit:
// fn0C00_0023
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// ah:ah
// bx:bx
// cx:cx
// ds:ds
// dx:dx
// ds_dx:Sequence ds:dx
// ax:ax
// C:Flags
// return address size: 2
void fn0C00_0023()
fn0C00_0023_entry:
	sp = fp
	// succ:  l0C00_0023
l0C00_0023:
	ah = 0x3F
	C = msdos_read_file(bx, cx, ds_dx, out ax)
	branch Test(UGE,C) l0C00_002C
	// succ:  l0C00_0029 l0C00_002C
l0C00_0029:
	ax = 0xFFFF
	// succ:  l0C00_002C
l0C00_002C:
	return
	// succ:  fn0C00_0023_exit
fn0C00_0023_exit:
