// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ecx:Register ecx
// SZO:Flags
// C:Flags
// ds:Register ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	call fn0C00_000F (depth: 0;)
	call fn0C00_0010 (depth: 0;)
	ecx = ecx ^ ecx
	SZO = cond(ecx)
	C = false
	store(Mem0[ds:0x0310:word32]) = ecx
	return
fn0C00_0000_exit:

// fn0C00_000F
// Mem0:Global memory
// fp:Temporary
// return address size: 2
void fn0C00_000F()
fn0C00_000F_entry:
l0C00_000F:
	return
fn0C00_000F_exit:

// fn0C00_0010
// Mem0:Global memory
// fp:Temporary
// ch:Register ch
// SZO:Flags
// C:Flags
// ds:Register ds
// cl:Register cl
// cx:Register cx
// return address size: 2
void fn0C00_0010()
fn0C00_0010_entry:
l0C00_0010:
	ch = ch ^ ch
	SZO = cond(ch)
	C = false
	cl = Mem0[ds:0x0300:byte]
	branch cx == 0x0000 l0C00_001E
l0C00_0018:
	store(Mem0[ds:0x0302:word16]) = 0x0000
l0C00_001E:
	return
fn0C00_0010_exit:

