// fn0C00_0000
// Return size: 2
// Mem0:Mem
// fp:fp
// sp:sp
// eax:eax
// ds:ds
// edx:edx
// SCZO:SCZO
// v7:v7
// C:C
// Top:Top
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	Top = 0
	eax = Mem0[ds:0x0100:word32]
	edx = Mem0[ds:0x0104:word32]
	eax = __shld(eax, edx, 0x04)
	edx = edx >>u 0x00000004
	SCZO = cond(edx)
	Mem0[ds:0x0108:word32] = eax
	Mem0[ds:0x010C:word32] = edx
	eax = Mem0[ds:0x0100:word32]
	edx = Mem0[ds:0x0104:word32]
	eax = eax << 0x00000001
	SCZO = cond(eax)
	v7 = (edx & 0x00000001 << 0x20 - 0x01) != 0x00000000
	edx = __rcl(edx, 0x01, C)
	C = v7
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

