// fn0C00_0000
// Return size: 2
// Mem0:Mem
// fp:fp
// sp:sp
// ds:ds
// ax:ax
// Top:Top
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0000
l0C00_0000:
	call fn0C00_0008 (retsize: 2;)
	Mem0[ds:0x0306:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_0008
// Return size: 2
// Mem0:Mem
// fp:fp
// sp:sp
// ds:ds
// ss:ss
// bx:bx
// ax:ax
// ss_sp:Sequence ss:sp
// Top:Top
// return address size: 2
define fn0C00_0008
fn0C00_0008_entry:
	sp = fp
	Top = 0
	// succ:  l0C00_0008
l0C00_0008:
	Mem0[ds:0x0300:word16] = sp
	Mem0[ds:0x0302:word16] = ss
	Mem0[ds:0x0308:word16] = bx
	ax = Mem0[ds:0x0304:word16]
	ss_sp = Mem0[ds:0x0300:segptr32]
	return
	// succ:  fn0C00_0008_exit
fn0C00_0008_exit:
