// fn0C00_0000
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// v4:v4
// ss:ss
// es_bx:Sequence es:bx
// es:es
// v8:v8
// bx:bx
// v10:v10
// SCZO:Flags
// ax:ax
// v13:v13
// v14:v14
// v15:v15
// ds:ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	v4 = bp
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	bp = sp
	es_bx = Mem0[ss:bp + 0x0006:segptr32]
	v8 = es
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v8
	v10 = bx
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v10
	call fn0C00_0020 (retsize: 2;)
	sp = sp + 0x0004
	SCZO = cond(sp)
	v13 = ax
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v13
	es_bx = Mem0[ss:bp + 0x0006:segptr32]
	v14 = es
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v14
	v15 = bx
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v15
	call fn0C00_002E (retsize: 2;)
	sp = sp + 0x0006
	SCZO = cond(sp)
	Mem0[ds:0x0200:word16] = ax
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_0020
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// v4:v4
// ss:ss
// es_bx:Sequence es:bx
// ax:ax
// bx:bx
// es:es
// return address size: 2
void fn0C00_0020()
fn0C00_0020_entry:
	// succ:  l0C00_0020
l0C00_0020:
	sp = fp
	v4 = bp
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	bp = sp
	es_bx = Mem0[ss:bp + 0x0004:segptr32]
	ax = Mem0[es:bx + 0x0004:word16]
	sp = bp
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
	// succ:  fn0C00_0020_exit
fn0C00_0020_exit:
// fn0C00_002E
// Return size: 2
// Mem0:Global memory
// fp:fp
// sp:sp
// bp:bp
// v4:v4
// ss:ss
// es_bx:Sequence es:bx
// ax:ax
// bx:bx
// es:es
// SCZO:Flags
// return address size: 2
void fn0C00_002E()
fn0C00_002E_entry:
	// succ:  l0C00_002E
l0C00_002E:
	sp = fp
	v4 = bp
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	bp = sp
	es_bx = Mem0[ss:bp + 0x0004:segptr32]
	ax = Mem0[ss:bp + 0x0008:word16]
	ax = ax + Mem0[es:bx + 0x0006:word16]
	SCZO = cond(ax)
	sp = bp
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
	// succ:  fn0C00_002E_exit
fn0C00_002E_exit:
