// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// ax:Register ax
// ds:Register ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	sp = sp - 0x0002
	call fn0C00_0008 (depth: 0;)
	store(Mem0[ds:0x0306:word16]) = ax
	return
fn0C00_0000_exit:
// fn0C00_0008
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// ds:Register ds
// ss:Register ss
// bx:Register bx
// ax:Register ax
// ss_sp:Sequence ss:sp
// return address size: 2
void fn0C00_0008()
fn0C00_0008_entry:
l0C00_0008:
	store(Mem0[ds:0x0300:word16]) = sp
	store(Mem0[ds:0x0302:word16]) = ss
	store(Mem0[ds:0x0308:word16]) = bx
	ax = Mem0[ds:0x0304:word16]
	ss_sp = Mem0[ds:0x0300:ptr32]
	return
fn0C00_0008_exit:
