// fn0C00_0000
// Return size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	sp = fp
	v4 = cs
	sp = sp - 0x0002
	Mem0[ss:sp:word16] = v4
	ds = Mem0[ss:sp:selector]
	sp = sp + 0x0002
	bl = Mem0[ds:si:byte]
	SCZO = cond(bl - 0x02)
	branch Test(UGT,CZ) l0C00_0023
	// succ:  l0C00_0009 l0C00_0023
l0C00_0009:
	bh = bh ^ bh
	SZO = cond(bh)
	C = false
	bx = bx + bx
	SCZO = cond(bx)
	call Mem0[ds:bx + 0x0011:word16] (retsize: 4;)
	return
	// succ:  fn0C00_0000_exit
l0C00_0023:
	ax = 0x0000
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
