#region License
/* 
 * Copyright (C) 1999-2020 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

namespace Reko.Arch.RiscV
{
    public enum Mnemonic
    {
        invalid, 

        and,
        addi,
        addiw,
        andi,
        auipc,

        beq,
        bge,
        bgeu,
        blt,
        bltu,
        bne,

        c_add,
        c_addi,
        c_addi16sp,
        c_addi4spn,
        c_addiw,
        c_addw,
        c_and,
        c_andi,
        c_beqz,
        c_bnez,
        c_fld,
        c_fldsp,
        c_flw,
        c_flwsp,
        c_j,
        c_jalr,
        c_jr,
        c_ld,
        c_ldsp,
        c_li,
        c_lui,
        c_lw,
        c_lwsp,
        c_mv,
        c_or,
        c_sd,
        c_sdsp,
        c_slli,
        c_srai,
        c_srli,
        c_sub,
        c_subw,
        c_sw,
        c_swsp,
        c_xor,

        flw,

        jal,
        jalr,

        lui,

        lb,
        ld,
        lh,

        or,
        ori,
        lw,
        sb,
        sd,
        sh,
        sw,

        slli,
        sra,
        srai,
        srl,
        srli,

        slti,
        sltiu,
        xori,
        add,
        sub,
        sll,
        slt,
        sltu,
        xor,
        addw,
        subw,
        sllw,
        srlw,
        sraw,
        slliw,
        srliw,
        sraiw,
        lbu,
        lhu,

        fadd_d,
        fadd_s,
        fcvt_d_s,
        fcvt_s_d,
        feq_s,
        fmv_d_x,
        fmv_s_x,
        fmadd_s,
        fmsub_s,
        fnmsub_s,
        fnmadd_s,
        lwu,
        fsw,

        mulw,
        divw,
        remuw,
        fld,
        flq,
        fsd,
        c_fsdsp,
        c_fsd,
        remw,
        divuw,
        ecall,
        ebreak,
        fadd_q,
        fsub_q,
        fmul_q,
        fdiv_q,
        fsqrt_q,
        fsgnj_q,
        fsgnjn_q,
        fsgnjx_q,
        fmin_q,
        fmax_q,
        fcvt_s_q,
        fcvt_d_q,
        fcvt_q_s,
        fle_q,
        flt_q,
        fclass_q,
        fcvt_w_q,
        fcvt_wu_q,
        fcvt_q_w,
        fcvt_s_wu,
        fsub_d,
        fmul_s,
        fdiv_s,
        fsqrt_s,
        fsgnj_s,
        fsgnjn_s,
        fsgnjx_s,
        fmin_s,
        fmax_s,
        fcvt_w_s,
        fcvt_wu_s,
        fmv_x_w,
        fle_s,
        flt_s,
        fcvt_s_w,
        fmv_w_x,
        fcvt_l_s,
        fcvt_lu_s,
        fcvt_q_wu,
        fcvt_s_l,
        fcvt_s_lu,
        fsub_s,
        fmul_d,
        fdiv_d,
        fsqrt_d,
        fsgnj_d,
        fsgnjn_d,
        fsgnjx_d,
        fmin_d,
        fmax_d,
        fle_d,
        flt_d,
        feq_d,
        fcvt_w_d,
        fcvt_wu_d,
        fcvt_l_d,
        fcvt_lu_d,
        fcvt_d_w,
        fcvt_d_wu,
        fcvt_d_l,
        fcvt_d_lu,
        fcvt_l_q,
        fcvt_lu_q,
        fcvt_q_l,
        fcvt_q_lu,
        fcvt_q_d,
    }
}