Register word32 AppendMenuA(Stack word32 hMenu, Stack word32 uFlags, Stack word32 uIDNewItem, Stack word32 lpNewItem)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 BeginPaint(Stack word32 hWnd, Stack word32 lpPaint)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 BringWindowToTop(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 CheckRadioButton(Stack word32 hDlg, Stack word32 nIDFirstButton, Stack word32 nIDLastButton, Stack word32 nIDCheckButton)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 ClientToScreen(Stack word32 hWnd, Stack word32 lpPoint)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 CreatePopupMenu()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 CreateWindowExA(Stack word32 dwExStyle, Stack word32 lpClassName, Stack word32 lpWindowName, Stack word32 dwStyle, Stack word32 X, Stack word32 Y, Stack word32 nWidth, Stack word32 nHeight, Stack word32 hWndParent, Stack word32 hMenu, Stack word32 hInstance, Stack word32 lpParam)
// stackDelta: 48; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DefWindowProcA(Stack word32 hWnd, Stack word32 Msg, Stack word32 wParam, Stack word32 lParam)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DestroyMenu(Stack word32 hMenu)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DestroyWindow(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DialogBoxParamA(Stack word32 hInstance, Stack word32 lpTemplateName, Stack word32 hWndParent, Stack word32 lpDialogFunc, Stack word32 dwInitParam)
// stackDelta: 20; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DrawFocusRect(Stack word32 hDC, Stack word32 lprc)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DrawIcon(Stack word32 hDC, Stack word32 X, Stack word32 Y, Stack word32 hIcon)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 DrawTextA(Stack word32 hDC, Stack word32 lpString, Stack word32 nCount, Stack word32 lpRect, Stack word32 uFormat)
// stackDelta: 20; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 EndDialog(Stack word32 hDlg, Stack word32 nResult)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 EndPaint(Stack word32 hWnd, Stack word32 lpPaint)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 FillRect(Stack word32 hDC, Stack word32 lprc, Stack word32 hbr)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetAsyncKeyState(Stack word32 vKey)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetClientRect(Stack word32 hWnd, Stack word32 lpRect)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetDC(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetDesktopWindow()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetDlgItem(Stack word32 hDlg, Stack word32 nIDDlgItem)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetDlgItemTextA(Stack word32 hDlg, Stack word32 nIDDlgItem, Stack word32 lpString, Stack word32 nMaxCount)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetMenuCheckMarkDimensions()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetParent(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetSysColor(Stack word32 nIndex)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetSystemMetrics(Stack word32 nIndex)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetWindowLongA(Stack word32 hWnd, Stack word32 nIndex)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 GetWindowRect(Stack word32 hWnd, Stack word32 lpRect)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 InflateRect(Stack word32 lprc, Stack word32 dx, Stack word32 dy)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 InvalidateRect(Stack word32 hWnd, Stack word32 lpRect, Stack word32 bErase)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 KillTimer(Stack word32 hWnd, Stack word32 uIDEvent)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 LoadBitmapA(Stack word32 hInstance, Stack word32 lpBitmapName)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 LoadCursorA(Stack word32 hInstance, Stack word32 lpCursorName)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 LoadIconA(Stack word32 hInstance, Stack word32 lpIconName)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 MessageBeep(Stack word32 uType)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 MessageBoxA(Stack word32 hWnd, Stack word32 lpText, Stack word32 lpCaption, Stack word32 uType)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 MoveWindow(Stack word32 hWnd, Stack word32 X, Stack word32 Y, Stack word32 nWidth, Stack word32 nHeight, Stack word32 bRepaint)
// stackDelta: 24; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 OffsetRect(Stack word32 lprc, Stack word32 dx, Stack word32 dy)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 PostMessageA(Stack word32 hWnd, Stack word32 Msg, Stack word32 wParam, Stack word32 lParam)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 RegisterClassExA(Stack word32 WNDCLASSEXA *)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 ReleaseCapture()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 ReleaseDC(Stack word32 hWnd, Stack word32 hDC)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 ScreenToClient(Stack word32 hWnd, Stack word32 lpPoint)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SendDlgItemMessageA(Stack word32 hDlg, Stack word32 nIDDlgItem, Stack word32 Msg, Stack word32 wParam, Stack word32 lParam)
// stackDelta: 20; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SendMessageA(Stack word32 hWnd, Stack word32 Msg, Stack word32 wParam, Stack word32 lParam)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetCapture(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetCursor(Stack word32 hCursor)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetDlgItemTextA(Stack word32 hDlg, Stack word32 nIDDlgItem, Stack word32 lpString)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetFocus(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetRect(Stack word32 lprc, Stack word32 xLeft, Stack word32 yTop, Stack word32 xRight, Stack word32 yBottom)
// stackDelta: 20; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetTimer(Stack word32 hWnd, Stack word32 nIDEvent, Stack word32 uElapse, Stack word32 lpTimerFunc)
// stackDelta: 16; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetWindowLongA(Stack word32 hWnd, Stack word32 nIndex, Stack word32 dwNewLong)
// stackDelta: 12; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetWindowPos(Stack word32 hWnd, Stack word32 hWndInsertAfter, Stack word32 X, Stack word32 Y, Stack word32 cx, Stack word32 cy, Stack word32 uFlags)
// stackDelta: 28; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 SetWindowTextA(Stack word32 hWnd, Stack word32 lpString)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 ShowWindow(Stack word32 hWnd, Stack word32 nCmdShow)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 UnregisterClassA(Stack word32 lpClassName, Stack word32 hInstance)
// stackDelta: 8; fpuStackDelta: 0; fpuMaxParam: 0
Register word32 UpdateWindow(Stack word32 hWnd)
// stackDelta: 4; fpuStackDelta: 0; fpuMaxParam: 0
