// fn10000000
// Mem0:Global memory
// fp:Temporary
// edi:Register edi
// esi:Register esi
// ebx:Register ebx
// SCZO:Flags
// Z:Flags
// dwLoc08:Local -0008
// eax:Register eax
// return address size: 4
void fn10000000()
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	edi = 0x10000034
	esi = 0x00000003
	ebx = malloc
	// succ:  2
l1000002F:		// block 2, pred: 1 3
	SCZO = cond(esi - 0x00000000)
	branch Test(NE,Z) l10000015
	// succ:  4 3
l10000015:		// block 3, pred: 2
	dwLoc08 = 0x00000008
	eax = malloc(dwLoc08)
	store(Mem0[eax:word32]) = 0x00000000
	store(Mem0[eax + 0x00000004:word32]) = 0x00000000
	store(Mem0[edi:word32]) = eax
	esi = esi - 0x00000001
	edi = edi + 0x00000004
	SCZO = cond(edi)
	// succ:  2
l10000033:		// block 4, pred: 2
	return
	// succ:  5
fn10000000_exit:		// block 5, pred: 4
	// succ: 

