void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax bx al bl ah bh
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ds:Register ds
// ax:Register ax
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	ax = Mem0[ds:0x0300:word16]
	memfoo()
	store(Mem0[ds:0x0302:word16]) = ax
	ax = Mem0[ds:0x0300:word16]
	ax = membar(ax, ds)
	store(Mem0[ds:0x0304:word16]) = ax
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 
void memfoo()
// MayUse:  ax cx bx ds
// LiveOut:
// Trashed: SCZO ax cx bx al cl bl ah ch bh
// Preserved:
// memfoo
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// ds:Register ds
// bx:Register bx
// cx:Register cx
// cl:Register cl
// SCZO:Flags
// return address size: 2
void memfoo()
memfoo_entry:		// block 0, pred:
	// succ:  1
l0C00_0017:		// block 1, pred: 0
	store(Mem0[ds:0x0400:word16]) = ax
	store(Mem0[ds:0x0402:word16]) = bx
	store(Mem0[ds:0x0404:word16]) = cx
	bx = Mem0[ds:0x0100:word16]
	cl = Mem0[ds:bx + 0x0042:byte]
	ax = Mem0[ds:bx + 0x0040:word16]
	ax = ax << cl
	SCZO = cond(ax)
	store(Mem0[ds:0x0102:word16]) = ax
	ax = Mem0[ds:0x0400:word16]
	bx = Mem0[ds:0x0402:word16]
	cx = Mem0[ds:0x0404:word16]
	return
	// succ:  2
memfoo_exit:		// block 2, pred: 1
	// succ: 
Register word16 membar(Register word16 ax, Register selector ds)
// MayUse:  ax ds
// LiveOut: ax
// Trashed: SCZO ax bx al bl ah bh
// Preserved:
// membar
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// ds:Register ds
// bx:Register bx
// SCZO:Flags
// return address size: 2
word16 membar(word16 ax, selector ds)
membar_entry:		// block 0, pred:
	// succ:  1
l0C00_0040:		// block 1, pred: 0
	store(Mem0[ds:0x0500:word16]) = ax
	bx = Mem0[ds:0x1000:word16]
	ax = Mem0[ds:bx:word16]
	ax = ax + Mem0[ds:bx + 0x0002:word16]
	SCZO = cond(ax)
	store(Mem0[ds:bx + 0x0004:word16]) = ax
	ax = Mem0[ds:0x0500:word16]
	return ax
	// succ:  2
membar_exit:		// block 2, pred: 1
	// succ: 
