// WhileLtIncMock
void WhileLtIncMock()
WhileLtIncMock_entry:		// block 0, pred:
	def a
	// succ:  1
l1:		// block 1, pred: 0
	i_4 = 0x00000000
	// succ:  2
loopHdr:		// block 2, pred: 1 3
	i_5 = PHI(i_4, i_8)
	branch i_5 < 0x00000064 loop
	// succ:  4 3
loop:		// block 3, pred: 2
	store(Mem7[a + i_5 * 0x00000004:word32]) = 0x00000000
	i_8 = i_5 + 0x00000001
	// succ:  2
l2:		// block 4, pred: 2
	return
	// succ:  5
WhileLtIncMock_exit:		// block 5, pred: 4
	// succ: 

(0x00000000 0x00000001 0x00000064 signed)
