// redir_rodata.c
// Generated by decompiling redir
// using Reko decompiler version 0.11.6.0.

#include "redir.h"

<unknown> g_t409DD4 = // 00409DD4;
<unknown> g_t409E04 = // 00409E04;
char g_str409E44[] = "w"; // 00409E44
char g_str409E4C[] = "a"; // 00409E4C
<unknown> g_t409E50 = // 00409E50;
<unknown> g_t409EB0 = // 00409EB0;
<unknown> g_t409ECC = // 00409ECC;
<unknown> g_t409F00 = // 00409F00;
<unknown> g_t409F28 = // 00409F28;
<unknown> g_t409F60 = // 00409F60;
char g_str409F94[] = "CONNECT %s:%d HTTP/1.1\r\nHost: %s:%d\r\n\r\n"; // 00409F94
char g_str409FBC[] = "host: "; // 00409FBC
<unknown> g_t409FC4 = // 00409FC4;
char g_str409FE0[] = "content-length: "; // 00409FE0
char g_str409FF4[] = "Content-Length: "; // 00409FF4
<unknown> g_t40A008 = // 0040A008;
<unknown> g_t40A03C = // 0040A03C;
<unknown> g_t40A074 = // 0040A074;
<unknown> g_t40A0B4 = // 0040A0B4;
<unknown> g_t40A0E4 = // 0040A0E4;
<unknown> g_t40A124 = // 0040A124;
<unknown> g_t40A148 = // 0040A148;
<unknown> g_t40A174 = // 0040A174;
char g_str40A1A8[] = "HTTP"; // 0040A1A8
<unknown> g_t40A1B0 = // 0040A1B0;
<unknown> g_t40A1F4 = // 0040A1F4;
<unknown> g_t40A224 = // 0040A224;
<unknown> g_t40A268 = // 0040A268;
<unknown> g_t40A2A0 = // 0040A2A0;
<unknown> g_t40A308 = // 0040A308;
<unknown> g_t40A344 = // 0040A344;
<unknown> g_t40A364 = // 0040A364;
<unknown> g_t40A398 = // 0040A398;
<unknown> g_t40A3C4 = // 0040A3C4;
char g_str40A3FC[] = "http://"; // 0040A3FC
char g_str40A404[] = "%s %s %s\r\n"; // 0040A404
char g_str40A410[] = "%s http://%s%s %s\r\n"; // 0040A410
char g_str40A424[] = "%s http://%s/%s %s\r\n"; // 0040A424
<unknown> g_t40A464 = // 0040A464;
char g_str40A468[] = " \n\r"; // 0040A468
char g_str40A46C[] = " \t"; // 0040A46C
<unknown> g_t40A470 = // 0040A470;
<unknown> g_t40A4AC = // 0040A4AC;
<unknown> g_t40A4D0 = // 0040A4D0;
<unknown> g_t40A4F0 = // 0040A4F0;
<unknown> g_t40A538 = // 0040A538;
<unknown> g_t40A564 = // 0040A564;
<unknown> g_t40A590 = // 0040A590;
char g_str40A5C0[] = "1yY"; // 0040A5C0
<unknown> g_t40A5C4 = // 0040A5C4;
<unknown> g_t40A5EC = // 0040A5EC;
char g_str40A614[] = "r"; // 0040A614
<unknown> g_t40A618 = // 0040A618;
char g_str40A640[] = " \t"; // 0040A640
char g_str40A644[] = " \t="; // 0040A644
<unknown> g_t40A648 = // 0040A648;
<unknown> g_t40A704 = // 0040A704;
char g_str40A73C[] = "-"; // 0040A73C
char g_str40A740[] = "w"; // 0040A740
char g_str40A744[] = ".old"; // 0040A744
char g_str40A74C[] = "%Y-%m-%d %H:%M:%S"; // 0040A74C
<unknown> g_t40A770 = // 0040A770;
<unknown> g_t40A79C = // 0040A79C;
<unknown> g_t40A7D4 = // 0040A7D4;
<unknown> g_t40A7FC = // 0040A7FC;
<unknown> g_t40A81C = // 0040A81C;
<unknown> g_t40A850 = // 0040A850;
<unknown> g_t40A87C = // 0040A87C;
