// SegmentedPointerProc
void SegmentedPointerProc()
SegmentedPointerProc_entry:
	// succ:  l1
l1:
	Mem0[0x0300:word16] = 0x1234
	Mem0[0x0302:word16] = 0x5550
	es_bx = Mem0[0x0300:segptr32]
	Mem0[0x0304:word16] = Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 0x0004:word16]
SegmentedPointerProc_exit:

// Equivalence classes ////////////
Eq_1: (struct (300 Eq_2 t0300) (302 word16 w0302) (304 word16 w0304))
	Globals (in globals : (ptr (struct "Globals")))
Eq_2: (union (segptr32 u0) (word16 u1))
	T_2 (in 0x1234 : word16)
	T_4 (in Mem0[0x0300:word16] : word16)
	T_9 (in Mem0[0x0300:segptr32] : segptr32)
	T_10 (in es_bx : segptr32)
Eq_11: (segment)
	T_11 (in SLICE(es_bx, selector, 16) : selector)
Eq_12: (struct (4 word16 w0004))
	T_12 (in SLICE(es_bx, word16, 0) : word16)
// Type Variables ////////////
Globals: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (300 T_2 t0300) (302 T_7 t0302) (304 T_17 t0304)))
T_2: (in 0x1234 : word16)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: word16
T_3: (in 0x0300 : word16)
  Class: Eq_3
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (0 T_4 t0000)))
T_4: (in Mem0[0x0300:word16] : word16)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: word16
T_5: (in 0x5550 : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in 0x0302 : word16)
  Class: Eq_6
  DataType: (ptr word16)
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem0[0x0302:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_8: (in 0x0300 : word16)
  Class: Eq_8
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (0 T_9 t0000)))
T_9: (in Mem0[0x0300:segptr32] : segptr32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: segptr32
T_10: (in es_bx : segptr32)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: segptr32
T_11: (in SLICE(es_bx, selector, 16) : selector)
  Class: Eq_11
  DataType: (ptr Eq_11)
  OrigDataType: (ptr (segment))
T_12: (in SLICE(es_bx, word16, 0) : word16)
  Class: Eq_12
  DataType: (memptr (ptr Eq_11) Eq_12)
  OrigDataType: (memptr T_11 (struct (4 T_15 t0004)))
T_13: (in 0x0004 : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in SLICE(es_bx, word16, 0) + 0x0004 : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in Mem0[SLICE(es_bx, selector, 16):SLICE(es_bx, word16, 0) + 0x0004:word16] : word16)
  Class: Eq_15
  DataType: word16
  OrigDataType: word16
T_16: (in 0x0304 : word16)
  Class: Eq_16
  DataType: (ptr word16)
  OrigDataType: (ptr (struct (0 T_17 t0000)))
T_17: (in Mem0[0x0304:word16] : word16)
  Class: Eq_15
  DataType: word16
  OrigDataType: word16
