// Equivalence classes ////////////
Eq_1: (ptr (struct (10000000 T_8 t10000000) (10000004 T_5 t10000004)))
	Globals (in globals : ptr32)
Eq_2: (ptr (struct (0 T_5 t0000)))
	T_2 (in ptr : word32)
	T_3 (in 0x10000004 : word32)
Eq_4: real32
	T_4 (in 0.75F : real32)
	T_5 (in Mem0[ptr:real32] : real32)
Eq_6: real32
	T_6 (in 0.5F : real32)
	T_8 (in Mem0[0x10000000:real32] : real32)
Eq_7: (ptr (struct (0 T_8 t0000)))
	T_7 (in 0x10000000 : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: (ptr (struct (10000000 T_8 t10000000) (10000004 T_5 t10000004)))
  OrigDataType: (ptr (struct (10000000 T_8 t10000000) (10000004 T_5 t10000004)))
T_2: (in ptr : word32)
  Class: Eq_2
  DataType: (ptr (struct (0 T_5 t0000)))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_3: (in 0x10000004 : word32)
  Class: Eq_2
  DataType: (ptr (struct (0 T_5 t0000)))
  OrigDataType: word32
T_4: (in 0.75F : real32)
  Class: Eq_4
  DataType: real32
  OrigDataType: real32
T_5: (in Mem0[ptr:real32] : real32)
  Class: Eq_4
  DataType: real32
  OrigDataType: real32
T_6: (in 0.5F : real32)
  Class: Eq_6
  DataType: real32
  OrigDataType: real32
T_7: (in 0x10000000 : word32)
  Class: Eq_7
  DataType: (ptr (struct (0 T_8 t0000)))
  OrigDataType: (ptr (struct (0 T_8 t0000)))
T_8: (in Mem0[0x10000000:real32] : real32)
  Class: Eq_6
  DataType: real32
  OrigDataType: real32
