// Equivalence classes ////////////
Eq_1: (ptr (struct (0 (arr (struct 1 (0 T_3 t0000)) 10) a0000) (10000 (arr (struct 4 (0 T_5 t0000)) 16) a10000)))
	T_1 (in globals : ptr32)
Eq_2: (ptr (struct 1 (0 T_3 t0000)))
	T_2 (in i : word32)
Eq_3: int32
	T_3 (in Mem0[i:int32] : int32)
Eq_4: (ptr (struct 4 (0 T_5 t0000)))
	T_4 (in i2 : word32)
Eq_5: int32
	T_5 (in Mem0[i2:int32] : int32)
// Type Variables ////////////
T_1: (in globals : ptr32)
  Class: Eq_1
  DataType: (ptr (struct (0 (arr (struct 1 (0 T_3 t0000)) 10) a0000) (10000 (arr (struct 4 (0 T_5 t0000)) 16) a10000)))
  OrigDataType: (ptr (struct (0 (arr (struct 1 (0 T_3 t0000)) 10) a0000) (10000 (arr (struct 4 (0 T_5 t0000)) 16) a10000)))
T_2: (in i : word32)
  Class: Eq_2
  DataType: (ptr (struct 1 (0 T_3 t0000)))
  OrigDataType: (ptr (struct 1 (0 T_3 t0000)))
T_3: (in Mem0[i:int32] : int32)
  Class: Eq_3
  DataType: int32
  OrigDataType: int32
T_4: (in i2 : word32)
  Class: Eq_4
  DataType: (ptr (struct 4 (0 T_5 t0000)))
  OrigDataType: (ptr (struct 4 (0 T_5 t0000)))
T_5: (in Mem0[i2:int32] : int32)
  Class: Eq_5
  DataType: int32
  OrigDataType: int32
