// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	word16 ax_8 = 0x0000
	// succ:  l0C00_0002
l0C00_0002:		// pred: l0C00_0000 l0C00_0006
	branch bx == 0x0000 l0C00_000D
	// succ:  l0C00_0006 l0C00_000D
l0C00_0006:		// pred: l0C00_0002
	ax_8 = ax_8 + 0x0001
	bx = Mem0[ds:bx + 0x0004:word16]
	// succ:  l0C00_0002
l0C00_000D:		// pred: l0C00_0002
	Mem15[ds:0x0200:word16] = ax_8
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_000D
	// succ: 

T_2 (in ax_8 : word16)
	trait_primitive(word16)
	trait_equal(T_3)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_primitive(word16)
	trait_equal(T_11)
T_3 (in 0x0000 : word16)
	trait_primitive(word16)
T_4 (in bx : word16)
	trait_primitive(word16)
	trait_equal(T_5)
	trait_primitive(word16)
	trait_mem(T_7:T_14, 4)
	trait_primitive(word16)
	trait_equal(T_14)
T_5 (in 0x0000 : word16)
	trait_primitive(word16)
T_6 (in bx == 0x0000 : bool)
	trait_primitive(bool)
T_7 (in ds : selector)
	trait_primitive(selector)
	trait_mem(T_9, 200)
	trait_primitive(selector)
T_8 (in 0x0200 : word16)
	trait_primitive(word16)
	trait_mem(T_7:T_9, 0)
T_9 (in Mem15[ds:0x0200:word16] : word16)
	trait_primitive(word16)
	trait_equal(T_2)
T_10 (in 0x0001 : word16)
	trait_primitive(word16)
T_11 (in ax_8 + 0x0001 : word16)
	trait_primitive(word16)
T_12 (in 0x0004 : word16)
	trait_primitive(word16)
T_13 (in bx + 0x0004 : word16)
	trait_primitive(word16)
T_14 (in Mem0[ds:bx + 0x0004:word16] : word16)
	trait_primitive(word16)
