// PP.globals.c
// Generated by decompiling PP.EXE
// using Reko decompiler version 0.11.6.0.

#include "PP.h"

Eq_n g_tFFFF9D35;
Eq_n g_tFFFF9D37;
Eq_n g_tFFFF9D39;
Eq_n g_tFFFF9D3B;
word16 g_wFFFF9D3D; // F800:9D3D
word16 g_wFFFF9D3F; // F800:9D3F
int16 g_aFFFFBC39[];
Eq_n g_aFFFFBC41[];
int16 g_aFFFFBE1F[];
Eq_n g_aFFFFBE2D[];
Eq_n g_tADDCAFE0;
