// RTOSDemo_privileged_data.c
// Generated by decompiling RTOSDemo.axf
// using Reko decompiler version 0.9.3.0.

#include "RTOSDemo.h"

Eq_n g_t200000C4 = 
	{
		0x00,
		null,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
struct Eq_n * g_ptr200000C8 = null;
