// RTOSDemo_data.c
// Generated by decompiling RTOSDemo.axf
// using Reko decompiler version 0.11.1.0.

#include "RTOSDemo.h"

word32 g_a20000000[] = // 20000000
	{
	};
word32 uxErrorStatus = 0x01; // 200000B8
word32 uxCriticalNesting = 0xAAAAAAAA; // 200000BC
word32 xCoRoutineFlashStatus = 0x01; // 200000C0
