// FnPointerMock
void FnPointerMock()
FnPointerMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	pfn = 0x01213130
	store(Mem0[0x10000000:word32]) = pfn
	icall Mem0[0x10000000:word32]
	// succ: 

Globals (in globals : ptr32)
	trait_mem(T_5, 10000000)
	trait_mem(T_7, 10000000)
T_2 (in 0x01213130 : word32)
	trait_primitive(word32)
T_3 (in pfn : word32)
	trait_primitive(word32)
	trait_equal(T_2)
	trait_primitive(word32)
T_4 (in 0x10000000 : word32)
	trait_primitive(word32)
	trait_mem(T_5, 0)
T_5 (in Mem0[0x10000000:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_3)
T_6 (in 0x10000000 : word32)
	trait_primitive(word32)
	trait_mem(T_7, 0)
T_7 (in Mem0[0x10000000:word32] : word32)
	trait_primitive(word32)
	trait_func( -> )
