// CmpMock
void CmpMock()
CmpMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	Z = cond(r0 - 0x00000000)
	branch Test(EQ,Z) skip
	// succ:  2 3
l2:		// block 2, pred: 1
	r0 = r0 + r1
	// succ:  3
skip:		// block 3, pred: 1 2
	store(Mem0[0x10003000:word32]) = r0
	return
	// succ:  4
CmpMock_exit:		// block 4, pred: 3
	// succ: 

Globals (in globals : ptr32)
	trait_mem(T_11, 10003000)
T_2 (in r0 : word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_primitive(word32)
	trait_equal(T_9)
	trait_primitive(word32)
T_3 (in 0x00000000 : word32)
	trait_primitive(word32)
T_4 (in r0 - 0x00000000 : word32)
	trait_primitive(word32)
T_5 (in cond(r0 - 0x00000000) : byte)
	trait_primitive(byte)
T_6 (in Z : byte)
	trait_primitive(byte)
	trait_equal(T_5)
	trait_primitive(byte)
T_7 (in Test(EQ,Z) : bool)
	trait_primitive(bool)
T_8 (in r1 : word32)
	trait_primitive(word32)
T_9 (in r0 + r1 : word32)
	trait_primitive(word32)
T_10 (in 0x10003000 : word32)
	trait_primitive(word32)
	trait_mem(T_11, 0)
T_11 (in Mem0[0x10003000:word32] : word32)
	trait_primitive(word32)
	trait_equal(T_2)
