// FnPointerMock
void FnPointerMock()
FnPointerMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	pfn = 0x01213130
	store(Mem0[0x10000000:word32]) = pfn
	icall Mem0[0x10000000:word32]
	// succ: 

// Equivalence classes ////////////
Eq_1: (struct (10000000 (ptr Eq_2) ptr10000000))
	Globals (in globals : ptr32)
Eq_2: (fn void ())
	T_2 (in 0x01213130 : word32)
	T_3 (in pfn : word32)
	T_5 (in Mem0[0x10000000:word32] : word32)
	T_7 (in Mem0[0x10000000:word32] : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (10000000 T_2 t10000000)))
T_2: (in 0x01213130 : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: word32
T_3: (in pfn : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: word32
T_4: (in 0x10000000 : word32)
  Class: Eq_4
  DataType: (ptr (ptr Eq_2))
  OrigDataType: (ptr (struct (0 T_5 t0000)))
T_5: (in Mem0[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: word32
T_6: (in 0x10000000 : word32)
  Class: Eq_6
  DataType: (ptr (ptr Eq_2))
  OrigDataType: (ptr (struct (0 T_7 t0000)))
T_7: (in Mem0[0x10000000:word32] : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn void ()))
