// IntelIndexedAddressingMode
void IntelIndexedAddressingMode()
IntelIndexedAddressingMode_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	es = Mem0[0x7070:word16]
	ax = 0x004A
	si = ax *s Mem0[0x1C0A:word16]
	bx = Mem0[0x0CA4:word16]
	store(Mem0[bx + 0x000A + si:byte]) = 0xF8
	return
	// succ:  2
IntelIndexedAddressingMode_exit:		// block 2, pred: 1
	// succ: 

// Equivalence classes ////////////
Eq_1: (struct (CA4 word16 w0CA4) (1C0A int16 w1C0A) (7070 word16 w7070))
	Globals (in globals : ptr32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (CA4 T_12 t0CA4) (1C0A T_8 t1C0A) (7070 T_3 t7070)))
T_2: (in 0x7070 : word16)
  Class: Eq_2
  DataType: (ptr word16)
  OrigDataType: (ptr (struct (0 T_3 t0000)))
T_3: (in Mem0[0x7070:word16] : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_4: (in es : word16)
  Class: Eq_3
  DataType: word16
  OrigDataType: word16
T_5: (in 0x004A : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: word16
T_6: (in ax : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_7: (in 0x1C0A : word16)
  Class: Eq_7
  DataType: (ptr int16)
  OrigDataType: (ptr (struct (0 T_8 t0000)))
T_8: (in Mem0[0x1C0A:word16] : word16)
  Class: Eq_8
  DataType: int16
  OrigDataType: int16
T_9: (in ax *s Mem0[0x1C0A:word16] : int16)
  Class: Eq_9
  DataType: int16
  OrigDataType: int16
T_10: (in si : word16)
  Class: Eq_9
  DataType: int16
  OrigDataType: word16
T_11: (in 0x0CA4 : word16)
  Class: Eq_11
  DataType: (ptr word16)
  OrigDataType: (ptr (struct (0 T_12 t0000)))
T_12: (in Mem0[0x0CA4:word16] : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in bx : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_14: (in 0xF8 : byte)
  Class: Eq_14
  DataType: byte
  OrigDataType: byte
T_15: (in 0x000A : word16)
  Class: Eq_15
  DataType: word16
  OrigDataType: word16
T_16: (in bx + 0x000A : word16)
  Class: Eq_16
  DataType: (ptr byte)
  OrigDataType: (ptr (struct (0 T_18 t0000)))
T_17: (in bx + 0x000A + si : word16)
  Class: Eq_17
  DataType: word16
  OrigDataType: word16
T_18: (in Mem0[bx + 0x000A + si:byte] : byte)
  Class: Eq_14
  DataType: byte
  OrigDataType: byte
