// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	f = p->ptr0004 < 0x00000003;
	// succ: 

// Equivalence classes ////////////
Eq_2: (struct "Eq_2" (4 (ptr Eq_5) ptr0004))
	T_2 (in p : word32)
Eq_5: (struct "foo" 8)
	T_5 (in Mem0[p + 0x00000004:(ptr (struct "foo" 8))] : (ptr (struct "foo" 8)))
	T_6 (in 0x00000003 : word32)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in p : word32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (struct (4 T_5 t0004)))
T_3: (in 0x00000004 : word32)
  Class: Eq_3
  DataType: word32
  OrigDataType: word32
T_4: (in p + 0x00000004 : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in Mem0[p + 0x00000004:(ptr (struct "foo" 8))] : (ptr (struct "foo" 8)))
  Class: Eq_5
  DataType: (ptr Eq_5)
  OrigDataType: (ptr (struct "foo" 8))
T_6: (in 0x00000003 : word32)
  Class: Eq_5
  DataType: (ptr Eq_5)
  OrigDataType: int32
T_7: (in p->ptr0004 < 0x00000003 : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
T_8: (in f : bool)
  Class: Eq_7
  DataType: bool
  OrigDataType: bool
