// ProcedureMock
void ProcedureMock()
ProcedureMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	bx = bx >>u 0x02;
	f = bx < 0x0004;
	bx.u0 = 0x0004;
	// succ: 

// Equivalence classes ////////////
Eq_2: (union "Eq_2" (int16 u0) (uint16 u1))
	T_2 (in bx : word16)
	T_4 (in bx >>u 0x02 : word16)
	T_5 (in 0x0004 : word16)
	T_8 (in 0x0004 : word16)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in bx : word16)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: (union (int16 u0) (uint16 u1))
T_3: (in 0x02 : byte)
  Class: Eq_3
  DataType: uint8
  OrigDataType: uint8
T_4: (in bx >>u 0x02 : word16)
  Class: Eq_2
  DataType: Eq_2
  OrigDataType: uint16
T_5: (in 0x0004 : word16)
  Class: Eq_2
  DataType: int16
  OrigDataType: int16
T_6: (in bx < 0x0004 : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in f : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_8: (in 0x0004 : word16)
  Class: Eq_2
  DataType: int16
  OrigDataType: word16
