// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem11[ds:0x9A2E:word16]) = 0x0000
	store(Mem13[ds:0x9A26:word16]) = 0x0100
	word16 si_16 = 0x0000
	// succ:  2
l0C00_0015:		// block 2, pred: 1 2
	store(Mem19[0x5CE1:si_16 + 0x0000:word16]) = 0xFFFF
	word16 v8_22 = Mem19[ds:0x9A26:word16] - 0x0001
	store(Mem23[ds:0x9A26:word16]) = v8_22
	si_16 = si_16 + 0x0026
	branch v8_22 != 0x0000
	// succ:  3 2
l0C00_0023:		// block 3, pred: 2
	return
	// succ:  4
fn0C00_0000_exit:		// block 4, pred: 3
	// succ: 

// Equivalence classes ////////////
Eq_1: (struct (5CE1 word16 w5CE1))
	Globals (in globals : ptr0)
Eq_3: (segment (9A26 word16 w9A26) (9A2E word16 w9A2E))
	T_3 (in ds : selector)
Eq_9: (struct 26 (0 word16 w0000))
	T_9 (in si_16 : word16)
	T_10 (in 0x0000 : word16)
	T_23 (in si_16 + 0x0026 : word16)
Eq_12: (segment (0 word16 w0000))
	T_12 (in 0x5CE1 : selector)
Eq_13: (arr Eq_26)
	T_13 (in 0x0000 : word16)
Eq_26: (struct 26)
	T_26
// Type Variables ////////////
Globals: (in globals : ptr0)
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct (5CE1 T_15 t5CE1)))
T_2: (in 0x0000 : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_3: (in ds : selector)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (segment (9A26 T_6 t9A26) (9A2E T_5 t9A2E)))
T_4: (in 0x9A2E : word16)
  Class: Eq_4
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_5 t0000)))
T_5: (in Mem11[ds:0x9A2E:word16] : word16)
  Class: Eq_2
  DataType: word16
  OrigDataType: word16
T_6: (in 0x0100 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_7: (in 0x9A26 : word16)
  Class: Eq_7
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_8 t0000)))
T_8: (in Mem13[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_9: (in si_16 : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: (memptr T_12 (struct 26 (0 T_15 t0000)))
T_10: (in 0x0000 : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: word16
T_11: (in 0xFFFF : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_12: (in 0x5CE1 : selector)
  Class: Eq_12
  DataType: (ptr Eq_12)
  OrigDataType: (ptr (segment (0 T_15 t0000)))
T_13: (in 0x0000 : word16)
  Class: Eq_13
  DataType: (ptr Eq_13)
  OrigDataType: (ptr (arr (struct 26)))
T_14: (in si_16 + 0x0000 : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in Mem19[0x5CE1:si_16 + 0x0000:word16] : word16)
  Class: Eq_11
  DataType: word16
  OrigDataType: word16
T_16: (in v8_22 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_17: (in 0x9A26 : word16)
  Class: Eq_17
  DataType: (memptr (ptr Eq_3) word16)
  OrigDataType: (memptr T_3 (struct (0 T_6 t0000)))
T_18: (in Mem19[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_19: (in 0x0001 : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in Mem19[ds:0x9A26:word16] - 0x0001 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_21: (in Mem23[ds:0x9A26:word16] : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_22: (in 0x0026 : word16)
  Class: Eq_22
  DataType: word16
  OrigDataType: word16
T_23: (in si_16 + 0x0026 : word16)
  Class: Eq_9
  DataType: (memptr (ptr Eq_12) Eq_9)
  OrigDataType: word16
T_24: (in 0x0000 : word16)
  Class: Eq_6
  DataType: word16
  OrigDataType: word16
T_25: (in v8_22 != 0x0000 : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26:
  Class: Eq_26
  DataType: Eq_26
  OrigDataType: 
