// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem6[ds:bx + 0x0000:word32]) = Mem0[ds:bx + 0x0004:word32]
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// Equivalence classes ////////////
Eq_2: (segment)
	T_2 (in ds : selector)
Eq_3: (struct (0 word32 dw0000) (4 word32 dw0004))
	T_3 (in bx : word16)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in ds : selector)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment))
T_3: (in bx : word16)
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) Eq_3)
  OrigDataType: (memptr T_2 (struct (0 T_9 t0000) (4 T_6 t0004)))
T_4: (in 0x0004 : word16)
  Class: Eq_4
  DataType: word16
  OrigDataType: word16
T_5: (in bx + 0x0004 : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in Mem0[ds:bx + 0x0004:word32] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in 0x0000 : word16)
  Class: Eq_7
  DataType: word16
  OrigDataType: word16
T_8: (in bx + 0x0000 : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in Mem6[ds:bx + 0x0000:word32] : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
