using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reko.Arch.Tms7000
{
    public enum Mnemonic
    {
        invalid,

        adc,
        add,
        and,
        andp,
        br,
        btjo,
        btjop,
        btjz,
        btjzp,
        call,
        clr,
        cmp,
        cmpa,
        dac,
        dec,
        djnz,
        dint,
        decd,
        dsb,
        eint,
        idle,
        inc,
        inv,
        jmp,
        jeq,
        jge,
        jgt,
        jhs,
        jl,
        jne,
        lda,
        ldsp,
        mov,
        movd,
        movp,
        mpy,
        nop,
        or,
        orp,
        pop,
        push,
        reti,
        rets,
        rl,
        rlc,
        rr,
        rrc,
        sbb,
        setc,
        sta,
        stsp,
        sub,
        swap,
        trap_0,
        trap_1,
        trap_2,
        trap_3,
        trap_4,
        trap_5,
        trap_6,
        trap_7,
        trap_8,
        trap_9,
        trap_10,
        trap_11,
        trap_12,
        trap_13,
        trap_14,
        trap_15,
        trap_16,
        trap_17,
        trap_18,
        trap_19,
        trap_20,
        trap_21,
        trap_22,
        trap_23,

        tsta,
        tstb,
        xchb,
        xor,
        xorp,
    }
}