// fft_static.c
// Generated by decompiling fft.hex
// using Reko decompiler version 0.10.1.0.

#include "fft.h"

struct Eq_n g_tFFFF8000 = // 8000
	{
		
		{
			;
struct Eq_n g_tFFFF800C = // 800C
			{
				
				{
					;
struct Eq_n g_tFFFF801B = // 801B
					{
						
						{
							;
Eq_n g_aFFFF8030[] = // 8030
							{
							};
real48 g_rFFFF8054 = ;
real48 g_r8057 = ;
union Eq_n g_uFFFF805D = // 805D
							{
								0x00
							};
Eq_n g_t805F = // 805F
							{
								0x00
							};
Eq_n g_aFFFF8060[] = // 8060
							{
							};
real48 g_rFFFF8061 = ;
real48 g_r8064 = ;
word32 g_dwFFFF806A = 0x00; // 806A
word32 g_dw806C = 0x00; // 806C
struct Eq_n g_tFFFF806E = // 806E
							{
								
								{
									;
