// redir.c
// Generated by decompiling redir
// using Decompiler version 0.5.5.0.

#include "redir.h"

void fn00400230(Eq_2 * ra, word32 dwArg00)
{
fn00400230_entry:
l00400230:
l00400230_ds_f:
	goto l00400238
l00400230_ds_f:
	goto l00400238
l00400230_ds_t:
	goto l00400238
l00400230_ds_t:
l00400238:
	code * r25_18 = ra->ptrFC00690
	word32 sp_19
	word32 r28_20
	word32 ra_21
	word32 r4_22
	word32 r5_23
	word32 r6_24
	word32 r7_25
	word32 r2_26
	word32 r25_27
	r25_18()
	code * r25_42 = globals->ptrFC00690
	word32 sp_43
	word32 r28_44
	word32 ra_45
	word32 r4_46
	word32 r5_47
	word32 r6_48
	word32 r7_49
	word32 r2_50
	word32 r25_51
	r25_42()
l00400284:
	goto l00400284
fn00400230_exit:
}

