// test.c
// Generated by decompiling test.exe
// using Reko decompiler version 0.8.0.2.

#include "test.h"

// 00011000: Register word32 fn00011000(Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Register out ptr32 raOut)
word32 fn00011000(word32 dwArg00, word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & raOut)
{
	memset(fp + -0x0014, 0x00, 0x05);
	memcpy(calloc(0x01, 0x05), fp + ~0x1B, 0x05);
	dwLoc24->b0000 = 0x0C;
	dwLoc24->dw0001 = 0x00;
	raOut = dwLoc14;
	return 0x00;
}

// 000110A0: Register Eq_46 Win32CrtStartup()
Eq_46 Win32CrtStartup()
{
	fn000111C4(r2, r9, ra);
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	word32 stackArg12 = <invalid>;
	return fn000110E8(ra, stackArg0, stackArg4, stackArg8, stackArg12);
}

// 000110E8: Register Eq_69 fn000110E8(Register word32 ra, Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C)
Eq_69 fn000110E8(word32 ra, word32 dwArg00, word32 dwArg04, word32 dwArg08, word32 dwArg0C)
{
	fn000114E4(ra);
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	word32 stackArg12 = <invalid>;
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 ra_30;
	Eq_69 r2_25 = fn00011000(stackArg0, stackArg4, stackArg8, stackArg12, out ra_30);
	word32 stackArg0 = <invalid>;
	fn00011278(r2_25, r2_25, ra_30, stackArg0);
	return r2_25;
}

// 0001116C: void fn0001116C(Register (ptr32 Eq_92) r2, Register (ptr32 (ptr32 word32)) r4, Register word32 r30, Register word32 ra)
void fn0001116C(struct Eq_92 * r2, word32 ** r4, word32 r30, word32 ra)
{
	r2->ptrFFFFFFEC = r4;
	r2->ptrFFFFFFF0 = r2->ptrFFFFFFEC;
	r2->dwFFFFFFF4 = **r2->ptrFFFFFFEC;
	word32 r8_18 = r2->dwFFFFFFF4;
	r2->dwFFFFFFE8 = r8_18;
	XcptFilter();
}

// 000111C4: void fn000111C4(Register word32 r2, Register ui32 r9, Register word32 ra)
void fn000111C4(word32 r2, ui32 r9, word32 ra)
{
	ui32 r8_7 = globals->dw13030;
	ui32 r8_11 = r8_7;
	if (r8_7 != 0x00)
	{
		r9 = r8_7;
		r8_11 = 0xB064;
		if (r8_7 != 0xB064)
		{
			globals->dw13034 = ~r8_7;
			return;
		}
	}
	uint32 r2_21;
	COREDLL.dll!Ordinal_2696();
	ui32 r8_29 = r2_21 >> 0x10 ^ r2_21 + 0xFFFF;
	ui32 dwLoc0C_57 = r8_29;
	if (r8_29 == 0x00)
		dwLoc0C_57 = 0xB064;
	globals->dw13030 = dwLoc0C_57;
	globals->dw13034 = ~dwLoc0C_57;
}

// 00011278: void fn00011278(Register Eq_69 r2, Register Eq_69 r4, Register word32 ra, Stack word32 dwArg00)
void fn00011278(Eq_69 r2, Eq_69 r4, word32 ra, word32 dwArg00)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	fn000112A8(r2, r4, 0x00, 0x00, ra, stackArg0, stackArg4, stackArg8);
}

// 000112A8: void fn000112A8(Register Eq_69 r2, Register Eq_69 r4, Register int32 r5, Register int32 r6, Register word32 ra, Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08)
void fn000112A8(Eq_69 r2, Eq_69 r4, int32 r5, int32 r6, word32 ra, word32 dwArg00, word32 dwArg04, word32 dwArg08)
{
	globals->b13038 = (byte) (r6 << 0x18 >> 0x18);
	if (r5 != 0x00)
	{
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		word32 stackArg0 = <invalid>;
		word32 stackArg4 = <invalid>;
		fn0001147C(&globals->dw12018, &globals->dw1201C, ra, stackArg0, stackArg4);
		if (r6 != 0x00)
			return;
		TerminateProcess(fn00011460(), r4);
	}
	else if (globals->t13040 == 0x00)
	{
l00011374:
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		word32 stackArg0 = <invalid>;
		word32 stackArg4 = <invalid>;
		fn0001147C(&globals->dw12010, &globals->dw12014, ra, stackArg0, stackArg4);
	}
	else
	{
		do
		{
			globals->t1303C = (word32) globals->t1303C - 0x04;
			Eq_196 r9_42 = globals->t1303C;
			if ((word32) (r9_42 < globals->t13040) != 0x00)
			{
				free(globals->t13040);
				globals->t1303C.u0 = 0x00;
				globals->t13040 = globals->t1303C;
				goto l00011374;
			}
		} while (*globals->t1303C == null);
		<anonymous> * r8_69 = *globals->t1303C;
		r8_69();
	}
}

// 000113D8: void fn000113D8(Register Eq_69 r2, Register Eq_69 r4, Register word32 ra, Stack word32 dwArg00)
void fn000113D8(Eq_69 r2, Eq_69 r4, word32 ra, word32 dwArg00)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	fn000112A8(r2, r4, 0x01, 0x00, ra, stackArg0, stackArg4, stackArg8);
}

// 00011408: void fn00011408(Register Eq_69 r2, Register word32 ra)
void fn00011408(Eq_69 r2, word32 ra)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	fn000112A8(r2, 0x00, 0x00, 0x01, ra, stackArg0, stackArg4, stackArg8);
}

// 00011434: void fn00011434(Register Eq_69 r2, Register word32 ra)
void fn00011434(Eq_69 r2, word32 ra)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	word32 stackArg8 = <invalid>;
	fn000112A8(r2, 0x00, 0x01, 0x01, ra, stackArg0, stackArg4, stackArg8);
}

// 00011460: Register int32 fn00011460()
int32 fn00011460()
{
	return 66;
}

// 0001147C: void fn0001147C(Register (ptr32 word32) r4, Register (ptr32 word32) r5, Register word32 ra, Stack word32 dwArg00, Stack word32 dwArg04)
void fn0001147C(word32 * r4, word32 * r5, word32 ra, word32 dwArg00, word32 dwArg04)
{
	word32 * dwArg00_33 = r4;
	while ((word32) (dwArg00_33 < r5) != 0x00)
	{
		if (*dwArg00_33 != 0x00)
			fn00000000();
		++dwArg00_33;
	}
}

// 000114E4: void fn000114E4(Register word32 ra)
void fn000114E4(word32 ra)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	fn0001147C(&globals->dw12008, &globals->dw1200C, ra, stackArg0, stackArg4);
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	word32 stackArg4 = <invalid>;
	fn0001147C(&globals->dw12000, &globals->dw12004, ra, stackArg0, stackArg4);
}

// 0001152C: Register (ptr32 code) fn0001152C(Register (ptr32 code) r2, Register word32 r4, Register word32 r5, Register word32 ra, Stack word32 dwArg00)
<anonymous> * fn0001152C(<anonymous> * r2, word32 r4, word32 r5, word32 ra, word32 dwArg00)
{
	Eq_196 r8_10 = globals->t13040;
	Eq_196 r8_13 = globals->t1303C;
	struct Eq_324 * sp_107 = fp + -0x0038;
	Eq_12 dwLoc20_117 = 0x00;
	Eq_330 r8_19 = r8_13 - r8_10;
	if (r8_19 < 0x00)
		return sp_107->ptr002C;
	if (r8_10 != 0x00)
	{
		Eq_12 r2_31;
		msize();
		dwLoc20_117 = r2_31;
	}
	if ((word32) (dwLoc20_117 < (word32) r8_19 + 0x04) != 0x00)
	{
		if (r8_10 == 0x00)
		{
			malloc(0x0010);
			sp_107 = fp + ~0x3B;
		}
		else
		{
			Eq_12 dwLoc18_125 = dwLoc20_117 << 0x01;
			if ((word32) (dwLoc20_117 < 0x0201) == 0x00)
				dwLoc18_125 = (word32) dwLoc20_117 + 0x0200;
			if ((word32) (dwLoc20_117 < dwLoc18_125) != 0x00)
			{
				realloc(r8_10, dwLoc18_125);
				sp_107 = fp + ~0x3B;
			}
			if (sp_107->t0014 == 0x00 && (word32) (sp_107->t0018 < sp_107->t0024) != 0x00)
			{
				sp_107 = (struct Eq_324 *) ((char *) sp_107 - 0x04);
				sp_107->t0014 = realloc(sp_107->t001C, sp_107->t0024);
			}
		}
		if (sp_107->t0014 == 0x00)
		{
			sp_107->ptr002C = null;
			return sp_107->ptr002C;
		}
		sp_107->t0028 = (word32) sp_107->t0014 + ((sp_107->t0028 - sp_107->t001C >> 0x02) << 0x02);
		sp_107->t001C = sp_107->t0014;
	}
	*sp_107->t0028 = sp_107->ptr0038;
	sp_107->t0028 = (word32) sp_107->t0028 + 0x04;
	globals->t1303C = sp_107->t0028;
	globals->t13040 = sp_107->t001C;
	sp_107->ptr002C = sp_107->ptr0038;
	return sp_107->ptr002C;
}

// 000116FC: void fn000116FC(Register (ptr32 code) r2, Register word32 r4, Register word32 r5, Register word32 ra, Stack word32 dwArg00)
void fn000116FC(<anonymous> * r2, word32 r4, word32 r5, word32 ra, word32 dwArg00)
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	word32 stackArg0 = <invalid>;
	struct Eq_478 * sp_17;
	if (fn0001152C(r2, r4, r5, ra, stackArg0) != 0x00)
		sp_17->dw0014 = 0x00;
	else
		sp_17->dw0014 = -0x01;
	sp_17->dw0010 = sp_17->dw0014;
}

