// a.c
// Generated by decompiling a.out
// using Reko decompiler version 0.8.0.2.

#include "a.h"

struct Eq_4252 g_tFFFFFFFF;
byte g_a0200[] = 
	{
	};
union Eq_745 g_u0202 = 
	{
		0x0000
	};
ptr16 g_ptr0204 = 0x0000;
ptr16 g_ptr0206 = 0x0000;
union Eq_742 g_u0208 = 
	{
		0x0000
	};
union Eq_831 g_u020A = 
	{
		0x0000
	};
union Eq_831 g_u020C = 
	{
		0x0000
	};
ptr16 g_ptr020E = 0x0000;
ptr16 g_ptr0210 = 0x0000;
ptr16 g_ptr0212 = 0x0000;
ptr16 g_ptr0214 = 0x0000;
union Eq_3395 g_u0216 = 
	{
		0x0000
	};
ptr16 g_ptr0218 = 0x000A;
ptr16 g_ptr021A = 0x0000;
byte g_a021C[] = 
	{
	};
union Eq_405 g_u021E = 
	{
		0x0000
	};
ptr16 g_ptr0220 = 0x0000;
Eq_4853 g_a0222[] = 
	{
	};
Eq_4855 g_a0226[] = 
	{
	};
ptr16 g_ptr0282 = 0x0000;
ptr16 g_ptr0284 = 0x0000;
struct Eq_1303 * g_ptr028A = null;
struct Eq_1839 * g_ptr029A = null;
union Eq_3689 g_u09B2 = 
	{
		0x0000
	};
byte g_a5B78[];

