// fn10000000
// Mem0:Global memory
// fp:Temporary
// esi:Register esi
// dwLoc08:Local -0008
// dwArg00:Stack +0000
// edi:Register edi
// dwLoc0C:Local -000C
// dwLoc10:Local -0010
// eax:Register eax
// return address size: 4
void fn10000000()
fn10000000_entry:		// pred:
	// succ:  l10000000
l10000000:		// pred: fn10000000_entry
	dwLoc08 = esi
	esi = dwArg00
	dwLoc0C = edi
	edi = GlobalHandle
	dwLoc10 = esi
	eax = GlobalHandle(dwLoc10)
	dwLoc10 = eax
	eax = GlobalUnlock(dwLoc10)
	dwLoc10 = esi
	eax = GlobalHandle(dwLoc10)
	dwLoc10 = eax
	eax = GlobalFree(dwLoc10)
	edi = dwLoc0C
	esi = dwLoc08
	return
	// succ:  fn10000000_exit
fn10000000_exit:		// pred: l10000000
	// succ: 

