// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// C:Flags
// ebx:Register ebx
// SCZO:Flags
// Z:Flags
// ds:Register ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	ax = ax & 0x000F
	C = false
	ebx = ebx & ebx
	SCZO = cond(ebx)
	C = false
	branch Test(EQ,Z) l0C00_000C
	// succ:  l0C00_0008 l0C00_000C
l0C00_0008:		// pred: l0C00_0000
	store(Mem0[ds:0x0300:word16]) = ax
	// succ:  l0C00_000C
l0C00_000C:		// pred: l0C00_0000 l0C00_0008
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_000C
	// succ: 

