// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ds:Register ds
// al:Register al
// ax:Register ax
// dx:Register dx
// dx_ax:Sequence dx:ax
// cx:Register cx
// cl:Register cl
// SCZO:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	al = Mem0[ds:0x0300:byte]
	ax = Mem0[ds:0x0301:byte] *u al
	store(Mem0[ds:0x0302:word16]) = ax
	ax = Mem0[ds:0x0304:word16]
	dx_ax = Mem0[ds:0x0306:word16] *u ax
	store(Mem0[ds:0x0308:word16]) = ax
	store(Mem0[ds:0x030A:word16]) = dx
	cx = Mem0[ds:0x030C:word16]
	ax = Mem0[ds:0x030E:word16]
	dx_ax = cx *s ax
	store(Mem0[ds:0x0310:word16]) = ax
	store(Mem0[ds:0x0312:word16]) = dx
	al = Mem0[ds:0x0300:byte]
	cl = Mem0[ds:0x0301:byte]
	ax = cl *u al
	store(Mem0[ds:0x0302:word16]) = ax
	ax = Mem0[ds:0x0304:word16] *s 0x0024
	dx = ax *s 0x0024
	ax = Mem0[ds:0x0304:word16] *s 0x0114
	dx = ax *s 0x0114
	ax = Mem0[ds:0x0304:word16] *s 0x0114
	SCZO = cond(ax)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
