// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// bx:Register bx
// ds:Register ds
// cl:Register cl
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	call fn0C00_000C (depth: 2;)
	store(Mem0[ds:0x0300:word16]) = bx
	store(Mem0[ds:0x0302:byte]) = cl
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

// fn0C00_000C
// Mem0:Global memory
// fp:Temporary
// ds:Register ds
// cx:Register cx
// es:Register es
// di:Register di
// al:Register al
// SCZO:Flags
// v8:Temporary
// Z:Flags
// bx:Register bx
// cl:Register cl
// ah:Register ah
// ax:Register ax
// return address size: 2
void fn0C00_000C()
fn0C00_000C_entry:		// pred:
	// succ:  l0C00_000C
l0C00_000C:		// pred: fn0C00_000C_entry
	cx = ds
	es = cx
	di = 0x7E0F
	cx = 0x000C
	al = 0x00
	SCZO = cond(al)
	// succ:  l0C00_0019
l0C00_0019:		// pred: l0C00_000C l0C00_0019_rep
	branch cx == 0x0000 l0C00_0019_rep
	// succ:  l0C00_001B l0C00_0019_rep
l0C00_001B:		// pred: l0C00_0019 l0C00_0019_rep
	branch Test(EQ,Z) l0C00_002D
	// succ:  l0C00_001D l0C00_002D
l0C00_001D:		// pred: l0C00_001B
	ah = Mem0[ds:di + 0x0001:byte]
	Z = ax == 0x0000
	cx = __bsr(ax)
	cx = cx - 0x0008
	bx = di
	bx = bx - 0x7E03
	SCZO = cond(bx)
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:		// pred: l0C00_002D l0C00_001D
	// succ: 
l0C00_002D:		// pred: l0C00_001B
	bx = 0x0000
	cl = 0x00
	SCZO = cond(cl)
	return
	// succ:  fn0C00_000C_exit
l0C00_0019_rep:		// pred: l0C00_0019
	cx = cx - 0x0001
	SCZO = cond(al - Mem0[es:di:byte])
	di = di + 0x0001
	branch Test(EQ,Z) l0C00_0019
	// succ:  l0C00_001B l0C00_0019

