// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ecx:Register ecx
// bx:Register bx
// ax:Register ax
// SCZO:Flags
// Z:Flags
// cl:Register cl
// ds:Register ds
// SO:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	ecx = 0x00000000
	ax = ax - bx
	SCZO = cond(ax)
	cl = Test(EQ,Z)
	store(Mem0[ds:0x0300:word32]) = ecx
	SCZO = cond(ax - 0x0030)
	branch Test(LT,SO) l0C00_0016
	// succ:  l0C00_0012 l0C00_0016
l0C00_0012:		// pred: l0C00_0000
	store(Mem0[ds:0x0302:word16]) = ax
	// succ:  l0C00_0016
l0C00_0016:		// pred: l0C00_0000 l0C00_0012
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0016
	// succ: 
