// Equivalence classes ////////////
Eq_1: (ptr (struct (10000000 T_2 t10000000)))
	Globals (in globals : ptr0)
Eq_2: (ptr (fn void ()))
	T_2 (in 0x01213130 : word32)
	T_4 (in Mem4[0x10000000:word32] : word32)
	T_6 (in Mem4[0x10000000:word32] : word32)
Eq_3: (ptr (struct (0 T_4 t0000)))
	T_3 (in 0x10000000 : word32)
Eq_5: (ptr (struct (0 T_6 t0000)))
	T_5 (in 0x10000000 : word32)
// Type Variables ////////////
Globals:(in globals)
  Class: Eq_1
  DataType: (ptr (struct (10000000 T_2 t10000000)))
  OrigDataType: (ptr (struct (10000000 T_2 t10000000)))
T_2:(in 0x01213130)
  Class: Eq_2
  DataType: (ptr (fn void ()))
  OrigDataType: word32
T_3:(in 0x10000000)
  Class: Eq_3
  DataType: (ptr (struct (0 T_4 t0000)))
  OrigDataType: (ptr (struct (0 T_4 t0000)))
T_4:(in Mem4[0x10000000:word32])
  Class: Eq_2
  DataType: (ptr (fn void ()))
  OrigDataType: word32
T_5:(in 0x10000000)
  Class: Eq_5
  DataType: (ptr (struct (0 T_6 t0000)))
  OrigDataType: (ptr (struct (0 T_6 t0000)))
T_6:(in Mem4[0x10000000:word32])
  Class: Eq_2
  DataType: (ptr (fn void ()))
  OrigDataType: (ptr (fn void ()))
