// SegmentedMemoryPointerMock
void SegmentedMemoryPointerMock()
SegmentedMemoryPointerMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	si = 0x0001
	ax = Mem0[cs:si:word16]
	// succ: 

T_2 (in 0x0001)
	trait_primitive(word16)
T_3 (in si)
	trait_primitive(word16)
	trait_equal(T_2)
	trait_primitive(word16)
	trait_mem(T_4:T_5, 0)
T_4 (in cs)
	trait_primitive(word16)
T_5 (in Mem0[cs:si:word16])
	trait_primitive(word16)
T_6 (in ax)
	trait_primitive(word16)
	trait_equal(T_5)
