void fn0C00_0000(Register word16 ax, Register word16 bx, Register selector ds)
// MayUse:  ax bx ds
// LiveOut:
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// bx:Register bx
// SCZO:Flags
// Z:Flags
// ds:Register ds
// return address size: 2
void fn0C00_0000(word16 ax, word16 bx, selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	SCZO = cond(ax - bx)
	branch Test(EQ,Z) l0C00_000A
	// succ:  3 2
l0C00_000A:		// block 2, pred: 1
	ax = 0x0001
	// succ:  4
l0C00_0004:		// block 3, pred: 1
	ax = 0x0000
	// succ:  4
l0C00_000D:		// block 4, pred: 2 3
	store(Mem0[ds:0x0064:word16]) = ax
	return
	// succ:  5
fn0C00_0000_exit:		// block 5, pred: 4
	// succ: 
