// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax cx dx al cl dl ah ch dh
// Preserved:
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	store(Mem9[ds:0x0064:word16]) = fn0C00_000F(0x0064)
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// Register word16 fn0C00_000F(Stack word16 wArg00)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse: 
// LiveOut: ax
// Trashed: SCZO ax dx al dl ah dh
// Preserved: bp
// Stack args: Stack +0000(16)
// fn0C00_000F
word16 fn0C00_000F(word16 wArg00)
fn0C00_000F_entry:		// block 0, pred:
	// succ:  1
l0C00_000F:		// block 1, pred: 0
	word16 ax_18
	word16 ax_14 = wArg00 - 0x0001
	branch ax_14 == 0x0000 l0C00_0026
	// succ:  3 2
l0C00_0026:		// block 2, pred: 1
	ax_18 = 0x0001
	// succ:  4
l0C00_0018:		// block 3, pred: 1
	ax_18 = (word16) (wArg00 *s fn0C00_000F(ax_14)) (alias)
	// succ:  4
l0C00_0029:		// block 4, pred: 2 3
	return ax_18
	// succ:  5
fn0C00_000F_exit:		// block 5, pred: 4
	// succ: 

