Mem0:Global memory
    def:  def Mem0
fp:Temporary
    def:  def fp
r4:Register r4
    def:  def r4
r4_3: orig: r4
    def:  store(Mem4[0x00000400:word32]) = foo(&r4_3)
Mem4: orig: Mem0
    def:  store(Mem4[0x00000400:word32]) = foo(&r4_3)
// foo
void foo()
foo_entry:		// block 0, pred:
	def Mem0
	def fp
	def r4
	// succ:  1
l1:		// block 1, pred: 0
	store(Mem4[0x00000400:word32]) = foo(&r4_3)
	return
	// succ:  2
foo_exit:		// block 2, pred: 1
	// succ: 

