using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Decompiler.Arch.Arm
{
    public enum Opcode
    {
        illegal,
        adc,
        add,
        adds,
        add16,
        add8,
        addsubx,
        subaddx,
        and,

        b,
        beq,
        bic,
        bkpt,
        bl,
        blx,
        bx,
        bxj,
        clz,
        cmn,
        cmp,
        cpy,
        cps,
        eor,

        ldc,
        ldm,
        ldr,
        ldrb,
        ldrbt,
        ldrd,
        ldrex,
        ldrh,
        ldrsb,
        ldrsh,
        ldrt,
        mla,
        mov,
        mvn,
        mul,
        orr,
        pkhbt,
        pkhtb,
        rev,
        rev16,
        revsh,
        rfe,
        rsb,
        rsc,
        sbc,
        sel,
        smlad,
        smlald,
        smlalxy,
        smlawy,
        smlaxy,
        smlsd,
        smlsld,
        smmla,
        smmls,
        smmul,
        smuad,
        smull,
        smulwy,
        smulxy,
        smusd,
        smlal,

        stm,
        str,
        strb,
        strbt,
        strd,
        strex,
        strh,
        strt,
        sub,
        sub16,
        sub8,
        swi,
        swp,
        swpb,
        teq,
        tst,
        umaal,
        umull,
        umlal,



    }
}
