Mem0:Global memory
    def:  def Mem0
    uses: branch 0 <= Mem0[ds:si:real64] l0C00_0010
fp:fp
sp:sp
rLoc1:FPU stack
si:si
    def:  def si
    uses: branch 0 <= Mem0[ds:si:real64] l0C00_0010
ds:ds
    def:  def ds
    uses: Mem12[ds:di:word16] = 0x0001
          Mem13[ds:di:word16] = 0x0000
          branch 0 <= Mem0[ds:si:real64] l0C00_0010
FPUF:Flags
SCZO:Flags
di:di
    def:  def di
    uses: Mem12[ds:di:word16] = 0x0001
          Mem13[ds:di:word16] = 0x0000
rLoc1_9: orig: rLoc1
FPUF_10: orig: FPUF
SCZO_11: orig: SCZO
Mem12: orig: Mem0
    def:  Mem12[ds:di:word16] = 0x0001
Mem13: orig: Mem0
    def:  Mem13[ds:di:word16] = 0x0000
// fn0C00_0000
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def Mem0
	def si
	def ds
	def di
	// succ:  l0C00_0000
l0C00_0000:
	branch 0 <= Mem0[ds:si:real64] l0C00_0010
	// succ:  l0C00_000B l0C00_0010
l0C00_000B:
	Mem12[ds:di:word16] = 0x0001
	return
	// succ:  fn0C00_0000_exit
l0C00_0010:
	Mem13[ds:di:word16] = 0x0000
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

