void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// ax:Register ax
// al:Register al
// ds:Register ds
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	ax = 0x0003
	al = fn0C00_0015(ax)
	store(Mem0[ds:0x0300:byte]) = al
	ax = 0x0003
	al = fn0C00_0020(ax)
	store(Mem0[ds:0x0301:byte]) = al
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
Register byte fn0C00_0015(Register word16 ax)
// MayUse:  ax
// LiveOut: al
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0015
// Mem0:Global memory
// fp:Temporary
// SCZO:Flags
// ax:Register ax
// Z:Flags
// al:Register al
// SZO:Flags
// return address size: 2
byte fn0C00_0015(word16 ax)
fn0C00_0015_entry:		// pred:
	// succ:  l0C00_0015
l0C00_0015:		// pred: fn0C00_0015_entry
	SCZO = cond(ax - 0x0000)
	branch Test(EQ,Z) l0C00_001D
	// succ:  l0C00_0019 l0C00_001D
l0C00_0019:		// pred: l0C00_0015
	ax = ax - 0x0001
	SZO = cond(ax)
	al = fn0C00_0020(ax)
	return al
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:		// pred: l0C00_001D l0C00_0019
	// succ: 
l0C00_001D:		// pred: l0C00_0015
	al = 0x01
	return al
	// succ:  fn0C00_0015_exit
Register byte fn0C00_0020(Register word16 ax)
// MayUse:  ax
// LiveOut: al
// Trashed: SCZO ax al ah
// Preserved:
// fn0C00_0020
// Mem0:Global memory
// fp:Temporary
// SCZO:Flags
// ax:Register ax
// Z:Flags
// al:Register al
// SZO:Flags
// return address size: 2
byte fn0C00_0020(word16 ax)
fn0C00_0020_entry:		// pred:
	// succ:  l0C00_0020
l0C00_0020:		// pred: fn0C00_0020_entry
	SCZO = cond(ax - 0x0000)
	branch Test(EQ,Z) l0C00_0028
	// succ:  l0C00_0024 l0C00_0028
l0C00_0024:		// pred: l0C00_0020
	ax = ax - 0x0001
	SZO = cond(ax)
	al = fn0C00_0015(ax)
	return al
	// succ:  fn0C00_0020_exit
fn0C00_0020_exit:		// pred: l0C00_0028 l0C00_0024
	// succ: 
l0C00_0028:		// pred: l0C00_0020
	al = 0x00
	SCZO = cond(al)
	return al
	// succ:  fn0C00_0020_exit
