// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: ax al ah
// Preserved:
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	word16 ax_4 = Mem0[ds:0x0100:word16]
	fn0C00_000C(ds)
	store(Mem5[ds:0x0102:word16]) = ax_4
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

// void fn0C00_000C(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: ax al
// Preserved: ax
// fn0C00_000C
void fn0C00_000C(selector ds)
fn0C00_000C_entry:		// pred:
	// succ:  l0C00_000C
l0C00_000C:		// pred: fn0C00_000C_entry
	store(Mem8[ds:0x0105:byte]) = Mem0[ds:0x0104:byte]
	return
	// succ:  fn0C00_000C_exit
fn0C00_000C_exit:		// pred: l0C00_000C
	// succ: 

