// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	def Mem0
	def fp
	def ds
	def si
	def ax
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	si_5 = Mem0[ds:0x0200:word16]
	ax_7 = fn0C00_0025(si_5, ds, &si_6)
	store(Mem8[ds:0x0310:word16]) = ax_7
	ax_10 = fn0C00_0027(si_6, ds, &si_9)
	store(Mem11[ds:0x0320:word16]) = ax_10
	ax_13 = fn0C00_002F(si_9, ds, &si_12)
	store(Mem14[ds:0x0330:word16]) = ax_13
	ax_16 = fn0C00_0036(si_12, ds, &si_15)
	store(Mem17[ds:0x0340:word16]) = ax_16
	store(Mem18[ds:0x0400:word16]) = si_15
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	def Mem0
	def ds
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	si_5 = Mem0[ds:0x0200:word16]
	ax_7 = fn0C00_0025(si_5, ds, &si_6)
	store(Mem8[ds:0x0310:word16]) = ax_7
	ax_10 = fn0C00_0027(si_6, ds, &si_9)
	store(Mem11[ds:0x0320:word16]) = ax_10
	ax_13 = fn0C00_002F(si_9, ds, &si_12)
	store(Mem14[ds:0x0330:word16]) = ax_13
	ax_16 = fn0C00_0036(si_12, ds, &si_15)
	store(Mem17[ds:0x0340:word16]) = ax_16
	store(Mem18[ds:0x0400:word16]) = si_15
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
====================
// fn0C00_0025
word16 fn0C00_0025(word16 si, selector ds, ptr16 siOut)
fn0C00_0025_entry:		// pred:
	def Mem0
	def fp
	def ax
	def ds
	def si
	def siOut
	// succ:  l0C00_0025
l0C00_0025:		// pred: fn0C00_0025_entry
	ax_6 = Mem0[ds:si:word16]
	si_7 = si + 0x0002
	return ax_6
	// succ:  fn0C00_0025_exit
fn0C00_0025_exit:		// pred: l0C00_0025
	use si_7 (=> siOut)
	// succ: 

// fn0C00_0025
word16 fn0C00_0025(word16 si, selector ds, ptr16 siOut)
fn0C00_0025_entry:		// pred:
	def Mem0
	def ds
	def si
	def siOut
	// succ:  l0C00_0025
l0C00_0025:		// pred: fn0C00_0025_entry
	ax_6 = Mem0[ds:si:word16]
	store(Mem0[siOut:word16]) = si + 0x0002
	return ax_6
	// succ:  fn0C00_0025_exit
fn0C00_0025_exit:		// pred: l0C00_0025
	// succ: 
====================
// fn0C00_0027
word16 fn0C00_0027(word16 si, selector ds, ptr16 siOut)
fn0C00_0027_entry:		// pred:
	def Mem0
	def fp
	def ax
	def SCZO
	def si
	def Z
	def ds
	def siOut
	// succ:  l0C00_0027
l0C00_0027:		// pred: fn0C00_0027_entry
	ax_8 = 0x0000
	SCZO_9 = cond(si - 0x0000)
	Z_10 = SCZO_9 (alias)
	branch Test(EQ,Z_10) l0C00_002E
	// succ:  l0C00_002D l0C00_002E
l0C00_002D:		// pred: l0C00_0027
	ax_11 = Mem0[ds:si:word16]
	si_12 = si + 0x0002
	// succ:  l0C00_002E
l0C00_002E:		// pred: l0C00_0027 l0C00_002D
	si_13 = PHI(si, si_12)
	ax_14 = PHI(ax_8, ax_11)
	return ax_14
	// succ:  fn0C00_0027_exit
fn0C00_0027_exit:		// pred: l0C00_002E
	use si_13 (=> siOut)
	// succ: 

// fn0C00_0027
word16 fn0C00_0027(word16 si, selector ds, ptr16 siOut)
fn0C00_0027_entry:		// pred:
	def Mem0
	def si
	store(Mem0[siOut:word16]) = si
	def ds
	def siOut
	// succ:  l0C00_0027
l0C00_0027:		// pred: fn0C00_0027_entry
	ax_8 = 0x0000
	SCZO_9 = cond(si - 0x0000)
	Z_10 = SCZO_9 (alias)
	branch Test(EQ,Z_10) l0C00_002E
	// succ:  l0C00_002D l0C00_002E
l0C00_002D:		// pred: l0C00_0027
	ax_11 = Mem0[ds:si:word16]
	store(Mem0[siOut:word16]) = si + 0x0002
	// succ:  l0C00_002E
l0C00_002E:		// pred: l0C00_0027 l0C00_002D
	ax_14 = PHI(ax_8, ax_11)
	return ax_14
	// succ:  fn0C00_0027_exit
fn0C00_0027_exit:		// pred: l0C00_002E
	// succ: 
====================
// fn0C00_002F
word16 fn0C00_002F(word16 si, selector ds, ptr16 siOut)
fn0C00_002F_entry:		// pred:
	def Mem0
	def fp
	def ax
	def ds
	def si
	def siOut
	// succ:  l0C00_002F
l0C00_002F:		// pred: fn0C00_002F_entry
	ax_6 = Mem0[ds:si:word16]
	si_7 = si + 0x0002
	store(Mem8[ds:si_7 + 0x0002:word16]) = 0x0000
	return ax_6
	// succ:  fn0C00_002F_exit
fn0C00_002F_exit:		// pred: l0C00_002F
	use si_7 (=> siOut)
	// succ: 

// fn0C00_002F
word16 fn0C00_002F(word16 si, selector ds, ptr16 siOut)
fn0C00_002F_entry:		// pred:
	def Mem0
	def ds
	def si
	def siOut
	// succ:  l0C00_002F
l0C00_002F:		// pred: fn0C00_002F_entry
	ax_6 = Mem0[ds:si:word16]
	si_7 = si + 0x0002
	store(Mem0[siOut:word16]) = si_7
	store(Mem8[ds:si_7 + 0x0002:word16]) = 0x0000
	return ax_6
	// succ:  fn0C00_002F_exit
fn0C00_002F_exit:		// pred: l0C00_002F
	// succ: 
====================
// fn0C00_0036
word16 fn0C00_0036(word16 si, selector ds, ptr16 siOut)
fn0C00_0036_entry:		// pred:
	def Mem0
	def fp
	def ax
	def ds
	def si
	def siOut
	// succ:  l0C00_0036
l0C00_0036:		// pred: fn0C00_0036_entry
	ax_6 = Mem0[ds:si:word16]
	si_7 = si + 0x0002
	ax_9 = fn0C00_0025(si_7, ds, &si_8)
	return ax_9
	// succ:  fn0C00_0036_exit
fn0C00_0036_exit:		// pred: l0C00_0036
	use si_8 (=> siOut)
	// succ: 

// fn0C00_0036
word16 fn0C00_0036(word16 si, selector ds, ptr16 siOut)
fn0C00_0036_entry:		// pred:
	def ds
	def si
	def siOut
	// succ:  l0C00_0036
l0C00_0036:		// pred: fn0C00_0036_entry
	si_7 = si + 0x0002
	ax_9 = fn0C00_0025(si_7, ds, siOut)
	return ax_9
	// succ:  fn0C00_0036_exit
fn0C00_0036_exit:		// pred: l0C00_0036
	// succ: 
====================
