#region License
/* 
 * Copyright (C) 1999-2017 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

namespace Reko.Arch.Alpha
{
    public enum Opcode
    {
        invalid,

        addl,
        addl_v,
        addq,
        addq_v,
        and,
        beq,
        bge,
        bgt,
        bic,
        bis,
        blbc,
        blbs,
        ble,
        blt,
        bne,
        br,
        bsr,
        cmovge,
        cmovgt,
        cmovlbc,
        cmovlbs,
        cmovlt,
        cmovne,
        cmpbge,
        cmpeq,
        cmple,
        cmplt,
        cmpule,
        cmpult,
        extbl,
        extlh,
        extll,
        extqh,
        extql,
        extwh,
        extwl,
        fbeq,
        fbge,
        fbgt,
        fble,
        fblt,
        fbne,
        halt,
        implver,
        insbl,
        inslh,
        insll,
        insqh,
        insql,
        inswh,
        inswl,
        jmp,
        jsr,
        jsr_coroutine,
        lda,
        ldah,
        ldbu,
        ldf,
        ldg,
        ldl,
        ldl_l,
        ldq,
        ldq_l,
        ldq_u,
        lds,
        ldt,
        ldwu,
        mskbl,
        msklh,
        mskll,
        mskqh,
        mskql,
        mskwh,
        mskwl,
        mull,
        mull_v,
        mulq,
        mulq_v,
        ornot,
        ret,
        s4addl,
        s4addq,
        s4subl,
        s4subq,
        s8addl,
        s8addq,
        s8subl,
        s8subq,
        sll,
        src,
        srl,
        stb,
        stf,
        stg,
        stl,
        stl_c,
        stq,
        stq_c,
        stq_u,
        sts,
        stt,
        stw,
        subl,
        subl_v,
        subq,
        subq_v,
        umulh,
        xor,
        zap,
        zapnot,
    }
}