// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// ds:Register ds
// ax:Register ax
// dx:Register dx
// cx:Register cx
// bx:Register bx
// SCZO:Flags
// v9:Temporary
// C:Flags
// es:Register es
// es_cx:Sequence es:cx
// v13:Temporary
// SZO:Flags
// cl:Register cl
// v16:Temporary
// v17:Temporary
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	ax = Mem0[ds:0x0200:word16]
	dx = Mem0[ds:0x0202:word16]
	cx = Mem0[ds:0x0204:word16]
	bx = Mem0[ds:0x0206:word16]
	ax = ax + cx
	SCZO = cond(ax)
	v9 = dx + bx
	dx = v9 + (word16) C
	SCZO = cond(dx)
	store(Mem0[ds:0x0208:word16]) = ax
	store(Mem0[ds:0x020A:word16]) = dx
	ax = Mem0[ds:0x0210:word16]
	dx = Mem0[ds:0x0212:word16]
	es_cx = Mem0[ds:0x0214:ptr32]
	bx = es
	ax = ax - cx
	SCZO = cond(ax)
	store(Mem0[ds:0x0218:word16]) = ax
	v13 = dx - bx
	dx = v13 - (word16) C
	SCZO = cond(dx)
	store(Mem0[ds:0x021A:word16]) = dx
	ax = ax ^ ax
	SZO = cond(ax)
	C = false
	cl = Mem0[ds:0x0220:byte]
	SCZO = cond(cl - 0x30)
	v16 = ax + ax
	ax = v16 + (word16) C
	SCZO = cond(ax)
	cl = Mem0[ds:0x0221:byte]
	SCZO = cond(cl - 0x3A)
	C = !C
	v17 = ax + ax
	ax = v17 + (word16) C
	SCZO = cond(ax)
	store(Mem0[ds:0x0222:word16]) = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

