// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// bp:Register bp
// ss:Register ss
// bx:Register bx
// ds:Register ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = bp
	bp = sp
	bx = Mem0[ss:bp + 0x0004:word16]
	store(Mem0[ds:bx:byte]) = 0x00
	sp = bp
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
fn0C00_0000_exit:

