// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// ss:Register ss
// SCZO:Flags
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0D00
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0300
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0001
	sp = sp - 0x0002
	call fn0C00_0020 (retsize: 2;)
	sp = sp + 0x0006
	SCZO = cond(sp)
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0D00
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0304
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = 0x0002
	call fn0C00_002E (retsize: 4;)
	sp = sp + 0x0006
	SCZO = cond(sp)
	return
fn0C00_0000_exit:

// fn0C00_0020
// Mem0:Global memory
// fp:Temporary
// bp:Register bp
// sp:Register sp
// ss:Register ss
// es:Register es
// bx:Register bx
// es_bx:Sequence es:bx
// ax:Register ax
// v9:Temporary
// SCZO:Flags
// return address size: 4
void fn0C00_0020()
fn0C00_0020_entry:
l0C00_0020:
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = bp
	bp = sp
	es_bx = Mem0[ss:bp + 0x0006:ptr32]
	ax = Mem0[ss:bp + 0x000A:word16]
	v9 = Mem0[es:bx:word16] + ax
	store(Mem0[es:bx:word16]) = v9
	SCZO = cond(v9)
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
fn0C00_0020_exit:

// fn0C00_002E
// Mem0:Global memory
// fp:Temporary
// bp:Register bp
// sp:Register sp
// ss:Register ss
// es:Register es
// bx:Register bx
// es_bx:Sequence es:bx
// ax:Register ax
// v9:Temporary
// SCZO:Flags
// return address size: 4
void fn0C00_002E()
fn0C00_002E_entry:
l0C00_002E:
	sp = sp - 0x0002
	store(Mem0[ss:sp:word16]) = bp
	bp = sp
	es_bx = Mem0[ss:bp + 0x0006:ptr32]
	ax = Mem0[ss:bp + 0x000A:word16]
	v9 = Mem0[es:bx:word16] - ax
	store(Mem0[es:bx:word16]) = v9
	SCZO = cond(v9)
	bp = Mem0[ss:sp:word16]
	sp = sp + 0x0002
	return
fn0C00_002E_exit:

