// fn10000000
// Mem0:Global memory
// fp:Temporary
// edi:Register edi
// esi:Register esi
// ebx:Register ebx
// SZO:Flags
// C:Flags
// Z:Flags
// esp:Register esp
// eax:Register eax
// dwLoc08:Local -0008
// SCZO:Flags
// return address size: 4
void fn10000000()
fn10000000_entry:
l10000000:
	edi = Mem0[0x1000002C:word32]
	esi = 0x00000003
	ebx = GetDC
	goto l10000027
l10000016:
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = Mem0[edi:word32]
	eax = GetDC(Mem0[esp:word32])
	store(Mem0[edi:word32]) = eax
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = 0x00000000
	eax = GetDC(Mem0[esp:word32])
	store(Mem0[edi + 0x00000004:word32]) = eax
	esi = esi - 0x00000001
	SZO = cond(esi)
	edi = edi + 0x00000008
	SCZO = cond(edi)
l10000027:
	esi = esi | esi
	SZO = cond(esi)
	C = false
	branch Test(NE,Z) l10000016
l1000002B:
	return
fn10000000_exit:
