// fn10000000
// Mem0:Global memory
// fp:Temporary
// eax:Register eax
// al:Register al
// v4:Temporary
// SCZO:Flags
// v6:Temporary
// v7:Temporary
// v8:Temporary
// dwLoc08:Local -0008
// return address size: 4
void fn10000000()
fn10000000_entry:
l10000000:
	v4 = Mem0[eax:byte] + al
	store(Mem0[eax:byte]) = v4
	v5 = Mem0[eax:byte] + al
	store(Mem0[eax:byte]) = v5
	v6 = Mem0[eax:byte] + al
	store(Mem0[eax:byte]) = v6
	v7 = Mem0[eax:byte] + al
	store(Mem0[eax:byte]) = v7
	dwLoc08 = 0x00000008
	eax = malloc(dwLoc08)
	store(Mem0[eax:word32]) = 0x00000000
	store(Mem0[eax + 0x00000004:word32]) = 0x00001024
	dwLoc08 = eax
	free(dwLoc08)
	return
fn10000000_exit:

