// fn10000008
// Mem0:Global memory
// fp:Temporary
// esp:Register esp
// eax:Register eax
// SCZO:Flags
// return address size: 4
void fn10000008()
fn10000008_entry:
l10000008:
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = 0x00000008
	eax = malloc(Mem0[esp:word32])
	esp = esp + 0x00000004
	SCZO = cond(esp)
	store(Mem0[eax:word32]) = 0x00000000
	store(Mem0[eax + 0x00000004:word32]) = 0x00001024
	esp = esp - 0x00000004
	store(Mem0[esp:word32]) = eax
	free(Mem0[esp:word32])
	esp = esp + 0x00000004
	SCZO = cond(esp)
	return
fn10000008_exit:

