// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:Register sp
// bp:Register bp
// ss:Register ss
// si:Register si
// dx:Register dx
// al:Register al
// v8:Temporary
// bx:Register bx
// C:Flags
// v11:Temporary
// cx:Register cx
// SZO:Flags
// es:Register es
// di:Register di
// ds:Register ds
// ax:Register ax
// Z:Flags
// eax:Register eax
// ecx:Register ecx
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
l0C00_0000:
	si = bp + 0x000C
	__outb(dx, al)
	v8 = (bx & 0x0001 << 0x01) != 0x0000
	bx = __ror(bx, 0x01)
	C = v8
	v11 = (cx & 0x0001 << 0x01) != 0x0000
	cx = __rcr(cx, 0x01, C)
	C = v11
	dx = dx + 0x0001
	SZO = cond(dx)
	al = __inb(dx)
	store(Mem0[es:di:byte]) = al
	di = di + 0x0001
	C = __bt(Mem0[ds:0x3000:word16], ax)
	C = __bt(cx, ax)
	C = __bt(cx, 0x02)
	Z = Mem0[ds:si:word16] == 0x0000
	cx = __bsr(Mem0[ds:si:word16])
	Z = eax == 0x00000000
	ecx = __bsr(eax)
	return
fn0C00_0000_exit:
