// fn10000000
// Mem0:Global memory
// fp:Temporary
// dwArg00:Stack +0000
// eax:Register eax
// SCZO:Flags
// CZ:Flags
// edx:Register edx
// dl:Register dl
// return address size: 4
void fn10000000()
fn10000000_entry:		// block 0, pred:
	// succ:  1
l10000000:		// block 1, pred: 0
	eax = dwArg00
	SCZO = cond(eax - 0x00000003)
	branch Test(UGT,CZ) l10000048
	// succ:  3 2
l10000048:		// block 2, pred: 1
	eax = 0xFFFFFFFF
	// succ:  7
l1000000B:		// block 3, pred: 1
	edx = 0x00000000
	SCZO = cond(edx)
	dl = Mem0[eax + 0x1000001A:byte]
	switch (eax) { 6 5 6 4 }
	// succ:  6 5 6 4
l1000003E:		// block 4, pred: 3
	eax = 0x00000002
	// succ:  7
l1000002A:		// block 5, pred: 3
	eax = 0x00000000
	// succ:  7
l10000034:		// block 6, pred: 3 3
	eax = 0x00000001
	// succ:  7
l1000004D:		// block 7, pred: 2 4 5 6
	store(Mem0[0x10000054:word32]) = eax
	return
	// succ:  8
fn10000000_exit:		// block 8, pred: 7
	// succ: 

