Mem0:Global memory
fp:Temporary
C:Flags
al:Register al
    def:  def al
    uses: branch fn0C00_000A(al, &al_5) l0C00_0009
ds:Register ds
    def:  def ds
    uses: Mem7[ds:0x0300:byte] = al_5
al_5: orig: al
    def:  branch fn0C00_000A(al, &al_5) l0C00_0009
    uses: Mem7[ds:0x0300:byte] = al_5
C_6: orig: C
    uses: branch fn0C00_000A(al, &al_5) l0C00_0009
Mem7: orig: Mem0
    def:  Mem7[ds:0x0300:byte] = al_5
Mem8: orig: Mem0
// fn0C00_0000
void fn0C00_0000(byte al, selector ds)
fn0C00_0000_entry:
	def al
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	branch fn0C00_000A(al, &al_5) l0C00_0009
	// succ:  l0C00_0005 l0C00_0009
l0C00_0005:
	Mem7[ds:0x0300:byte] = al_5
	// succ:  l0C00_0009
l0C00_0009:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
	// succ: 

Mem0:Global memory
fp:Temporary
al:Register al
    def:  def al
    uses: al_25 = al - 0x30
          al_47 = PHI(al, al_37)
          branch al <u 0x30 l0C00_0032
          branch al <=u 0x39 l0C00_0022
          branch al <u 0x41 l0C00_0032
          branch al <=u 0x46 l0C00_0022
          branch al <u 0x61 l0C00_0032
          branch al >u 0x66 l0C00_0032
          al_29 = al - 0x37
          al_33 = al - 0x57
SCZO:Flags
C:Flags
CZ:Flags
alOut:Out:Register al
SCZO_7: orig: SCZO
C_8: orig: C
CZ_9: orig: CZ
SCZO_10: orig: SCZO
C_11: orig: C
CZ_12: orig: CZ
SCZO_13: orig: SCZO
C_14: orig: C
CZ_15: orig: CZ
SCZO_16: orig: SCZO
C_17: orig: C
CZ_18: orig: CZ
SCZO_19: orig: SCZO
C_20: orig: C
CZ_21: orig: CZ
SCZO_22: orig: SCZO
C_23: orig: C
CZ_24: orig: CZ
al_25: orig: al
    def:  al_25 = al - 0x30
    uses: al_37 = PHI(al_25, al_29, al_33)
          branch al_25 <u 0x0A l0C00_0030
SCZO_26: orig: SCZO
C_27: orig: C
CZ_28: orig: CZ
al_29: orig: al
    def:  al_29 = al - 0x37
    uses: al_37 = PHI(al_25, al_29, al_33)
          branch al_29 <u 0x10 l0C00_0030
SCZO_30: orig: SCZO
C_31: orig: C
CZ_32: orig: CZ
al_33: orig: al
    def:  al_33 = al - 0x57
    uses: al_37 = PHI(al_25, al_29, al_33)
SCZO_34: orig: SCZO
C_35: orig: C
CZ_36: orig: CZ
al_37: orig: al
    def:  al_37 = PHI(al_25, al_29, al_33)
    uses: al_47 = PHI(al, al_37)
C_38: orig: C
SCZO_39: orig: SCZO
CZ_40: orig: CZ
C_41: orig: C
SCZO_42: orig: SCZO
CZ_43: orig: CZ
CZ_44: orig: CZ
C_45: orig: C
SCZO_46: orig: SCZO
al_47: orig: al
    def:  al_47 = PHI(al, al_37)
    uses: use al_47 (=> alOut)
// fn0C00_000A
byte fn0C00_000A(byte al, ptr16 alOut)
fn0C00_000A_entry:
	def al
	// succ:  l0C00_000A
l0C00_000A:
	branch al <u 0x30 l0C00_0032
	// succ:  l0C00_000E l0C00_0032
l0C00_000E:
	branch al <=u 0x39 l0C00_0022
	// succ:  l0C00_0012 l0C00_0022
l0C00_0012:
	branch al <u 0x41 l0C00_0032
	// succ:  l0C00_0016 l0C00_0032
l0C00_0016:
	branch al <=u 0x46 l0C00_0022
	// succ:  l0C00_001A l0C00_0022
l0C00_001A:
	branch al <u 0x61 l0C00_0032
	// succ:  l0C00_001E l0C00_0032
l0C00_001E:
	branch al >u 0x66 l0C00_0032
	// succ:  l0C00_0022 l0C00_0032
l0C00_0022:
	al_25 = al - 0x30
	branch al_25 <u 0x0A l0C00_0030
	// succ:  l0C00_0028 l0C00_0030
l0C00_0028:
	al_29 = al - 0x37
	branch al_29 <u 0x10 l0C00_0030
	// succ:  l0C00_002E l0C00_0030
l0C00_002E:
	al_33 = al - 0x57
	// succ:  l0C00_0030
l0C00_0030:
	al_37 = PHI(al_25, al_29, al_33)
	return false
	// succ:  fn0C00_000A_exit
fn0C00_000A_exit:
	al_47 = PHI(al, al_37)
	use al_47 (=> alOut)
	// succ: 
l0C00_0032:
	return true
	// succ:  fn0C00_000A_exit

