// void fn0C00_0000()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ax bx al bl ah bh es
// Preserved: sp
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	fn0C00_0004()
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

// void fn0C00_0004()
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1
// MayUse: 
// LiveOut:
// Trashed: SCZO ax bx al bl ah bh es
// Preserved: sp
// fn0C00_0004
void fn0C00_0004()
fn0C00_0004_entry:
	// succ:  l0C00_0004
l0C00_0004:
	word16 bx_16 = 0x0FFF
	byte bh_17 = 0x0F
	byte bl_18 = 0xFF
	// succ:  l0C00_000C
l0C00_000C:
	Mem37[0x4DE1:bx_50:byte] = bl_18 & 0xF0 | SLICE((bl_18 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F
	bx_16 = bx_50 - 0x0001
	bh_17 = SLICE(bx_16, byte, 8) (alias)
	bl_18 = (byte) bx_16 (alias)
	branch bx_50 >= 0x0000 l0C00_000C
	// succ:  l0C00_0029 l0C00_000C
l0C00_0029:
	return
	// succ:  fn0C00_0004_exit
fn0C00_0004_exit:

