// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	fn0C00_0004()
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 

// fn0C00_0004
void fn0C00_0004()
fn0C00_0004_entry:		// block 0, pred:
	// succ:  1
l0C00_0004:		// block 1, pred: 0
	int16 bx_15 = 0x0FFF
	byte bh_16 = 0x0F
	byte bl_17 = 0xFF
	// succ:  2
l0C00_000C:		// block 2, pred: 1 2
	0x4DE1->a0000[bx_15] = bl_17 & 0xF0 | SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F;
	bx_15 = bx_15 - 0x0001;
	bh_16 = SLICE(bx_15, byte, 8);
	bl_17 = (byte) bx_15;
	branch bx_15 >= 0x0000 l0C00_000C
	// succ:  3 2
l0C00_0029:		// block 3, pred: 2
	return
	// succ:  4
fn0C00_0004_exit:		// block 4, pred: 3
	// succ: 

// Equivalence classes ////////////
Eq_2: (fn void ())
	T_2 (in fn0C00_0004 : ptr32)
	T_3 (in signature of fn0C00_0004)
Eq_24: (segment "Eq_24" (0 (arr byte 4096) a0000))
	T_24 (in 0x4DE1 : selector)
// Type Variables ////////////
Globals: (in globals : ptr32)
  Class: Eq_1
  DataType: Eq_1
  OrigDataType: 
T_2: (in fn0C00_0004 : ptr32)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (fn T_4 ()))
T_3: (in signature of fn0C00_0004)
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: 
T_4: (in fn0C00_0004() : void)
  Class: Eq_4
  DataType: void
  OrigDataType: void
T_5: (in bx_15 : int16)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_6: (in 0x0FFF : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: word16
T_7: (in bh_16 : byte)
  Class: Eq_7
  DataType: byte
  OrigDataType: byte
T_8: (in 0x0F : byte)
  Class: Eq_7
  DataType: byte
  OrigDataType: byte
T_9: (in bl_17 : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_10: (in 0xFF : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_11: (in 0xF0 : byte)
  Class: Eq_11
  DataType: byte
  OrigDataType: byte
T_12: (in bl_17 & 0xF0 : byte)
  Class: Eq_12
  DataType: byte
  OrigDataType: byte
T_13: (in 0x0F : byte)
  Class: Eq_13
  DataType: byte
  OrigDataType: byte
T_14: (in bl_17 & 0x0F : byte)
  Class: Eq_14
  DataType: uint8
  OrigDataType: uint8
T_15: (in 0x01 : byte)
  Class: Eq_15
  DataType: byte
  OrigDataType: byte
T_16: (in bh_16 + 0x01 : byte)
  Class: Eq_16
  DataType: uint8
  OrigDataType: uint8
T_17: (in (bl_17 & 0x0F) *u (bh_16 + 0x01) : uint16)
  Class: Eq_17
  DataType: uint16
  OrigDataType: uint16
T_18: (in 0x0004 : word16)
  Class: Eq_18
  DataType: word16
  OrigDataType: word16
T_19: (in (bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004 : word16)
  Class: Eq_19
  DataType: word16
  OrigDataType: word16
T_20: (in SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_21: (in 0x0F : byte)
  Class: Eq_21
  DataType: byte
  OrigDataType: byte
T_22: (in SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
  Class: Eq_22
  DataType: byte
  OrigDataType: byte
T_23: (in bl_17 & 0xF0 | SLICE((bl_17 & 0x0F) *u (bh_16 + 0x01) << 0x0004, byte, 8) & 0x0F : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_24: (in 0x4DE1 : selector)
  Class: Eq_24
  DataType: (ptr Eq_24)
  OrigDataType: (ptr (segment (0 (arr (struct 1 (0 byte b0000)) 4096) a0000)))
T_25: (in 0x0000 : word16)
  Class: Eq_25
  DataType: (memptr (ptr Eq_24) byte)
  OrigDataType: (memptr T_24 (struct 1 (0 T_27 t0000)))
T_26: (in bx_15 + 0x0000 : word16)
  Class: Eq_26
  DataType: word16
  OrigDataType: word16
T_27: (in Mem37[0x4DE1:bx_15 + 0x0000:byte] : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_28: (in 0x0001 : word16)
  Class: Eq_28
  DataType: word16
  OrigDataType: word16
T_29: (in bx_15 - 0x0001 : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: word16
T_30: (in SLICE(bx_15, byte, 8) : byte)
  Class: Eq_7
  DataType: byte
  OrigDataType: byte
T_31: (in (byte) bx_15 : byte)
  Class: Eq_9
  DataType: byte
  OrigDataType: byte
T_32: (in 0x0000 : word16)
  Class: Eq_5
  DataType: int16
  OrigDataType: int16
T_33: (in bx_15 >= 0x0000 : bool)
  Class: Eq_33
  DataType: bool
  OrigDataType: bool
