// subject.h
// Generated by decompiling subject.exe
// using Reko decompiler version 0.11.4.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals"
		(FC0 Eq_12 t0FC0)
		(16B8 Eq_15 t16B8)
		(1738 Eq_16 t1738)
		(1FC20 (ptr64 void) ptr1FC20)
		(1FF98 (ptr64 Eq_16) ptr1FF98)
		(1FFA0 (ptr64 code) ptr1FFA0)
		(1FFD0 word64 qw1FFD0)
		(1FFD8 (ptr64 (ptr64 void)) ptr1FFD8)
		(1FFE0 (ptr64 Eq_15) ptr1FFE0)
		(1FFE8 (ptr64 Eq_12) ptr1FFE8))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_2: (fn void ())
	T_2 (in fn0000000000001498 @ 0000000000000D90 : ptr64)
	T_3 (in signature of fn0000000000001498 @ 0000000000001498 : void)
Eq_5: (fn void ())
	T_5 (in x0 @ 0000000000000D98 : (ptr64 Eq_5))
	T_17 (in rtld_fini @ 0000000000001490 : (ptr64 (fn void ())))
Eq_10: (fn int32 ((ptr64 Eq_12), int32, (ptr64 (ptr64 char)), (ptr64 Eq_15), (ptr64 Eq_16), (ptr64 Eq_5), (ptr64 void)))
	T_10 (in __libc_start_main @ 0000000000001490 : ptr64)
	T_11 (in signature of __libc_start_main : void)
Eq_12: (fn int32 (int32, (ptr64 (ptr64 char)), (ptr64 (ptr64 char))))
	T_12 (in main @ 0000000000001490 : (ptr64 (fn int32 (int32, (ptr64 (ptr64 char)), (ptr64 (ptr64 char))))))
	T_20 (in Mem0[0x000000000001FFE8<p64>:word64] @ 0000000000001490 : word64)
Eq_15: (fn void ())
	T_15 (in init @ 0000000000001490 : (ptr64 (fn void ())))
	T_24 (in Mem0[0x000000000001FFE0<p64>:word64] @ 0000000000001490 : word64)
Eq_16: (fn void ())
	T_16 (in fini @ 0000000000001490 : (ptr64 (fn void ())))
	T_26 (in Mem0[0x000000000001FF98<p64>:word64] @ 0000000000001490 : word64)
Eq_28: (fn void ())
	T_28 (in abort @ 0000000000001494 : ptr64)
	T_29 (in signature of abort : void)
Eq_35: (fn word64 ())
	T_35 (in __gmon_start__ @ 00000000000014A4 : ptr64)
Eq_45: (fn void ((ptr64 void)))
	T_45 (in x0 @ 00000000000014D4 : (ptr64 Eq_45))
	T_55 (in func @ 0000000000001758 : (ptr64 (fn void ((ptr64 void)))))
Eq_53: (fn int32 ((ptr64 Eq_45), (ptr64 void), (ptr64 void)))
	T_53 (in __cxa_atexit @ 0000000000001758 : ptr64)
	T_54 (in signature of __cxa_atexit : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in fn0000000000001498 @ 0000000000000D90 : ptr64)
  Class: Eq_2
  DataType: (ptr64 Eq_2)
  OrigDataType: (ptr64 (fn T_4 ()))
T_3: (in signature of fn0000000000001498 @ 0000000000001498 : void)
  Class: Eq_2
  DataType: (ptr64 Eq_2)
  OrigDataType: 
T_4: (in fn0000000000001498() @ 0000000000000D90 : void)
  Class: Eq_4
  DataType: void
  OrigDataType: void
T_5: (in x0 @ 0000000000000D98 : (ptr64 Eq_5))
  Class: Eq_5
  DataType: (ptr64 Eq_5)
  OrigDataType: (ptr64 (fn void ()))
T_6: (in dwArg00 @ 0000000000000D98 : word32)
  Class: Eq_6
  DataType: word32
  OrigDataType: word32
T_7: (in ptrArg08 @ 0000000000000D98 : (ptr64 char))
  Class: Eq_7
  DataType: (ptr64 char)
  OrigDataType: (ptr64 char)
T_8: (in fp @ 0000000000001460 : (ptr64 void))
  Class: Eq_8
  DataType: (ptr64 void)
  OrigDataType: (ptr64 void)
T_9: (in qwArg00 @ 0000000000001460 : word64)
  Class: Eq_9
  DataType: word64
  OrigDataType: word64
T_10: (in __libc_start_main @ 0000000000001490 : ptr64)
  Class: Eq_10
  DataType: (ptr64 Eq_10)
  OrigDataType: (ptr64 (fn T_27 (T_20, T_21, T_22, T_24, T_26, T_5, T_8)))
T_11: (in signature of __libc_start_main : void)
  Class: Eq_10
  DataType: (ptr64 Eq_10)
  OrigDataType: 
T_12: (in main @ 0000000000001490 : (ptr64 (fn int32 (int32, (ptr64 (ptr64 char)), (ptr64 (ptr64 char))))))
  Class: Eq_12
  DataType: (ptr64 Eq_12)
  OrigDataType: 
T_13: (in argc @ 0000000000001490 : int32)
  Class: Eq_13
  DataType: int32
  OrigDataType: 
T_14: (in ubp_av @ 0000000000001490 : (ptr64 (ptr64 char)))
  Class: Eq_14
  DataType: (ptr64 (ptr64 char))
  OrigDataType: 
T_15: (in init @ 0000000000001490 : (ptr64 (fn void ())))
  Class: Eq_15
  DataType: (ptr64 Eq_15)
  OrigDataType: 
T_16: (in fini @ 0000000000001490 : (ptr64 (fn void ())))
  Class: Eq_16
  DataType: (ptr64 Eq_16)
  OrigDataType: 
T_17: (in rtld_fini @ 0000000000001490 : (ptr64 (fn void ())))
  Class: Eq_5
  DataType: (ptr64 Eq_5)
  OrigDataType: 
T_18: (in stack_end @ 0000000000001490 : (ptr64 void))
  Class: Eq_8
  DataType: (ptr64 void)
  OrigDataType: 
T_19: (in 000000000001FFE8 @ 0000000000001490 : ptr64)
  Class: Eq_19
  DataType: (ptr64 (ptr64 Eq_12))
  OrigDataType: (ptr64 (struct (0 T_20 t0000)))
T_20: (in Mem0[0x000000000001FFE8<p64>:word64] @ 0000000000001490 : word64)
  Class: Eq_12
  DataType: (ptr64 Eq_12)
  OrigDataType: (ptr64 (fn int32 (int32, (ptr64 (ptr64 char)), (ptr64 (ptr64 char)))))
T_21: (in SLICE(qwArg00, int32, 0) @ 0000000000001490 : int32)
  Class: Eq_13
  DataType: int32
  OrigDataType: int32
T_22: (in &ptrArg08 @ 0000000000001490 : (ptr64 (ptr64 char)))
  Class: Eq_14
  DataType: (ptr64 (ptr64 char))
  OrigDataType: (ptr64 (ptr64 char))
T_23: (in 000000000001FFE0 @ 0000000000001490 : ptr64)
  Class: Eq_23
  DataType: (ptr64 (ptr64 Eq_15))
  OrigDataType: (ptr64 (struct (0 T_24 t0000)))
T_24: (in Mem0[0x000000000001FFE0<p64>:word64] @ 0000000000001490 : word64)
  Class: Eq_15
  DataType: (ptr64 Eq_15)
  OrigDataType: (ptr64 (fn void ()))
T_25: (in 000000000001FF98 @ 0000000000001490 : ptr64)
  Class: Eq_25
  DataType: (ptr64 (ptr64 Eq_16))
  OrigDataType: (ptr64 (struct (0 T_26 t0000)))
T_26: (in Mem0[0x000000000001FF98<p64>:word64] @ 0000000000001490 : word64)
  Class: Eq_16
  DataType: (ptr64 Eq_16)
  OrigDataType: (ptr64 (fn void ()))
T_27: (in __libc_start_main(g_ptr1FFE8, (int32) qwArg00, &ptrArg08, g_ptr1FFE0, g_ptr1FF98, x0, fp) @ 0000000000001490 : int32)
  Class: Eq_27
  DataType: int32
  OrigDataType: int32
T_28: (in abort @ 0000000000001494 : ptr64)
  Class: Eq_28
  DataType: (ptr64 Eq_28)
  OrigDataType: (ptr64 (fn T_30 ()))
T_29: (in signature of abort : void)
  Class: Eq_28
  DataType: (ptr64 Eq_28)
  OrigDataType: 
T_30: (in abort() @ 0000000000001494 : void)
  Class: Eq_30
  DataType: void
  OrigDataType: void
T_31: (in 000000000001FFD0 @ 00000000000014A0 : ptr64)
  Class: Eq_31
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_32 t0000)))
T_32: (in Mem0[0x000000000001FFD0<p64>:word64] @ 00000000000014A0 : word64)
  Class: Eq_32
  DataType: word64
  OrigDataType: word64
T_33: (in 0<64> @ 00000000000014A0 : word64)
  Class: Eq_32
  DataType: word64
  OrigDataType: word64
T_34: (in g_qw1FFD0 == 0<64> @ 00000000000014A0 : bool)
  Class: Eq_34
  DataType: bool
  OrigDataType: bool
T_35: (in __gmon_start__ @ 00000000000014A4 : ptr64)
  Class: Eq_35
  DataType: (ptr64 Eq_35)
  OrigDataType: (ptr64 (fn T_37 ()))
T_36: (in signature of __gmon_start__ : void)
  Class: Eq_36
  DataType: Eq_36
  OrigDataType: 
T_37: (in __gmon_start__() @ 00000000000014A4 : word64)
  Class: Eq_37
  DataType: word64
  OrigDataType: word64
T_38: (in 0000000000020008 @ 00000000000014C4 : ptr64)
  Class: Eq_38
  DataType: ptr64
  OrigDataType: ptr64
T_39: (in 0x20008<u64> == 0x20008<u64> @ 00000000000014C4 : bool)
  Class: Eq_39
  DataType: bool
  OrigDataType: bool
T_40: (in x1_12 @ 00000000000014CC : (ptr64 code))
  Class: Eq_40
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_41: (in 000000000001FFA0 @ 00000000000014CC : ptr64)
  Class: Eq_41
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_42 t0000)))
T_42: (in Mem0[0x000000000001FFA0<p64>:word64] @ 00000000000014CC : word64)
  Class: Eq_40
  DataType: (ptr64 code)
  OrigDataType: word64
T_43: (in 0<64> @ 00000000000014D0 : word64)
  Class: Eq_40
  DataType: (ptr64 code)
  OrigDataType: word64
T_44: (in x1_12 == null @ 00000000000014D0 : bool)
  Class: Eq_44
  DataType: bool
  OrigDataType: bool
T_45: (in x0 @ 00000000000014D4 : (ptr64 Eq_45))
  Class: Eq_45
  DataType: (ptr64 Eq_45)
  OrigDataType: (ptr64 (fn void ((ptr64 void))))
T_46: (in x2_11 @ 0000000000001744 : (ptr64 void))
  Class: Eq_46
  DataType: (ptr64 void)
  OrigDataType: (ptr64 void)
T_47: (in 0<64> @ 0000000000001744 : word64)
  Class: Eq_46
  DataType: (ptr64 void)
  OrigDataType: word64
T_48: (in x1_6 @ 0000000000001748 : (ptr64 (ptr64 void)))
  Class: Eq_48
  DataType: (ptr64 (ptr64 void))
  OrigDataType: (ptr64 (struct (0 T_62 t0000)))
T_49: (in 000000000001FFD8 @ 0000000000001748 : ptr64)
  Class: Eq_49
  DataType: (ptr64 (ptr64 (ptr64 void)))
  OrigDataType: (ptr64 (struct (0 T_50 t0000)))
T_50: (in Mem0[0x000000000001FFD8<p64>:word64] @ 0000000000001748 : word64)
  Class: Eq_48
  DataType: (ptr64 (ptr64 void))
  OrigDataType: word64
T_51: (in 0<64> @ 000000000000174C : word64)
  Class: Eq_48
  DataType: (ptr64 (ptr64 void))
  OrigDataType: word64
T_52: (in x1_6 == null @ 000000000000174C : bool)
  Class: Eq_52
  DataType: bool
  OrigDataType: bool
T_53: (in __cxa_atexit @ 0000000000001758 : ptr64)
  Class: Eq_53
  DataType: (ptr64 Eq_53)
  OrigDataType: (ptr64 (fn T_59 (T_45, T_58, T_46)))
T_54: (in signature of __cxa_atexit : void)
  Class: Eq_53
  DataType: (ptr64 Eq_53)
  OrigDataType: 
T_55: (in func @ 0000000000001758 : (ptr64 (fn void ((ptr64 void)))))
  Class: Eq_45
  DataType: (ptr64 Eq_45)
  OrigDataType: 
T_56: (in arg @ 0000000000001758 : (ptr64 void))
  Class: Eq_56
  DataType: (ptr64 void)
  OrigDataType: 
T_57: (in dso_handle @ 0000000000001758 : (ptr64 void))
  Class: Eq_46
  DataType: (ptr64 void)
  OrigDataType: 
T_58: (in 0<64> @ 0000000000001758 : word64)
  Class: Eq_56
  DataType: (ptr64 void)
  OrigDataType: (ptr64 void)
T_59: (in __cxa_atexit(x0, null, x2_11) @ 0000000000001758 : int32)
  Class: Eq_59
  DataType: int32
  OrigDataType: int32
T_60: (in 0<64> @ 0000000000001750 : word64)
  Class: Eq_60
  DataType: word64
  OrigDataType: word64
T_61: (in x1_6 + 0<64> @ 0000000000001750 : word64)
  Class: Eq_61
  DataType: word64
  OrigDataType: word64
T_62: (in Mem0[x1_6 + 0<64>:word64] @ 0000000000001750 : word64)
  Class: Eq_46
  DataType: (ptr64 void)
  OrigDataType: word64
*/
typedef struct Globals {
	Eq_12 t0FC0;	// FC0
	Eq_15 t16B8;	// 16B8
	Eq_16 t1738;	// 1738
	void * ptr1FC20;	// 1FC20
	void (* ptr1FF98)();	// 1FF98
	<anonymous> * ptr1FFA0;	// 1FFA0
	word64 qw1FFD0;	// 1FFD0
	void ** ptr1FFD8;	// 1FFD8
	void (* ptr1FFE0)();	// 1FFE0
	int32 (* ptr1FFE8)(int32 x0, char ** x1, char ** x2);	// 1FFE8
} Eq_1;

typedef void (Eq_2)();

typedef void (Eq_5)();

typedef int32 (Eq_10)( *, int32, char * *,  *,  *,  *, void);

typedef int32 (Eq_12)(int32 x0, char * * x1, char * * x2);

typedef void (Eq_15)();

typedef void (Eq_16)();

typedef void (Eq_28)();

typedef word64 (Eq_35)();

typedef void (Eq_45)(void);

typedef int32 (Eq_53)( *, void, void);

