Mem0:Global memory
    def:  def Mem0
    uses: branch rArg0 > Mem0[ds:bx:real32] l0C00_000C
fp:Temporary
rArg0:FPU stack
    def:  def rArg0
    uses: branch rArg0 > Mem0[ds:bx:real32] l0C00_000C
bx:Register bx
    def:  def bx
    uses: branch rArg0 > Mem0[ds:bx:real32] l0C00_000C
ds:Register ds
    def:  def ds
    uses: branch rArg0 > Mem0[ds:bx:real32] l0C00_000C
FPUF:Flags
SCZO:Flags
SZO:Flags
ecx:Register ecx
FPUF_9: orig: FPUF
SCZO_10: orig: SCZO
SZO_11: orig: SZO
ecx_12: orig: ecx
SCZO_13: orig: SCZO
ecx_14: orig: ecx
SCZO_15: orig: SCZO
// fn0C00_0000
void fn0C00_0000(word16 bx, selector ds, real64 rArg0)
fn0C00_0000_entry:		// block 0, pred:
	def Mem0
	def rArg0
	def bx
	def ds
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	branch rArg0 > Mem0[ds:bx:real32] l0C00_000C
	// succ:  2 3
l0C00_0009:		// block 2, pred: 1
	// succ:  3
l0C00_000C:		// block 3, pred: 1 2
	return
	// succ:  4
fn0C00_0000_exit:		// block 4, pred: 3
	// succ: 

