fp:fp
sp_1: orig: sp
ax_2: orig: ax
bx_3: orig: bx
cx_4: orig: cx
Mem5: orig: Mem0
    def:  Mem5[ds:0x0300:word16] = 0x0004
ds:ds
    def:  def ds
    uses: Mem5[ds:0x0300:word16] = 0x0004
bx_7: orig: bx
ax_8: orig: ax
// fn0C00_0000
// Return size: 0
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	Mem5[ds:0x0300:word16] = 0x0004
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

