Mem0:Global memory
fp:Temporary
sp:sp
ax:ax
bx:bx
cx:cx
ds:ds
    def:  def ds
    uses: Mem10[ds:0x0300:word16] = 0x0004
ax_7: orig: ax
bx_8: orig: bx
cx_9: orig: cx
Mem10: orig: Mem0
    def:  Mem10[ds:0x0300:word16] = 0x0004
bx_11: orig: bx
ax_12: orig: ax
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:
	def ds
	// succ:  l0C00_0000
l0C00_0000:
	Mem10[ds:0x0300:word16] = 0x0004
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

