void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax si al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// C:Flags
// ax:Register ax
// ds:Register ds
// v5:Temporary
// SCZO:Flags
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	C = fn0C00_000A(ds, &ax)
	branch Test(ULT,C) l0C00_0009
	// succ:  l0C00_0005 l0C00_0009
l0C00_0005:		// pred: l0C00_0000
	v5 = Mem0[ds:0x0300:word16] + ax
	Mem0[ds:0x0300:word16] = v5
	SCZO = cond(v5)
	// succ:  l0C00_0009
l0C00_0009:		// pred: l0C00_0000 l0C00_0005
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0009
	// succ: 
FlagGroup byte fn0C00_000A(Register selector ds, Register out ptr16 axOut)
// MayUse:  ds
// LiveOut: C ax
// Trashed: SCZO ax si al ah
// Preserved:
// fn0C00_000A
// Mem0:Global memory
// fp:Temporary
// ds:Register ds
// si:Register si
// SCZO:Flags
// Z:Flags
// C:Flags
// ax:Register ax
// SZO:Flags
// axOut:Out:Register ax
// return address size: 2
byte fn0C00_000A(selector ds, ptr16 axOut)
fn0C00_000A_entry:		// pred:
	// succ:  l0C00_000A
l0C00_000A:		// pred: fn0C00_000A_entry
	si = Mem0[ds:0x0100:word16]
	SCZO = cond(si - Mem0[ds:0x0102:word16])
	branch Test(EQ,Z) l0C00_001E
	// succ:  l0C00_0014 l0C00_001E
l0C00_0014:		// pred: l0C00_000A
	ax = Mem0[ds:si:word16]
	si = si + 0x0001
	si = si + 0x0001
	SZO = cond(si)
	Mem0[ds:0x0100:word16] = si
	C = false
	return C
	// succ:  fn0C00_000A_exit
fn0C00_000A_exit:		// pred: l0C00_001E l0C00_0014
	use ax (=> axOut)
	// succ: 
l0C00_001E:		// pred: l0C00_000A
	C = true
	return C
	// succ:  fn0C00_000A_exit
