void fn0C00_0000(Register selector ds)
// MayUse:  ds
// LiveOut:
// Trashed: ax si al ah
// Preserved:
// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// si:Register si
// ax:Register ax
// ds:Register ds
// al:Register al
// return address size: 2
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	si = 0x0200
	ax = fn0C00_0015(si, ds)
	Mem0[ds:0x0202:word16] = ax
	si = 0x0300
	ax = fn0C00_0015(si, ds)
	Mem0[ds:0x0302:byte] = al
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
Register word16 fn0C00_0015(Register word16 si, Register selector ds)
// MayUse:  si ds
// LiveOut: ax al
// Trashed: ax al ah
// Preserved:
// fn0C00_0015
// Mem0:Global memory
// fp:Temporary
// si:Register si
// ds:Register ds
// ax:Register ax
// return address size: 2
word16 fn0C00_0015(word16 si, selector ds)
fn0C00_0015_entry:		// pred:
	// succ:  l0C00_0015
l0C00_0015:		// pred: fn0C00_0015_entry
	ax = Mem0[ds:si:word16]
	return ax
	// succ:  fn0C00_0015_exit
fn0C00_0015_exit:		// pred: l0C00_0015
	// succ: 
