// void fn0C00_0000(Register selector ds)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse:  ds
// LiveOut:
// Trashed: SCZO ax cx dx bx di al cl dl bl ah ch dh bh es gs
// Preserved: ds
// fn0C00_0000
void fn0C00_0000(selector ds)
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	word16 dx_18 = Mem0[ds:Mem0[ds:0x9CFD:word16] * 0x0002 + 0x99F8:word16]
	Mem19[ds:0x9CFF:word16] = dx_18
	word16 ax_28
	msdos_read_file(Mem19[ds:0x99D0:word16], 0x0180, SEQ(0x6041, dx_18), &ax_28)
	msdos_close_file(Mem19[ds:0x99D0:word16])
	Mem38[ds:0xC36A:word16] = Mem19[ds:Mem19[ds:0x9CFD:word16] * 0x0002 + 0x542E:word16]
	Mem44[ds:0x0100:word16] = ds
	Mem46[ds:0x0102:word16] = 0x6041
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 

