// LiveCopyMock
void LiveCopyMock()
LiveCopyMock_entry:		// pred:
	def reg
	// succ:  l1
l1:		// pred: LiveCopyMock_entry
	reg_6 = reg
	branch (reg & 0x00000001) == 0x00000000 even
	// succ:  l2 even
l2:		// pred: l1
	reg_5 = reg + 0x00000002
	// succ:  even
even:		// pred: l1 l2
	reg_6 = PHI(reg_6, reg_5)
	return reg_6 - reg
	// succ:  LiveCopyMock_exit
LiveCopyMock_exit:		// pred: even
	// succ: 
