a:Local -0004
    def:  def a
    uses: Mem3[0x10000000:word32] = a + b
          Mem4[0x10000004:word32] = a
b:Local -0008
    def:  def b
    uses: Mem3[0x10000000:word32] = a + b
c_2: orig: c
Mem3: orig: Mem0
    def:  Mem3[0x10000000:word32] = a + b
Mem4: orig: Mem0
    def:  Mem4[0x10000004:word32] = a
// SimpleMock
void SimpleMock()
	// liveIn: 
SimpleMock_entry:
	def a
	def b
	// liveOut: a b
	// liveIn: a b
l1:
	Mem3[0x10000000:word32] = a + b
	Mem4[0x10000004:word32] = a
	// liveOut: 
	// liveIn: 
SimpleMock_exit:
	// liveOut: 

