// STRLEN.c
// Generated by decompiling STRLEN
// using Decompiler version 0.5.5.0.

#include "STRLEN.h"

Eq_135 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * g_ptr0000;
Eq_243 g_t0001;
Eq_707 g_a0005[];
word32 g_a0008[];
ui32 g_a0010[];
word32 g_dw13C8 = 0x00000000;

