decompile.exe --heuristic shingle  BENCHFN
decompile.exe --heuristic shingle  BENCHLNG
decompile.exe --heuristic shingle  BENCHMUL
decompile.exe --heuristic shingle  BYTEOPS
decompile.exe --heuristic shingle  FIBO
decompile.exe --heuristic shingle  MATRIXMU
decompile.exe --heuristic shingle  MAX
decompile.exe --heuristic shingle  STRLEN
decompile.exe --heuristic shingle  TESTLONG
