// ais3_crackme.globals.c
// Generated by decompiling ais3_crackme
// using Reko decompiler version 0.9.1.0.

#include "ais3_crackme.h"

Eq_n g_t4005C5 = Unexpected function type (fn int32 (int32, (ptr64 (ptr64 char)), (ptr64 (ptr64 char))))
;
Eq_n g_t400620 = Unexpected function type (fn void ())
;
Eq_n g_t4006B0 = Unexpected function type (fn void ())
;
char g_str4006C8[] = "You need to enter the secret key!";
char g_str4006F0[] = "Correct! that is the secret key!";
char g_str400718[] = "I'm sorry, that's the wrong secret key!";
<anonymous> * g_a600DF8[] = 
	{
	};
word64 g_qw600E08 = 0x00;
byte g_a601020[] = 
	{
	};
byte g_b601038 = 0x00;

