// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// sp:sp
// ax:ax
// ds:ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:
	// succ:  l0C00_0000
l0C00_0000:
	call fn0C00_0008 (retsize: 2;)
	Mem0[ds:0x0306:word16] = ax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_0008
// Mem0:Global memory
// fp:Temporary
// sp:sp
// ds:ds
// ss:ss
// bx:bx
// ax:ax
// ss_sp:Sequence ss:sp
// return address size: 2
void fn0C00_0008()
fn0C00_0008_entry:
	// succ:  l0C00_0008
l0C00_0008:
	Mem0[ds:0x0300:word16] = sp
	Mem0[ds:0x0302:word16] = ss
	Mem0[ds:0x0308:word16] = bx
	ax = Mem0[ds:0x0304:word16]
	ss_sp = Mem0[ds:0x0300:ptr32]
	return
	// succ:  fn0C00_0008_exit
fn0C00_0008_exit:
