// hello_data.c
// Generated by decompiling hello.wasm
// using Reko decompiler version 0.11.4.0.

#include "hello.h"

ui32 g_dw140030 = 0x52000026; // 00140030
word32 g_dw140034 = 0x70000035; // 00140034
word32 g_dw140048 = 0x01000000; // 00140048
ui32 g_dw140094 = 0x18000000; // 00140094
