#region License
/* 
 * Copyright (C) 1999-2020 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reko.Arch.PaRisc
{
    public enum Mnemonic
    {
        invalid,

        add,
        add_c,
        add_c_tsv,
        add_l,
        add_tsv,
        addb,
        addbf,
        addbt,
        addi,
        addi_tc,
        addi_tsv,
        addi_tsv_tc,
        addib,
        addibf,
        addibt,
        addil,
        addl,
        and,
        andcm,
        b_gate,
        b_l,
        b_l_push,
        bb,
        be,
        be_l,
        blr,
        blrpush,
        @break,
        bv,
        bvb,
        bve,
        cldd,
        cldw,
        cmpb,
        cmpclr,
        cmpib,
        cmpiclr,
        cstd,
        cstw,
        dcor,
        dcor_i,
        depw,
        depwi,
        diag,
        ds,
        extrw,
        fabs,
        fadd,
        fcmp,
        fcnv,
        fcnv_t,
        fcnvff,
        fcnvfx,
        fcnvfxt,
        fcnvxf,
        fcpy,
        fdc,
        fdce,
        fdiv,
        fic,
        fic_0a,
        fice,
        fid,
        fldd,
        fldw,
        fmpy,
        fmpyadd,
        fmpysub,
        fneg,
        fnegabs,
        frnd,
        fsqrt,
        fstd,
        fstw,
        fsub,
        hadd,
        hadd_ss,
        hadd_us,
        havg,
        hshl,
        hshladd,
        hshr_s,
        hshr_u,
        hshradd,
        hsub,
        hsub_ss,
        hsub_us,
        idcor,
        idtlbt,
        iitlbt,
        lci,
        ldb,
        ldcd,
        ldcw,
        ldd,
        ldda,
        ldh,
        ldil,
        ldo,
        ldsid,
        ldw,
        ldwa,
        ldwm,
        lpa,
        mfctl,
        mfctl_w,
        mfsp,
        mixh_l,
        mixh_r,
        mixw_l,
        mixw_r,
        movb,
        movib,
        mtctl,
        mtsm,
        mtsp,
        or,
        pdc,
        pdtlb,
        pdtlb_l,
        pdtlbe,
        permh,
        pitlb,
        pitlb_l,
        pitlbe,
        probe,
        probei,
        rfi,
        rfi_r,
        rsm,
        sh1addl,
        sh2addl,
        sh3addl,
        shladd,
        shladd_tsv,
        shladdo,
        shrpd,
        shrpw,
        spop0,
        spop1,
        spop2,
        spop3,
        ssm,
        stb,
        stby,
        std,
        stda,
        stdby,
        sth,
        stw,
        stwa,
        stwm,
        sub,
        sub_b,
        sub_b_tsv,
        sub_tc,
        sub_tsv,
        sub_tsv_tc,
        subb,
        subbo,
        subi,
        subi_tsv,
        subo,
        subto,
        sync,
        syncdma,
        uaddcm,
        uaddcm_tc,
        uxor,
        xmpyu,
        xor,
        bve_l,
    }
}