// void fn10000000(Stack word32 dwArg00)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: 0
// MayUse: 
// LiveOut:
// Trashed: eax ax al ah
// Preserved: esi edi
// Stack args: Stack +0000(32)
// fn10000000
void fn10000000(word32 dwArg00)
fn10000000_entry:		// pred:
	// succ:  l10000000
l10000000:		// pred: fn10000000_entry
	GlobalUnlock(GlobalHandle(dwArg00))
	GlobalFree(GlobalHandle(dwArg00))
	return
	// succ:  fn10000000_exit
fn10000000_exit:		// pred: l10000000
	// succ: 

