// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  si ds
	BypassIn: 
	Trashed:   SCZO ax al ah
	Preserved:
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
// DataOut: si ds
l0C00_0000:		// pred: fn0C00_0000_entry
	ax = Mem0[ds:si + 0x0200:word16]
	Mem0[ds:0x0200:word16] = 0x0000
	Mem0[ds:0x0300:word16] = ax
	ax = Mem0[ds:si + 0x0202:word16]
	Mem0[ds:0x0202:word16] = ax
	ax = Mem0[ds:si + 0x0204:word16]
	v5 = Mem0[ds:0x0204:word16] + ax
	Mem0[ds:0x0204:word16] = v5
	SCZO = cond(v5)
	ax = Mem0[ds:0x0200:word16]
	call fn0C00_002A (depth: 2;)
	Mem0[ds:0x0200:word16] = ax
	return
	// succ:  fn0C00_0000_exit
// DataOut:
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
// DataOut:
// fn0C00_002A /////////////////////
	LiveOut:   ds
	MayUseIn:  ds
	BypassIn: 
	Trashed:  
	Preserved: ax
// fn0C00_002A
void fn0C00_002A()
fn0C00_002A_entry:		// pred:
	// succ:  l0C00_002A
// DataOut: ds
l0C00_002A:		// pred: fn0C00_002A_entry
	wLoc04 = ax
	Mem0[ds:0x0200:word16] = 0xFFFF
	ax = wLoc04
	return
	// succ:  fn0C00_002A_exit
// DataOut: ds
fn0C00_002A_exit:		// pred: l0C00_002A
	// succ: 
// DataOut: ds
