// fn0C00_0000 /////////////////////
	LiveOut:  
	MayUseIn:  bx ds
	BypassIn: 
	Trashed:   ax al ah
	Preserved: sp
// fn0C00_0000
void fn0C00_0000()
fn0C00_0000_entry:
// DataOut: bx ds
// DataOut (flags):
// SymbolicIn: sp:fp
l0C00_0000:
	call fn0C00_0006 (retsize: 2; depth: 2)
	Mem0[ds:bx:word16] = 0x0001
	return
// DataOut:
// DataOut (flags):
// SymbolicIn: sp:fp

fn0C00_0000_exit:
// DataOut:
// DataOut (flags):
// SymbolicIn: sp:fp ax:0x0001

// fn0C00_0006 /////////////////////
	LiveOut:   ax bx ds
	MayUseIn: 
	BypassIn: 
	Trashed:   ax al ah
	Preserved:
// fn0C00_0006
void fn0C00_0006()
fn0C00_0006_entry:		// block 0, pred:
	// succ:  1
// DataOut: bx ds
l0C00_0006:		// block 1, pred: 0
	ax = 0x0001
	return
	// succ:  2
// DataOut: ax bx ds
fn0C00_0006_exit:		// block 2, pred: 1
	// succ: 
// DataOut: ax bx ds
