cmake_minimum_required ( VERSION 3.10 FATAL_ERROR )
list(INSERT CMAKE_MODULE_PATH 0 "${REKO_SRC}/../cmake")

include(msbuild2cmake)

invoke_cmake(
	BUILD_DIR ${CMAKE_BINARY_DIR}/build/${TARGET}
	DIRECTORY ${REKO_SRC}/../
	TARGET ${TARGET}
	PASS_VARIABLES
		CMAKE_BUILD_TYPE
		REKO_SRC
	EXTRA_ARGUMENTS
		-DREKO_PLATFORM=${REKO_ACTUAL_PLATFORM}
		-DTARGET=${TARGET}
)