#region License
/* 
 * Copyright (C) 1999-2020 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

namespace Reko.Arch.M6800.M6809
{
    public enum Mnemonic
    {
        invalid,

        abx,
        adca,
        adcb,
        adda,
        addb,
        addd,
        anda,
        andb,
        andcc,
        asr,
        beq,
        bge,
        bgt,
        bhi,
        bhs,
        bita,
        bitb,
        ble,
        blo,
        bls,
        blt,
        bmi,
        bne,
        bpl,
        bra,
        brn,
        bsr,
        bvc,
        bvs,
        clr,
        cmpa,
        cmpb,
        cmpd,
        cmps,
        cmpu,
        cmpx,
        cmpy,
        com,
        cwai,
        daa,
        dec,
        eora,
        eorb,
        exg,
        inc,
        jmp,
        jsr,
        lbeq,
        lbge,
        lbgt,
        lbhi,
        lbhs,
        lble,
        lblo,
        lbls,
        lblt,
        lbmi,
        lbne,
        lbpl,
        lbra,
        lbrn,
        lbsr,
        lbvc,
        lbvs,
        lda,
        ldb,
        ldd,
        lds,
        ldu,
        ldx,
        ldy,
        leas,
        leau,
        leax,
        leay,
        lsl,
        lsr,
        mul,
        neg,
        nop,
        ora,
        orb,
        orcc,
        pshs,
        pshu,
        puls,
        pulu,
        rol,
        ror,
        rti,
        rts,
        sbca,
        sbcb,
        sex,
        sta,
        stb,
        std,
        sts,
        stu,
        stx,
        sty,
        suba,
        subb,
        subd,
        swi,
        swi2,
        swi3,
        sync,
        tfr,
        tst,
    }
}