// fn0C00_0000
// Return size: 2
define fn0C00_0000
fn0C00_0000_entry:
	sp = fp
	Top = 0<i8>
	// succ:  l0C00_0000
l0C00_0000:
	ebx = 0x20<32>
	eax = 0x64<32>
	edx_eax = CONVERT(eax, int32, int64)
	v8 = edx_eax
	edx = CONVERT(v8 %s ebx, int64, int32)
	eax = CONVERT(v8 /32 ebx, word32, int32)
	SCZO = cond(eax)
	cx = Mem0[ds:si:word16]
	ax = Mem0[ds:si + 2<i16>:word16]
	dx = Mem0[ds:si + 4<i16>:word16]
	v16 = dx_ax
	dx = CONVERT(v16 %u cx, word32, uint16)
	ax = CONVERT(v16 /u cx, word16, uint16)
	SCZO = cond(ax)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
