// fn10000000
// Return size: 4
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// esp:esp
// edi:edi
// esi:esi
// ebx:ebx
// SZ:SZ
// O:O
// C:C
// Z:Z
// eax:eax
// SCZO:SCZO
// SZO:SZO
// Top:Top
// return address size: 4
define fn10000000
fn10000000_entry:
	esp = fp
	Top = 0<i8>
	// succ:  l10000000
l10000000:
	edi = 0x10000034<32>
	esi = 3<32>
	ebx = malloc
	goto l1000002F
	// succ:  l1000002F
l10000015:
	esp = esp - 4<i32>
	Mem0[esp:word32] = 8<32>
	eax = malloc(Mem0[esp:size_t])
	esp = esp + 4<32>
	SCZO = cond(esp)
	Mem0[eax:word32] = 0<32>
	Mem0[eax + 4<i32>:word32] = 0<32>
	Mem0[edi:word32] = eax
	esi = esi - 1<32>
	SZO = cond(esi)
	edi = edi + 4<32>
	SCZO = cond(edi)
	// succ:  l1000002F
l1000002F:
	esi = esi | esi
	SZ = cond(esi)
	O = false
	C = false
	branch Test(NE,Z) l10000015
	// succ:  l10000033 l10000015
l10000033:
	return
	// succ:  fn10000000_exit
fn10000000_exit:

