// fn10000000
// Return size: 4
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// esp:esp
// edi:edi
// esi:esi
// ebx:ebx
// SZ:SZ
// O:O
// C:C
// Z:Z
// v11:v11
// eax:eax
// SZO:SZO
// SCZO:SCZO
// Top:Top
// return address size: 4
define fn10000000
fn10000000_entry:
	esp = fp
	Top = 0<i8>
	// succ:  l10000000
l10000000:
	edi = Mem0[0x1000002C<p32>:word32]
	esi = 3<32>
	ebx = GetDC
	goto l10000027
	// succ:  l10000027
l10000016:
	v11 = Mem0[edi:word32]
	esp = esp - 4<i32>
	Mem0[esp:word32] = v11
	eax = GetDC(Mem0[esp:HWND])
	esp = esp + 4<32>
	Mem0[edi:word32] = eax
	esp = esp - 4<i32>
	Mem0[esp:word32] = 0<32>
	eax = GetDC(Mem0[esp:HWND])
	esp = esp + 4<32>
	Mem0[edi + 4<i32>:word32] = eax
	esi = esi - 1<32>
	SZO = cond(esi)
	edi = edi + 8<32>
	SCZO = cond(edi)
	// succ:  l10000027
l10000027:
	esi = esi | esi
	SZ = cond(esi)
	O = false
	C = false
	branch Test(NE,Z) l10000016
	// succ:  l1000002B l10000016
l1000002B:
	return
	// succ:  fn10000000_exit
fn10000000_exit:

