// fn10000008
// Return size: 4
// Mem0:Mem
// fp:fp
// esp:esp
// eax:eax
// SCZO:SCZO
// Top:Top
// return address size: 4
define fn10000008
fn10000008_entry:
	esp = fp
	Top = 0<i8>
	// succ:  l10000008
l10000008:
	esp = esp - 4<i32>
	Mem0[esp:word32] = 8<32>
	eax = malloc(Mem0[esp:size_t])
	esp = esp + 4<32>
	SCZO = cond(esp)
	Mem0[eax:word32] = 0<32>
	Mem0[eax + 4<i32>:word32] = 0x1024<32>
	esp = esp - 4<i32>
	Mem0[esp:word32] = eax
	free(Mem0[esp:(ptr32 void)])
	esp = esp + 4<32>
	SCZO = cond(esp)
	return
	// succ:  fn10000008_exit
fn10000008_exit:

