// fn0C00_0000
// Return size: 2
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// sp:sp
// eax:eax
// C:C
// SZO:SZO
// SCZO:SCZO
// ds:ds
// v9:v9
// v10:v10
// v11:v11
// v12:v12
// ecx:ecx
// bx:bx
// v15:v15
// cx:cx
// Top:Top
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:
	sp = fp
	Top = 0<i8>
	// succ:  l0C00_0000
l0C00_0000:
	C = eax != 0<32>
	eax = -eax
	SZO = cond(eax)
	eax = eax - eax - C
	SCZO = cond(eax)
	Mem0[ds:0x300<16>:word32] = eax
	v9 = Mem0[ds:0x202<16>:word16]
	C = v9 != 0<16>
	v10 = -v9
	Mem0[ds:0x202<16>:word16] = v10
	SZO = cond(v10)
	v11 = Mem0[ds:0x200<16>:word16]
	C = v11 != 0<16>
	v12 = -v11
	Mem0[ds:0x200<16>:word16] = v12
	SZO = cond(v12)
	ecx = ecx - ecx - C
	SCZO = cond(ecx)
	Mem0[ds:0x308<16>:word32] = ecx
	bx = ~bx
	Mem0[ds:0x304<16>:word16] = bx
	v15 = ~Mem0[ds:0x204<16>:word16]
	Mem0[ds:0x204<16>:word16] = v15
	cx = Mem0[ds:0x304<16>:word16]
	cx = cx - 0x3E8<16>
	SCZO = cond(cx)
	C = cx != 0<16>
	cx = -cx
	SZO = cond(cx)
	Mem0[ds:0x306<16>:word16] = cx
	eax = Mem0[ds:0x310<16>:word32]
	C = eax != 0<32>
	eax = -eax
	SZO = cond(eax)
	eax = eax - eax - C
	SCZO = cond(eax)
	eax = eax + 1<32>
	SZO = cond(eax)
	Mem0[ds:0x30C<16>:word32] = eax
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

