// fn10000000
// Return size: 4
// Mem0:Mem
// fp:fp
// esp:esp
// edi:edi
// Top:Top
// eax:eax
// return address size: 4
define fn10000000
fn10000000_entry:
	esp = fp
	Top = 0<i8>
	// succ:  l10000000
l10000000:
	edi = 0x10001212<32>
	Top = Top - 1<i8>
	ST[Top:real64] = Mem0[edi + 4<i32>:real64]
	Top = Top - 1<i8>
	ST[Top:real64] = Mem0[edi + 12<i32>:real64]
	call not_found_import (retsize: 4;)
	Mem0[edi + 20<i32>:word32] = eax
	call not_found_import (retsize: 4;)
	Mem0[edi + 28<i32>:word32] = eax
	return
	// succ:  fn10000000_exit
fn10000000_exit:

