// fn0C00_0000
// Return size: 2
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// sp:sp
// C:C
// ds:ds
// bp:bp
// Top:Top
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:
	sp = fp
	Top = 0<i8>
	// succ:  l0C00_0000
l0C00_0000:
	call fn0C00_000A (retsize: 2;)
	branch Test(ULT,C) l0C00_0009
	// succ:  l0C00_0005 l0C00_0009
l0C00_0005:
	Mem0[ds:0x200<16>:word16] = bp
	// succ:  l0C00_0009
l0C00_0009:
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
// fn0C00_000A
// Return size: 2
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// sp:sp
// bp:bp
// ss:ss
// SCZO:SCZO
// Z:Z
// C:C
// Top:Top
// return address size: 2
define fn0C00_000A
fn0C00_000A_entry:
	sp = fp
	Top = 0<i8>
	// succ:  l0C00_000A
l0C00_000A:
	sp = sp - 2<i16>
	Mem0[ss:sp:word16] = bp
	bp = 0x300<16>
	goto l0C00_0014
	// succ:  l0C00_0014
l0C00_0011:
	bp = Mem0[ss:bp:word16]
	// succ:  l0C00_0014
l0C00_0014:
	SCZO = cond(bp - 0<16>)
	branch Test(EQ,Z) l0C00_0024
	// succ:  l0C00_0019 l0C00_0024
l0C00_0019:
	SCZO = cond(Mem0[ss:bp:word16] - 0<16>)
	branch Test(NE,Z) l0C00_0011
	// succ:  l0C00_001F l0C00_0011
l0C00_001F:
	sp = sp + 2<16>
	SCZO = cond(sp)
	C = 0<32>
	return
	// succ:  fn0C00_000A_exit
l0C00_0024:
	bp = Mem0[ss:sp:word16]
	sp = sp + 2<i16>
	C = 2<32>
	return
	// succ:  fn0C00_000A_exit
fn0C00_000A_exit:
