// fn0C00_0000
// Mem0:Mem memory
// fp:Temporary
// wLoc04:Local -0004
// return address size: 2
define fn0C00_0000
fn0C00_0000_entry:		// pred:
	// succ:  l0C00_0000
l0C00_0000:		// pred: fn0C00_0000_entry
	wLoc04 = 0x0000
	call fn0C00_0009 (depth: 4;)
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:		// pred: l0C00_0000
	// succ: 
// fn0C00_0009
// Mem0:Mem memory
// fp:Temporary
// bx:Register bx
// wLoc04:Local -0004
// dx:Register dx
// wLoc06:Local -0006
// bp:Register bp
// wLoc08:Local -0008
// wArg00:Stack +0000
// ax:Register ax
// wLoc0A:Local -000A
// return address size: 2
define fn0C00_0009
fn0C00_0009_entry:		// pred:
	// succ:  l0C00_0009
l0C00_0009:		// pred: fn0C00_0009_entry
	wLoc04 = bx
	wLoc06 = dx
	wLoc08 = bp
	dx = wArg00
	wLoc0A = ax
	ax = 0x0354
	call fn0C00_0029 (depth: 10;)
	bp = wLoc08
	dx = wLoc06
	bx = wLoc04
	return
	// succ:  fn0C00_0009_exit
fn0C00_0009_exit:		// pred: l0C00_0009
	// succ: 
// fn0C00_0029
// Mem0:Mem memory
// fp:Temporary
// ax:Register ax
// ds:Register ds
// return address size: 2
define fn0C00_0029
fn0C00_0029_entry:		// pred:
	// succ:  l0C00_0029
l0C00_0029:		// pred: fn0C00_0029_entry
	Mem0[ds:0x0300:word16] = ax
	return
	// succ:  fn0C00_0029_exit
fn0C00_0029_exit:		// pred: l0C00_0029
	// succ: 
