// ProcedureBuilder
// Return size: 0
define ProcedureBuilder
ProcedureBuilder_entry:
	goto l1
	// succ:  l1
grox:
l1:
	sp = sp - 2<16>
	Mem0[sp:selector] = cs
	ds = Mem0[sp:word16]
	sp = sp + 2<16>
	bl = Mem0[si:byte]
	SCZO = cond(bl - 2<8>)
	branch Test(UGT,SCZO) grox
	// succ:  l2 grox
l2:
	bh = bh ^ bh
	SCZO = cond(bh)
	bx = bx + bx
	SCZO = cond(bx)
ProcedureBuilder_exit:
cmp 2
branch UGT
& 255
* 2
Index register: bl
