#region License
/* 
 * Copyright (C) 1999-2021 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

namespace Reko.Arch.Renesas.Rx
{
    public enum Mnemonic
    {
        add,
        nyi,
        Invalid,
        abs,
        adc,
        and,
        bclr,
        beq,
        bne,
        bgeu,
        bltu,
        bgtu,
        bleu,
        bpz,
        bn,
        bge,
        blt,
        bgt,
        ble,
        bo,
        bno,
        bra,

        bmeq,
        bmne,
        bmgeu,
        bmltu,

        bmgtu,
        bmleu,
        bmpz,
        bmn,


        bmge,
        bmlt,
        bmgt,
        bmle,

        bmo,
        bmno,
        bnot,
        brk,
        bset,
        btst,
        clrpsw,
        cmp,
        div,
        divu,
        emaca,
        emsba,
        emul,
        nop,
        rts,
        fadd,
        emula,
        emulu,
        bsr,
        fcmp,
        fdiv,
        fsqrt,
        fmul,
        ftoi,
        fsub,
        ftou,
        @int,
        jmp,
        jsr,
        maclo,
        machi,
        maclh,
        max,
        itof,
        min,
        mov,
        movco,
        movli,
        movu,
        msbhi,
        msblh,
        msblo,
        mul,
        mulhi,
        mullh,
        mullo,
        mvfacgu,
        mvfachi,
        mvfaclo,
        mvfacmi,
        mvfc,
        mvtacgu,
        mvtacmi,
        mvtaclo,
        mvtachi,
        mvtc,
        mvtipl,
        not,
        or,
        pop,
        popc,
        popm,
        push,
        pushc,
        pushm,
        revl,
        revw,
        rmpa,
        rolc,
        rorc,
        rotl,
        rotr,
        round,
        rte,
        rtfi,
        rtsd,
        sat,
        satr,
        sbb,

        sceq,
        scne,
        scgeu,
        scltu,
        scgtu,
        scleu,
        scpz,
        scn,
        scge,
        sclt,
        scgt,
        scle,
        sco,
        scno,
        setpsw,
        shar,
        shll,
        shlr,
        smovb,
        smovf,
        smovu,
        sstr,
        stnz,
        stz,
        sub,
        swhile,
        suntil,
        tst,
        utof,
        wait,
        xchg,
        xor,
        neg,
        racw,
        scmpu,
        racl,
        rdacw,
        rdacl,
    }
}