// FactorialMock
// Return size: 0
// Mem0:Mem
// fp:fp
// %continuation:%continuation
// r2:Stack -0004
// r3:Stack -0008
// Z:Z
// r1:Stack -000C
// return address size: 0
define FactorialMock
FactorialMock_entry:
	goto l1
	// succ:  l1
done:
	return r3
	// succ:  FactorialMock_exit
l1:
	r3 = 1<i32>
	goto test
	// succ:  test
l2:
	r3 = r3 *s r2
	r2 = r2 - 1<i32>
	// succ:  test
test:
	Z = cond(r2 - 0<i32>)
	branch Test(EQ,Z) done
	goto l2
	// succ:  l2 done
FactorialMock_exit:
