// WhileLtIncMock
// Return size: 0
void WhileLtIncMock()
WhileLtIncMock_entry:
	def a
	// succ:  l1
l1:
	i_4 = 0x00000000
	goto loopHdr
	// succ:  loopHdr
l2:
	return
	// succ:  WhileLtIncMock_exit
loop:
	Mem6[a + i_5 * 0x00000004:word32] = 0x00000000
	i_7 = i_5 + 0x00000001
	// succ:  loopHdr
loopHdr:
	i_5 = PHI(i_4, i_7)
	branch i_5 < 0x00000064 loop
	goto l2
	// succ:  l2 loop
WhileLtIncMock_exit:

(0x00000000 0x00000001 0x00000064 signed)
