= fn0C00_0000 ========================
Mem0:Global memory
    def:  def Mem0
    uses: ax_15 = Mem0[ds:si_14:word16]
fp:fp
    def:  def fp
sp:sp
    def:  def sp
bx:bx
    def:  def bx
si:si
    def:  def si
    uses: bx_13 = si
          si_14 = PHI(si, si_16, si_16)
ax:ax
    def:  def ax
ds:ds
    def:  def ds
    uses: ax_15 = Mem0[ds:si_14:word16]
          Mem26[ds:0x0300:word16] = ax_25
          Mem33[ds:di:word16] = ax_15
          v12_44 = Mem33[ds:0x0302:word16] + 0x0001
          Mem45[ds:0x0302:word16] = v12_44
SCZO:Flags
    def:  def SCZO
Z:Flags
    def:  def Z
di:di
    def:  def di
    uses: Mem33[ds:di:word16] = ax_15
SZO:Flags
    def:  def SZO
C:Flags
    def:  def C
v12:v12
    def:  def v12
bx_13: orig: bx
    def:  bx_13 = si
    uses: ax_28 = ax_27 - bx_13
si_14: orig: si
    def:  si_14 = PHI(si, si_16, si_16)
    uses: ax_15 = Mem0[ds:si_14:word16]
          si_16 = si_14 + 0x0002
ax_15: orig: ax
    def:  ax_15 = Mem0[ds:si_14:word16]
    uses: SCZO_17 = cond(ax_15 - 0x0020)
          Mem33[ds:di:word16] = ax_15
          ax_34 = ax_15 | ax_15
          ax_34 = ax_15 | ax_15
          branch ax_15 != 0x0020 l0C00_0005
si_16: orig: si
    def:  si_16 = si_14 + 0x0002
    uses: ax_27 = si_16
          si_14 = PHI(si, si_16, si_16)
          si_14 = PHI(si, si_16, si_16)
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(ax_15 - 0x0020)
    uses: Z_18 = SCZO_17 (alias)
          SZO_19 = SCZO_17 (alias)
          C_20 = SCZO_17 (alias)
Z_18: orig: Z
    def:  Z_18 = SCZO_17 (alias)
SZO_19: orig: SZO
    def:  SZO_19 = SCZO_17 (alias)
C_20: orig: C
    def:  C_20 = SCZO_17 (alias)
C_21: orig: C
    def:  C_21 = PHI(C_32, C_37)
SZO_22: orig: SZO
    def:  SZO_22 = PHI(SZO_31, SZO_35)
Z_23: orig: Z
    def:  Z_23 = PHI(Z_30, Z_36)
SCZO_24: orig: SCZO
    def:  SCZO_24 = PHI(SCZO_29, SCZO_38)
ax_25: orig: ax
    def:  ax_25 = PHI(ax_28, ax_39)
    uses: Mem26[ds:0x0300:word16] = ax_25
Mem26: orig: Mem0
    def:  Mem26[ds:0x0300:word16] = ax_25
ax_27: orig: ax
    def:  ax_27 = si_16
    uses: ax_28 = ax_27 - bx_13
ax_28: orig: ax
    def:  ax_28 = ax_27 - bx_13
    uses: SCZO_29 = cond(ax_28)
          ax_25 = PHI(ax_28, ax_39)
SCZO_29: orig: SCZO
    def:  SCZO_29 = cond(ax_28)
    uses: Z_30 = SCZO_29 (alias)
          SZO_31 = SCZO_29 (alias)
          C_32 = SCZO_29 (alias)
          SCZO_24 = PHI(SCZO_29, SCZO_38)
Z_30: orig: Z
    def:  Z_30 = SCZO_29 (alias)
    uses: Z_23 = PHI(Z_30, Z_36)
SZO_31: orig: SZO
    def:  SZO_31 = SCZO_29 (alias)
    uses: SZO_22 = PHI(SZO_31, SZO_35)
C_32: orig: C
    def:  C_32 = SCZO_29 (alias)
    uses: C_21 = PHI(C_32, C_37)
Mem33: orig: Mem0
    def:  Mem33[ds:di:word16] = ax_15
    uses: v12_44 = Mem33[ds:0x0302:word16] + 0x0001
ax_34: orig: ax
    def:  ax_34 = ax_15 | ax_15
    uses: SZO_35 = cond(ax_34)
          SCZO_40 = cond(ax_34 - 0x000D)
          branch ax_34 != 0x0000 l0C00_0011
          branch ax_34 != 0x000D l0C00_001A
SZO_35: orig: SZO
    def:  SZO_35 = cond(ax_34)
    uses: Z_36 = SZO_35 (alias)
          SZO_22 = PHI(SZO_31, SZO_35)
Z_36: orig: Z
    def:  Z_36 = SZO_35 (alias)
    uses: Z_23 = PHI(Z_30, Z_36)
C_37: orig: C
    def:  C_37 = false
    uses: SCZO_38 = C_37 (alias)
          C_21 = PHI(C_32, C_37)
SCZO_38: orig: SCZO
    def:  SCZO_38 = C_37 (alias)
    uses: SCZO_24 = PHI(SCZO_29, SCZO_38)
ax_39: orig: ax
    def:  ax_39 = 0xFFFF
    uses: ax_25 = PHI(ax_28, ax_39)
SCZO_40: orig: SCZO
    def:  SCZO_40 = cond(ax_34 - 0x000D)
    uses: Z_41 = SCZO_40 (alias)
          SZO_42 = SCZO_40 (alias)
          C_43 = SCZO_40 (alias)
Z_41: orig: Z
    def:  Z_41 = SCZO_40 (alias)
SZO_42: orig: SZO
    def:  SZO_42 = SCZO_40 (alias)
C_43: orig: C
    def:  C_43 = SCZO_40 (alias)
v12_44: orig: v12
    def:  v12_44 = Mem33[ds:0x0302:word16] + 0x0001
    uses: Mem45[ds:0x0302:word16] = v12_44
          SZO_46 = cond(v12_44)
Mem45: orig: Mem0
    def:  Mem45[ds:0x0302:word16] = v12_44
SZO_46: orig: SZO
    def:  SZO_46 = cond(v12_44)
    uses: SCZO_47 = SZO_46 (alias)
          Z_48 = SZO_46 (alias)
SCZO_47: orig: SCZO
    def:  SCZO_47 = SZO_46 (alias)
Z_48: orig: Z
    def:  Z_48 = SZO_46 (alias)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def Mem0
	def fp
	def sp
	def bx
	def si
	def ax
	def ds
	def SCZO
	def Z
	def di
	def SZO
	def C
	def v12
	// succ:  l0C00_0000
l0C00_0000:
	bx_13 = si
	goto l0C00_001A
	// succ:  l0C00_001A
l0C00_0005:
	Mem33[ds:di:word16] = ax_15
	ax_34 = ax_15 | ax_15
	SZO_35 = cond(ax_34)
	Z_36 = SZO_35 (alias)
	C_37 = false
	SCZO_38 = C_37 (alias)
	branch ax_34 != 0x0000 l0C00_0011
	// succ:  l0C00_000B l0C00_0011
l0C00_000B:
	ax_39 = 0xFFFF
	goto l0C00_0024
	// succ:  l0C00_0024
l0C00_0011:
	SCZO_40 = cond(ax_34 - 0x000D)
	Z_41 = SCZO_40 (alias)
	SZO_42 = SCZO_40 (alias)
	C_43 = SCZO_40 (alias)
	branch ax_34 != 0x000D l0C00_001A
	// succ:  l0C00_0016 l0C00_001A
l0C00_0016:
	v12_44 = Mem33[ds:0x0302:word16] + 0x0001
	Mem45[ds:0x0302:word16] = v12_44
	SZO_46 = cond(v12_44)
	SCZO_47 = SZO_46 (alias)
	Z_48 = SZO_46 (alias)
	// succ:  l0C00_001A
l0C00_001A:
	si_14 = PHI(si, si_16, si_16)
	ax_15 = Mem0[ds:si_14:word16]
	si_16 = si_14 + 0x0002
	SCZO_17 = cond(ax_15 - 0x0020)
	Z_18 = SCZO_17 (alias)
	SZO_19 = SCZO_17 (alias)
	C_20 = SCZO_17 (alias)
	branch ax_15 != 0x0020 l0C00_0005
	// succ:  l0C00_0020 l0C00_0005
l0C00_0020:
	ax_27 = si_16
	ax_28 = ax_27 - bx_13
	SCZO_29 = cond(ax_28)
	Z_30 = SCZO_29 (alias)
	SZO_31 = SCZO_29 (alias)
	C_32 = SCZO_29 (alias)
	// succ:  l0C00_0024
l0C00_0024:
	C_21 = PHI(C_32, C_37)
	SZO_22 = PHI(SZO_31, SZO_35)
	Z_23 = PHI(Z_30, Z_36)
	SCZO_24 = PHI(SCZO_29, SCZO_38)
	ax_25 = PHI(ax_28, ax_39)
	Mem26[ds:0x0300:word16] = ax_25
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:

Mem0:Global memory
    def:  def Mem0
    uses: ax_15 = Mem0[ds:si_14:word16]
fp:fp
    def:  def fp
sp:sp
    def:  def sp
bx:bx
    def:  def bx
si:si
    def:  def si
    uses: bx_13 = si
          si_14 = PHI(si, si_16, si_16)
          ax_28 = si_16 - si
ax:ax
    def:  def ax
ds:ds
    def:  def ds
    uses: ax_15 = Mem0[ds:si_14:word16]
          Mem26[ds:0x0300:word16] = ax_25
          Mem33[ds:di:word16] = ax_15
          v12_44 = Mem33[ds:0x0302:word16] + 0x0001
          Mem45[ds:0x0302:word16] = v12_44
SCZO:Flags
    def:  def SCZO
Z:Flags
    def:  def Z
di:di
    def:  def di
    uses: Mem33[ds:di:word16] = ax_15
SZO:Flags
    def:  def SZO
C:Flags
    def:  def C
v12:v12
    def:  def v12
bx_13: orig: bx
    def:  bx_13 = si
si_14: orig: si
    def:  si_14 = PHI(si, si_16, si_16)
    uses: ax_15 = Mem0[ds:si_14:word16]
          si_16 = si_14 + 0x0002
ax_15: orig: ax
    def:  ax_15 = Mem0[ds:si_14:word16]
    uses: SCZO_17 = cond(ax_15 - 0x0020)
          Mem33[ds:di:word16] = ax_15
          ax_34 = ax_15
          branch ax_15 != 0x0020 l0C00_0005
          SZO_35 = cond(ax_15)
          branch ax_15 != 0x0000 l0C00_0011
          SCZO_40 = cond(ax_15 - 0x000D)
          branch ax_15 != 0x000D l0C00_001A
si_16: orig: si
    def:  si_16 = si_14 + 0x0002
    uses: ax_27 = si_16
          si_14 = PHI(si, si_16, si_16)
          si_14 = PHI(si, si_16, si_16)
          ax_28 = si_16 - si
SCZO_17: orig: SCZO
    def:  SCZO_17 = cond(ax_15 - 0x0020)
    uses: Z_18 = SCZO_17 (alias)
          SZO_19 = SCZO_17 (alias)
          C_20 = SCZO_17 (alias)
Z_18: orig: Z
    def:  Z_18 = SCZO_17 (alias)
SZO_19: orig: SZO
    def:  SZO_19 = SCZO_17 (alias)
C_20: orig: C
    def:  C_20 = SCZO_17 (alias)
C_21: orig: C
    def:  C_21 = PHI(C_32, C_37)
SZO_22: orig: SZO
    def:  SZO_22 = PHI(SZO_31, SZO_35)
Z_23: orig: Z
    def:  Z_23 = PHI(Z_30, Z_36)
SCZO_24: orig: SCZO
    def:  SCZO_24 = PHI(SCZO_29, SCZO_38)
ax_25: orig: ax
    def:  ax_25 = PHI(ax_28, ax_39)
    uses: Mem26[ds:0x0300:word16] = ax_25
Mem26: orig: Mem0
    def:  Mem26[ds:0x0300:word16] = ax_25
ax_27: orig: ax
    def:  ax_27 = si_16
ax_28: orig: ax
    def:  ax_28 = si_16 - si
    uses: SCZO_29 = cond(ax_28)
          ax_25 = PHI(ax_28, ax_39)
SCZO_29: orig: SCZO
    def:  SCZO_29 = cond(ax_28)
    uses: Z_30 = SCZO_29 (alias)
          SZO_31 = SCZO_29 (alias)
          C_32 = SCZO_29 (alias)
          SCZO_24 = PHI(SCZO_29, SCZO_38)
Z_30: orig: Z
    def:  Z_30 = SCZO_29 (alias)
    uses: Z_23 = PHI(Z_30, Z_36)
SZO_31: orig: SZO
    def:  SZO_31 = SCZO_29 (alias)
    uses: SZO_22 = PHI(SZO_31, SZO_35)
C_32: orig: C
    def:  C_32 = SCZO_29 (alias)
    uses: C_21 = PHI(C_32, C_37)
Mem33: orig: Mem0
    def:  Mem33[ds:di:word16] = ax_15
    uses: v12_44 = Mem33[ds:0x0302:word16] + 0x0001
ax_34: orig: ax
    def:  ax_34 = ax_15
SZO_35: orig: SZO
    def:  SZO_35 = cond(ax_15)
    uses: Z_36 = SZO_35 (alias)
          SZO_22 = PHI(SZO_31, SZO_35)
Z_36: orig: Z
    def:  Z_36 = SZO_35 (alias)
    uses: Z_23 = PHI(Z_30, Z_36)
C_37: orig: C
    def:  C_37 = false
    uses: C_21 = PHI(C_32, C_37)
SCZO_38: orig: SCZO
    def:  SCZO_38 = false (alias)
    uses: SCZO_24 = PHI(SCZO_29, SCZO_38)
ax_39: orig: ax
    def:  ax_39 = 0xFFFF
    uses: ax_25 = PHI(ax_28, ax_39)
SCZO_40: orig: SCZO
    def:  SCZO_40 = cond(ax_15 - 0x000D)
    uses: Z_41 = SCZO_40 (alias)
          SZO_42 = SCZO_40 (alias)
          C_43 = SCZO_40 (alias)
Z_41: orig: Z
    def:  Z_41 = SCZO_40 (alias)
SZO_42: orig: SZO
    def:  SZO_42 = SCZO_40 (alias)
C_43: orig: C
    def:  C_43 = SCZO_40 (alias)
v12_44: orig: v12
    def:  v12_44 = Mem33[ds:0x0302:word16] + 0x0001
    uses: Mem45[ds:0x0302:word16] = v12_44
          SZO_46 = cond(v12_44)
Mem45: orig: Mem0
    def:  Mem45[ds:0x0302:word16] = v12_44
SZO_46: orig: SZO
    def:  SZO_46 = cond(v12_44)
    uses: SCZO_47 = SZO_46 (alias)
          Z_48 = SZO_46 (alias)
SCZO_47: orig: SCZO
    def:  SCZO_47 = SZO_46 (alias)
Z_48: orig: Z
    def:  Z_48 = SZO_46 (alias)
// fn0C00_0000
// Return size: 0
void fn0C00_0000(word16 si, word16 di, selector ds)
fn0C00_0000_entry:
	def Mem0
	def fp
	def sp
	def bx
	def si
	def ax
	def ds
	def SCZO
	def Z
	def di
	def SZO
	def C
	def v12
	// succ:  l0C00_0000
l0C00_0000:
	bx_13 = si
	goto l0C00_001A
	// succ:  l0C00_001A
l0C00_0005:
	Mem33[ds:di:word16] = ax_15
	ax_34 = ax_15
	SZO_35 = cond(ax_15)
	Z_36 = SZO_35 (alias)
	C_37 = false
	SCZO_38 = false (alias)
	branch ax_15 != 0x0000 l0C00_0011
	// succ:  l0C00_000B l0C00_0011
l0C00_000B:
	ax_39 = 0xFFFF
	goto l0C00_0024
	// succ:  l0C00_0024
l0C00_0011:
	SCZO_40 = cond(ax_15 - 0x000D)
	Z_41 = SCZO_40 (alias)
	SZO_42 = SCZO_40 (alias)
	C_43 = SCZO_40 (alias)
	branch ax_15 != 0x000D l0C00_001A
	// succ:  l0C00_0016 l0C00_001A
l0C00_0016:
	v12_44 = Mem33[ds:0x0302:word16] + 0x0001
	Mem45[ds:0x0302:word16] = v12_44
	SZO_46 = cond(v12_44)
	SCZO_47 = SZO_46 (alias)
	Z_48 = SZO_46 (alias)
	// succ:  l0C00_001A
l0C00_001A:
	si_14 = PHI(si, si_16, si_16)
	ax_15 = Mem0[ds:si_14:word16]
	si_16 = si_14 + 0x0002
	SCZO_17 = cond(ax_15 - 0x0020)
	Z_18 = SCZO_17 (alias)
	SZO_19 = SCZO_17 (alias)
	C_20 = SCZO_17 (alias)
	branch ax_15 != 0x0020 l0C00_0005
	// succ:  l0C00_0020 l0C00_0005
l0C00_0020:
	ax_27 = si_16
	ax_28 = si_16 - si
	SCZO_29 = cond(ax_28)
	Z_30 = SCZO_29 (alias)
	SZO_31 = SCZO_29 (alias)
	C_32 = SCZO_29 (alias)
	// succ:  l0C00_0024
l0C00_0024:
	C_21 = PHI(C_32, C_37)
	SZO_22 = PHI(SZO_31, SZO_35)
	Z_23 = PHI(Z_30, Z_36)
	SCZO_24 = PHI(SCZO_29, SCZO_38)
	ax_25 = PHI(ax_28, ax_39)
	Mem26[ds:0x0300:word16] = ax_25
	return
	// succ:  fn0C00_0000_exit
fn0C00_0000_exit:
