// fn0C00_0000
// Mem0:Global memory
// fp:Temporary
// cx:Register cx
// wLoc04:Local -0004
// ax:Register ax
// ds:Register ds
// return address size: 2
void fn0C00_0000()
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	cx = 0x0064
	wLoc04 = cx
	call fn0C00_000F (depth: 4;)
	store(Mem0[ds:0x0064:word16]) = ax
	return
	// succ:  2
fn0C00_0000_exit:		// block 2, pred: 1
	// succ: 
// fn0C00_000F
// Mem0:Global memory
// fp:Temporary
// bp:Register bp
// wLoc04:Local -0004
// wArg00:Stack +0000
// ax:Register ax
// SZO:Flags
// Z:Flags
// wLoc06:Local -0006
// dx:Register dx
// dx_ax:Sequence dx:ax
// SCZO:Flags
// return address size: 2
void fn0C00_000F()
fn0C00_000F_entry:		// block 0, pred:
	// succ:  1
l0C00_000F:		// block 1, pred: 0
	wLoc04 = bp
	ax = wArg00
	ax = ax - 0x0001
	SZO = cond(ax)
	branch Test(EQ,Z) l0C00_0026
	// succ:  3 2
l0C00_0026:		// block 2, pred: 1
	ax = 0x0001
	// succ:  4
l0C00_0018:		// block 3, pred: 1
	wLoc06 = ax
	call fn0C00_000F (depth: 6;)
	dx = wArg00
	dx_ax = dx *s ax
	SCZO = cond(dx_ax)
	// succ:  4
l0C00_0029:		// block 4, pred: 2 3
	bp = wLoc04
	return
	// succ:  5
fn0C00_000F_exit:		// block 5, pred: 4
	// succ: 
