// ThrottleControl_seg000C0154.c
// Generated by decompiling ThrottleControl.mot
// using Reko decompiler version 0.12.3.0.

#include "ThrottleControl.h"

// 000C0154: void fn000C0154(Register byte r0h, Register (ptr16 Eq_n) sb)
void fn000C0154(byte r0h, struct Eq_n * sb)
{
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x05);
	((union Eq_n *) 0x043C)->u0 = (byte) __write_bit<word16,byte>(SEQ(r0h, 0x00), 0x00, !!__bit<byte,byte>(*(union Eq_n *) 996, 0x04)) == 0x01 ? 0x41 : 66;
	*(byte *) 0x043D = 0x00;
	word16 wLoc04;
	if (*(union Eq_n *) 0x043C != 0x41)
	{
		fn000C0BBA();
		fn000C0B0A();
		fn000C0BA2();
		fn000C0978();
		fn000C0B92();
		fn000C0A7E();
		fn000C0BE8();
		fn000C0C46();
		fn000C0C52();
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		fn000C0E46();
		fn000C1186(0x01, 0x05);
		*(union Eq_n *) 0x03D8 = *(union Eq_n *) 0x03CA;
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x00));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x01));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x02));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x03));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x04));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x05));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x05));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x06));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x07));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x05));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x06));
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x07));
		fn000C1222(&g_tC0073);
		fn000C1222(&g_tC002D);
		fn000C1222(&g_tC0000);
		fn000C1186(0x01, 44);
		fn000C1222(&g_tC008A);
		fn000C1186(0x05, 0x01);
		while (true)
		{
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x00));
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x01));
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x02));
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x03));
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x04));
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x05));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x05));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x06));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x07));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x05));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x06));
			*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x07));
			if (wLoc04 == 0x01)
			{
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x01);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x02);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x07);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x04);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x03);
				wLoc04 = 0x00;
			}
			else
			{
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x01);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x02);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x07);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x04);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x03);
				wLoc04 = 0x01;
			}
			fn000C1186(0x05, 0x00);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x00)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x01)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x02)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x03)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x04)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x05)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x05)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x06)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x07)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x05)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x06)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x07)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C0);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C2);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C4);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 966);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C8);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03CA);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03CC);
			fn000C1616();
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03CE);
			fn000C1616();
			UART1_putc(0x20);
			fn000C1186(0x09, 0x00);
			Eq_n r0l_n = *(union Eq_n *) 996;
			114 = 141;
			*(union Eq_n *) 0x2177 = r0l_n;
			fn000C13CC();
			UART1_putc(0x20);
			Eq_n r0l_n = *(union Eq_n *) 996;
			114 = 141;
			*(union Eq_n *) 0x2177 = r0l_n;
			fn000C0F06(0x20);
			fn000C13CC();
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x02)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1005, 0x05)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x03)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x04)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
		}
	}
	else
	{
		fn000C0BBA();
		fn000C0A08();
		fn000C0BA2();
		fn000C0978();
		fn000C0B92();
		fn000C098C();
		fn000C0BE8();
		fn000C0C46();
		fn000C0C52();
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		UART1_putc(0x55);
		fn000C0E46();
		fn000C1186(0x01, 0x05);
		fn000C1222(&g_tC012F);
		fn000C1222(&g_tC00E3);
		fn000C1222(&g_tC00C0);
		fn000C1186(0x01, 0x20);
		fn000C1222(&g_tC008A);
		fn000C1186(0x05, 0x01);
		while (true)
		{
			*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x06, !!__bit<byte,byte>(*(union Eq_n *) 1001, 0x06));
			if (wLoc04 == 0x01)
			{
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x01);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x02);
				*(union Eq_n *) 1005 = __set_bit<byte,byte>(*(union Eq_n *) 1005, 0x04);
				*(union Eq_n *) 1005 = __set_bit<byte,byte>(*(union Eq_n *) 1005, 0x06);
				wLoc04 = 0x00;
			}
			else
			{
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x01);
				*(union Eq_n *) 1001 = __set_bit<byte,byte>(*(union Eq_n *) 1001, 0x02);
				*(union Eq_n *) 1005 = __set_bit<byte,byte>(*(union Eq_n *) 1005, 0x04);
				*(union Eq_n *) 1005 = __set_bit<byte,byte>(*(union Eq_n *) 1005, 0x06);
				wLoc04 = 0x01;
			}
			fn000C1186(0x05, 0x00);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x05)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x06)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x07)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x03)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x04)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C0);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C2);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C4);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 966);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03C8);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			fn000C0F06(*(union Eq_n *) 0x03CA);
			fn000C1616();
			UART1_putc(0x20);
			UART1_putc(0x20);
			Eq_n r1_n = fn000C1186(0x09, 0x00);
			Eq_n r0l_n = *(union Eq_n *) 996;
			114 = 141;
			*(union Eq_n *) 0x2177 = r0l_n;
			if (*(byte *) 0xF500 == 0x00)
				sb->b00F5 = 0x0A;
			*(byte *) 49525 &= r0l_n;
			__break();
			UART1_putc(r1_n);
			Eq_n r0l_n = *(union Eq_n *) 996;
			114 = 141;
			*(union Eq_n *) 0x2177 = r0l_n;
			fn000C0F06(r1_n);
			fn000C13CC();
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc((uint16) ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 0x03F0, 0x02)) == 0x01 ? 0x31 : 0x30));
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			UART1_putc(0x20);
			if ((byte) __write_bit<word16,byte>(0x00, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1001, 0x06)) == 0x01)
				UART1_putc(0x31);
			else
				UART1_putc(0x30);
		}
	}
}

// 000C0978: void fn000C0978()
// Called from:
//      fn000C0154
void fn000C0978()
{
	*(union Eq_n *) 0x03D4 |= 0x01;
	((union Eq_n *) 0x03D6)->u1 = 88;
	*(byte *) 0x03D7 = 0x23;
}

// 000C098C: void fn000C098C()
// Called from:
//      fn000C0154
void fn000C098C()
{
	*(byte *) 0x4E = 0x00;
	*(byte *) 0x5D = 0x00;
	*(byte *) 0x5E = 0x00;
	*(byte *) 0x5F = 0x00;
	*(byte *) 0x44 = 0x00;
	*(byte *) 0x49 = 0x00;
	*(byte *) 0x48 = 0x00;
	*(byte *) 0x52 = 0x00;
	*(byte *) 0x51 = 0x00;
	*(byte *) 0x54 = 0x01;
	*(byte *) 0x53 = 0x00;
	*(byte *) 0x55 = 0x04;
	*(byte *) 0x56 = 0x00;
	*(byte *) 0x57 = 0x00;
	*(byte *) 88 = 0x00;
	*(byte *) 0x59 = 0x00;
	*(byte *) 0x5A = 0x00;
	*(byte *) 0x5B = 0x00;
	*(byte *) 0x5C = 0x00;
	*(byte *) 0x47 = 0x00;
	*(byte *) 0x46 = 0x00;
	*(byte *) 0x45 = 0x00;
	*(union Eq_n *) 0x01DF |= 0xC0;
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x01);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x02);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x03);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x04);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x05);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x03);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x04);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x05);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x01);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x00);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x02);
}

// 000C0A08: void fn000C0A08()
// Called from:
//      fn000C0154
void fn000C0A08()
{
	*(byte *) 994 = 0x00;
	*(byte *) 0x03E3 = 0x00;
	*(byte *) 998 = 0x00;
	*(byte *) 999 = 0x00;
	*(byte *) 1002 = 0x40;
	*(byte *) 1003 = 0x00;
	*(byte *) 0x03EE = 0x88;
	*(byte *) 1007 = 0x00;
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x02);
	*(byte *) 1011 = 0x00;
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x02);
	*(byte *) 1014 = 0x00;
	*(union Eq_n *) 991 = __set_bit<byte,byte>(*(union Eq_n *) 991, 0x07);
	*(byte *) 1015 = 0x00;
	*(byte *) 1018 = 0x00;
	*(byte *) 1019 = 0x00;
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x00);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x01);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x02);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x03);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x04);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x05);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x06);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x07);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x00);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x01);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x02);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x03);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x04);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x05);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x06);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x07);
}

// 000C0A7E: void fn000C0A7E()
// Called from:
//      fn000C0154
void fn000C0A7E()
{
	*(byte *) 0x4E = 0x00;
	*(byte *) 0x5D = 0x01;
	*(byte *) 0x5E = 0x02;
	*(byte *) 0x5F = 0x02;
	*(byte *) 0x44 = 0x03;
	*(byte *) 0x49 = 0x03;
	*(byte *) 0x48 = 0x03;
	*(byte *) 0x52 = 0x00;
	*(byte *) 0x51 = 0x00;
	*(byte *) 0x54 = 0x01;
	*(byte *) 0x53 = 0x00;
	*(byte *) 0x55 = 0x04;
	*(byte *) 0x56 = 0x01;
	*(byte *) 0x57 = 0x03;
	*(byte *) 88 = 0x03;
	*(byte *) 0x59 = 0x01;
	*(byte *) 0x5A = 0x01;
	*(byte *) 0x5B = 0x03;
	*(byte *) 0x5C = 0x01;
	*(byte *) 0x47 = 0x01;
	*(byte *) 0x46 = 0x01;
	*(byte *) 0x45 = 0x01;
	*(union Eq_n *) 0x01DF |= 0xC0;
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x01);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x02);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x03);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x04);
	*(union Eq_n *) 0x01DF = __set_bit<byte,byte>(*(union Eq_n *) 0x01DF, 0x05);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x03);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x04);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x05);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x01);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x00);
	*(union Eq_n *) 0x01CF = __set_bit<byte,byte>(*(union Eq_n *) 0x01CF, 0x02);
}

// 000C0B0A: void fn000C0B0A()
// Called from:
//      fn000C0154
void fn000C0B0A()
{
	*(byte *) 997 = ~0x00;
	*(byte *) 1000 = ~0x00;
	*(byte *) 994 = 0x00;
	*(byte *) 0x03E3 = 0x00;
	*(byte *) 998 = 0x00;
	*(byte *) 999 = ~0x00;
	*(byte *) 1002 = ~0x00;
	*(byte *) 1003 = ~0x00;
	*(byte *) 0x03EE = 0x88;
	*(byte *) 1007 = 0x00;
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x02);
	*(byte *) 1011 = 0x00;
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x02);
	*(byte *) 1014 = 0x00;
	*(union Eq_n *) 991 = __set_bit<byte,byte>(*(union Eq_n *) 991, 0x07);
	*(byte *) 1015 = 0x00;
	*(byte *) 1018 = 0x00;
	*(byte *) 1019 = 0x00;
	*(byte *) 997 = ~0x00;
	*(byte *) 1000 = ~0x00;
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x00);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x01);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x02);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x03);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x04);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x05);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x06);
	*(union Eq_n *) 1020 = __set_bit<byte,byte>(*(union Eq_n *) 1020, 0x07);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x00);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x01);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x02);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x03);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x04);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x05);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x06);
	*(union Eq_n *) 1021 = __set_bit<byte,byte>(*(union Eq_n *) 1021, 0x07);
}

// 000C0B92: void fn000C0B92()
// Called from:
//      fn000C0154
void fn000C0B92()
{
	*(union Eq_n *) 988 = __set_bit<byte,byte>(*(union Eq_n *) 988, 0x00);
	((union Eq_n *) 0x03D8)->u2 = 0x00;
	*(union Eq_n *) 988 = __set_bit<byte,byte>(*(union Eq_n *) 988, 0x01);
	*(byte *) 0x03DA = 0x00;
}

// 000C0BA2: void fn000C0BA2()
// Called from:
//      fn000C0154
void fn000C0BA2()
{
	*(byte *) 0x03A8 = 0x05;
	*(byte *) 0x03AC = 0x18;
	*(union Eq_n *) 0x03AD |= 0x04;
	*(byte *) 0x03A9 = 0x19;
}

// 000C0BBA: void fn000C0BBA()
// Called from:
//      fn000C0154
void fn000C0BBA()
{
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x00);
	*(union Eq_n *) 0x06 = __set_bit<byte,byte>(*(union Eq_n *) 0x06, 0x07);
	*(union Eq_n *) 0x07 = __set_bit<byte,byte>(*(union Eq_n *) 0x07, 0x06);
	*(union Eq_n *) 0x07 = __set_bit<byte,byte>(*(union Eq_n *) 0x07, 0x07);
	*(union Eq_n *) 0x06 = __set_bit<byte,byte>(*(union Eq_n *) 0x06, 0x06);
	*(union Eq_n *) 0x1C = __set_bit<byte,byte>(*(union Eq_n *) 0x1C, 0x02);
	*(union Eq_n *) 0x1C = __set_bit<byte,byte>(*(union Eq_n *) 0x1C, 0x01);
	*(union Eq_n *) 0x1C = __set_bit<byte,byte>(*(union Eq_n *) 0x1C, 0x00);
	*(union Eq_n *) 0x1C = __set_bit<byte,byte>(*(union Eq_n *) 0x1C, 0x07);
	*(union Eq_n *) 0x0A = __set_bit<byte,byte>(*(union Eq_n *) 0x0A, 0x00);
	*(word16 *) 0x043A = 0x00;
}

// 000C0BE8: void fn000C0BE8()
// Called from:
//      fn000C0154
void fn000C0BE8()
{
	*(byte *) 0x0396 = 0x40;
	*(byte *) 919 = 0x00;
	*(byte *) 0x0398 = 0x00;
	*(byte *) 0x0399 = 0x00;
	*(byte *) 922 = 0x00;
	*(byte *) 0x039B = 0x00;
	*(byte *) 0x039C = 0x00;
	*(byte *) 0x039D = 0x00;
	*(byte *) 0x01DB = 0x00;
	*(byte *) 0x01DC = 0x00;
	*(byte *) 0x01DD = 0x00;
	*(word16 *) 0x0386 = 99;
	*(word16 *) 0x0388 = ~0x00;
	*(word16 *) 0x038A = ~0x00;
	*(word16 *) 0x038C = ~0x00;
	*(word16 *) 0x038E = ~0x00;
	*(word16 *) 0x0390 = ~0x00;
	*(word16 *) 0x0392 = ~0x00;
	*(word16 *) 0x0394 = ~0x00;
	*(word16 *) 464 = ~0x00;
	*(word16 *) 466 = ~0x00;
	*(word16 *) 0x01D4 = ~0x00;
	*(union Eq_n *) 900 |= 0x04;
}

// 000C0C46: void fn000C0C46()
// Called from:
//      fn000C0154
void fn000C0C46()
{
	*(union Eq_n *) 0x0380 |= 0x01;
}

// 000C0C52: void fn000C0C52()
// Called from:
//      fn000C0154
void fn000C0C52()
{
	*(union Eq_n *) 0x03D6 |= 0x40;
}

// 000C0C5E: void fn000C0C5E()
void fn000C0C5E()
{
	__return_from_interrupt();
}

// 000C0C66: void fn000C0C66()
void fn000C0C66()
{
	__return_from_interrupt();
}

// 000C0C6E: void fn000C0C6E()
void fn000C0C6E()
{
	if (*(union Eq_n *) 0x043C != 0x41)
	{
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x00));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x02));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x04));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x01));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x03));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x05));
	}
	__return_from_interrupt();
}

// 000C0CB4: void fn000C0CB4()
void fn000C0CB4()
{
	if (*(union Eq_n *) 0x043C != 0x41)
	{
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x00));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x02));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x04, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x04));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x01));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x03));
		*(byte *) 1000 = __write_bit<byte,byte>(*(byte *) 1000, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1016, 0x05));
	}
	__return_from_interrupt();
}

// 000C0CFA: void fn000C0CFA()
void fn000C0CFA()
{
	if (*(union Eq_n *) 0x043C != 0x41)
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x00, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x05));
	__return_from_interrupt();
}

// 000C0D13: void fn000C0D13()
void fn000C0D13()
{
	fn000764EB();
	byte v4_n = *(byte *) 0x4104 - 0x3C;
	*(byte *) 0x4104 = v4_n;
	__break();
	if (v4_n != 0x00)
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x01, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x06));
	__return_from_interrupt();
}

// 000C0D2A: void fn000C0D2A()
void fn000C0D2A()
{
	if (*(union Eq_n *) 0x043C != 0x41)
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x02, !!__bit<byte,byte>(*(union Eq_n *) 993, 0x07));
	__return_from_interrupt();
}

// 000C0D42: void fn000C0D42()
void fn000C0D42()
{
	__return_from_interrupt();
}

// 000C0DB4: void fn000C0DB4()
void fn000C0DB4()
{
	if (*(union Eq_n *) 0x043C != 0x41)
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x03, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x05));
	__return_from_interrupt();
}

// 000C0DCC: void fn000C0DCC()
void fn000C0DCC()
{
	__return_from_interrupt();
}

// 000C0DD4: void fn000C0DD4()
void fn000C0DD4()
{
	__return_from_interrupt();
}

// 000C0DDC: void fn000C0DDC()
void fn000C0DDC()
{
	if (*(union Eq_n *) 0x043C != 0x41)
		*(byte *) 997 = __write_bit<byte,byte>(*(byte *) 997, 0x05, !!__bit<byte,byte>(*(union Eq_n *) 1017, 0x07));
	__return_from_interrupt();
}

// 000C0DF4: void fn000C0DF4()
void fn000C0DF4()
{
	__return_from_interrupt();
}

// 000C0DFC: void fn000C0DFC()
void fn000C0DFC()
{
	__return_from_interrupt();
}

// 000C0E04: void fn000C0E04()
void fn000C0E04()
{
	__return_from_interrupt();
}

// 000C0E0C: void fn000C0E0C()
void fn000C0E0C()
{
	__return_from_interrupt();
}

// 000C0E14: void fn000C0E14()
void fn000C0E14()
{
	*(union Eq_n *) 0x0412 = *(union Eq_n *) 0x03C0;
	*(union Eq_n *) 0x0414 = *(union Eq_n *) 0x03C2;
	*(union Eq_n *) 0x0416 = *(union Eq_n *) 0x03C4;
	*(union Eq_n *) 0x0418 = *(union Eq_n *) 966;
	*(union Eq_n *) 1050 = *(union Eq_n *) 0x03C8;
	*(union Eq_n *) 0x041C = *(union Eq_n *) 0x03CA;
	*(union Eq_n *) 0x041E = *(union Eq_n *) 0x03CC;
	*(union Eq_n *) 0x0420 = *(union Eq_n *) 0x03CE;
}

// 000C0E46: void fn000C0E46()
// Called from:
//      fn000C0154
void fn000C0E46()
{
	UART1_putc(0x1B);
	UART1_putc(0x5B);
	UART1_putc(0x31);
	UART1_putc(0x3B);
	UART1_putc(0x32);
	UART1_putc(0x34);
	UART1_putc(114);
	UART1_putc(0x1B);
	UART1_putc(0x5B);
	UART1_putc(0x30);
	UART1_putc(0x6D);
	UART1_putc(0x1B);
	UART1_putc(0x5B);
	UART1_putc(0x32);
	UART1_putc(0x4A);
}

// 000C0EB0: void fn000C0EB0(Register uint16 r1)
void fn000C0EB0(uint16 r1)
{
	uint32 r2_r0_n = (uint32) r1;
	uint16 v12_n = r1 - (r2_r0_n /u 100) *s32 100;
	uint32 r2_r0_n = (uint32) v12_n;
	*(union Eq_n *) 0x0424 = v12_n - (r2_r0_n /u 0x0A) *s32 0x0A + 0x30;
	*(union Eq_n *) 0x0426 = r2_r0_n /u 0x0A + 0x30;
	*(union Eq_n *) 0x0428 = r2_r0_n /u 100 + 0x30;
}

// 000C0F06: void fn000C0F06(Register Eq_n r1)
// Called from:
//      fn000C0154
void fn000C0F06(Eq_n r1)
{
	uint32 r2_r0_n = (uint32) r1;
	uint16 v12_n = r1 - (r2_r0_n /u 10000) *s32 10000;
	uint32 r2_r0_n = (uint32) v12_n;
	uint16 v15_n = v12_n - (r2_r0_n /u 1000) *s32 1000;
	uint32 r2_r0_n = (uint32) v15_n;
	uint16 v17_n = v15_n - (r2_r0_n /u 100) *s32 100;
	uint32 r2_r0_n = (uint32) v17_n;
	*(union Eq_n *) 0x0424 = v17_n - (r2_r0_n /u 0x0A) *s32 0x0A + 0x30;
	*(union Eq_n *) 0x0426 = r2_r0_n /u 0x0A + 0x30;
	*(union Eq_n *) 0x0428 = r2_r0_n /u 100 + 0x30;
	*(union Eq_n *) 1066 = r2_r0_n /u 1000 + 0x30;
	*(union Eq_n *) 0x042C = r2_r0_n /u 10000 + 0x30;
}

// 000C0F9E: void fn000C0F9E(Register (ptr16 Eq_n) sb, Stack Eq_n dwArg03)
void fn000C0F9E(struct Eq_n * sb, Eq_n dwArg03)
{
	word16 r0_n = (word16) fn000C17B4(dwArg03, sb);
	Eq_n v13_v11_n = dwArg03 - fn000C1802(0x9680, 0x98, sb);
	word16 r0_n = (word16) fn000C17B4(v13_v11_n, sb);
	Eq_n v17_v16_n = v13_v11_n - fn000C1802(0x4240, 0x0F, sb);
	word16 r0_n = (word16) fn000C17B4(v17_v16_n, sb);
	Eq_n v21_v20_n = v17_v16_n - fn000C1802(34464, 0x01, sb);
	word16 r0_n = (word16) fn000C17B4(v21_v20_n, sb);
	Eq_n v25_v24_n = v21_v20_n - fn000C1802(10000, 0x00, sb);
	word16 r0_n = (word16) fn000C17B4(v25_v24_n, sb);
	Eq_n v29_v28_n = v25_v24_n - fn000C1802(1000, 0x00, sb);
	word16 r0_n = (word16) fn000C17B4(v29_v28_n, sb);
	Eq_n v33_v32_n = v29_v28_n - fn000C1802(100, 0x00, sb);
	word16 r0_n = (word16) fn000C17B4(v33_v32_n, sb);
	*(union Eq_n *) 0x0424 = (word16) (v33_v32_n - fn000C1802(0x0A, 0x00, sb)) + 0x30;
	*(union Eq_n *) 0x0426 = r0_n + 0x30;
	*(union Eq_n *) 0x0428 = r0_n + 0x30;
	*(union Eq_n *) 1066 = r0_n + 0x30;
	*(union Eq_n *) 0x042C = r0_n + 0x30;
	*(union Eq_n *) 1070 = r0_n + 0x30;
	*(union Eq_n *) 0x0430 = r0_n + 0x30;
	*(union Eq_n *) 0x0432 = r0_n + 0x30;
}

// 000C1186: Register uint16 fn000C1186(Register uint16 r1, Register uint16 r2)
// Called from:
//      fn000C0154
uint16 fn000C1186(uint16 r1, uint16 r2)
{
	uint16 wLoc0A_n = r1;
	uint16 wLoc04_n = r2;
	if (r1 > 0x18)
		wLoc0A_n = 0x18;
	uint32 r2_r0_n = (uint32) wLoc0A_n;
	uint16 v15_n = wLoc0A_n - (r2_r0_n /u 0x0A) *s32 0x0A;
	if (r2 > 0x4F)
		wLoc04_n = 0x4F;
	UART1_putc(0x1B);
	UART1_putc(0x5B);
	UART1_putc(r2_r0_n /u 0x0A + 0x30);
	UART1_putc(v15_n + 0x30);
	UART1_putc(0x3B);
	uint32 r2_r0_n = (uint32) wLoc04_n;
	UART1_putc(r2_r0_n /u 0x0A + 0x30);
	UART1_putc(wLoc04_n - (r2_r0_n /u 0x0A) *s32 0x0A + 0x30);
	UART1_putc(0x48);
	return 0x48;
}

// 000C1222: void fn000C1222(Stack (ptr32 Eq_n) dwArg03)
// Called from:
//      fn000C0154
void fn000C1222(struct Eq_n * dwArg03)
{
	cup16 wLoc04_n = 0x01;
	struct Eq_n * dwArg03_n = dwArg03;
	while (true)
	{
		word16 wArg03_n = (word16) dwArg03_n;
		if (wLoc04_n > 100)
			break;
		switch (dwArg03_n->b0000)
		{
		case 0x7E:
			if (dwArg03_n->b0001 == 0x4E)
			{
				UART1_putc(0x0A);
				UART1_putc(0x0D);
			}
			if (dwArg03_n->b0001 == 0x7E)
				UART1_putc(0x7E);
			if (dwArg03_n->b0001 == 66)
			{
				UART1_putc(0x1B);
				UART1_putc(0x5B);
				UART1_putc(0x31);
				UART1_putc(0x6D);
			}
			if (dwArg03_n->b0001 == 0x55)
			{
				UART1_putc(0x1B);
				UART1_putc(0x5B);
				UART1_putc(0x34);
				UART1_putc(0x6D);
			}
			if (dwArg03_n->b0001 == 0x52)
			{
				UART1_putc(0x1B);
				UART1_putc(0x5B);
				UART1_putc(55);
				UART1_putc(0x6D);
			}
			if (dwArg03_n->b0001 == 0x4F)
			{
				UART1_putc(0x1B);
				UART1_putc(0x5B);
				UART1_putc(0x30);
				UART1_putc(0x6D);
			}
			if (dwArg03_n->b0001 == 0x53)
			{
				UART1_putc(0x1B);
				UART1_putc(0x5B);
				UART1_putc(0x35);
				UART1_putc(0x6D);
			}
			dwArg03_n = SEQ(SLICE(&dwArg03_n->b0001 + 1, word16, 16), wArg03_n + 0x02);
			break;
		case 0x00:
			wLoc04_n = 100;
			break;
		default:
			UART1_putc((uint16) dwArg03_n->b0000);
			dwArg03_n = SEQ(SLICE(&dwArg03_n->b0001, word16, 16), wArg03_n + 0x01);
			break;
		}
		++wLoc04_n;
	}
}

// 000C1372: Register byte UART1_putc(Register Eq_n r1)
// Called from:
//      fn000C0154
//      fn000C0E46
//      fn000C1186
//      fn000C1222
//      fn000C1392
//      fn000C13CC
//      fn000C1432
//      fn000C14A0
//      fn000C14C4
//      fn000C14F0
//      fn000C155E
//      fn000C158A
//      fn000C15B6
//      fn000C1616
//      fn000C1634
//      fn000C166E
//      fn000C1684
//      fn000C16B0
//      fn000C1730
//      fn000C175C
//      fn000C177A
//      fn000C1790
byte UART1_putc(Eq_n r1)
{
	while (!!__bit<word16,byte>((uint16) *(union Eq_n *) 0x03AD, 0x01))
		;
	*(union Eq_n *) 0x03AD |= 0x01;
	*(union Eq_n *) 0x03AA = r1;
	return 0x00;
}

// 000C1392: void fn000C1392()
void fn000C1392()
{
	UART1_putc(*(union Eq_n *) 0x0432);
	UART1_putc(*(union Eq_n *) 0x0430);
	UART1_putc(*(union Eq_n *) 1070);
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C13CC: void fn000C13CC()
// Called from:
//      fn000C0154
void fn000C13CC()
{
	if (*(union Eq_n *) 0x042C == 0x30)
		((union Eq_n *) 0x042C)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && *((union Eq_n *) 1066) == 0x30)
		((union Eq_n *) 1066)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && (*((union Eq_n *) 1066) == 0x20 && *((union Eq_n *) 0x0428) == 0x30))
		((union Eq_n *) 0x0428)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1432: void fn000C1432()
void fn000C1432()
{
	if (*(union Eq_n *) 0x042C == 0x30)
		((union Eq_n *) 0x042C)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && *((union Eq_n *) 1066) == 0x30)
		((union Eq_n *) 1066)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && (*((union Eq_n *) 1066) == 0x20 && *((union Eq_n *) 0x0428) == 0x30))
		((union Eq_n *) 0x0428)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C14A0: void fn000C14A0()
void fn000C14A0()
{
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C14C4: void fn000C14C4()
void fn000C14C4()
{
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C14F0: void fn000C14F0()
void fn000C14F0()
{
	if (*(union Eq_n *) 0x042C == 0x30)
		((union Eq_n *) 0x042C)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && *((union Eq_n *) 1066) == 0x30)
		((union Eq_n *) 1066)->u0 = 0x20;
	if (*(union Eq_n *) 0x042C == 0x20 && (*((union Eq_n *) 1066) == 0x20 && *((union Eq_n *) 0x0428) == 0x30))
		((union Eq_n *) 0x0428)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C155E: void fn000C155E()
void fn000C155E()
{
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C158A: void fn000C158A()
void fn000C158A()
{
	UART1_putc(*(union Eq_n *) 0x042C);
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C15B6: void fn000C15B6()
void fn000C15B6()
{
	if (*(union Eq_n *) 1066 == 0x30)
		((union Eq_n *) 1066)->u0 = 0x20;
	if (*(union Eq_n *) 1066 == 0x20 && *((union Eq_n *) 0x0428) == 0x30)
		((union Eq_n *) 0x0428)->u0 = 0x20;
	if (*(union Eq_n *) 1066 == 0x20 && (*((union Eq_n *) 0x0428) == 0x20 && *((union Eq_n *) 0x0426) == 0x30))
		((union Eq_n *) 0x0426)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1616: void fn000C1616()
// Called from:
//      fn000C0154
void fn000C1616()
{
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1634: void fn000C1634()
void fn000C1634()
{
	if (*(union Eq_n *) 0x0428 == 0x30)
		((union Eq_n *) 0x0428)->u0 = 0x20;
	if (*(union Eq_n *) 0x0428 == 0x20 && *((union Eq_n *) 0x0426) == 0x30)
		((union Eq_n *) 0x0426)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C166E: void fn000C166E()
void fn000C166E()
{
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1684: void fn000C1684()
void fn000C1684()
{
	if (*(union Eq_n *) 0x0428 == 0x30)
		((union Eq_n *) 0x0428)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C16B0: void fn000C16B0()
void fn000C16B0()
{
	if (*(union Eq_n *) 1066 == 0x30)
		((union Eq_n *) 1066)->u0 = 0x20;
	if (*(union Eq_n *) 1066 == 0x20 && *((union Eq_n *) 0x0428) == 0x30)
		((union Eq_n *) 0x0428)->u0 = 0x20;
	if (*(union Eq_n *) 1066 == 0x2D && *((union Eq_n *) 0x0428) == 0x30)
	{
		((union Eq_n *) 1066)->u0 = 0x20;
		((union Eq_n *) 0x0428)->u0 = 0x2D;
	}
	if (*(union Eq_n *) 1066 == 0x2B && *((union Eq_n *) 0x0428) == 0x30)
	{
		((union Eq_n *) 1066)->u0 = 0x20;
		((union Eq_n *) 0x0428)->u0 = 0x2B;
	}
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1730: void fn000C1730()
void fn000C1730()
{
	if (*(union Eq_n *) 0x0428 == 0x30)
		((union Eq_n *) 0x0428)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C175C: void fn000C175C()
void fn000C175C()
{
	if (*(union Eq_n *) 0x0426 == 0x30)
		((union Eq_n *) 0x0426)->u0 = 0x20;
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C177A: void fn000C177A()
void fn000C177A()
{
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C1790: void fn000C1790()
void fn000C1790()
{
	UART1_putc(*(union Eq_n *) 1066);
	UART1_putc(*(union Eq_n *) 0x0428);
	UART1_putc(*(union Eq_n *) 0x0426);
	UART1_putc(0x2E);
	UART1_putc(*(union Eq_n *) 0x0424);
}

// 000C17B4: Sequence Eq_n fn000C17B4(Sequence Eq_n r2_r0, Register (ptr16 Eq_n) sb)
// Called from:
//      fn000C0F9E
Eq_n fn000C17B4(Eq_n r2_r0, struct Eq_n * sb)
{
	Eq_n r2 = SLICE(r2_r0, word16, 16);
	word16 r0 = (word16) r2_r0;
	uint16 a0_n = 0x00;
	ci16 a1_n = 0x00;
	uint16 r1_n = sb->w000B;
	Eq_n r3_n;
	r3_n.u0 = sb->t000D.u0;
	Eq_n r2_r0_n;
	if (r3_n == 0x00)
	{
		if (r2 != 0x00)
		{
			uint32 r2_r0_n = (uint32) r2;
			r2 = r2_r0_n % r1_n;
			r3_n = r2_r0_n /u r1_n;
		}
		r2_r0_n = SEQ(r3_n, SEQ(r2, r0) /u r1_n);
	}
	else
	{
		Eq_n r2_r0_n = r2_r0;
		uint32 r3_r1_n = SEQ(r3_n, r1_n);
		uint32 r3_r1_n = SEQ(r3_n, r1_n);
		if (r3_n >= 0x00)
		{
			cui16 r1_n;
			do
			{
				r1_n = (word16) r3_r1_n;
				r2_r0_n = r2_r0;
				r3_r1_n = r3_r1_n;
				if (r2 <= SLICE(r3_r1_n, word16, 16))
					break;
				ui16 r3_n = SLICE(r3_r1_n << 0x01, word16, 16);
				++a1_n;
				r2_r0_n = r2_r0;
				r3_r1_n = SEQ(r3_n, r1_n << 0x01);
				r3_r1_n = SEQ(r3_n, r1_n << 0x01);
			} while (r1_n << 0x01 >= 0x00);
		}
		do
		{
			Eq_n r2_r0_n = r2_r0_n - r3_r1_n;
			cup16 r2_n = SLICE(r2_r0_n, word16, 16);
			Eq_n C_n = cond(r2_n) & 0x01;
			if (r2_n < 0x00)
			{
				r2_r0_n = (word32) r2_r0_n + r3_r1_n;
				C_n.u0 = 0x00;
			}
			a0_n = __rcl<word16,int16>(a0_n, 1, C_n);
			--a1_n;
			r2_r0_n = r2_r0_n;
			r3_r1_n >>= 0x01;
		} while (a1_n >= 0x00);
		r2_r0_n.u1 = (uint32) a0_n;
	}
	return r2_r0_n;
}

