// fn0C00_0000
void fn0C00_0000(I2 ax)
fn0C00_0000_entry:		// block 0, pred:
	branch ax < 0000
	// succ:  3 1
l0C00_0012:		// block 1, pred: 0
	cl_10 = 01
	branch ax >= FFF4
	// succ:  2 5
l0C00_0019:		// block 2, pred: 1
	ax = FFF4
	// succ:  5
l0C00_0005:		// block 3, pred: 0
	cl_10 = 00
	branch ax <= 000C
	// succ:  4 5
l0C00_000C:		// block 4, pred: 3
	ax = 000C
	// succ:  5
l0C00_001C:		// block 5, pred: 2 1 4 3
	g_w00000300 = ax
	g_b00000302 = cl_10
	return
	// succ: 
-----------
fn0C00_0000()
{
    if (ax < 0000)
        {
            cl_10 = 01;
            if (ax < FFF4)
                ax = FFF4;
        }
    else
        {
            cl_10 = 00;
            if (ax > 000C)
                ax = 000C;
        }
    g_w00000300 = ax;
    g_b00000302 = cl_10;
    return;
}
===========
