// fn0C00_0000
void fn0C00_0000(word16 ax, segment ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	branch ax != 0x0000
	// succ:  2 3
l0C00_0005:		// block 2, pred: 1 3
	ax = ax - 0x0003 >> 0x0001
	// succ:  3
l0C00_000A:		// block 3, pred: 2 1
	ax = (word16) (ax *s ax) | 0x0000
	branch ax != 0x0000
	// succ:  4 2
l0C00_0011:		// block 4, pred: 3
	store(Mem25[ds:0x0200:word16]) = ax
	return
	// succ:  5
fn0C00_0000_exit:		// block 5, pred: 4
	// succ: 
Header 0, blocks: 0 1
Header 2, blocks: 2 3 4 5
Interval of block 0: Header 0, blocks: 0 1
Interval of block 1: Header 0, blocks: 0 1
Interval of block 2: Header 2, blocks: 2 3 4 5
Interval of block 3: Header 2, blocks: 2 3 4 5
Interval of block 4: Header 2, blocks: 2 3 4 5
Interval of block 5: Header 2, blocks: 2 3 4 5

