// fn0C00_0000
void fn0C00_0000(word16 bx, word16 si, word16 di, segment ds)
fn0C00_0000_entry:		// block 0, pred:
	// succ:  1
l0C00_0000:		// block 1, pred: 0
	word16 dx_12 = 0x0004
	// succ:  2
l0C00_0003:		// block 2, pred: 1 4
	word16 cx_22 = 0x0004
	// succ:  3
l0C00_0006:		// block 3, pred: 2 3
	store(Mem31[ds:di:word32]) = Mem27[ds:si:word32] + Mem27[ds:bx:word32]
	si = si + 0x0004
	bx = bx + 0x0004
	di = di + 0x0004
	cx_22 = cx_22 - 0x0001
	branch cx_22 != 0x0000
	// succ:  4 3
l0C00_001A:		// block 4, pred: 3
	dx_12 = dx_12 - 0x0001
	branch dx_12 != 0x0000
	// succ:  5 2
l0C00_001D:		// block 5, pred: 4
	return
	// succ:  6
fn0C00_0000_exit:		// block 6, pred: 5
	// succ: 
Header 0, blocks: 0 1
Header 2, blocks: 2
Header 3, blocks: 3 4 5 6
Interval of block 0: Header 0, blocks: 0 1
Interval of block 1: Header 0, blocks: 0 1
Interval of block 2: Header 2, blocks: 2
Interval of block 3: Header 3, blocks: 3 4 5 6
Interval of block 4: Header 3, blocks: 3 4 5 6
Interval of block 5: Header 3, blocks: 3 4 5 6
Interval of block 6: Header 3, blocks: 3 4 5 6

