using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Decompiler.Arch.Z80
{
    public enum Opcode
    {
        illegal = 0,

        // i8080 opcodes
        aci,
        adi,
        ana,
        cma,
        cmc,
        cmp,
        dad,
        dcr,
        dcx,
        inr,
        inx,
        jc,
        jm,
        jmp,
        jnc,
        jnz,
        jpe,
        jpo,
        jz,
        lda,
        ldax,
        lhld,
        lxi,
        mov,
        mvi,
        ora,
        pchl,
        shld,
        sphl,
        sta,
        stax,
        sbb,
        sbi,
        stc,
        sui,
        xra,

        // Z80 opcodes
        and,
        bit,
        call,
        ccf,
        cp,
        cpd,
        cpdr,
        cpi,
        cpir,
        cpl,
        dec,
        djnz,
        ex,
        ex_af,
        exx,
        jr,
        inc,
        ld,
        ldd,
        lddr,
        ldi,
        ldir,
        im,
        @in,
        ind,
        indr,
        ini,
        inir,
        neg,
        or,
        otdr,
        otir,
        @out,
        outd,
        outi,
        outr,
        pop,
        push,
        res,
        ret,
        reti,
        retn,
        rla,
        rl,
        rlc,
        rlca,
        rld,
        rra,
        rr,
        rrc,
        rrd,
        rrca,
        rst,
        sbc,
        scf,
        sla,
        srl,
        sra,
        set,
        swap,
        xor,

        // Shared opcodes
        adc,
        add,
        daa,
        di,
        ei,
        hlt,
        jp,
        nop,
        sub,
    }
}
