// VCExeSample.c
// Generated by decompiling D:\dev\uxmal\reko\master\subjects\PE-x86\VCExeSample\VCExeSample.exe
// using Decompiler version 0.6.0.0.

#include "VCExeSample.h"

char g_str4020C0[] = "test123";
char g_str4020C8[] = "%s %d %s %f";
char g_str4020D4[] = "3";
char g_str4020D8[] = "1";
char g_str4020DC[] = "7";
char g_str4020E0[] = "5";

