// FactorialMock
// Mem0:Global memory
// fp:Temporary
// r2:Local -0004
// r3:Local -0008
// Z:Flags
// r1:Local -000C
// return address size: 0
void FactorialMock()
FactorialMock_entry:		// block 0, pred:
	// succ:  1
l1:		// block 1, pred: 0
	r3 = 0x00000001
	// succ:  2
test:		// block 2, pred: 1 5
	Z = cond(r2 - 0x00000000)
	branch Test(EQ,Z) done
	// succ:  5 3
done:		// block 3, pred: 2
	return r3
	// succ:  4
FactorialMock_exit:		// block 4, pred: 3
	// succ: 
l2:		// block 5, pred: 2
	r3 = r3 *s r2
	r2 = r2 - 0x00000001
	// succ:  2
