// FactorialMock
// Mem0:Global memory
// fp:Temporary
// r2:Local -0004
// r3:Local -0008
// Z:Flags
// r1:Local -000C
// return address size: 0
void FactorialMock()
FactorialMock_entry:
	goto l1
	// succ:  l1
done:
	return r3
	// succ:  FactorialMock_exit
l1:
	r3 = 0x00000001
	goto test
	// succ:  test
l2:
	r3 = r3 *s r2
	r2 = r2 - 0x00000001
	// succ:  test
test:
	Z = cond(r2 - 0x00000000)
	branch Test(EQ,Z) done
	goto l2
	// succ:  l2 done
FactorialMock_exit:
